{1}{}{DEVIDER@ Крафт на коленке [диапазон 2-1000]: @@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{2}{}{DEVIDER@ Дикарский [ИНТ < 5, диапазон 3-100]: @@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{3}{}{PID_SHARPENED_POLE@Вжик-вжик, и готово!@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@@PID_SHARPENED_POLE 1@script fix_boy@fix_Tribal}
{4}{}{PID_FIREWOOD@Чем вам доска не полено?@@@PID_WOOD_PLANK 1@@PID_FIREWOOD 1@script fix_boy@fix_Tribal}
{5}{}{PID_CLUB@Как оказалось, сделать устрашающего вида дубину может каждый!@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@@PID_CLUB 1@script fix_boy@fix_Tribal}
{6}{}{PID_REVFIST1@Примитивный инструмент из подручных средств. Жаль, что одноразовый - очень быстро стачивается.@@@PID_ROCK 1|PID_FLINT 1|PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1@@PID_REVFIST1 1@script fix_boy@fix_Tribal}
{7}{}{PID_REVKNIFE1@Примитивное подобие ножа из подручного металлолома.@@@PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE1 1@script fix_boy@fix_Tribal}
{8}{}{PID_REVKNIFE2@Взяв за основу более крупный кусок металла, можно выточить грубое мачете.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE2 1@script fix_boy@fix_Tribal}
{9}{}{PID_REVCLUB1@Шипы и лезвия - вот то, чего не хватало вашей дубине!@@@PID_CLUB 1&PID_REVFIST1 1&PID_CRAFT_M_BARS 1@@PID_REVCLUB1 1@script fix_boy@fix_Tribal}
{10}{}{PID_KNIFE@Удобно лежит в руке и хорошо выглядит - что ещё нужно от ножа? Ещё бы только не пришлось его так долго вытачивать..@@@PID_REVKNIFE2 1&PID_REVFIST1 1@@PID_KNIFE 1@script fix_boy@fix_Tribal}
{11}{}{PID_MEDNEEDLE@Нет ничего сложного в том, что бы скрутить из проволки подобие иглы.@@@PID_CRAFT_M_BARS 1@PID_REVFIST1 1@PID_MEDNEEDLE 1@script fix_boy@fix_Tribal}
{12}{}{PID_MEDTHREAD@Вручную выпрядь метр низкокачественных ниток - задача не сложная, но крайне занудная.@@@PID_CRAFT_L_LINT 1@PID_SHIV 1@PID_MEDTHREAD 1@script fix_boy@fix_Tribal}
{13}{}{PID_SHIV@Стачиваем лишнее, вдалбливаем в рукоятку - и долото/шило готово!@@@PID_FIREWOOD 1&PID_REVFIST1 1&PID_REVKNIFE1 1@@PID_SHIV 1@script fix_boy@fix_Tribal}
{14}{}{PID_CRAFT_L_RAGS@Сшить тряпку из подходящих материалов не так уж и сложно.@@@PID_MEDTHREAD 1&PID_CRAFT_L_LINT 4|PID_BROC_FLOWER 8@PID_MEDNEEDLE 1@PID_CRAFT_L_RAGS 1@script fix_boy@fix_Tribal}
{15}{}{PID_PART_OF_ROPE@Берете тряпки и связываете их вместе. Вуаля! Куски веревки в ваших руках.@@@PID_CRAFT_L_RAGS 2@@PID_PART_OF_ROPE 1@script fix_boy@fix_Tribal}
{16}{}{PID_SPEAR@Настало время нести смерть на расстоянии!@@@PID_REVKNIFE1 1&PID_PART_OF_ROPE 2&PID_SHARPENED_POLE 1@@PID_SPEAR 1@script fix_boy@fix_Tribal}
{17}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@@PID_REVFIST1 2&PID_ROCK 2&PID_PART_OF_ROPE 2&PID_SHARPENED_POLE 1@@PID_SLEDGEHAMMER 1@script fix_boy@fix_Tribal}
{18}{}{PID_BOOMERANG_LOW@Жалкое подобие метательного ножа.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@@PID_BOOMERANG_LOW 1@script fix_boy@fix_Tribal}
{19}{}{PID_REV_BALL1@Пара грузил и прочная верёвка - если этот снаряд не опутает жертву, то хотя бы больно стукнет!@@@PID_PART_OF_ROPE 3&PID_ROCK 2@@PID_REV_BALL1 1@script fix_boy@fix_Tribal}
{20}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@@@PID_PART_OF_ROPE 6@@PID_ROPE 1@script fix_boy@fix_Tribal}
{21}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@@@PID_REVKNIFE2 1&PID_CLUB 1&PID_PART_OF_ROPE 2@PID_REVFIST1 1@PID_AXE 1@script fix_boy@fix_Tribal}
{22}{}{PID_SHOVEL@Найдите где-нибудь палку и насадите на один из ее концов подходящую железку.@@@PID_METAL_LIST_MEH 1&PID_SHARPENED_POLE 1&PID_PART_OF_ROPE 2@PID_REVFIST1 1@PID_SHOVEL 1@script fix_boy@fix_Tribal}
{23}{}{PID_KLK@Шкура это не только ценный мех, но и редкие когти с зубами. Жаль, в силу нехватки навыков приходится жертвовать большей части получаемой кожи.@@@PID_MOUSE_SKIN 3|PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 1|PID_FIRE_GECKO_PELT 2@PID_KNIFE 1@PID_KLK 3&PID_CRAFT_L_HIDE 2&PID_CRAFT_L_RAGS 4@script fix_boy@fix_Tribal}
{24}{}{PID_OZHER@Каждый дикарь стремится всунуть в свое ожерелье как можно больше когтей и клыков. Чем вы хуже? [используются все имеющиеся клыки]@@@PID_PART_OF_ROPE 2@PID_KLK 1&PID_SHIV 1@PID_OZHER 1@script fix_boy@fix_Ozher}
{25}{}{PID_RPSTUFF1@Хотите выделиться среди остальных? Бирка вам в помощь!@@@PID_CRAFT_M_BARS 1&PID_CRAFT_L_LINT 1@PID_KNIFE 1@PID_RPSTUFF1 1@script fix_boy@fix_Tribal}
{26}{}{PID_RPSTUFF4@Хотите выделиться среди остальных? Найдите что-либо, на чём можно писать.@@@PID_CRAFT_L_RAGS 1@@PID_RPSTUFF4 1&PID_CRAFT_L_LINT 1@script fix_boy@fix_Tribal}
{27}{}{PID_DICE@Распиливаем палку так, чтобы получился брусок небольших размеров, после чего ножом делаем небольшие углубления, служащие разметкой.@@@PID_FIREWOOD 1@PID_KNIFE 1|PID_REVFIST1 1@PID_DICE 1@script fix_boy@fix_Tribal}
{28}{}{PID_HEALING_POWDER@Разотрите высушенные на солнце ингредиенты и заверните в тряпочку.@@@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_CRAFT_L_RAGS 1@PID_REVFIST1 1@PID_HEALING_POWDER 1@script fix_boy@fix_Tribal}
{29}{}{PID_SHARP_SPEAR@На хорошее копьё не жалко и нож потратить.@@SK_REPAIR 100|SK_OUTDOORSMAN 150|SK_MELEE_WEAPONS 150@PID_KNIFE 1&PID_REVFIST1 1&PID_PART_OF_ROPE 3&PID_SHARPENED_POLE 1@@PID_SHARP_SPEAR 1@script fix_boy@fix_FreeHands}
{30}{}{PID_CUTTHROAT@Бритва, мало чем отличается от ножа-бабочки. Отличается от обычного ножа крайне острой заточкой. Идеальна для работы со всеми видами кожи.@@@PID_CRAFT_M_BARS 1&PID_REVFIST1 1&PID_KNIFE 1@@PID_CUTTHROAT 1@script fix_boy@fix_FreeHands}
{31}{}{PID_SCISSORS@Довольно таки нежный предмет, сложный в изготовлении на коленке.@@@PID_KNIFE 2&PID_CRAFT_M_BARS 2&PID_REVFIST1 2@@PID_SCISSORS 1@script fix_boy@fix_FreeHands}
{32}{}{PID_CROWBAR@Нежными ударами молота загибаем кусок арматуры и затем затачиваем один конец.@@@PID_IRON_PROD 1&PID_REVKNIFE1 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@script fix_boy@fix_FreeHands}
{33}{}{PID_SANDROBE@Почти так же легко, как сшить мешок для мутафруктов размером с человека. Ресурсов и времени уйдёт так много, что даже самодельная игла сломается.@@@PID_CRAFT_L_RAGS 14&PID_CRAFT_L_LINT 14&PID_MEDTHREAD 14&PID_MEDNEEDLE 1@PID_SCISSORS 1@PID_SANDROBE 1@script fix_boy@fix_FreeHands}
{34}{}{PID_SHORT_TUBE@Резать трубы ножом не самая удачная идея, но вам ничего другого не остается.@@@PID_WATER_TUBE 1|PID_TUBE 1&PID_REVKNIFE2 1@@PID_SHORT_TUBE 1@script fix_boy@fix_FreeHands}
{35}{}{PID_SWITCHBLADE@Простенький выкидной нож - удобное оружие, которое легко можно незаметно пронести "в рукаве".@@SK_REPAIR 100|SK_OUTDOORSMAN 150|SK_MELEE_WEAPONS 150@PID_SHORT_TUBE 1|PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_CUTTHROAT 1@@PID_SWITCHBLADE 1@script fix_boy@fix_FreeHands}
{36}{}{PID_ZIP_GUN@Хочется напугать дикарей гром-палкой, но руки из жопы? Тогда делаем лёгкий кривокосый простенький чиркаш! Главное - не удивляться, если он рванёт в вашей руке при выстреле.@@@PID_SHORT_TUBE 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_FLINT 1&PID_CLUB 1@@PID_ZIP_GUN 1@script fix_boy@fix_FreeHands}
{37}{}{PID_SPRINGER_RIFLE@Примитивный мушкет малого калибра из подручных средств. Ствол очень быстро забивается пороховыми газами.@@SK_SMALL_GUNS 100&SK_REPAIR 100@PID_TUBE 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_FLINT 1&PID_CLUB 1@@PID_SPRINGER_RIFLE 1@script fix_boy@fix_FreeHands}
{38}{}{PID_CHEMICALS@Базовых познаний в химии хватает для того что бы экспериментальным путём выварить и процедить из минеральной крошки небольшую порцию химического реагента.@@SK_SCIENCE 100|SK_OUTDOORSMAN 100|SK_DOCTOR 100@PID_MINERAL 1&PID_GLASS_BOTTLE_FULL 1&PID_CRAFT_L_RAGS 1&PID_FIREPLACE_TOKEN 1@PID_SLEDGEHAMMER 1@PID_CHEMICALS 1@script fix_boy@fix_FreeHands}
{39}{}{PID_REV_BALL2@Укрепив верёвку пластиковой смесью и навтыкав в неё острых кусков стекла, вы значительно усложнили процесс освобождения из этих пут.@@SK_SCIENCE 100|SK_OUTDOORSMAN 100@PID_REV_BALL1 1&PID_CHEMICALS 1@@PID_REV_BALL1 1@script fix_boy@fix_FreeHands}
{40}{}{PID_CRAFT_L_HIDE@Ваших познаний достаточно, что бы выдубить имеющиеся шкуры и получить из неё шматы кожи.@@SK_SCIENCE 100|SK_OUTDOORSMAN 100@PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 1|PID_GECKO_PELT 2|PID_MOUSE_SKIN 3&PID_CHEMICALS 1&PID_FIREPLACE_TOKEN 1@@PID_CRAFT_L_HIDE 4&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}
{41}{}{PID_LEATHER_JACKET@Сшейте куртку из кусков шкур и ткани. По последней моде без одного рукава.@@SK_OUTDOORSMAN 150|SK_REPAIR 100@PID_CRAFT_L_HIDE 8&PID_CRAFT_L_LINT 8&PID_MEDTHREAD 8&PID_MEDNEEDLE 1@PID_SHIV 1&PID_SCISSORS 1&PID_CUTTHROAT 1@PID_LEATHER_JACKET 1@script fix_boy@fix_FreeHands}
{42}{}{PID_LEATHER_ARMOR@Вываренная дублёная кожа - отличный материал для обеспечения полной защиты вашего тела.@@SK_OUTDOORSMAN 200|SK_REPAIR 150&SK_SCIENCE 100@PID_BOTTLE_FULL 6&PID_CRAFT_L_HIDE 12&PID_CRAFT_L_LINT 8&PID_MEDTHREAD 12&PID_MEDNEEDLE 1&PID_FIREPLACE_TOKEN 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1&PID_CUTTHROAT 1@PID_LEATHER_ARMOR 1@script fix_boy@fix_FreeHands}
{43}{}{PID_LEATHER_ARMOR_MK_II@Что бы усилить поглощение ударов, вы обшиваете жёсткими элементами из кожанного доспеха всю вашу одежду из кожи@@SK_OUTDOORSMAN 250|SK_REPAIR 200&SK_SCIENCE 150@PID_LEATHER_JACKET 1&PID_CURED_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{44}{}{PID_CURED_LEATHER_ARMOR@Что бы увеличить защиту от скользящих ударов и при этом не потерять мобильность, вы пришиваете небольшие куски вываренной кожи к открытым частям одежды.@@SK_OUTDOORSMAN 250|SK_REPAIR 200&SK_SCIENCE 150@PID_LEATHER_JACKET 1&PID_BOTTLE_FULL 4&PID_CRAFT_L_HIDE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_CURED_LEATHER_ARMOR 1@script fix_boy@fix_FreeHands}
{45}{}{PID_CURED_LEATHER_ARMOR_MK_II@Совершенно другой подход к решению проблемы защиты открывается при использовании небольших бронепластин. Переделав нашлёпки из кожи в карманы для пластин, вы добиваетесь разительного увеличения защиты от проникающих и касательных ударов без потерь в мобильности.@@SK_SCIENCE 200&SK_REPAIR 150@PID_CURED_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_PB_PLATE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_CURED_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{46}{}{PID_LEATHER_ARMOR_MK_III@Полноценная защита из кожи укреплённой бронепластинами. С таким и пулю схлопотать не страшно.@@SK_SCIENCE 200&SK_REPAIR 150@PID_LEATHER_ARMOR_MK_II 1&PID_PART_OF_ROPE 6&PID_PB_PLATE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{47}{}{PID_MULTI_TOOL@Плоскогубцы, отвертка и расческа одновременно. Посложней, чем ножницы мастерить, но оно того стоит!@@SK_REPAIR 150@PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 4&PID_SHIV 1@@PID_MULTI_TOOL 1@script fix_boy@fix_FreeHands}
{48}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@PID_MULTI_TOOL 1@PID_BRASS_KNUCKLES 1@script fix_boy@fix_FreeHands}
{49}{}{PID_PB_FOR_AMMO@Кропотливо выполненные вручную гильзы.@@SK_REPAIR 100@PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_METAL_LIST_MEH 1&PID_FIREPLACE_TOKEN 1@PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 4@script fix_boy@fix_FreeHands}
{50}{}{PID_GUNPOWDER@В процессе приготовления главное не надышаться ядовитыми парами.@@SK_SCIENCE 150@PID_CHEMICALS 1&PID_MUSH_LOW 3&PID_GLASS_BOTTLE_FULL 1&PID_FIREPLACE_TOKEN 1@@PID_GUNPOWDER 2&PID_BOTTLE_GLASS 2@script fix_boy@fix_FreeHands}
{51}{}{PID_10mm_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100&SK_REPAIR 100@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1@PID_10mm_LOW 4@script fix_boy@fix_FreeHands}
{52}{}{PID_044mag_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 150&SK_REPAIR 150@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_044mag_LOW 4@script fix_boy@fix_Workbench}
{53}{}{PID_DARTS_LOW@Длинные ровные острые деревянные полуметровые болты без оперения. Чем попало такое не вырезать.@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@PID_CUTTHROAT 1@PID_DARTS_LOW 2@script fix_boy@fix_FreeHands}
{54}{}{PID_SPEARTHROWER1_LOW@"Пара пружин, рычаги и рама" - так вы думали, пока не поняли что без калибровки и доводки оно швыряет болты куда попало и постоянно делает осечки. Но это всё уже позади. К тому же, вместо пружинного механизма, вполне можно использовать крепкую проволку или грубую тетиву.@@SK_SMALL_GUNS 150&SK_SCIENCE 150&SK_REPAIR 150@PID_CRAFT_M_JUNK 3&PID_DETAL_MEH 1&PID_CLUB 1&PID_ROPE 1|PID_CRAFT_M_BARS 3@PID_MULTI_TOOL 1@PID_SPEARTHROWER1 1@script fix_boy@fix_FreeHands}
{55}{}{PID_WOOD_PLANK@Базовый строительный материал.@@SK_REPAIR 100|SK_OUTDOORSMAN 100@PID_FIREWOOD 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_WOOD_PLANK 1@script fix_boy@fix_Workbench}
{56}{}{PID_ELECTO_MEH@Из подручных материалов всегда можно собрать что-нибудь полезное.@@SK_SCIENCE 100&SK_REPAIR 150@PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_ELECTO_MEH 1@script fix_boy@fix_Workbench}
{57}{}{PID_SOED_MEH@Из подручных материалов всегда можно собрать что-нибудь полезное.@@SK_SCIENCE 100&SK_REPAIR 150@PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_ELECTO_MEH 1@script fix_boy@fix_Workbench}
{58}{}{PID_CRAFT_M_STEL@Ценная универсальная деталь, из чего попало такую не собрать.@@SK_SCIENCE 150&SK_REPAIR 200@PID_ELECTO_MEH 1&PID_SOED_MEH 1@PID_MULTI_TOOL 1@PID_CRAFT_M_STEL 1@script fix_boy@fix_FreeHands}
{59}{}{PID_REVOLVER_LOW@Использовав черкаш за основу, вы собираете более вменяемый ствол, спусковой механизм и барабан. Самодельный револьвер готов!@@SK_SMALL_GUNS 150&SK_REPAIR 150&SK_SCIENCE 100@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_ELECTO_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REVOLVER_LOW 1@script fix_boy@fix_Workbench}
{60}{}{PID_PISTOL_LOW@Использовав черкаш за основу, вы собираете примитивный пистолет. Он явно нуждается в доработке.@@SK_SMALL_GUNS 150&SK_REPAIR 200&SK_SCIENCE 100@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_CRAFT_M_STEL 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_PISTOL_LOW 1@script fix_boy@fix_Workbench}
{61}{}{PID_SMOKE_GUN_LOW@Переточив ствол под меньший калибр и модернизировав зарядно-спусковой механизм вы вытачиваете неснимаемый самодельный глушитель, позволяющий не выдавать себя при стрельбе.@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 150@PID_PISTOL_LOW 1&PID_TUBE 1&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SMOKE_GUN_LOW 1@script fix_boy@fix_Workbench}
{62}{}{PID_SHOTPISTOL_LOW@Берем парочку труб подходящего диаместра, воруем спусковой механизм у простенького пистолета, модернизируем, тщательно закрепляем и получаем подобие дробовика.@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 150@PID_PISTOL_LOW 1&PID_SHORT_TUBE 2&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SHOTPISTOL_LOW 1@script fix_boy@fix_Workbench}
{63}{}{PID_REV_RIFLE_LOW@Слегка переделываем мушкет, получая простенькую револьверную винтовку.@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 15@PID_SPRINGER_RIFLE 1&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_TUBE 1&PID_FIREWOOD 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REVOLVER_LOW 1@script fix_boy@fix_Workbench}
{64}{}{PID_SNIPER_GUN_LOW@Переточка под другой карабин и усиление ствола позволяют превратить жалкий мушкет в грозную винтовку.@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 150@PID_SPRINGER_RIFLE 1&PID_TUBE 2&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SNIPER_GUN_LOW 1@script fix_boy@fix_Workbench}
{65}{}{PID_LOW_SNIPER2@Ваших навыков достаточно для модернизации винтовки экспериментальным путём. Новая конструкция имеет более высокую точность, дальность и урон, но жутко громыхает.@@SK_SMALL_GUNS 250&SK_REPAIR 250&SK_SCIENCE 200@PID_SNIPER_GUN_LOW 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_TUBE 1&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOW_SNIPER2 1@script fix_boy@fix_Workbench}
{66}{}{PID_LOW_SNIPER3@Учитывая все возможные особенности и ограничения подобного самодела, вы максимально модернизируете винтовку без помощи нормального оборудования, используя один лишь верстак с простецкими инструментами.@@SK_SMALL_GUNS 300&SK_REPAIR 300&SK_SCIENCE 200@PID_LOW_SNIPER2 1&PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_TUBE 2&PID_CRAFT_M_STEL 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOW_SNIPER3 1@script fix_boy@fix_Workbench}