{100}{}{PID_CRAFT_MENU_MAIN@Вернуться к выбору категории крафта.@CR_CRAFT_MENU 0&CR_CRAFT_GRADE 73@@PID_CRAFT_MENU_MAIN 1@@PID_CRAFT_MENU_MAIN 1@script fix_boy@fix_typeFilter}
{101}{}{PID_CRAFT_MENU_OLD@Старые несортированные пункты крафта:@CR_CRAFT_MENU 1&CR_CRAFT_GRADE 72@@PID_CRAFT_MENU_OLD 1@@PID_CRAFT_MENU_OLD 1@script fix_boy@fix_typeFilter}
{102}{}{PID_CRAFT_MENU_TEST@Старые несортированные пункты крафта:@CR_CRAFT_MENU 2&CR_CRAFT_GRADE 71@@PID_CRAFT_MENU_TEST 1@@PID_CRAFT_MENU_TEST 1@script fix_boy@fix_typeFilter}
{700}{}{PID_ZAPLATKA_CRAFT_BASIC@Разделитель раздела для создания простейших вещей.@@@PID_ZAPLATKA_CRAFT_BASIC 1@@PID_ZAPLATKA_CRAFT_BASIC 1@script fix_boy@fix_Tribal}
{705}{}{PID_KLK@Шкура это не только ценный мех, но и редкие когти с зубами. Жаль, в силу нехватки навыков приходится жертвовать большей части получаемой кожи.@@@PID_MOUSE_SKIN 9|PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 1|PID_GECKO_PELT 2@PID_KNIFE 1@PID_KLK 3&PID_CRAFT_L_HIDE 2&PID_CRAFT_L_RAGS 4@script fix_boy@fix_Tribal}
{710}{}{PID_MEAT_JERKY@Вялим мясо на костре.@@@PID_RAD_MEAT 4&PID_BOOZE 1&PID_FIREPLACE_TOKEN 1@@PID_MEAT_JERKY 3&PID_BOTTLE_GLASS 1@script fix_boy@fix_Tribal}
{715}{}{PID_MEAT_JERKY@Вариант для ленивых - жарим мясо в углях, запекая в собственной корке.@@@PID_RAD_MEAT 3&PID_FIREPLACE_TOKEN 1@@PID_MEAT_JERKY 1@script fix_boy@fix_Delayed}
{720}{}{PID_MEAT@Маринуем два килограмма мяса диких животных в водке со специями, что бы вывести из него всю гадость.@@SK_OUTDOORSMAN 100@PID_RAD_MEAT 8&PID_BOOZE 1&PID_HEALING_POWDER 1&PID_FIREPLACE_TOKEN 1@@PID_MEAT 2&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}
{725}{}{PID_FLINT@Нужный вам кремний можно найти в груде камней, если поработать с ними молотком.@@@PID_ROCK 8@PID_SLEDGEHAMMER 1@PID_FLINT 1@script fix_boy@fix_Tribal}
{730}{}{PID_BOTTLE_GLASS@Переливаем воду из бутылки в баклашку, ничего особенного.@@@PID_GLASS_BOTTLE_FULL 1&PID_BOTTLE_EMPTY 1@@PID_BOTTLE_FULL 1&PID_BOTTLE_GLASS 1@script fix_boy@fix_None}
{735}{}{PID_BOTTLE_EMPTY@Переливаем воду из баклашки в бутылку, ничего особенного.@@@PID_BOTTLE_FULL 1&PID_BOTTLE_GLASS 1@@PID_GLASS_BOTTLE_FULL 1&PID_BOTTLE_EMPTY 1@script fix_boy@fix_None}
{740}{}{PID_PORTMONE@Кусок кожи и пара верёвок - файлпапка/пормоне готов!@@@PID_PART_OF_ROPE 2&PID_CRAFT_L_HIDE 1@@PID_PORTMONE 1@script fix_boy@fix_Tribal}
{745}{}{PID_KEY_BUNCH@Для связки ключей подойдёт любая проволка или кусок верёвки@@@PID_CRAFT_M_BARS 1|PID_PART_OF_ROPE 1@@PID_KEY_BUNCH 1@script fix_boy@fix_None}
{750}{}{PID_CRAFT_M_BARS@Два ключика похожего типа можно разломать и распилить обратно на пустую заготовку.@@@PID_BLANK_KEY 2|PID_TEMPLE_KEY 2|PID_JAIL_KEY 2|PID_VAULT_13_SHACK_KEY 2@@PID_CRAFT_M_BARS 1@script fix_boy@fix_None}
{755}{}{PID_SHARPENED_POLE@Вжик-вжик, и готово!@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@@PID_SHARPENED_POLE 1@script fix_boy@fix_None}
{760}{}{PID_FIREWOOD@Чем вам доска не полено?@@@PID_WOOD_PLANK 1@@PID_FIREWOOD 1@script fix_boy@fix_None}
{765}{}{PID_WOOD_PLANK@Немного сточить там-сям, и готово.@@@PID_REVFIST1 1&PID_FIREWOOD 3@@PID_WOOD_PLANK 2@script fix_boy@fix_Tribal}
{770}{}{PID_CLUB@Как оказалось, сделать устрашающего вида дубину может каждый!@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@@PID_CLUB 1@script fix_boy@fix_Tribal}
{775}{}{PID_MEDTHREAD@Вручную выпрядь метр низкокачественных ниток - задача не сложная, но крайне занудная.@@@PID_CRAFT_L_LINT 1@PID_SHIV 1@PID_MEDTHREAD 1@script fix_boy@fix_None}
{780}{}{PID_CRAFT_L_LINT@Разрезаем ножом тряпку на кусочки. Гайд для чайников.@@@PID_CRAFT_L_RAGS 1@PID_KNIFE 1|PID_SCISSORS 1@PID_CRAFT_L_LINT 4@script fix_boy@fix_None}
{785}{}{PID_CRAFT_L_RAGS@Сшить тряпку из подходящих материалов не так уж и сложно.@@@PID_MEDTHREAD 1&PID_CRAFT_L_LINT 4|PID_BROC_FLOWER 8@PID_MEDNEEDLE 1@PID_CRAFT_L_RAGS 1@script fix_boy@fix_Tribal}
{790}{}{PID_PART_OF_ROPE@Берете тряпки и связываете их вместе. Вуаля! Куски веревки в ваших руках.@@@PID_CRAFT_L_RAGS 2@@PID_PART_OF_ROPE 1@script fix_boy@fix_Tribal}
{795}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@@@PID_PART_OF_ROPE 6@@PID_ROPE 1@script fix_boy@fix_Tribal}
{800}{}{PID_PART_OF_ROPE@Пора убрать клыки с этой верёвки, ведь для неё есть более полезное применение.@@@PID_OZHER 1@@PID_PART_OF_ROPE 1@script fix_boy@fix_None}
{805}{}{PID_SHORT_TUBE@Резать трубы ножом не самая удачная идея, но вам ничего другого не остается.@@@PID_WATER_TUBE 1|PID_TUBE 1&PID_REVKNIFE2 1@@PID_SHORT_TUBE 1@script fix_boy@fix_FreeHands}
{810}{}{PID_CRAFT_L_HIDE@Ваших познаний достаточно, что бы выдубить имеющиеся шкуры и получить из неё шматы кожи.@@SK_SCIENCE 200|SK_OUTDOORSMAN 200@PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 1|PID_GECKO_PELT 2|PID_MOUSE_SKIN 6&PID_CHEMICALS 1&PID_FIREPLACE_TOKEN 1@@PID_CRAFT_L_HIDE 4&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}
{815}{}{PID_SIGN@Имея прямые руки, доски, гвозди и молоток, можно вполне спокойно сделать себе табличку из древесины. Или баррикаду. Да хоть стену, либо дверь!@@SK_REPAIR 100|SK_OUTDOORSMAN 100@PID_CLUB 1&PID_WOOD_PLANK 2&PID_WOOD_PART 2&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@@PID_SIGN 1@script fix_boy@fix_Workbench}
{820}{}{PID_IRON_PLATE@Ковка листового железа - утомительное и опасное занятие. Без хорошей защиты от жара этим лучше не заниматься!@@SK_SCIENCE 100|SK_REPAIR 100|SK_OUTDOORSMAN 100@PID_IRON_BAR 1&PID_FIREPLACE_TOKEN 1&PID_GLASS_BOTTLE_FULL 1|PID_BOTTLE_FULL 1@PID_MULTI_TOOL 1&PID_MOTOGLES 1&PID_SLEDGEHAMMER 1@PID_IRON_PLATE 1@script fix_boy@fix_Smithing}
{825}{}{PID_IRON_DETALS@Штампуем базовые детали для сложных механизмов.@@SK_SCIENCE 200&SK_REPAIR 175@PID_IRON_PLATE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_IRON_DETALS 1@script fix_boy@fix_Workbench}
{830}{}{PID_DICE@Распиливаем палку так, чтобы получился брусок небольших размеров, после чего ножом делаем небольшие углубления, служащие разметкой.@@@PID_FIREWOOD 1@PID_KNIFE 1|PID_REVFIST1 1@PID_DICE 1@script fix_boy@fix_None}
{835}{}{PID_WOOD_PART@Базовый строительный материал.@@SK_REPAIR 100|SK_OUTDOORSMAN 100@PID_FIREWOOD 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_WOOD_PART 1@script fix_boy@fix_Tribal}
{840}{}{PID_DETAL_MEH@Из подручных материалов всегда можно собрать что-нибудь полезное.@@SK_SCIENCE 125&SK_REPAIR 125@PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_DETAL_MEH 1@script fix_boy@fix_Workbench}
{845}{}{PID_ELECTO_MEH@Из подручных материалов всегда можно собрать что-нибудь полезное.@@SK_SCIENCE 150&SK_REPAIR 150@PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_ELECTO_MEH 1@script fix_boy@fix_Workbench}
{850}{}{PID_SOED_MEH@Из подручных материалов всегда можно собрать что-нибудь полезное.@@SK_SCIENCE 200&SK_REPAIR 200@PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SOED_MEH 1@script fix_boy@fix_Workbench}
{855}{}{PID_CRAFT_M_STEL@Ценная универсальная деталь, из чего попало такую не собрать.@@SK_SCIENCE 250&SK_REPAIR 250@PID_ELECTO_MEH 1&PID_SOED_MEH 1&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_CRAFT_M_STEL 1@script fix_boy@fix_Workbench}
{860}{}{PID_DVIGAT_MEH@Используя особые детали и набор подручных средств, собираем ключевой элемент для создания крупных пушек.@@SK_BIG_GUNS 200&SK_REPAIR 200&SK_SCIENCE 150@PID_IRON_DETALS 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_DVIGAT_MEH 1@script fix_boy@fix_Workbench}
{870}{}{PID_GOLDEN_COIN@Ковка заготовок для монет - утомительное и опасное занятие. Без хорошей защиты от жара этим лучше не заниматься!@@SK_SCIENCE 100|SK_REPAIR 100|SK_OUTDOORSMAN 100@PID_GOLDEN_BAR 1&PID_FIREPLACE_TOKEN 1&PID_GLASS_BOTTLE_FULL 1|PID_BOTTLE_FULL 1@PID_MULTI_TOOL 1&PID_MOTOGLES 1&PID_SLEDGEHAMMER 1@PID_GOLDEN_COIN 100@script fix_boy@fix_Smithing}
{875}{}{PID_BOTTLE_CAPS@Вы чеканите монеты из заготовок. Тупая работа, не требующая ничего кроме инструментов и кучи времени.@@@PID_GOLDEN_COIN 25&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_SLEDGEHAMMER 1@PID_BOTTLE_CAPS 25@script fix_boy@fix_Delayed}
{880}{}{PID_SAND@Берём лопату - копаем песок. Кремний для заточки.@@@PID_FLINT 1@PID_SHOVEL 1@PID_SAND 1@script fix_boy@fix_FreeHands}
{885}{}{PID_GLASS_BAR@Берём качественную древесину в качестве топлива, и выплавляем стеклянный куб на огне.@@@PID_BANKA_MEH 1&PID_SAND 10&PID_WOOD_PART 4&PID_FIREPLACE_TOKEN 1@PID_MULTI_TOOL 1@PID_GLASS_BAR 1@script fix_boy@fix_FreeHands}
{890}{}{PID_GLASS@Распиливаем точной сваркой кубик на пластины.@@SK_REPAIR 100@PID_GLASS_BAR 1@PID_WELDING 1&PID_MULTI_TOOL 1@PID_GLASS 2@script fix_boy@fix_FreeHands}
{895}{}{PID_LINZA@После точных замеров, вы вытачивате линзы нужной вам формы.@@SK_REPAIR 150&SK_SCIENCE 100|SK_DOCTOR 100@PID_GLASS 1&PID_FLINT 4&PID_BOTTLE_FULL 2&PID_CRAFT_L_RAGS 4&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LINZA 2@script fix_boy@fix_Workbench}
{900}{}{PID_CRAFT_E_LAMP@Радиодетали, или что-то на них похожее. Крайне просты в изготовлении, хоть и требуют для этого полный набор базовых инструментов.@@SK_REPAIR 150&SK_SCIENCE 150&SK_ENERGY_WEAPONS 100@PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 4&PID_BOTTLE_EMPTY 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_CRAFT_E_LAMP 1@script fix_boy@fix_Workbench}
{905}{}{PID_CRAFT_E_PART@Кустарная плата. Не стоит ожидать от неё многого.@@SK_REPAIR 200&SK_SCIENCE 200&SK_ENERGY_WEAPONS 100@PID_WOOD_PART 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 4&PID_BOTTLE_GLASS 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_CRAFT_E_PART 1@script fix_boy@fix_Workbench}
{910}{}{PID_EXCAVATOR_CHIP@Кустарный конденсатор. Не стоит ожидать от него многого.@@SK_REPAIR 200&SK_SCIENCE 200&SK_ENERGY_WEAPONS 150@PID_GLASS 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_EXCAVATOR_CHIP 1@script fix_boy@fix_Workbench}
{915}{}{PID_CRAFT_E_CHIP@Чип-плата - мечта компьютерного фанатика. Крайне сложна в изготовлении и требовательна в использовании. Основа, сердце и разум любой сложной электроники.@@SK_REPAIR 200&SK_SCIENCE 200&SK_ENERGY_WEAPONS 200@PID_CRAFT_E_PART 1&PID_CRAFT_E_LAMP 1&PID_EXCAVATOR_CHIP 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_CRAFT_E_CHIP 1@script fix_boy@fix_Workbench}
{1000}{}{PID_ZAPLATKA_CRAFT_MISC@Разделитель раздела для создания полезных вещей общего назначения.@@@PID_ZAPLATKA_CRAFT_MISC 1@@PID_ZAPLATKA_CRAFT_MISC 1@script fix_boy@fix_Tribal}
{1005}{}{PID_AMMO_BELT@Кусок кожи и пара верёвок - и ваш колчан/патронташ/чехол/пояс готов!@@@PID_PART_OF_ROPE 2&PID_CRAFT_L_HIDE 1@@PID_AMMO_BELT 1@script fix_boy@fix_Tribal}
{1010}{}{PID_BRIEFCASE@Вставляем металлические распорки в сумку, что бы её содержимое не сломалось от случайных ударов, и делаем защёлку сверху, что бы ничего не выпало. Чемоданчик готов!@@@PID_CRAFT_M_BARS 2&PID_BAG 1@PID_WORKBENCH_TOKEN 1@PID_BRIEFCASE 1@script fix_boy@fix_Delayed} 
{1015}{}{PID_BOXING_GLOVES@Боксёрские перчатки.@@@PID_CRAFT_L_HIDE 2&PID_CRAFT_L_RAGS 4&PID_CRAFT_L_LINT 4&PID_MEDTHREAD 4&PID_MEDNEEDLE 1@PID_SHIV 1&PID_SCISSORS 1&PID_CUTTHROAT 1@PID_BOXING_GLOVES 1@script fix_boy@fix_FreeHands}
{1020}{}{PID_OZHER@Каждый дикарь стремится всунуть в свое ожерелье как можно больше когтей и клыков. Чем вы хуже? [используются все имеющиеся клыки]@@@PID_PART_OF_ROPE 2@PID_KLK 1&PID_SHIV 1@PID_OZHER 1@script fix_boy@fix_Ozher}
{1025}{}{PID_RPSTUFF1@Хотите выделиться среди остальных? Бирка вам в помощь!@@@PID_CRAFT_M_BARS 1&PID_CRAFT_L_LINT 1@PID_KNIFE 1@PID_RPSTUFF1 1@script fix_boy@fix_Tribal}
{1030}{}{PID_HOLODISK@Хотите выделиться среди остальных? Найдите что-либо, на чём можно писать.@@@PID_CRAFT_L_RAGS 1@@PID_HOLODISK 1&PID_CRAFT_L_LINT 1@script fix_boy@fix_None}
{1035}{}{PID_CRAFT_RECIPES@Некоторым листам суждено стать чем-то большим.@@@PID_CRAFT_L_RAGS 1@@PID_CRAFT_RECIPES 1@script fix_boy@fix_None}
{1040}{}{PID_HANDWRITINGS@Некоторым листам суждено стать чем-то большим.@@@PID_CRAFT_L_RAGS 1@@PID_HANDWRITINGS 1@script fix_boy@fix_None}
{1045}{}{PID_PASSPORT@Некоторым листам суждено стать чем-то большим.@@@PID_CRAFT_L_RAGS 1@@PID_PASSPORT 1@script fix_boy@fix_None}
{1050}{}{PID_PAPERS_JAMMED@Некоторым листам суждено стать чем-то большим.@@@PID_CRAFT_L_RAGS 1@@PID_PAPERS_JAMMED 1@script fix_boy@fix_None}
{1055}{}{PID_mgzn01@Некоторым листам суждено стать чем-то большим.@@@PID_CRAFT_L_RAGS 1@@PID_mgzn01 1@script fix_boy@fix_None}
{1060}{}{PID_BANDAGE@Нарежьте тряпки в ленты и как следует прокипятите их. Сверните в рулоны, обработав спиртом. @@@PID_GLASS_BOTTLE_FULL 1&PID_CRAFT_L_RAGS 5&PID_BOOZE 1@PID_FIREPLACE_TOKEN 1@PID_BANDAGE 3&PID_BOTTLE_GLASS 2@script fix_boy@fix_FreeHands}
{1065}{}{PID_MEDSPLINT@Делаем ремешки на фиксаторы, делаем мягкую прокладку и мы готовы к фиксации конечности!@@SK_DOCTOR 125@PID_CRAFT_M_JUNK 1&PID_PART_OF_ROPE 3&PID_WOOD_PART 1@PID_WORKBENCH_TOKEN 1@PID_MEDSPLINT 3@script fix_boy@fix_FreeHands}
{1070}{}{PID_MEDCLIP@Хотите, чтобы операция проходила менее болезненно для вашего пациента? Тогда вам непременно стоит сделать зажим. Не забудте продезинфицировать ваше творение! @@SK_REPAIR 100&SK_FIRST_AID 100|SK_DOCTOR 100@PID_CRAFT_M_BARS 2&PID_BOOZE 1@PID_MULTI_TOOL 1@PID_MEDCLIP 1@script fix_boy@fix_FreeHands}
{1075}{}{PID_RESPIRATOR@Работаете с химикатами, любите блуждать по подземке или просто боитесь запаха изо рта? Респиратор поможет вам!@@SK_SCIENCE 100&SK_REPAIR 150@PID_CRAFT_L_HIDE 1&PID_CRAFT_M_JUNK 1&PID_EMKOCT_MEH 1&PID_ELECTO_MEH 1&PID_PART_OF_ROPE 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1@PID_RESPIRATOR 1@script fix_boy@fix_Workbench}
{1080}{}{PID_LOCKER_LOW@Самый просто навесной замок. Проще некуда.@@SK_REPAIR 100@PID_CRAFT_M_BARS 5@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_LOCKER_LOW 1@script fix_boy@fix_Workbench}
{1085}{}{PID_LOCKER_MED@Не смотря на то, что вы не разбираетесь в замках, ваших научных познаний и расходников хватает на модернизацию методом проб и ошибок.@@SK_REPAIR 150&SK_SCIENCE 200@PID_LOCKER_LOW 1&PID_CRAFT_M_BARS 10@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_LOCKER_MED 1@script fix_boy@fix_Workbench}
{1090}{}{PID_LOCKER_MED@Замок среднего уровня. Может от кого-то и спасет.@@SK_REPAIR 150&SK_LOCKPICK 100@PID_CRAFT_M_BARS 5&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOCKER_MED 1@script fix_boy@fix_Workbench}
{1095}{}{PID_LOCKER_HARD@Хех, куда же такой сейф ставить?@@SK_REPAIR 200&SK_LOCKPICK 150@PID_CRAFT_M_BARS 15&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_LOCKER_HARD 1@script fix_boy@fix_Workbench}
{1100}{}{PID_SANDBAG_EMPTY@Мешок. Да, его можно сшить.@@@PID_CRAFT_L_RAGS 4&PID_MEDTHREAD 4@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_SANDBAG_EMPTY 1@script fix_boy@fix_FreeHands}
{1105}{}{PID_SANDBAG_1@Есть пустой мешок? Скорей набери в него песка!@@@PID_SANDBAG_EMPTY 1@PID_SHOVEL 1@PID_SANDBAG_1 1@script fix_boy@fix_None}
{1110}{}{PID_BAG@Берем мешок, связываем одну из сторон веревкой.@@@PID_SANDBAG_EMPTY 1&PID_ROPE 1@@PID_BAG 1@script fix_boy@fix_FreeHands}
{1115}{}{PID_BACKPACK@Обычный такой рюкзак.@@SK_REPAIR 150&SK_SCIENCE 100@PID_SANDBAG_EMPTY 1&PID_BAG 1&PID_CRAFT_L_HIDE 4&PID_MEDTHREAD 4&PID_PART_OF_ROPE 2@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_BACKPACK 1@script fix_boy@fix_FreeHands}
{1120}{}{PID_SKIN_CHANGER@Костюм, набор одежды - всё что вам нужно для полного преображения!@@ST_CHARISMA 4@PID_CRAFT_L_RAGS 12&PID_MEDTHREAD 12@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_SKIN_CHANGER 1@script fix_boy@fix_FreeHands}
{1125}{}{PID_SPECTACLES@Вы вставляете линзы в оправу - ваши очки готовы!@@SK_SCIENCE 150|SK_DOCTOR 150@PID_CRAFT_M_JUNK 2&PID_LINZA 2&PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_SPECTACLES 1@script fix_boy@fix_Tribal}
{1130}{}{PID_MIRROR_SHADES@Простенькие солнцезащитные очки - пластик с зандером пополам, замешать и добавить душки.@@@PID_BOTTLE_EMPTY 4&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 1&PID_BOOZE 1&PID_XANDER_ROOT 4@PID_FIREPLACE_TOKEN 1@PID_MIRROR_SHADES 1@script fix_boy@fix_Workbench}
{1135}{}{PID_MOTOGLES@Идеальный выбор путешественника: взяв линзы из настроенных оптических и солнцезащитных очков, вы комбинируете их в подобии шлема, позволяющего видеть дальше в условиях пустоши.@@SK_SCIENCE 150&SK_REPAIR 200@PID_SPECTACLES 1&PID_MIRROR_SHADES 1&PID_BOTTLE_EMPTY 2&PID_CRAFT_M_BARS 2&PID_PART_OF_ROPE 1&PID_CRAFT_L_HIDE 2&PID_WORKBENCH_TOKEN 1@PID_SHIV 1&PID_SCISSORS 1&PID_MULTI_TOOL 1@PID_MOTOGLES 1@script fix_boy@fix_FreeHands}
{1140}{}{PID_HANDCUFFS@Обычные наручники из подручных средств.@@SK_SCIENCE 100&SK_REPAIR 150@PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 1&PID_CHAIN 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_HANDCUFFS 1@script fix_boy@fix_Workbench}
{1145}{}{PID_FIRST_AID_KIT@Вставляем металлические распорки в сумку, что бы её содержимое не сломалось от случайных ударов, и делаем защёлку сверху, что бы ничего не выпало. Походная аптечка готова!@@@PID_CRAFT_M_BARS 2&PID_BAG 1@PID_WORKBENCH_TOKEN 1@PID_FIRST_AID_KIT 1@script fix_boy@fix_Delayed} 
{1150}{}{PID_DOCTORS_BAG@Вставляем металлические распорки в рюкзак, что бы его содержимое не сломалось от случайных ударов, и делаем защёлку сверху, что бы ничего не высыпалось. Лямки переделываем в ручки. Саквояж готов!@@@PID_CRAFT_M_BARS 3&PID_BACKPACK 1@PID_WORKBENCH_TOKEN 1@PID_DOCTORS_BAG 1@script fix_boy@fix_Delayed}
{1155}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Ну так чего же вы ждёте - соберите скорей простейший радиопередатчик и соедините его с радиоприёмником!@@SK_REPAIR 200&SK_SCIENCE 200&SK_ENERGY_WEAPONS 100@PID_SMALL_ENERGY_CELL 1&PID_CRAFT_E_PART 1&PID_CRAFT_E_LAMP 1&PID_IRON_DETALS 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_RADIO 1@script fix_boy@fix_Workbench}
{1200}{}{PID_ZAPLATKA_CRAFT_TOOLS@Разделитель раздела для создания холодного оружия и инструментов.@@@PID_ZAPLATKA_CRAFT_TOOLS 1@@PID_ZAPLATKA_CRAFT_TOOLS 1@script fix_boy@fix_Tribal}
{1205}{}{PID_REVFIST1@Примитивный инструмент из подручных средств. Жаль, что одноразовый - очень быстро стачивается.@@@PID_ROCK 3|PID_FLINT 1|PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1@@PID_REVFIST1 1@script fix_boy@fix_Tribal}
{1210}{}{PID_REVKNIFE1@Примитивное подобие ножа из подручного металлолома.@@@PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE1 1@script fix_boy@fix_Tribal}
{1215}{}{PID_REVKNIFE2@Взяв за основу более крупный кусок металла, можно выточить грубое мачете.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE2 1@script fix_boy@fix_Tribal}
{1220}{}{PID_REVCLUB1@Шипы и лезвия - вот то, чего не хватало вашей дубине!@@@PID_CLUB 1&PID_REVFIST1 1&PID_CRAFT_M_BARS 1@@PID_REVCLUB1 1@script fix_boy@fix_Tribal}
{1225}{}{PID_KNIFE@Удобно лежит в руке и хорошо выглядит - что ещё нужно от ножа? Ещё бы только не пришлось его так долго вытачивать..@@@PID_REVKNIFE2 1&PID_REVFIST1 1@@PID_KNIFE 1@script fix_boy@fix_Tribal}
{1230}{}{PID_MEDNEEDLE@Нет ничего сложного в том, что бы скрутить из проволки подобие иглы.@@@PID_CRAFT_M_BARS 1@PID_REVFIST1 1@PID_MEDNEEDLE 1@script fix_boy@fix_Tribal}
{1235}{}{PID_SHIV@Стачиваем лишнее, вдалбливаем в рукоятку - и долото/шило готово!@@@PID_FIREWOOD 1&PID_REVFIST1 1&PID_REVKNIFE1 1@@PID_SHIV 1@script fix_boy@fix_Tribal}
{1240}{}{PID_SPEAR@Настало время нести смерть на расстоянии!@@@PID_REVKNIFE1 1&PID_PART_OF_ROPE 2&PID_SHARPENED_POLE 1@@PID_SPEAR 1@script fix_boy@fix_Tribal}
{1241}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, обмотать рукоять кожей, и этот нож уже можно называть оружием.@@SK_OUTDOORSMAN 100&SK_REPAIR 150&SK_MELEE_WEAPONS 100@PID_IRON_PLATE 1&PID_FIREWOOD 1&PID_CRAFT_L_HIDE 1&PID_FLINT 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_COMBAT_KNIFE 1@script fix_boy@fix_Workbench}
{1245}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@@PID_REVFIST1 2&PID_ROCK 2&PID_PART_OF_ROPE 2&PID_SHARPENED_POLE 1@@PID_SLEDGEHAMMER 1@script fix_boy@fix_Tribal}
{1250}{}{PID_BOOMERANG_LOW@Жалкое подобие метательного ножа.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@@PID_BOOMERANG_LOW 1@script fix_boy@fix_Tribal}
{1255}{}{PID_REV_BALL1@Пара грузил и прочная верёвка - если этот снаряд не опутает жертву, то хотя бы больно стукнет!@@@PID_PART_OF_ROPE 3&PID_ROCK 2@@PID_REV_BALL1 1@script fix_boy@fix_Tribal}
{1260}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@@@PID_REVKNIFE2 1&PID_CLUB 1&PID_PART_OF_ROPE 2@PID_REVFIST1 1@PID_AXE 1@script fix_boy@fix_Tribal}
{1265}{}{PID_SHOVEL@Найдите где-нибудь палку и насадите на один из ее концов подходящую железку.@@@PID_METAL_LIST_MEH 1&PID_SHARPENED_POLE 1&PID_PART_OF_ROPE 2@PID_REVFIST1 1@PID_SHOVEL 1@script fix_boy@fix_Tribal}
{1270}{}{PID_SHARP_SPEAR@На хорошее копьё не жалко и нож потратить.@@SK_REPAIR 100|SK_OUTDOORSMAN 150|SK_MELEE_WEAPONS 150@PID_KNIFE 1&PID_REVFIST1 1&PID_PART_OF_ROPE 3&PID_SHARPENED_POLE 1@@PID_SHARP_SPEAR 1@script fix_boy@fix_FreeHands}
{1275{}{PID_CUTTHROAT@Бритва, мало чем отличается от ножа-бабочки. Отличается от обычного ножа крайне острой заточкой.@@@PID_CRAFT_M_BARS 1&PID_REVFIST1 1&PID_KNIFE 1@@PID_CUTTHROAT 1@script fix_boy@fix_FreeHands}
{1280}{}{PID_SCISSORS@Довольно таки нежный предмет, сложный в изготовлении на коленке.@@@PID_KNIFE 2&PID_CRAFT_M_BARS 2&PID_REVFIST1 2@@PID_SCISSORS 1@script fix_boy@fix_FreeHands}
{1285}{}{PID_CROWBAR@Нежными ударами молота загибаем кусок арматуры и затем затачиваем один конец.@@@PID_IRON_PROD 1&PID_REVKNIFE1 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@script fix_boy@fix_FreeHands}
{1290}{}{PID_SWITCHBLADE@Простенький выкидной нож - удобное оружие, которое легко можно незаметно пронести "в рукаве".@@SK_REPAIR 100|SK_OUTDOORSMAN 150|SK_MELEE_WEAPONS 150@PID_SHORT_TUBE 1|PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_CUTTHROAT 1@@PID_SWITCHBLADE 1@script fix_boy@fix_FreeHands}
{1295}{}{PID_REV_BALL2@Укрепив верёвку пластиковой смесью и навтыкав в неё острых кусков стекла, вы значительно усложнили процесс освобождения из этих пут.@@SK_SCIENCE 100|SK_OUTDOORSMAN 100@PID_REV_BALL1 1&PID_CHEMICALS 1&PID_CRAFT_M_JUNK 1@@PID_REV_BALL2 1@script fix_boy@fix_FreeHands}
{1300}{}{PID_MULTI_TOOL@Плоскогубцы, отвертка и расческа одновременно. Посложней, чем ножницы мастерить, но оно того стоит!@@SK_REPAIR 150@PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 4&PID_SHIV 1@@PID_MULTI_TOOL 1@script fix_boy@fix_FreeHands}
{1305}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь.@@@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@PID_MULTI_TOOL 1@PID_BRASS_KNUCKLES 1@script fix_boy@fix_FreeHands}
{1306}{}{PID_SPIKED_KNUCKLES@Что железяка с прорезями для пальцев уже не внушает у других уважение к вам? Не проблема! Просто приварите несколько шипов и вас снова все зауважают. @@SK_REPAIR 80&SK_UNARMED 100|SK_MELEE_WEAPONS 100@PID_BRASS_KNUCKLES 1&PID_SPIKE_MEH 4@PID_MULTI_TOOL 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SPIKED_KNUCKLES 1@script fix_boy@fix_Workbench}
{1310}{}{PID_PICKAXE@В качестве ручки потребуется взять качественную доску, а ударной - два куска бруса и соединительный элемент.@@SK_REPAIR 100@PID_WOOD_PART 1&PID_IRON_BAR 2&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_PICKAXE 1@script fix_boy@fix_Workbench}
{1315}{}{PID_CRAFT_M_BARS@Штампуем железяки из стального листа.@@SK_SCIENCE 100&SK_REPAIR 100@PID_IRON_PLATE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_CRAFT_M_BARS 4@script fix_boy@fix_FreeHands}
{1320}{}{PID_WELDING@Берем батареи на блок питания для дуги, кусачки пойдут как удержатель электрода, а куча хлама на сами электроды.@@SK_REPAIR 200&SK_SCIENCE 150@PID_CUENCELL_LOW 8|PID_SMALL_ENERGY_CELL 4&PID_MULTI_TOOL 1&PID_CRAFT_M_BARS 4&PID_EMKOCT_MEH 1&PID_WORKBENCH_TOKEN 1@@PID_WELDING 1@script fix_boy@fix_Workbench}
{1325}{}{PID_WELDING@Берем несколько ёмкостей, наполняем их топливом и активирем реагентом.@@SK_REPAIR 100&SK_SCIENCE 200@PID_FLAMETHROWER_FUEL 8&PID_MULTI_TOOL 1&PID_CRAFT_M_BARS 4&PID_EMKOCT_MEH 3&PID_WORKBENCH_TOKEN 1@@PID_WELDING 1@script fix_boy@fix_Workbench}
{1330}{}{PID_LIGHTER@Соберите простенький корпус для самодельной Зиппо, набейте его смоченной в керосине ватой и закройте, добавив фитиль из тряпки в том-же керосине, и кремень для высекания искр. Огоньку?@@SK_SCIENCE 100@PID_BANKA_MEH 1&PID_FLINT 1&PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1&PID_BOOZE 1&PID_CHEMICALS 1@@PID_LIGHTER 1@script fix_boy@fix_FreeHands}
{1335}{}{PID_LIGHTER@Соберите простенький корпус для самодельной Зиппо, теперь в новом футляре.@@SK_SCIENCE 100@PID_PB_FOR_AMMO 1&PID_FLINT 1&PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1&PID_FLAMETHROWER_FUEL 2@PID_MULTI_TOOL 1@PID_LIGHTER 1@script fix_boy@fix_FreeHands}
{1340}{}{PID_ROD@Прийдётся попотеть, но с помощью кусачек, горелки, отвёртки и молотка можно сделать вполне пригодные рыболовные снасти.@@@PID_SHARPENED_POLE 2&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_ROD 1@exp 100 script fix_boy@fix_FreeHands}
{1345}{}{PID_HOOK@Прийдётся попотеть, но с помощью кусачек, горелки, отвёртки и молотка можно сделать вполне пригодные рыболовные снасти.@@@PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_HOOK 1@exp 100 script fix_boy@fix_FreeHands}
{1350}{}{PID_STRING@Прийдётся попотеть, но с помощью кусачек, горелки, отвёртки и молотка можно сделать вполне пригодные рыболовные снасти.@@@PID_BOTTLE_EMPTY 3&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_STRING 1@exp 100 script fix_boy@fix_FreeHands}
{1355}{}{PID_THROWING_KNIFE@Вырезаем и затачиваем метательные ножи.@@SK_THROWING 150&SK_REPAIR 125@PID_IRON_PLATE 1&PID_FLINT 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_THROWING_KNIFE 3@script fix_boy@fix_Workbench}
{1360}{}{PID_WRENCH@Разводной ключ.@@@PID_IRON_DETALS 1&PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 1@PID_WELDING 1&PID_MULTI_TOOL 1@PID_WRENCH 1@script fix_boy@fix_Workbench}
{1365}{}{PID_SUPER_TOOL_KIT@Мобильный набор высокоточных инструментов - держи всё под рукой!@@SK_REPAIR 200@PID_MULTI_TOOL 2&PID_CUTTHROAT 1&PID_SCISSORS 1&PID_CROWBAR 1&PID_WRENCH 1&PID_CRAFT_M_BARS 5&PID_WOOD_PART 6|PID_METAL_LIST_MEH 4@PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@script fix_boy@fix_Workbench}
{1370}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле. Они дорогого стоят.@@SK_LOCKPICK 200@PID_CRAFT_M_STEL 1&PID_IRON_DETALS 2&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_CRAFT_L_HIDE 2&PID_WORKBENCH_TOKEN 1@PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_LOCKPICKS 1@script fix_boy@fix_Workbench}
{1375}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами и экипировкой! Такой набор - на вес золота.@@SK_LOCKPICK 250@PID_LOCKPICKS 2&PID_MULTI_TOOL 1&PID_CRAFT_L_HIDE 1&PID_MOTOGLES 1&PID_WORKBENCH_TOKEN 1@PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_EXP_LOCKPICK_SET 1@script fix_boy@fix_Workbench}
{1380}{}{PID_FLocks@Эта маленькая шпилька способна спати вас из самых невероятных ситуаций.@@SK_LOCKPICK 100@PID_CRAFT_M_BARS 1@@PID_FLocks 1@script fix_boy@fix_None}
{1400}{}{PID_ZAPLATKA_CRAFT_CHEM@Разделитель раздела для создания реактивов, реагентов и химических смесей.@@@PID_ZAPLATKA_CRAFT_CHEM 1@@PID_ZAPLATKA_CRAFT_CHEM 1@script fix_boy@fix_Tribal}
{1405}{}{PID_HEALING_POWDER@Разотрите высушенные на солнце ингредиенты и заверните в тряпочку.@@@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_CRAFT_L_RAGS 1@PID_REVFIST1 1@PID_HEALING_POWDER 1@script fix_boy@fix_Tribal}
{1410}{}{PID_FPSHL6@Мыло сделать намного проще, чем вы думали.@@SK_SCIENCE 100|SK_OUTDOORSMAN 150@PID_MEAT 5&PID_BOTTLE_FULL 1&PID_CHEMICALS 1&PID_MUTATED_FRUIT 5&PID_FIREPLACE_TOKEN 1@PID_KNIFE 1&PID_BANKA_MEH 1@PID_FPSHL6 1@script fix_boy@fix_FreeHands}
{1415}{}{PID_itsoap01@Мыло сделать намного проще, чем вы думали.@@SK_SCIENCE 100|SK_OUTDOORSMAN 150@PID_RAD_MEAT 5&PID_BOTTLE_FULL 1&PID_CHEMICALS 1&PID_MUTATED_FRUIT 1&PID_FIREPLACE_TOKEN 1@PID_KNIFE 1&PID_BANKA_MEH 1@PID_itsoap01 1@script fix_boy@fix_FreeHands}
{1420}{}{PID_FORSAGE_GUM@Нюка, мутофрукт и немного фантазии.@@SK_SCIENCE 100|SK_OUTDOORSMAN 150@PID_HEALING_POWDER 1&PID_NUKA_COLA 1&PID_MUTATED_FRUIT 1&PID_MUSH_LOW 1&PID_FIREPLACE_TOKEN 1@PID_KNIFE 1&PID_BANKA_MEH 1@PID_FORSAGE_GUM 1@script fix_boy@fix_FreeHands}
{1425}{}{PID_CARAMEL2@Нюка, мутофрукт и немного фантазии.@@SK_SCIENCE 100|SK_OUTDOORSMAN 150@PID_HEALING_POWDER 1&PID_NUKA_COLA 1&PID_MUTATED_FRUIT 1&PID_MUSH_LOW 1&PID_FIREPLACE_TOKEN 1@PID_KNIFE 1&PID_BANKA_MEH 1@PID_CARAMEL2 1@script fix_boy@fix_FreeHands}
{1430}{}{PID_itcandy@Нюка, мутофрукт и немного фантазии.@@SK_SCIENCE 100|SK_OUTDOORSMAN 150@PID_HEALING_POWDER 1&PID_NUKA_COLA 1&PID_MUTATED_FRUIT 1&PID_MUSH_LOW 1&PID_FIREPLACE_TOKEN 1@PID_KNIFE 1&PID_BANKA_MEH 1@PID_itcandy 1@script fix_boy@fix_FreeHands}
{1435}{}{PID_CHEMICALS@Базовых познаний в химии хватает для того что бы экспериментальным путём выварить и процедить из минеральной крошки небольшую порцию химического реагента.@@SK_SCIENCE 150|SK_OUTDOORSMAN 150|SK_DOCTOR 150@PID_MINERAL 1&PID_GLASS_BOTTLE_FULL 1&PID_CRAFT_L_RAGS 1&PID_FIREPLACE_TOKEN 1@PID_SLEDGEHAMMER 1@PID_CHEMICALS 1@script fix_boy@fix_FreeHands}
{1440}{}{PID_GUNPOWDER@В процессе приготовления главное не надышаться ядовитыми парами.@@SK_SCIENCE 200@PID_CHEMICALS 1&PID_MUSH_LOW 2&PID_GLASS_BOTTLE_FULL 2&PID_FIREPLACE_TOKEN 1@@PID_GUNPOWDER 3&PID_BOTTLE_GLASS 3@script fix_boy@fix_FreeHands}
{1445}{}{PID_HYPODERMIC_NEEDLE@Несколько шприцов ручной сборки.@@@PID_BOTTLE_GLASS 4&PID_MEDNEEDLE 4&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1&PID_FIREPLACE_TOKEN 1@PID_HYPODERMIC_NEEDLE 4@script fix_boy@fix_Delayed}
{1450}{}{PID_HYPODERMIC_NEEDLE@Если подойти к делу с умом, то можно сэкономить немало расходников.@@@PID_GLASS 2&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 1@PID_SUPER_TOOL_KIT 1&PID_FIREPLACE_TOKEN 1@PID_HYPODERMIC_NEEDLE 12@script fix_boy@fix_Delayed}
{1455}{}{PID_KOSYAK@Косячок@@PE_FLOWER_CHILD 1@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1&PID_CRAFT_L_RAGS 1@@PID_KOSYAK 1@script fix_boy@fix_FreeHands}
{1460}{}{PID_ANTIDOTE@Противоядие.@@SK_OUTDOORSMAN 200|SK_SCIENCE 150&SK_DOCTOR 150@PID_XANDER_ROOT 3&PID_BOOZE 1&PID_SCORPION_TAIL 1&PID_GLASS_BOTTLE_FULL 1&PID_FIREPLACE_TOKEN 1@@PID_ANTIDOTE 2@script fix_boy@fix_Workbench}
{1465}{}{PID_ANTIDOTE@Настоящие доктора и учёные могут синтезировать противоядие из любого органического активного компонента: грибов, водорослей или хитина.@@SK_OUTDOORSMAN 100&SK_DOCTOR 100&SK_SCIENCE 125@PID_ROT_GUT 1&PID_CHEMICALS 1&PID_GLASS_BOTTLE_FULL 1&PID_MUSH_LOW 1|PID_MANTIS_SHELL 3|PID_ALGAE 1@PID_LIGHTER 1&PID_BOTTLE_GLASS 3&PID_HYPODERMIC_NEEDLE 2&PID_BOOZE 1&PID_WORKBENCH_TOKEN 1@PID_ANTIDOTE 3@script fix_boy@fix_Workbench}
{1470}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@@SK_SCIENCE 125&SK_DOCTOR 125@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1&PID_BOOZE 1&PID_HEALING_POWDER 2@PID_FIREPLACE_TOKEN 1@PID_STIMPAK 1&PID_BOTTLE_GLASS 1&PID_BOTTLE_EMPTY 1@script fix_boy@fix_Workbench}
{1475}{}{PID_ANTISEPTIC@Вскипятите воду и засыпьте в нее растертые в порошок брок и зандер, добавьте немного самогона и тщательно все перемешайте.@@SK_SCIENCE 150&SK_DOCTOR 150@PID_GLASS_BOTTLE_FULL 1&PID_ANTIDOTE 1&PID_BOOZE 1&PID_HEALING_POWDER 1@PID_FIREPLACE_TOKEN 1@PID_ANTISEPTIC 3@script fix_boy@fix_Workbench}
{1480}{}{PID_PILLS@Брок выварить в кипятке и выстоять в течении часа, процедить. Пока выстаивается отвар, приготовьте основу для таблеткок на основе клейстера из кукурузной муки. Катализатором фармокологического действия, а также замечательным консервантом станет эмульсия из стандартного стимулятора. Соблюдайте стерильность!@@SK_SCIENCE 150&SK_DOCTOR 200@PID_ROT_GUT 1&PID_ANTISEPTIC 1&PID_BOTTLE_FULL 1&PID_HEALING_POWDER 1&PID_CHEMICALS 1@PID_FIREPLACE_TOKEN 1@PID_PILLS 1&PID_BOTTLE_GLASS 3@script fix_boy@fix_Workbench}
{1485}{}{PID_MENTATS@Ментаты. Нужно что-то, что бы торкало и действовало дольше, чем винт, но не с такими отходняками? Для начала вам понадобятся те же самые грибы, содержащие в себе небольшое количество необходимых солей. Измельчаем их,  отбиваем до получения концентрата. В итоге, получившийся концентрат разделяем на более мелкие дозы, добавляем по вкусу брока, что бы это дерьмо не так противно было держать во рту, и вот-у вас все готово!@@SK_DOCTOR 200|SK_SCIENCE 200&PE_FLOWER_CHILD 1@PID_MUTATED_FRUIT 1&PID_HEALING_POWDER 1&PID_MUSH_LOW 1@PID_FIREPLACE_TOKEN 1@PID_MENTATS 1@script fix_boy@fix_Workbench}
{1490}{}{PID_JET@Джет. Ну что же, не зря Майрон, или его последователи капали вам на мозги, пытаясь вбить вам в голову весь процесс синтеза правнука первитина. Сначала понадобятся особые грибы, произрастающие только в помете двухголовых друзей. Раздобыв их, мы для начала измельчаем грибы и выгоняем из них эмульсию. Следом добавляем немного кристаллизированного йода. Оставляем отстояться, потом еще раз выгоняем получившуюся жидкостью до образования осадка. Этот осадок-и есть то, что нам нужно.@@SK_DOCTOR 200&SK_SCIENCE 200&PE_FLOWER_CHILD 1@PID_EMPTY_JET 5&PID_ANTISEPTIC 1&PID_MUSH_LOW 2@PID_FIREPLACE_TOKEN 1&PID_BOTTLE_GLASS 1@PID_JET 5@script fix_boy@fix_Workbench}
{1495}{}{PID_PSYCHO@Вы долго ломали голову над тем, что бы сделать самодельный боевой психостимулятор, временно усиливающий боевые характеристики бойца. Наблюдения за ФЭВ-мутантами дали вам подсказку..@@SK_DOCTOR 200&SK_SCIENCE 200&PE_FLOWER_CHILD 1@PID_MUTATED_GLAND 1&PID_ANTISEPTIC 1&PID_GLASS_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1@PID_FIREPLACE_TOKEN 1&PID_BOTTLE_GLASS 1@PID_PSYCHO 1@script fix_boy@fix_Workbench}
{1500}{}{PID_MOLOTOV_COCKTAIL@Разливаем по бутылкам топливо, вставляем тряпки - молотовы готовы к применению!@@SK_SCIENCE 100&SK_THROWING 100@PID_FLAMETHROWER_FUEL 1&PID_CRAFT_L_RAGS 1&PID_BOTTLE_GLASS 1@@PID_MOLOTOV_COCKTAIL 1@script fix_boy@fix_FreeHands}
{1505}{}{PID_MOLOTOV_COCKTAIL@Эконом версия молотова, для самых смышлёных.@@SK_SCIENCE 150&SK_THROWING 150@PID_ROT_GUT 1&PID_CRAFT_L_RAGS 1@@PID_MOLOTOV_COCKTAIL 1@script fix_boy@fix_Delayed}
{1510}{}{PID_ROT_GUT@Адский коктейль. Взболтать, но не смешивать.@@SK_SCIENCE 150|SK_OUTDOORSMAN 150@PID_BOOZE 1&PID_BEER 1@@PID_ROT_GUT 2@script fix_boy@fix_Delayed}
{1600}{}{PID_ZAPLATKA_CRAFT_AMMO@Разделитель раздела для создания боеприпасов.@@@PID_ZAPLATKA_CRAFT_AMMO 1@@PID_ZAPLATKA_CRAFT_AMMO 1@script fix_boy@fix_Tribal}
{1605}{}{PID_DARTS_LOW@Длинные ровные острые деревянные полуметровые болты без оперения. Чем попало такое не вырезать.@@@PID_FIREWOOD 1|PID_WOOD_PLANK 1@PID_CUTTHROAT 1@PID_DARTS_LOW 2@script fix_boy@fix_Tribal}
{1610}{}{PID_PB_FOR_AMMO@Кропотливо выполненные вручную гильзы.@@SK_REPAIR 200@PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_METAL_LIST_MEH 1&PID_FIREPLACE_TOKEN 1@PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 4@script fix_boy@fix_FreeHands}
{1615}{}{PID_PB_FOR_AMMO@Перебирите имеющиеся стрелянные гильзы, и выберите подходящие.@@SK_REPAIR 100@PID_gilza 14@PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 1@script fix_boy@fix_None}
{1620}{}{PID_10mm_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100|SK_BIG_GUNS 100&SK_REPAIR 100@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1@PID_10mm_LOW 4@script fix_boy@fix_FreeHands}
{1625}{}{PID_044mag_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100|SK_BIG_GUNS 100&SK_REPAIR 100@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_044mag_LOW 4@script fix_boy@fix_Workbench}
{1630}{}{PID_223_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100|SK_BIG_GUNS 100&SK_REPAIR 100@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1@PID_223_LOW 3@script fix_boy@fix_Workbench}
{1635}{}{PID_12g_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100|SK_BIG_GUNS 100&SK_REPAIR 100@PID_CRAFT_L_RAGS 1&PID_CRAFT_M_BARS 2&PID_GUNPOWDER 1@PID_MULTI_TOOL 1@PID_12g_LOW 4@script fix_boy@fix_Workbench}
{1640}{}{PID_14mm_LOW@Вручную заряженные патроны. Очень некачественная сборка!@@SK_SMALL_GUNS 100|SK_BIG_GUNS 100&SK_REPAIR 100@PID_PB_FOR_AMMO 1&PID_CRAFT_M_BARS 1&PID_GUNPOWDER 1@PID_MULTI_TOOL 1@PID_14mm_LOW 3@script fix_boy@fix_Workbench}
{1645}{}{PID_CUENCELL_LOW@извлекаем радиоактивные элементы, естанавливаем их в оболочку, добавляем реагенты, обматываем фольгой и закрываем в корпус@@SK_SCIENCE 200&SK_REPAIR 200@PID_RAD_LOW 1&PID_CRAFT_M_BARS 4&PID_BANKA_MEH 4&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_CUENCELL_LOW 8@script fix_boy@fix_Workbench}
{1650}{}{PID_FLAMETHROWER_FUEL@Найдите побольше пластика, растворяйте в ацетоне, пока эта смесь не станет густой. Добавьте в ёмкость грибов и молитесь что бы не рвануло.@@SK_SCIENCE 200&SK_REPAIR 100@PID_CHEMICALS 2&PID_MUSH_LOW 2&PID_BOTTLE_EMPTY 10&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL 8@script fix_boy@fix_Workbench}
{1655}{}{PID_10MM@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_10MM_JHP 8@script fix_boy@fix_Workbench}
{1660}{}{PID_10MM_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_10MM_AP 8@script fix_boy@fix_Workbench}
{1665}{}{PID_10MM_FMJ@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_10MM_FMJ 8@script fix_boy@fix_Workbench}
{1670}{}{PID_44_MAGNUM_JHP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_44_MAGNUM_JHP 9@script fix_boy@fix_Workbench}
{1675}{}{PID_44_FMJ_MAGNUM@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_44_FMJ_MAGNUM 9@script fix_boy@fix_Workbench}
{1680}{}{PID_14MM_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_14MM_AP 6@script fix_boy@fix_Workbench}
{1685}{}{PID_SHOTGUN_SHELLS@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 125|SK_BIG_GUNS 125@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_BOTTLE_EMPTY 5@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SHOTGUN_SHELLS 10@script fix_boy@fix_Workbench}
{1690}{}{PID_223_FMJ@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_223_FMJ 7@script fix_boy@fix_Workbench}
{1695}{}{PID_223_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_223_AP 7@script fix_boy@fix_Workbench}
{1700}{}{PID_45_CALIBER_AMMO@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_45_CALIBER_AMMO 8@script fix_boy@fix_Workbench}
{1705}{}{PID_45CAL_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_45CAL_AP 8@script fix_boy@fix_Workbench}
{1710}{}{PID_9MM_AMMO@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_9MM_AMMO 10@script fix_boy@fix_Workbench}
{1715}{}{PID_9MM_BALL@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_9MM_BALL 11@script fix_boy@fix_Workbench}
{1720}{}{PID_7_62MM_AMMO@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_7_62MM_AMMO 10@script fix_boy@fix_Workbench}
{1725}{}{PID_762_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_762_AP 10@script fix_boy@fix_Workbench}
{1730}{}{PID_5MM_JHP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_5MM_JHP 10@script fix_boy@fix_Workbench}
{1735}{}{PID_5MM_AP@Снаряжаем качественные патроны, используя качественное точное оборудование и инструменты.@@SK_REPAIR 200&SK_SCIENCE 150&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_PB_FOR_AMMO 1&PID_GUNPOWDER 1&PID_IRON_DETALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_5MM_AP 10@script fix_boy@fix_Workbench}
{1740}{}{PID_SMALL_ENERGY_CELL@Пересобираем низкокачественные батарейки в новом герметичном корпусе и заливаем свежий реагент.@@SK_REPAIR 100&SK_SCIENCE 200&SK_ENERGY_WEAPONS 100@PID_CUENCELL_LOW 4&PID_IRON_DETALS 1&PID_CHEMICALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SMALL_ENERGY_CELL 4@script fix_boy@fix_Workbench}
{1800}{}{PID_ZAPLATKA_CRAFT_SMALL@Разделитель раздела для создания стрелкового оружия малого калибра.@@@PID_ZAPLATKA_CRAFT_SMALL 1@@PID_ZAPLATKA_CRAFT_SMALL 1@script fix_boy@fix_Tribal}
{1805}{}{PID_ZIP_GUN@Хочется напугать дикарей гром-палкой, но руки из жопы? Тогда делаем лёгкий кривокосый простенький чиркаш! Главное - не удивляться, если он рванёт в вашей руке при выстреле.@@@PID_SHORT_TUBE 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_FLINT 1&PID_CLUB 1@@PID_ZIP_GUN 1@script fix_boy@fix_FreeHands}
{1810}{}{PID_SPRINGER_RIFLE@Примитивный мушкет малого калибра из подручных средств. Ствол очень быстро забивается пороховыми газами.@@SK_SMALL_GUNS 100&SK_REPAIR 100@PID_TUBE 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_FLINT 1&PID_CLUB 1@@PID_SPRINGER_RIFLE 1@script fix_boy@fix_FreeHands}
{1815}{}{PID_SPEARTHROWER1_LOW@"Пара пружин, рычаги и рама" - так вы думали, пока не поняли что без калибровки и доводки оно швыряет болты куда попало и постоянно делает осечки. Но это всё уже позади. К тому же, вместо пружинного механизма, вполне можно использовать крепкую проволку или грубую тетиву.@@SK_SMALL_GUNS 100&SK_SCIENCE 100&SK_REPAIR 100@PID_CRAFT_M_JUNK 3&PID_DETAL_MEH 1&PID_CLUB 1&PID_ROPE 1|PID_CRAFT_M_BARS 3@PID_MULTI_TOOL 1@PID_SPEARTHROWER1 1@script fix_boy@fix_FreeHands}
{1820}{}{PID_REVOLVER_PART@Используя банку в качестве корпуса, вы собираете в ней камры для пуль.@@SK_SMALL_GUNS 150&SK_REPAIR 150&SK_SCIENCE 100@PID_BANKA_MEH 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REVOLVER_PART 1@script fix_boy@fix_Workbench}
{1825}{}{PID_REVOLVER_LOW@Использовав черкаш за основу, вы собираете вместе более вменяемый ствол, спусковой механизм и барабан. Самодельный револьвер готов!@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_REVOLVER_PART 1&PID_ELECTO_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REVOLVER_LOW 1@script fix_boy@fix_Workbench}
{1830}{}{PID_PISTOL_LOW@Использовав черкаш за основу, вы собираете примитивный пистолет. Он явно нуждается в доработке.@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_SOED_MEH 1&PID_WORKBENCH_TOKEN 1&PID_CRAFT_M_JUNK 1|PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1@PID_PISTOL_LOW 1@script fix_boy@fix_Workbench}
{1835}{}{PID_SMOKE_GUN_LOW@Переточив ствол под меньший калибр и модернизировав зарядно-спусковой механизм вы вытачиваете неснимаемый самодельный глушитель, позволяющий не выдавать себя при стрельбе.@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_PISTOL_LOW 1&PID_TUBE 1&PID_DETAL_MEH 1&PID_CRAFT_L_RAGS 2&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SMOKE_GUN_LOW 1@script fix_boy@fix_Workbench}
{1840}{}{PID_SHOTPISTOL_LOW@Берем парочку труб подходящего диаместра, воруем спусковой механизм у простенького пистолета, модернизируем, тщательно закрепляем и получаем подобие дробовика.@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_PISTOL_LOW 1&PID_SHORT_TUBE 2&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SHOTPISTOL_LOW 1@script fix_boy@fix_Workbench}
{1845}{}{PID_REV_RIFLE_LOW@Слегка переделываем мушкет, получая простенькую револьверную винтовку.@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_SPRINGER_RIFLE 1&PID_REVOLVER_PART 1&PID_ELECTO_MEH 1&PID_TUBE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REV_RIFLE_LOW 1@script fix_boy@fix_Workbench}
{1850}{}{PID_SNIPER_GUN_LOW@Переточка под другой калибр и усиление ствола позволяют превратить жалкий мушкет в грозную винтовку.@@SK_SMALL_GUNS 150&SK_REPAIR 200&SK_SCIENCE 100@PID_SPRINGER_RIFLE 1&PID_TUBE 2&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 2&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SNIPER_GUN_LOW 1@script fix_boy@fix_Workbench}
{1855}{}{PID_LOW_SNIPER2@Ваших навыков достаточно для модернизации винтовки экспериментальным путём. Новая конструкция имеет более высокую точность, дальность и урон, но жутко громыхает.@@SK_SMALL_GUNS 150&SK_REPAIR 200&SK_SCIENCE 150@PID_SNIPER_GUN_LOW 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_TUBE 1&PID_CRAFT_M_STEL 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOW_SNIPER2 1@script fix_boy@fix_Workbench}
{1860}{}{PID_LOW_SNIPER3@Учитывая все возможные особенности и ограничения подобного самодела, вы максимально модернизируете винтовку без помощи нормального оборудования, используя один лишь верстак с простецкими инструментами.@@SK_SMALL_GUNS 200&SK_REPAIR 225&SK_SCIENCE 150@PID_LOW_SNIPER2 1&PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 3&PID_TUBE 2&PID_CRAFT_M_STEL 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOW_SNIPER3 1@script fix_boy@fix_Workbench}
{1865}{}{PID_QUADRO_SHOTGUN@Самодельный дробовик с четырьмя стволами.@@SK_SMALL_GUNS 150&SK_REPAIR 150&SK_SCIENCE 100@PID_CRAFT_L_HIDE 2&PID_TUBE 4&PID_SOED_MEH 1&PID_DETAL_MEH 4&PID_FIREWOOD 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_SCISSORS 1@PID_QUADRO_SHOTGUN 1@script fix_boy@fix_Workbench}
{1870}{}{PID_SAWED_OFF_SHOTGUN@Модернизируем двуствольный пистолет так, что бы можно было покрывать выстрелом широкую область.@@SK_REPAIR 200&SK_SMALL_GUNS 150&SK_SCIENCE 125@PID_SHOTPISTOL_LOW 1&PID_CRAFT_M_STEL 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SAWED_OFF_SHOTGUN 1@script fix_boy@fix_Workbench}
{1875}{}{PID_SHOTGUN@Мощный короткостволный дробовик. Мечта любого фермера.@@SK_REPAIR 225&SK_SMALL_GUNS 150&SK_SCIENCE 125@PID_SAWED_OFF_SHOTGUN 1&PID_TUBE 2&PID_SOED_MEH 2&PID_CRAFT_M_JUNK 4&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SHOTGUN 1@script fix_boy@fix_Workbench}
{1880}{}{PID_GECKO_LOW@Гладкоствольный дробовик.@@SK_REPAIR 200&SK_SMALL_GUNS 150&SK_SCIENCE 100@PID_SPRINGER_RIFLE 1&PID_TUBE 1&PID_FIREWOOD 2&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_EMKOCT_MEH 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_GECKO_LOW 1@script fix_boy@fix_Workbench}
{1885}{}{PID_DRUM_GUN_LOW@Перепиливаем диаметр канала ствола под 9мм патрон и возимся с механизмом ствольной коробки для автоматической стрельбы. Дальше всё пойдёт само по себе.@@SK_SMALL_GUNS 150&SK_REPAIR 175&SK_SCIENCE 125@PID_PISTOL_LOW 1&PID_ELECTO_MEH 1&PID_DETAL_MEH 1&PID_PERED_MEH 1&PID_CRAFT_M_BARS 2&PID_IRON_DETALS 2&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_DRUM_GUN_LOW 1@script fix_boy@fix_FreeHands}
{1890}{}{PID_9MM_MAUSER@Надежная конструкция, стильный дизайн и простота сборки!@@SK_SMALL_GUNS 185&SK_REPAIR 200&SK_SCIENCE 200@PID_SHORT_TUBE 1&PID_METAL_LIST_MEH 1&PID_CRAFT_M_STEL 1&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_IRON_DETALS 2&PID_CRAFT_M_BARS 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_9MM_MAUSER 1@script fix_boy@fix_FreeHands}
{1895}{}{PID_MAUSER_SMG@Как настоящие механики, соорудим чудо инженерной мысли заменив полуавтоматический механизм подачи патронов на автоматический!@@SK_SMALL_GUNS 175&SK_REPAIR 225&SK_SCIENCE 200@PID_9MM_MAUSER 1&PID_PERED_MEH 1&PID_CRAFT_M_BARS 4&PID_DETAL_MEH 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_MAUSER_SMG 1@script fix_boy@fix_FreeHands}
{1900}{}{PID_HUNTING_RIFLE@Хочется пострелять из ружья, а однозарядные и револьверные системы вас больше не возбуждают?@@SK_SMALL_GUNS 225&SK_REPAIR 200&SK_SCIENCE 230@PID_TUBE 1&PID_SOED_MEH 2&PID_ELECTO_MEH 2&PID_FIREWOOD 3&PID_DETAL_MEH 1&PID_IRON_DETALS 3&PID_CRAFT_M_BARS 6&PID_CRAFT_M_JUNK 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_HUNTING_RIFLE 1@script fix_boy@fix_FreeHands}
{1905}{}{PID_SCOPED_HUNTING_RIFLE@Сделать примитивный телескоп из всякого хлама и прикрутить готовый прицел к винтовке.@@SK_SMALL_GUNS 150&SK_REPAIR 170&SK_SCIENCE 200@PID_HUNTING_RIFLE 1&PID_CRAFT_M_BARS 2&PID_SHORT_TUBE 1&PID_LINZA 2&PID_CRAFT_M_JUNK 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SCOPED_HUNTING_RIFLE 1@script fix_boy@fix_FreeHands}
{1910}{}{PID_DESERT_EAGLE@Нестареющая классика...@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 225@PID_SHORT_TUBE 1&PID_CRAFT_M_STEL 2&PID_SOED_MEH 2&PID_IRON_DETALS 4&PID_CRAFT_M_BARS 3@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_DESERT_EAGLE 1@script fix_boy@fix_FreeHands}
{1915}{}{PID_DESERT_EAGLE_EXT_MAG@Расширить магазин для Дезерт Игла не так сложно если знать его конструкцию.@@SK_SMALL_GUNS 180&SK_REPAIR 180&SK_SCIENCE 200@PID_DESERT_EAGLE 1&PID_ELECTO_MEH 1&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_DESERT_EAGLE_EXT_MAG 1@script fix_boy@fix_FreeHands}
{1920}{}{PID_44_MAGNUM_REVOLVER@Попыхтеть пару часов и револьвер вашей мечты готов! И помни ковбой... Перед тем как махать пушкой, спили мушку!@@SK_SMALL_GUNS 175&SK_REPAIR 225&SK_SCIENCE 200@PID_REVOLVER_LOW 1&PID_IRON_DETALS 3&PID_SOED_MEH 1&PID_CRAFT_M_STEL 1&PID_CRAFT_M_BARS 5@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_44_MAGNUM_REVOLVER 1@script fix_boy@fix_FreeHands}
{1925}{}{PID_44_MAGNUM_SPEEDLOADER@Вам не хватает 6 патронов в барабане и дальности стрельбы магнума? Ну чтож... Делаем или достаём откуда-то барабан револьвера (Желательно не из вашей красавицы, вы же не хотите его сломать, верно?) и фигачим с одной стороны хватательный механизм, чтобы патроны лишний раз не выпадали из барабана. Вуаля и ускоритель готов!@@SK_SMALL_GUNS 180&SK_REPAIR 180&SK_SCIENCE 200@PID_44_MAGNUM_REVOLVER 1&PID_REVOLVER_PART 1&PID_SHORT_TUBE 1&PID_CRAFT_M_BARS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_44_MAGNUM_SPEEDLOADER 1@script fix_boy@fix_FreeHands}
{1930}{}{PID_ASSAULT_RIFLE@Два слова - отсечка очереди.@@SK_SMALL_GUNS 250&SK_REPAIR 225&SK_SCIENCE 200@PID_TUBE 1&PID_SHORT_TUBE 1&PID_SOED_MEH 1&PID_ELECTO_MEH 3&PID_FIREWOOD 2&PID_DETAL_MEH 4&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 3@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_ASSAULT_RIFLE 1@script fix_boy@fix_FreeHands}
{1935}{}{PID_ASSAULT_RIFLE_EXT_MAG@Не устраивает боезапас в магазине вашей винтовки? Просто сделайте коробчатый магазин по-больше. Только не облажайтесь с подавателем и пружинкой внутри...@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 200@PID_ASSAULT_RIFLE 1&PID_ELECTO_MEH 1&PID_CRAFT_M_BARS 2&PID_DETAL_MEH 1&PID_CRAFT_M_JUNK 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_ASSAULT_RIFLE_EXT_MAG 1@script fix_boy@fix_FreeHands}
{1940}{}{PID_10MM_PISTOL@Делаем практичный и удобный пистолет под малый калибр.@@SK_SMALL_GUNS 185&SK_REPAIR 190&SK_SCIENCE 190@PID_SHORT_TUBE 1&PID_ELECTO_MEH 2&PID_DETAL_MEH 1&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 1&PID_DETAL_MEH 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_10MM_PISTOL 1@script fix_boy@fix_FreeHands}
{1945}{}{PID_10MM_SMG@Захотели быстро пострелять, а под рукой у вас только старый добрый 10мм пистолет? Не беда!@@SK_SMALL_GUNS 200&SK_REPAIR 200&SK_SCIENCE 200@PID_10MM_PISTOL 1&PID_ELECTO_MEH 2&PID_DETAL_MEH 2&PID_CRAFT_M_STEL 1&PID_SOED_MEH 1&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_10MM_SMG 1@script fix_boy@fix_FreeHands}
{1950}{}{PID_14MM_PISTOL@Слелай ручную пушку своими руками.@@SK_SMALL_GUNS 210&SK_REPAIR 210&SK_SCIENCE 200@PID_SHORT_TUBE 1&PID_ELECTO_MEH 2&PID_SOED_MEH 1&PID_DETAL_MEH 2&PID_IRON_DETALS 3&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 3&PID_FIREWOOD 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_14MM_PISTOL 1@script fix_boy@fix_FreeHands}
{1955}{}{PID_REMINGTON@Вам надоел громоздкий громкий Геккобо? Есть решение!@@SK_SMALL_GUNS 210&SK_REPAIR 225&SK_SCIENCE 210@PID_GECKO_LOW 1&PID_SOED_MEH 1&PID_DETAL_MEH 1&PID_CRAFT_M_STEL 2&PID_CRAFT_M_BARS 3&PID_IRON_DETALS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_REMINGTON 1@script fix_boy@fix_FreeHands}
{1960}{}{PID_COMBAT_SHOTGUN@Как много смысла в этой фразе - режим стрельбы очередями.@@SK_SMALL_GUNS 225&SK_REPAIR 250&SK_SCIENCE 230@PID_REMINGTON 1&PID_PERED_MEH 1&PID_DVIGAT_MEH 1&PID_SOED_MEH 2&PID_CRAFT_M_STEL 2&PID_CRAFT_M_BARS 8&PID_IRON_DETALS 6@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_COMBAT_SHOTGUN 1@script fix_boy@fix_FreeHands}
{1965}{}{PID_HK_CAWS@Булл-пап версия. Убойная крошка.@@SK_SMALL_GUNS 250&SK_REPAIR 250&SK_SCIENCE 250@PID_COMBAT_SHOTGUN 1&PID_CRAFT_M_BARS 4&PID_IRON_DETALS 8&PID_PERED_MEH 1&PID_SOED_MEH 2&PID_CRAFT_M_STEL 2&PID_ELECTO_MEH 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_HK_CAWS 1@script fix_boy@fix_FreeHands}
{2000}{}{PID_ZAPLATKA_CRAFT_BIG@Разделитель раздела для создания стрелкового оружия большого калибра.@@@PID_ZAPLATKA_CRAFT_BIG 1@@PID_ZAPLATKA_CRAFT_BIG 1@script fix_boy@fix_Tribal}
{2005}{}{PID_14mm_BIGGUN2_LOW@Крупнокалиберная пушка в здоровом металлическом коробе. Собрать легче чем носить...@@SK_BIG_GUNS 150&SK_REPAIR 200&SK_SCIENCE 100@PID_METAL_LIST_MEH 1&PID_DVIGAT_MEH 1&PID_TUBE 2&PID_SOED_MEH 2&PID_ELECTO_MEH 1&PID_EMKOCT_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_14mm_BIGGUN2_LOW 1@script fix_boy@fix_Workbench}
{2010}{}{PID_SPEARTHROWER2@Тяжёлый копьемёт.@@SK_BIG_GUNS 150&SK_SCIENCE 150&SK_REPAIR 200@PID_TUBE 2&PID_DVIGAT_MEH 1&PID_CRAFT_M_JUNK 4&PID_DETAL_MEH 1&PID_CLUB 1&PID_ROPE 1|PID_CRAFT_M_BARS 3@PID_MULTI_TOOL 1@PID_SPEARTHROWER2 1@script fix_boy@fix_Workbench}
{2015}{}{PID_BIGGUN_LOW@Берём трубу по больше. Скрепляем всё различными заклёпками и стяжками, делаем примитивный спусковой механизм. Для удобства делаем деревянный приклад-рукоять. Бо-оже, ну и убожество мысли...@@SK_BIG_GUNS 125&SK_REPAIR 150&SK_SCIENCE 125@PID_TUBE 1&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 2&PID_FIREWOOD 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_BIGGUN_LOW 1@script fix_boy@fix_FreeHands}
{2020}{}{PID_GATLING_LOW@Ваших знаний тяжелого оружия и истории достаточно чтобы смастерить простейший Гатлинг@@SK_BIG_GUNS 165&SK_REPAIR 190&SK_SCIENCE 200@PID_TUBE 6&PID_REVOLVER_PART 1&PID_ELECTO_MEH 1&PID_DETAL_MEH 1&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_GATLING_LOW 1@script fix_boy@fix_FreeHands}
{2025}{}{PID_FLAMER@Burn, baby, burn!@@SK_BIG_GUNS 180&SK_REPAIR 200&SK_SCIENCE 160@PID_EMKOCT_MEH 1&PID_TUBE 3&PID_IRON_DETALS 6&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 5&PID_DETAL_MEH 1&PID_LIGHTER 1&PID_FLAMETHROWER_FUEL 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_FLAMER 1@script fix_boy@fix_FreeHands}
{2030}{}{PID_IMPROVED_FLAMETHROWER@После сборки, можете начать писать книгу "Поваренная книга пиромана"@@SK_BIG_GUNS 225&SK_REPAIR 250&SK_SCIENCE 230@PID_FLAMER 1&PID_EMKOCT_MEH 1&PID_TUBE 1&PID_IRON_DETALS 2&PID_CRAFT_M_BARS 3&PID_SOED_MEH 1&PID_DETAL_MEH 1&PID_ELECTO_MEH 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_IMPROVED_FLAMETHROWER 1@script fix_boy@fix_FreeHands}
{2035}{}{PID_MINIGUN@В этом Минигана нет ничего от слова "мини"!@@SK_BIG_GUNS 225&SK_REPAIR 200&SK_SCIENCE 250@PID_GATLING_LOW 1&PID_CRAFT_M_STEL 3&PID_SOED_MEH 3&PID_SMALL_ENERGY_CELL 3&PID_IRON_DETALS 5&PID_CRAFT_M_BARS 4@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_MINIGUN 1@script fix_boy@fix_FreeHands}
{2040}{}{PID_M60@Не оружие, а произведение искусства.@@SK_BIG_GUNS 250&SK_REPAIR 250&SK_SCIENCE 250@PID_IRON_DETALS 10&PID_CRAFT_M_BARS 6&PID_SOED_MEH 2&PID_PERED_MEH 1&PID_ELECTO_MEH 4&PID_DETAL_MEH 3&PID_CRAFT_M_STEL 3&PID_TUBE 1&PID_CHEMICALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_M60 1@script fix_boy@fix_FreeHands}
{2100}{}{PID_ZAPLATKA_CRAFT_ARMOUR@Разделитель раздела для создания защитной экипировки.@@@PID_ZAPLATKA_CRAFT_ARMOUR 1@@PID_ZAPLATKA_CRAFT_ARMOUR 1@script fix_boy@fix_Tribal}
{2105}{}{PID_SANDROBE@Почти так же легко, как сшить мешок для мутафруктов размером с человека. Ресурсов и времени уйдёт так много, что даже самодельная игла сломается.@@@PID_CRAFT_L_RAGS 14&PID_CRAFT_L_LINT 14&PID_MEDTHREAD 14&PID_MEDNEEDLE 1@PID_SCISSORS 1@PID_SANDROBE 1@script fix_boy@fix_FreeHands}
{2110}{}{PID_PURPLE_ROBE@В качестве красителя подойдёт цветок брока.@@@PID_BROC_FLOWER 5&PID_BOOZE 1&PID_SANDROBE 1@@PID_PURPLE_ROBE 1@script fix_boy@fix_FreeHands}
{2115}{}{PID_BLACK_ROBE@В качестве красителя подойдёт корень зандера.@@@PID_XANDER_ROOT 5&PID_BOOZE 1&PID_SANDROBE 1@@PID_BLACK_ROBE 1@script fix_boy@fix_FreeHands}
{2120}{}{PID_LEATHER_JACKET@Сшейте куртку из кусков шкур и ткани. По последней моде без одного рукава.@@SK_OUTDOORSMAN 150|SK_REPAIR 100@PID_CRAFT_L_HIDE 8&PID_CRAFT_L_LINT 8&PID_MEDTHREAD 8&PID_MEDNEEDLE 1@PID_SHIV 1&PID_SCISSORS 1&PID_CUTTHROAT 1@PID_LEATHER_JACKET 1@script fix_boy@fix_FreeHands}
{2125}{}{PID_LEATHER_ARMOR@Вываренная дублёная кожа - отличный материал для обеспечения полной защиты вашего тела.@@SK_OUTDOORSMAN 200|SK_REPAIR 150&SK_SCIENCE 100@PID_BOTTLE_FULL 6&PID_CRAFT_L_HIDE 12&PID_CRAFT_L_LINT 8&PID_MEDTHREAD 12&PID_MEDNEEDLE 1&PID_FIREPLACE_TOKEN 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1&PID_CUTTHROAT 1@PID_LEATHER_ARMOR 1@script fix_boy@fix_FreeHands}
{2130}{}{PID_LEATHER_ARMOR_MK_II@Что бы усилить поглощение ударов, вы обшиваете жёсткими элементами из кожанного доспеха всю вашу одежду из кожи@@SK_OUTDOORSMAN 250|SK_REPAIR 200&SK_SCIENCE 150@PID_LEATHER_JACKET 1&PID_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{2135}{}{PID_CURED_LEATHER_ARMOR@Что бы увеличить защиту от скользящих ударов и при этом не потерять мобильность, вы пришиваете небольшие куски вываренной кожи к открытым частям одежды.@@SK_OUTDOORSMAN 250|SK_REPAIR 200&SK_SCIENCE 150@PID_LEATHER_JACKET 1&PID_BOTTLE_FULL 4&PID_CRAFT_L_HIDE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_CURED_LEATHER_ARMOR 1@script fix_boy@fix_FreeHands}
{2140}{}{PID_CURED_LEATHER_ARMOR_MK_II@Совершенно другой подход к решению проблемы защиты открывается при использовании небольших бронепластин. Переделав нашлёпки из кожи в карманы для пластин, вы добиваетесь разительного увеличения защиты от проникающих и касательных ударов без потерь в мобильности.@@SK_SCIENCE 200&SK_REPAIR 150@PID_CURED_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_PB_PLATE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_CURED_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{2145}{}{PID_LEATHER_ARMOR_MK_III@Полноценная защита из кожи укреплённой бронепластинами. С таким и пулю схлопотать не страшно.@@SK_SCIENCE 200&SK_REPAIR 150@PID_LEATHER_ARMOR_MK_II 1&PID_PART_OF_ROPE 6&PID_PB_PLATE 6&PID_CRAFT_L_LINT 6&PID_MEDTHREAD 6&PID_MEDNEEDLE 1@PID_SHIV 1&PID_KNIFE 1&PID_SCISSORS 1@PID_LEATHER_ARMOR_MK_III 1@script fix_boy@fix_FreeHands}
{2150}{}{PID_METAL_ARMOR@Выпрямив несколько листов ржавого железа, вы использовали их для укрепления брони.@@SK_REPAIR 150&SK_SCIENCE 130@PID_LEATHER_ARMOR_MK_II 1&PID_METAL_LIST_MEH 8&PID_CRAFT_M_BARS 5&PID_WORKBENCH_TOKEN 1@PID_SLEDGEHAMMER 1&PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_METAL_ARMOR 1@script fix_boy@fix_FreeHands}
{2155}{}{PID_METAL_ARMOR_MK_II@Используя качественные материалы вы облегчили конструкцию и сделали ее надежнее.@@SK_REPAIR 200&SK_SCIENCE 200@PID_METAL_ARMOR 1&PID_IRON_PLATE 6&PID_CRAFT_M_BARS 5&PID_WORKBENCH_TOKEN 1@PID_SLEDGEHAMMER 1&PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_METAL_ARMOR_MK_II 1@script fix_boy@fix_FreeHands}
{2160}{}{PID_PB_PLATE@Делаем композитный многослойный бронепакет, нарезаем его на пластинки - готово!@@SK_REPAIR 200&SK_SCIENCE 150@PID_IRON_PLATE 1&PID_METAL_LIST_MEH 4&PID_CHEMICALS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_PB_PLATE 4@script fix_boy@fix_Workbench}
{2165}{}{PID_MANTIS_ARMOR@К шкурам из брамина нужно пришить внахлёст кучу хитиновых пластин. Гротесная экипировка готова!@@SK_OUTDOORSMAN 200@PID_MEDTHREAD 20&PID_CRAFT_L_HIDE 10&PID_CRAFT_L_RAGS 10&PID_BRAHMIN_SKIN 4&PID_MANTIS_SHELL 16&PID_MEDNEEDLE 3@PID_SHIV 1@PID_MANTIS_ARMOUR 1@script fix_boy@fix_Workbench}
{2170}{}{PID_MIRELURK_ARMOR@Делаем качественный кожаный колпак и бутсы, дополнительно укрепляем торс.@@SK_REPAIR 200&SK_SCIENCE 150@PID_MANTIS_ARMOUR 1&PID_MIRROR_SHADES 1&PID_MEDTHREAD 10&PID_CRAFT_L_HIDE 15&PID_CRAFT_L_RAGS 10&PID_MANTIS_SHELL 16&PID_MEDNEEDLE 4&PID_WORKBENCH_TOKEN 1@PID_SHIV 1@PID_MIRELURK_ARMOR 1@script fix_boy@fix_Workbench}
{2175}{}{PID_CARED@В качестве основы для самодельной боевой брони берётся модернизированная кожанная мк3. @@SK_REPAIR 200&SK_SCIENCE 150&SK_OUTDOORSMAN 100@PID_MOTOGLES 1&PID_LEATHER_ARMOR_MK_III 1&PID_MEDTHREAD 8&PID_CRAFT_L_HIDE 16&PID_PB_PLATE 8&PID_CRAFT_L_RAGS 6&PID_MEDNEEDLE 2&PID_PART_OF_ROPE 1@PID_WELDING 1&PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_CARED 1@script fix_boy@fix_Workbench}
{2180}{}{PID_FIRE_ARMOR@Вашей одежде из кожи не хватает огнеустойчивости? Работаете в горячей среде? Возьмите пару шкур огненных гекконов, и обшейте ими открытые участки тела!@@SK_REPAIR 200&SK_SCIENCE 150&SK_OUTDOORSMAN 100@PID_LEATHER_ARMOR 1&PID_MEDTHREAD 8&PID_CRAFT_L_HIDE 6&PID_FIRE_GECKO_PELT 3&PID_CRAFT_L_RAGS 6&PID_MEDNEEDLE 2&PID_PART_OF_ROPE 2@PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_FIRE_ARMOR 1@script fix_boy@fix_Workbench}