{30}{}{PID_RING_BOXING_GLOVES@ Любите бить людей, при этом стараетесь их не калечить? Тогда эти перчатки специально для вас! @@SK_OUTDOORSMAN 30@PID_CRAFT_L_RAGS 2&PID_CRAFT_L_LINT 1&PID_CRAFT_L_HIDE 2@PID_MEDTHREAD 1&PID_MEDNEEDLE 1@PID_RING_BOXING_GLOVES 1@script fix_boy@fix_FreeHands}
{35}{}{PID_RING_PLATED_BOXING_GLOVES@ При ударах ощущения совсем не те? Хочется чего-то большего? Тогда стоит набить эти перчатки обработанными плоскими камнями, или же, если вы состоятельный человек - можете разрезать лист металла и вставить в каждую перчатку по части.@@SK_OUTDOORSMAN 30@PID_ROCK 2|PID_METAL_LIST_MEH 1&PID_RING_BOXING_GLOVES 1@@PID_RING_PLATED_BOXING_GLOVES 1@script fix_boy@fix_FreeHands}
{40}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 50@PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_BRASS_KNUCKLES 1@script fix_boy@fix_LowTier}
{50}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету, четыре дырки в противнике того стоят.@SK_REPAIR 40@SK_REPAIR 55@PID_BRASS_KNUCKLES 1&PID_SPIKE_MEH 4@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SPIKED_KNUCKLES 1@script fix_boy@fix_MidTier}
{70}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1&PID_FIREWOOD 1@@PID_SLEDGEHAMMER 1@script fix_boy@fix_FreeHands}
{80}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 30&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@script fix_boy@fix_FreeHands}
{90}{}{PID_SHARP_SPEAR@Заточка копья кремнем от фирмы "Морлис" позволит разрубать врагов им как алебардой.@SK_OUTDOORSMAN 30@SK_MELEE_WEAPONS 40&SK_REPAIR 20&SK_OUTDOORSMAN 40@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@script fix_boy@fix_FreeHands}
{100}{}{PID_SHARPENED_POLE@Вжик-вжик, готово!@ST_STRENGTH 0@SK_OUTDOORSMAN 20@PID_FIREWOOD 1|PID_WOOD_PLANK 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1|PID_REVFIST1 1@PID_SHARPENED_POLE 1@script fix_boy@fix_FreeHands}
{105}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@ST_STRENGTH 0@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@script fix_boy@fix_FreeHands}
{106}{}{PID_WOOD_PLANK@Отломайте нахрен минимум треть этой палки, забейте камнем в один конец какой-нибудь утяжелитель. Отломаный кусок можно притарабанить в качестве дополнительной рукояти. Готово, можно пойти проломить кому-нибудь черепушку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40&SK_REPAIR 30@PID_SHARPENED_POLE 1&PID_CRAFT_M_JUNK 1@PID_ROCK 1@PID_WOOD_PLANK 1@script fix_boy@fix_FreeHands}
{107}{}{PID_WOOD_PART@ Длительное время вы страдали от отсутствия качественных досок, но уже все позади. Теперь вы и сами в состоянии сделать их! @@SK_REPAIR 50|SK_OUTDOORSMAN 80@PID_WOOD_PLANK 2|PID_FIREWOOD 2@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1@PID_WOOD_PART 2@script fix_boy@fix_MidTier}
{108}{}{PID_LOUISVILLE_SLUGGER@Придайте палке более изящную форму и покройте ее лаком.@ST_STRENGTH 0@ST_LEVEL 6&SK_REPAIR 90&SK_MELEE_WEAPONS 80@PID_CHEMICALS 1&PID_WOOD_PART 1@PID_COMBAT_KNIFE 1&PID_WORKBENCH_TOKEN 1@PID_LOUISVILLE_SLUGGER 1@script fix_boy@fix_MidTier}
{109}{}{PID_KNIFE_P@Выдавите немного яда из хвоста скорпиона на нож, и ваш противник будет повержен ядом.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_KNIFE 1&PID_SCORPION_TAIL 1@@PID_KNIFE_P 1@script fix_boy@fix_FreeHands}
{112}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, обмотать рукоять кожей, и этот нож уже можно называть оружием.@SK_REPAIR 60@SK_OUTDOORSMAN 20&SK_REPAIR 80&SK_MELEE_WEAPONS 60@PID_KNIFE 1&PID_CRAFT_M_BARS 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_COMBAT_KNIFE 1@script fix_boy@fix_MidTier}
{115}{}{PID_СKNIFE_P@Верный боевой нож. Теперь с ядом! Ограниченная партия!@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 1&PID_COMBAT_KNIFE 1@@PID_CKNIFE_P 1@script fix_boy@fix_FreeHands}
{120}{}{PID_SPEAK_P@Острое как бритва, и ядовитое как опасный враг путешественника@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SPEAR 1&PID_SCORPION_TAIL 1@@PID_SPEAK_P 1@script fix_boy@fix_FreeHands}
 
{138}{}{DEVIDER@ МЕТАТЕЛЬНОЕ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{140}{}{PID_REV_BALL1@Расплавьте несколько пластиковых бутылок и повтыкайте в еще не до конца остывший ком пластмассы заостренных железяк@SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 60&SK_THROWING 60&SK_REPAIR 35@PID_BOTTLE_EMPTY 2&PID_CRAFT_M_BARS 1@PID_LIGHTER 1|PID_FIREPLACE_TOKEN 1@PID_REV_BALL1 1@script fix_boy@fix_FreeHands}
{145}{}{PID_REV_BALL2@Нехватка убойной мощи? Давайте это исправим!@SK_REPAIR 35@SK_OUTDOORSMAN 70&SK_THROWING 65&SK_REPAIR 40@PID_REV_BALL1 1@PID_FLINT 1@PID_REV_BALL2 1@script fix_boy@fix_FreeHands}
{150}{}{PID_THROWING_KNIFE@Сбалансируйте и дополнительно заточите эту железку.@SK_THROWING 40@SK_THROWING 50&SK_REPAIR 30@PID_KNIFE 1&PID_FLINT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_THROWING_KNIFE 1@script fix_boy@fix_LowTier}
{151}{}{PID_MKNIFE_P@Метательный и ядовитый. Гремучая смесь.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 1&PID_THROWING_KNIFE 1@@PID_MKNIFE_P 1@script fix_boy@fix_FreeHands}
{155}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 30@PID_ROT_GUT 1&PID_CRAFT_L_RAGS 1&PID_BROC_FLOWER 5@@PID_MOLOTOV_COCKTAIL 1@script fix_boy@fix_FreeHands}

{156}{}{DEVIDER@ Набор выживальщика @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{157}{}{PID_BEER@ Захотелось пивчанского, а дрожжей днём с огнём не найти? Разбавь нюкой самогон и добавь немного специй, что бы придать тот самый горковатый вкус..@@SK_OUTDOORSMAN 70&SK_SCIENCE 50@PID_NUKA_COLA 1&PID_BOOZE 1&PID_BROC_FLOWER 2@@PID_BEER 2@script fix_boy@fix_FreeHands}
{158}{}{PID_WRENCH@ Гаечный ключ @@SK_REPAIR 60@PID_CRAFT_M_BARS 3@PID_MULTI_TOOL 1@PID_WRENCH 1@script fix_boy@fix_LowTier}
{159}{}{PID_LIGHTER@ Соберите простенький корпус для самодельной Зиппо, набейте его смоченной в керосине ватой и закройте, добавив фитиль из тряпки в том-же керосине, и кремень для высекания искр. Огоньку? @@SK_REPAIR 70@PID_FLINT 1&PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1&PID_BOOZE 1@@PID_LIGHTER 1@script fix_boy@fix_LowTier}
{160}{}{PID_PART_OF_ROPE@Берете тряпки и связываете их вместе. Вуаля! Куски веревки в ваших руках.@ST_STRENGTH 0@@PID_CRAFT_L_RAGS 4@@PID_PART_OF_ROPE 3@script fix_boy@fix_FreeHands}
{165}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@ST_STRENGTH 0@@PID_PART_OF_ROPE 6@@PID_ROPE 1@script fix_boy@fix_FreeHands}
{170}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@ST_STRENGTH 0@SK_OUTDOORSMAN 30@PID_CRAFT_M_BARS 1&PID_FIREWOOD 1|PID_WOOD_PLANK 1@PID_ROCK 1|PID_MULTI_TOOL 1@PID_AXE 1@script fix_boy@fix_FreeHands}
{172}{}{PID_SHOVEL@Найдите где-нибудь палку и насадите на один из ее концов подходящую железку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_CRAFT_M_BARS 1&PID_SHARPENED_POLE 1@PID_KNIFE 1@PID_SHOVEL 1@script fix_boy@fix_FreeHands}
{174}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_CRAFT_M_BARS 1&PID_FIREWOOD 1@PID_KNIFE 1@PID_SHIV 1@script fix_boy@fix_FreeHands}
{175}{}{PID_KNIFE@Заточите железяку о камень, обмотайте конец какой-нибудь тряпкой. Готово, можно идти похвастаться родителям.@ST_STRENGTH 0@SK_OUTDOORSMAN 20@PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1@@PID_KNIFE 1@script fix_boy@fix_FreeHands}
{177}{}{PID_ROD@ Хочется ловить рыбу? Удочка к твоим услугам!@@SK_OUTDOORSMAN 120@PID_SHARPENED_POLE 1&PID_CRAFT_M_BARS 2@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_MULTI_TOOL 1@PID_ROD 1@script fix_boy@fix_FreeHands}
{179}{}{PID_HOOK@ Удочке не хватает крючка? Следует поискать что-нибудь в мусоре.@@SK_OUTDOORSMAN 100@PID_MEDNEEDLE 1&PID_CRAFT_M_BARS 2&PID_CRAFT_L_LINT 1@PID_MULTI_TOOL 1@PID_HOOK 1@script fix_boy@fix_FreeHands}
{182}{}{PID_STRING@ Леска? Используй более прочную нить в качестве нее.@@SK_OUTDOORSMAN 90@PID_MEDTHREAD 1&PID_CRAFT_L_LINT 2@@PID_STRING 1@script fix_boy@fix_FreeHands}
{183}{}{PID_ROT_GUT@ Нехватка острых ощущений? Перемешайте пиво с самогоном и попробуйте на вкус! @@ST_INTELLECT 2@PID_BEER 1&PID_BOOZE 1@@PID_ROT_GUT 2@script fix_boy@fix_FreeHands}
{184}{}{PID_NUKA_COLA@ Нюка-кола! Бесплатно и без ломающего конечности автомата. @@SK_OUTDOORSMAN 70&SK_SCIENCE 50@PID_GLASS_BOTTLE_FULL 1&PID_XANDER_ROOT 2@PID_LIGHTER 1@PID_NUKA_COLA 1@script fix_boy@fix_FreeHands}
{185}{}{PID_MEAT@ Бросьте пару кусков мяса в самогон, быть может, это поможет..@@SK_OUTDOORSMAN 30@PID_RAD_MEAT 2&PID_BOOZE 1@@PID_MEAT 1&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}

{186}{}{DEVIDER@Набор потрошителя.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{187}{}{PID_REV_BALL1@Расплавьте несколько пластиковых бутылок и повтыкайте в еще не до конца остывший ком пластмассы заостренных железяк@@SK_OUTDOORSMAN 60&SK_THROWING 60&SK_REPAIR 35@PID_BOTTLE_EMPTY 2&PID_CRAFT_M_BARS 1@PID_LIGHTER 1|PID_FIREPLACE_TOKEN 1@PID_REV_BALL1 1@script fix_boy@fix_FreeHands}
{188}{}{PID_REV_BALL2@Нехватка убойной мощи? Давайте это исправим!@@SK_OUTDOORSMAN 70&SK_THROWING 65&SK_REPAIR 40@PID_REV_BALL1 1@PID_FLINT 1@PID_REV_BALL2 1@script fix_boy@fix_FreeHands}
{189}{}{PID_REVFIST1@Ваше первое орудие, используйте его с.. силой!@@SK_OUTDOORSMAN 50@PID_CRAFT_M_BARS 1@@PID_REVFIST1 1@script fix_boy@fix_FreeHands}
{190}{}{PID_REVKNIFE1@Опытному воину требуется более сильное орудие!@@SK_OUTDOORSMAN 60@PID_CRAFT_M_BARS 2@PID_REVFIST1 1@PID_REVKNIFE1 1@script fix_boy@fix_FreeHands}
{191}{}{PID_REVKNIFE2@Совершенству нет предела! У вас в голове безумная идея о создании могучей железяки!@@SK_OUTDOORSMAN 80@PID_REVKNIFE1 1&PID_CRAFT_M_BARS 3@PID_REVFIST1 1@PID_REVKNIFE2 1@script fix_boy@fix_FreeHands}
{192}{}{PID_REVCLUB1@Вам кажется, что вы почти идеяльно подходите на роль вожака какого-нибудь племени. Вам срочно нужно сделать кусачую палку, чтобы повелевать! @@SK_OUTDOORSMAN 110@PID_FIREWOOD 1|PID_WOOD_PLANK 1&PID_CRAFT_M_BARS 1@PID_FLINT 1&PID_REVKNIFE2 1|PID_REVFIST1 1@PID_REVCLUB1 1@script fix_boy@fix_FreeHands}

{194}{}{DEVIDER@Вундервафли пустоши.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{195}{}{PID_KLK@ Вырвите клыки у побежденной вами твари, или не вами.. Неважно! Важно лишь то, что шкура будет безнадежно испорчена.@@SK_OUTDOORSMAN 50@PID_MOUSE_SKIN 1|PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 1|PID_FIRE_GECKO_PELT 1@PID_MULTI_TOOL 1|PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_KLK 4@script fix_boy@fix_FreeHands}
{196}{}{PID_OZHER@ Каждый дикарь стремится всунуть в свое ожерелье как можно больше клыков. Чем хуже вы? @@SK_OUTDOORSMAN 55@PID_KLK 8&PID_CRAFT_L_LINT 1@PID_SHIV 1@PID_OZHER 1@script fix_boy@fix_FreeHands}
{197}{}{PID_RPSTUFF1@ Хотите выделиться среди остальных? Бирка вам в помощь!@@SK_REPAIR 40@PID_CRAFT_M_BARS 1&PID_CRAFT_L_LINT 2@PID_KNIFE 1|PID_MULTI_TOOL 1@PID_RPSTUFF1 1@script fix_boy@fix_FreeHands}
{198}{}{PID_RPSTUFF4@ Хотите выделиться среди остальных? Вырвите лист бумаги из книги и представьте, что это документ.@@ST_LEVEL 4&SK_SCIENCE 40@PID_BOOK2 1@@PID_BOOK2 1&PID_RPSTUFF4 1@script fix_boy@fix_FreeHands}
{199}{}{PID_SHERIFF_BADGE@Вам всегда очень хотелось стать шерифом, но никто не спешил вам вручить соответствующий значок? Не переживайте, ведь вы и сами в состоянии сделать его себе.@@ST_LEVEL 2&SK_OUTDOORSMAN 60|SK_SMALL_GUNS 75@PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1@PID_SHERIFF_BADGE 1@script fix_boy@fix_FreeHands}
{200}{}{PID_DICE@Распиливаем доску так, чтобы получился брусок небольших размеров, после чего ножом делаем небольшие углубления, служащие разметкой@@ST_LEVEL 4@PID_FIREWOOD 1@PID_KNIFE 1&PID_REVFIST1 1@PID_DICE 1@script fix_boy@fix_FreeHands}

{205}{}{DEVIDER@ МЕДИЦИНА @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{210}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_CRAFT_L_RAGS 1@@PID_HEALING_POWDER 1@script fix_boy@fix_FreeHands}
{220}{}{PID_ANTIDOTE@Это будет скорей самовнушением. @SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60&SK_DOCTOR 40|SK_SCIENCE 40@PID_BOOZE 1&PID_SCORPION_TAIL 1@PID_LIGHTER 1&PID_KNIFE 1@PID_ANTIDOTE 1@script fix_boy@fix_FreeHands}
{221}{}{PID_ANTIDOTE@Настоящие доктора и учёные могут синтезировать противоядие из любого органического активного компонента: грибов, водорослей или хитина.@@SK_OUTDOORSMAN 80&SK_DOCTOR 80&SK_SCIENCE 80@PID_ROT_GUT 1&PID_CHEMICALS 1&PID_GLASS_BOTTLE_FULL 1&PID_MUSH_LOW 1|PID_MANTIS_SHELL 3|PID_ALGAE 1@PID_LIGHTER 1&PID_BOTTLE_GLASS 3&PID_HYPODERMIC_NEEDLE 2&PID_BOOZE 1&PID_WORKBENCH_TOKEN 1@PID_ANTIDOTE 3@script fix_boy@fix_MidTier}
{225}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@SK_FIRST_AID 20@SK_FIRST_AID 100&SK_SCIENCE 70@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1&PID_BOOZE 1&PID_HEALING_POWDER 2&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1@PID_STIMPAK 1@script fix_boy@fix_MidTier}
{226}{}{PID_SUPER_STIMPAK@Одной банки биогеля вполне хватает на то что бы усилить эффект от шести стимпаков. Для увеличения скорости ввода такого объёма вы делаете специальный ремешок с иглами по периметру. Три супер-стимпака готовы к использованию!@ST_CHARISMA 2@SK_SCIENCE 80&SK_DOCTOR 120&SK_REPAIR 40@PID_BIO_GEL 1&PID_STIMPAK 6&PID_CRAFT_L_HIDE 3@PID_LIGHTER 1&PID_BOTTLE_GLASS 1&PID_MULTI_TOOL 1@PID_SUPER_STIMPAK 2@script fix_boy@fix_HiTier}
{227}{}{PID_BIO_GEL@Годы, потраченные на изучение химии и биологии не прошли даром! Используя все доступные вам ресурсы и технологии, вы создаёте очень сильный медицинский реагент. Каждая из этих пяти баночек определённо стоит потраченных ресурсов и времени!@ST_INTELLECT 2@SK_SCIENCE 150&SK_DOCTOR 120&SK_REPAIR 40@PID_CHEMICALS 1&PID_ANTISEPTIC 2&PID_JET_ANTIDOTE 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_CHEMISTRY_MANUAL 1&PID_MEDCLIP 1&PID_LIGHTER 1@PID_BIO_GEL 5@script fix_boy@fix_HiTier}
{230}{}{PID_FIRST_AID_KIT@ Устали носить шприцы и иглы в далеко не самых стерильных карманах? Пацинты гибнут от заражения, даже не успевая уйти от вас? Что-ж, тогда эта коробка специально для вас. @@SK_FIRST_AID 60|SK_DOCTOR 40&SK_OUTDOORSMAN 30@PID_FIREWOOD 2&PID_CRAFT_L_HIDE 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_FIRST_AID_KIT 1@script fix_boy@fix_LowTier}
{235}{}{PID_DEFIB@Стандартный реанимационный набор для восстановления жизнедеятельности. Можно собрать, имея нужные познания в медицине@SK_DOCTOR 20@ST_LEVEL 12&SK_FIRST_AID 100&SK_SCIENCE 50&SK_DOCTOR 120&SK_REPAIR 30@PID_CRAFT_M_BARS 5&PID_SMALL_ENERGY_CELL 6&PID_CRAFT_M_JUNK 4&PID_STIMPAK 3&PID_CRAFT_E_CHIP 4&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_DEFIB 1@script fix_boy@fix_HiTier}
{240}{}{PID_ANTIDOTE_2@Мощное противоядие, нейтрализующее действие нейротоксина. Можно сделать, имея образец токсина.@SK_SCIENCE 30@SK_SCIENCE 100@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 3&PID_BOTTLE_GLASS 2&PID_HYPO_POISON 1&PID_WORKBENCH_TOKEN 1@PID_CHEMISTRY_MANUAL 1&PID_LIGHTER 1@PID_ANTIDOTE_2 3@script fix_boy@fix_HiTier}
{245}{}{PID_MEDTHREAD@Найдите что нибудь острое и мелкое, напоминающее иглу, проделайте отверстие, которое будет служить "ушком", затем промойте все это водой. Из карманного мусора можно смело сплести нить.@@SK_FIRST_AID 60|SK_DOCTOR 60|SK_OUTDOORSMAN 80@PID_CRAFT_M_BARS 1&PID_CRAFT_L_LINT 8@PID_BOTTLE_FULL 1&PID_SHIV 1@PID_MEDTHREAD 1&PID_MEDNEEDLE 1@script fix_boy@fix_LowTier}
{247}{}{PID_BANDAGE@Нарежьте тряпки в ленты и как следует прокипятите их. Сверните в рулоны, обработав спиртом. @SK_FIRST_AID 15@ST_LEVEL 4&SK_FIRST_AID 70&SK_DOCTOR 40@PID_GLASS_BOTTLE_FULL 1&PID_CRAFT_L_RAGS 5&PID_BOOZE 1@PID_LIGHTER 1@PID_BANDAGE 3@script fix_boy@fix_LowTier}
{249}{}{PID_MEDSPLINT@ Делаем ремешки на железные фиксаторы, делаем мягкую прокладку и мы готовы к фиксации конечности! Не забудьте обмотать все это бинтами, вы же доктор!  @@SK_DOCTOR 100|SK_FIRST_AID 120@PID_CRAFT_L_RAGS 4&PID_CRAFT_M_BARS 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_MEDSPLINT 1@script fix_boy@fix_LowTier}
{250}{}{PID_MEDCLIP@Хотите, чтобы операция проходила менее болезненно для вашего пациента? Тогда вам непременно стоит сделать зажим. Не забудте продезинфицировать ваше творение! @SK_FIRST_AID 20|SK_DOCTOR 20@ST_LEVEL 4&SK_REPAIR 70&SK_FIRST_AID 40|SK_DOCTOR 40@PID_CRAFT_M_BARS 2&PID_BOOZE 1@PID_MULTI_TOOL 1@PID_MEDCLIP 1@script fix_boy@fix_LowTier}
{251}{}{PID_RESPIRATOR@Работаете с химикатами, любите блуждать по подземке или просто боитесь запаха изо рта? Респиратор поможет вам!@@SK_SCIENCE 100&SK_REPAIR 70@PID_CRAFT_M_JUNK 3&PID_EMPTY_JET 2&PID_ELECTO_MEH 1&PID_IRON_DETALS 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1@PID_RESPIRATOR 1@script fix_boy@fix_MidTier}
{255}{}{PID_ANTISEPTIC@Вскипятите воду и засыпьте в нее растертые в порошок брок и зандер, добавьте немного самогона и тщательно все перемешайте.@SK_FIRST_AID 20|SK_DOCTOR 20|SK_SCIENCE 20@ST_LEVEL 4&SK_SCIENCE 40&SK_DOCTOR 80|SK_FIRST_AID 80@PID_GLASS_BOTTLE_FULL 1&PID_ANTIDOTE 1&PID_BOOZE 1&PID_BROC_FLOWER 1&PID_XANDER_ROOT 1@PID_LIGHTER 1@PID_ANTISEPTIC 3@script fix_boy@fix_MidTier}
{257}{}{PID_PILLS @Брок выварить в кипятке и выстоять в течении часа, процедить. Пока выстаивается отвар, приготовьте основу для таблеткок на основе клейстера из кукурузной муки. Катализатором фармокологического действия, а также замечательным консервантом станет эмульсия из стандартного стимулятора. Соблюдайте стерильность!.@SK_FIRST_AID 20|SK_DOCTOR 20@SK_FIRST_AID 110|SK_SCIENCE 100&SK_DOCTOR 60@PID_BROC_FLOWER 3&PID_XANDER_ROOT 5&PID_ANTISEPTIC 1&PID_BOTTLE_FULL 1&PID_HEALING_POWDER 1@PID_LIGHTER 1@PID_PILLS  1@script fix_boy@fix_MidTier}
{258}{}{PID_JET_ANTIDOTE@ Мясо измельчить и замешать с сильнейшим из доступных наркотиков. Пока идет связывание с белком, измельчите таблетки и растворите в воде. Промойте наркофарш полученным расствором и процедите через стерильную ткань. Полученную сыворотку выпаривать до получения вязкой, карамелеобразной субстанции. @SK_FIRST_AID 20|SK_SCIENCE 20|SK_DOCTOR 20@SK_FIRST_AID 120|SK_DOCTOR 70&SK_SCIENCE 110@PID_JET 3&PID_MEAT 1&PID_PILLS 1&PID_BOTTLE_FULL 1&PID_BANDAGE 2@PID_LIGHTER 1&PID_KNIFE 1|PID_THROWING_KNIFE 1&PID_BOTTLE_EMPTY 1@PID_JET_ANTIDOTE 1@script fix_boy@fix_HiTier}

{259}{}{DEVIDER@Упорка@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{260}{}{PID_KOSYAK@Разотрите камнем высушенные на солнце ингредиенты, добавьте секретный ингридиент.@@SK_OUTDOORSMAN 30&PE_FLOWER_CHILD 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_CRAFT_L_RAGS 1@@PID_KOSYAK 1@escript fix_boy@fix_FreeHands}
{261}{}{PID_MUSH_LOW@Мешок удобрений, пара литров воды, немного терпения - и ваши домашние грибочки готовы к употреблению!@@SK_OUTDOORSMAN 120&SK_SCIENCE 100@PID_SANDBAG_1 1&PID_MUSH_LOW 1&PID_MINERAL 5&PID_BOTTLE_FULL 3@PID_SHOVEL 1&PID_KNIFE 1&PID_SLEDGEHAMMER 1@PID_MUSH_LOW 5&PID_BOTTLE_EMPTY 3@script fix_boy@fix_HiTier}
{262}{}{PID_MENTATS@Ментаты. Нужно что-то, что бы торкало и действовало дольше, чем винт, но не с такими отходняками? Для начала вам понадобятся те же самые грибы, содержащие в себе небольшое количество необходимых солей. Измельчаем их,  отбиваем до получения концентрата. В итоге, получившийся концентрат разделяем на более мелкие дозы, добавляем по вкусу брока, что бы это дерьмо не так противно было держать во рту, и вот-у вас все готово!@@SK_DOCTOR 80|SK_SCIENCE 80&PE_FLOWER_CHILD 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_MUSH_LOW 1@PID_LIGHTER 1&PID_BOTTLE_GLASS 1@PID_MENTATS 1@script fix_boy@fix_HiTier}
{263}{}{PID_BUFFOUT@Баффаут. Если у вас еще осталось что-то в голове после принятия этих пилюль, то следуем несложной рецептуре-для начала понадобится стимулятор, который мы избавляем от всех лишний примесей посредством несложных химических реакций. Получившийся концентрат соединяем с заранее заготовленными, небольшими дозами солей амфетаминов, и получаем в итоге сырой стимулятор для тела. Осталось дать подсохнуть и разбить на дозы.@@SK_DOCTOR 100|SK_SCIENCE 100&PE_FLOWER_CHILD 1@PID_STIMPAK 1&PID_JET 1@PID_LIGHTER 1&PID_BOTTLE_GLASS 1@PID_BUFFOUT 1@script fix_boy@fix_HiTier}
{264}{}{PID_JET@Джет. Ну что же, не зря Майрон, или его последователи капали вам на мозги, пытаясь вбить вам в голову весь процесс синтеза правнука первитина. Сначала понадобятся особые грибы, произрастающие только в помете двухголовых друзей. Раздобыв их, мы для начала измельчаем грибы и выгоняем из них эмульсию. Следом добавляем немного кристаллизированного йода. Оставляем отстояться, потом еще раз выгоняем получившуюся жидкостью до образования осадка. Этот осадок-и есть то, что нам нужно.@@SK_DOCTOR 100|SK_SCIENCE 100&PE_FLOWER_CHILD 1@PID_EMPTY_JET 5&PID_ANTISEPTIC 1&PID_MUSH_LOW 2@PID_LIGHTER 1&PID_BOTTLE_GLASS 1@PID_JET 5@script fix_boy@fix_HiTier}
{265}{}{PID_PSYCHO@ Мама учила вас не делать такие плохие вещи, но ведь ее рядом нет, верно? Для начала нужно выгнать сурогат из анестетиков, что бы получить концентрат для изготовления психо. Следом отбиваем первитин до получения бесцветной жидкости. Не забываем щелочить все это дело, оставляем получившуюся смесь остыть и вот у вас готов кустарный психо. @@SK_SCIENCE 80|SK_FIRST_AID 120&SK_DOCTOR 120&PE_FLOWER_CHILD 1@PID_PILLS 1&PID_ANTISEPTIC 1&PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 1@PID_LIGHTER 1&PID_BOTTLE_GLASS 1@PID_PSYCHO 1@script fix_boy@fix_HiTier}
{280}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{285}{}{PID_MULTI_TOOL@Каждый порядочный человек просто обязан уметь делать плоскогубцы.@@ST_LEVEL 4&SK_REPAIR 70@PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 3@PID_KNIFE 1&PID_SHIV 1@PID_MULTI_TOOL 1@script fix_boy@fix_MidTier}
{286}{}{PID_SUPER_TOOL_KIT@Вам хочется создать нечто грандиозное, чего невозможно сделать одними плоскогубцами? Значит, вам следует расширить свой инструментарий!@@ST_LEVEL 8&SK_REPAIR 120@PID_MULTI_TOOL 1&PID_KNIFE 2&PID_SHIV 1&PID_FLARE 1&PID_CROWBAR 1&PID_CRAFT_M_BARS 5&PID_WRENCH 1&PID_BAG 1@@PID_SUPER_TOOL_KIT 1@script fix_boy@fix_MidTier}
{287}{}{PID_WELDING@Берем батареи на блок питания для дуги, кусачки пойдут как удержатель электрода, а куча хлама на сами электроды, химикаты - на смазку.@@SK_REPAIR 120|SK_SCIENCE 140@PID_CUENCELL_LOW 10|PID_SMALL_ENERGY_CELL 2&PID_MULTI_TOOL 1&PID_CRAFT_M_BARS 4&PID_EMKOCT_MEH 1@PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_WELDING 1@script fix_boy@fix_MidTier}

{291}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{310}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле.@SK_LOCKPICK 50@SK_LOCKPICK 70@PID_CRAFT_M_JUNK 1&PID_CRAFT_L_HIDE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_LOCKPICKS 1@script fix_boy@fix_MidTier}
{320}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами!@SK_LOCKPICK 70@SK_LOCKPICK 100@PID_LOCKPICKS 1&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_EXP_LOCKPICK_SET 1@script fix_boy@fix_MidTier}
{340}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Схема простейшего приёмника в каждом номере "Электроники Дина"!@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 80@PID_CRAFT_E_CHIP 2&PID_CRAFT_M_JUNK 2&PID_CRAFT_E_LAMP 3&PID_VIC_RADIO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_RADIO 1@script fix_boy@fix_MidTier}
{370}{}{PID_HANDCUFFS@Как-то давно, в довоенном журнале про оружие вы нашли статью об устройстве наручников. Не так уж сложно сделать, если немного рабираться в ремонте и замках.@SK_REPAIR 80@SK_SCIENCE 40&SK_REPAIR 110&SK_LOCKPICK 50@PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_HANDCUFFS 1@script fix_boy@fix_MidTier}
{380}{}{PID_LOCKER_LOW@Самый просто навесной замок. Проще некуда.@SK_REPAIR 50&SK_LOCKPICK 30@SK_REPAIR 60&SK_LOCKPICK 40@PID_CRAFT_M_BARS 5&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOCKER_LOW 1@script fix_boy@fix_FreeHands}
{390}{}{PID_LOCKER_MED@Замок среднего уровня. Может от кого-то и спасет.@SK_REPAIR 90&SK_LOCKPICK 50@SK_REPAIR 100&SK_LOCKPICK 60@PID_CRAFT_M_BARS 10&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1|PID_MULTI_TOOL 1@PID_LOCKER_MED 1@script fix_boy@fix_MidTier}
{400}{}{PID_LOCKER_HARD@Хех, куда же такой сейф ставить?@SK_REPAIR 140&SK_LOCKPICK 70@SK_REPAIR 150&SK_LOCKPICK 80@PID_CRAFT_M_BARS 15&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_LOCKER_HARD 1@script fix_boy@fix_HiTier}

{450}{}{DEVIDER@ ПАТРОНЫ ФИРМЫ "ГРУСТЬ" @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{500}{}{PID_PB_FOR_AMMO@Нехитрым приспособлением можно быстро клепать болванки гильз и заготовки для пуль.@SK_SMALL_GUNS 30@SK_REPAIR 60@PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1&PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 6@script fix_boy@fix_LowTier}
{502}{}{PID_10mm_LOW@Выпарить грибы, засыпать получившийся порошок в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_PB_FOR_AMMO 2&PID_MUSH_LOW 3&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1@PID_10mm_LOW 16@script fix_boy@fix_LowTier}
{504}{}{PID_044mag_LOW@Выпарить грибы, засыпать получившийся порошок в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_PB_FOR_AMMO 2&PID_MUSH_LOW 3&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1@PID_044mag_LOW 17@script fix_boy@fix_LowTier}
{510}{}{PID_14mm_LOW@Засыпать порох в гильзу, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_GUNPOWDER 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_14mm_LOW 10@script fix_boy@fix_LowTier}
{512}{}{PID_12g_LOW@Выпарить грибы, засыпать получившийся порошок в картуш из ветоши, насыпать обломков гвоздей.@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_MUSH_LOW 4&PID_CRAFT_L_RAGS 3&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_12g_LOW 14@script fix_boy@fix_LowTier}
{514}{}{PID_223_LOW@Засыпать порох в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_CRAFT_M_BARS 3&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_223_LOW 13@script fix_boy@fix_LowTier}
{515}{}{PID_CUENCELL_LOW@извлекаем радиоактивные элементы, естанавливаем их в оболочку, добавляем реагенты, обматываем фольгой и закрываем в корпус@SK_SCIENCE 20@SK_REPAIR 80@PID_RAD_LOW 1&PID_CRAFT_M_BARS 4&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_CUENCELL_LOW 18@script fix_boy@fix_MidTier}
{520}{}{PID_POLE_DART_LOW@Выстругиваем небольшие деревянные дротики и как можно скорей бежим их продавать!@SK_OUTDOORSMAN 10@SK_OUTDOORSMAN 20@PID_FIREWOOD 4@PID_KNIFE 1@PID_POLE_DART_LOW 15@script fix_boy@fix_FreeHands}
{525}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_CHEMICALS 2&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMETHROWER_FUEL 8@script fix_boy@fix_MidTier}
{527}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 80@PID_FLAMETHROWER_FUEL 1&PID_ROT_GUT 1&PID_CHEMICALS 1&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_CHEMISTRY_MANUAL 1@PID_FLAMETHROWER_FUEL 8@script fix_boy@fix_MidTier}
{535}{}{PID_FRAG_GRENADE@Поместите взрывчатое вещевство в осколочную рубашку и придумайте простенький взрыватель.@SK_REPAIR 80@SK_REPAIR 120@PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_TNT 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_FRAG_GRENADE 1@script fix_boy@fix_MidTier}
{537}{}{PID_HN_NEEDLER_CARTRIDGE@Шприцы-дротики для пистолета-инъектора делаются из твердого пластика. Довольно просто. Нужно только заполнить их какими-нибудь химикатами.@SK_REPAIR 20@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_CRAFT_M_JUNK 5&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_LIGHTER 1@PID_HN_NEEDLER_CARTRIDGE 10@script fix_boy@fix_MidTier}
{539}{}{PID_NEED_CART_POISON@Картриджи для инъектора можно заполнить ядом радскорпионов. Измельчить 2 хвоста радскорпиона, залить растворителем, дать настояться несколько часов. Затем выпарить для достижения большей концентрации и заправить картриджи.@SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 100&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_HN_NEEDLER_CARTRIDGE 10&PID_CRAFT_M_BARS 1&PID_SCORPION_TAIL 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_NEED_CART_POISON 10@script fix_boy@fix_MidTier}
{542}{}{PID_NEED_CART_NT@Картриджи иньектора можно заполнить опаснейшим нейротоксином... Нужно только найти нейротоксин. @SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_HYPO_POISON 1&PID_HN_NEEDLER_CARTRIDGE 10&PID_WORKBENCH_TOKEN 1@@PID_NEED_CART_NT 10@script fix_boy@fix_HiTier}
{545}{}{PID_HYPO_POISON@Сильнейший нейротоксин, который в малых количествах содержится в ядовитом жале радскорпионов можно извлечь методом кислотно-щелочной экстракции.@SK_SCIENCE 80@SK_SCIENCE 140@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 1&PID_BOTTLE_GLASS 2&PID_SCORPION_TAIL 8&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_HYPO_POISON 1@script fix_boy@fix_HiTier}

{550}{}{DEVIDER@ ПАТРОНЫ ФИРМЫ "РАДОСТЬ" @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{551}{}{PID_10mm@Старательно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_SMALL_GUNS 90@PID_PB_FOR_AMMO 3&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_10MM_JHP 8@script fix_boy@fix_MidTier}
{552}{}{PID_044mag@Старательно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_SMALL_GUNS 90&SK_REPAIR 140@PID_PB_FOR_AMMO 3&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_44_MAGNUM_JHP 9@script fix_boy@fix_MidTier}
{553}{}{PID_14MM_AP@Засыпать порох в гильзы, утромбовать его, вставить пули@SK_BIG_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_BIG_GUNS 90@PID_GUNPOWDER 3&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_14MM_AP 6@script fix_boy@fix_MidTier}
{554}{}{PID_12g@Старательно засыпать порох в картуш из ветоши, насыпать отборных обломков гвоздей.@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_SMALL_GUNS 90@PID_GUNPOWDER 2&PID_CRAFT_L_RAGS 2&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_SHOTGUN_SHELLS 7@script fix_boy@fix_MidTier}
{557}{}{PID_223@Аккуратно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_SMALL_GUNS 60&SK_REPAIR 140@PID_CRAFT_M_BARS 3&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 3&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_223_FMJ 7@script fix_boy@fix_MidTier}
{558}{}{PID_SMALL_ENERGY_CELL@Осторожно извлекаем радиоактивные элементы, естанавливаем их в оболочку, добавляем реагенты, обматываем качественной фольгой и закрываем в корпус@SK_SCIENCE 20@ST_LEVEL 12&SK_SCIENCE 140&SK_ENERGY_WEAPONS 90@PID_RAD_LOW 3&PID_CRAFT_M_BARS 4&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SMALL_ENERGY_CELL 5@script fix_boy@fix_MidTier}
{560}{}{PID_GRENADELAUNCHER_AMMO@Для того, что бы сбивать небесные светила, вам нужны будут заряды! Найдите где-то взрывчатку, немного железяк и учебник по физике, а так же немного времени. Чик-чик, и вы остаётесь без руки, либо у вас есть готовый снаряд. @@ST_LEVEL 9&SK_SCIENCE 70&SK_REPAIR 140&SK_BIG_GUNS 70@PID_TNT 1&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 3@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_WORKBENCH_TOKEN 1@PID_GRENADELAUNCHER_AMMO 4@script fix_boy@fix_HiTier}
{562}{}{PID_45_CALIBER_AMMO@Старательно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_SMALL_GUNS 90@PID_PB_FOR_AMMO 6&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_45_CALIBER_AMMO 8@script fix_boy@fix_MidTier}
{564}{}{PID_9MM_AMMO@Старательно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_SMALL_GUNS 90@PID_PB_FOR_AMMO 6&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_9MM_AMMO 10@script fix_boy@fix_MidTier}
{566}{}{PID_9MM_BALL@Старательно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_REPAIR 140&SK_SMALL_GUNS 90@PID_PB_FOR_AMMO 6&PID_GUNPOWDER 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_9MM_BALL 11@script fix_boy@fix_MidTier}
{568}{}{PID_7_62MM_AMMO@Аккуратно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_SMALL_GUNS 60&SK_REPAIR 140@PID_CRAFT_M_BARS 3&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 6&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_7_62MM_AMMO 10@script fix_boy@fix_MidTier}
{570}{}{PID_5MM_JHP@Аккуратно засыпать порох в новые гильзы, вставить пули@SK_SMALL_GUNS 20@ST_LEVEL 12&SK_SMALL_GUNS 60&SK_REPAIR 140@PID_CRAFT_M_BARS 3&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 6&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1@PID_5MM_JHP 10@script fix_boy@fix_MidTier}

{655}{}{DEVIDER@ БРОНЯ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{660}{}{PID_SANDBAG_EMPTY@Мешок. Да, его можно сшить.@@SK_OUTDOORSMAN 35@PID_CRAFT_L_RAGS 2&PID_CRAFT_L_LINT 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_SANDBAG_EMPTY 1@script fix_boy@fix_FreeHands}
{665}{}{PID_SANDBAG_1@Есть пустой мешок? Скорей набери в него песка!@@@PID_SANDBAG_EMPTY 1@PID_SHOVEL 1@PID_SANDBAG_1 1@script fix_boy@fix_FreeHands}
{666}{}{PID_BAG@Берем мешок, связываем одну из сторон веревкой.@@SK_OUTDOORSMAN 40@PID_SANDBAG_EMPTY 1&PID_ROPE 1@@PID_BAG 1@script fix_boy@fix_FreeHands}
{667}{}{PID_BACKPACK@Обычный такой рюкзак.@@SK_OUTDOORSMAN 80@PID_BAG 1&PID_CRAFT_L_HIDE 4&PID_CRAFT_L_LINT 4@@PID_BACKPACK 1@script fix_boy@fix_FreeHands}
{668}{}{PID_MOTOGLES@Стильно. Модно. Молодежно.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 70@PID_BOTTLE_EMPTY 2&PID_CRAFT_M_BARS 2&PID_PART_OF_ROPE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_MOTOGLES 1@script fix_boy@fix_FreeHands}

{672}{}{DEVIDER@ БРОНЯ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{674}{}{PID_BALL@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. В качестве красителя подойдёт хитин.@@SK_OUTDOORSMAN 40@PID_CRAFT_L_RAGS 6&PID_CRAFT_L_LINT 4&PID_MANTIS_SHELL 3@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_BALL 1@script fix_boy@fix_FreeHands}
{675}{}{PID_PURPLE_ROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. В качестве красителя подойдёт цветок брока.@@SK_OUTDOORSMAN 40@PID_CRAFT_L_RAGS 6&PID_CRAFT_L_LINT 4&PID_BROC_FLOWER 5&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_PURPLE_ROBE 1@script fix_boy@fix_FreeHands}
{680}{}{PID_SANDROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава.@ST_STRENGTH 0@SK_OUTDOORSMAN 40@PID_CRAFT_L_RAGS 6&PID_CRAFT_L_LINT 4@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_SANDROBE 1@script fix_boy@fix_FreeHands}
{690}{}{PID_LEATHER_JACKET@Сшейте куртку из кусков шкур и ткани. По последней моде без одного рукава.@@SK_OUTDOORSMAN 40@PID_CRAFT_L_LINT 2&PID_CRAFT_L_HIDE 6@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_SHIV 1@PID_LEATHER_JACKET 1@script fix_boy@fix_LowTier}
{700}{}{PID_CURED_LEATHER_ARMOR@Плотная куртка? Да будет так. Несколько дополнительных слоев кожи удовлетворят вашу потребность быть более защищенным.@SK_REPAIR 30|SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 80&SK_REPAIR 90@PID_CRAFT_L_HIDE 10&PID_CRAFT_L_LINT 2&PID_BRAHMIN_SKIN 1&PID_LEATHER_JACKET 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_CURED_LEATHER_ARMOR 1@script fix_boy@fix_MidTier}
{710}{}{PID_CURED_LEATHER_ARMOR_MK_II@Хотите ещё более плотную куртку? Пожалуйста. Только учтите, что она не такая просторная, хоть и выглядит достаточно стильно.@SK_REPAIR 30|SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 90&SK_REPAIR 120@PID_CRAFT_M_BARS 2&PID_CRAFT_L_LINT 2&PID_CURED_LEATHER_ARMOR 1&PID_METAL_LIST_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_CURED_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_HiTier}
{720}{}{PID_LEATHER_ARMOR@Шкуры брамина, сшитые в несколько слоёв, позволят чувствовать себя защищённей.@SK_OUTDOORSMAN 30|SK_REPAIR 20@SK_OUTDOORSMAN 80&SK_REPAIR 40&ST_STRENGTH 5@PID_BRAHMIN_SKIN 2&PID_CRAFT_L_LINT 6&PID_ROPE 1&PID_WORKBENCH_TOKEN 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_LEATHER_ARMOR 1@script fix_boy@fix_LowTier}
{725}{}{PID_LEATHER_ARMOR_MK_II@Укрепите броню несколькими слоями кожи и обработайте её химикатами для улучшения защитных свойств.@SK_OUTDOORSMAN 20|SK_REPAIR 20@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_LEATHER_ARMOR 1&PID_ROPE 1&PID_GOLDEN_GECKO_PELT 2&PID_CHEMICALS 1&PID_WORKBENCH_TOKEN 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_REVFIST1 1@PID_LEATHER_ARMOR_MK_II 1@script fix_boy@fix_MidTier}
{726}{}{ITEM_TREASURE_HOLE@Шкуры огненного геккона, сшитые поверх основных слоёв, позволят чувствовать себя более огнеустойчивым.@SK_OUTDOORSMAN 20|SK_REPAIR 20@SK_OUTDOORSMAN 80|SK_REPAIR 80&ST_STRENGTH 5@PID_FIRE_GECKO_PELT 2&PID_MEDTHREAD 2&PID_ROPE 1&PID_LEATHER_ARMOR_MK_II 1&PID_WORKBENCH_TOKEN 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1|PID_REVFIST1 1@ITEM_TREASURE_HOLE 1@script fix_boy@fix_HiTier}
{727}{}{PID_LEATHER_ARMOR_MK_III@Удалите поношенную кожу с огнеупорной брони, дополните остатки новой и обработайте её химикатами, устойчивость к огню немного снизится, зато она станет более удобной и универсальной по всем защитным качествам. И более тяжелой.@SK_OUTDOORSMAN 20|SK_REPAIR 20@SK_OUTDOORSMAN 100|SK_REPAIR 100@ITEM_TREASURE_HOLE 1&PID_ROPE 1&PID_CRAFT_L_HIDE 6&PID_CHEMICALS 1&PID_MEDTHREAD 1&PID_WORKBENCH_TOKEN 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_REVFIST1 1&PID_MEDNEEDLE 1@PID_LEATHER_ARMOR_MK_III 1@script fix_boy@fix_HiTier}
{730}{}{PID_METAL_ARMOR@Боитесь ножей из-за угла и когтей гекко? С вашей новой металлической бронёй они будут для вас не больше, чем царапинами.@SK_REPAIR 30@SK_REPAIR 100@PID_CRAFT_M_BARS 5&PID_CRAFT_M_JUNK 2&PID_LEATHER_ARMOR 1&PID_CRAFT_L_LINT 1&PID_IRON_PLATE 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR 1@script fix_boy@fix_MidTier}
{740}{}{PID_METAL_ARMOR_MK_II@Укрепите слабые места на броне, а затем обработайте напильником и отполируйте до блеска для лучше защиты от лазерного оружия.@SK_REPAIR 35@SK_REPAIR 130@PID_METAL_ARMOR 1&PID_CRAFT_M_BARS 2&PID_MOUSE_SKIN 1&PID_IRON_PLATE 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR_MK_II 1@script fix_boy@fix_HiTier}
{745}{}{PID_TESLA_ARMOR@ Вы непризнанный гений? Вам нужно доказать, что вы способны на великие творения? Тогда броня укрепленная переносными катушками тесла будет достойным доказательством того, что ваши мозги еще не спеклись от радиации.  @SK_REPAIR 15@SK_SCIENCE 160&SK_REPAIR 140@PID_METAL_ARMOR_MK_II 1&PID_CRAFT_M_STEL 4&PID_SMALL_ENERGY_CELL 10&PID_CRAFT_E_CHIP 8&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_TESLA_ARMOR 1@script fix_boy@fix_HiTier}
{750}{}{PID_MANTIS_ARMOR@Скрепляем хитиновые пластины подобием чешуи, шкура брамина идет на нагрудник.@SK_OUTDOORSMAN 25|SK_REPAIR 20@SK_OUTDOORSMAN 60&SK_REPAIR 30@PID_CRAFT_L_LINT 1&PID_BRAHMIN_SKIN 1&PID_MANTIS_SHELL 4&PID_WORKBENCH_TOKEN 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MANTIS_ARMOUR 1@script fix_boy@fix_MidTier}
{760}{}{PID_MUMARMOR@Специализированная броня для супермутантов. Укрепляет их и без того мощное тело.@SK_REPAIR 40@SK_REPAIR 120&SK_OUTDOORSMAN 80@PID_CRAFT_M_BARS 8&PID_BRAHMIN_SKIN 4&PID_CRAFT_M_JUNK 2&PID_WELDING 1&PID_IRON_PLATE 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUMARMOR 1@script fix_boy@fix_LowTier}
{770}{}{PID_MUJACKET@Кожанная куртка для мутантов. Технология производста почти не отличается от обычной, но материала уходит в два раза больше.@SK_OUTDOORSMAN 20@SK_REPAIR 35&SK_OUTDOORSMAN 80@PID_CRAFT_L_HIDE 16&PID_CRAFT_L_LINT 4&PID_WORKBENCH_TOKEN 1@PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUJACKET 1@script fix_boy@fix_LowTier}

{790}{}{DEVIDER@ ОРУЖИЕ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{800}{}{PID_SPEARTHROWER1_LOW@Пара пружин, рычаги и рама@SK_REPAIR 15@SK_REPAIR 50&SK_SCIENCE 30@PID_CRAFT_M_JUNK 2&PID_DETAL_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SPEARTHROWER1 1@script fix_boy@fix_LowTier}
{810}{}{PID_SPEARTHROWER2_LOW@Баллон, корпус, ручная помпа.@SK_SCIENCE 5@SK_SCIENCE 80&SK_REPAIR 60@PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1&PID_EMKOCT_MEH 3&PID_DETAL_MEH 1&PID_SOED_MEH 1&PID_CRAFT_L_HIDE 1@PID_MULTI_TOOL 1@PID_SPEARTHROWER2 1@script fix_boy@fix_LowTier}
{820}{}{PID_SPRINGER_RIFLE@Главной проблемой будет найти трубу подходящего диаметра, а спусковой механизм вы соорудить сумеете.@SK_SMALL_GUNS 10@SK_REPAIR 40&SK_OUTDOORSMAN 40&SK_SMALL_GUNS 50@PID_TUBE 1&PID_FIREWOOD 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SPRINGER_RIFLE 1@script fix_boy@fix_LowTier}
{830}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@SK_SMALL_GUNS 10@SK_OUTDOORSMAN 30&SK_REPAIR 40@PID_FIREWOOD 1&PID_CRAFT_M_BARS 1&PID_SHORT_TUBE 1&PID_WORKBENCH_TOKEN 1@@PID_ZIP_GUN 1@script fix_boy@fix_LowTier}
{840}{}{PID_REVOLVER_LOW@Самодельный револьвер.Барабан, курок и ствол. Ничего сложного@SK_SMALL_GUNS 10@SK_SMALL_GUNS 50&SK_REPAIR 40@PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REVOLVER_LOW 1@script fix_boy@fix_LowTier}
{850}{}{PID_PISTOL_LOW@Самозарядный пистолет.проблема в механизме заряжания, из подручного хлама ничего получше не сделать@SK_SMALL_GUNS 30@SK_REPAIR 60@PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 1&PID_SHORT_TUBE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_PISTOL_LOW 1@script fix_boy@fix_LowTier}
{860}{}{PID_REV_RIFLE_LOW@Револьверная винтовка, проще говоря револьвер с длинным стволом и переработанной рукоятью.@@SK_REPAIR 60@PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_CRAFT_M_BARS 1&PID_REVOLVER_LOW 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_REV_RIFLE_LOW 1@script fix_boy@fix_LowTier}
{870}{}{PID_DRUM_GUN_LOW@Барабанная пушка.Собираем затворный механизм, барабанный магазин, автовзвод и надеемся, что это не рассыпется при первом выстреле.@@SK_REPAIR 60&SK_SCIENCE 40@PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_IRON_DETALS 1&PID_PERED_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_DRUM_GUN_LOW 1@script fix_boy@fix_LowTier}
{880}{}{PID_SNIPER_GUN_LOW@Дырокол. Высверливаем ствол, жестко скрепляем раму приклада, присоединяем сошки.@SK_SMALL_GUNS 10@SK_REPAIR 90@PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 1&PID_TUBE 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_SNIPER_GUN_LOW 1@script fix_boy@fix_LowTier}
{885}{}{PID_LOW_SNIPER2@Вы безумно скучаете по выстрелам из руин? У вас есть бронепластины, но нет подходящего убойного оружия? Что-ж, сделайте его себе!@SK_SMALL_GUNS 10@SK_REPAIR 110@PID_SNIPER_GUN_LOW 1&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 2&PID_SOED_MEH 2&PID_TUBE 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LOW_SNIPER2 1@script fix_boy@fix_HiTier}
{886}{}{PID_LOW_SNIPER3@Для сверхлюдей нужно что-то более мощное, нежели та ржавая пушка. Пришла пора отпилить все лишнее и добавить более качественное!@SK_SMALL_GUNS 10@SK_REPAIR 140@PID_LOW_SNIPER2 1&PID_CRAFT_M_BARS 5&PID_TUBE 1&PID_SOED_MEH 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LOW_SNIPER3 1@script fix_boy@fix_HiTier}
{887}{}{PID_SCOPED_HUNTING_RIFLE@Небольшое улучшение на ваше любимое оружие.@SK_SMALL_GUNS 1@SK_REPAIR 130&SK_SCIENCE 40@PID_HUNTING_RIFLE 1&PID_CRAFT_M_BARS 1&PID_BOTTLE_GLASS 2&PID_SOED_MEH 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SCOPED_HUNTING_RIFLE 1@script fix_boy@fix_HiTier}
{890}{}{PID_SMOKE_GUN_LOW@Соединяем различные старые испорченные детали от старых пистолетов, понимание как сделать такую вещь приходит только после первого убийства.@SK_SMALL_GUNS 30@SK_REPAIR 80@PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_CRAFT_M_BARS 1&PID_BANKA_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_SMOKE_GUN_LOW 1@script fix_boy@fix_LowTier}
{900}{}{PID_AUTOGUN_LOW@Берем обычный пистолет, модернизируем затворный механизм, для автовзвода, закрываем корпусом. Громоздко, но работает.@SK_SMALL_GUNS 30@SK_REPAIR 80&SK_SCIENCE 50@PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_CRAFT_M_BARS 1&PID_10MM_PISTOL 1&PID_DETAL_MEH 1&PID_METAL_LIST_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_AUTOGUN_LOW 1@script fix_boy@fix_LowTier}
{910}{}{PID_SHOTGUN@Найдите две трубы более-менее подходящего диаметра, изготовьте к ним приклад и простенький спусковой механизм.@@ST_LEVEL 6&SK_SMALL_GUNS 60&SK_REPAIR 150@PID_TUBE 2&PID_SOED_MEH 2&PID_CRAFT_M_JUNK 4&PID_CRAFT_M_BARS 2&PID_WOOD_PART 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SHOTGUN 1@script fix_boy@fix_MidTier}
{915}{}{PID_COMBAT_SHOTGUN@Не хватает режима автоматического огня у дробовика? Вы знаете как это исправить!@@ST_LEVEL 11&SK_SMALL_GUNS 40&SK_REPAIR 170@PID_TUBE 2&PID_SOED_MEH 2&PID_CRAFT_M_STEL 4&PID_IRON_DETALS 3&PID_CRAFT_M_BARS 7&PID_SHOTGUN 1&PID_FIREWOOD 1&PID_CRAFT_M_JUNK 4@PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1&PID_WELDING 1@PID_COMBAT_SHOTGUN 1@script fix_boy@fix_HiTier}
{920}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 20@SK_REPAIR 40&SK_SMALL_GUNS 30@PID_SHOTGUN 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SAWED_OFF_SHOTGUN 1@script fix_boy@fix_LowTier}
{930}{}{PID_SHOTPISTOL_LOW@Берем парочку труб подходящего диаместра, воруем спусковой механизм у простенького пистолета, модернизируем, тщательно закрепляем и получаем весьма убойную пушку.@SK_SMALL_GUNS 30&SK_REPAIR 40@SK_REPAIR 70&SK_SMALL_GUNS 50@PID_ZIP_GUN 1&PID_SOED_MEH 1&PID_SHORT_TUBE 2&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_12g_LOW 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHOTPISTOL_LOW 1@script fix_boy@fix_LowTier}
{935}{}{PID_QUADRO_SHOTGUN@Хочется что-то более внушительное? Окей. Подыщите подходящие трубы, сваркой приварите к пистолету и обмотайте их цепью, предварительно удалив стволы самого пистолета, и сделайте единый спусковой механизм.@SK_SMALL_GUNS 30@SK_REPAIR 90&SK_SMALL_GUNS 60@PID_SOED_MEH 1&PID_DETAL_MEH 1&PID_TUBE 2&PID_CHAIN 1&PID_SHOTPISTOL_LOW 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_QUADRO_SHOTGUN 1@script fix_boy@fix_LowTier}
{940}{}{PID_BIGGUN_LOW@Большая пушка.@SK_BIG_GUNS 10@SK_REPAIR 60@PID_CRAFT_M_JUNK 1&PID_TUBE 1&PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_BIGGUN_LOW 1@script fix_boy@fix_LowTier}
{941}{}{PID_14mm_BIGGUN2_LOW@Вам не нравится ваша большая пушка? Сделайте ее еще больше!@SK_BIG_GUNS 40@SK_REPAIR 120&SK_BIG_GUNS 60@PID_BIGGUN_LOW 1&PID_SOED_MEH 2&PID_CRAFT_M_JUNK 4&PID_TUBE 1&PID_CRAFT_M_BARS 4&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_14mm_BIGGUN2_LOW 1@script fix_boy@fix_MidTier}
{942}{}{PID_GATLING_LOW@Вы любите стрелять и крутить? Если да, то непременно создайте эту громадину, она сполна удовлетворит вашу потребность.@SK_BIG_GUNS 30@ST_LEVEL 5&SK_REPAIR 120&SK_BIG_GUNS 90@PID_CRAFT_M_JUNK 4&PID_TUBE 6&PID_SOED_MEH 2&PID_CRAFT_M_BARS 3&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_GATLING_LOW 1@script fix_boy@fix_LowTier}
{950}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_REPAIR 30@SK_REPAIR 100&SK_SCIENCE 60@PID_CRAFT_M_BARS 3&PID_TUBE 1&PID_CRAFT_M_JUNK 2&PID_SOED_MEH 1&PID_EMKOCT_MEH 2&PID_LIGHTER 1&PID_WORKBENCH_TOKEN 1@PID_WELDING 1&PID_MULTI_TOOL 1@PID_FLAMER 1@script fix_boy@fix_LowTier}
{960}{}{PID_SAWGUN_LOW@Пушка пила.Собираем раму, устанавливаем движок, натягиваем цепь и передаточный механизм для катапульты.@SK_BIG_GUNS 30@SK_REPAIR 120&SK_SCIENCE 60&SK_BIG_GUNS 40@PID_CRAFT_M_BARS 8&PID_CRAFT_M_JUNK 3&PID_TUBE 2&PID_MOTOR 1&PID_CHAIN 2&PID_PERED_MEH 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SAWGUN_LOW 1@script fix_boy@fix_LowTier}
{965}{}{PID_ONEHAND_ROCKET_LAUNCHER@В жизни настал такой момент, когда врага уже не удивить обычным пулеметом?! Вы считаете что луну надо взорвать, что бы это противное светило не мешало спать? Тогда ручная пушка - ваш выбор. @@ST_LEVEL 12&SK_REPAIR 150&SK_SCIENCE 40&SK_BIG_GUNS 60@PID_SOED_MEH 1&PID_DETAL_MEH 2&PID_EMKOCT_MEH 1&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 5&PID_METAL_LIST_MEH 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_ONEHAND_ROCKET_LAUNCHER 1@script fix_boy@fix_MidTier}

{970}{}{PID_PLASMA_SMG_LOW@Излучатель, отражатели, камера для энергоячеек, вот вроде и все.@SK_ENERGY_WEAPONS 20@ST_LEVEL 9&SK_REPAIR 80&SK_SCIENCE 120@PID_CRAFT_E_CHIP 4&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 4&PID_TUBE 2&PID_CRAFT_E_LAMP 6&PID_ELECTO_MEH 2&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_PLASMA_SMG_LOW 1@script fix_boy@fix_MidTier}
{975}{}{PID_PLASMA_SMG_LOW2@Хороший мастер запросто заметит изъяны в этой пушке, которые следовало бы исправить.@SK_ENERGY_WEAPONS 20@ST_LEVEL 9&SK_REPAIR 140&SK_SCIENCE 60@PID_CRAFT_E_CHIP 4&PID_PLASMA_SMG_LOW 1&PID_CRAFT_E_LAMP 3&PID_ELECTO_MEH 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_PLASMA_SMG_LOW2 1@script fix_boy@fix_HiTier}
{980}{}{PID_LASER_PISTOL_LOW@Энергетическое оружие. Не очень мощное, но относительно простое в производстве.@SK_REPAIR 20@ST_LEVEL 9&SK_REPAIR 90&SK_SCIENCE 100&SK_ENERGY_WEAPONS 80@PID_CRAFT_M_BARS 6&PID_SMALL_ENERGY_CELL 6&PID_CRAFT_M_JUNK 4&PID_ZIP_GUN 1&PID_CRAFT_E_CHIP 6&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_PISTOL_LOW 1@script fix_boy@fix_MidTier}
{981}{}{PID_LASER_PISTOL_LOW2@Модификация кустарного лазерного пистолета. Увеличена мощность и дальность.@SK_REPAIR 20@ST_LEVEL 12&SK_REPAIR 140&SK_SCIENCE 60&SK_ENERGY_WEAPONS 100@PID_CRAFT_M_BARS 3&PID_SMALL_ENERGY_CELL 1&PID_CRAFT_M_JUNK 2&PID_LASER_PISTOL_LOW 1&PID_CRAFT_E_CHIP 12&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_PISTOL_LOW2 1@script fix_boy@fix_HiTier}
{982}{}{PID_LASER_RIFLE_LOW@Пришла пора сделать что-то более громоздкое и убойное, а за основу, для создания этого монстра, можно взять лазерный пистолет.@SK_REPAIR 20@ST_LEVEL 12&SK_REPAIR 150&SK_SCIENCE 70&SK_ENERGY_WEAPONS 100@PID_CRAFT_M_BARS 5&PID_SMALL_ENERGY_CELL 2&PID_CRAFT_M_JUNK 3&PID_CRAFT_E_CHIP 10&PID_WORKBENCH_TOKEN 1&PID_LASER_PISTOL_LOW2 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_RIFLE_LOW 1@script fix_boy@fix_HiTier}

{985}{}{PID_SOLAR_SCORCHER@Улучшение системы охлаждения у пистолета, пара самодельных солнечных батарей из подручной химии и немного магии - выродок мертвой эры высоких технологий готов..@SK_SCIENCE 20@ST_LEVEL 9&SK_REPAIR 70&SK_SCIENCE 140@PID_LASER_PISTOL_LOW 1&PID_CRAFT_M_BARS 4&PID_CHEMICALS 4&PID_CRAFT_E_CHIP 4&PID_OHLAD_MEH 2@PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_SOLAR_SCORCHER 1@script fix_boy@fix_HiTier}
{986}{}{PID_SUN@Ложе от старой охотничьей винтовки, детали "Солнечного Скорчера", чертежи и немного воображения и вуаля, перед вами лежит авторская лазерная винтовка "Солнышко"! Хм. Однозарядная. И быстро изнашивающаяся... Но - совершенно не требующая боеприпасов!@@ST_LEVEL 12&ST_INTELLECT 5&SK_SCIENCE 150&SK_REPAIR 80&SK_ENERGY_WEAPONS 90@PID_SOLAR_SCORCHER 1&PID_HUNTING_RIFLE 1|PID_LOW_SNIPER3 1&PID_CRAFT_M_BARS 5&PID_CRAFT_M_JUNK 2&PID_TUBE 2&PID_BOTTLE_GLASS 1@PID_SUNC 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SUN 1@script fix_boy@fix_HiTier}
{987}{}{PID_SUN2@Обзаведясь необходимым количеством знаний и материалов, вы приступаете к модернизации вашего оружия. К чёрту дерево - только металл! К чёрту устаревшие аккумуляторы и быстро изнашивающиеся детали, вы достойны лучшего. Отныне полного заряда винтовки хватает на целых три выстрела, а скорость износа не превышает таковой у заводских образцов.@@ST_LEVEL 12&ST_INTELLECT 6&SK_SCIENCE 170&SK_REPAIR 120&SK_ENERGY_WEAPONS 100@PID_SUN 1&PID_IRON_PLATE 4&PID_SMALL_ENERGY_CELL 15&PID_BOTTLE_GLASS 2&PID_WELDING 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SUN2 1@script fix_boy@fix_HiTier}
{988}{}{PID_SUN3@Вы - настоящий гений энергетики? Что ж, докажите это, проведя ещё одну модернизацию вашей винтовки. Только высококачественные полимеры, революционная технология накопления энергии и потрясающая фокусировка луча. Да с такой малышкой хоть в космос! Винтовка теперь может делать пять выстрелов до перезарядки, а редчайшие материалы корпуса сохранят её работоспособность вплоть до нового Судного дня.@@ST_LEVEL 12&ST_INTELLECT 8&SK_SCIENCE 180&SK_REPAIR 140&SK_ENERGY_WEAPONS 120@PID_SUN2 1&PID_IRON_PLATE 3&PID_MICRO_FUSION_CELL 10&PID_BOTTLE_GLASS 2&PID_WELDING 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_SUN3 1@script fix_boy@fix_HiTier}

{992}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{996}{}{PID_CHEMICALS@Аккуратно сцеживайте с емкости остатки химикатов. Рекомендуется принять рад-х перед всем действом и обмотать чем-нибудь руки.@SK_SCIENCE 20@ST_LEVEL 9&SK_SCIENCE 120@PID_BOTTLE_GLASS 3&PID_RAD_LOW 1@PID_CRAFT_L_RAGS 2@PID_CHEMICALS 3@script fix_boy@fix_FreeHands}
{1000}{}{PID_TNT@Вливайте азотную кислоту в толуол, постоянно нагревая, осадок просушите и поместите в какую-нибудь банку.@SK_SCIENCE 20@SK_SCIENCE 100@PID_CHEMICALS 2&PID_BOTTLE_FULL 1&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_TNT 1@script fix_boy@fix_LowTier}
{1005}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 20@SK_SCIENCE 110&SK_OUTDOORSMAN 50@PID_MEAT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 1&PID_WORKBENCH_TOKEN 1@PID_CHEMISTRY_MANUAL 1@PID_NITROGLYCERIN 1@script fix_boy@fix_LowTier}
{1010}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@SK_TRAPS 20@SK_OUTDOORSMAN 30&SK_SCIENCE 60&SK_TRAPS 120&SK_REPAIR 100@PID_NITROGLYCERIN 2&PID_HEALING_POWDER 2&PID_FIREWOOD 1&PID_CRAFT_E_CHIP 1&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_DYNAMITE 1@script fix_boy@fix_HiTier}
{1015}{}{PID_PLASTIC_EXPLOSIVES_DULL@Найдите в мусоре какой-нибудь пластик, нагрейте его до плавления и вмешивайте в него порошок гексогена. Всё, теперь он удобен для хранения.@SK_SCIENCE 20@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_CRAFT_M_JUNK 2&PID_HEXOGEN 1&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1@PID_PLASTIC_EXPLOSIVES_DULL 1@script fix_boy@fix_MidTier}
{1020}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор из запчастей и старого радио.@SK_REPAIR 20@SK_REPAIR 130&SK_TRAPS 120@PID_PLASTIC_EXPLOSIVES_DULL 1&PID_CRAFT_E_CHIP 1&PID_RADIO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_CHEMISTRY_MANUAL 1|PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_PLASTIC_EXPLOSIVES 1@script fix_boy@fix_HiTier}
{1025}{}{PID_MINE@Высыпьте гексоген в какую-нибудь старую банку, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@SK_TRAPS 20@SK_TRAPS 130&SK_SCIENCE 100&SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_HEXOGEN 1&PID_CRAFT_M_JUNK 2&PID_SHOTGUN_SHELLS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_MINE 1@script fix_boy@fix_LowTier}

{1028}{}{DEVIDER@ МАЙНКАМПФ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{1030}{}{PID_METAL_ORE@Очищаем породу от примесей и выплавляем  шлак. Используйте перчатки при работе с огнем!@@ST_LEVEL 5&SK_REPAIR 120|SK_SCIENCE 120@PID_METAL_ORE 3@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_MOTOGLES 1&PID_WORKBENCH_TOKEN 1@PID_CRAFT_M_BARS 10@script fix_boy@fix_HiTier}
{1031}{}{PID_MINERAL@ Очищаем породу от примесей @@ST_LEVEL 5&SK_REPAIR 150|SK_SCIENCE 150@PID_MINERAL 5@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_MOTOGLES 1&PID_WORKBENCH_TOKEN 1@PID_GUNPOWDER 3&PID_HEXOGEN 1@script fix_boy@fix_HiTier}
{1032}{}{PID_GOLD_NUGGET@ Вам нечем платить за выпивку? А может.. вам хочется захватить мир? Колышки нынче добываются проблемно? Тогда вам определенно стоит выплавить себе горсть монет! @@SK_REPAIR 150&SK_SCIENCE 150@PID_GOLD_NUGGET 1&PID_WORKBENCH_TOKEN 1@PID_MOTOGLES 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_BOTTLE_CAPS 250@script fix_boy@fix_MidTier}
{1035}{}{PID_GOLD_NUGGET@ Берем достаточное количество руды и масляных компонентов, воды, а так же ваш багаж научных знаний. После проводим курс масляной флотации и вуаля! Вы почти знаете секрет философского камня.  @@ST_LEVEL 12&SK_SCIENCE 150&SK_REPAIR 150@PID_METAL_ORE 5&PID_MINERAL 2&PID_ROCK 15&PID_BOTTLE_FULL 6@PID_MOTOGLES 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_GOLD_NUGGET 2&PID_BOTTLE_EMPTY 6@script fix_boy@fix_HiTier}
{1036}{}{PID_CRAFT_L_RAGS@Сшить тряпку из подходящих материалов не так уж и сложно.@@SK_OUTDOORSMAN 30&SK_REPAIR 30@PID_CRAFT_L_LINT 8|PID_BROC_FLOWER 10@PID_SHIV 1&PID_MEDTHREAD 1&PID_MEDNEEDLE 1@PID_CRAFT_L_RAGS 1@script fix_boy@fix_LowTier}
{1037}{}{PID_IRON_DETALS@При наличии достаточного количества металла и качественных инструментов, можно отштамповать необходимую деталь на верстаке.@@SK_REPAIR 120@PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_IRON_DETALS 1@script fix_boy@fix_HiTier}
{1038}{}{PID_TUBE@Нужна труба? Сварите её из несколько кусков поменьше, либо отштампуйте из железа на верстаке, либо просто отпилите лишнее от имеющегося под рукой куска трубопровода.@@SK_REPAIR 90@PID_CRAFT_M_BARS 3|PID_SHORT_TUBE 3|PID_WATER_TUBE 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_TUBE 1@script fix_boy@fix_LowTier}
{1039}{}{DEVIDER@Любите ковать и плавить железо? Тогда вы точно должны найти применение этому хламу!@@ST_LEVEL 5&SK_REPAIR 120|SK_SCIENCE 120@PID_SHORT_TUBE 2|PID_SPIKE_MEH 3|PID_PLANK 1|PID_IRON_PROD 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_MOTOGLES 1&PID_WORKBENCH_TOKEN 1@PID_CRAFT_M_BARS 10@script fix_boy@fix_MidTier}

{1075}{}{DEVIDER@ ДЕКРАФТ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{1076}{}{PID_VIC_RADIO@Микросхемы и радиодетали будут куда полезней в ваших руках, нежели в этой раздолбанной рации.@@ST_LEVEL 4&SK_SCIENCE 60&SK_REPAIR 80@PID_VIC_RADIO 1@PID_MULTI_TOOL 1&PID_SHIV 1@PID_CRAFT_E_LAMP 1&PID_CRAFT_E_CHIP 1@script fix_boy@fix_LowTier}
{1077}{}{PID_RADIO@Микросхемы и радиодетали будут куда полезней в ваших руках, нежели в этой работающей рации.@@ST_LEVEL 4&SK_SCIENCE 60&SK_REPAIR 90@PID_RADIO 1@PID_MULTI_TOOL 1&PID_SHIV 1@PID_CRAFT_E_LAMP 2&PID_CRAFT_E_CHIP 2@script fix_boy@fix_LowTier}
{1078}{}{DEVIDER@Вооружившись паяльником либо раскаленным добела прутом вы аккуратно снимаете с печатной платы все выпирающие элементы, добирая недостающее из ближайшей кучи мусора.@@SK_SCIENCE 50&SK_REPAIR 50@PID_CRAFT_E_CHIP 3&PID_CRAFT_M_JUNK 2@PID_SHIV 1|PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_CRAFT_E_LAMP 2@script fix_boy@fix_LowTier}
{1079}{}{DEVIDER@Вооружившись паяльником либо раскаленным добела прутом вы аккуратно снимаете с печатной платы все выпирающие элементы и даже больше.@@SK_SCIENCE 80&SK_REPAIR 80@PID_CRAFT_E_CHIP 4@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1@PID_CRAFT_E_LAMP 3@script fix_boy@fix_LowTier}
{1080}{}{DEVIDER@ Разбирая эти фонарики, вы наверняка сможете найти хотя бы одну пригодную к работе батарейку. @@SK_SCIENCE 70|SK_REPAIR 70|ST_LUCK 6&ST_LEVEL 6@PID_FLARE 8@PID_MULTI_TOOL 1@PID_CUENCELL_LOW 1&PID_CRAFT_M_JUNK 1@script fix_boy@fix_LowTier}
{1082}{}{DEVIDER@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться. @@SK_REPAIR 30|SK_OUTDOORSMAN 70@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_ZIP_GUN 1|PID_IRON_DETALS 1|PID_SPRINGER_RIFLE 1|PID_AXE 1|PID_SHOVEL 1|PID_BRASS_KNUCKLES 1|PID_FLARE 1@PID_MULTI_TOOL 1@PID_CRAFT_M_BARS 1@script fix_boy@fix_LowTier}
{1083}{}{DEVIDER@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться. @@SK_REPAIR 40|SK_SCIENCE 40|SK_OUTDOORSMAN 80@PID_HLAM_MEH 3|PID_HLAM2_MEH 3|PID_BANKA_MEH 3|PID_EMKOCT_MEH 1|PID_IRON_DETALS 1|PID_METAL_LIST_MEH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@script fix_boy@fix_LowTier}
{1084}{}{DEVIDER@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться. @@SK_REPAIR 40|SK_SCIENCE 40|SK_OUTDOORSMAN 80@PID_SOED_MEH 1|PID_OHLAD_MEH 1|PID_DETAL_MEH 1|PID_EMKOCT_MEH 1|PID_CHAIN 2|PID_PERED_MEH 1|PID_IRON_PLATE 1@PID_SUPER_TOOL_KIT 1@PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@script fix_boy@fix_LowTier}
{1085}{}{DEVIDER@ Just do it. @@SK_OUTDOORSMAN 30|SK_REPAIR 30|SK_FIRST_AID 30@PID_CRAFT_L_RAGS 1@PID_KNIFE 1|PID_SHIV 1|PID_THROWING_KNIFE 1@PID_CRAFT_L_LINT 4@script fix_boy@fix_LowTier}
{1088}{}{DEVIDER@ Разрезаем здоровую шкуру на куски @@SK_OUTDOORSMAN 15@PID_MOUSE_SKIN 1@PID_KNIFE 1|PID_SHIV 1|PID_THROWING_KNIFE 1|PID_REVFIST1 1@PID_CRAFT_L_HIDE 2@script fix_boy@fix_LowTier}
{1090}{}{DEVIDER@ Разрезаем здоровую кусок кожи на тряпки @@SK_OUTDOORSMAN 15@PID_CRAFT_L_HIDE 1@PID_KNIFE 1|PID_SHIV 1|PID_THROWING_KNIFE 1|PID_REVFIST1 1@PID_CRAFT_L_RAGS 4@script fix_boy@fix_LowTier}
{1091}{}{DEVIDER@ Распилите эту трубу пополам @@SK_REPAIR 20|SK_SCIENCE 25|SK_OUTDOORSMAN 30@PID_TUBE 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHORT_TUBE 2@script fix_boy@fix_LowTier}
{1092}{}{DEVIDER@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться.@@SK_SCIENCE 60|SK_REPAIR 50|SK_OUTDOORSMAN 80@PID_BIGGUN_LOW 1|PID_DRUM_GUN_LOW 1|PID_SNIPER_GUN_LOW 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_CRAFT_M_JUNK 2&PID_TUBE 1@script fix_boy@fix_LowTier}
{1093}{}{DEVIDER@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться. @@SK_REPAIR 80&SK_SCIENCE 25@PID_IRON_BAR 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_CRAFT_M_BARS 5@script fix_boy@fix_LowTier}
{1094}{}{PID_PLANK@ Разберите этот бесполезный хлам и возьмите то, что вам могло бы пригодиться. @@@PID_PLANK 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_SPIKE_MEH 4@script fix_boy@fix_LowTier}

{1095}{}{DEVIDER@ РЕМОНТ @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{1096}{}{PID_COMBAT_ARMOR@ Слезами делу не поможешь, так что возьми этот, ставший мусором после стольких боев, нагрудник, и законопать подручным материалом все серьезные повреждения. На оригинал мало похоже, но можно снова использовать по назначению! @@ST_LEVEL 12&SK_REPAIR 140&SK_SCIENCE 50@PID_COMBAT_ARMOR 1|PID_POLICE_ARMOR 1|PID_CASER 1|PID_CADES 1&PID_CRAFT_M_BARS 6&PID_CRAFT_M_JUNK 2&PID_IRON_PLATE 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_BALL_DEAD 1@script fix_boy@fix_HiTier}

{1201}{}{DEVIDER@ Временный крафт, пока отсутствует спавн необходимых предметов @@@PID_DEVIDER 1@@PID_DEVIDER 1@}

{1209}{}{PID_RED_CONDOM@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_OUTDOORSMAN 70@PID_CRAFT_M_JUNK 3@@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_FLINT 1&PID_CHAIN 2@script fix_boy@fix_LowTier}
{1210}{}{PID_RED_CONDOM@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_OUTDOORSMAN 80@PID_CRAFT_M_JUNK 5@@PID_SPIKE_MEH 2&PID_SHORT_TUBE 1&PID_FLINT 2&PID_RED_CONDOM 3&PID_HYPODERMIC_NEEDLE 2@script fix_boy@fix_LowTier}
{1211}{}{PID_RED_CONDOM@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_OUTDOORSMAN 100@PID_CRAFT_M_JUNK 7@@PID_METAL_ORE 2&PID_MINERAL 3&PID_CRAFT_M_BARS 1&PID_SHARPENED_POLE 1&PID_VIC_RADIO@script fix_boy@fix_LowTier}
{1215}{}{PID_RED_CONDOM@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_OUTDOORSMAN 140@PID_CRAFT_M_JUNK 11@@PID_FIRE_GECKO_PELT 1&PID_VIC_RADIO 2&PID_HYPODERMIC_NEEDLE 3&PID_DICE 1&PID_MAGIC_8_BALL 1@script fix_boy@fix_LowTier}
{1250}{}{PID_EMKOCT_MEH@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_REPAIR 100|SK_SCIENCE 100@PID_CRAFT_M_JUNK 6@@PID_RAD_LOW 4&PID_SHORT_TUBE 3&PID_IRON_DETALS 1&PID_PERED_MEH 1&PID_CRAFT_M_BARS 1@script fix_boy@fix_LowTier}
{1251}{}{PID_EMKOCT_MEH@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_REPAIR 100|SK_SCIENCE 100@PID_CRAFT_M_JUNK 7@@PID_SOED_MEH 1&PID_OHLAD_MEH 2&PID_DETAL_MEH 2&PID_EMKOCT_MEH 1&PID_CHAIN 2&PID_VIC_RADIO@script fix_boy@fix_LowTier}
{1252}{}{PID_EMKOCT_MEH@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_REPAIR 100|SK_SCIENCE 100@PID_CRAFT_M_JUNK 7@@PID_HLAM_MEH 3&PID_HLAM2_MEH 1&PID_BANKA_MEH 1&PID_SPIKE_MEH 2&PID_TUBE 1&PID_PB_PLATE 1&PID_IRON_PLATE 1@script fix_boy@fix_LowTier}
{1253}{}{PID_EMKOCT_MEH@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_REPAIR 120|SK_SCIENCE 120@PID_CRAFT_M_JUNK 10@@PID_ELECTO_MEH 1&PID_DVIGAT_MEH 2&PID_METAL_LIST_MEH 1&PID_CRAFT_M_STEL 1&PID_CHAIN 3&PID_MOTOR 1@script fix_boy@fix_LowTier}
{1290}{}{PID_EMKOCT_MEH@Покопавшись в груде мусора, вы наверняка сможете найти что-то полезное!@@SK_FIRST_AID 100|SK_DOCTOR 100@PID_CRAFT_M_JUNK 4@@PID_HYPODERMIC_NEEDLE 4&PID_VIC_RADIO 1&PID_BROC_FLOWER 1&PID_XANDER_ROOT 1@script fix_boy@fix_LowTier}