{10}{}{Герой}
{20}{}{Героиня}
{30}{}{Деревенщина}
{40}{}{Деревенщина}
{50}{}{Рад-скорпион}
{51}{}{Небольшой мутировавший скорпион.}
{60}{}{Рад-скорпион}
{61}{}{Мутировавший скорпион}
{70}{}{Коготь Смерти}
{71}{}{Маленький Коготь Смерти}
{80}{}{Коготь Смерти}
{81}{}{Маленький Коготь Смерти}
{90}{}{Пес}
{91}{}{Собака, наверняка бездомная, дворняжьей породы.}
{100}{}{Брамин}
{101}{}{Двухголовая корова-мутант.}
{110}{}{Грызун}
{111}{}{Самый обыкновенный большой грызун.}
{120}{}{Мантис}
{121}{}{Страшно надоедливое существо.}
{130}{}{Старейшая}
{140}{}{Хакунин}
{150}{}{Минок}
{160}{}{Хищный Цветок}
{161}{}{Плотоядное растение.}
{170}{}{Симпатичный раб}
{180}{}{Красивый раб}
{190}{}{Здоровая рабыня}
{200}{}{Здоровый раб}
{210}{}{Сильная рабыня}
{220}{}{Сильный раб}
{230}{}{Боевая рабыня}
{240}{}{Боевой раб}
{250}{}{Умная рабыня}
{260}{}{Умный раб}
{270}{}{Обычная рабыня}
{280}{}{Обычный раб}
{290}{}{Анна}
{300}{}{Крутой бандит}
{310}{}{Крутая воровка}
{311}{}{Её цепкий взгляд следит за вами. Берегите свой кошелёк}
{320}{}{Жестокий бандит}
{330}{}{Лихая разбойница}
{340}{}{Проворный бандит}
{350}{}{Ловкая потаскуха}
{360}{}{Мощный бандит}
{370}{}{Стерва с пушкой}
{380}{}{Бандит с пушкой}
{390}{}{Дешевая шлюха}
{400}{}{Крутой Охранник}
{410}{}{Крутая Охранница}
{420}{}{Мощный Охранник}
{430}{}{Мощная Охранница}
{440}{}{Ловкий Охранник}
{450}{}{Ловкая Охранница}
{460}{}{Охранник со стволом}
{470}{}{Охранница со стволом}
{480}{}{Охранник с пушкой}
{490}{}{Охранница с пушкой}
{500}{}{Сирота}
{501}{}{Худой и изнемождённый оборванец, при виде вас он протягивает ладошки и смотрит с мольбой}
{510}{}{Сиротка}
{511}{}{Бедная сиротка. Её платье изорвано и одежда свисает по большей части лоскутами. Её грязное личико измождено}
{520}{}{Ребенок}
{521}{}{Обычный мальчишка. Играет и резвится, да занимается своими детскими делами. Ему нет дела до вас}
{530}{}{Ребенок}
{531}{}{Обычная девочка. Она играет со своими друзьями, строит куличики из радиоактивного песка. Ей нет дела до вас}
{540}{}{Нищий}
{541}{}{Жалкий нищий. Он влочет своё жалкое существование и пытается выжить}
{550}{}{Нищенка}
{551}{}{Нищенка, которая ещё имеет моральные принципы и не уходит в проституцию, это достойно уважения... Наверное}
{560}{}{Плохой торговец}
{570}{}{Плохая торговка}
{580}{}{Обычный продавец}
{590}{}{Обычная продавщица}
{600}{}{Мастер-купец}
{610}{}{Мастерица-купчиха}
{620}{}{Вик}
{630}{}{Слабый крестьянин}
{640}{}{Слабая крестьянка}
{650}{}{Обычный крестьянин}
{660}{}{Обычная крестьянка}
{670}{}{Сильный крестьянин}
{680}{}{Сильная крестьянка}
{690}{}{Слабый охранник}
{700}{}{Слабая охранница}
{710}{}{Слабый стрелок}
{720}{}{Слабая снайперша}
{730}{}{Робот-ремонтник}
{740}{}{Робот-ремонтник тип 2}
{750}{}{Робомозг}
{760}{}{Летучий Глаз}
{770}{}{Робот-страж}
{780}{}{Робот-страж тип 2}
{790}{}{Робомозг}
{800}{}{Мелкий ящер}
{810}{}{Крутой ящерок}
{820}{}{Волк}
{821}{}{Жестокое и свирепое хищное животное.}
{830}{}{Золотой ящер}
{840}{}{Коготь Смерти}
{850}{}{Отродье Когтя Смерти}
{860}{}{Сильный Золотой ящер}
{870}{}{Линетта}
{880}{}{Доктор Трой}
{890}{}{Джон Кэссиди}
{900}{}{Грегори}
{910}{}{Гражданка}
{920}{}{Гражданин}
{930}{}{Богатая гражданка}
{940}{}{Богатый гражданин}
{950}{}{Траппер}
{960}{}{Траппер}
{970}{}{Сулик}
{980}{}{Майда Бакнер}
{990}{}{Торр}
{1000}{}{Лумпи}
{1010}{}{Светящийся призрак}
{1020}{}{Призрак реактора}
{1030}{}{Стражник реактора}
{1040}{}{Зомак}
{1050}{}{Скитер}
{1060}{}{Крысиный Мозг}
{1070}{}{Ленни}
{1080}{}{Вузи}
{1090}{}{Гарольд}
{1100}{}{Крот-гризли}
{1110}{}{Большой крот-гризли}
{1120}{}{Крысокабан}
{1130}{}{Свирепый крысокабан}
{1140}{}{Слабый брамин}
{1141}{}{Мутировавшая двухголовая корова.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Крыса-мутант}
{1161}{}{Мутировавшая от радиации крыса.}
{1170}{}{Мутировавший крот-гризли}
{1171}{}{Покрутевший и злой крот-гризли.}
{1180}{}{Мутировавший крысокабан}
{1181}{}{Сильно оголодавший от мутации монстр.}
{1190}{}{Супер Мутант}
{1200}{}{Накачанный мутант}
{1210}{}{Мельхиор}
{1220}{}{Нero Andro (don't use)}
{1230}{}{Нero Andro (don't use)}
{1240}{}{Нero Male (don't use)}
{1250}{}{Нero Female (don't use)}
{1260}{}{Нero Male (don't use)}
{1270}{}{Нero Female (don't use)}
{1280}{}{Нero Male (don't use)}
{1290}{}{Нero Female (don't use)}
{1300}{}{Нero Male (don't use)}
{1310}{}{Нero Female (don't use)}
{1320}{}{Нero Male (don't use)}
{1330}{}{Нero Female (don't use)}
{1340}{}{Гвардеец Города}
{1350}{}{Гвардеец Города}
{1360}{}{Кибердог}
{1370}{}{Стражник НКР}
{1380}{}{Стражник НКР}
{1390}{}{Полицейский НКР}
{1400}{}{Сторож рабов}
{1410}{}{Надсмотрщик}
{1420}{}{Великий торговец людьми}
{1430}{}{Великая торговка людьми}
{1440}{}{Танди}
{1450}{}{Мерк}
{1460}{}{Ратч}
{1470}{}{Скитер}
{1480}{}{Майки}
{1490}{}{Бармен НКР}
{1500}{}{Владелец магазина}
{1510}{}{Грунтар}
{1520}{}{Горис}
{1530}{}{Хищный крот-гризли}
{1540}{}{Хищный крот-гризли}
{1550}{}{Хищный крот-гризли}
{1560}{}{Хищный крот-гризли}
{1570}{}{Хищный крот-гризли}
{1580}{}{Хищный крот-гризли}
{1590}{}{Обычный призрак}
{1600}{}{Мирон}
{1610}{}{Маркус}
{1620}{}{Доктор Джонс}
{1630}{}{Дэвин}
{1640}{}{Мирия}
{1650}{}{Лэдди}
{1660}{}{Рондо}
{1670}{}{Подмастерье}
{1680}{}{Подмастерье}
{1690}{}{Подмастерье}
{1700}{}{Вышибала}
{1710}{}{Вышибала}
{1720}{}{Слабый мр. Хэнди}
{1730}{}{Обычный Светящийся}
{1740}{}{Дар}
{1750}{}{Далиа}
{1760}{}{Гордон}
{1770}{}{test (don't use)}
{1780}{}{Призрак реактора}
{1790}{}{Обычный призрак}
{1800}{}{Мэтт}
{1810}{}{Командир охотников}
{1820}{}{Охотник за бандитами}
{1830}{}{Командир охотников}
{1840}{}{Охотник за бандитами}
{1850}{}{Охотник за бандитами}
{1860}{}{Командир охотников}
{1870}{}{Охотник за бандитами}
{1880}{}{Охотник за бандитами}
{1890}{}{Командир охотников}
{1900}{}{Охотник за бандитами}
{1910}{}{Бесс}
{1911}{}{Двухголовая мутировавшая корова.}
{1920}{}{Балтас}
{1930}{}{Гришэм}
{1940}{}{Фил}
{1950}{}{Цыпленок}
{1960}{}{Карл}
{1970}{}{Джонни}
{1980}{}{Джо}
{1990}{}{Зеке}
{2000}{}{Мясник}
{2010}{}{Питти}
{2020}{}{Воин племени}
{2030}{}{Воительница племени}
{2040}{}{Каннибал}
{2050}{}{Людоедка}
{2060}{}{Святой муж}
{2070}{}{Святая женщина}
{2080}{}{Кочевник}
{2090}{}{Кочевник}
{2100}{}{Кочевница}
{2110}{}{Кочевница}
{2120}{}{Убийца}
{2130}{}{Убийца}
{2140}{}{Крестьянин}
{2150}{}{Крестьянка}
{2160}{}{Мантис}
{2170}{}{Рабовладелец}
{2180}{}{Рабовладелица}
{2190}{}{Дикий брамин}
{2200}{}{Переселенец}
{2210}{}{Переселенка}
{2220}{}{Патрульный Города}
{2230}{}{Патрульная Города}
{2240}{}{Сильный рабовладелец}
{2250}{}{Сильная рабовладелица}
{2260}{}{Чокнутый}
{2270}{}{Мародер}
{2280}{}{Чокнутый из Глоу}
{2290}{}{Мародер из Глоу}
{2300}{}{Рыбак}
{2310}{}{Рыбачка}
{2320}{}{Дикарь}
{2330}{}{Дикарка}
{2340}{}{Самогонщик}
{2350}{}{Самогонщица}
{2360}{}{Артельщик}
{2370}{}{Артельщица}
{2380}{}{Рейдер}
{2390}{}{Рейдерша}
{2400}{}{Огнедышащий ящер}
{2410}{}{Крутой огнедышащий ящер}
{2420}{}{Инопланетянин}
{2430}{}{Чужой}
{2440}{}{Мелкий сильный Коготь Смерти}
{2450}{}{Злобный Коготь Смерти}
{2460}{}{Летатель}
{2470}{}{Подлый Летатель}
{2480}{}{Псевдо-кентавр}
{2490}{}{Кентавр Апдайка}
{2500}{}{Патрульный АНКЛАВА}
{2510}{}{Патрульная АНКЛАВА}
{2520}{}{Саботажник}
{2530}{}{Саботажница}
{2540}{}{Наемник}
{2550}{}{Наемница}
{2560}{}{Найткин}
{2570}{}{Мощный Найткин}
{2580}{}{Крутой Призрак}
{2590}{}{Мафиози}
{2600}{}{Якудза}
{2610}{}{Рейнджер НКР}
{2620}{}{Рейнджер НКР}
{2630}{}{Мародер}
{2640}{}{Мародер}
{2650}{}{Симпатяга Ллойд}
{2660}{}{Зубастый грызун}
{2670}{}{Житель 13-го}
{2680}{}{Жительница 13-го}
{2690}{}{Хранитель Моста}
{2700}{}{Таинственный незнакомец}
{2710}{}{Таинственная незнакомка}
{2720}{}{Хэйксвилл}
{2730}{}{Большой Езус Мордино}
{2740}{}{Думар}
{2750}{}{Мать Когтей Смерти}
{2760}{}{Дракон}
{2770}{}{Ло Пан}
{2780}{}{Хабологист}
{2790}{}{Хабологистка}
{2800}{}{Неопознанная личность}
{2810}{}{Неопознанная личность}
{2820}{}{Неопознанная личность}
{2830}{}{Неопознанная личность}
{2840}{}{Неопознанная личность}
{2850}{}{Неопознанная личность}
{2860}{}{Неопознанная личность}
{2870}{}{Неопознанная личность}
{2880}{}{Суперагент Президента}
{2890}{}{Яйцо Когтя Смерти}
{2900}{}{Метцгер}
{2910}{}{Гвардеец АНКЛАВА}
{2920}{}{Гвардеец АНКЛАВА}
{2930}{}{Президент}
{2940}{}{Вице-президент}
{2950}{}{Техник}
{2960}{}{Бадгер}
{2970}{}{Доктор Фонг}
{2980}{}{Дитя}
{2990}{}{Дитя}
{3000}{}{Продавец оружия}
{3010}{}{Лаборант Ши}
{3020}{}{Страж Ши}
{3030}{}{Крестьянин Ши}
{3040}{}{Крестьянка Ши}
{3050}{}{Крестьянин Ло Пана}
{3060}{}{Крестьянка Ло Пана}
{3070}{}{Докер}
{3080}{}{Торговец Ши}
{3090}{}{Пинки}
{3100}{}{Крыса}
{3110}{}{Мантис}
{3120}{}{Муравей}
{3130}{}{Кротокрыс}
{3140}{}{Крот Гриззли}
{3150}{}{Кротокрыс мутант}
{3160}{}{Обычный геккон}
{3170}{}{Золотой геккон}
{3180}{}{Собака}
{3190}{}{Скорпион}
{3200}{}{Большой скорпион}
{3210}{}{Брамин}
{3220}{}{Хищное растение}
{3230}{}{Чужой}
{3240}{}{Маленький коготь смерти}
{3250}{}{Коготь смерти}
{3260}{}{Серый коготь смерти}
{3270}{}{Огнедышащий геккон}
{3280}{}{Псевдо-кентавр}
{3290}{}{Летатель}
{3300}{}{Болотник}
{3310}{}{крыса}
{3320}{}{крыса}
{3330}{}{крыса}
{3340}{}{крыса}
{3350}{}{Потрошитель}
{3360}{}{Потрошительница}
{3370}{}{Бандит}
{3380}{}{Бандитка}
{3390}{}{Мародер}
{3400}{}{Рейдер}
{3410}{}{Рейдерша}
{3420}{}{Работорговец}
{3430}{}{Мародер}
{3440}{}{Налетчик}
{3450}{}{Налетчица}
{3460}{}{Путник}
{3470}{}{Гуль}
{3480}{}{Гуль}
{3490}{}{Супермутант}
{3500}{}{Мальчик}
{3510}{}{Девочка}
{3520}{}{Житель}
{3530}{}{Житель}
{3540}{}{Житель}
{3550}{}{Житель}
{3560}{}{Житель}
{3570}{}{Житель}
{3580}{}{Житель}
{3590}{}{Панк}
{3600}{}{Мясник}
{3610}{}{Тип в балахоне}
{3620}{}{Бедняк}
{3630}{}{Вышибала}
{3640}{}{Житель}
{3650}{}{Женщина}
{3660}{}{Девушка}
{3670}{}{Проститутка}
{3680}{}{Женщина}
{3690}{}{Человек в костюме}
{3700}{}{Стражник}
{3710}{}{Стражница}
{3720}{}{Стражник}
{3730}{}{Стражница}
{3740}{}{Стражник}
{3750}{}{Вик - Стадия 3}
{3760}{}{Вик - Стадия 4}
{3770}{}{Вик - Стадия 5}
{3780}{}{Вик - Стадия 6}
{3790}{}{Робомозг - Шимпанзе}
{3800}{}{Робомозг - Ненормальный}
{3810}{}{Робомозг - Человек}
{3820}{}{Муравей}
{3830}{}{Крутой муравей}
{3840}{}{Пария}
{3850}{}{Зурак}
{3860}{}{Имбот}
{3870}{}{Джимми}
{3880}{}{Вейунгх}
{3890}{}{Херб}
{3900}{}{Лупал}
{3910}{}{Джобе}
{3920}{}{Смитти}
{3930}{}{Рубе}
{3940}{}{Мастер Кралл}
{3950}{}{Зигги}
{3960}{}{Мастер Кунг}
{3970}{}{Джон Бишоп}
{3980}{}{Анжела Бишоп}
{3990}{}{Миссис Бишоп}
{4000}{}{Телохранитель 1}
{4010}{}{Телохранитель 2}
{4020}{}{Громила Бишопа 1}
{4030}{}{Громила Бишопа 2}
{4040}{}{Сердитый брамин}
{4050}{}{Малый Езус}
{4060}{}{Большой Езус}
{4070}{}{Человек Мордино 1}
{4080}{}{Человек Мордино 2}
{4090}{}{Человек Мордино 3}
{4100}{}{Телохранитель Мирона 1}
{4110}{}{Телохранитель Мирона 2}
{4120}{}{Мистер Врайт}
{4130}{}{Миссис Врайт}
{4140}{}{Крис Врайт}
{4150}{}{Кейт Врайт}
{4160}{}{Сын Врайта 1}
{4170}{}{Сын Врайта 2}
{4180}{}{Дочь Врайта 1}
{4190}{}{Дочь Врайта 2}
{4200}{}{Мистер Сальваторе}
{4210}{}{Мэйсон}
{4220}{}{Вышибала Сальваторе 1}
{4230}{}{Вышибала Сальваторе 2}
{4240}{}{Обычный бармен 1}
{4250}{}{Обычный бармен 2}
{4260}{}{Обычный бармен 3}
{4270}{}{Боксер 1}
{4280}{}{Боксер 2}
{4290}{}{Боксер 3}
{4300}{}{Боксер 4}
{4310}{}{Майк Мастикатор}
{4320}{}{Холифелд}
{4330}{}{МакКнили}
{4340}{}{Малыш Стюарт}
{4350}{}{Братья с Корсики}
{4360}{}{Порноактрисы}
{4370}{}{Отец Тулли}
{4380}{}{Вышибала Казино 1}
{4390}{}{Вышибала Казино 2}
{4400}{}{Крупье}
{4410}{}{Сутенер/Наркоторговец1}
{4420}{}{Сутенер/Наркоторговец1}
{4430}{}{Сутенер/Наркоторговец1}
{4440}{}{Сутенер/Наркоторговец1}
{4450}{}{МакГи}
{4460}{}{Мисс Китти}
{4470}{}{Обычная Шлюха 1}
{4480}{}{Обычная Шлюха 2}
{4490}{}{Джимми Джей}
{4500}{}{Ренеско}
{4510}{}{Ученый}
{4520}{}{Элдридж}
{4530}{}{Алжернон}
{4540}{}{Джулс}
{4550}{}{Бюрократ 1}
{4560}{}{Бюрократ 2}
{4570}{}{Продавец 1}
{4580}{}{Продавец 2}
{4590}{}{Охранник 1}
{4600}{}{Охранник 2}
{4610}{}{Охранник 3}
{4620}{}{Охранник 4}
{4630}{}{Солдат 1}
{4640}{}{Солдат 2}
{4650}{}{Солдат 3}
{4660}{}{Солдат 4}
{4670}{}{Сержант Старк}
{4680}{}{Доктор Эндрью}
{4690}{}{Бармен}
{4700}{}{Орудийная башня}
{4701}{}{Автоматическое оборонительное устройство, снабженное двумя плазма-пушками.}
{4710}{}{К-9 (базовый)}
{4720}{}{К-9 (стадия 1)}
{4730}{}{К-9 (стадия 2)}
{4740}{}{К-9 (стадия 3)}
{4750}{}{К-9 (стадия 4)}
{4760}{}{Обычный Кибердог}
{4770}{}{Яйцо Ванаминго}
{4780}{}{Страж Ло Пана}
{4790}{}{Мэрджори}
{4800}{}{Авто-пушка}
{4810}{}{Особенный ящер}
{4820}{}{Смертушка}
{4830}{}{Фрэнк Хорриган}
{4831}{}{Суперагент и телохранитель президента}
{4840}{}{Хаболог}
{4850}{}{Хаболог}
{4860}{}{Паладин Братства}
{4870}{}{Гигантская оса}
{4880}{}{Жук-мутант}
{4890}{}{Мятежник}
{4900}{}{Опасный жук}
{4910}{}{Инженер}
{4920}{}{Пехотинец Анклава}
{4930}{}{Инженер}
{4940}{}{Солдат Братства}
{4950}{}{Диверсант}
{4960}{}{Солдат Анклава}
{4970}{}{Паладин Братства}
{4980}{}{Патрульный регулятор}
{4990}{}{Бандит}
{5000}{}{Разбойница}
{5010}{}{Рейдер}
{5020}{}{Рейдер}
{5030}{}{Рейдер}
{5040}{}{Рейдер}
{5050}{}{Ядовитый болотник}
{5060}{}{Болотник}
{5070}{}{Футбольный мяч}
{5080}{}{Человек в белом одеянии}
{5081}{}{Он спокоен и молчалив. Кажется, за все время, что вы здесь провели он ни разу не шевельнулся.}
{5090}{}{Яйцо смертекогта.}
{5100}{}{Яйцо чужого.}
{5110}{}{Яйцо огненного гекко.}
{5120}{}{Мутирующая дрянь.}
{5121}{}{Предположительно, так выглядят летатели и кентавры до "рождения".}
{5130}{}{Вожак кентавров.}
{5131}{}{Похоже, он сторожит "выводок".}
{5140}{}{Вожак огненных ящеров.}
{5150}{}{Матка смертекогтов.}
{5180}{}{Хелацитон тип 1}
{5181}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5190}{}{Злобный хелацитон тип 1}
{5191}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5200}{}{Хелацитон тип 2}
{5201}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5210}{}{Злобный хелацитон тип 2}
{5211}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5220}{}{Хелацитон тип 3}
{5221}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5230}{}{Генриетта}
{5231}{}{Кожа этого существа напоминает одну большую мозоль.}
{5240}{}{Здоровый гуль}
{5250}{}{Здоровый гуль}
{5260}{}{Боец}
{5270}{}{Боец}
{5280}{}{Боец}
{5290}{}{Боец}
{5300}{}{Боец}
{5310}{}{Боец}
{5320}{}{Боец}
{5330}{}{Боец}
{5340}{}{Здоровый ящер}
{5350}{}{Протектрон}
{5360}{}{Музыкальный автомат}
{5370}{}{Химера}
{5380}{}{Йелли}
{5390}{}{Линн}
{5400}{}{Боец красных}
{5410}{}{Боец красных}
{5420}{}{Мутант}
{5421}{}{Крупная мутировавшая особь.}
{5430}{}{Здоровый мутант}
{5431}{}{Крупная мутировавшая особь.}
{5440}{}{Огромный мутант}
{5441}{}{Крупная мутировавшая особь с развитой мускулатурой.}
{5450}{}{Брамин}
{5451}{}{Обычный брамин}
{5460}{}{Житель}
{5470}{}{Житель}

#-------------------------------------------------------------------
#TLJ - GM spawns
#-------------------------------------------------------------------

#RATS
{6000}{}{Детеныш крысы}
{6001}{}{Довольно мелкая тварь.}

#-------------------------------------------------------------------
#FORP - Critters
#-------------------------------------------------------------------
#RIVERDALE NPC
{8000}{}{Снайпер Саула}
{8001}{}{Хладнокровный боец дальнего боя. Первым делом вы познакомитесь с её пулей, нежели с ней. На лбу метка работорговца.}
{8010}{}{Наёмник Моргана}
{8011}{}{Профессиональный боец Моргана. Очевидно, обилие его шрамов и отметин на оружии - не от спокойной жизни.}
{8020}{}{Наёмница Моргана}
{8021}{}{Опытная наёмница, посвятившая свою жизнь работе на "случайный кошелёк", а после - на Моргана.}
{8030}{}{Стальной Ромул}
{8031}{}{Высокий, сильный мужчина с седоватыми длинными волосами. Вместо левой руки, от локтя идёт металлический протез.}
{8040}{}{Жирный Морган}
{8041}{}{Очень толстый мужчина в официальной одежде, но что странно - гавайской рубашке под жилетом. По его виду легко понять, что ценит он в людях лишь личную выгоду.}
{8050}{}{Саул}
{8051}{}{Накачанный, большой негр в металлической броне. Его холодный взгляд подсказывает, что он здесь главный. На лбу видна большая метка работорговцев.}
{8100}{}{Лита}
{8101}{}{Крайне накаченная девушка с ярким кислотным ирокезом. На её броне видно множество зарубок, а на щеке имеются старые шрамы.}
{8110}{}{Никки}
{8111}{}{Небрежная прическа в фиолетовых тонах, множество татуировок по всему телу, а так же вычищенная броня до блеска. Девушка выглядит крайне расслабленно.}
{8120}{}{Псарь Дюк}
{8121}{}{Взрослый мужик в плотной куртке с потрепанными рукавами. На брови виднеется шрам, а от одежды пахнет собаками.}
{8130}{}{Мишлен}
{8131}{}{Девушка среднего роста с аккуратными руками. Одежда слегка приоткрыта, а на лице держится хитрая улыбка.}
{8140}{}{Дайрон}
{8141}{}{Крепкий мужчина в зеркальной металлической броне. Миниган на его спине не предвещает ничего добродушного.}
{8150}{}{Найра}
{8151}{}{Острый взгляд, хищный оскал и крепкое телосложение. Девушка явно повидала многое и уверенно повидает столько же.}
{8160}{}{Себастиан}
{8161}{}{Деловой мужчина в огнеупорной броне. На лице задумчивая мина, изредка сменяющаяся на нейтральную.}
{8170}{}{Реджи}
{8171}{}{Спокойный мужчина азиатской наружности. На куртке видны какие-то зарубки.}
{8180}{}{Жан}
{8181}{}{Мужчина в деловом костюмы и с густыми длинными усами. Выглядит напыщенно. От него веет странным ощущением чего-то инородного.}
{8190}{}{Освальд}
{8191}{}{Крепкий мужчина с множеством мешочков и сумок на его плечах и ногах. Кажется, он кого-то ждёт.}
{8200}{}{Шерри}
{8201}{}{Взрослая девушка с короткой прической и несколькими шрамами на губе. Её камуфляжная броня выглядит запачканной.}

#SANDBOX NPC
{9500}{}{Дюбридж Ли Эрвин}
{9501}{}{Старая, залатанная во всех возможных местах и укрепленная кусками сырой браминей кожи, роба опоясывает такого же истертого временем пожилого человека.}
{9510}{}{Маркус Голдман}
{9511}{}{Бронзовый загар и литые мышцы говорят о том, что этот невысокий мужичок даст фору самым удалым армреслерам из Брокен-Хиллс.}
{9520}{}{Стивен Барр}
{9521}{}{Постоянно жует какой-то сорт жевательного табака, сплевывая попадающиеся комки в сторону, после чего, как ни в чем не бывало, продолжает улыбаться, обнажая слегка пожелтевшие, но ровные зубы.}
{9530}{}{Сэт Сэйл}
{9531}{}{Определенно мастер своего дела, тщательно подобранная экипировка которого сразу же выдает в нем его род занятий - мощная кожаная праща на поясе, заточенное копье за спиной и милая накидка на плечах из дубленой кожи огнедышащего геккона.}
{9540}{}{Эндрю Мэллон}
{9541}{}{Одет в лохмотья караванщика с кучей нацепленных на них армейский разгрузок. Пахнет керосином.}
{9550}{}{Раймонд Тайер}
{9551}{}{На поясе у этого древнего гуля затянут ремень с кучей подручных инструментов. Также как заядлый курильщик всегда держит в зубах сигарету, он сжимает в руке старый, потертый мультитул.}
{9560}{}{Карл Ругер}
{9561}{}{Если бы техническое масло было парфюмом, этот далеко не гладкокожий парень был бы законодателем моды. Опоясан старым кузнечным фартуком.}
{9570}{}{Сэмуэль Сакс}
{9571}{}{Удивительное отличие этого гуля от всех других - сохранившиеся клочки седых волос на скупо обтянутой кожей голове.}
{9580}{}{Вексельберг}
{9581}{}{Гуль, выдающейся чертой которого являются крупные кузнечные перчатки, которые очень смешно смотрятся на его тщедушных, но очень жилистых ручонках.}
{9590}{}{Честер}
{9591}{}{Чудовище столь огромных размеров, что рядом с ним небо кажется мелким и незначительным элементом пейзажа.}
{9600}{}{Дэвид «Лапша» Ааронсон}
{9601}{}{Высокого роста гуль с накинутым на грудь легким брнежилетом. Постоянно осматривается по сторонам, медленно проводя по окрестностям своим дымным взглядом}
{9610}{}{Максимилиан «Макс» Беркович}
{9611}{}{Гуль, у которого всё ещё сохранился нос, придающий ему более менее человеческий облик. Одет в грязный комбинезон, подвязанный ремнем с нацепленной на него различной боевой снарягой.}
{9620}{}{Патрик «Простак» Голдберг}
{9621}{}{Пузатый гуль, носящий соломенную шляпу. Жует что-то, размеренно и раздражающе почавкивая.}
{9630}{}{Филипп «Косой» Штейн}
{9631}{}{Отличительная особенность этого гуля в сильной разнице уровня глаз. Левый глаз совсе замутнен, а правый же, наоборот, сохранил человеческое выражение и глубину мысли.}
{9640}{}{Малыш Доминик}
{9641}{}{Миниатюрный паренек. Его можно было бы назвать славным малым, если бы не тот факт, что это мерзкий, отвратительный и крайне вонючий гуль.}
{9650}{}{Элис}
{9651}{}{Очень крутая, но выглядящая миролюбиво, охотница.}
{9660}{}{Чейз, лидер шахтеров}
{9661}{}{Коренастый парень в довольно чистой одежде. По его рукам видно, что ему приходилось работать на шахте старателем.}
{9670}{}{Линкольн, караванщик}
{9671}{}{Пыльный плащ, драные сапоги, разношенная кобура... сразу видно - бывалый путешественник.}
{9680}{}{Сара, кладовщик шахтеров}
{9681}{}{Девушка лет тридцати, приятной наружности. По её загарелой коже нельзя сказать, что она много времени провела в шахтах.}
{9690}{}{Страйк}
{9691}{}{Парень с самодовольным видом и зубочисткой во рту. Он так занят своими колодами карт, что ничего вокруг не замечает.}
{9700}{}{Лана}
{9701}{}{Молодая девушка весьма привлекательного вида с аппетитными формами и игривым взглядом.}
{9710}{}{Роджер, торговец}
{9711}{}{Парень средних лет, одет в пыльную куртку с заплатками. Выглядит как типичный торгаш.}
{9720}{}{Мей, представитель "Красного Рассвета"}
{9721}{}{Девушка в кожаной броне со значком организации "Красный Рассвет".}
{9730}{}{Джессика Роуман}
{9731}{}{Девушка с веснушками и ровной челкой. Очки на её лице добавляют ей важности, что нельзя сказать о её потрепанном костюме}

#RIVERDALE NPC
{9740}{}{Сьюзи}
{9741}{}{Молодая девушка со светлыми волосами, очень красивая}
{9750}{}{Терминал}
{9751}{}{Машина по выдаче талонов.}
{9760}{}{Сэт}
{9761}{}{Сурового вида траппер. Один глаз закрыт повязкой. Кажется вы его уже видели где-то, или нет...}
{9770}{}{Варг}
{9771}{}{Огромный лохматый пес, он величественнен и спокоен.}
{9780}{}{Гери}
{9781}{}{Поджарый рыжий волчара, лучше не поворачиваться к нему спиной.}
{9790}{}{Фреки}
{9791}{}{Это судя по всему сука, однако зубы у нее не уступают любому кобелю.}
{9800}{}{Рей Свонсон}
{9801}{}{К кому вы пойдете когда вам будет так плохо что хоть помирай? Правильно, к доктору. Это он.}
{9810}{}{Фрэд Бобкэт}
{9811}{}{С виду обыкновенный житель трущоб, правда глаза у него какие-то "затуманенные".}
{9820}{}{Эйб Цукерман}
{9821}{}{Пожилой мужчина, сухого телосложения.}
{9830}{}{Крупье казино}
{9831}{}{Очень красивая и сексуальная девушка. На шее красивое ожерелье, а на ногах милые балетки.}
{9840}{}{Охранник казино}
{9841}{}{Рослый парень с протокольной рожей, он внимательно следит за вами. Когда вы подходите ближе, он улыбается вам, разумеется из вежливости.}
{9850}{}{Заядлый торчок}
{9851}{}{Горбатый наркоман, явно смотрящий на вас с немым вопросом.}
{9860}{}{Проститутка}
{9861}{}{Потасканная женщина, которую явно проведали многие.}
{9870}{}{Ганди}
{9871}{}{Крепкий наёмник с небольшой улыбкой на лице. Он выглядит молодо.}
{9880}{}{Трэвор}
{9881}{}{Высокий и молодой парень, строго осматривающийся вокруг.}
{9890}{}{Селестия}
{9891}{}{Молодая девушка со шрамом на шее. Через всю грудь проходит патронташ, заполненный патронами.}
{9900}{}{Забавный толстяк}
{9901}{}{Странный мужичок, медленно поглаживающий своё выпирающее пузо.}
{9910}{}{Базил}
{9911}{}{Крупный мужчина в бронежилете, вечно что-то записывающий в свою тетрадь.}
{9920}{}{Льюис}
{9921}{}{Деловой парень в металлической броне. Кажется, он кого-то ждёт.}
{9930}{}{Гарфилд}
{9931}{}{Высокий, лысый мужик. Он смотрит на вас с неким нетерпением.}
{9940}{}{Салли}
{9941}{}{Молодая, ухоженная девушка. Она явно кого-то ожидает и мягко улыбается.}
{9950}{}{Отморозок Ромула}
{9951}{}{Отбитый боец Ромула, готовый ввязаться в драку, даже если это было не нужно.}
{9960}{}{Бандит Ромула}
{9961}{}{Опасный "цепной пёс" синдиката, готовый выполнить любую грязную работу.}
{9970}{}{Головорез Ромула}
{9971}{}{Кровожадный убийца, каким-то чудом находящийся на службе у Ромула.}
{9980}{}{Стрелок Саула}
{9981}{}{Умелый боец-работорговец в бронежилете. Его строгий взгляд подсказывает, что с пустыми разговорами к нему лучше не подходить. На лбу метка работорговца.}
{9990}{}{Надсмотрщик Саула}
{9991}{}{Наблюдатель за рабами с множеством старых шрамов и тяжелым взглядом. На лбу метка работорговца.}

#RATS
{10000}{}{Детеныш крысы}
{10001}{}{Довольно мелкая тварь.}
{10010}{}{Мелкая крыса}
{10011}{}{Непропорционально большие клыки и красные глаза.}
{10020}{}{Средняя крыса}
{10021}{}{С её клыков обильно течёт слюна.}
{10030}{}{Облученная крыса}
{10031}{}{Она светится и на ней почти нет шерсти.}
{10040}{}{Огромный крыс}
{10041}{}{Этот злобный грызун может легко допрыгнуть до вашего лица.}
{10050}{}{Крыса-мутант}
{10051}{}{Матерая злая тварь размером с небольшую собаку.}

#MANTIS
{10300}{}{Жалкий мантис} 
{10301}{}{Мелкое и противное насекомое с длинными лапками.} 
{10310}{}{Мантис} 
{10311}{}{Среднее тельце с длинными лапками, способными заколоть вас досмерти. } 
{10320}{}{Огромный мантис} 
{10321}{}{Огромное насекомое с не менее внушительными клешнями и массивным тельцем. Голова хаотично ходит в разные стороны.}
{10330}{}{Мантис вожак}
{10331}{}{Громадный и исключительный представитель мантисов. Внушительные крылья и вечно агрессивно клацающие клешни.}

#ANTS
{10600}{}{Муравей-рабочий}
{10601}{}{Небольшое существо, вечно виляющее на ходу.} 
{10610}{}{Муравей-солдат} 
{10611}{}{Крупное существо, среднего размера лапы и длинные усики. Внушительные жвалы плавно двигаются.} 
{10620}{}{Муравей-трутень} 
{10621}{}{Этот здоровенный муравей выглядит особенно мерзко и габаритно. Тело непропорционально большое, отчего он выглядит неприятно.} 
{10630}{}{Муравей-охранник} 
{10631}{}{Это Альфа-самец: его панцирь выглядит очень толстым, а пасть огромной. Мощные лапы, длинные жвалы и огромные глазища.}

#SPOREPLANTS
{10900}{}{Хищное растение} 
{10901}{}{Странная, безглазая пасть держится на толстом стебле.} 
{10910}{}{Огромное хищное растение} 
{10911}{}{Громадная безглазая пасть с многочисленными отростками по сторонам. Стебель покрыт шипами, а само растение крайне высокое.} 

#BRAHMINS
{11200}{}{Слабый брамин} 
{11201}{}{Небольшой и слабенький брамин. Выглядит тощим и изголодавшимся.} 
{11210}{}{Брамин} 
{11211}{}{Две головы, четыре копыта и одно большое брюхо. У одной из голов имеются рога.}
{11220}{}{Большой Брамин} 
{11221}{}{Крупный брамин с массивными головами и телом.}
{11230}{}{Дикий брамин} 
{11231}{}{Худой и потрепанный брамин. Тело брамина истрёпано дикой природой.} 
{11240}{}{Яростный брамин} 
{11241}{}{Крупный брамин с тёмным окрасом. Рога длиннее, чем у обычного брамина, а копыта выглядят массивнее.}

#DOGS
{11500}{}{Слабая собака} 
{11501}{}{Тощее животное, по телу видны рёбра и следы долгого голодания. Шерсть поредела.} 
{11510}{}{Собака} 
{11511}{}{Обычная дворняга средних размеров.} 
{11520}{}{Матёрая собака} 
{11521}{}{Множество старых шрамов и ранений, дают понять, что этот пёс через многое прошёл.} 
{11530}{}{Большая собака} 
{11531}{}{Крупная собака с грубой и диковатой мордой. С клыков стекают слюни, а на лапах видна грязь.}
{11540}{}{Щенок} 
{11541}{}{Маленькое создание с мелкими лапками, длинной мордочкой и короткой шерсткой.}

#WOLFES
{11800}{}{Слабый волк} 
{11801}{}{Небольшое существо, чем-то напоминающее собаку. Редкая шерсть, небольшие клыки и когти на лапах. Выглядит истощенным.} 
{11810}{}{Волк} 
{11811}{}{Среднего размера существо. Хорошая шкура, крепкое телосложение, длинная и вытянутая морда с острыми зубами в пасти.} 
{11820}{}{Матёрый волк} 
{11821}{}{Потрёпанный жизнью волк. На шкуре видны множественные шрамы, на лапах запекшаяся кровь.} 
{11830}{}{Вожак стаи волков} 
{11831}{}{Огромный и старый волк. Крупное телосложение и крайне длинные когти и зубы дают понять, что он прожил многое. По шкуре волка наблюдается обилие старых шрамов и относительно свежих ран.} 
{11840}{}{Щенок} 
{11841}{}{Маленькое создание с мелкими лапками, длинной мордочкой и серой шерсткой. Наличие острых клыков выдает в нём щенка волка.}


#PIGRATS
{12100}{}{Свинокрыс} 
{12101}{}{Он издаёт звуки, напоминающие писк и хрюканье в одном. Маленькая противная тушка на когтистых лапках.} 
{12110}{}{Огромный свинокрыс} 
{12111}{}{Громадная мясистая туша на мускулистых лапищах с когтями и острыми зубищами в пасти.} 
{12120}{}{Свинокрыс альфа-особь} 
{12121}{}{Невероятно большой и мускулистый свинокрыс. По его телу видно обилие неприятных шрамов и старых ранений.} 

#MOLERATS
{12400}{}{Кротокрыс} 
{12401}{}{Небольшое животное на четырех лапах с когтями и острыми зубами. На морде и хвосте видны длинные усики.} 
{12410}{}{Огромный кротокрыс} 
{12411}{}{Огромный и крайне мясистый зверь. Вся кожа в складках тёмно-розового цвета.} 
{12420}{}{Кротокрыс-вожак} 
{12421}{}{Громадный кротокрыс с особенно длинными когтями. Зубы крайне острые и большие, а на теле видны многочисленные шрамы.} 

#SILVER GECKOS
{12700}{}{Серебряный гекко} 
{12701}{}{Небольшой серебристый геккон. Маленькие лапки на относительно большом тельце.} 
{12710}{}{Серебряный хищный гекко} 
{12711}{}{Жилистый геккон с длинным хвостом. В пасти видны частые и очень острые зубы.} 
{12720}{}{Крупный серебряный гекко} 
{12721}{}{Очень большой геккон, по сравнению с его собратьями. Длинные лапы с опасными когтями, переливающаяся шкурка.} 
{12730}{}{Серебряный гекко альфа-особь} 
{12731}{}{Самый большой серебряный геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются мелкие шипы.} 

#GOLDEN GECKOS
{13000}{}{Золотой гекко} 
{13001}{}{Маленький и юркий золотой гекко. Мелкий хвостик вечно двигается в такт походке.} 
{13010}{}{Крупный золотой гекко} 
{13011}{}{Большое существо с длинным хвостом и острыми зубами. Его золотая шкурка красиво переливается на солнце.} 
{13020}{}{Золотой гекко альфа-особь} 
{13021}{}{Самый большой золотой геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются частые рубцы и шрамы.} 

#FIREGECKOS
{13300}{}{Огненный гекко} 
{13301}{}{Небольшой, но крайне красочный зверь. Из ноздрей твари исходит легкий дымок.} 
{13310}{}{Огненный гекко альфа-особь} 
{13311}{}{Крайне крупный огненный гекко с внушительным телосложением и целым "фонтаном" дыма, выходящим из его ноздрей. Пасть вечно открывается, выпуская на волю струйки огня.} 

#SMALLSCROPS
{13600}{}{Мелкий радскорпион} 
{13601}{}{Маленький скорпион с не сильно внушительными клешнями и мелким хвостом.} 

#BIGSCORPS
{13900}{}{Радскорпион} 
{13901}{}{Среднего размера скорпион. С его хвоста и жала стекает яд. Массивные клешни и быстрые лапки.} 
{13910}{}{Матёрый радскорпион} 
{13911}{}{Крупный скорпион с большим и набухшим жалом. Крепкий и массивный панцирь.} 

#BLACKSCORPS
{14200}{}{Мелкий чёрный радскорпион} 
{14201}{}{Малый скорпион с длинным хвостом и чёрным панцирем.} 
{14210}{}{Чёрный радскорпион} 
{14211}{}{Крупный чёрный скорпион с толстым панцирем и массивным свисающим хвостом. Жало твори сочится ядом.} 

#DEATHCLAWS
{14500}{}{Детёныш Когтя смерти} 
{14501}{}{Маленькое гуманоидное существо с длиннющими лапами, из которых виднеются острые когти.} 
{14510}{}{Молодой Коготь смерти} 
{14511}{}{Среднего размера существо со светлой шерстью и небольшими рожками.} 
{14520}{}{Крупный Коготь смерти} 
{14521}{}{Большая и мускулистая страшная тварь. Длинные и крайне острые когти на лапах. Жёлтые и изогнутые клыки.} 
{14530}{}{Коготь смерти альфа-особь} 
{14531}{}{Громадный коготь-смерти с длинными изогнутыми рогами и обилием шрамов на всему телу. Потемневший окрас и громоздкие лапы.} 
{14540}{}{Коготь смерти охотник} 
{14541}{}{Огромный коготь-смерти серого окраса. Изогнутое тело, могучие лапы и изогнутые рога, нацеленные вперёд.} 

#SWAMPLURKERS
{14800}{}{Слабый болотник} 
{14801}{}{Небольшое существо в толстом панцире и массивными клешнями.} 
{14810}{}{Болотник} 
{14811}{}{Вонючая, большая и громоздкая тварь, покрытая цельным крепким панцирем. Острые клешни выглядят крайне опасно и остро.} 
{14820}{}{Вожак болотников} 
{14821}{}{Невероятно массивный и крепкий, исключительный болотник. Его громадный панцирь покрыт болотными отходами и обилием водорослей.} 

#ALIENS
{15100}{}{Странное яйцо} 
{15101}{}{Странное, округлое яйцо неизвестного происхождения.} 
{15110}{}{Ванаминго} 
{15111}{}{У этой твари нет ни глаз, ни пальцев. Из тела выходят мерзкие длинные безкостные щупальца.} 
{15120}{}{Крупный ванаминго} 
{15121}{}{Большая и страшная безглазая тварь с длинными мерзкими щупальцами.} 

#MOTERALIENS
{15400}{}{Матка ванаминго} 
{15401}{}{Матка ванаминго. С пасти здоровенного ванаминго течёт слизь, а блестящая шкура имеет тёмно-серый оттенок.} 

#FLOATERS
{15700}{}{Мелкий летатель} 
{15701}{}{Маленькое змееподобное нечто, медленно ползущее на хвосте. Вместо лица у существа есть подобие большого рта.} 
{15710}{}{Летатель} 
{15711}{}{Безобразная тварь с огромным, полным зубов горизонтальным ртом.} 
{15720}{}{Гадкий летатель} 
{15721}{}{Он мерзко воняет, а его передние рты обильно истекают слизью.} 
{15730}{}{Вожак летателей} 
{15731}{}{Огромный летатель с несколькими громадными ртами, полными обилием острых зубов в едкой слизи. Существо очень сильно воняет.} 

#CENTAURS
{16000}{}{Мелкий кентавр} 
{16001}{}{Небольшое, но крайне мерзкое создание. Передвигается на шести человеческих руках. На длинных шеях красуются разные обезображенные головы.} 
{16010}{}{Кентавр.} 
{16011}{}{С длинного щупальцеобразного языка течёт мутная слизь. Две обезображенные головы и нечто, похожее на кишки, свисающие из тела и волочащиеся следом.} 
{16020}{}{Гадкий кентавр} 
{16021}{}{Крайне неприятное зрелище. Существо с разными головами, обилием органов, находящихся снаружи. По телу течёт вязкая слизь.} 
{16030}{}{Альфа кентавр} 
{16031}{}{Громадный кентавр держится на десяти человеческих руках. Три уродливые головы и не менее обезображенное подобие тела.}

#PRIMITIVES
{16300}{}{Тощий дикарь} 
{16301}{}{Тощий дикарь. Этот дикарь похоже очень давно не ел.} 
{16310}{}{Тощая дикарка} 
{16311}{}{Тощая дикарка. Она похожа на обтянутый кожей скелет. Ну или на свеженького гуля.}
{16320}{}{Грязый дикарь} 
{16321}{}{Грязый дикарь. Этот похоже целыми днями копается в земле.}
{16330}{}{Перемазанная дикарка} 
{16331}{}{Перемазанная дикарка. Возможно глина на ее лице и волосах - это украшение.}
{16340}{}{Старейшина племени} 
{16341}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16350}{}{Старейшина племени} 
{16351}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16360}{}{Шаман племени} 
{16361}{}{Шаман племени. Множество амулетов и опьяненный вид намекаютвам, что перед вами сильный колдун.}
{16370}{}{Дикарь охотник} 
{16371}{}{Дикарь охотник. Вы когда нибудь видели траппера без штанов? Вот он.}
{16380}{}{Дикарка охотница} 
{16381}{}{Дикарка охотница. Она не так доступна как кажется.}
{16390}{}{Дикарь воин} 
{16391}{}{Дикарь воин. Сильный и ловкий, он будет защищать свое племя до последнего вздоха.}
{16400}{}{Дикарка воительница} 
{16401}{}{Дикарка воительница. Боевая раскраска, дикий оскал и голые сиськи, все как положено.}

#CANNIBALS & RIPPERS
{16600}{}{Мерзкий людоед} 
{16601}{}{Мерзкий людоед. Он смотрит на вас со злобой и голодом. Быстро шагает в Вашу сторону, громко принюхиваясь и пуская слюну.}
{16610}{}{Грязная людоедка} 
{16611}{}{Грязная людоедка. Она смотрит на вас голодным взглядом. Её волосы взъерошены, некоторые зубы отсутствуют.}
{16620}{}{Бородатый людоед} 
{16621}{}{Бородатый людоед. Он жадно смотрит на вас. Этот пидор собирается вас сожрать!}
{16630}{}{Сумасшедший людоед} 
{16631}{}{Сумасшедший людоед. Его взгляд бегает по округе. Он клацает зубами, топчась на земле.}
{16640}{}{Фермер-людоед} 
{16641}{}{Фермер-людоед. Он смотрит на вас голодными глазами. Его комбинезон заляпан кровью, а соломенная шляпа кем-то надкусана.}
{16650}{}{Голодный людоед} 
{16651}{}{Голодный людоед. Он смотрит на вас голодными глазами. С его рта течёт слюна, а рёбра заметно проступают под кожей.}
{16660}{}{Рабыня-людоедка} 
{16661}{}{Рабыня-людоедка. Она смотрит на вас голодным взглядом. На её шее висит сломанный ошейник.}
{16670}{}{Лысый каннибал} 
{16671}{}{Лысый каннибал. Он злобно смотрит на вас. От его красной макушки исходит пар, видимо, там он кусочек Вашей ноги и зажарит.}
{16680}{}{Фермерша-людоедка} 
{16681}{}{Фермерша-людоедка. Она смотрит на вас голодным взглядом. На её фартуке кровью написано МЯСО.}
{16690}{}{Странный парень} 
{16691}{}{Странный парень. Его лицо скрыто капюшоном. Рваная роба имеет участки с засохшей кровью.}
{16700}{}{Китаец-каннибал} 
{16701}{}{Китаец-каннибал. Он смотрит вас, как на свежую рыбу. К жилетке и штанам прикреплены ножи разных размеров.}
{16710}{}{Странный нигер} 
{16711}{}{Странный нигер. Он негромко хрипит. С его рта стекает кровь, а зрачки почему-то закатились вверх.}
{16720}{}{Здоровый каннибал} 
{16721}{}{Здоровый каннибал. Он смотрит на вас, пуская кровавые слюни. Похоже, он даже рычит.}
{16730}{}{Бледный каннибал} 
{16731}{}{Бледный каннибал. Он смотрит на вас голодными глазами. Его кожа почти что белая, очень странно для обитателя Пустоши.}
{16740}{}{Мутированный каннибал} 
{16741}{}{Мутированный каннибал. Он смотрит на вас голодным взглядом. Половина его головы гниёт заживо, другая половина полна гнойных наростов.}
{16750}{}{Мелкий каннибал} 
{16751}{}{Мелкий каннибал. Он смотрит на вас голодными глазами. Этот мелкий пидор, по всей видимости, питается человечиной.}
{16760}{}{Симпатичная людоедка} 
{16761}{}{Симпатичная людоедка. Она смотрит на вас голодным взглядом. Одежда на ней уже полностью изношена, из-за чего хорошо видна её большая грудь.}
{16770}{}{Жирная людоедка} 
{16771}{}{Жирная людоедка. Она смотрит на вас со зловещей улыбкой. Её одежда сшита из разных шкур, а на них нарисованы загадочные символы из крови.}
{16780}{}{Престарелый каннибал} 
{16781}{}{Престарелый каннибал. Он смотрит на вас хладнокровно. Седовласый старик жуёт собственные губы.}
{16790}{}{Ловчий потрошителей} 
{16791}{}{Ловчий потрошителей. Похоже, что вы нужны ему живым.} 
{16800}{}{Ловчая потрошителей} 
{16801}{}{Ловчая потрошителей. Ловкая и быстрая. Похоже, что она не прочь с вами "позабавиться".}
{16810}{}{Потрошитель-забойщик} 
{16811}{}{Потрошитель-забойщик. Крепко сложен. Его рот искривлен в плотоядной ухмылке.}
{16820}{}{Потрошитель-забойщик} 
{16821}{}{Потрошитель-забойщик. Сильная женщина. Ее лицо испачкано кровью. Судя по всему это не ее кровь.}
{16830}{}{Потрошитель-свежеватель} 
{16831}{}{Потрошитель-свежеватель. Агрессивно настроенный представитель племени потрошителей.}
{16840}{}{Потрошитель-свежеватель} 
{16841}{}{Потрошитель-свежеватель. Полуобнаженная женщина. Хищно смотрит на вас.}
{16850}{}{Потрошитель-воин} 
{16851}{}{Потрошитель-воин. Его торс увешен украшениями из костей поверженных врагов.}
{16860}{}{Воительница потрошителей} 
{16861}{}{Воительница потрошителей. Ее взгляд затуманен жаждой крови.}
{16870}{}{Потрошитель жрец } 
{16871}{}{Потрошитель жрец. Его шею украшает ожерелье из фаланг человеческих пальцев.}
{16880}{}{Патриарх потрошителей} 
{16881}{}{Патриарх потрошителей. Высокий и властный мужчина. Его лицо украшают ритуальные шрамы. Остальные потрошители смотрят на него как на живого бога.}
{16890}{}{Матриарх потрошителей} 
{16891}{}{Матриарх потрошителей. Крепко сложенная женщина в одежде из человеческой кожи. Другие потрошители почтительно опускают глаза в ее присутствии.}

#GANGS
{16900}{}{Торчок} 
{16901}{}{Торчок. Наркоман, его руки дрожат, а глаза бегают.} 
{16910}{}{Наркоманка} 
{16911}{}{Наркоманка. Судя по ее отсутствующему взгляду - она уже давным давно готова на что угодно ради дозы.}
{16920}{}{Отребье} 
{16921}{}{Отребье. Оборванец, который пытается жить за чужой счет.}
{16930}{}{Шмара} 
{16931}{}{Шмара. Отсутствие принципов - вот ее главный принцип!}
{16940}{}{Мелкая шпана} 
{16941}{}{Мелкая шпана. Он не постесняется лишить вас кошелька, а за одно и жизни.}
{16950}{}{Мелкая шпана} 
{16951}{}{Мелкая шпана. Она уже давно привыкла играть по правилам пустоши.}
{16960}{}{Плут} 
{16961}{}{Плут. Мелкий воришка.}
{16970}{}{Плутовка} 
{16971}{}{Плутовка. Остра на язык. И на заточку тоже остра!} 
{16980}{}{Подонок} 
{16981}{}{Подонок. Готов выпустить вам кишки за пару крышек.}
{16990}{}{Грабительница} 
{16991}{}{Грабительница. Беспринципная и очень опасная.}
{17000}{}{Отморозок} 
{17001}{}{Отморозок. Судя по всему этот психопат собирается пролить вашу кровь!}
{17010}{}{Отбитый} 
{17011}{}{Отбитый. Для него перерезать глотку ребенку как два пальца обоссать.}
{17020}{}{Авторитет} 
{17021}{}{Авторитет. Местный авторитет. Смотрит на вас как на говно.}
{17030}{}{Авторитет} 
{17031}{}{Авторитет. Местный авторитет. Смотрит на вас как на говно.}

#RAIDERS
{17200}{}{Рейдер мусорщик} 
{17201}{}{Рейдер мусорщик. Вы бы спутали с бродягой, если бы не направленное на вас оружие.}
{17210}{}{Рейдер мусорщик} 
{17211}{}{Рейдер мусорщик. Вы бы спутали с бродягой, если бы не направленное на вас оружие.} 
{17220}{}{Рейдер псих} 
{17221}{}{Рейдер псих. Отмороженная наглухо личность.}
{17230}{}{Рейдер псих} 
{17231}{}{Рейдер псих. Отмороженная наглухо личность.}
{17240}{}{Рейдер камикадзе} 
{17241}{}{Рейдер камикадзе. Он прямо просит что бы вы его пристрелили.}
{17250}{}{Рейдер камикадзе} 
{17251}{}{Рейдер камикадзе. Он прямо просит что бы вы его пристрелили.}
{17260}{}{Рейдер громила} 
{17261}{}{Рейдер громила. Не попадайтесь под его удары.}
{17270}{}{Рейдер громила} 
{17271}{}{Рейдер громила. Не попадайтесь под его удары.}
{17280}{}{Рейдер налетчик} 
{17281}{}{Рейдер налетчик. Рейдер или налетчик? Да какая разница!}
{17290}{}{Рейдер налетчик} 
{17291}{}{Рейдер налетчик. Рейдер или налетчик? Да какая разница!}
{17300}{}{Рейдер стрелок} 
{17301}{}{Рейдер стрелок. Вы на мушке.}
{17310}{}{Рейдер стрелок} 
{17311}{}{Рейдер стрелок. Вы на мушке.}
{17320}{}{Рейдер безумец} 
{17321}{}{Рейдер безумец. Этот рвется в бой в первых рядах. Выглядит очень опасным.}
{17330}{}{Рейдер безумец}
{17331}{}{Рейдер безумец. Этот рвется в бой в первых рядах. Выглядит очень опасным.}
{17340}{}{Элитный рейдер}
{17341}{}{Элитный рейдер. Элита своей банды.}
{17350}{}{Элитный рейдер}
{17351}{}{Элитный рейдер. Элита своей банды.}
{17360}{}{Рейдер профессионал}
{17361}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17370}{}{Рейдер профессионал}
{17371}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17380}{}{Рейдер профессионал}
{17381}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17390}{}{Легендарный лидер рейдеров}
{17391}{}{Легендарный лидер рейдеров. Один из представителей легендарной банды "Ханы". Он очень силен.}

#SLAVERS
{17500}{}{Работорговец новичок}
{17501}{}{Работорговец новичок. Молодой парень с клеймом работорговца на лбу. Дёрганый мерзавец, который жаждет себя проявить.}
{17510}{}{Работорговец новичок}
{17511}{}{Работорговец новичок. Молодая девушка с клеймом работорговца на лбу. Дёрганая дрянь, которая жаждет себя проявить.}
{17520}{}{Работорговец бугай}
{17521}{}{Работорговец бугай. Крепкий мужик с клеймом работорговца на лбу. Он дерзко осматривал Вас, словно прицениваясь}
{17530}{}{Работорговец бугай}
{17531}{}{Работорговец бугай. Крепкий мужик с клеймом работорговца на лбу. Грязные руки, не чистая совесть и хищный взгляд выдают в нём «хорошего бизнесмена».}
{17540}{}{Работорговец стрелок}
{17541}{}{Работорговец стрелок. Судя по всему это один из «загонщиков» работорговцев.  Задача этого трапера выследить и поймать человека, желательно со всей семьёй.}
{17550}{}{Работорговец стрелок}
{17551}{}{Работорговец стрелок. Судя по всему это один из «загонщиков» работорговцев.  Задача этого трапера выследить и поймать человека, желательно со всей семьёй.}
{17560}{}{Работорговец ветеран}
{17561}{}{Работорговец ветеран. Опытный бандит с клеймом работорговца на лбу. Похоже, он знает цену каждому и Вам не хотелось бы быть в зоне его «интереса».}
{17570}{}{Работорговец ветеран}
{17571}{}{Работорговец ветеран. Опытная разбойница с клеймом работорговца на лбу. Похоже, она знает цену каждому и Вам не хотелось бы быть в зоне её «интереса».}
{17580}{}{Начальник работорговцев}
{17581}{}{Начальник работорговцев. Хорошо выглядящий бизнесмен с клеймом работорговца на лбу.  Он знает толк в «трудовых коллективах» и системе мотиваций.}
{17590}{}{Начальник работорговцев}
{17591}{}{Начальник работорговцев. Статного вида мужик с клеймом работорговца на лбу. Этот «Чёрный властелин» поломал не мало судеб.}

#CARAVANS
{17800}{}{Случайный попутчик}
{17801}{}{Случайный попутчик. Вас не отпускает чувство, что этого человека тут вообще быть не должно.}
{17810}{}{Случайный попутчик}
{17811}{}{Случайный попутчик. Вас не отпускает чувство, что этого человека тут вообще быть не должно.}
{17820}{}{Охранник каравана новичок}
{17821}{}{Охранник каравана новичок. Явно чувствует себя неуверенно.}
{17830}{}{Охранник каравана новичок}
{17831}{}{Охранник каравана новичок. Явно чувствует себя неуверенно.}
{17840}{}{Здоровый охранник каравана}
{17841}{}{Здоровый охранник каравана. Да это настоящий шкаф!}
{17850}{}{Здоровый охранник каравана}
{17851}{}{Здоровый охранник каравана. Да это настоящий шкаф!}
{17860}{}{Охранник каравана ветеран}
{17861}{}{Охранник каравана ветеран. Бывалого человека видно сразу.}
{17870}{}{Охранник каравана ветеран}
{17871}{}{Охранник каравана ветеран. Бывалого человека видно сразу.}
{17880}{}{Охранник каравана стрелок}
{17881}{}{Охранник каравана стрелок. Щурясь разглядывает местность.}
{17890}{}{Охранник каравана стрелок}
{17891}{}{Охранник каравана стрелок. Щурясь разглядывает местность.}
{17900}{}{Караванщик}
{17901}{}{Караванщик. Кажется, этот человек тут всеми руководит.}
{17910}{}{Караванщик}
{17911}{}{Караванщик. Кажется, этот человек тут всеми руководит.}

#STRANGERS
{18100}{}{Бездомный}
{18101}{}{Бездомный. Вонючий бродяга, которых полно на пустошах. Выглядит побитым, ведёт себя нервно.}
{18110}{}{Бездомная}
{18111}{}{Бездомная. Грязная женщина с забитым взглядом. От неё разит несчастьем.}
{18120}{}{Мусорщик}
{18121}{}{Мусорщик. Обычный собиратель. Он дёргано осматривается вокруг, ища то, чем можно поживиться.}
{18130}{}{Мусорщица}
{18131}{}{Мусорщица. Типичная собирательница. Она дёргано осматривается вокруг, ища то, чем можно поживиться.}
{18140}{}{Отброс}
{18141}{}{Отброс. Озлобленный оборванец, каких полно в любых трущобах. Он чем-то занят и старается на Вас не смотреть.} 
{18150}{}{Отброс}
{18151}{}{Отброс. Озлобленная оборванка, каких полно в любых трущобах. Она чем-то занята и старается на Вас не смотреть.}
{18160}{}{Охотник}
{18161}{}{Охотник. Бывалый трапер с обветренным лицом и характерным прищуром.}
{18170}{}{Охотница}
{18171}{}{Охотница. Бывалый трапер с обветренным лицом и характерным прищуром.}
{18180}{}{Бродяга}
{18181}{}{Бродяга. Обычный путник из пустошей.  Не понять, из каких мест он родом, но судя по рваной мешковине на нём – путь был долгим.}
{18190}{}{Бродяжка}
{18191}{}{Бродяжка. Обычная путница из пустошей.  Не понять, из каких мест она родом, но судя по рваной мешковине на ней – путь был долгим.}
{18200}{}{Изгой}
{18201}{}{Изгой. Вонючий бродяга, которых полно на пустошах. Этот выглядит больным, или просто урод.}
{18210}{}{Изгой}
{18211}{}{Изгой. Дряхлый старик, доживающий свой век. Жалкое зрелище.}
{18220}{}{Законник}
{18221}{}{Законник. Бывалый наёмник в крепкой амуниции. Вооружён и видимо опасен.}
{18230}{}{Законник}
{18231}{}{Законник. Бывалый наёмник в крепкой амуниции. Вооружён и видимо опасен.}

#GHOULS
{18400}{}{Хилый гуль}
{18401}{}{Хилый гуль. Кожа да кости. В прямом смысле.}
{18410}{}{Хилый гуль}
{18411}{}{Хилый гуль. Кожа да кости. В прямом смысле.}
{18420}{}{Облезлый гуль}
{18421}{}{Облезлый гуль. Из отвалившихся кусков кожи вполне можно было бы сшить сумку.}
{18430}{}{Облезлый гуль}
{18431}{}{Облезлый гуль. Из отвалившихся кусков кожи вполне можно было бы сшить сумку.}
{18440}{}{Мерзкий гуль}
{18441}{}{Мерзкий гуль. Кажется, от одного вида вас сейчас вырвет.}
{18450}{}{Мерзкий гуль}
{18451}{}{Мерзкий гуль. Кажется, от одного вида вас сейчас вырвет.}
{18460}{}{Грязный гуль}
{18461}{}{Грязный гуль. Налипшая на ходячий скелет грязь сделала его не таким заметным.}
{18470}{}{Грязный гуль}
{18471}{}{Грязный гуль. Налипшая на ходячий скелет грязь сделала его не таким заметным.}
{18480}{}{Отвратительный гуль}
{18481}{}{Отвратительный гуль. На ЭТО можно смотреть только через прицел.}
{18490}{}{Отвратительный гуль}
{18491}{}{Отвратительный гуль. На ЭТО можно смотреть только через прицел.}
{18500}{}{Гниющий гуль}
{18501}{}{Гниющий гуль. Ничего отвратительнее ваш нос еще не... нюхал?}
{18510}{}{Гниющий гуль}
{18511}{}{Гниющий гуль. Ничего отвратительнее ваш нос еще не... нюхал?}
{18520}{}{Светящийся гуль}
{18521}{}{Светящийся гуль. Как насчет пары лишних РАД?}
{18530}{}{Светящийся гуль}
{18531}{}{Светящийся гуль. Как насчет пары лишних РАД?}
{18540}{}{Быстрый гуль}
{18541}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18550}{}{Быстрый гуль}
{18551}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18560}{}{Быстрый гуль}
{18561}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18570}{}{Быстрый гуль}
{18571}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18580}{}{Быстрый гуль}
{18581}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18590}{}{Быстрый гуль}
{18591}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}

#SUPERMUTANTS
{18700}{}{Супермутант}
{18701}{}{Супермутант. Огромный кусок мышц. У этих созданий не так много оснований быть причисленными к разряду разумных.}
{18710}{}{Супермутант}
{18711}{}{Супермутант. Живой ужас пустошей. Тупой, злой, воняет.}
{18720}{}{Супермутант громила}
{18721}{}{Супермутант громила. Огромная туша состоящая из мышц, злобы и лёгкой брони - выглядит опасно. Осматривается с тупым видом в поисках того, что можно сломать.}
{18730}{}{Супермутант громила}
{18731}{}{Супермутант громила. Тварь в нетерпении топчется на месте.  Она хочет бить, ломать и крушить, а не вот это вот всё.}
{18740}{}{Супермутант берсерк}
{18741}{}{Супермутант берсерк. Тело этого существа покрыто гематомами. Похоже, от боли и ярости эта тварь совсем обезумела.}
{18750}{}{Супермутант берсерк}
{18751}{}{Супермутант берсерк. Всё его тело покрыто шрамами. Это безумное существо вышло победителем из многих схваток, оно очень опасно.}
{18760}{}{Супермутант мастер}
{18761}{}{Супермутант мастер. Существо покрыто бронёй из ржавых листов метала и цепей. Доспех выглядит дико и гремит при движении, но похоже очень нравится монстру}
{18770}{}{Супермутант мастер}
{18771}{}{Супермутант мастер. Закованное в доспех чудовище выглядит не умнее остальных представителей своего вида, но чувствует себя явно важнее.}
{18780}{}{Тень}
{18781}{}{Тень. Огромный кусок мышц. Это создание обладает удивительно осмысленным и пронзительным взглядом.}
{18790}{}{Тень}
{18791}{}{Тень. Огромный кусок мышц. Это создание обладает осмысленным и пронзительным взглядом.}
{18800}{}{Тень берсерк}
{18801}{}{Тень берсерк. Это умное и опытное существо вышло победителем из многих схваток, оно очень опасно.}
{18810}{}{Тень берсерк}
{18811}{}{Тень берсерк. Это умное и опытное существо вышло победителем из многих схваток, оно очень опасно.}
{18820}{}{Тень мастер}
{18821}{}{Тень мастер. Монстр с умным и спокойным взглядом. Вы чувствуете себя маленьким перед ним не только по росту. Это существо больше всего, чем вы могли бы стать.}
{18830}{}{Тень мастер}
{18831}{}{Тень мастер. Монстр с умным и спокойным взглядом. Вы чувствуете себя маленьким перед ним не только по росту. Это существо больше всего, чем вы могли бы стать.}
{18840}{}{Тень снайпер}
{18841}{}{Тень снайпер. Умное и хитрое существо с отточенными движениями и огромной винтовкой в руках.}
{18850}{}{Тень снайпер}
{18851}{}{Тень снайпер. Умное и хитрое существо с отточенными движениями и огромной винтовкой в руках.}

#ROBOTS
{19000}{}{Робомозг}
{19001}{}{Многоцелевой кибернетический организм, в качестве процессора которого используется мозг животного или человека.}
{19010}{}{Робоглаз}
{19011}{}{Вооружённый парящий робот. Как правило, несёт ремонтные или охранные функции.}
{19020}{}{Помощник}
{19021}{}{Пользующаяся огромной популярностью в довоенных США серия домашних и рабочих роботов.}
{19030}{}{Робот охранник}
{19031}{}{Довоенная боевая еденица. Имеет систему распознавания «свой-чужой». Вооружены тяжёлым оружием но испытывают недостаток мобильности.}
{19040}{}{Лазерная турель}
{19041}{}{Роботизировання охранная система.}
{19050}{}{Лазерная турель}
{19051}{}{Роботизировання охранная система.}
{19060}{}{Плазменная турель}
{19061}{}{Роботизировання охранная система.}
{19070}{}{Пулеметная турель}
{19071}{}{Роботизировання охранная система.}

#MODOC GUARDS
{19300}{}{Охранник Модока}
{19301}{}{Охранник Модока. Эти ребята знают свое дело.}
{19310}{}{Охранник Модока}
{19311}{}{Охранник Модока. Эти ребята знают свое дело.}
{19320}{}{Охранник Модока}
{19321}{}{Охранник Модока. Эти ребята знают свое дело.}
{19330}{}{Охранник Модока}
{19331}{}{Охранник Модока. Эти ребята знают свое дело.}
{19340}{}{Охранник Модока}
{19341}{}{Охранник Модока. Эти ребята знают свое дело.}
{19350}{}{Охранник Модока}
{19351}{}{Охранник Модока. Эти ребята знают свое дело.}
{19360}{}{Охранник Модока}
{19361}{}{Охранник Модока. Эти ребята знают свое дело.}
{19370}{}{Охранник Модока}
{19371}{}{Охранник Модока. Эти ребята знают свое дело.}
{19380}{}{Охранник Модока}
{19381}{}{Охранник Модока. Эти ребята знают свое дело.}
{19390}{}{Охранник Модока}
{19391}{}{Охранник Модока. Эти ребята знают свое дело.}
{19400}{}{Охранник караванщиков}
{19401}{}{Охранник караванщиков. Крутой, суровый, молчаливый. Настоящий профи.}
{19410}{}{Лирой}
{19411}{}{Лирой. Этот мужик не пропустит даже муху без документов.}

#FOX'S VILLA
{19600}{}{Сильная рабыня}
{19601}{}{Сильная рабыня. Крепкого вида рабыня. Хотите купить?}
{19610}{}{Сильная рабыня}
{19611}{}{Сильная рабыня. Крепкого вида рабыня. Хотите купить?}
{19620}{}{Сильный раб}
{19621}{}{Сильный раб. Крепкого вида раб. Хотите купить?}
{19630}{}{Сильный раб}
{19631}{}{Сильный раб. Крепкого вида раб. Хотите купить?}
{19640}{}{Сильный раб}
{19641}{}{Сильный раб. Крепкого вида раб. Хотите купить?}
{19650}{}{Сильный раб}
{19651}{}{Сильный раб. Крепкого вида раб. Хотите купить?}
{19660}{}{Сильный раб}
{19661}{}{Сильный раб. Крепкого вида раб. Этот - классического черного цвета.}
{19670}{}{Крутой работорговец Фокса}
{19671}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19680}{}{Крутой работорговец Фокса}
{19681}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19690}{}{Крутой работорговец Фокса}
{19691}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19700}{}{Крутой работорговец Фокса}
{19701}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19710}{}{Крутой работорговец Фокса}
{19711}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19720}{}{Крутой работорговец Фокса}
{19721}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19730}{}{Крутой работорговец Фокса}
{19731}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19740}{}{Крутой работорговец Фокса}
{19741}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19750}{}{Крутой работорговец Фокса}
{19751}{}{Крутой работорговец Фокса. С гордостью носит клеймо на лбу.}
{19760}{}{Мецгер}
{19761}{}{Это Мецгер. Он явно знает толк в торговле живым товаром.}
{19770}{}{Полковник Фокс}
{19771}{}{Мистер Фокс - крупнейший рабовладелец в этих землях.}

#OTHER HUMAN NPC
{19900}{}{Балтас}
{19901}{}{Балтас. Чертовски сильный человек, знаменитый охотник.}
{19910}{}{Матерый охотник}
{19911}{}{Матерый охотник. Эти ребята могут поймать любую тварь.}
{19920}{}{Матерый охотник}
{19921}{}{Матерый охотник. Эти ребята могут поймать любую тварь.}

#POSEYDON NPC
{20000}{}{Бессмертный Джон}
{20001}{}{Потрепанный годами робот с мозгом в колбе.}
{20010}{}{Кок}
{20011}{}{Жирный потный мужик с лукавым взглядом похотливых глаз. Носит фартук и поварской колпак.}
{20020}{}{Профессор Кеворкян}
{20021}{}{На морщинистом лице читается интерес, раздражение и усталость. Носит очки.}
{20030}{}{Хьюго "Боров" Рут}
{20031}{}{Мордатый грузный мужчина с красным лицом.}
{20040}{}{Могила}
{20041}{}{Сухопарый мужчина с обветренным лицом. Обладатель роскошных усов "подкова".}
{20050}{}{Пепельный Том}
{20051}{}{Гуль совсем уж черного цвета, будто бы соткан из грязи и пепла.}
{20060}{}{Чэд}
{20061}{}{Тучный, пузатый и широкоплечий мужик, в кровавом фартуке. Взгляд не блещет интеллектом.}
{20070}{}{Козявка}
{20071}{}{Очень низкорослый молодой парень.}
{20080}{}{Чог}
{20081}{}{Огромный даже для супермутанта, жуткий монстр.}
{20090}{}{Джесси "СвЕтоша" Кастор}
{20091}{}{Высокий брюнет похмельного вида с вечной щетиной на лице.}
{20100}{}{Шон "Трещётка" МаршАл}
{20101}{}{Необычайно светящийся гуль.}
{20110}{}{Кэртис "Ковбой" Рейдлер}
{20111}{}{Молодой бородатый мужчина, в поношенном пиджаке и в ковбойской шляпе.}
{20120}{}{Брайс "Труба"}
{20121}{}{Высокий худой мужик, с бледной кожей. На левой руке нет среднего пальца. На поясе в чехле лежит металлическая труба.}
{20130}{}{Монтгомери "Монти" Тонато}
{20131}{}{Молодой мужчина с суровым и волевым выражением лица. На щеке видна тонкая белая полоска - шрам от ножа.}
{20140}{}{Гвен Тайлер}
{20141}{}{Симпатичная молодая девушка, сверкает белоснежной улыбкой.}
{20150}{}{Донни "Тесак" Трахо}
{20151}{}{Высокий мексиканец с изрезанным морщинами и ветром лицом. Носит бороду стиля "Якорь".}
{20160}{}{Гарфилд "Заноза" Нельсон}
{20161}{}{Жизнерадостного вида рыжий парень.}
{20170}{}{Нера "Труди" Аргвайр}
{20171}{}{Брюнетка с холодным взглядом.}
{20180}{}{Оливер "Айсман" Рэми}
{20181}{}{Он иронично ухмыляется, глядя на вас.}
{20190}{}{Харон "Просоленный" Диклейн}
{20191}{}{Крайне хорошо сохранившейся гуль в военной форме.}
{20200}{}{Крук Маккензи}
{20201}{}{Худой длиннорукий и длинноногий парень с грязными волосами цвета кукурузы.}
{20210}{}{Саншайн "Санни" 209}
{20211}{}{Выглядит опасно, если вы не знаете что это и зачем - лучше не трогать это.}
{20220}{}{Молли Блум}
{20221}{}{Очень сексуальная, привлекательна девушка.}
{20230}{}{Даймонд "Пэйдж" Даллас}
{20231}{}{Крупный мужчина в возрасте. Его кучерявую шевелюру давно покрыл налет седины.}
{20240}{}{Мерфюс "Старый" МакДилл}
{20241}{}{Пышная рыжая борода, седые виски и явно натянутая улыбка на лице.}
{20250}{}{Бам-Бам Бигелоу}
{20251}{}{Короткостриженный и гладковыбритый коренастый мужик.}
{20260}{}{Броди Джэвис}
{20261}{}{Очки примотаны изолентой к черепу, смотрит хитро и надменно.}
{20270}{}{Турок}
{20271}{}{Небритый, короткостриженный угрюмый чувак, активно предлагающий вам поторговать и приобрести "уникальные вещицы".}
{20280}{}{Гэри}
{20281}{}{Дёрганый вид, порваная роба, большой рюкзак за спиной, руки постоянно чёрные.}
{20290}{}{Дуглас "Шишак"}
{20291}{}{Опрятного вида пожилой мужчина в довоенном костюме, носит очки и кипу.}
{20300}{}{Винни "Широкий" Флетчер}
{20301}{}{Широченный детина, смотрит прям в глаза, тяжелый голос и оттопыренная нижняя губа.}
{20310}{}{Бургер Чак}
{20311}{}{Негр в тёмном расстёгнутом плаще и шляпе, человек неприхотливого и тяжёлого труда.}
{20320}{}{Туко "Амиго" Саламанка}
{20321}{}{Крепкого вида мексиканец. Взглядом буравит вас, будто бы вы должны ему денег.}
{20330}{}{Чунг Дэйшу}
{20331}{}{Небольшого роста азиат с короткими светлыми волосами. Меч на поясе.}
{20340}{}{Томми "Сиська"}
{20341}{}{Невысокий мужчина с мягкими чертами на круглом лице с раздраженно-настороженном выражением.}
{20350}{}{Мистер Шоу}
{20351}{}{Огромный, тучный мужчина с париком на голове и с гримом клоуна на лице. Он вас пугает своим видом.}

#POSEYDON GUARDS
{21000}{}{Рядовая СКБ "Посейдона"}
{21001}{}{Очевидно, что эти наемники не даром получают деньги. С ними лучше не связываться.}
{21010}{}{Рядовой СКБ "Посейдона"}
{21011}{}{Очевидно, что эти наемники не даром получают деньги. С ними лучше не связываться.}
{21020}{}{Страж Башни}
{21021}{}{Суровый мужик, оценивает вас проессиональным взглядом убийцы. Хорошо, что он нанят охранять, а не убивать.}

#LARS'S GANG
{21300}{}{Жучило Дублом}
{21301}{}{Видно что он - отъявленный пират и головорез. Броня покрыта множеством следов битв.}
{21310}{}{Черный Пес}
{21311}{}{Крепкий мужик, на шее красная, выцветшая бандана. Смотрит с прищуром.}
{21320}{}{Жох}
{21321}{}{Длинный нигер крепкого телосложения, при разговоре переодически сплевывает на землю.}
{21330}{}{Израиль Хэнкс}
{21331}{}{Хмурый молчаливый мужик, смотрит на вас оценивающим взлядом, будто бы прикидывая цену ваших пожиток.}
{21340}{}{Карнат}
{21341}{}{Веселый на первый взгляд парень, вечная улыбка. Однако во взгляде видны жажда наживы и славы.}

#KASTOR'S CLERGY
{21400}{}{Хранитель веры Томас "Блаженный" Мэнсон}
{21401}{}{Человек в грязной робе, на которой виднеется свинцовый символ культа «Атом».}
{21410}{}{Хранительница веры Марта "Голос" Свифт}
{21411}{}{Хрупкая фигура в грязноватой робе Атома не по размеру. Она смотрит на вас светло-серыми глазами из под тени капюшона.}
{21420}{}{Хранитель веры Гарольд "Лазарь" Шипман}
{21421}{}{Бородатый, улыбчивый мужчина в грязной робе Атома, на которой виднеются багровые следы.}
{21430}{}{Ревнитель Атома}
{21431}{}{Мрачная личность в алой мантии с символом Атома на ней, лицо скрывает железная маска с прорезью для глаз.}
{21440}{}{Ревнительница Атома}
{21441}{}{Мрачная личность в алой мантии с символом Атома на ней, лицо скрывает железная маска с прорезью для глаз.}

#SAN FRANCISCO NPC
{21500}{}{Ханаяма Каору}
{21501}{}{Огромный азиат, настоящий гигант. Облачен в довоенный костюм-тройку, носит отчки.}
{21510}{}{Акисамэ Коэцудзи}
{21511}{}{Невысокий японец, спокойного вида. В его глазах читается мудрость.}
{21520}{}{Реви Руётэ}
{21521}{}{Молодая красивая японка с дерзким и нахальным взглядом.}
{21530}{}{Бэнг Шируба}
{21531}{}{Ссутуленный седой старикан с пышными усами. Вам кажется, что он оценивает вас.}
{21540}{}{Ло-Пэн}
{21541}{}{Этот китаец достаточно известный в городе. Вы определенно слышали что-то о мастере Ло-Пэне.}
{21550}{}{Лам Чин Ин}
{21551}{}{Он смотрит на вас пристально и как будто бы с враждебностью.}
{21560}{}{Саммо Хун}
{21561}{}{Толстный азиат со смешным лицом и строгим взглядом.}
{21570}{}{Донни Йен}
{21571}{}{Высокий китаец в строгом традиционном наряде позапрошлого столетия.}
{21580}{}{Господин Молох}
{21581}{}{Невероятно крупный и атлетично сложенный мужик, вас поражает ширина его плеч.}
{21590}{}{Арнольд Митч}
{21591}{}{Мужик в замасленном комбенизоне, на голове среди копны немытых волос виднеются очки сварщика.}
{21600}{}{Вальдис Гуз}
{21601}{}{Тучный мужчина от которого смердит рыбой. Быть может он пришел из глубин океана? Вы не знаете.}
{21610}{}{Сигурд Крофт}
{21611}{}{Низкорослый брюнет, разглядывающий вас подобно тому, как торговец смотрит на покупателя.}
{21620}{}{Амели Крофт}
{21621}{}{Женщина средних лет с огромными мешками под глазами. Видно что она очень устает, но улыбка на ее лице довольно искренняя.}
{21630}{}{Билли Ли}
{21631}{}{Поледователь Дракона. Этот парень вам кого-то напоминает, возможно у него есть брат. Крупный, очевидно сильный боец.}
{21640}{}{Джимми Ли}
{21641}{}{Поледователь Дракона. Кажется вы видели его раньше, или у него есть брат близнец. С виду очень силен.}
{21650}{}{Бомж Лукас}
{21651}{}{Из-за огромной свалявшейся грязной бороды на вас смотрят парочка замутненных алкоголем глаз.}
{21660}{}{Кинтара Айнис}
{21661}{}{Обычная с виду девушка, достаточно симпатичная.}
{21670}{}{Акира Хомма}
{21671}{}{Пожилая женщина лет пятидесяти, по ее одежде можно предположить, что она бывалый траппер.}
{21680}{}{Сунь Хэй}
{21681}{}{Этот мужик явно опытный выживалец и охотник, его трофеи говорят сами за себя.}
{21690}{}{Бинго Коробок}
{21691}{}{Лысый щербатый мужичок с хитрющей рожей, чуток шепелявит.}
{21700}{}{Рыбак}
{21701}{}{Этот человек наверное видел больше рыбы, чем вы выпустили пуль за всю жизнь.}
{21710}{}{Крестьянин}
{21711}{}{Быть крестьянином - нелегкий труд, как хорошо что вы обычный бродяга.}
{21720}{}{Крестьянка}
{21721}{}{Из-за грязи истинный цвет ее кожи остается для вас загадкой.}
{21730}{}{Боец Якудза}
{21731}{}{Азиат сурового вида, он точно бандит. Из-под одежды виднеются края ярких татуировок.}
{21740}{}{Боец Якудза}
{21741}{}{Эта дамочка даст фору любому мужику, с татуированными азиатами лучше не связываться.}
{21750}{}{Боец Ши}
{21751}{}{Представитель крупного клана Ши, возможно он крестьянин, а может и бандит.}
{21760}{}{Боец Ши}
{21761}{}{В Ши состоят также и женщины, возможно они примут и вас? Осталось найти контакты.}
{21770}{}{Солдат Молоха}
{21771}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21780}{}{Шлюха}
{21781}{}{Хотите весело провести время? Идите в цирк, а эта грязная шлюха стремится заработать.}
{21790}{}{Шлюха}
{21791}{}{Вы слышали что у некоторых азатских баб есть член, вы уверены что хотите проверить?}
{21800}{}{Сутенер}
{21801}{}{Этот крутой мужик достаточно крут, чтобы держать в узде своих девочек.}
{21810}{}{Барыга}
{21811}{}{Судя по его виду он часть товара употребляет сам.}
{21820}{}{Барыга}
{21821}{}{Наркобарыга, самый обыкновенный, скорее всего он занимается поставками из Рено.}
{21830}{}{Солдат Молоха}
{21831}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21840}{}{Солдат Молоха}
{21841}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21850}{}{Командир Ши}
{21851}{}{Этот представитель Ши выглядит как младший офицер, наверное где то рядом его отряд.}
{21860}{}{Командир Ши}
{21861}{}{Это тот случай когда женщина может эффективно командовать мужчинами. Все у этих азиатов не как у людей.}
{21870}{}{Боец Ши}
{21871}{}{Представитель крупного клана Ши, возможно он крестьянин, а может и бандит.}
{21880}{}{Боец Ши}
{21881}{}{В Ши состоят также и женщины, возможно они примут и вас? Осталось найти контакты.}

#FORP 2019 NPC
{22000}{}{Крыса}
{22001}{}{Крыса. Довольно мелкая тварь.}
{22010}{}{Мантис}
{22011}{}{Мантис. Хладнокровные глаза уставлены на Вас, очень громко и неприятно стрекочет.}
{22020}{}{Муравей}
{22021}{}{Муравей. Усики указывают на Вас, сопровождаясь взглядом хищника.}
{22030}{}{Муравьиный-лев}
{22031}{}{Этот здоровенный муравей выглядит особенно мерзко и опасно, его толстый панцирь покрыт белой вязкой жидкостью, а пасть огромна.}
{22040}{}{Свинокрыс}
{22041}{}{Свинокрыс. Он издаёт звуки, напоминающие писк и хрюканье в одном.}
{22050}{}{Кротокрыс}
{22051}{}{Кротокрыс. Эта огроменная тварь громко рычит.}
{22060}{}{Кротокрыс мутант}
{22061}{}{Гора мускулов и огромные красные глазища. С клыков течёт вязкая слюна. От мутанта крайне дурно пахнет.}
{22070}{}{Серебряный гекко} 
{22071}{}{Серебряный гекко. Это простой мелкий ящер.}
{22080}{}{Золотой гекко}
{22081}{}{Золотой гекко. Этот большой геккон громко клацает острыми зубами.}
{22090}{}{Пещерный гекко}
{22091}{}{Небольшое создание с тёмным окрасом шкуры. По всему телу видны шрамы и потертости от прибывания в пещере. Жёлтые глазища вечно бегают по окружению.}
{22100}{}{Собака} 
{22101}{}{Собака. Дворняга обычных размеров.}
{22110}{}{Оса}
{22111}{}{Крупное мутировавшее насекомое с крупными крылышками. Зеленоватые глаза и острые шипы по тельцу.}
{22120}{}{Таракан} 
{22121}{}{Противный, большой и крайне юркий таракан. Обладает длинными усиками и лапками,а также относительно крепким панцирем.}
{22130}{}{Мелкий чёрный радскорпион} 
{22131}{}{Мелкий чёрный радскорпион. Это малый, но опасный скорпион.} 
{22140}{}{Чёрный радскорпион}
{22141}{}{Чёрный радскорпион. Направляет свой чёрный хвост на вас.}
{22150}{}{Пещерный радскорпион}
{22151}{}{Крупный скорпион с серым панцирем и массивным чёрным хвостом.}
{22160}{}{Брамин}
{22161}{}{Брамин. Над головами летают мухи.}
{22170}{}{Хищное-растение}
{22171}{}{Хищное-растение. Странная, безглазая пасть держится на толстом стебле и манит вас улыбкой.}
{22180}{}{Ванаминго}
{22181}{}{Ванаминго. У этой твари нет ни глаз, ни пальцев. Жуткое зрелище.}
{22190}{}{Детёныш Когтя смерти} 
{22191}{}{Детёныш Когтя смерти. Чуть меньше Вас ростом, но безусловно опасен!}
{22200}{}{Коготь смерти} 
{22201}{}{Коготь смерти. Опустив большие лапы вниз, этот Коготь принюхивается.}
{22210}{}{Коготь смерти охотник} 
{22211}{}{Коготь смерти охотник. Эта тварь серого цвета, она намного опаснее самого сильного когтя смерти в стае.}
{22220}{}{Огненный гекко} 
{22221}{}{Огненный гекко. Из ноздрей исходит слабый дымок.}
{22230}{}{Бестия} 
{22231}{}{Когтистая, низкая и коренастая тварь с серым окрасом.}
{22240}{}{Кентавр} 
{22241}{}{Кентавр. С длинного щупальцеобразного языка течёт мутная слизь.} 
{22250}{}{Летатель} 
{22251}{}{Летатель. Он парит в воздухе, издавая вредные газы через поры подкожного мешка.} 
{22260}{}{Болотник}
{22261}{}{Болотник. Грозная тварь из морских или болотных пучин.}  
{22270}{}{Яо-гай}
{22271}{}{Громадная, мускулистая медведеподобная тварь с внушительными лапами, покрытыми редкой шерстью. На теле виднеются язвы и шрамы. Невероятно острые зубы и длиннющие когти размером с человеческую руку.}
{22280}{}{Жуткохват} 
{22281}{}{Большая извиваящаяся тварь с длинными опасными лапами, острыми клыками и сильным хвостом.}
{22290}{}{Тенехват} 
{22291}{}{Большая извиваящаяся тёмная тварь с длинными опасными лапами, острыми клыками и сильным хвостом.}
{22300}{}{Разлагающийся гуль} 
{22301}{}{Дикий гуль, в глазах ни грамма разума.}
{22310}{}{Дикий гуль} 
{22311}{}{Дикий гуль, в глазах ни грамма разума..}
{22320}{}{Мутированный гуль} 
{22321}{}{Дикий гуль, в глазах ни грамма разума..}
{22330}{}{Огромный мутированный гуль} 
{22331}{}{Дикий гуль, в глазах ни грамма разума..}
#FORP NCR SOLDIERS
{22340}{}{Солдат} 
{22341}{}{Видна нашивка с изображением двуxголового медведя.}
{22350}{}{Солдат} 
{22351}{}{Видна нашивка с изображением двуxголового медведя.}
{22360}{}{Солдат} 
{22361}{}{Видна нашивка с изображением двуxголового медведя.}
{22370}{}{Солдат} 
{22371}{}{Видна нашивка с изображением двуxголового медведя.}
{22380}{}{Солдат} 
{22381}{}{Видна нашивка с изображением двуxголового медведя.}
{22390}{}{Солдат} 
{22391}{}{Видна нашивка с изображением двуxголового медведя.}
#FORP RAINGERS
{22400}{}{Солдат} 
{22401}{}{На груди значок в форме пятиконечной золотистой звезды.}
{22410}{}{Солдат} 
{22411}{}{На груди значок в форме пятиконечной золотистой звезды.}
{22420}{}{Солдат} 
{22421}{}{На груди значок в форме пятиконечной золотистой звезды.}
{22430}{}{Солдат} 
{22431}{}{На груди значок в форме пятиконечной золотистой звезды.}
{22440}{}{Солдат} 
{22441}{}{На груди значок в форме пятиконечной золотистой звезды.}
{22450}{}{Солдат} 
{22451}{}{На груди значок в форме пятиконечной золотистой звезды.}
#FORP BoS SOLDIERS
{22460}{}{Солдат} 
{22461}{}{На броне изображен крылатый меч и шестеренки.}
{22470}{}{Солдат} 
{22471}{}{На броне изображен крылатый меч и шестеренки.}
{22480}{}{Солдат} 
{22481}{}{На броне изображен крылатый меч и шестеренки.}
{22490}{}{Солдат} 
{22491}{}{На броне изображен крылатый меч и шестеренки.}
{22500}{}{Солдат} 
{22501}{}{На броне изображен крылатый меч и шестеренки.}
{22510}{}{Солдат} 
{22511}{}{На броне изображен крылатый меч и шестеренки.}
#FORP ENCLAVE SOLDIERS
{22520}{}{Солдат} 
{22521}{}{На груди эмблема: "E" в окружении звезд.}
{22530}{}{Солдат} 
{22531}{}{На груди эмблема: "E" в окружении звезд.}
{22540}{}{Солдат} 
{22541}{}{На груди эмблема: "E" в окружении звезд.}
{22550}{}{Солдат} 
{22551}{}{На груди эмблема: "E" в окружении звезд.}
{22560}{}{Солдат} 
{22561}{}{На груди эмблема: "E" в окружении звезд.}
{22570}{}{Солдат} 
{22571}{}{На груди эмблема: "E" в окружении звезд.}
#FORP VAULT_CITY SOLDIERS
{22580}{}{Солдат} 
{22581}{}{На наплечнике эмблема: "VC".}
{22590}{}{Солдат} 
{22591}{}{На наплечнике эмблема: "VC".}
{22600}{}{Солдат} 
{22601}{}{На наплечнике эмблема: "VC".}
{22610}{}{Солдат} 
{22611}{}{На наплечнике эмблема: "VC".}
{22620}{}{Солдат} 
{22621}{}{На наплечнике эмблема: "VC".}
{22630}{}{Солдат} 
{22631}{}{На наплечнике эмблема: "VC".}
#FORP RENEGADE SOLDIERS
{22640}{}{Солдат} 
{22641}{}{На броне нет отличительных черт.}
{22650}{}{Солдат} 
{22651}{}{На броне нет отличительных черт.}
{22660}{}{Солдат} 
{22661}{}{На броне нет отличительных черт.}
{22670}{}{Солдат} 
{22671}{}{На броне нет отличительных черт.}
{22680}{}{Солдат} 
{22681}{}{На броне нет отличительных черт.}
{22690}{}{Солдат} 
{22691}{}{На броне нет отличительных черт.}
#GENERIC DWELLERS
{22700}{}{Шлюха} 
{22701}{}{Типичная шмара.}
#Vault Lads
{22710}{}{Житель Убежища} 
{22711}{}{Типичный житель Убежища.}
{22720}{}{Житель Убежища} 
{22721}{}{Типичный житель Убежища.}
{22730}{}{Офицер СБ Убежища} 
{22731}{}{Местный силовик на страже порядка.}
{22740}{}{Офицер СБ Убежища} 
{22741}{}{Местный силовик на страже порядка.}
{22750}{}{Ученый} 
{22751}{}{Опрятный человек с явными повадками ученого.}
{22760}{}{Ученый} 
{22761}{}{Опрятный человек с явными повадками ученого.}
{22770}{}{Мистер Помощник} 
{22771}{}{Самый продоваемый довоенный робот. Всеми известный Мистер Помощник - лучший друг домохозяек.}
{22780}{}{Работник Тех. Отдела} 
{22781}{}{Обычный работник технического отдела.}
{22790}{}{Работник Тех. Отдела} 
{22791}{}{Обычный работник технического отдела.}
{22800}{}{Капитан СБ Убежища} 
{22801}{}{Капитан местной СБ Убежища.}
{22810}{}{Привилегерованный Резидент} 
{22811}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22820}{}{Привилегерованный Резидент} 
{22821}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22830}{}{Привилегерованный Резидент} 
{22831}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22840}{}{Привилегерованный Резидент} 
{22841}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22850}{}{Привилегерованный Резидент} 
{22851}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22860}{}{Привилегерованный Резидент} 
{22861}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22870}{}{Привилегерованный Резидент} 
{22871}{}{Этот житель либо очень важен, либо имеет некие особые привилегии в Убежище.}
{22900}{}{Аризонская Многоножка} 
{22901}{}{Огромная многоножка.}
{22910}{}{Лаваш} 
{22911}{}{Огромная мутировавшая корова.}
{22920}{}{Гигантский Паук}
{22921}{}{Гигантский Паук.}
{22930}{}{Койот}
{22931}{}{Пустынный койот. В этих краях это самое распространенное существо.}
{23180}{}{Шейман Мур}
{23181}{}{Перед вами лидер "Подполья". С этим мужчной шутки плохи, его внимательный взгляд изучает Вас.}
{23190}{}{София Пейн}
{23191}{}{Правая рука лидера "Подполья". Ирокез на её голове, множество татуировок на теле и горючие смеси на поясе говорят о том, что она подрывник.}
{23200}{}{Анархист из "Подполья"}
{23201}{}{Один из сподвижников революционного движения "Подполье". Его лицо скрыто красной банданой.}
{23210}{}{Анархистка из "Подполья"}
{23211}{}{В ней явно виден дух революции и символика "Подполья" на нагруднике. Её лицо скрыто красной банданой.}
{23220}{}{Оперативник из "Подполья"}
{23221}{}{Боевик из "Подполья". Он на вид опасен и решителен, готов к битве за свободу и жизнь.}
{23230}{}{Оперативница из "Подполья"}
{23231}{}{Данная особа явно знает с какой стороны держать оружие. В её взгляде читаем непоколебимый дух революции.}
