#-------------------------------------------------------------------
#TLJ - GM spawns
#-------------------------------------------------------------------

#RATS
{10}{}{Детёныш крысы}
{11}{}{Ещё совсем маленький, но уже достаточно наглый.}
{20}{}{Мелкая крыса}
{21}{}{У этой мелкой крыски непропорционально большие клыки и красные глаза.}
{30}{}{Крыса}
{31}{}{С ее клыков обильно течет слюна.}
{40}{}{Облученная крыса}
{41}{}{От этой крысы исходит слабое свечение и на ней почти нет шерсти.}
{50}{}{Большая крыса}
{51}{}{Кто сказал, что «чем больше, тем лучше», явно никогда не видел таких крыс.}
{60}{}{Мутировавшая крыса}
{61}{}{Злое существо размером с маленькую собаку.}
{70}{}{Бешеная крыса}
{71}{}{Обычная крыса со следами укусов. У неё отсутствует большая часть хвоста.}

#MANTIS
{100}{}{Жалкий мантис}
{101}{}{Маленькое и противное насекомое с длинными ногами.}
{110}{}{Мантис}
{111}{}{Среднего размера мантис с длинными и острыми лапками, которые могут заколоть вас до смерти, особенно если против вас стайка этих существ.}
{120}{}{Большой мантис}
{121}{}{Огромное насекомое с не менее внушительными клешнями и массивным телом. Голова хаотично двигается в разные стороны.}
{130}{}{Мантис вожак}
{131}{}{Огромный и исключительный представитель своего семейства. Впечатляющие крылья и вечно агрессивно щелкающие клешни, которые удивительно легко могут и ноги сломать.}

#ANTS
{200}{}{Муравей рабочий}
{201}{}{Маленькие, изворотливые твари, постоянно находятся в движении.}
{210}{}{Муравей солдат}
{211}{}{Крупное существо, со среднего размера когтями и длинными усиками. Внушительные челюсти двигаются плавно.}
{220}{}{Муравей задира}
{221}{}{Этот здоровенный муравей выглядит особенно отвратительно и крупногабаритно. Тело непропорционально большое, из-за чего выглядит неприятно.}
{230}{}{Муравей стражник}
{231}{}{Это Альфа-самец: его панцирь выглядит очень толстым. Мощные когти, длинные жвалы и огромные глаза.}
{240}{}{Муравьиный-лев}
{241}{}{Эта особь настолько же отвратительная, насколько опасная. Прочный хитин, ко всему прочему покрыт вязкой, белесой дрянью, а широкая пасть словно приглашает тебя на ужин.}

#PIG RATS
{300}{}{Свинокрыс}
{301}{}{Вот уж действительно мерзкая тушка на когтистых лапках. Оно издает звуки, напоминающие писк и хрюканье одновременно.}
{310}{}{Большой свинокрыс}
{311}{}{Жирная туша на толстых, когтистых лапах с зубасты рылом.}
{320}{}{Свинокрыс альфа-особь}
{321}{}{Матерый, невероятно крупный хряк. Его исполосованная старыми шрамами шкура может рассказать о долгой, насыщенной "захватывающими" событиями жизни.}

#MOLE RATS
{330}{}{Кротокрыс}
{331}{}{Маленькое животное на четырех ногах с когтями и острыми зубами. На морде и хвосте видны длинные усики.}
{340}{}{Большой кротокрыс}
{341}{}{Огромный и чрезвычайно мясистый зверь. Вся кожа в складках темно-розового цвета.}
{350}{}{Крысокабанище}
{351}{}{Огромный, мясистый землекоп с особенно длинными когтями. Зубы чрезвычайно острые и крупные, а на теле видны многочисленные шрамы.}
{360}{}{Кротокрыс мутант}
{361}{}{Лысая гора мускулов лишенная всякой растительности на теле, с огромными красными глазами. С клыков течет вязкая слюна. От мутанта невероятно дурно пахнет...}

#RABIT H RATS VARIANTS
{370}{}{Бешеный свинокрыс}
{371}{}{Крыса-свинья, полностью покрытая грязью и слизью, с кусками мяса там, где должен быть рот. Он издает громкие леденящий кровь писки.}
{380}{}{Бешеный кротокрыс}
{381}{}{Большой вонючий кротокрыс, потерявший рассудок. Он постоянно нюхает землю, шаркая мордой по ней, оставляя за собой кровавый след.}

#SILVER GECKOS
{400}{}{Серебряный гекко}
{401}{}{Маленький серебристый геккон. Маленькие лапки на относительно крупном тельце.}
{410}{}{Хищный серебряный гекко}
{411}{}{Жилистый геккон с длинным хвостом. Во пасти видны частые и очень острые зубы.}
{420}{}{Крупный серебряный гекко}
{421}{}{Очень крупный геккон, по сравнению со своими собратьями. Длинные лапы с опасными когтями, радужная кожа.}
{430}{}{Серебряный гекко альфа-особь}
{431}{}{Самый большой серебристый геккон. Его крупные красные глаза налиты кровью, а на коже наблюдаются небольшие шипы.}

#GOLDEN GECKOS
{440}{}{Золотой гекко}
{441}{}{Маленький и шустрый золотистый геккон. Хвостик всегда виляет в такт походке.}
{450}{}{Большой золотой гекко}
{451}{}{Крупное существо с длинным хвостом и острыми зубами. Его золотистая шкурка красиво переливается на солнце.}
{460}{}{Золотой гекко Альфа}
{461}{}{Самый большой золотой геккон. Его большие красные глаза налиты кровью, а на коже часты шрамы и рубцы.}

#CAVE GECKOS
{470}{}{Пещерный гекко}
{471}{}{Небольшое существо с темным цветом кожи. По всему телу видны шрамы и потертости от пребывания в пещере. Желтые глаза, кажется, постоянно бегают.}

#FIREGECKOS
{480}{}{Огненный гекко}
{481}{}{Небольшой, но чрезвычайно красочный зверек. Из ноздрей существа идет легкий дымок.}
{490}{}{Огненный гекко Альфа-особь}
{491}{}{Чрезвычайно крупный огненный геккон с внушительным телосложением и целым «фонтаном» дыма, вырывающимся из его ноздрей. Пасть вечно открывается, выпуская на волю струйки огня. Много славных мужчин и женщин  «погорели» при встречи с ним.}

#RABID GECKO VARIANTS
{500}{}{Бешеный серебрянный гекко}
{501}{}{Потрёпанный геккон с сухой кожей от постоянного пребывания на открытом воздухе. он рычит на тебя, высовывая прикушенный язык.}
{510}{}{Бешеный золотой гекон}
{511}{}{Сгорбленный геккон с золотистой кожей с крупными коричневатыми пятнами на ней. он скрипит зубами в ожидании чего-то.}

#DOGS
{600}{}{Слабый пёс}
{601}{}{Тощее животное, на теле видны ребра и следы длительного голодания. Шерсть поредела.}
{610}{}{Собака}
{611}{}{Обыкновенная дворняга средних размеров.}
{620}{}{Матерый пёс}
{621}{}{Множество старых шрамов и ран дают понять, что эта собака многое пережила.}
{630}{}{Большая собака}
{631}{}{Большая собака с грубой и дикой мордой. С клыков капает слюна, а на лапах видна грязь.}
{640}{}{Щенок}
{641}{}{Небольшое создание с маленькими лапками, длинной мордочкой и короткой шерстью.}

#WOLVES
{650}{}{Слабый волк}
{651}{}{Маленькое существо, чем-то напоминающее собаку. Редкий мех, маленькие клыки и когти на лапах. Он выглядит измученным.}
{660}{}{Волк}
{661}{}{Существо средних размеров. Хорошая шкура, крепкое телосложение, длинная и вытянутая морда с острыми зубами в пасти.}
{670}{}{Матерый волк}
{671}{}{Потрепанный волк. На теле множественные шрамы, на лапах запекшаяся кровь.}
{680}{}{Вожак волков}
{681}{}{Огромный и старый волк. Его крупное телосложение и чрезвычайно длинные когти и зубы дают понять, что он прожил очень много. На волчьей шкуре обилие старых шрамов и относительно свежих ран.}
{690}{}{Щенок}
{691}{}{Маленькое существо с маленькими лапками, длинной мордочкой и серым мехом. Наличие острых клыков выдает в нем волчьего щенка.}

#COYOTES
{700}{}{Койот}
{701}{}{Пустынный койот.}

#RABID DOG VARIANTS
{710}{}{Бешеный пёс}
{711}{}{Избитая собака с липкой отвратительной черной шерстью. Бесцельно бродит, рыча на все что движется.}
{720}{}{Бешеный волк}
{721}{}{Огромный серый волк с большим шрамом на голове. Когда он замечает вас, то обнажает набор острых окровавленных клыков.}

#RAD SCORPIONS
{800}{}{Маленький радскорпион}
{801}{}{Маленький скорпион с не очень внушительными клешнями и маленьким хвостом.}
{810}{}{Радскорпион}
{811}{}{Скорпион средних размеров. С хвоста и жала капает яд. Массивные клешни и быстрые лапы.}
{820}{}{Большой радскорпион}
{821}{}{Клешни раскрыты, готовые рвать. Жало поднято, пора умирать.}

#BLACKSCORPS
{830}{}{Маленький черный скорпион}
{831}{}{Маленький скорпион с длинным хвостом и черным панцирем.}
{840}{}{Черный радскорпион}
{841}{}{Большой черный скорпион с толстым панцирем и массивным свисающим хвостом. Жало источает яд.}

#CAVESROPS
{850}{}{Пещерный радскорпион}
{851}{}{Большой скорпион с серым панцирем и массивным черным хвостом.}

#BRAHMINS
{900}{}{Слабый брамин}
{901}{}{Маленький и слабый брамин. Он выглядит худым и голодным.}
{910}{}{Брамин}
{911}{}{Две головы, четыре копыта и одно большое брюхо. На одной из голов есть рога.}
{920}{}{Большой брамин}
{921}{}{Крупный брамин с массивными головами и туловищем.}
{930}{}{Дикий брамин}
{931}{}{Худой и потрепанный брамин. Тело брамина истерзано дикой природой.}
{940}{}{Яростный брамин}
{941}{}{Крупный брамин темного цвета. Рога длиннее, чем у обычного брамина, а копыта выглядят массивнее.}
{950}{}{Бешеный брамин}
{951}{}{Брамин весь в синяках и ссадинах, его головы бездумно бьются друг о друга.}

#LAVASH
{960}{}{Лаваш}
{961}{}{Существо, похожее на корову.}

#SPOREPLANTS
{1000}{}{Хищное растение}
{1001}{}{Странный безглазый рот держится на толстом стебле.}
{1010}{}{Большое хищное растение}
{1011}{}{Огромный безглазый рот с многочисленными придатками по бокам. Стебель покрыт шипами, а само растение чрезвычайно высокое.}

#YAO
{1100}{}{Яо-гай}
{1101}{}{Огромное, мускулистое существо похожее на медведя, с внушительными лапами, покрытыми редкой шерстью. На теле есть язвы и шрамы. У него невероятно острые зубы и длинные когти размером с человеческую руку.}
{1110}{}{Бешеный Яо-гай}
{1111}{}{Огромное мускулистое медвежье существо, покрытое кровью и свежими ранами. Вокруг его огромных и острых зубов видна пена, и он яростно оглядывается.}

#ALIENS
{1200}{}{Странное яйцо}
{1201}{}{Странное округлое яйцо неизвестного происхождения.}
{1210}{}{Ванаминго}
{1211}{}{У этого существа нет ни глаз, ни пальцев. Мерзкие длинные бескостные щупальца выходят из тела.}
{1220}{}{Большой ванаминго}
{1221}{}{Большое и страшное безглазое существо с длинными противными щупальцами.}

#MOTERALIENS
{1230}{}{Ванаминго матриарх}
{1231}{}{Матриарх Ванаминго. Из пасти здоровенного ванаминго течет слизь, а блестящая кожа имеет темно-серый оттенок.}

#DEATHCLAWS
{1300}{}{Коготь Смерти детеныш}
{1301}{}{Маленькое гуманоидное существо с длинными лапами, из-под которых видны острые когти.}
{1310}{}{Молодой Коготь Смерти}
{1311}{}{Существо среднего размера с светло-коричневым окрасом и небольшими рожками.}
{1320}{}{Большой Коготь Смерти}
{1321}{}{Большое и мускулистое и страшное существо. На лапах видны длинные и острые когти. У него большие и изогнутые клыки.}
{1330}{}{Коготь Смерти Альфа}
{1331}{}{Огромный коготь смерти с более темным окрасом, длинными изогнутыми рогами и множеством шрамов по всему телу. Громоздкие лапы способны разорвать на части даже хорошо защищенного бойца.}
{1340}{}{Коготь Смерти охотник}
{1341}{}{Огромный коготь смерти серого цвета. Изогнутое мускулистое тело, мощные лапы и длинные рога, направленные вперед. Посмотри в его глаза, прежде чем умереть. Знай, что всякая надежда покинула тебя.}

#BEAST
{1350}{}{Бестия}
{1351}{}{Когтистое, низкорослое, коренастое существо серого цвета.}

#CROCS
{1400}{}{Жуткохват}
{1401}{}{Большое, извивающееся существо, с длинными опасными лапами, острыми клыками и сильным хвостом.}
{1410}{}{Тенехват}
{1411}{}{Большое, извивающееся, темное существо с длинными опасными лапами, острыми клыками и сильным хвостом.}

#CENTAURS
{1500}{}{Немощный кентавр}
{1501}{}{Маленькое, но крайне мерзкое существо. Передвигается на шести человеческих руках. На длинных шеях красуются изуродованные головы.}
{1510}{}{Кентавр}
{1511}{}{С длинного щупальцеобразного языка этого существа течет мутная слизь, а из живота растёт пучок толстых щупалец, скребущих землю под ними.}
{1520}{}{Кентавр задира}
{1521}{}{Крайне неприятное зрелище. Существо с разными головами, обилием органов, расположенных снаружи. По телу течет вязкая слизь. Выглядит более опасней и больше среди своих собратьев.}
{1530}{}{Кентавр вожак}
{1531}{}{Огромного кентавра поддерживают десять человеческих рук и пучок щупалец. Три уродливые головы и столь же изуродованное подобие тела.}

#FLOATERS
{1600}{}{Слабый летун}
{1601}{}{Маленькое змееподобное создание, медленно ползующее на хвосте. Вместо лица у существа подобие большого рта.}
{1610}{}{Летун}
{1611}{}{Уродливое существо с огромным горизонтальным ртом, полным зубов.}
{1620}{}{Летатель задира}
{1621}{}{Глупое, но быстрое, живучее и опасное существо. Видит в вас лишь источник пищи.}
{1630}{}{Летатель Альфа}
{1631}{}{Гигантский Летун с несколькими огромными ртами, полными множества острых зубов в едкой слизи. Существо очень сильно воняет.}

#SWAMPLURKERS
{1700}{}{Слабый болотник}
{1701}{}{Маленькое существо в крепком панцире и с массивными клешнями.}
{1710}{}{Болотник}
{1711}{}{Вонючее, крупное и громоздкое существо, покрытое твердым и крепким панцирем. Клешни выглядят чрезвычайно опасными и острыми.}
{1720}{}{Болотник вожак}
{1721}{}{Невероятно большой и сильный, настоящий король болот и других водоемов. Выглядит грозно, а пахнет и того хуже. Защищен крепчайшим панцирем, а клешни могут легко оттяпать конечность.}

#OTHER_INSECTS
{1800}{}{Оса}
{1801}{}{Мутировавшее насекомое с большими крыльями. Зеленоватые глаза и острые шипы по всему телу.}
{1810}{}{Таракан}
{1811}{}{Противный, большой и чрезвычайно шустрый таракан. У него длинные усики и ноги, а также относительно прочный панцирь.}
{1820}{}{Гигантская многоножка}
{1821}{}{Внушительных размеров многоножка. Быстро передвигается, больно кусается... Бррр, мерзость.}
{1830}{}{Гигантский паук}
{1831}{}{Больших размеров паук, обладатель сразу восьми лап, что делает его весьма подвижным и опасным противником.}

#WILD GHOULS
{1900}{}{Разлагающийся гуль}
{1901}{}{Разлагающийся гуль без всяких признаков адекватности в его глазах.}
{1910}{}{Дикий гуль}
{1911}{}{Дикий гуль поехавший крышей во всех смыслах этого слова.}
{1920}{}{Мутировавший гуль}
{1921}{}{Сбрендевший гуль, подверженный дополнительным мутациям.}
{1930}{}{Огромный мутировавший гуль}
{1931}{}{Обезумевший гуль утративший последние остатки разума, внешне выглядит очень опасным и свирепым.}
{1940}{}{Лоботомит}
{1941}{}{Чудовищное творение чьего-то больного разума. Из мозга этого бедолаги была удалена некоторая часть, что сделало его бездумным болванчиком, что даже свою смерть не заметит.}

#FORP NCR SOLDIERS
{2100}{}{Солдат}
{2101}{}{У него видна нашивка с изображением двуглавого медведя.}
{2110}{}{Солдат}
{2111}{}{У неё видна нашивка с изображением двуглавого медведя.}
{2120}{}{Солдат}
{2121}{}{У него видна нашивка с изображением двуглавого медведя.}
{2130}{}{Солдат}
{2131}{}{У неё видна нашивка с изображением двуглавого медведя.}
{2140}{}{Солдат}
{2141}{}{У него видна нашивка с изображением двуглавого медведя.}
{2150}{}{Солдат}
{2151}{}{У неё видна нашивка с изображением двуглавого медведя.}

#FORP RAINGERS
{2200}{}{Солдат}
{2201}{}{На груди знак в виде пятиконечной золотой звезды.}
{2210}{}{Солдат}
{2211}{}{На груди знак в виде пятиконечной золотой звезды.}
{2220}{}{Солдат}
{2221}{}{На груди знак в виде пятиконечной золотой звезды.}
{2230}{}{Солдат}
{2231}{}{На груди знак в виде пятиконечной золотой звезды.}
{2240}{}{Солдат}
{2241}{}{На груди знак в виде пятиконечной золотой звезды.}
{2250}{}{Солдат}
{2251}{}{На груди знак в виде пятиконечной золотой звезды.}

#FORP BoS SOLDIERS
{2300}{}{Солдат}
{2301}{}{На броне изображены крылатый меч и шестеренки.}
{2310}{}{Солдат}
{2311}{}{На броне изображены крылатый меч и шестеренки.}
{2320}{}{Солдат}
{2321}{}{На броне изображены крылатый меч и шестеренки.}
{2330}{}{Солдат}
{2331}{}{На броне изображены крылатый меч и шестеренки.}
{2340}{}{Солдат}
{2341}{}{На доспехе изображены крылатый меч и шестеренки.}
{2350}{}{Солдат}
{2351}{}{На доспехе изображены крылатый меч и шестеренки.}

#FORP ENCLAVE SOLDIERS
{2400}{}{Солдат}
{2401}{}{На груди эмблема «Е», окруженная звездами.}
{2410}{}{Солдат}
{2411}{}{На груди эмблема «Е», окруженная звездами.}
{2420}{}{Солдат}
{2421}{}{На груди эмблема «Е», окруженная звездами.}
{2430}{}{Солдат}
{2431}{}{На груди эмблема «Е», окруженная звездами.}
{2440}{}{Солдат}
{2441}{}{На груди эмблема «Е», окруженная звездами.}
{2450}{}{Солдат}
{2451}{}{На груди эмблема «Е», окруженная звездами.}

#FORP VAULT_CITY SOLDIERS
{2500}{}{Солдат}
{2501}{}{На наплечнике видна эмблема "ГУ"}
{2510}{}{Солдат}
{2511}{}{На наплечнике видна эмблема "ГУ"}
{2520}{}{Солдат}
{2521}{}{На наплечнике видна эмблема "ГУ"}
{2530}{}{Солдат}
{2531}{}{На наплечнике видна эмблема "ГУ"}
{2540}{}{Солдат}
{2541}{}{На наплечнике видна эмблема "ГУ"}
{2550}{}{Солдат}
{2551}{}{На наплечнике видна эмблема "ГУ"}

#FORP RENEGADE SOLDIERS
{2600}{}{Солдат}
{2601}{}{На броне нет никаких отличительных знаков.}
{2610}{}{Солдат}
{2611}{}{На броне нет никаких отличительных знаков.}
{2620}{}{Солдат}
{2621}{}{На броне нет никаких отличительных знаков.}
{2630}{}{Солдат}
{2631}{}{На броне нет никаких отличительных знаков.}
{2640}{}{Солдат}
{2641}{}{На броне нет никаких отличительных знаков.}
{2650}{}{Солдат}
{2651}{}{На броне нет никаких отличительных знаков.}

#VAULT DWELLERS
{2700}{}{Резидент Убежища} 
{2701}{}{Обычный житель убежища.}
{2710}{}{Резидент Убежища} 
{2711}{}{Обычный житель убежища.}
{2720}{}{Офицер охраны Убежища} 
{2721}{}{Сотрудник службы безопасности Убежища, отвечающий за порядок.}
{2730}{}{Офицер охраны Убежища} 
{2731}{}{Сотрудник службы безопасности Убежища, отвечающий за порядок.}
{2740}{}{Ученый} 
{2741}{}{Опрятного вида ученый.}
{2750}{}{Ученый} 
{2751}{}{Опрятного вида ученый.}
{2760}{}{Мистер Помощник} 
{2761}{}{Серия роботов, пользовавшаяся огромной популярностью в довоенных США.}
{2770}{}{Техник Убежища} 
{2771}{}{Обычный работник Убежища из технического отдела.}
{2780}{}{Техник Убежища} 
{2781}{}{Обычный работник Убежища из технического отдела.}
{2790}{}{Начальник Службы Безопасности} 
{2791}{}{Главный офицер, отвечающий за всю службу безопасности Убежища.}
{2800}{}{Резидент высокого класса} 
{2801}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2810}{}{Резидент высокого класса} 
{2811}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2820}{}{Резидент высокого класса} 
{2821}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2830}{}{Резидент высокого класса} 
{2831}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2840}{}{Резидент высокого класса} 
{2841}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2850}{}{Резидент высокого класса} 
{2851}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}
{2860}{}{Резидент высокого класса} 
{2861}{}{Похоже, что этот конкретный житель очень важен или имеет определенные привилегии в Убежище.}

#GENERIC NPC
{3000}{}{Шлюха} 
{3001}{}{Обыкновенная проститутка.}
{3010}{}{Пьяница}
{3011}{}{У этого человека отсутствующий взгляд и очень неприятный запах изо рта.}
{3020}{}{Пьяница}
{3021}{}{Пьяная женщина. Ей трудно ходить прямо, не спотыкаясь.}
{3030}{}{Панк}
{3031}{}{Вы видите довольно молодого человека с несколькими баллончиками и уверенным взглядом.}
{3040}{}{Панк}
{3041}{}{Вы видите довольно молодую женщину со странной причёской и пирсингом на лице.}
{3050}{}{Нищий}
{3051}{}{Он выглядит как труп и не двигается, только один раз неглубоко вздыхает.}
{3060}{}{Нищий}
{3061}{}{Бедная грязная женщина. Проходя мимо, можно услышать тихие рыдания.}
{3070}{}{Дешевая шлюха}
{3071}{}{Женщина средних лет в откровенном изношенном наряде. Она безучастно смотрит на тебя.}
{3080}{}{Бездомный вурдалак}
{3081}{}{Гниющая груда мышц и костей. Вы не можете сказать, жив ли он вообще.}
{3090}{}{Путешественник}
{3091}{}{Обычный путешественник, все еще весь в песке после скитаний по пустошам.}
{3100}{}{Путешественник}
{3101}{}{Обычный путешественник, все еще весь в песке после скитаний по пустошам.}
{3110}{}{Разбойник}
{3111}{}{Обычный грабитель, ищущий свою очередную добычу.}
{3120}{}{Разбойник}
{3121}{}{Обычный грабитель, ищущий свою очередную добычу.}
{3130}{}{Ребенок}
{3131}{}{Маленький ребенок.}
{3140}{}{Ребенок}
{3141}{}{Маленький ребенок.}
{3150}{}{Торговец}
{3151}{}{Вы видите человека в безрукавке и мешком бутылочных пробок, перекинутыми через пояс.}
{3160}{}{Стражник}
{3161}{}{Он одет в металлическую броню. Его глаза лениво следят за каждым проходящим человеком.}
{3170}{}{Стражница}
{3171}{}{Она одета в металлическую броню. Ее глаза лениво следят за каждым проходящим человеком.}
{3180}{}{Сильный охранник}
{3181}{}{Одетый в полный боевой доспех, этот охранник стоит бесстрашно.}
{3190}{}{Сильный охранник}
{3191}{}{Одетый в полный боевой доспех, этот охранник стоит бесстрашно.}
{3200}{}{Доктор}
{3201}{}{Одетый в белый халат, он роется в своей сумке полной медицинского оборудования.}
{3210}{}{Фермер}
{3211}{}{У этого человека хилая осанка и грязная одежда, но он не выглядит голодным или бездомным.}
{3220}{}{Фермер}
{3221}{}{У этого человека хилая осанка и грязная одежда, но он не выглядит голодным или бездомным.}
{3230}{}{Фермер}
{3231}{}{У этого человека хилая осанка и грязная одежда, но он не выглядит голодным или бездомным.}
{3240}{}{Фермер}
{3241}{}{У этой женщины хлипкая осанка и грязная одежда, но она не выглядит голодной или бездомной.}
{3250}{}{Гражданин}
{3251}{}{Похоже, этот человек живет здесь уже давно.}
{3260}{}{Гражданин}
{3261}{}{Похоже, этот человек живет здесь уже давно.}
{3270}{}{Гражданин}
{3271}{}{Эта женщина выглядит так, будто живет здесь уже давно.}
{3280}{}{Мужчина}
{3281}{}{Типичный представитель мужского пола.}
{3290}{}{Женщина}
{3291}{}{Типичный представитель женского пола.}
{3300}{}{Мэр}
{3301}{}{Этот человек отвечает за управление всем городом.}
{3310}{}{Шериф}
{3311}{}{Этот человек отвечает за поддержание порядка во всём городе.}

#ОХОТНИКИ ЗА ГОЛОВАМИ
{3500}{}{Охотник за головами}
{3501}{}{Вы видите обычного охотника за головами в боевой броне.}
{3510}{}{Охотник за головами}
{3511}{}{Вы видите обычного охотника за головами в боевой броне.}
{3520}{}{Крутой охотник за головами}
{3521}{}{Крупный мужчина в боевых доспехах небрежно курящий сигарету.}
{3530}{}{Крутой охотник за головами}
{3531}{}{Крупная женщина в боевых доспехах со скрещенными руками на груди.}
{3540}{}{Ветеран охотников за головами}
{3541}{}{Мужчина с острым взглядом и серьезным выражением лица. Его боевая броня имеет встроенный патронташ.}
{3550}{}{Ветеран охотников за головами}
{3551}{}{Женщина с острым взглядом и серьезным выражением лица. В ее боевую броню встроен патронташ.}
{3560}{}{Охотник за головами-садист}
{3561}{}{Его лицо скрыто за банданой. На его доспехах можно увидеть коллекцию ножей и отрубленных пальцев.}
{3570}{}{Охотник за головами-садист}
{3571}{}{Ее лицо скрыто за банданой. На ее доспехах можно увидеть набор ножей и отрубленных пальцев.}
{3580}{}{Лидер охотников за головами}
{3581}{}{На его боевом доспехе можно увидеть нашивку, напоминающую дракона и винтовку.}
{3590}{}{Лидер охотников за головами}
{3591}{}{На ее боевом доспехе можно увидеть нашивку, напоминающую дракона и винтовку.}

#MUTANTS
{3700}{}{Супермутант}
{3701}{}{Большая зеленая груда мускулов, рожденных рвать и кромсать.}
{3710}{}{Мощный супермутант}
{3711}{}{Гора мускулов, опутанная ржавыми цепями, готовыми кого-нибудь раздавить.}
{3720}{}{Яросный супермутант}
{3721}{}{Судя по ужасным шрамам на его теле, он многое пережил и теперь не собирается останавливаться.}
{3730}{}{Супермутант-берсерк}
{3731}{}{Эта угроза в тяжелых металлических доспехах готова выбить вашу душу из тела.}
{3740}{}{Повелитель супермутантов}
{3741}{}{Этот супермутант в прочных металлических доспехах, украшенных черепами его противников, выглядит так, будто может задушить вас всего двумя пальцами.}
{3750}{}{Найткин}
{3751}{}{Чрезвычайно сильное и умное существо с синей кожей.}
{3760}{}{Крутой найткин}
{3761}{}{Похоже, что кожа этого найткина толще, чем у остальных.}
{3770}{}{Найткин охотник}
{3771}{}{Огромный мутант, способный нести на спине целую машину.}
{3780}{}{Найткин-мастер}
{3781}{}{Между металлическими пластинами его доспехов виднеются небольшие пятна синей кожи. Его глаза спокойно блуждают по сторонам.}

#TRIBALS
{4000}{}{Дикарь}
{4001}{}{Обычный представитель племени. Жизнь в дикой природе сделала его сильным и ловким.}
{4010}{}{Дикариха}
{4011}{}{Обычный представитель племени. Жизнь на дикой природе сделала её сильной и здоровой.}
{4020}{}{Охотник племени}
{4021}{}{Охотник из племени с колчаном на ремне. На его груди и руках видны шрамы.}
{4030}{}{Племенная охотница}
{4031}{}{Охотница из племени играет со своим оружием. Ее руки покрыты шрамами.}
{4040}{}{Племенной шаман}
(4041}{}{Пожилой мужчина, покрытый символами нарисованными красной краской. Его лицо ничего не выражает.}
{4050}{}{Племенная шаманка}
{4051}{}{Спокойная женщина. Она смотрит на тебя с любопытством.}
{4060}{}{Воин племени}
{4061}{}{Суровый племенной воин с ожерельем из зубов животных, он смотрит на вас холодно.}
{4070}{}{Воин племени}
{4071}{}{На ней только шкура геккона, остальное тело покрыто черной краской.}

#CANNIBALS
{4200}{}{Каннибал}
{4201}{}{Этот мужчина жаждет человеческого мяса и смотрит в вашу сторону.}
{4210}{}{Каннибал}
{4211}{}{Эта женщина жаждет человеческого мяса и смотрит в вашу сторону, облизывая губы.}
{4220}{}{Жалкий каннибал}
{4221}{}{Вы видите худощавого жалкого мужчину в поношенной одежде, запачканной кровью. Он бросает на вас голодный взгляд.}
{4230}{}{Жалкий каннибал}
{4231}{}{Вы видите худощавую бледную женщину в поношенной одежде, запачканной кровью. когда она видит вас, на ее лице появляется слабая улыбка.}
{4240}{}{Мясник-каннибал}
{4241}{}{Крупный мужчина в фартуке, совершенно коричневом от запекшейся крови. Он выглядит сытым.}
{4250}{}{Мясник-каннибал}
{4251}{}{Толстая женщина в фартуке, совсем коричневом от запекшейся крови. Она бросает на вас игривый взгляд, водя пальцем по кухонному ножу.}
{4260}{}{Безумный каннибал}
{4261}{}{Человек, весь в грязи и крови. На руках нет ногтей, вместо них пятна запекшейся крови. когда он смотрит на тебя, по спине пробегает волна мурашек.}
{4270}{}{Безумный каннибал}
{4271}{}{Женщина вся в грязи и крови. она сгорбилась, и ее длинные спутанные волосы почти касаются земли. когда она улыбается тебе, у нее во рту ничего, кроме пустоты.}
{4280}{}{Дикий каннибал}
{4281}{}{Этот бедно одетый мужчина ничем не отличается от остальных, но чувствуется, что что-то не так.}
{4290}{}{Дикий каннибал}
{4291}{}{Эта бедно одетая женщина ничем не отличается от остальных, но чувствуется, что что-то не так.}
{4300}{}{Охотник каннибалов}
{4301}{}{Его руки и грудь изрезаны каким-то холодным оружием, оставляя прямые шрамы. Он стоит невозмутимо.}
{4310}{}{Охотница-каннибал}
{4311}{}{К ее поясу привязана коллекция ножей. Она смотрит на вас с хищной ухмылкой на лице.}
{4320}{}{Крутой каннибал}
{4321}{}{Его мускулистое тело с грубой бледной кожей бросается в глаза. Он смотрит на вас с гордостью и превосходством в глазах.}
{4330}{}{Крутой каннибал}
{4331}{}{Ее впечатляющее подтянутое тело испорчено лишь несколькими шрамами и грязью. Увидев тебя, она хрустит костяшками пальцев.}
{4340}{}{Каннибал-распорядитель пира}
{4341}{}{Высокий лысый мужчина в ремешках из человеческой кожи, украшенных зубами. Белая краска на его лице напоминает череп.}
{4350}{}{Хозяйка пира каннибалов}
{4351}{}{Женщина в скудном наряде и рваном платье из человеческой кожи. Ее черная раскраска лица напоминает череп.}

#BANDITS
{4500}{}{Бандит}
{4501}{}{Обычный бандит, с нетерпением ищущий случая кого-нибудь ограбить.}
{4510}{}{Бандитка}
{4511}{}{Обычный бандит, с нетерпением ищущий случая кого-нибудь ограбить.}
{4520}{}{Крутой Бандит}
{4521}{}{Сильный мужчина в кожаной куртке, обнажающей его бицепсы. Его лицо несколько оцепенело.}
{4530}{}{Крутая Бандитка}
{4531}{}{Сильная женщина в кожаной куртке. Выражение ее лица показывает превосходство.}
{4540}{}{Лидер Бандитов}
{4541}{}{На его броне много царапин. Он выглядит уверенно.}
{4550}{}{Ладерша Бандитов}
{4551}{}{На ее доспехах много царапин. Она выглядит уверенно.}
{4560}{}{Бандитский разведчик}
{4561}{}{Тощий молодой человек в кожаной куртке и бандане пытается выследить любого, кого можно ограбить.}
{4570}{}{Бандитская разведчица}
{4571}{}{Молодая женщина в кожаной куртке и бандане пытается выследить любого, кого можно ограбить.}
{4580}{}{Бандит-ветеран}
{4581}{}{Ветеран бандитов в плаще и нескольких патронташах с пулями, что придает ему опасный вид.}
{4590}{}{Бандит-ветеран}
{4591}{}{Бандит-ветеран в плаще и нескольких патронташах, набитых пулями, что придает ей опасный вид.}
{4600}{}{Бандитская мразь}
{4601}{}{Плохо одетый бандит. На его теле множество странных татуировок, придающих ему причудливый вид.}
{4610}{}{Бандитская мразь}
{4611}{}{Плохо одетый бандит. На ее теле множество странных татуировок, а волосы выкрашены в зеленый цвет, что делает ее похожей на псих.}

# MERCENARIES
{4700}{}{Наемник}
{4701}{}{У него есть свое мнение на любой счет, и свинцовые аргументы.}
{4710}{}{Наемнца}
{4711}{}{Всем своим видом она дает понять, что с ней лучше не связываться.}
{4720}{}{Наемник-ветеран}
{4721}{}{Статный мужчина с серьезным взглядом, обладатель крупной челюсти и развитой мускулатуры.}
{4730}{}{Наемнца-ветеран}
{4731}{}{Молодая девушка с короткой стрижкой каре и длинными сильными ногами.}
{4740}{}{Командир Наемников}
{4741}{}{У него множество нашивок с наименованиями штатов на плече.}
{4750}{}{Командир Наемников}
{4751}{}{Прожженная многочисленными стычками валькирия Пустоши.}
{4760}{}{Охотник за головами}
{4761}{}{Не шибко отличается от обычного отъявленного головореза. Хотя все зубы на месте.}
{4770}{}{Охотнца за головами}
{4771}{}{Она все время наготове. Всегда. Даже сейчас.}
{4780}{}{Опытный охотник за головами}
{4781}{}{Многочисленные трофеи украшают его обмундирование.}
{4790}{}{Опытная охотница за головами}
{4791}{}{Решительные движения лица, загорелое лицо, выдают в ней опытную путешественницу.}
{4800}{}{Охотник за головами-ветеран}
{4801}{}{Смотрит на людей, как на мишень.}

# SLAVERS
{4900}{}{Работорговец-стрелок}
{4901}{}{Заурядный молодой человек с татуированным лбом и грязной шеей.}
{4910}{}{Работорговка-стрелок}
{4911}{}{Её татуировку работорговца явно делал какой-то бездарь.}
{4920}{}{Работорговец-ветеран}
{4921}{}{Крупный мужчина средних лет с перстнями на руках.}
{4930}{}{Работорговка-ветеран}
{4931}{}{Лицо украшено шрамами, а взгляд полон уверенности и сдержанной силы.}
{4940}{}{Крутой Работорговец}
{4941}{}{Опытный загонщик, на поясе висят скальпы поверженных дикарей.}
{4950}{}{Крутая Работорговка}
{4951}{}{Татуированная девушка с вредной ухмылкой, выглядит поддатой и расслабленной.}
{4960}{}{Лидер Работорговцев}
{4961}{}{Хорошо одетый и ухоженный мужчина с вальяжными повадками и татуировкой.}
{4970}{}{Командир Работорговцев}
{4971}{}{Женщина в высоких ботинках, с кнутом за пазухой и татуировкой.}

# SLAVES
{5100}{}{Слабый Раб}
{5101}{}{Слабый и худощавый раб, за такого много денег не выручить.}
{5110}{}{Слабая Рабыня}
{5111}{}{Истощенная от работы и недоедания невольница.}
{5120}{}{Раб}
{5121}{}{Раб, который провел немало времени в цепях.}
{5130}{}{Рабыня}
{5131}{}{Свыкшаяся с жизнью невольницы девушка.}
{5140}{}{Сильный Раб}
{5141}{}{Крепкий и мускулистый раб, не чурающийся тяжелого инструмента.}
{5150}{}{Сильная Рабыня}
{5151}{}{Жилистая и сильная рабыня, с такой шутки плохи.}

# HOMELESS
{5800}{}{Мусорщик}
{5801}{}{Одежда с характерными ржавыми пятнами, изрядно подрана от шастанья по руинам.}
{5810}{}{Мусорщица}
{5811}{}{Женщина с опустевшим взглядом, она знавала и лучшие времена.}
{5820}{}{Изгой}
{5821}{}{Этого несчастного оборванца уже сложно чем-то заинтересовать.}
{5830}{}{Бродяжка}
{5831}{}{Взгляд понурый, это явно не первая остановка на ее пути.}
{5840}{}{Странник}
{5841}{}{Типичный бродяга постядерной Пустоши.}
{5850}{}{Торчок}
{5851}{}{Он уже определился со своим местом в жизни.}
{5860}{}{Бездомный}
{5861}{}{Уже не разобрать, чем раньше была его одежда.}
{5870}{}{Бездомная}
{5871}{}{Одета в лохмотья, не сказать что ее это сильно беспокоит.}
{5880}{}{Беспризорник}
{5881}{}{Чумазый и неприхотливый.}
{5890}{}{Беспризорница}
{5891}{}{Весь мир для нее игра.}
{5900}{}{Обыватель}
{5901}{}{Ничем не примечателен, поглядывает по сторонам, не ожидая ничего хорошего.}
{5910}{}{Обывательница}
{5911}{}{Этот день для нее ничем не отличается от другого.}
{5920}{}{Барыга}
{5921}{}{Обладатель липкого и оценивающего взгляда.}

#ROBOTS
{6000}{}{Робомозг}
{6001}{}{Очень продвинутый робот, использующий в качестве процессора органический мозг.}
{6010}{}{Робоглаз}
{6011}{}{Небольшая плавучая машина, вооруженная лазерным оружием. Очень быстрый и ловкий.}
{6020}{}{Мистер Хэнди}
{6021}{}{Двигаясь с помощью двигателя с несколькими глазами и еще большим количеством рук, этот робот обычно использовался семьями в США и не только.}
{6030}{}{Сторожевой бот}
{6031}{}{Сверхмощный военный робот, обычно вооруженный миниганом и ракетной пусковой установкой. Из-за своего веса он довольно медленный.}
{6040}{}{Сторожевой бот}
{6041}{}{Сверхмощный военный робот, обычно вооруженный миниганом и ракетной пусковой установкой. Из-за своего веса он довольно медленный. Этот покрыт серой краской.}
{6050}{}{Сторожевой бот}
{6051}{}{Сверхмощный военный робот, обычно вооруженный миниганом и ракетной пусковой установкой. Из-за своего веса он довольно медленный. Его синяя краска делает его хорошо заметным.}
{6060}{}{Кибер-собака}
{6061}{}{Кибернетически усовершенствованная собака с острыми металлическими когтями и сильным телом, защищенным металлическим покрытием.}
{6070}{}{Протектрон}
{6071}{}{Широко распространенный робот с основной директивой защищать и служить. Он предназначен для общественного пользования, но все равно представляет собой опасную машину.}
{6080}{}{Протектрон}
{6081}{}{Широко распространенный робот с основной директивой защищать и служить. Он предназначен для общественного пользования, но все равно представляет собой опасную машину.}

#TURRETS
{6200}{}{Лазерная турель}
{6201}{}{Роботизированная система защиты.}
{6210}{}{Лазерная башня}
{6211}{}{Роботизированная система защиты.}
{6220}{}{Плазменная турель}
{6221}{}{Роботизированная система защиты.}
{6230}{}{Башня Гатлинга}
{6231}{}{Роботизированная система защиты.}

#-------------------------------------------------------------------
#FORP - Critters
#-------------------------------------------------------------------
#RIVERDALE NPC
{8000}{}{Снайпер Саула}
{8001}{}{Хладнокровный боец дальнего боя. Первым делом вы познакомитесь с её пулей, нежели с ней. На лбу метка работорговца.}
{8010}{}{Наёмник Моргана}
{8011}{}{Профессиональный боец Моргана. Очевидно, обилие его шрамов и отметин на оружии - не от спокойной жизни.}
{8020}{}{Наёмница Моргана}
{8021}{}{Опытная наёмница, посвятившая свою жизнь работе на "случайный кошелёк", а после - на Моргана.}
{8030}{}{Стальной Ромул}
{8031}{}{Высокий, сильный мужчина с седоватыми длинными волосами. Вместо левой руки, от локтя идёт металлический протез.}
{8040}{}{Жирный Морган}
{8041}{}{Очень толстый мужчина в официальной одежде, но что странно - гавайской рубашке под жилетом. По его виду легко понять, что ценит он в людях лишь личную выгоду.}
{8050}{}{Саул}
{8051}{}{Накачанный, большой негр в металлической броне. Его холодный взгляд подсказывает, что он здесь главный. На лбу видна большая метка работорговцев.}
{8100}{}{Лита}
{8101}{}{Крайне накаченная девушка с ярким кислотным ирокезом. На её броне видно множество зарубок, а на щеке имеются старые шрамы.}
{8110}{}{Никки}
{8111}{}{Небрежная прическа в фиолетовых тонах, множество татуировок по всему телу, а так же вычищенная броня до блеска. Девушка выглядит крайне расслабленно.}
{8120}{}{Псарь Дюк}
{8121}{}{Взрослый мужик в плотной куртке с потрепанными рукавами. На брови виднеется шрам, а от одежды пахнет собаками.}
{8130}{}{Мишлен}
{8131}{}{Девушка среднего роста с аккуратными руками. Одежда слегка приоткрыта, а на лице держится хитрая улыбка.}
{8140}{}{Дайрон}
{8141}{}{Крепкий мужчина в зеркальной металлической броне. Миниган на его спине не предвещает ничего добродушного.}
{8150}{}{Найра}
{8151}{}{Острый взгляд, хищный оскал и крепкое телосложение. Девушка явно повидала многое и уверенно повидает столько же.}
{8160}{}{Себастиан}
{8161}{}{Деловой мужчина в огнеупорной броне. На лице задумчивая мина, изредка сменяющаяся на нейтральную.}
{8170}{}{Реджи}
{8171}{}{Спокойный мужчина азиатской наружности. На куртке видны какие-то зарубки.}
{8180}{}{Жан}
{8181}{}{Мужчина в деловом костюмы и с густыми длинными усами. Выглядит напыщенно. От него веет странным ощущением чего-то инородного.}
{8190}{}{Освальд}
{8191}{}{Крепкий мужчина с множеством мешочков и сумок на его плечах и ногах. Кажется, он кого-то ждёт.}
{8200}{}{Шерри}
{8201}{}{Взрослая девушка с короткой прической и несколькими шрамами на губе. Её камуфляжная броня выглядит запачканной.}

#ROBOTS
{9000}{}{Робомозг}
{9001}{}{Многоцелевой кибернетический организм, в качестве процессора которого используется мозг животного или человека.}
{9010}{}{Робоглаз}
{9011}{}{Вооружённый парящий робот. Как правило, несёт ремонтные или охранные функции.}
{9020}{}{Помощник}
{9021}{}{Пользующаяся огромной популярностью в довоенных США серия домашних и рабочих роботов.}
{9030}{}{Робот охранник}
{9031}{}{Довоенная боевая еденица. Имеет систему распознавания «свой-чужой». Вооружены тяжёлым оружием но испытывают недостаток мобильности.}

#Riverdale NPC
{9040}{}{Лазерная турель}
{9041}{}{Роботизированная защитная система.}
{9050}{}{Лазерная башня}
{9051}{}{Роботизированная защитная система.}
{9060}{}{Плазменная турель}
{9061}{}{Роботизированная защитная система.}
{9070}{}{Гатлинг-пушка}
{9071}{}{Роботизированная защитная система.}

#SANDBOX NPC
{9500}{}{Дюбридж Ли Эрвин}
{9501}{}{Старая, залатанная во всех возможных местах и укрепленная кусками сырой браминей кожи, роба опоясывает такого же истертого временем пожилого человека.}
{9510}{}{Маркус Голдман}
{9511}{}{Бронзовый загар и литые мышцы говорят о том, что этот невысокий мужичок даст фору самым удалым армреслерам из Брокен-Хиллс.}
{9520}{}{Стивен Барр}
{9521}{}{Постоянно жует какой-то сорт жевательного табака, сплевывая попадающиеся комки в сторону, после чего, как ни в чем не бывало, продолжает улыбаться, обнажая слегка пожелтевшие, но ровные зубы.}
{9530}{}{Сэт Сэйл}
{9531}{}{Определенно мастер своего дела, тщательно подобранная экипировка которого сразу же выдает в нем его род занятий - мощная кожаная праща на поясе, заточенное копье за спиной и милая накидка на плечах из дубленой кожи огнедышащего геккона.}
{9540}{}{Эндрю Мэллон}
{9541}{}{Одет в лохмотья караванщика с кучей нацепленных на них армейский разгрузок. Пахнет керосином.}
{9550}{}{Раймонд Тайер}
{9551}{}{На поясе у этого древнего гуля затянут ремень с кучей подручных инструментов. Также как заядлый курильщик всегда держит в зубах сигарету, он сжимает в руке старый, потертый мультитул.}
{9560}{}{Карл Ругер}
{9561}{}{Если бы техническое масло было парфюмом, этот далеко не гладкокожий парень был бы законодателем моды. Опоясан старым кузнечным фартуком.}
{9570}{}{Сэмуэль Сакс}
{9571}{}{Удивительное отличие этого гуля от всех других - сохранившиеся клочки седых волос на скупо обтянутой кожей голове.}
{9580}{}{Вексельберг}
{9581}{}{Гуль, выдающейся чертой которого являются крупные кузнечные перчатки, которые очень смешно смотрятся на его тщедушных, но очень жилистых ручонках.}
{9590}{}{Честер}
{9591}{}{Чудовище столь огромных размеров, что рядом с ним небо кажется мелким и незначительным элементом пейзажа.}
{9600}{}{Дэвид «Лапша» Ааронсон}
{9601}{}{Высокого роста гуль с накинутым на грудь легким брнежилетом. Постоянно осматривается по сторонам, медленно проводя по окрестностям своим дымным взглядом}
{9610}{}{Максимилиан «Макс» Беркович}
{9611}{}{Гуль, у которого всё ещё сохранился нос, придающий ему более менее человеческий облик. Одет в грязный комбинезон, подвязанный ремнем с нацепленной на него различной боевой снарягой.}
{9620}{}{Патрик «Простак» Голдберг}
{9621}{}{Пузатый гуль, носящий соломенную шляпу. Жует что-то, размеренно и раздражающе почавкивая.}
{9630}{}{Филипп «Косой» Штейн}
{9631}{}{Отличительная особенность этого гуля в сильной разнице уровня глаз. Левый глаз совсе замутнен, а правый же, наоборот, сохранил человеческое выражение и глубину мысли.}
{9640}{}{Малыш Доминик}
{9641}{}{Миниатюрный паренек. Его можно было бы назвать славным малым, если бы не тот факт, что это мерзкий, отвратительный и крайне вонючий гуль.}
{9650}{}{Элис}
{9651}{}{Очень крутая, но выглядящая миролюбиво, охотница.}
{9660}{}{Чейз, лидер шахтеров}
{9661}{}{Коренастый парень в довольно чистой одежде. По его рукам видно, что ему приходилось работать на шахте старателем.}
{9670}{}{Линкольн, караванщик}
{9671}{}{Пыльный плащ, драные сапоги, разношенная кобура... сразу видно - бывалый путешественник.}
{9680}{}{Сара, кладовщик шахтеров}
{9681}{}{Девушка лет тридцати, приятной наружности. По её загарелой коже нельзя сказать, что она много времени провела в шахтах.}
{9690}{}{Страйк}
{9691}{}{Парень с самодовольным видом и зубочисткой во рту. Он так занят своими колодами карт, что ничего вокруг не замечает.}
{9700}{}{Лана}
{9701}{}{Молодая девушка весьма привлекательного вида с аппетитными формами и игривым взглядом.}
{9710}{}{Роджер, торговец}
{9711}{}{Парень средних лет, одет в пыльную куртку с заплатками. Выглядит как типичный торгаш.}
{9720}{}{Мей, представитель "Красного Рассвета"}
{9721}{}{Девушка в кожаной броне со значком организации "Красный Рассвет".}
{9730}{}{Джессика Роуман}
{9731}{}{Девушка с веснушками и ровной челкой. Очки на её лице добавляют ей важности, что нельзя сказать о её потрепанном костюме}

#RIVERDALE NPC
{9740}{}{Сьюзи}
{9741}{}{Молодая девушка со светлыми волосами, очень красивая}
{9750}{}{Терминал}
{9751}{}{Машина по выдаче талонов.}
{9760}{}{Сэт}
{9761}{}{Сурового вида траппер. Один глаз закрыт повязкой. Кажется вы его уже видели где-то, или нет...}
{9770}{}{Варг}
{9771}{}{Огромный лохматый пес, он величественнен и спокоен.}
{9780}{}{Гери}
{9781}{}{Поджарый рыжий волчара, лучше не поворачиваться к нему спиной.}
{9790}{}{Фреки}
{9791}{}{Это судя по всему сука, однако зубы у нее не уступают любому кобелю.}
{9800}{}{Рей Свонсон}
{9801}{}{К кому вы пойдете когда вам будет так плохо что хоть помирай? Правильно, к доктору. Это он.}
{9810}{}{Фрэд Бобкэт}
{9811}{}{С виду обыкновенный житель трущоб, правда глаза у него какие-то "затуманенные".}
{9820}{}{Эйб Цукерман}
{9821}{}{Пожилой мужчина, сухого телосложения.}
{9830}{}{Крупье казино}
{9831}{}{Очень красивая и сексуальная девушка. На шее красивое ожерелье, а на ногах милые балетки.}
{9840}{}{Охранник казино}
{9841}{}{Рослый парень с протокольной рожей, он внимательно следит за вами. Когда вы подходите ближе, он улыбается вам, разумеется из вежливости.}
{9850}{}{Заядлый торчок}
{9851}{}{Горбатый наркоман, явно смотрящий на вас с немым вопросом.}
{9860}{}{Проститутка}
{9861}{}{Потасканная женщина, которую явно проведали многие.}
{9870}{}{Ганди}
{9871}{}{Крепкий наёмник с небольшой улыбкой на лице. Он выглядит молодо.}
{9880}{}{Трэвор}
{9881}{}{Высокий и молодой парень, строго осматривающийся вокруг.}
{9890}{}{Селестия}
{9891}{}{Молодая девушка со шрамом на шее. Через всю грудь проходит патронташ, заполненный патронами.}
{9900}{}{Забавный толстяк}
{9901}{}{Странный мужичок, медленно поглаживающий своё выпирающее пузо.}
{9910}{}{Базил}
{9911}{}{Крупный мужчина в бронежилете, вечно что-то записывающий в свою тетрадь.}
{9920}{}{Льюис}
{9921}{}{Деловой парень в металлической броне. Кажется, он кого-то ждёт.}
{9930}{}{Гарфилд}
{9931}{}{Высокий, лысый мужик. Он смотрит на вас с неким нетерпением.}
{9940}{}{Салли}
{9941}{}{Молодая, ухоженная девушка. Она явно кого-то ожидает и мягко улыбается.}
{9950}{}{Отморозок Ромула}
{9951}{}{Отбитый боец Ромула, готовый ввязаться в драку, даже если это было не нужно.}
{9960}{}{Бандит Ромула}
{9961}{}{Опасный "цепной пёс" синдиката, готовый выполнить любую грязную работу.}
{9970}{}{Головорез Ромула}
{9971}{}{Кровожадный убийца, каким-то чудом находящийся на службе у Ромула.}
{9980}{}{Стрелок Саула}
{9981}{}{Умелый боец-работорговец в бронежилете. Его строгий взгляд подсказывает, что с пустыми разговорами к нему лучше не подходить. На лбу метка работорговца.}
{9990}{}{Надсмотрщик Саула}
{9991}{}{Наблюдатель за рабами с множеством старых шрамов и тяжелым взглядом. На лбу метка работорговца.}

#RATS
{10000}{}{Детеныш крысы}
{10001}{}{Довольно мелкая тварь.}
{10010}{}{Мелкая крыса}
{10011}{}{Непропорционально большие клыки и красные глаза.}
{10020}{}{Средняя крыса}
{10021}{}{С её клыков обильно течёт слюна.}
{10030}{}{Облученная крыса}
{10031}{}{Она светится и на ней почти нет шерсти.}
{10040}{}{Огромный крыс}
{10041}{}{Этот злобный грызун может легко допрыгнуть до вашего лица.}
{10050}{}{Крыса-мутант}
{10051}{}{Матерая злая тварь размером с небольшую собаку.}

#MANTIS
{10300}{}{Жалкий мантис} 
{10301}{}{Мелкое и противное насекомое с длинными лапками.} 
{10310}{}{Мантис} 
{10311}{}{Среднее тельце с длинными лапками, способными заколоть вас досмерти. } 
{10320}{}{Огромный мантис} 
{10321}{}{Огромное насекомое с не менее внушительными клешнями и массивным тельцем. Голова хаотично ходит в разные стороны.}
{10330}{}{Мантис вожак}
{10331}{}{Громадный и исключительный представитель мантисов. Внушительные крылья и вечно агрессивно клацающие клешни.}

#ANTS
{10600}{}{Муравей-рабочий}
{10601}{}{Небольшое существо, вечно виляющее на ходу.} 
{10610}{}{Муравей-солдат} 
{10611}{}{Крупное существо, среднего размера лапы и длинные усики. Внушительные жвалы плавно двигаются.} 
{10620}{}{Муравей-трутень} 
{10621}{}{Этот здоровенный муравей выглядит особенно мерзко и габаритно. Тело непропорционально большое, отчего он выглядит неприятно.} 
{10630}{}{Муравей-охранник} 
{10631}{}{Это Альфа-самец: его панцирь выглядит очень толстым, а пасть огромной. Мощные лапы, длинные жвалы и огромные глазища.}

#SPOREPLANTS
{10900}{}{Хищное растение} 
{10901}{}{Странная, безглазая пасть держится на толстом стебле.} 
{10910}{}{Огромное хищное растение} 
{10911}{}{Громадная безглазая пасть с многочисленными отростками по сторонам. Стебель покрыт шипами, а само растение крайне высокое.} 

#BRAHMINS
{11200}{}{Слабый брамин} 
{11201}{}{Небольшой и слабенький брамин. Выглядит тощим и изголодавшимся.} 
{11210}{}{Брамин} 
{11211}{}{Две головы, четыре копыта и одно большое брюхо. У одной из голов имеются рога.}
{11220}{}{Большой Брамин} 
{11221}{}{Крупный брамин с массивными головами и телом.}
{11230}{}{Дикий брамин} 
{11231}{}{Худой и потрепанный брамин. Тело брамина истрёпано дикой природой.} 
{11240}{}{Яростный брамин} 
{11241}{}{Крупный брамин с тёмным окрасом. Рога длиннее, чем у обычного брамина, а копыта выглядят массивнее.}

#DOGS
{11500}{}{Слабая собака} 
{11501}{}{Тощее животное, по телу видны рёбра и следы долгого голодания. Шерсть поредела.} 
{11510}{}{Собака} 
{11511}{}{Обычная дворняга средних размеров.} 
{11520}{}{Матёрая собака} 
{11521}{}{Множество старых шрамов и ранений, дают понять, что этот пёс через многое прошёл.} 
{11530}{}{Большая собака} 
{11531}{}{Крупная собака с грубой и диковатой мордой. С клыков стекают слюни, а на лапах видна грязь.}
{11540}{}{Щенок} 
{11541}{}{Маленькое создание с мелкими лапками, длинной мордочкой и короткой шерсткой.}

#WOLFES
{11800}{}{Слабый волк} 
{11801}{}{Небольшое существо, чем-то напоминающее собаку. Редкая шерсть, небольшие клыки и когти на лапах. Выглядит истощенным.} 
{11810}{}{Волк} 
{11811}{}{Среднего размера существо. Хорошая шкура, крепкое телосложение, длинная и вытянутая морда с острыми зубами в пасти.} 
{11820}{}{Матёрый волк} 
{11821}{}{Потрёпанный жизнью волк. На шкуре видны множественные шрамы, на лапах запекшаяся кровь.} 
{11830}{}{Вожак стаи волков} 
{11831}{}{Огромный и старый волк. Крупное телосложение и крайне длинные когти и зубы дают понять, что он прожил многое. По шкуре волка наблюдается обилие старых шрамов и относительно свежих ран.} 
{11840}{}{Щенок} 
{11841}{}{Маленькое создание с мелкими лапками, длинной мордочкой и серой шерсткой. Наличие острых клыков выдает в нём щенка волка.}

#PIG RATS
{12100}{}{Свинокрыс} 
{12101}{}{Он издаёт звуки, напоминающие писк и хрюканье в одном. Маленькая противная тушка на когтистых лапках.} 
{12110}{}{Огромный свинокрыс} 
{12111}{}{Громадная мясистая туша на мускулистых лапищах с когтями и острыми зубищами в пасти.} 
{12120}{}{Свинокрыс альфа-особь} 
{12121}{}{Невероятно большой и мускулистый свинокрыс. По его телу видно обилие неприятных шрамов и старых ранений.} 

#MOLE RATS
{12400}{}{Кротокрыс} 
{12401}{}{Небольшое животное на четырех лапах с когтями и острыми зубами. На морде и хвосте видны длинные усики.} 
{12410}{}{Огромный кротокрыс} 
{12411}{}{Огромный и крайне мясистый зверь. Вся кожа в складках тёмно-розового цвета.} 
{12420}{}{Кротокрыс-вожак} 
{12421}{}{Громадный кротокрыс с особенно длинными когтями. Зубы крайне острые и большие, а на теле видны многочисленные шрамы.} 

#SILVER GECKOS
{12700}{}{Серебряный гекко} 
{12701}{}{Небольшой серебристый геккон. Маленькие лапки на относительно большом тельце.} 
{12710}{}{Серебряный хищный гекко} 
{12711}{}{Жилистый геккон с длинным хвостом. В пасти видны частые и очень острые зубы.} 
{12720}{}{Крупный серебряный гекко} 
{12721}{}{Очень большой геккон, по сравнению с его собратьями. Длинные лапы с опасными когтями, переливающаяся шкурка.} 
{12730}{}{Серебряный гекко альфа-особь} 
{12731}{}{Самый большой серебряный геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются мелкие шипы.} 

#GOLDEN GECKOS
{13000}{}{Золотой гекко} 
{13001}{}{Маленький и юркий золотой гекко. Мелкий хвостик вечно двигается в такт походке.} 
{13010}{}{Крупный золотой гекко} 
{13011}{}{Большое существо с длинным хвостом и острыми зубами. Его золотая шкурка красиво переливается на солнце.} 
{13020}{}{Золотой гекко альфа-особь} 
{13021}{}{Самый большой золотой геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются частые рубцы и шрамы.} 

#FIREGECKOS
{13300}{}{Огненный гекко} 
{13301}{}{Небольшой, но крайне красочный зверь. Из ноздрей твари исходит легкий дымок.} 
{13310}{}{Огненный гекко альфа-особь} 
{13311}{}{Крайне крупный огненный гекко с внушительным телосложением и целым "фонтаном" дыма, выходящим из его ноздрей. Пасть вечно открывается, выпуская на волю струйки огня.} 

#SCORPS
{13900}{}{Радскорпион}
{13901}{}{Скорпион среднего размера. С хвоста и жала капает яд. Массивные клешни и быстрые ноги.}
{13910}{}{Крутой радскорпион}
{13911}{}{Большой скорпион с большим опухшим жалом. Крепкий и массивный панцирь.}
{13920}{}{Малый радскорпион}
{13931}{}{Маленький скорпион с не очень впечатляющими клешнями и маленьким хвостом.}

#BLACKSCORPS
{14200}{}{Мелкий чёрный радскорпион} 
{14201}{}{Малый скорпион с длинным хвостом и чёрным панцирем.} 
{14210}{}{Чёрный радскорпион} 
{14211}{}{Крупный чёрный скорпион с толстым панцирем и массивным свисающим хвостом. Жало твори сочится ядом.} 

#DEATHCLAWS
{14500}{}{Детёныш Когтя смерти} 
{14501}{}{Маленькое гуманоидное существо с длиннющими лапами, из которых виднеются острые когти.} 
{14510}{}{Молодой Коготь смерти} 
{14511}{}{Среднего размера существо со светлой шерстью и небольшими рожками.} 
{14520}{}{Крупный Коготь смерти} 
{14521}{}{Большая и мускулистая страшная тварь. Длинные и крайне острые когти на лапах. Жёлтые и изогнутые клыки.} 
{14530}{}{Коготь смерти альфа-особь} 
{14531}{}{Громадный коготь-смерти с длинными изогнутыми рогами и обилием шрамов на всему телу. Потемневший окрас и громоздкие лапы.} 
{14540}{}{Коготь смерти охотник} 
{14541}{}{Огромный коготь-смерти серого окраса. Изогнутое тело, могучие лапы и изогнутые рога, нацеленные вперёд.} 

#SWAMPLURKERS
{14800}{}{Слабый болотник} 
{14801}{}{Небольшое существо в толстом панцире и массивными клешнями.} 
{14810}{}{Болотник} 
{14811}{}{Вонючая, большая и громоздкая тварь, покрытая цельным крепким панцирем. Острые клешни выглядят крайне опасно и остро.} 
{14820}{}{Вожак болотников} 
{14821}{}{Невероятно массивный и крепкий, исключительный болотник. Его громадный панцирь покрыт болотными отходами и обилием водорослей.} 

#ALIENS
{15100}{}{Странное яйцо} 
{15101}{}{Странное, округлое яйцо неизвестного происхождения.} 
{15110}{}{Ванаминго} 
{15111}{}{У этой твари нет ни глаз, ни пальцев. Из тела выходят мерзкие длинные безкостные щупальца.} 
{15120}{}{Крупный ванаминго} 
{15121}{}{Большая и страшная безглазая тварь с длинными мерзкими щупальцами.} 

#MOTERALIENS
{15400}{}{Матка ванаминго} 
{15401}{}{Матка ванаминго. С пасти здоровенного ванаминго течёт слизь, а блестящая шкура имеет тёмно-серый оттенок.} 

#FLOATERS
{15700}{}{Мелкий летатель} 
{15701}{}{Маленькое змееподобное нечто, медленно ползущее на хвосте. Вместо лица у существа есть подобие большого рта.} 
{15710}{}{Летатель} 
{15711}{}{Безобразная тварь с огромным, полным зубов горизонтальным ртом.} 
{15720}{}{Гадкий летатель} 
{15721}{}{Он мерзко воняет, а его передние рты обильно истекают слизью.} 
{15730}{}{Вожак летателей} 
{15731}{}{Огромный летатель с несколькими громадными ртами, полными обилием острых зубов в едкой слизи. Существо очень сильно воняет.} 

#CENTAURS
{16000}{}{Мелкий кентавр} 
{16001}{}{Небольшое, но крайне мерзкое создание. Передвигается на шести человеческих руках. На длинных шеях красуются разные обезображенные головы.} 
{16010}{}{Кентавр.} 
{16011}{}{С длинного щупальцеобразного языка течёт мутная слизь. Две обезображенные головы и нечто, похожее на кишки, свисающие из тела и волочащиеся следом.} 
{16020}{}{Гадкий кентавр} 
{16021}{}{Крайне неприятное зрелище. Существо с разными головами, обилием органов, находящихся снаружи. По телу течёт вязкая слизь.} 
{16030}{}{Альфа кентавр} 
{16031}{}{Громадный кентавр держится на десяти человеческих руках. Три уродливые головы и не менее обезображенное подобие тела.}

#PRIMITIVES
{16300}{}{Тощий дикарь} 
{16301}{}{Тощий дикарь. Этот дикарь похоже очень давно не ел.} 
{16310}{}{Тощая дикарка} 
{16311}{}{Тощая дикарка. Она похожа на обтянутый кожей скелет. Ну или на свеженького гуля.}
{16320}{}{Грязый дикарь} 
{16321}{}{Грязый дикарь. Этот похоже целыми днями копается в земле.}
{16330}{}{Перемазанная дикарка} 
{16331}{}{Перемазанная дикарка. Возможно глина на ее лице и волосах - это украшение.}
{16340}{}{Старейшина племени} 
{16341}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16350}{}{Старейшина племени} 
{16351}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16360}{}{Шаман племени} 
{16361}{}{Шаман племени. Множество амулетов и опьяненный вид намекаютвам, что перед вами сильный колдун.}
{16370}{}{Дикарь охотник} 
{16371}{}{Дикарь охотник. Вы когда нибудь видели траппера без штанов? Вот он.}
{16380}{}{Дикарка охотница} 
{16381}{}{Дикарка охотница. Она не так доступна как кажется.}
{16390}{}{Дикарь воин} 
{16391}{}{Дикарь воин. Сильный и ловкий, он будет защищать свое племя до последнего вздоха.}
{16400}{}{Дикарка воительница} 
{16401}{}{Дикарка воительница. Боевая раскраска, дикий оскал и голые сиськи, все как положено.}

#CANNIBALS & RIPPERS
{16600}{}{Мерзкий людоед} 
{16601}{}{Мерзкий людоед. Он смотрит на вас со злобой и голодом. Быстро шагает в Вашу сторону, громко принюхиваясь и пуская слюну.}
{16610}{}{Грязная людоедка} 
{16611}{}{Грязная людоедка. Она смотрит на вас голодным взглядом. Её волосы взъерошены, некоторые зубы отсутствуют.}
{16620}{}{Бородатый людоед} 
{16621}{}{Бородатый людоед. Он жадно смотрит на вас. Этот пидор собирается вас сожрать!}
{16630}{}{Сумасшедший людоед} 
{16631}{}{Сумасшедший людоед. Его взгляд бегает по округе. Он клацает зубами, топчась на земле.}
{16640}{}{Фермер-людоед} 
{16641}{}{Фермер-людоед. Он смотрит на вас голодными глазами. Его комбинезон заляпан кровью, а соломенная шляпа кем-то надкусана.}
{16650}{}{Голодный людоед} 
{16651}{}{Голодный людоед. Он смотрит на вас голодными глазами. С его рта течёт слюна, а рёбра заметно проступают под кожей.}
{16660}{}{Рабыня-людоедка} 
{16661}{}{Рабыня-людоедка. Она смотрит на вас голодным взглядом. На её шее висит сломанный ошейник.}
{16670}{}{Лысый каннибал} 
{16671}{}{Лысый каннибал. Он злобно смотрит на вас. От его красной макушки исходит пар, видимо, там он кусочек Вашей ноги и зажарит.}
{16680}{}{Фермерша-людоедка} 
{16681}{}{Фермерша-людоедка. Она смотрит на вас голодным взглядом. На её фартуке кровью написано МЯСО.}
{16690}{}{Странный парень} 
{16691}{}{Странный парень. Его лицо скрыто капюшоном. Рваная роба имеет участки с засохшей кровью.}
{16700}{}{Китаец-каннибал} 
{16701}{}{Китаец-каннибал. Он смотрит вас, как на свежую рыбу. К жилетке и штанам прикреплены ножи разных размеров.}
{16710}{}{Странный нигер} 
{16711}{}{Странный нигер. Он негромко хрипит. С его рта стекает кровь, а зрачки почему-то закатились вверх.}
{16720}{}{Здоровый каннибал} 
{16721}{}{Здоровый каннибал. Он смотрит на вас, пуская кровавые слюни. Похоже, он даже рычит.}
{16730}{}{Бледный каннибал} 
{16731}{}{Бледный каннибал. Он смотрит на вас голодными глазами. Его кожа почти что белая, очень странно для обитателя Пустоши.}
{16740}{}{Мутированный каннибал} 
{16741}{}{Мутированный каннибал. Он смотрит на вас голодным взглядом. Половина его головы гниёт заживо, другая половина полна гнойных наростов.}
{16750}{}{Мелкий каннибал} 
{16751}{}{Мелкий каннибал. Он смотрит на вас голодными глазами. Этот мелкий пидор, по всей видимости, питается человечиной.}
{16760}{}{Симпатичная людоедка} 
{16761}{}{Симпатичная людоедка. Она смотрит на вас голодным взглядом. Одежда на ней уже полностью изношена, из-за чего хорошо видна её большая грудь.}
{16770}{}{Жирная людоедка} 
{16771}{}{Жирная людоедка. Она смотрит на вас со зловещей улыбкой. Её одежда сшита из разных шкур, а на них нарисованы загадочные символы из крови.}
{16780}{}{Престарелый каннибал} 
{16781}{}{Престарелый каннибал. Он смотрит на вас хладнокровно. Седовласый старик жуёт собственные губы.}
{16790}{}{Ловчий потрошителей} 
{16791}{}{Ловчий потрошителей. Похоже, что вы нужны ему живым.} 
{16800}{}{Ловчая потрошителей} 
{16801}{}{Ловчая потрошителей. Ловкая и быстрая. Похоже, что она не прочь с вами "позабавиться".}
{16810}{}{Потрошитель-забойщик} 
{16811}{}{Потрошитель-забойщик. Крепко сложен. Его рот искривлен в плотоядной ухмылке.}
{16820}{}{Потрошитель-забойщик} 
{16821}{}{Потрошитель-забойщик. Сильная женщина. Ее лицо испачкано кровью. Судя по всему это не ее кровь.}
{16830}{}{Потрошитель-свежеватель} 
{16831}{}{Потрошитель-свежеватель. Агрессивно настроенный представитель племени потрошителей.}
{16840}{}{Потрошитель-свежеватель} 
{16841}{}{Потрошитель-свежеватель. Полуобнаженная женщина. Хищно смотрит на вас.}
{16850}{}{Потрошитель-воин} 
{16851}{}{Потрошитель-воин. Его торс увешен украшениями из костей поверженных врагов.}
{16860}{}{Воительница потрошителей} 
{16861}{}{Воительница потрошителей. Ее взгляд затуманен жаждой крови.}
{16870}{}{Потрошитель жрец } 
{16871}{}{Потрошитель жрец. Его шею украшает ожерелье из фаланг человеческих пальцев.}
{16880}{}{Патриарх потрошителей} 
{16881}{}{Патриарх потрошителей. Высокий и властный мужчина. Его лицо украшают ритуальные шрамы. Остальные потрошители смотрят на него как на живого бога.}
{16890}{}{Матриарх потрошителей} 
{16891}{}{Матриарх потрошителей. Крепко сложенная женщина в одежде из человеческой кожи. Другие потрошители почтительно опускают глаза в ее присутствии.}

#GANGS
{16900}{}{Торчок} 
{16901}{}{Торчок. Наркоман, его руки дрожат, а глаза бегают.} 
{16910}{}{Наркоманка} 
{16911}{}{Наркоманка. Судя по ее отсутствующему взгляду - она уже давным давно готова на что угодно ради дозы.}
{16920}{}{Отребье} 
{16921}{}{Отребье. Оборванец, который пытается жить за чужой счет.}
{16930}{}{Шмара} 
{16931}{}{Шмара. Отсутствие принципов - вот ее главный принцип!}
{16940}{}{Мелкая шпана} 
{16941}{}{Мелкая шпана. Он не постесняется лишить вас кошелька, а за одно и жизни.}
{16950}{}{Мелкая шпана} 
{16951}{}{Мелкая шпана. Она уже давно привыкла играть по правилам пустоши.}
{16960}{}{Плут} 
{16961}{}{Плут. Мелкий воришка.}
{16970}{}{Плутовка} 
{16971}{}{Плутовка. Остра на язык. И на заточку тоже остра!} 
{16980}{}{Подонок} 
{16981}{}{Подонок. Готов выпустить вам кишки за пару крышек.}
{16990}{}{Грабительница} 
{16991}{}{Грабительница. Беспринципная и очень опасная.}
{17000}{}{Отморозок} 
{17001}{}{Отморозок. Судя по всему этот психопат собирается пролить вашу кровь!}
{17010}{}{Отбитый} 
{17011}{}{Отбитый. Для него перерезать глотку ребенку как два пальца обоссать.}
{17020}{}{Авторитет} 
{17021}{}{Авторитет. Местный авторитет. Смотрит на вас как на говно.}
{17030}{}{Авторитет} 
{17031}{}{Авторитет. Местный авторитет. Смотрит на вас как на говно.}

#RAIDERS
{17200}{}{Рейдер мусорщик} 
{17201}{}{Рейдер мусорщик. Вы бы спутали с бродягой, если бы не направленное на вас оружие.}
{17210}{}{Рейдер мусорщик} 
{17211}{}{Рейдер мусорщик. Вы бы спутали с бродягой, если бы не направленное на вас оружие.} 
{17220}{}{Рейдер псих} 
{17221}{}{Рейдер псих. Отмороженная наглухо личность.}
{17230}{}{Рейдер псих} 
{17231}{}{Рейдер псих. Отмороженная наглухо личность.}
{17240}{}{Рейдер камикадзе} 
{17241}{}{Рейдер камикадзе. Он прямо просит что бы вы его пристрелили.}
{17250}{}{Рейдер камикадзе} 
{17251}{}{Рейдер камикадзе. Он прямо просит что бы вы его пристрелили.}
{17260}{}{Рейдер громила} 
{17261}{}{Рейдер громила. Не попадайтесь под его удары.}
{17270}{}{Рейдер громила} 
{17271}{}{Рейдер громила. Не попадайтесь под его удары.}
{17280}{}{Рейдер налетчик} 
{17281}{}{Рейдер налетчик. Рейдер или налетчик? Да какая разница!}
{17290}{}{Рейдер налетчик} 
{17291}{}{Рейдер налетчик. Рейдер или налетчик? Да какая разница!}
{17300}{}{Рейдер стрелок} 
{17301}{}{Рейдер стрелок. Вы на мушке.}
{17310}{}{Рейдер стрелок} 
{17311}{}{Рейдер стрелок. Вы на мушке.}
{17320}{}{Рейдер безумец} 
{17321}{}{Рейдер безумец. Этот рвется в бой в первых рядах. Выглядит очень опасным.}
{17330}{}{Рейдер безумец}
{17331}{}{Рейдер безумец. Этот рвется в бой в первых рядах. Выглядит очень опасным.}
{17340}{}{Элитный рейдер}
{17341}{}{Элитный рейдер. Элита своей банды.}
{17350}{}{Элитный рейдер}
{17351}{}{Элитный рейдер. Элита своей банды.}
{17360}{}{Рейдер профессионал}
{17361}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17370}{}{Рейдер профессионал}
{17371}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17380}{}{Рейдер профессионал}
{17381}{}{Рейдер профессионал. Такие обычно имеют за спиной мнжество битв.}
{17390}{}{Легендарный лидер рейдеров}
{17391}{}{Легендарный лидер рейдеров. Один из представителей легендарной банды "Ханы". Он очень силен.}

#SLAVERS
{17500}{}{Работорговец новичок}
{17501}{}{Работорговец новичок. Молодой парень с клеймом работорговца на лбу. Дёрганый мерзавец, который жаждет себя проявить.}
{17510}{}{Работорговец новичок}
{17511}{}{Работорговец новичок. Молодая девушка с клеймом работорговца на лбу. Дёрганая дрянь, которая жаждет себя проявить.}
{17520}{}{Работорговец бугай}
{17521}{}{Работорговец бугай. Крепкий мужик с клеймом работорговца на лбу. Он дерзко осматривал Вас, словно прицениваясь}
{17530}{}{Работорговец бугай}
{17531}{}{Работорговец бугай. Крепкий мужик с клеймом работорговца на лбу. Грязные руки, не чистая совесть и хищный взгляд выдают в нём «хорошего бизнесмена».}
{17540}{}{Работорговец стрелок}
{17541}{}{Работорговец стрелок. Судя по всему это один из «загонщиков» работорговцев.  Задача этого трапера выследить и поймать человека, желательно со всей семьёй.}
{17550}{}{Работорговец стрелок}
{17551}{}{Работорговец стрелок. Судя по всему это один из «загонщиков» работорговцев.  Задача этого трапера выследить и поймать человека, желательно со всей семьёй.}
{17560}{}{Работорговец ветеран}
{17561}{}{Работорговец ветеран. Опытный бандит с клеймом работорговца на лбу. Похоже, он знает цену каждому и Вам не хотелось бы быть в зоне его «интереса».}
{17570}{}{Работорговец ветеран}
{17571}{}{Работорговец ветеран. Опытная разбойница с клеймом работорговца на лбу. Похоже, она знает цену каждому и Вам не хотелось бы быть в зоне её «интереса».}
{17580}{}{Начальник работорговцев}
{17581}{}{Начальник работорговцев. Хорошо выглядящий бизнесмен с клеймом работорговца на лбу.  Он знает толк в «трудовых коллективах» и системе мотиваций.}
{17590}{}{Начальник работорговцев}
{17591}{}{Начальник работорговцев. Статного вида мужик с клеймом работорговца на лбу. Этот «Чёрный властелин» поломал не мало судеб.}

#CARAVANS
{17800}{}{Случайный попутчик}
{17801}{}{Случайный попутчик. Вас не отпускает чувство, что этого человека тут вообще быть не должно.}
{17810}{}{Случайный попутчик}
{17811}{}{Случайный попутчик. Вас не отпускает чувство, что этого человека тут вообще быть не должно.}
{17820}{}{Охранник каравана новичок}
{17821}{}{Охранник каравана новичок. Явно чувствует себя неуверенно.}
{17830}{}{Охранник каравана новичок}
{17831}{}{Охранник каравана новичок. Явно чувствует себя неуверенно.}
{17840}{}{Здоровый охранник каравана}
{17841}{}{Здоровый охранник каравана. Да это настоящий шкаф!}
{17850}{}{Здоровый охранник каравана}
{17851}{}{Здоровый охранник каравана. Да это настоящий шкаф!}
{17860}{}{Охранник каравана ветеран}
{17861}{}{Охранник каравана ветеран. Бывалого человека видно сразу.}
{17870}{}{Охранник каравана ветеран}
{17871}{}{Охранник каравана ветеран. Бывалого человека видно сразу.}
{17880}{}{Охранник каравана стрелок}
{17881}{}{Охранник каравана стрелок. Щурясь разглядывает местность.}
{17890}{}{Охранник каравана стрелок}
{17891}{}{Охранник каравана стрелок. Щурясь разглядывает местность.}
{17900}{}{Караванщик}
{17901}{}{Караванщик. Кажется, этот человек тут всеми руководит.}
{17910}{}{Караванщик}
{17911}{}{Караванщик. Кажется, этот человек тут всеми руководит.}

#STRANGERS
{18100}{}{Бездомный}
{18101}{}{Бездомный. Вонючий бродяга, которых полно на пустошах. Выглядит побитым, ведёт себя нервно.}
{18110}{}{Бездомная}
{18111}{}{Бездомная. Грязная женщина с забитым взглядом. От неё разит несчастьем.}
{18120}{}{Мусорщик}
{18121}{}{Мусорщик. Обычный собиратель. Он дёргано осматривается вокруг, ища то, чем можно поживиться.}
{18130}{}{Мусорщица}
{18131}{}{Мусорщица. Типичная собирательница. Она дёргано осматривается вокруг, ища то, чем можно поживиться.}
{18140}{}{Отброс}
{18141}{}{Отброс. Озлобленный оборванец, каких полно в любых трущобах. Он чем-то занят и старается на Вас не смотреть.} 
{18150}{}{Отброс}
{18151}{}{Отброс. Озлобленная оборванка, каких полно в любых трущобах. Она чем-то занята и старается на Вас не смотреть.}
{18160}{}{Охотник}
{18161}{}{Охотник. Бывалый трапер с обветренным лицом и характерным прищуром.}
{18170}{}{Охотница}
{18171}{}{Охотница. Бывалый трапер с обветренным лицом и характерным прищуром.}
{18180}{}{Бродяга}
{18181}{}{Бродяга. Обычный путник из пустошей.  Не понять, из каких мест он родом, но судя по рваной мешковине на нём – путь был долгим.}
{18190}{}{Бродяжка}
{18191}{}{Бродяжка. Обычная путница из пустошей.  Не понять, из каких мест она родом, но судя по рваной мешковине на ней – путь был долгим.}
{18200}{}{Изгой}
{18201}{}{Изгой. Вонючий бродяга, которых полно на пустошах. Этот выглядит больным, или просто урод.}
{18210}{}{Изгой}
{18211}{}{Изгой. Дряхлый старик, доживающий свой век. Жалкое зрелище.}
{18220}{}{Законник}
{18221}{}{Законник. Бывалый наёмник в крепкой амуниции. Вооружён и видимо опасен.}
{18230}{}{Законник}
{18231}{}{Законник. Бывалый наёмник в крепкой амуниции. Вооружён и видимо опасен.}

#GHOULS
{18400}{}{Хилый гуль}
{18401}{}{Хилый гуль. Кожа да кости. В прямом смысле.}
{18410}{}{Хилый гуль}
{18411}{}{Хилый гуль. Кожа да кости. В прямом смысле.}
{18420}{}{Облезлый гуль}
{18421}{}{Облезлый гуль. Из отвалившихся кусков кожи вполне можно было бы сшить сумку.}
{18430}{}{Облезлый гуль}
{18431}{}{Облезлый гуль. Из отвалившихся кусков кожи вполне можно было бы сшить сумку.}
{18440}{}{Мерзкий гуль}
{18441}{}{Мерзкий гуль. Кажется, от одного вида вас сейчас вырвет.}
{18450}{}{Мерзкий гуль}
{18451}{}{Мерзкий гуль. Кажется, от одного вида вас сейчас вырвет.}
{18460}{}{Грязный гуль}
{18461}{}{Грязный гуль. Налипшая на ходячий скелет грязь сделала его не таким заметным.}
{18470}{}{Грязный гуль}
{18471}{}{Грязный гуль. Налипшая на ходячий скелет грязь сделала его не таким заметным.}
{18480}{}{Отвратительный гуль}
{18481}{}{Отвратительный гуль. На ЭТО можно смотреть только через прицел.}
{18490}{}{Отвратительный гуль}
{18491}{}{Отвратительный гуль. На ЭТО можно смотреть только через прицел.}
{18500}{}{Гниющий гуль}
{18501}{}{Гниющий гуль. Ничего отвратительнее ваш нос еще не... нюхал?}
{18510}{}{Гниющий гуль}
{18511}{}{Гниющий гуль. Ничего отвратительнее ваш нос еще не... нюхал?}
{18520}{}{Светящийся гуль}
{18521}{}{Светящийся гуль. Как насчет пары лишних РАД?}
{18530}{}{Светящийся гуль}
{18531}{}{Светящийся гуль. Как насчет пары лишних РАД?}
{18540}{}{Быстрый гуль}
{18541}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18550}{}{Быстрый гуль}
{18551}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18560}{}{Быстрый гуль}
{18561}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18570}{}{Быстрый гуль}
{18571}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18580}{}{Быстрый гуль}
{18581}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}
{18590}{}{Быстрый гуль}
{18591}{}{Быстрый гуль. Кажется, это не такая медленная развалина, как другие.}

#SUPERMUTANTS
{18700}{}{Супермутант}
{18701}{}{Супермутант. Огромный кусок мышц. У этих созданий не так много оснований быть причисленными к разряду разумных.}
{18710}{}{Супермутант}
{18711}{}{Супермутант. Живой ужас пустошей. Тупой, злой, воняет.}
{18720}{}{Супермутант громила}
{18721}{}{Супермутант громила. Огромная туша состоящая из мышц, злобы и лёгкой брони - выглядит опасно. Осматривается с тупым видом в поисках того, что можно сломать.}
{18730}{}{Супермутант громила}
{18731}{}{Супермутант громила. Тварь в нетерпении топчется на месте.  Она хочет бить, ломать и крушить, а не вот это вот всё.}
{18740}{}{Супермутант берсерк}
{18741}{}{Супермутант берсерк. Тело этого существа покрыто гематомами. Похоже, от боли и ярости эта тварь совсем обезумела.}
{18750}{}{Супермутант берсерк}
{18751}{}{Супермутант берсерк. Всё его тело покрыто шрамами. Это безумное существо вышло победителем из многих схваток, оно очень опасно.}
{18760}{}{Супермутант мастер}
{18761}{}{Супермутант мастер. Существо покрыто бронёй из ржавых листов метала и цепей. Доспех выглядит дико и гремит при движении, но похоже очень нравится монстру}
{18770}{}{Супермутант мастер}
{18771}{}{Супермутант мастер. Закованное в доспех чудовище выглядит не умнее остальных представителей своего вида, но чувствует себя явно важнее.}
{18780}{}{Тень}
{18781}{}{Тень. Огромный кусок мышц. Это создание обладает удивительно осмысленным и пронзительным взглядом.}
{18790}{}{Тень}
{18791}{}{Тень. Огромный кусок мышц. Это создание обладает осмысленным и пронзительным взглядом.}
{18800}{}{Тень берсерк}
{18801}{}{Тень берсерк. Это умное и опытное существо вышло победителем из многих схваток, оно очень опасно.}
{18810}{}{Тень берсерк}
{18811}{}{Тень берсерк. Это умное и опытное существо вышло победителем из многих схваток, оно очень опасно.}
{18820}{}{Тень мастер}
{18821}{}{Тень мастер. Монстр с умным и спокойным взглядом. Вы чувствуете себя маленьким перед ним не только по росту. Это существо больше всего, чем вы могли бы стать.}
{18830}{}{Тень мастер}
{18831}{}{Тень мастер. Монстр с умным и спокойным взглядом. Вы чувствуете себя маленьким перед ним не только по росту. Это существо больше всего, чем вы могли бы стать.}
{18840}{}{Тень снайпер}
{18841}{}{Тень снайпер. Умное и хитрое существо с отточенными движениями и огромной винтовкой в руках.}
{18850}{}{Тень снайпер}
{18851}{}{Тень снайпер. Умное и хитрое существо с отточенными движениями и огромной винтовкой в руках.}

#POSEYDON NPC
{20000}{}{Бессмертный Джон}
{20001}{}{Потрепанный годами робот с мозгом в колбе.}
{20010}{}{Кок}
{20011}{}{Жирный потный мужик с лукавым взглядом похотливых глаз. Носит фартук и поварской колпак.}
{20020}{}{Профессор Кеворкян}
{20021}{}{На морщинистом лице читается интерес, раздражение и усталость. Носит очки.}
{20030}{}{Хьюго "Боров" Рут}
{20031}{}{Мордатый грузный мужчина с красным лицом.}
{20040}{}{Могила}
{20041}{}{Сухопарый мужчина с обветренным лицом. Обладатель роскошных усов "подкова".}
{20050}{}{Пепельный Том}
{20051}{}{Гуль совсем уж черного цвета, будто бы соткан из грязи и пепла.}
{20060}{}{Чэд}
{20061}{}{Тучный, пузатый и широкоплечий мужик, в кровавом фартуке. Взгляд не блещет интеллектом.}
{20070}{}{Козявка}
{20071}{}{Очень низкорослый молодой парень.}
{20080}{}{Чог}
{20081}{}{Огромный даже для супермутанта, жуткий монстр.}
{20090}{}{Джесси "СвЕтоша" Кастор}
{20091}{}{Высокий брюнет похмельного вида с вечной щетиной на лице.}
{20100}{}{Шон "Трещётка" МаршАл}
{20101}{}{Необычайно светящийся гуль.}
{20110}{}{Кэртис "Ковбой" Рейдлер}
{20111}{}{Молодой бородатый мужчина, в поношенном пиджаке и в ковбойской шляпе.}
{20120}{}{Брайс "Труба"}
{20121}{}{Высокий худой мужик, с бледной кожей. На левой руке нет среднего пальца. На поясе в чехле лежит металлическая труба.}
{20130}{}{Монтгомери "Монти" Тонато}
{20131}{}{Молодой мужчина с суровым и волевым выражением лица. На щеке видна тонкая белая полоска - шрам от ножа.}
{20140}{}{Гвен Тайлер}
{20141}{}{Симпатичная молодая девушка, сверкает белоснежной улыбкой.}
{20150}{}{Донни "Тесак" Трахо}
{20151}{}{Высокий мексиканец с изрезанным морщинами и ветром лицом. Носит бороду стиля "Якорь".}
{20160}{}{Гарфилд "Заноза" Нельсон}
{20161}{}{Жизнерадостного вида рыжий парень.}
{20170}{}{Нера "Труди" Аргвайр}
{20171}{}{Брюнетка с холодным взглядом.}
{20180}{}{Оливер "Айсман" Рэми}
{20181}{}{Он иронично ухмыляется, глядя на вас.}
{20190}{}{Харон "Просоленный" Диклейн}
{20191}{}{Крайне хорошо сохранившейся гуль в военной форме.}
{20200}{}{Крук Маккензи}
{20201}{}{Худой длиннорукий и длинноногий парень с грязными волосами цвета кукурузы.}
{20210}{}{Саншайн "Санни" 209}
{20211}{}{Выглядит опасно, если вы не знаете что это и зачем - лучше не трогать это.}
{20220}{}{Молли Блум}
{20221}{}{Очень сексуальная, привлекательна девушка.}
{20230}{}{Даймонд "Пэйдж" Даллас}
{20231}{}{Крупный мужчина в возрасте. Его кучерявую шевелюру давно покрыл налет седины.}
{20240}{}{Мерфюс "Старый" МакДилл}
{20241}{}{Пышная рыжая борода, седые виски и явно натянутая улыбка на лице.}
{20250}{}{Бам-Бам Бигелоу}
{20251}{}{Короткостриженный и гладковыбритый коренастый мужик.}
{20260}{}{Броди Джэвис}
{20261}{}{Очки примотаны изолентой к черепу, смотрит хитро и надменно.}
{20270}{}{Турок}
{20271}{}{Небритый, короткостриженный угрюмый чувак, активно предлагающий вам поторговать и приобрести "уникальные вещицы".}
{20280}{}{Гэри}
{20281}{}{Дёрганый вид, порваная роба, большой рюкзак за спиной, руки постоянно чёрные.}
{20290}{}{Дуглас "Шишак"}
{20291}{}{Опрятного вида пожилой мужчина в довоенном костюме, носит очки и кипу.}
{20300}{}{Винни "Широкий" Флетчер}
{20301}{}{Широченный детина, смотрит прям в глаза, тяжелый голос и оттопыренная нижняя губа.}
{20310}{}{Бургер Чак}
{20311}{}{Негр в тёмном расстёгнутом плаще и шляпе, человек неприхотливого и тяжёлого труда.}
{20320}{}{Туко "Амиго" Саламанка}
{20321}{}{Крепкого вида мексиканец. Взглядом буравит вас, будто бы вы должны ему денег.}
{20330}{}{Чунг Дэйшу}
{20331}{}{Небольшого роста азиат с короткими светлыми волосами. Меч на поясе.}
{20340}{}{Томми "Сиська"}
{20341}{}{Невысокий мужчина с мягкими чертами на круглом лице с раздраженно-настороженном выражением.}
{20350}{}{Мистер Шоу}
{20351}{}{Огромный, тучный мужчина с париком на голове и с гримом клоуна на лице. Он вас пугает своим видом.}

#POSEYDON GUARDS
{21000}{}{Рядовая СКБ "Посейдона"}
{21001}{}{Очевидно, что эти наемники не даром получают деньги. С ними лучше не связываться.}
{21010}{}{Рядовой СКБ "Посейдона"}
{21011}{}{Очевидно, что эти наемники не даром получают деньги. С ними лучше не связываться.}
{21020}{}{Страж Башни}
{21021}{}{Суровый мужик, оценивает вас проессиональным взглядом убийцы. Хорошо, что он нанят охранять, а не убивать.}

#LARS'S GANG
{21300}{}{Жучило Дублом}
{21301}{}{Видно что он - отъявленный пират и головорез. Броня покрыта множеством следов битв.}
{21310}{}{Черный Пес}
{21311}{}{Крепкий мужик, на шее красная, выцветшая бандана. Смотрит с прищуром.}
{21320}{}{Жох}
{21321}{}{Длинный нигер крепкого телосложения, при разговоре переодически сплевывает на землю.}
{21330}{}{Израиль Хэнкс}
{21331}{}{Хмурый молчаливый мужик, смотрит на вас оценивающим взлядом, будто бы прикидывая цену ваших пожиток.}
{21340}{}{Карнат}
{21341}{}{Веселый на первый взгляд парень, вечная улыбка. Однако во взгляде видны жажда наживы и славы.}

#KASTOR'S CLERGY
{21400}{}{Хранитель веры Томас "Блаженный" Мэнсон}
{21401}{}{Человек в грязной робе, на которой виднеется свинцовый символ культа «Атом».}
{21410}{}{Хранительница веры Марта "Голос" Свифт}
{21411}{}{Хрупкая фигура в грязноватой робе Атома не по размеру. Она смотрит на вас светло-серыми глазами из под тени капюшона.}
{21420}{}{Хранитель веры Гарольд "Лазарь" Шипман}
{21421}{}{Бородатый, улыбчивый мужчина в грязной робе Атома, на которой виднеются багровые следы.}
{21430}{}{Ревнитель Атома}
{21431}{}{Мрачная личность в алой мантии с символом Атома на ней, лицо скрывает железная маска с прорезью для глаз.}
{21440}{}{Ревнительница Атома}
{21441}{}{Мрачная личность в алой мантии с символом Атома на ней, лицо скрывает железная маска с прорезью для глаз.}

#SAN FRANCISCO NPC
{21500}{}{Ханаяма Каору}
{21501}{}{Огромный азиат, настоящий гигант. Облачен в довоенный костюм-тройку, носит отчки.}
{21510}{}{Акисамэ Коэцудзи}
{21511}{}{Невысокий японец, спокойного вида. В его глазах читается мудрость.}
{21520}{}{Реви Руётэ}
{21521}{}{Молодая красивая японка с дерзким и нахальным взглядом.}
{21530}{}{Бэнг Шируба}
{21531}{}{Ссутуленный седой старикан с пышными усами. Вам кажется, что он оценивает вас.}
{21540}{}{Ло-Пэн}
{21541}{}{Этот китаец достаточно известный в городе. Вы определенно слышали что-то о мастере Ло-Пэне.}
{21550}{}{Лам Чин Ин}
{21551}{}{Он смотрит на вас пристально и как будто бы с враждебностью.}
{21560}{}{Саммо Хун}
{21561}{}{Толстный азиат со смешным лицом и строгим взглядом.}
{21570}{}{Донни Йен}
{21571}{}{Высокий китаец в строгом традиционном наряде позапрошлого столетия.}
{21580}{}{Господин Молох}
{21581}{}{Невероятно крупный и атлетично сложенный мужик, вас поражает ширина его плеч.}
{21590}{}{Арнольд Митч}
{21591}{}{Мужик в замасленном комбенизоне, на голове среди копны немытых волос виднеются очки сварщика.}
{21600}{}{Вальдис Гуз}
{21601}{}{Тучный мужчина от которого смердит рыбой. Быть может он пришел из глубин океана? Вы не знаете.}
{21610}{}{Сигурд Крофт}
{21611}{}{Низкорослый брюнет, разглядывающий вас подобно тому, как торговец смотрит на покупателя.}
{21620}{}{Амели Крофт}
{21621}{}{Женщина средних лет с огромными мешками под глазами. Видно что она очень устает, но улыбка на ее лице довольно искренняя.}
{21630}{}{Билли Ли}
{21631}{}{Поледователь Дракона. Этот парень вам кого-то напоминает, возможно у него есть брат. Крупный, очевидно сильный боец.}
{21640}{}{Джимми Ли}
{21641}{}{Поледователь Дракона. Кажется вы видели его раньше, или у него есть брат близнец. С виду очень силен.}
{21650}{}{Бомж Лукас}
{21651}{}{Из-за огромной свалявшейся грязной бороды на вас смотрят парочка замутненных алкоголем глаз.}
{21660}{}{Кинтара Айнис}
{21661}{}{Обычная с виду девушка, достаточно симпатичная.}
{21670}{}{Акира Хомма}
{21671}{}{Пожилая женщина лет пятидесяти, по ее одежде можно предположить, что она бывалый траппер.}
{21680}{}{Сунь Хэй}
{21681}{}{Этот мужик явно опытный выживалец и охотник, его трофеи говорят сами за себя.}
{21690}{}{Бинго Коробок}
{21691}{}{Лысый щербатый мужичок с хитрющей рожей, чуток шепелявит.}
{21700}{}{Рыбак}
{21701}{}{Этот человек наверное видел больше рыбы, чем вы выпустили пуль за всю жизнь.}
{21710}{}{Крестьянин}
{21711}{}{Быть крестьянином - нелегкий труд, как хорошо что вы обычный бродяга.}
{21720}{}{Крестьянка}
{21721}{}{Из-за грязи истинный цвет ее кожи остается для вас загадкой.}
{21730}{}{Боец Якудза}
{21731}{}{Азиат сурового вида, он точно бандит. Из-под одежды виднеются края ярких татуировок.}
{21740}{}{Боец Якудза}
{21741}{}{Эта дамочка даст фору любому мужику, с татуированными азиатами лучше не связываться.}
{21750}{}{Боец Ши}
{21751}{}{Представитель крупного клана Ши, возможно он крестьянин, а может и бандит.}
{21760}{}{Боец Ши}
{21761}{}{В Ши состоят также и женщины, возможно они примут и вас? Осталось найти контакты.}
{21770}{}{Солдат Молоха}
{21771}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21780}{}{Шлюха}
{21781}{}{Хотите весело провести время? Идите в цирк, а эта грязная шлюха стремится заработать.}
{21790}{}{Шлюха}
{21791}{}{Вы слышали что у некоторых азатских баб есть член, вы уверены что хотите проверить?}
{21800}{}{Сутенер}
{21801}{}{Этот крутой мужик достаточно крут, чтобы держать в узде своих девочек.}
{21810}{}{Барыга}
{21811}{}{Судя по его виду он часть товара употребляет сам.}
{21820}{}{Барыга}
{21821}{}{Наркобарыга, самый обыкновенный, скорее всего он занимается поставками из Рено.}
{21830}{}{Солдат Молоха}
{21831}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21840}{}{Солдат Молоха}
{21841}{}{Вы совершенно уверены, что перед вами если не рейдер, то что-то очень близкое.}
{21850}{}{Командир Ши}
{21851}{}{Этот представитель Ши выглядит как младший офицер, наверное где то рядом его отряд.}
{21860}{}{Командир Ши}
{21861}{}{Это тот случай когда женщина может эффективно командовать мужчинами. Все у этих азиатов не как у людей.}
{21870}{}{Боец Ши}
{21871}{}{Представитель крупного клана Ши, возможно он крестьянин, а может и бандит.}
{21880}{}{Боец Ши}
{21881}{}{В Ши состоят также и женщины, возможно они примут и вас? Осталось найти контакты.}

#FORP 2019 NPC
{22000}{}{Крыса}
{22001}{}{Крыса. Довольно мелкая тварь.}
{22010}{}{Мантис}
{22011}{}{Мантис. Хладнокровные глаза уставлены на Вас, очень громко и неприятно стрекочет.}
{22020}{}{Муравей}
{22021}{}{Муравей. Усики указывают на Вас, сопровождаясь взглядом хищника.}
{22030}{}{Муравьиный-лев}
{22031}{}{Этот здоровенный муравей выглядит особенно мерзко и опасно, его толстый панцирь покрыт белой вязкой жидкостью, а пасть огромна.}
{22040}{}{Свинокрыс}
{22041}{}{Свинокрыс. Он издаёт звуки, напоминающие писк и хрюканье в одном.}
{22050}{}{Кротокрыс}
{22051}{}{Кротокрыс. Эта огроменная тварь громко рычит.}
{22060}{}{Кротокрыс мутант}
{22061}{}{Гора мускулов и огромные красные глазища. С клыков течёт вязкая слюна. От мутанта крайне дурно пахнет.}
{22070}{}{Серебряный гекко} 
{22071}{}{Серебряный гекко. Это простой мелкий ящер.}
{22080}{}{Золотой гекко}
{22081}{}{Золотой гекко. Этот большой геккон громко клацает острыми зубами.}
{22090}{}{Пещерный гекко}
{22091}{}{Небольшое создание с тёмным окрасом шкуры. По всему телу видны шрамы и потертости от прибывания в пещере. Жёлтые глазища вечно бегают по окружению.}
{22100}{}{Собака} 
{22101}{}{Собака. Дворняга обычных размеров.}
{22110}{}{Оса}
{22111}{}{Крупное мутировавшее насекомое с крупными крылышками. Зеленоватые глаза и острые шипы по тельцу.}
{22120}{}{Таракан} 
{22121}{}{Противный, большой и крайне юркий таракан. Обладает длинными усиками и лапками,а также относительно крепким панцирем.}
{22130}{}{Мелкий чёрный радскорпион} 
{22131}{}{Мелкий чёрный радскорпион. Это малый, но опасный скорпион.} 
{22140}{}{Чёрный радскорпион}
{22141}{}{Чёрный радскорпион. Направляет свой чёрный хвост на вас.}
{22150}{}{Пещерный радскорпион}
{22151}{}{Крупный скорпион с серым панцирем и массивным чёрным хвостом.}
{22160}{}{Брамин}
{22161}{}{Брамин. Над головами летают мухи.}
{22170}{}{Хищное-растение}
{22171}{}{Хищное-растение. Странная, безглазая пасть держится на толстом стебле и манит вас улыбкой.}
{22180}{}{Ванаминго}
{22181}{}{Ванаминго. У этой твари нет ни глаз, ни пальцев. Жуткое зрелище.}
{22190}{}{Детёныш Когтя смерти} 
{22191}{}{Детёныш Когтя смерти. Чуть меньше Вас ростом, но безусловно опасен!}
{22200}{}{Коготь смерти} 
{22201}{}{Коготь смерти. Опустив большие лапы вниз, этот Коготь принюхивается.}
{22210}{}{Коготь смерти охотник} 
{22211}{}{Коготь смерти охотник. Эта тварь серого цвета, она намного опаснее самого сильного когтя смерти в стае.}
{22220}{}{Огненный гекко} 
{22221}{}{Огненный гекко. Из ноздрей исходит слабый дымок.}
{22230}{}{Бестия} 
{22231}{}{Когтистая, низкая и коренастая тварь с серым окрасом.}
{22240}{}{Кентавр} 
{22241}{}{Кентавр. С длинного щупальцеобразного языка течёт мутная слизь.} 
{22250}{}{Летатель} 
{22251}{}{Летатель. Он парит в воздухе, издавая вредные газы через поры подкожного мешка.} 
{22260}{}{Болотник}
{22261}{}{Болотник. Грозная тварь из морских или болотных пучин.}  
{22270}{}{Яо-гай}
{22271}{}{Громадная, мускулистая медведеподобная тварь с внушительными лапами, покрытыми редкой шерстью. На теле виднеются язвы и шрамы. Невероятно острые зубы и длиннющие когти размером с человеческую руку.}
{22280}{}{Жуткохват} 
{22281}{}{Большая извиваящаяся тварь с длинными опасными лапами, острыми клыками и сильным хвостом.}
{22290}{}{Тенехват} 
{22291}{}{Большая извиваящаяся тёмная тварь с длинными опасными лапами, острыми клыками и сильным хвостом.}
{22300}{}{Разлагающийся гуль} 
{22301}{}{Дикий гуль, в глазах ни грамма разума.}
{22310}{}{Дикий гуль} 
{22311}{}{Дикий гуль, в глазах ни грамма разума..}
{22320}{}{Мутированный гуль} 
{22321}{}{Дикий гуль, в глазах ни грамма разума..}
{22330}{}{Огромный мутированный гуль} 
{22331}{}{Дикий гуль, в глазах ни грамма разума..}

{22900}{}{Аризонская Многоножка} 
{22901}{}{Огромная многоножка.}
{22910}{}{Лаваш} 
{22911}{}{Огромная мутировавшая корова.}
{22920}{}{Гигантский Паук}
{22921}{}{Гигантский Паук.}
{22930}{}{Койот}
{22931}{}{Пустынный койот. В этих краях это самое распространенное существо.}

{25010}{}{Теодор Рейк}
{25011}{}{Этот мужчина среднего возраста и в аккуратном деловом костюме является Мэром города Сильверлейк, важная персона, которая отвечает за функционирование города.}

{30000}{}{Собака}
{30001}{}{Эта собака выглядит прирученой.}