# 08.2007 Cvet

# Version info
{1}{}{FalloutRP}

####################################################################################################################################
#
#		Months, Day of week
#
####################################################################################################################################

{21}{}{Январь}
{22}{}{Февраль}
{23}{}{Март}
{24}{}{Апрель}
{25}{}{Май}
{26}{}{Июнь}
{27}{}{Июль}
{28}{}{Август}
{29}{}{Сентябрь}
{30}{}{Октябрь}
{31}{}{Ноябрь}
{32}{}{Декабрь}

{33}{}{Воскресенье}
{34}{}{Понедельник}
{35}{}{Вторник}
{36}{}{Среда}
{37}{}{Четверг}
{38}{}{Пятница}
{39}{}{Суббота}

####################################################################################################################################
#
#		Material Types (from PROTO.MSG)
#
####################################################################################################################################

{40}{}{Стекло}
{41}{}{Металл}
{42}{}{Пластик}
{43}{}{Дерево}
{44}{}{Грязь}
{45}{}{Камень}
{46}{}{Цемент}
{47}{}{Кожа}

####################################################################################################################################
#
#		Misc
#
####################################################################################################################################

{50}{}{.}
{52}{}{,}
{53}{}{ }
{54}{}{ и }
{55}{}{ или }

####################################################################################################################################
#
#		Music/Video
#
####################################################################################################################################

# Main theme
{80}{}{Sleepless Ruins.ogg}
# Intro, from 90 to 99
#{90}{}{}
#{91}{}{}

####################################################################################################################################
#
#		Chat
#
####################################################################################################################################

# On head messages
{100}{}{|0xF8F993 %s}                     # Normal
{102}{}{|0xFF0000 !!!%s!!!}               # Shout
{104}{}{|0xFF00FF **%s**}                 # Emote
{106}{}{|0x00FFFF ...%s...}               # Whisp
{108}{}{|0xFFFFFF %s}                     # Social

# Message box
{120}{}{%s: |0xF8F993 %s}                 # Normal
{122}{}{%s: |0xFF0000 !!!%s!!!}           # Shout
{124}{}{%s: |0xFF00FF **%s**}             # Emote
{126}{}{%s: |0x00FFFF ...%s...}           # Whisp
{128}{}{%s: |0xFFFFFF %s}                 # Social
{130}{}{Рация %u> |0xFFFFFE ..%s..}       # Radio
{132}{}{%s}                               # NetMsg

{135}{}{name mode off}                    # radio names
{136}{}{bad chars in name. must be a(A)-z(Z) && 0-9}                   # radio names
{137}{}{min name length is 3}		 # radio names
{138}{}{max name length is 8}
{139}{}{radio name changed}
{140}{}{|0xFFFF00 Невозможно отправить - рация на предохранителе.}
{141}{}{|0xFFFF00 Нельзя использовать команды в процессе ожидания.}
{142}{}{Символы: |0xFFFF00 ()[]{}<>@#~^_ |0x3CF800 запрещены к применению в прямой речи.}
{143}{}{мычание}
{144}{}{неразборчивое мычание}
{145}{}{мычит}
{146}{}{неразборчивые звуки}

#Nameing
{150}{}{Выберите кого назвать: "|}
{151}{}{Вы запомнили: "|}
{152}{}{Вы вспомнили имен: |0xFFFF00 }

####################################################################################################################################
#
#		FixBoy
#
####################################################################################################################################

{200}{}{Параметры:}
{201}{}{Инструменты:}
{202}{}{Предметы:}
{205}{}{шт.}
{206}{}{у вас }
{210}{}{Вы успешно создали предмет (ы).}
{211}{}{Вам не удалось создать предмет (ы).}
{212}{}{Вы слишком устали, попробуйте повторить попытку позже.}

####################################################################################################################################
#
#		Interface text
#
####################################################################################################################################

{250}{}{|4291317840 Эта функция сейчас недоступна, используйте FOConfig.exe или Launcher.exe для редактирования настроек игры.}
{251}{}{Скриншот сохранен.}
{252}{}{Не удалось сохранить скриншот.}
{253}{}{Лог сохранен.}
{254}{}{Не удалось сохранить лог.}

{260}{}{Масштаб %d %%}
{265}{}{Игра приостановлена}

# Dialog
{275}{}{Бартер}
{276}{}{Сказать}
{277}{}{Лог}
# Barter
{280}{}{Обмен}
{281}{}{Диалог}
{282}{}{Выйти}
{283}{}{Сказать}
# Menu
{290}{}{Сохранить}   # Singleplayer
{291}{}{Загрузить}   # Singleplayer
{292}{}{Опции}
{293}{}{Выход}
{294}{}{Далее}
# Login
{300}{}{Новая игра}  # Singleplayer
{301}{}{Загрузить}   # Singleplayer
{302}{}{Играть}      # Multiplayer
{303}{}{Регистрация} # Multiplayer
{304}{}{Опции}
{305}{}{Авторы}
{306}{}{Выход}
# Dialog box
{310}{}{Отмена}
{311}{}{Дальше}
{312}{}{Следовать}
{313}{}{Открытый режим}
{314}{}{Скрытый режим}
{315}{}{Реальное время}
{316}{}{Пошаговый режим}
# Reg name
{320}{}{Имя}
{321}{}{Пароль}
# Reg Skin
{322}{}{hmjmps hmlwar hmbwar HMLWTRB hfprim HFPUNP hfblpr hfrprim nfprem HFYTRB HMBPRS nmhair hm2bsb HMBPRM nmfatt nmmyrn nmwarr}
{323}{}{62 110 120 418 61 151 279 392 256 396 140 236 284 353 91 88 64}
{324}{}{Выбранный скин не совпадает с полом персонажа.}
# Cha
{325}{}{Далее}
{326}{}{Назад}
{327}{}{Печать}
{328}{}{Навыки}
{329}{}{Очки умений}
# Reg
{335}{}{Особые навыки}
{336}{}{Очки расп.}
# Perk
{340}{}{Взять}
{341}{}{Назад}
# Global map
{350}{}{Вы не можете управлять группой.}
{351}{}{}
{352}{}{}
{353}{}{}
# Aim
{360}{}{Цель заблокирована.}
# Split
{365}{}{Переместить}
{366}{}{Все}
# Timer
{370}{}{Таймер}
# Say screen
{375}{}{Далее}
{376}{}{Назад}
{377}{}{Сказать...}
# Input box
{380}{}{Запись}
{381}{}{Назад}
# Town view
{385}{}{Назад}
{386}{}{Войти}
{387}{}{Контуры}
# Save/Load
{390}{}{Сохранить}
{391}{}{Загрузить}
{392}{}{Далее}
{393}{}{Назад}
{394}{}{Новая запись}
{395}{}{Введите имя записи}

####################################################################################################################################
#
#		Inventory (with INVENTRY.MSG + 400)
#
####################################################################################################################################

{400}{}{СЛ}
{401}{}{ВС}
{402}{}{ВН}
{403}{}{ОБ}
{404}{}{ИН}
{405}{}{ЛВ}
{406}{}{УД}
{407}{}{Жизней}
{408}{}{Класс брони: VALUE}
{409}{}{  Норма}
{410}{}{  Лазер}
{411}{}{  Огонь}
{412}{}{  Плазма}
{413}{}{  Взрыв}
{414}{}{Нет вещи}
{415}{}{Урон:}
{416}{}{Эф. Дальность: }
{417}{}{Заряд: }
{418}{}{Боеприпас: }
{419}{}{У вас не хватает Очков действия для входа в инвентарь.}
{420}{}{Общий вес:}
{421}{}{ПЕРЕМЕСТИТЬ}
{422}{}{ВСЕ}
{423}{}{ТАЙМЕР}
{424}{}{Безоружно:}
{425}{}{Вы не можете подобрать эту вещь. Вы и так несете максимальный груз.}
{426}{}{Для этой вещи не хватает места.}
{427}{}{Повр. Орган.}
{428}{}{Реген ОД: VALUE}
{429}{}{За удачное применение умения воровать, вы получаете %d очков опыта.}
{430}{}{Вес}
{431}{}{Объем: |0xE5C62B VALUE|0x3CF800 .}
{433}{}{Вы не находите там ничего для себя полезного.}
{434}{}{Зарядов: |0xE5C62B VALUE|0x3CF800| /|0xE5C62B| MAX_VALUE|0x3CF800 .}
{435}{}{Вес: |0xE5C62B VALUE |0x3CF800 грамм.}
{436}{}{Вес: |0xE5C62B VALUE |0x3CF800 фунтов.}
{437}{}{Цена: |0xE5C62B VALUE |0x3CF800 монет.}
{438}{}{Цена у торговца: |0xE5C62B VALUE |0x3CF800 монет.}
{439}{}{Перезарядка}
{440}{}{Перегруз}
{441}{}{Скрытность}
{442}{}{Уровень}
{443}{}{Отравление}
{444}{}{Облучение}
{445}{}{Травмирован}
{446}{}{Привыкание}
{447}{}{Таймаут VALUE}
{448}{}{Негабаритный}
{449}{}{Ваш ход VALUE}
{450}{}{Пошагово}

####################################################################################################################################
#
#		Radio
#
####################################################################################################################################

{455}{}{Рация}
{456}{}{Канал}
{457}{}{Обновить}
{458}{}{Передача}
{459}{}{Приём}
{460}{}{Везде}
{461}{}{5 зон}
{462}{}{2 зоны}
{463}{}{Локация}
{464}{}{Карта}
{465}{}{Радиовещание включено.}
{466}{}{Радиовещание закончено.}
{467}{}{Радиовещание изменено.}
{468}{}{Радиоприём включён.}
{469}{}{Радиоприём закончен.}
{470}{}{Радиоприём изменён.}
{471}{}{Канал сменён.}
{474}{}{Невозможно переключить канал.}
{475}{}{Невозможно переключить передачу.}
{476}{}{Невозможно переключить приём.}
{477}{}{Невозможно переключить тип передачи.}
{478}{}{Невозможно переключить тип приёма.}
{479}{}{У вас нет радио настроенного на передачу.}

####################################################################################################################################
#
#		Barter
#
####################################################################################################################################

{480}{}{Ну хорошо, будь по вашему.}
{481}{}{Нет, ваше предложение меня не радует.}
{482}{}{Извините, для вас это уже слишком.}
{483}{}{Извините, но столько вам не унести.}
{484}{}{На момент продажи у вас не было выбранной вещи.}
{485}{}{Извини, но я уже продал кое-что из того, что ты выбрал.}
{486}{}{Вы не можете торговать в данный момент.}
{487}{}{Вы не можете торговать с этим персонажем.}
{490}{}{%s хочет поторговать с вами. Режим торговли: %s.}
{491}{}{открытый}
{492}{}{скрытный}
{493}{}{Игрок не может сейчас торговать с вами.}
{495}{}{Начата торговля с %s. Ваш режим: %s, режим оппонента: %s.}
{496}{}{%s готов к сделке.}

####################################################################################################################################
#
#		Items info
#
####################################################################################################################################

# Wear
{500}{}{|0x3CF800 Износ: |0xE5C62B| VALUE%|0x3CF800| .}
{501}{}{Пройдено сервисное обслуживание.}
{502}{}{Пройдено дополнительное сервисное обслуживание.}
{503}{}{Небольшая поломка.}
{504}{}{Поломка средней тяжести.}
{505}{}{Серьезная поломка.}
{506}{}{Восстановлению не подлежит.}
{507}{}{Ломался: |0xE5C62B| VALUE |0x3CF800| раз.}

{510}{}{Сервисное обслуживание уже пройдено.}
{511}{}{Сервисное обслуживание пройдено успешно.}
{512}{}{Сервисное обслуживание провалено.}
{515}{}{Ремонт произведен успешно.}
{516}{}{Ремонт провален.}

{520}{}{Ваша броня сломалась.}
{521}{}{Ваше оружие сломалось.}

# Key
{550}{}{Номер ключа: |0xE5C62B KEY_ID|0x3CF800 .}

# Car
{560}{}{Номер машины CAR_ID.}
{561}{}{Топливо: |0xE5C62B VALUE|0x3CF800| /|0xE5C62B| MAX_VALUE|0x3CF800 .}
{562}{}{Износ: |0xE5C62B VALUE%|0x3CF800 .}

# FORP Additional Enduser Info
{563}{}{Мин. Сила: |0xE5C62B VALUE|0x3CF800 .}
{564}{}{Задержка: |0xE5C62B VALUE |0x3CF800 мс.}
{565}{}{Применение: |0xE5C62B VALUE |0x3CF800 ОД.}

{567}{}{Электро}
{568}{}{Перезарядка: |0xE5C62B VALUEAP |0x3CF800 ОД, |0xE5C62B VALUEMS |0x3CF800 мс.}
{569}{}{Перезарядка: |0xE5C62B VALUE |0x3CF800 ОД.}
{570}{}{Перки:}
{571}{}{Калибр: |0xE5C62B AMMO |0x3CF800 }

{576}{}{Класс Брони: -VALUE.}

# Ammo inventory stats
{600}{}{Мод Класса Брони: |0xE5C62B ACMOD|0x3CF800 .}
{601}{}{Мульт. Урона: |0xE5C62B MULT|0x3CF800 \|0xE5C62B DIV|0x3CF800 .}
{602}{}{Модиф. Резиста: |0xE5C62B DRMOD|0x3CF800 .}
{603}{}{Модиф. Трешхолда: |0xE5C62B DTMOD|0x3CF800 .}
{604}{}{Тип урона: |0xE5C62B DMGTYPE|0x3CF800 .}

####################################################################################################################################
#
#		PipBoy, Timeouts
#
####################################################################################################################################

{700}{}{----- Статус -----}
{701}{}{Баланс репликации}
{702}{}{%d долларов}
{703}{}{Стоимость репликации}
{704}{}{%d долларов}
{705}{}{Всего репликаций}
{706}{}{%d раз}
{720}{}{----- Квесты -----}
{723}{}{<<<<< Статистика >>>>>}
{725}{}{----- Карты -----}
{730}{}{----- Инфо -----}

{740}{}{----- Таймауты -----}
{741}{}{%s секунд}
{742}{}{%s минут}
{790}{}{|0xFFFF00 Таймаут на переходы. Ждите.}
{791}{}{|0xFFFF00 Боевой таймаут. Ждите.}
{792}{}{|0xFFFF00 Таймаут на скрытность. Ждите.}

{795}{}{Информация в процессе загрузки...}
{796}{}{Ошибка загрузки! Пожалуйста перезагрузите PipBoy.}

####################################################################################################################################
#
#		Dialogs
#
####################################################################################################################################

{800}{}{Вы не можете говорить с мобом.}
{801}{}{Нпц не в состоянии сейчас говорить.}
{802}{}{Нпц занят. Попробуйте поговорить позже.}
{803}{}{Слишком большая дистанция для разговора.}
{804}{}{Привет.} # Нет диалогов.
{805}{}{Нпц разговаривает с другими игроками. Попробуйте поговорить позже.}
{806}{}{Ошибка преддиалоговых настроек.}
{807}{}{Битая ссылка диалога.}
{808}{}{Ошибка компановки диалога.}
{809}{}{Нпц не найден.}
{810}{}{Не валидный указатель на диалог.}

####################################################################################################################################
#
#		Global map
#
####################################################################################################################################

{900}{}{|0xFFFF00 Вы не нашли локацию, ее поглотила пустошь.}
{901}{}{|0xFFFF00 Локация странным образом переместилась в другое место.}
{902}{}{|0xFFFF00 Вы не нашли входа в локацию.}
{903}{}{|0xFFFF00 Вы не нашли стоянки для своего транспорта.}
{904}{}{|0xFFFF00 Локация переполнена, попробуйте войти позже.}
{905}{}{|0xFFFF00 Вы не можете перейти.}
{906}{}{|0xFFFF00 Вы слишком далеко от сетки выхода.}
{907}{}{|0xFFFF00 Свободное посещение данной локации запрещено, она будет открыта по ходу сюжета.}
{908}{}{|0xFFFF00 Вы обходите естественные препятствия тайными тропами.}
{909}{}{|0xFFFF00 Совершенно не понятно, как пересечь эту труднопроходимую местность.}
{910}{}{|0xFFFF00 Вы не можете туда перейти. Гексы заняты.}
{911}{}{|0xFFFF00 Что-то пошло не так.}
{912}{}{Вы чувствуете опасность. Перейти?}
{913}{}{Да}
{914}{}|0xFFFF00 {Застоявшийся тяжёлый воздух затрудняет дыхание. Без респиратора здесь лучше не гулять.}
{915}{}{Недоступно}
{916}{}{Пустошь}

{950}{}{|0xFFFF00 Вы готовы следовать за %s в %s?}
{952}{}{|0xFFFF00 Приготовьтесь следовать за %s в %s.}
{970}{}{|0xFFFF00 незнакомцем}
{972}{}{|0xFFFF00 пустошь}

####################################################################################################################################
#
#		Maintenance
#
####################################################################################################################################

{1001}{}{|4291317840 Введен неверный логин.}
{1002}{}{|4291317840 Введен неверный пароль.}
{1003}{}{|4291317840 Аккаунт с таким именем уже есть - измените логин.}
{1004}{}{|4291317840 Игрок под этим логином уже в игре.}
{1005}{}{|4291317840 Неверные данные SPECIAL.}
{1006}{}{|4291317840 Регистрация пройдена успешно.}
{1007}{}{|4291317840 Идет соединение с сервером.}
{1008}{}{|4291317840 Сбой соединения! При повторениях сбоя - обратитесь к администратору сервера.}
{1009}{}{|4291317840 Неверный логин или пароль.}
{1010}{}{|4291317840 Соединение установлено, аутентификация...}
{1012}{}{|4291317840 Гексы для высадки заняты, попробуйте войти в игру немного позже.}
{1013}{}{|4291317840 Отключение по команде игрока.}
{1014}{}{|4291317840 Ошибка в имени. Возможно слишком длинное или короткое.}
{1015}{}{|4291317840 Ошибка в одном из склонений имени. Возможно слишком длинное или короткое.}
{1016}{}{|4291317840 Пол введен неверно.}
{1017}{}{|4291317840 Возраст введен неверно.}
{1018}{}{|4291317840 Не удалось подключиться к серверу игры.}
{1019}{}{|4291317840 Введены неверные данные.}
{1020}{}{|4291317840 Ошибка поиска стартовой локации, свяжитесь с администрацией сервера.}
{1021}{}{|4291317840 Ошибка поиска стартовой карты, свяжитесь с администрацией сервера.}
{1022}{}{|4291317840 Ошибка поиска стартовых координат, свяжитесь с администрацией сервера.}
{1023}{}{|4291317840 Ошибка БД, свяжитесь с администрацией сервера.}
{1024}{}{|4291317840 Неверная версия сетевого протокола, обновите клиент.}
{1025}{}{|4291317840 Ошибка в передаче данных, попробуйте еще раз.}
{1026}{}{|4291317840 Неверное сетевое сообщение.}
{1027}{}{|4291317840 Внутренняя ошибка сервера №1, сообщите о ней администрации сервера.}
{1028}{}{|4291317840 Аутентификация пройдена, загрузка карты.}
{1029}{}{|4291317840 Выберите 3 умения.}
{1030}{}{|4291317840 Имя должно быть написано с использованием одного языка.}
{1031}{}{|4291317840 Имя на 70% должно состоять из букв алфавита.}
{1032}{}{|4291317840 Пробел не может быть использован в начале или конце имени.}
{1033}{}{|4291317840 Не допускается ставить в имени два пробела подряд.}
{1034}{}{|4291317840 Ваш аккаунт заблокирован.}
{1035}{}{|4291317840 Недопустимые символы в имени.}
{1036}{}{|4291317840 Недопустимые символы в пароле.}
{1037}{}{|4291317840 Ошибка загрузки пользовательского интерфейса.}
{1038}{}{|4291317840 Ошибка выполнения стартового скрипта.}
{1039}{}{|4291317840 Выбранный язык не поддерживается. Установлен язык по умолчанию.}
{1040}{}{|4291317840 Игра может работать некорректно при разрешениях меньше 800x600 или больше 1280x1024.}
{1041}{}{|4291317840 Тук-тук, кто-нибудь есть?}
{1042}{}{|4291317840 Нельзя регистрироваться чаще чем раз в 5 минут.}
{1043}{}{|4291317840 Ваш IP заблокирован.}
{1044}{}{|4291317840 Нельзя переключаться между персонажами чаще чем раз в минуту.}
{1045}{}{|4291317840 Времени осталось: @lex time@ минут.}
{1046}{}{|4291317840 Вы были забанены.}
{1047}{}{|4291317840 Бан от: @lex banby@, Продолжительность: @lex time@ часов, Комментарий: @lex reason@.}
{1048}{}{|4291317840 Ошибка скрипта, обратитесь к администрации сервера.}
{1049}{}{|4291317840 Ваш персонаж полностью умер, игра за данный аккаунт больше невозможна.}
{1050}{}{|4291317840 Вы выбрали несовместимое сочетание трейтов!}

#Client info chat messages 1059 <-> 1069
{1059}{}{ }
{1060}{}{ }
{1061}{}{Вы можете настроить произвольное разрешение экрана игры в файле "|0xF2E519 FOConfig.exe|0x3CF800| ".}
{1062}{}{Загрузка конфигурации "|0xF2E519 default.ini|0x3CF800| "... Успешно завершена. Классический интерфейс активирован. 
Добро пожаловать на FalloutRP!}
{1063}{}{Загрузка конфигурации "|0xF2E519 rp_default.ini|0x3CF800| "... Успешно завершена. Новый интерфейс активирован. 
Добро пожаловать на FalloutRP!}
{1064}{}{|4291317840 Ошибка загрузки интерфейса, не найдены файлы конфигурации игры. Рекомендуется воспользоваться "|0xF2E519 Updater.exe|0x3CF800| ".}

# Singleplayer messages
{1070}{}{|4291317840 Игра сохранена.}
{1071}{}{|4291317840 Ошибка сохранения игры.}
{1072}{}{|4291317840 Игра загружена.}
{1073}{}{|4291317840 Ошибка загрузки игры.}
{1074}{}{|4291317840 Новая игра начата.}
{1075}{}{|4291317840 Ошибка начала новой игры.}

####################################################################################################################################
#
#		Character
#
####################################################################################################################################

#
# STAT LEVEL DESCRIPTIONS
#
{2301}{}{Гадко}
{2302}{}{Плохо}
{2303}{}{Низко}
{2304}{}{Неплохо}
{2305}{}{Средне}
{2306}{}{Xорошо}
{2307}{}{Высоко}
{2308}{}{Отлично}
{2309}{}{Круто}
{2310}{}{Герой!}

#Abbreviated, for editor
{2311}{}{Гадко}
{2312}{}{Плохо}
{2313}{}{Низко}
{2314}{}{Непл.}
{2315}{}{Средн.}
{2316}{}{Xорош.}
{2317}{}{Высок.}
{2318}{}{Отлич.}
{2319}{}{Круто}
{2320}{}{Герой!}

#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{3300}{}{+ (4 х ЛВ)}
{3301}{}{+ (2 х ЛВ)}
{3302}{}{+ (2 х ЛВ)}
{3303}{}{+ (ЛВ + СЛ)х2}
{3304}{}{+ (ЛВ + СЛ)х2}
{3305}{}{+ (4 х ЛВ)}
{3306}{}{+ (ВС + ИН)х2}
{3307}{}{+ (ВС + ИН)}
{3308}{}{+ (3 х ЛВ)}
{3309}{}{+ (ВС + ЛВ)}
{3310}{}{+ (3 х ЛВ)}
{3311}{}{+ (ВС + ЛВ)}
{3312}{}{+ (4 x ИН)}
{3313}{}{+ (3 х ИН)}
{3314}{}{+ (5 x ОБ)}
{3315}{}{+ (4 x ОБ)}
{3316}{}{+ (5 x УД)}
{3317}{}{+ (ВН + ИН)х2}
#
# SKILLDEX
#
{3340}{}{УМЕНИЯ}
{3341}{}{ОТКАЗ}

#
#   Skill Use Text
#
{3400}{}{|0xFFFF00 Вы пока не воскрешаете мертвых.}
{3400}{}{|0xFFFF00 Пусть мертвые почиют с миром.}
{3400}{}{|0xFFFF00 Не тронь дохляков.}
{3401}{}{|0xFFFF00 Подождите немного, похоже, вы исчерпали себя.}
{3401}{}{|0xFFFF00 Вы слишком устали.}
{3401}{}{|0xFFFF00 Такое напряжение убьет вас.}
{3402}{}{|0xFFFF00 Вы не нуждаетесь в помощи санитара.}
{3403}{}{|0xFFFF00 Вы не нуждаетесь в помощи доктора.}
{3404}{}{|0xFFFF00 Для лечения травмы требуется навык доктора.}
{3405}{}{|0xFFFF00 Для лечения этих повреждений требуется навык первой помощи.}

{3412}{}{|0xFFFF00 Вы лечите раненый глаз.}
{3413}{}{|0xFFFF00 Вы лечите сломанную правую руку.}
{3414}{}{|0xFFFF00 Вы лечите сломанную левую руку.}
{3415}{}{|0xFFFF00 Вы лечите сломанную правую ногу.}
{3416}{}{|0xFFFF00 Вы лечите сломанную левую ногу.}
{3422}{}{|0xFFFF00 Вы не лечите раненый глаз.}
{3423}{}{|0xFFFF00 Вы не лечите сломанную правую руку.}
{3424}{}{|0xFFFF00 Вы не лечите сломанную левую руку.}
{3425}{}{|0xFFFF00 Вы не лечите сломанную правую ногу.}
{3426}{}{|0xFFFF00 Вы не лечите сломанную левую ногу.}

{3430}{}{|0xFFFF00 Вас пытались обокрасть!}
{3431}{}{|0xFFFF00 Вам пытались что-то подложить!}

{3440}{}{|0xFFFF00 Попытка взлома безуспешна.}
{3441}{}{|0xFFFF00 Вы не смогли устновить ловушку.}
{3442}{}{|0xFFFF00 Вы устанавливаете ловушку.}
{3443}{}{|0xFFFF00 Вы не смогли снять ловушку.}
{3444}{}{|0xFFFF00 Вы смогли разминировать ловушку.}
{3445}{}{|0xFFFF00 Вы не можете войти в режим скрытности, когда вас кто-нибудь видит.}

{3450}{}{|0xFFFF00 Вы прибавили %d очков жизней.}
{3451}{}{|0xFFFF00 Вы и без того здоровы.}
{3452}{}{|0xFFFF00 %s и без того выглядит неплохо.}
{3453}{}{|0xFFFF00 Попытка лечения не удалась.}
{3455}{}{|0xFFFF00 Вы получаете %d Опыта за использование умений.}
{3459}{}{|0xFFFF00 \nskill_use: неправильное умение.}
{3461}{}{|0xFFFF00 Вы не видите ловушек.}
{3462}{}{|0xFFFF00 Вы так ничего и не узнали.}
{3463}{}{|0xFFFF00 Ремонту не подлежит.}
{3470}{}{|0xFFFF00 Вам не удалось похитить %s.}
{3471}{}{|0xFFFF00 Вы похищаете %s.}
{3472}{}{|0xFFFF00 Вы не сумели установить %s.}
{3473}{}{|0xFFFF00 Вы устанавливаете %s.}
{3495}{}{|0xFFFF00 Вы не так умелы, чтобы излечивать настолько тяжелые раны.}
{3496}{}{|0xFFFF00 Починить этого робота невозможно.}
{3497}{}{|0xFFFF00 Данный навык временно отключен и не прокачивается.}
{3498}{}{|0xFFFF00 Данный навык прокачивается за счет действий, связанных с этим навыком.}

#
#	 PC STAT NAMES
#
{4000}{}{Очки характеристик}
{4001}{}{Следующий уровень}
{4002}{}{Осталось очков умений}
{4003}{}{Уровень}
{4004}{}{Опытность}
{4005}{}{Репутация}
{4006}{}{Карма}
{4007}{}{Бонусы}
{4008}{}{Убито}
{4009}{}{Очки умений}
{4010}{}{Способности}
{4011}{}{Дополнительно}
{4012}{}{Умения}
#
#	 PC STAT DESCRIPTIONS
#
{4050}{}{Количество очков, оставшихся для добавления к одной из базовых характеристик персонажа.}
{4051}{}{Количество очков опыта, необходимых для получения следующего уровня.}
{4052}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}
{4053}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
{4054}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
{4055}{}{Известная миру информация о ваших деяниях, их оценка в народе. Влияет на прием вашего героя.}
{4056}{}{Эффект от предпринятых вами действий за время игры.}
{4057}{}{Бонусы прибавляют дополнительные способности. За каждый третий уровень опыта вы получаете один бонус.}
{4058}{}{Количество существ, погибших в вашем присутствии от естественных причин, как-то автоматных очередей, взрывов гранат и огнеметных залпов.}
{4059}{}{Увеличивайте свои умения распределением очков.}
{4060}{}{Вы обязаны выбрать три способности, в которых будет специализироваться ваш персонаж. За каждую он получит бонус 20%, а повышаться они будут вдвое быстрее.}
{4061}{}{Дополнительные способности описывают вашего персонажа более подробно. Все они имеют свои положительные и отрицательные стороны. Во время создания можно выбрать максимум две.}
{4062}{}{Умения накапливаются с опытом и изучением, а, кроме того, во время разных событий по игре. Чем выше те или иные умения, тем больше вероятность ваших успешных действий.}

#
#  Experience-gain messages
#
{4090}{}{Вы получили новый уровень.}
{4091}{}{|0xCDCBCB Вы получили VALUE опыта.}
{4092}{}{Вы получили %d очков опыта за убийство существа : %s.}
{4093}{}{%s вы получили %d очков опыта.}
{4094}{}{За победу над врагами, }  # 622-626 prepend to line 621
{4095}{}{За уничтожение противника, }
{4096}{}{Вы победили в этом бою, }
{4097}{}{За разгром ваших врагов }
{4098}{}{За уничтожение противника без единой царапины, }

#
# Editor
#
{4104}{}{ЛЕТ}
{4105}{}{ПОЛ}
{4106}{}{ИМЯ}
{4107}{}{МУЖ.}
{4108}{}{ЖЕН.}
{4109}{}{БОНУСЫ}
{4110}{}{КАРМА}
{4111}{}{УБИТО}
{4112}{}{ОЧКИ УМЕНИЙ}
{4113}{}{Уровень: %d}
{4114}{}{Опыт: %d}
{4115}{}{След. ур.: %d}

#
# Damage info texts
#

{4250}{}{Жизни  %d/%d}

#
# Karma
#

{6000}{}{Карма}
{6001}{}{: %d (%s)}  # Value, Desc
{6002}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

{6099}{}{9} # Max values
{6100}{}{1000} # Min value
{6101}{}{Спаситель обреченных} # Desc
{6102}{}{2000} # Picture index
{6103}{}{750}
{6104}{}{Надежда пустыни}
{6105}{}{2001}
{6106}{}{500}
{6107}{}{Щит надежды}
{6108}{}{2002}
{6109}{}{250}
{6110}{}{Защитник}
{6111}{}{2003}
{6112}{}{-249}
{6113}{}{Странник}
{6114}{}{2004}
{6115}{}{-500}
{6116}{}{Нечисть}
{6117}{}{2005}
{6118}{}{-750}
{6119}{}{Омраченная душа}
{6120}{}{2006}
{6121}{}{-1000}
{6122}{}{Бич пустоши}
{6123}{}{2007}
{6124}{}{-2147483648}
{6125}{}{Дьявольское отродье}
{6126}{}{2008}

# Town reputation
{6405}{}{Репутация}
{6406}{}{Отмечает вашу репутацию среди жителей разных поселений.}

# Name
{6500}{}{Поклонение}
{6501}{}{Любовь}
{6502}{}{Симпатия}
{6503}{}{Апатия}
{6504}{}{Скука}
{6505}{}{Злоба}
{6506}{}{Ярость}

# Desc
{6550}{}{Каждый человек отсюда стремится хоть немного походить на вас. Вас носят на руках, прославляют в стихах и песнях и называют детей в вашу честь.}
{6551}{}{Когда вы здесь появляетесь, люди радостно приветствуют вас. Все они что-нибудь слышали о вас и желают вам всего самого наилучшего.}
{6552}{}{Xотя никто не бросается вас обнимать, как только увидит, местные жители хорошо к вам относятся. У них сложилось в целом приятное о вас впечатление.}
{6553}{}{Несмотря на подозрительное отношение к незнакомым людям, вы ни у кого не вызываете ни положительных, ни отрицательных эмоций.}
{6554}{}{Появившийся неизвестно откуда чужак - так думают все и ждут от вас какой-либо каверзы.}
{6555}{}{Своим поведением вы доказали, что вас подозревали не зря. Увидев вас, люди начинают перешептываться и показывать пальцем, как будто на внезапно объявившегося сборщика налогов.}
{6556}{}{С опаской поглядывая в вашу сторону, местные жители обходят вас за километр, плюют вам в спину и отворачиваются при попытке заговорить. Всем известно, что хуже и гаже вас никого нет.}

# Addiction title
{6900}{}{Привычки}
{6901}{}{Возникшие у вас вредные привычки.}

# Critter status title
{7000}{}{Тяж. Ран.}
{7001}{}{Пул. Ран.}
{7002}{}{Кровотечение}
{7003}{}{Зар. Крови}
{7004}{}{Загрязнение}
{7005}{}{Кровопотеря}
{7006}{}{Отравление}
{7007}{}{Радиация}
{7008}{}{Удушье}
{7009}{}{Голод}
{7010}{}{Жажда}
{7011}{}{Опьянение}
{7012}{}{Паралич }
{7013}{}{КД }
{7014}{}{Прицел: }
{7015}{}{Вес }
{7016}{}{Объем }
{7017}{}{Бой}
{7018}{}{Усталость}
{7019}{}{Переход}
{7020}{}{Действие}
{7021}{}{Взлом}
{7022}{}{Лечение}
{7023}{}{Доктор}
{7024}{}{Ремонт}
{7025}{}{Наука}
{7026}{}{Передоз}

# Autoaim title
{7500}{}{Глаза}
{7501}{}{Голова}
{7502}{}{Л. Рука}
{7503}{}{Торс}
{7504}{}{П.Рука}
{7505}{}{Л. Нога}
{7506}{}{Живот}
{7507}{}{П. Нога}

# Client_main inventory
{7510}{}{Описание не может содержать больше 127 символов! Осталось: }
{7511}{}{ символов!}
{7512}{}{Команда не найдена!}
{7513}{}{Мертвые не разговаривают!}
{7514}{}{В руке: }
{7515}{}{ Очередь: x }
{7516}{}{. Радиус: }
{7517}{}{аккумулятор.}
{7518}{}{Объем вещей:}
{7519}{}{кг.}
{7520}{}{Доп. экипировка:}
{7521}{}{Слот головы пуст}
{7522}{}{Слот рюкзака пуст}
{7523}{}{Утилитарный слот пуст}

####################################################################################################################################
#
#		Items games
#
####################################################################################################################################

# Сообщение в мессаджбокс при наведении на объект
{10000}{}{Вы видите: NAME.}
# При рассмотрении объекта
{10004}{}{NAME}
# Имя или инфо не найдено
{10010}{}{Вы не видите ничего необычного.}
# Item not found in container (possible another critter take it)
{10020}{}{Предмет не найден, возможно его взял кто-то другой.}

# Container
{10100}{}{|0xFFFF00 Закрыто.}
{10101}{}{|0xFFFF00 Вы обыскали %s.}
{10102}{}{|0xFFFF00 Вы закрыли %s.}

#
# Use text messages
#
{10200}{}{|0xFFFF00 Вы применили: %s.}
{10201}{}{|0xFFFF00 Вы применили: %s на %s.}
{10202}{}{|0xFFFF00 Из этого ничего не вышло.}
{10203}{}{|0xFFFF00 К своей досаде, вы догадались, что перед вами обычный труп.}
{10204}{}{|0xFFFF00 Когда вы нагнулись и посмотрели, то обнаружили мертвое тело.}
{10205}{}{|0xFFFF00 Жаль, но вы опоздали.}
{10206}{}{|0xFFFF00 Это все как мертвому припарки.}
{10207}{}{|0xFFFF00 Вы засветили фонарь.}
{10208}{}{|0xFFFF00 Фонарь уже зажжен.}
{10209}{}{|0xFFFF00 Вы установили таймер.}
{10210}{}{|0xFFFF00 Таймер давно начал работу!}
{10211}{}{|0xFFFF00 Вход кажется заблокирован.}

# Solar scotcher
{10240}{}{|0xFFFF00 Вы не можете перезарядить батарейки - не хватает света.}

# Car
{10250}{}{Вы подзарядили машину энергией.}
{10251}{}{Энергоблок машины уже полностью заряжен.}
{10252}{}{Вы успешно отремонтировали машину.}
{10253}{}{Машина не нуждается в ремонте.}
{10254}{}{Этот двигатель не работает на данном виде топлива.}
{10255}{}{Кончилось топливо.}
{10256}{}{Машина сломана.}
{10257}{}{Машина не рассчитана на такое количество людей, уберите лишних.}
{10258}{}{Ваша харизма не позволяет руководить таким количеством людей, уберите лишних.}
{10259}{}{Нельзя отсоединять от группы находясь на воде.}

# Drugs
{10300}{}{Вы получили: |0xFFFF00 @lex value@ @lex name@|0x3CF800 .}
{10301}{}{Вы потеряли: |0xFFFF00 @lex value@ @lex name@|0x3CF800 .}
{10302}{}{|0xFFFF00 Вы очистились от всех эффектов зависимости.}
{10303}{}{|0xFFFF00 Вы получили инфаркт от чрезмерной передозировки химикалий.}
{10304}{}{|0xFFFF00 По-видимому, ничего не происходит.}
{10305}{}{|0xFFFF00 %s корчится от воздействия различных химикалий.}
{10306}{}{|0xFFFF00 На вас применили какой-то наркотик!}
{10307}{}{|0xFFFF00 На вас пытались применить какой-то наркотик!}

{10310}{}{вкалывает стимпак}
{10311}{}{вкалывает анти-радин}
{10312}{}{пьёт противоядие}
{10313}{}{глотает таблетку ментата}
{10314}{}{ест фрукт}
{10315}{}{ест шашлык из игуаны}
{10316}{}{глотает таблетку баффаута}
{10317}{}{ест шашлык из игуаны}
{10318}{}{пьёт нюка-колу}
{10319}{}{глотает таблетку рад-х}
{10320}{}{вкалывает психо}
{10321}{}{пьёт пиво}
{10322}{}{пьёт самогон}
{10323}{}{вкалывает суперстимулятор}
{10324}{}{вдыхает джет}
{10325}{}{пьёт антиджет}
{10326}{}{употребляет целебный порошок}
{10327}{}{пьёт гамма-глоток}
{10328}{}{пьёт рентген-ром}
{10329}{}{ест печенье}
{10330}{}{пьёт пойло}
{10331}{}{ест мясо}
{10332}{}{  .}
{10333}{}{  .}
{10334}{}{  .}
{10335}{}{  .}
{10336}{}{  .}
{10337}{}{  .}
{10338}{}{  .}
{10339}{}{  .}
{10340}{}{  .}
{10341}{}{  .}
{10342}{}{  .}
{10343}{}{  .}
{10344}{}{  .}
{10345}{}{  .}
{10346}{}{  .}
{10347}{}{  .}
{10348}{}{  .}
{10349}{}{  .}

# Geiger
{10350}{}{У счетчика Гейгера кончились заряды.}
{10351}{}{Счетчик Гейгера включен.}
{10352}{}{Счетчик Гейгера выключен.}
{10353}{}{Вы провели счетчик Гейгера над своим телом. На табло появились цифры: @lex rem@.}
{10354}{}{На табло появились цифры: @lex rem@.}
{10355}{}{Ничего не происходит.}
{10356}{}{Счетчик Гейгера подзаряжен.}
{10357}{}{Счетчик Гейгера заряжен на @lex cur@/@lex max@.}

# Weapon Damage
{10400}{}{Легк.}
{10401}{}{Средн.}
{10402}{}{Тяжел.}
{10403}{}{Экстрем.}

# Weapon Range
{10410}{}{Корот.}
{10411}{}{Средн.}
{10412}{}{Дальн.}

# Books
{10450}{}{Вы прочитали книгу.}
{10451}{}{Вы не узнали ничего нового.}
{10452}{}{Вы уяснили новую научную информацию.}
{10453}{}{Вы многое поняли о способах починки сломанной электроники.}
{10454}{}{Вы узнали новые способы обработки ран.}
{10455}{}{Вы научились лучше обращаться с оружием.}
{10456}{}{Вы научились лучше обращаться с энергетическим оружием.}
{10457}{}{Вы изучили новые способы выживания в пустыне.}

# Use on
{10500}{}{Запасы в Сумке Доктора подошли к концу.}
{10501}{}{Запасы в Аптечке Первой помощи подошли к концу.}
{10502}{}{Запрещено делать это во время боя.}
{10503}{}{Этот персонаж не будет торговать с вами.}
{10504}{}{Этот персонаж ничего вам не собирается говорить.}
{10505}{}{Вы не подберете этот предмет. Вы и так слишком нагружены разными вещами.}
{10506}{}{Медикаменты в Санитарной Сумке подошли к концу.}
{10507}{}{Запасы лекарств в Армейской Полевой Аптечке истощились.}
{10508}{}{Это существо не может ничего нести.}

# Grave
{10550}{}{|0xFFFF00 Эта могила разрыта.}
{10551}{}{|0xFFFF00 Эта могила зарыта.}

# Reloading
{10552}{}{|0xFFFF00 Это оружие не имеет магазина.}
{10553}{}{|0xFFFF00 Вы заряжаетесь из патронташа.}
{10554}{}{|0xFFFF00 Вы изменили тип боеприпаса, за неимением альтернатив.}
{10555}{}{|0xFFFF00 У вас нет аммуниции данного калибра.}
{10556}{}{|0xFFFF00 Вы изменили тип боеприпаса.}
{10557}{}{|0xFFFF00 Вы итак заняты перезарядкой.}
{10558}{}{меняет тип боеприпаса}
{10559}{}{Вы извлекли:
- |0xFFFF00  @lex proto@ |0x3CF800  - |0xFFFF00 @lex count@ шт.}
{10560}{}{разряжает оружие}
{10561}{}{передёргивает затвор}
{10562}{}{проверяет заряд}
{10563}{}{заряжает оружие}
{10564}{}{Вы зарядили:
- |0xFFFF00  @lex proto@ |0x3CF800  - |0xFFFF00 @lex count@ шт.}

####################################################################################################################################
#
#		Calibers (from PROTO.MSG)
#
####################################################################################################################################

#
# Caliber Types for weapons
#
{10900}{}{Нету}
{10901}{}{Ракета}
{10902}{}{Топл. огнемета}
{10903}{}{Энергопак С}
{10904}{}{Энергопак Д}
{10905}{}{.223}
{10906}{}{5.56мм}
{10907}{}{.40 кал.}
{10908}{}{10мм}
{10909}{}{.44 кал.}
{10910}{}{14мм}
{10911}{}{12кал}
{10912}{}{9мм}
{10913}{}{ББ}
{10914}{}{.45 кал.}
{10915}{}{2мм}
{10916}{}{Магазин 4.7мм}
{10917}{}{Основные XН}
{10918}{}{7.62мм}
{10919}{}{Болт}
{10920}{}{40 мм}
{10921}{}{Сигнальные ракеты}
{10922}{}{22 мм}
{10923}{}{Шипы}
{10924}{}{.50 кал.}
{10925}{}{12.7мм}
{10930}{}{Гвозди}

####################################################################################################################################
#
#		Critters game
#
####################################################################################################################################

# CrType
{10950}{}{монстра}
{10951}{}{кентавра}
{10952}{}{радскорпиона}
{10953}{}{гуля}
{10954}{}{брамина}
{10955}{}{крота-гризли}
{10956}{}{летателя}
{10957}{}{киберпса}
{10958}{}{собаку}
{10959}{}{мантиса}
{10960}{}{смертекогта}
{10961}{}{хищное растение}
{10962}{}{серебрянного ящера}
{10963}{}{чужого}
{10964}{}{муравья}
{10965}{}{мистера хенди}
{10966}{}{робомозг}
{10967}{}{робоглаз}
{10968}{}{охранного робота}
{10969}{}{туррель}
{10970}{}{крысу}
{10971}{}{крысокабана}
{10972}{}{крысиного короля}
{10973}{}{золотого ящера}
{10974}{}{огнедышащего ящера}
{10975}{}{матку чужих}

#For age and conditions
{11000}{}{Вы видите: }

#Default view
{11010}{}{Вы видите: NAME}
{11011}{}{Вы видите лежачего: NAME}
{11012}{}{Вы видите труп: NAME}
{11013}{}{Вы видите останки: NAME}
{11014}{}{Вы не видите ничего необычного}

# Male
##Age, max age 99
#<=16
{11116}{}{паренёк}
#<=30
{11130}{}{молодой человек}
#<=40
{11140}{}{мужчина средних лет}
#<=60
{11160}{}{пожилой мужчина}
#>60
{11199}{}{старик}

# Female
##Age, max age 99
#<=16
{12116}{}{девочка}
#<=30
{12130}{}{девушка}
#<=40
{12140}{}{женщина средних лет}
#<=60
{12160}{}{пожилая женщина}
#>60
{12199}{}{старуха}

//Descriptions for look at char
{12200}{}{Лицо скрыто капюшоном}
{12201}{}{Внешность скрывает доспех}
{12202}{}{Тело скрывает доспех}

//General line
{12203}{}{На вид}

//Maniac
{12205}{}{смотрит зло на тебя}
{12206}{}{бормочет что-то нехорошее о тебе}
{12207}{}{смотрит с ненавистью}
{12208}{}{насмехается над тобой}
{12209}{}{смотрит презрительно}
{12210}{}{выглядит уродливо}
{12211}{}{коситься в твою сторону}
{12212}{}{кажется хочет напасть}
{12213}{}{скалится на тебя}
{12214}{}{шепчет сдохни}

//Charisma modifier
{12215}{}{|0x3CF8FA неотразима|0x3CF800 }
{12216}{}{|0x3CF8FA неотразим|0x3CF800 }
{12217}{}{|0x3CF8D2 прекрасна|0x3CF800 }
{12218}{}{|0x3CF8D2 прекрасен|0x3CF800 }
{12219}{}{|0x3CF8AA красива|0x3CF800 }
{12220}{}{|0x3CF8AA красив|0x3CF800 }
{12221}{}{|0x3CF882 привлекательна|0x3CF800 }
{12222}{}{|0x3CF882 привлекателен|0x3CF800 }
{12223}{}{|0xFF0000 тошнотворная|0x3CF800 }
{12224}{}{|0xFF0000 тошнотворный|0x3CF800 }
{12225}{}{|0xFF4000 отвратительна|0x3CF800 }
{12226}{}{|0xFF4000 отвратителен|0x3CF800 }
{12227}{}{|0xFF6000 неприятна|0x3CF800 }
{12228}{}{|0xFF6000 неприятен|0x3CF800 }

//Strength modifier
{12229}{}{мощная}
{12230}{}{мощный}
{12231}{}{сильна}
{12232}{}{силён}
{12233}{}{немощная}
{12234}{}{немощный}
{12235}{}{слабая}
{12236}{}{слабый}

//Endurance modifier
{12237}{}{крепко сбита}
{12238}{}{крепко сбит}
{12239}{}{крепкая}
{12240}{}{крепкий}
{12241}{}{хрупкая}
{12242}{}{хрупкий}
{12243}{}{хилая}
{12244}{}{хилый}

//Agility modifier
{12245}{}{проворна}
{12246}{}{проворен}
{12247}{}{ловкая}
{12248}{}{ловкий}
{12249}{}{неповоротливая}
{12250}{}{неповоротливый}
{12251}{}{неуклюжая}
{12252}{}{неуклюжий}

//General stat
{12253}{}{обычная}
{12254}{}{обычный}
{12255}{}{обычное}

//Gender endings
{12256}{}{}
{12257}{}{а}
{12258}{}{о}

//Look full
{12500}{}{ Он }   # Male
{12501}{}{ Она }   # Female
{12502}{}{ Оно }   # It
{12509}{}{|0xFFFF00 мёртв}    
{12510}{}{|0xFFFF00 при смерти}    
{12511}{}{|0xFFFF00 обессилен}    
{12512}{}{|0xFFFF00 тяжело ранен}    
{12513}{}{|0xFFFF00 серьезно ранен} 
{12514}{}{|0xFFFF00 ранен}        
{12515}{}{|0xFFFF00 слегка ранен} 
{12516}{}{|0x3CF800 здоров}       
{12520}{}{|0x3CF800  и есть серьезные повреждения}      # Male hurt
{12521}{}{|0x3CF800 , но есть серьезные повреждения}    # Male unhurt
{12522}{}{|0x3CF800  и есть серьезные повреждения}      # Female hurt
{12523}{}{|0x3CF800 , но есть серьезные повреждения}    # Female unhurt
{12524}{}{|0x3CF800  и есть серьезные повреждения}      # It hurt
{12525}{}{|0x3CF800 , но есть серьезные повреждения}    # It unhurt

# SLOT_HAND1
{12538}{}{В руке}                        
{12539}{}{В руках}                        
{12540}{}{Вооружение:}
{12541}{}{Держит во рту}
{12542}{}{Носит при себе MISC}	# Any other item
{12543}{}{В пасти:}
{12544}{}{Держит в жвалах}
{12545}{}{Держит в клешнях}
{12546}{}{Держит в клешне}
{12547}{}{Держит в щупальцах}
{12548}{}{Держит в щупальце}
{12549}{}{Держит в манипуляторах}
{12550}{}{Держит в манипулятора}
{12551}{}{Держит в лапах}
{12552}{}{Держит в лапе}

# Other slots
{12570}{}{ На ней }
{12571}{}{ На нем }
{12572}{}{ У неё  }
{12573}{}{ У него  }
{12574}{}{ За спиной }
{12575}{}{.}
{12576}{}{.}

# items with charges
{12599}{}{Осталось использований: }
# character move restriction
{12600}{}{Вы не в силах сдвинуться.}
# Текст по хоткею - слишком частое использование
{12601}{}{Вы не можете отправлять сообщения так часто.}
# robot repair
{12750}{}{Вы успешно починили робота.}
{12751}{}{Вам не удалось починить робота.}
{12752}{}{Вы успешно починили сенсоры.}
{12753}{}{Вам не удалось починить сенсоры.}
{12754}{}{Вы успешно починили правый манипулятор.}
{12755}{}{Вам не удалось починить правый манипулятор.}
{12756}{}{Вы успешно починили левый манипулятор.}
{12757}{}{Вам не удалось починить левый манипулятор.}
{12758}{}{Вы успешно починили правую ходовую.}
{12759}{}{Вам не удалось починить правую ходовую.}
{12760}{}{Вы успешно починили правую ходовую.}
{12761}{}{Вам не удалось починить правую ходовую.}
{12762}{}{Робот не нуждается в ремонте.}

####################################################################################################################################
#
#		Plagues
#
####################################################################################################################################

{12800}{}{Вы чувствуете тошноту.}
{12801}{}{Вы чувствуете тошноту, и после нескольких приступов рвоты сильно утомляетесь.}
{12802}{}{Вы сильно устали, но приступы рвоты не прекращаются, и вы еще долго не можете прийти в себя.}
{12803}{}{У вас кровь идет горлом, выпадают волосы и облезает кожа на открытых участках тела. }
{12804}{}{У вас кровь идет горлом, выпадают волосы и со всего тела отваливается кожа. Рвота не прекращается. Вам не стоило увлекаться работой под Вин95.}
{12805}{}{Все внутренние органы кровоточат, у вас сильный понос и непрекращающаяся рвота. Вы корчитесь от боли и призываете смерть.}
{12806}{}{Вы скончались от лучевой болезни.}
{12807}{}{Вы получили большую дозу радиации.}
{12808}{}{Счетчик Гейгера отметил наличие радиации.}
{12809}{}{Счетчик Гейгера как будто взбесился.}
{12810}{}{Вы ощущаете действие яда!}
{12811}{}{Вы страдаете от отравления.}
{12812}{}{Вы чувствуете себя немного лучше.}
{12813}{}{Вам сильно полегчало.}
{12814}{}{Яд приятно растекается по вашим венам.}

{12815}{}{Вы чувствуете слабость, голова кружится.}
{12816}{}{Кашель буквально душит вас.}
{12817}{}{Глаза слезятся, кожа бледнее обычного.}

{12818}{}{Вас бьет озноб, на коже узелками проступают вены.}
{12819}{}{Кожа местами теряет чувствительность, другие участки дико чешутся.}
{12820}{}{Мышцы периодически скручивают спазмы боли.}

{12821}{}{Вас бросает в жар, ваши кости ломит, в ушах звенит, все как в тумане...}
{12822}{}{Ранки от язв сочатся кровью и сукровицей, чувствуется отвратительный запах.}
{12823}{}{Десны, веки и ушные раковины кровоточат, вы с трудом дышите.}

{12824}{}{Кажется вам немного легче.}

{12830}{}{Обычный}
{12831}{}{Крик}
{12832}{}{Емоция}
{12833}{}{Шепот}
{12834}{}{Описание}
{12835}{}{Текст}
{12836}{}{Готово}
{12837}{}{Заполните описание.}
{12838}{}{Заполните текс.}
{12839}{}{Не выбран тип текста.}

{12900}{}{Вы чувствуете слабость по всему телу, в глазах все плывет.} # Паралитический яд
{12901}{}{Вы плохо видите и почти не чувствуете тела.}
{12902}{}{Ваше тело вас не слушается. Вы полностью слепы.}
{12903}{}{Действие яда закончилось.}
{12904}{}{блюет}
{12905}{}{шатается}
{12906}{}{лицо искажает гримаса}
{12907}{}{закатывает глаза}
{12908}{}{Вам становится немного легче.}
{12909}{}{Вы вкололи себе нейротоксин. Ох, не стоило вам этого делать...}
{12910}{}{Вас чем-то укололи!}

{12920}{}{|0xFFFF00 Вы недостаточно разбираетесь в медицине.}
{12921}{}{|0xFFFF00 Вы успешно применили дефибриллятор.}
{12922}{}{|0xFFFF00 Это уже не поможет.}
{12923}{}{|0xFFFF00 В этом нет необходимости.}
{12924}{}{проверяет пульс@@заряжает дефибриллятор}
{12925}{}{|0xFFFF00 Вы заряжаете дефибриллятор.}
{12926}{}{|0xFFFF00 Вам нужно 3 обычных малых батареи для зарядки дефибриллятора.}
{12927}{}{перезаряжает дефибриллятор}

{12930}{}{Вы получаете предупреждение. Причина: @lex reason@. После третьего предупреждения вы будете заблокированы. Приятной игры.}
{12931}{}{КОЛИЧЕСТВО ПРЕДУПРЕЖДЕНИЙ:}
{12932}{}{ОК}
{12934}{}{Вас заблокировал @lex admin@ за многократное нарушение правил сервера. Причина - @lex reason@. Прощайте, мы не будем скучать.}
{12935}{}{Вы собираетесь сделать предупреждение игроку @lex PlayerName@ У него уже есть @lex WarnCount@ предупреждений. 
Подтверждаете?}
{12936}{}{Нет такого игрока.}
{12937}{}{Укажите причину предупреждения:}

{12960}{}{Вам стало лучше. Но вы чувствуете себя странно... Что-то определенно не так.}
{12961}{}{Радиация - это так... щекотно!}
{12962}{}{Почувствовав волну радиации, пронзившей вашу грудь, вы радуетесь, что вы уже не человек.}
{12963}{}{Что-то в сон клонит... наверное радиация опять зашкаливает.}
{12964}{}{Хм... А ведь тут сумасшедший уровень радиации... Можно устроить пикник.}

{12970}{}{Вас сильно стошнило, по телу прошла дрожь, но, похоже, вы победили инфекцию.}

{12971}{}{Вас бросает в жар, ваши кости ломит, выши мышцы наполняются густой кровью, в ушах звенит, все как в тумане... Похоже, вы изменяетесь.}
{12972}{}{По вашему телу проходит волна судорог, температура повышается. Вы испытываете непреодолимое желание вырвать кому-то кишки.}
{12973}{}{Ваши мышцы крепчают, кожа грубеет, но при этом вы чувствуете себя отвратительно.}
{12974}{}{Вас тошнит, глаза закатываются, все вокруг становится каким-то нереальным. Вы изменяетесь.}
{12975}{}{У вас кружится голова, вы не понимаете, что происходит вокруг, вы чувствуете сильную боль внутри, как будто что-то рвется оттуда наружу.}

{12980}{}{Вы чувствуете себя сильнее, умнее, быстрее... Похоже, вирус изменил вас только в лучшую сторону.}
{12981}{}{Болезнь одолела вас.}

# веревка
{12985}{}{У Вас нет зажигалки.}
{12986}{}{Похоже у Вас нет ножа.}
{12987}{}{Удивительно, но Вы пытались разрезать веревку пальцами. Ничего не вышло.}
{12988}{}{Вы освободились от веревки.}
{12989}{}{Вам не удалось связать цель.}
{12990}{}{Вы связали себя.}
{12991}{}{Вы связали @lex victim@.}
{12992}{}{Вас связали!}
{12993}{}{Персонаж уже связан.}

####################################################################################################################################
#
#		Scores
#
####################################################################################################################################

{13000}{}{Герои на час}
{13001}{}{Злодей на час (минимальная  значение кармы)}
{13011}{}{Герой на час (максимальное значение кармы)}
{13021}{}{Событие часа (максимальное изменение кармы за последний час)}

{13030}{}{Передовики}
{13031}{}{Почетный оратор (cамый говорливый)}
{13041}{}{Почетный торговец (cамый оборотистый)}
{13051}{}{Почетный зомби (cамый убиваемый)}
{13061}{}{Почетный обаяшка (cамый ветренный)}
{13071}{}{Почетный маньяк (cамый неадекватный)}
{13081}{}{Почетный скаут (cамый мобильный)}
{13091}{}{Почетный Айболит (cамый человеколюбивый)}
{13101}{}{Почетный стрелок (cамый огнестрельный)}
{13111}{}{Почетный клинок (cамый колюще-режущий)}
{13121}{}{Почетный кулак (cамый драчливый)}
{13131}{}{Почетный вор (cамый вороватый)}

{13140}{}{Профессионалы}
{13141}{}{Перевозчик (больше всего людей перевезено)}
{13151}{}{Убийца (больше всего существ убито)}
{13161}{}{Снайпер (больше всего критических попаданий)}
{13171}{}{Искатель приключений (больше всего квестов пройдено)}
{13181}{}{Взломщик (больше всего удачных взломов)}
{13191}{}{Костолом (больше всего рукопашных повреждений)}
{13201}{}{Нувориш (больше всего денег)}

{13210}{}{Избранный}
{13211}{}{Избранный (cамый cамый)}

{13400}{}{Базы}
{13401}{}{Текущий хозяин базы Сиерра}
{13411}{}{Текущий хозяин базы Марипоза}
{13421}{}{Текущий хозяин Собора}
{13431}{}{Лучший хозяин базы Сиерра}
{13441}{}{Лучший хозяин базы Марипоза}
{13451}{}{Лучший хозяин Собора}
{13461}{}{Принадлежность базы Сиерра}
{13471}{}{Принадлежность базы Марипоза}
{13481}{}{Принадлежность Собора}
{13491}{}{Большее предпочтение отдано организации}

####################################################################################################################################
#
#		Stats (with STAT.MSG + 2000)
#
####################################################################################################################################

# ST_STRENGTH
{100001}{}{Сила}
{100002}{}{Каждый вложенный пункт: увеличивает Очки Жизни на 3, Рукопашный урон на 2, максимальный переносимый вес на 10кг, дальность броска на 3 гекса.}
# ST_PERCEPTION
{100011}{}{Восприятие}
{100012}{}{Каждый вложенный пункт: увеличивает базовую дистанцию видимости на 5 гексов, дистанцию слышимости на 2 гекса, дает дополнительные 4% к шансу попасть в цель.}
# ST_ENDURANCE
{100021}{}{Выносливость}
{100022}{}{Каждый вложенный пункт: увеличивает Очки Жизни на 5, Устойчивость к яду на 5, Устойчивость к радиации на 2, Уровень Лечения на 1, Регенерацию ОД на 0.23, пул отрицательных ОЗ до смерти на 5.}
# ST_CHARISMA
{100031}{}{Обаяние}
{100032}{}{Каждый вложенный пункт: увеличивает пул отрицательных ОЗ до смерти на 10. Влияет на реакцию людей и диалоги НПЦ. При низком обаянии с вами могут не хотеть вести дела или даже разговаривать.}
# ST_INTELLECT
{100041}{}{Интеллект}
{100042}{}{Каждый вложенный пункт: мультипликатор очков навыков за каждый уровень персонажа: 5 + Уровень * Интеллект. При интеллекте ниже 4 персонаж начнет коверкать слова.}
# ST_AGILITY
{100051}{}{Ловкость}
{100052}{}{Каждый вложенный пункт: увеличивает Класс Брони на 5, регенерацию ОД на 0.57.}
# ST_LUCK
{100061}{}{Удача}
{100062}{}{Каждый вложенный пункт: увеличивает шанс критического урона на 3%, защиту от критического урона на 1%, 2% защиты от несчастных случаев, 9.5% защиты от поскальзывания.}
# ST_MAX_LIFE
{100071}{}{Максимум очков здоровья}
{100072}{}{Определяет, какое количество повреждений сможет вынести персонаж, прежде чем умрет (150 + Сила * 3 + Выносливость * 5 ). Смерть наступает при отрицательном ОЗ( Обаяние * 10 + Выносливость * 5 ).}
# ST_ACTION_POINTS
{100081}{}{Максимум очков действия}
{100082}{}{ОД расходуются на любые действия, кроме ходьбы. Регенерация происхдит каждые 250мс по формуле: ( 1,5 * Выносливость * 0.23 + Ловскость * 0.57 ). Регенерация ОД не может быть выше 10.}
{100083}{}{Очки действий}
# ST_ARMOR_CLASS
{100091}{}{Класс брони}
{100092}{}{Уменьшает базовый шанс попасть на значение КБ, дает 1% защиты от критических попаданий за каждое очко КБ.}
{100093}{}{Класс брони}
# ST_MELEE_DAMAGE
{100101}{}{Рукопашные повреждения}
{100102}{}{Количество повреждений, причиняемых вашим персонажем в рукопашном бою. Значение добавляется к значению рукопашного и холодного урона оружия и 50% значения к метательному оружию без радиуса поражения.}
{100103}{}{Рукоп. повр.}
# ST_CARRY_WEIGHT
{100111}{}{Переносимый груз}
{100112}{}{Максимальный вес поклажи, который может переносить ваш персонаж, в кг.}
{100113}{}{Макс. груз}
# ST_SEQUENCE
{100121}{}{Порядок}
{100122}{}{НЕ ИСПОЛЬЗУЕТСЯ.}
{100123}{}{Порядок}
# ST_HEALING_RATE
{100131}{}{Уровень лечения}
{100132}{}{Количество регенерируемых ОЗ. Пассивный реген происходит каждые 4 минуты стоя и каждые 2 минуты лежа.}
{100133}{}{Уров. лечен.}
# ST_CRITICAL_CHANCE
{100141}{}{Шанс критического удара}
{100142}{}{Базовая вероятность нанесения критических повреждений противнику.}
{100143}{}{Шанс на крит.}
# ST_MAX_CRITICAL
{100151}{}{Лучшие крит. удары}
{100152}{}{Лучшие крит. удары}
# ST_NORMAL_ABSORB
{100161}{}{Количество повреждений}
{100162}{}{Количество повреждений}
# ST_LASER_ABSORB
{100171}{}{Количество повреждений Лазер}
{100172}{}{Количество повреждений Лазер}
# ST_FIRE_ABSORB
{100181}{}{Количество повреждений Огонь}
{100182}{}{Количество повреждений Огонь}
# ST_PLASMA_ABSORB
{100191}{}{Количество повреждений Плазма}
{100192}{}{Количество повреждений Плазма}
# ST_ELECTRO_ABSORB
{100201}{}{Количество повреждений Электр.}
{100202}{}{Количество повреждений Электр.}
# ST_EMP_ABSORB
{100211}{}{Количество повреждений ЭМИ}
{100212}{}{Количество повреждений ЭМИ}
# ST_EXPLODE_ABSORB
{100221}{}{Количество повреждений Взрыв}
{100222}{}{Количество повреждений Взрыв}
# ST_NORMAL_RESIST
{100231}{}{Устойчивость к повреждениям}
{100232}{}{Все получаемые повреждения уменьшаются в соответствии с данным значением. На него сильно влияет Класс брони.}
{100233}{}{Уст. к повр.}
# ST_LASER_RESIST
{100241}{}{Устойчивость к поврежд. Лазер}
{100242}{}{Устойчивость к поврежд. Лазер}
# ST_FIRE_RESIST
{100251}{}{Устойчивость к поврежд. Огонь}
{100252}{}{Устойчивость к поврежд. Огонь}
# ST_PLASMA_RESIST
{100261}{}{Устойчивость к поврежд. Плазма}
{100262}{}{Устойчивость к поврежд. Плазма}
# ST_ELECTRO_RESIST
{100271}{}{Устойчивость к поврежд. Электр.}
{100272}{}{Устойчивость к поврежд. Электр.}
# ST_EMP_RESIST
{100281}{}{Устойчивость к поврежд. ЭМИ}
{100282}{}{Устойчивость к поврежд. ЭМИ}
# ST_EXPLODE_RESIST
{100291}{}{Устойчивость к поврежд. Взрыв}
{100292}{}{Устойчивость к поврежд. Взрыв}
# ST_RADIATION_RESISTANCE
{100301}{}{Устойчивость к радиации}
{100302}{}{Количество радиационного облучения, которому вы подвергаетесь, зависит от этого значения. На него влияет тип одетой вами брони и прием антирадиационных химикатов.}
{100303}{}{Уст. к рад.}
# ST_POISON_RESISTANCE
{100311}{}{Устойчивость к яду}
{100312}{}{Уменьшает повреждения от отравления.}
{100313}{}{Уст. к яду}

# 100700
# ST_AGE
{100701}{}{Возраст}
{100702}{}{Возраст}
# ST_GENDER
{100711}{}{Пол}
{100712}{}{Пол}
# ST_CURRENT_HP
{100721}{}{Текущие очки жизней}
{100722}{}{Текущие очки Жизней}
# ST_POISONING_LEVEL
{100731}{}{Текущий уровень яда}
{100732}{}{Текущий уровень Яда}
{100733}{}{Тек. ур. яда}
# ST_RADIATION_LEVEL
{100741}{}{Текущий уровень радиации}
{100742}{}{Текущий уровень Радиации}
{100743}{}{Тек. ур. рад.}

# 100760
# ST_EXPERIENCE
{100761}{}{Опыт}
{100762}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
# ST_LEVEL
{100771}{}{Уровень}
{100772}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
# ST_UNSPENT_SKILL_POINTS
{100781}{}{Осталось очков умений}
{100782}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}

# 100800
# ST_KARMA
{100801}{}{Карма}
{100802}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

# 112, ST_BASE_CRTYPE
{101121}{}{Тип тела}

# 150..165, 3d layers
{101501}{}{Кожа}
{101511}{}{Правая рука}
{101521}{}{Левая рука}
{101531}{}{Тело}
{101541}{}{Ноги}
{101551}{}{Руки}
{101561}{}{Голова}
{101571}{}{Волосы}
{101581}{}{Глаза}
{101591}{}{Усы}
{101601}{}{Коса}
{101611}{}{Борода}
{101621}{}{Наплечники}
{101631}{}{Браслет}
{101641}{}{Спина}
{101651}{}{Рюкзак}

# 195, ST_TRAUMATIN_OVERDOSE
{101951}{}{Доза Травматина}
{101952}{}{Передозировка травматина - отмечает сколько раз можно использовать травматин перед тем, как наступит запрет на дальнейшее использование}

####################################################################################################################################
#
#		Skills (with SKILL.MSG + 3000)
#
####################################################################################################################################

# 102000
# SK_SMALL_GUNS
{102001}{}{Легкое оружие}
{102002}{}{Использование, починка и общие знания по стрелковому оружию. Пистолетам, автоматам и винтовкам.}
{102003}{}{Легкое оружие}
# SK_BIG_GUNS
{102011}{}{Тяжелое оружие}
{102012}{}{Умение работать с тяжелым вооружением. Ручные и многоствольные пулеметы, гранатометы, огнеметы и тому подобное.}
{102013}{}{Тяжелое оружие}
# SK_ENERGY_WEAPONS
{102021}{}{Энергооружие}
{102022}{}{Способность эффективно применять энерго-оружие. Как вести огонь из различной лазерной и плазменной техники.}
{102023}{}{Энергооружие}
# SK_UNARMED
{102031}{}{Рукопашная}
{102032}{}{Сочетание боевых искусств, знание рукопашного боя и навыков самообороны позволяют вам драться используя только руки и ноги.}
{102033}{}{Рукопашная}
# SK_MELEE_WEAPONS
{102041}{}{Xолодное оружие}
{102042}{}{Использование разных подручных средств в ближнем бою. Ножи, дубинки, копья, вилы, кувалды, ломы и тому подобный хлам.}
{102043}{}{Xолодное оружие}
# SK_THROWING
{102051}{}{Метательное оружие}
{102052}{}{Способность успешно применять метательные средства. Копья, гранаты и прочее в том же роде.}
{102053}{}{Метательное оружие}
# SK_FIRST_AID
{102061}{}{Санитар}
{102062}{}{Общие познания в области первой медицинской помощи. Способность лечиться от мелких порезов, царапин и прочего. По игре способность восстанавливает больше жизней, чем просто отдых.}
{102063}{}{Санитар}
# SK_DOCTOR
{102071}{}{Доктор}
{102072}{}{Излечение тяжелых ранений и умение обращаться с поврежденными частями тела. Без этой способности для излечения будет требоваться очень много времени.}
{102073}{}{Доктор}
# SK_SNEAK
{102081}{}{-}
{102082}{}{Навык временно отключен.}
{102083}{}{Красться}
# SK_LOCKPICK
{102091}{}{Взлом замков}
{102092}{}{Умение открывать двери, даже не имея подходящего ключа. Использование отмычек или электронных устройств сильно улучшает жизненные перспективы.}
{102093}{}{Взлом}
# SK_STEAL
{102101}{}{Воровство}
{102102}{}{Часто вы оказываетесь в состоянии позаимствовать чужие вещи без ведома владельца. Неплохо для воровской карьеры.}
{102103}{}{Кража}
# SK_TRAPS
{102111}{}{Ловушки}
{102112}{}{Способность обнаруживать и обезвреживать ловушки. Кроме того, установка зарядов взрывчатого вещества.}
{102113}{}{Ловушки}
# SK_SCIENCE
{102121}{}{Наука}
{102122}{}{Большое количество научного знания, включая работу с компьютером, биологию, физику и геологию.}
{102123}{}{Наука}
# SK_REPAIR
{102131}{}{Ремонт}
{102132}{}{Практическое применение научных знаний. Ремонт и создание снаряжения, разнообразных механизмов, электроники и оружия.}
{102133}{}{Ремонт}
# SK_SPEECH
{102141}{}{-}
{102142}{}{Навык временно отключен.}
{102143}{}{Красноречие}
# SK_BARTER
{102151}{}{Торговля}
{102152}{}{Наука торговать и заниматься подобными вещами. Получение высоких цен за бросовый товар и покупка по дешевке хороших вещей помогут в жизни.}
{102153}{}{Торговля}
# SK_GAMBLING
{102161}{}{-}
{102162}{}{Навык временно отключен.}
{102163}{}{Азартные игры.}
# SK_OUTDOORSMAN
{102171}{}{Выживание}
{102172}{}{Вы не остаетесь подолгу в закрытом помещении, а всегда в дороге. Вы многое знаете о зверях, птицах, растениях и пустыне.}
{102173}{}{Выживание}
# SK_MINING
{102181}{}{Шахтерство}
{102182}{}{Ломать камни киркой или кувалдой, добывая из них что-нибудь ценное, что может быть проще? Хотя, если найти бур... 											Навык прокачивается за счет применения.}
{102183}{}{Шахтерство}
# SK_CHOPPING
{102191}{}{Лесозаготовка}
{102192}{}{Казалось бы, бей топором по дереву и все отлично, но в идеале надо сделать так, чтобы тебя не придавило тяжелым стволом.  												Навык прокачивается за счет применения.}
{102193}{}{Лесозаготовка}
# SK_SCAVENGING
{102201}{}{Сбор мусора}
{102202}{}{И пускай богатые горожане смотрят на тебя сверху вниз, зато эта ржавая рация досталась тебе совершенно бесплатно!  											Навык прокачивается за счет применения.}
{102203}{}{Сбор мусора}
# SK_HUNTING
{102211}{}{Охота}
{102212}{}{Прицелься, задержи дыхание, спусти курок. Ну вот, ты опять испортил шкуру редкого геккона, идиот! Никто за нее и больше 10 долларов теперь не даст! 																Навык прокачивается за счет применения.}
{102213}{}{Охота}
# SK_FISHING
{102221}{}{Рыбная ловля}
{102222}{}{Тишина, спокойствие, мерзкие комары.. и шанс прокормить семью почти не рискуя собственным здоровьем.  														Навык прокачивается за счет применения.}
{102223}{}{Рыбная ловля}
# SK_FARMING
{102231}{}{Фермерство}
{102232}{}{Если месяцами растущая капуста вызывает в вас чувство успокоения, а запах дерьма брамина не заставляет глаза слезиться - то это явно ваше призвание!  												Навык прокачивается за счет применения.}
{102233}{}{Фермерство}
# SK_COOKING
{102241}{}{Кулинария}
{102242}{}{Отварить овощи? Может пожарить мясо? Запечь рыбу? Плевать, главное убить все болезнетворные микроорганизмы, а если еще и вкусно - то вы король на этой кухне.  												Навык прокачивается за счет применения.}
{102243}{}{Кулинария}
# SK_SEX
{102251}{}{Секс}
{102252}{}{Сколько можно зарабатывать тяжким трудом в шахте? Научись доставлять удовольствие и живи за чужой счет!  														Навык прокачивается за счет применения.}
{102253}{}{Секс}

# 102300
# TO_SK_FIRST_AID, timeouts
{102301}{}{Первая помощь}
# TO_SK_DOCTOR, timeouts
{102311}{}{Доктор}
# TO_SK_REPAIR, timeouts
{102321}{}{Ремонт}
# TO_SK_SCIENCE, timeouts
{102331}{}{Наука}
# TO_SK_LOCKPICK, timeouts
{102341}{}{Взлом}
# TO_SK_STEAL, timeouts
{102351}{}{Кража}

# 102380
# TO_BATTLE, timeouts
{102381}{}{Боевой}
# TO_TRANSFER, timeouts
#{102391}{}{Переходы}
# TO_REMOVE_FROM_GAME, timeouts
{102401}{}{Выход из игры}
# TO_REPLICATION, timeouts
{102411}{}{Репликация}
# TO_TIREDNESS, timeouts
{102421}{}{Усталость}
# TO_SNEAK, timeouts
{102431}{}{Скрытность}

####################################################################################################################################
#
#		Kills (from PROTO.MSG)
#
####################################################################################################################################

#
# Kill Types names
#

# 102600
# BT_MEN..BT_BIG_BAD_BOSS, bodytypes
{102601}{}{Мужчины}
{102602}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей мужского пола.}
{102611}{}{Женщины}
{102612}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей женского пола.}
{102621}{}{Детишки}
{102622}{}{Здесь указано число убитых вами за время путешествий и приключений бедных маленьких человеческих детишек.}
{102631}{}{Супер Мутанты}
{102632}{}{Здесь указано число уничтоженных вами за время путешествий и приключений Супер Мутантов.}
{102641}{}{Гули}
{102642}{}{Здесь указано число уничтоженных вами за время путешествий и приключений гулей всех видов.}
{102651}{}{Брамины}
{102652}{}{Здесь указано число порезанных вами за время путешествий и приключений браминов - мутировавших коров.}
{102661}{}{Радскорпионы}
{102662}{}{Здесь указано число уничтоженных вами за время путешествий и приключений радскорпионов.}
{102671}{}{Крысы}
{102672}{}{Здесь указано число уничтоженных вами за время путешествий и приключений крыс и им подобных.}
{102681}{}{Летатели}
{102682}{}{Здесь указано число уничтоженных вами за время путешествий и приключений летателей.}
{102691}{}{Псевдо-кентавры}
{102692}{}{Количество убитых вами псевдо-кентавров.}
{102701}{}{Роботы}
{102702}{}{Общее количество разобранных или сломанных вами в путешествиях роботов.}
{102711}{}{Собаки}
{102712}{}{Общее количество собак, отправленных вами в великую небесную конуру на веки вечные.}
{102721}{}{Мантисы}
{102722}{}{Здесь указано число передавленных вами за время путешествий и приключений мантисов, других насекомых и подобных им существ.}
{102731}{}{Когти смерти}
{102732}{}{Здесь указано число убитых вами Когтей Смерти и их сородичей.}
{102741}{}{Растения}
{102742}{}{Количество растений, безжалостно выполотых вашей рукой.}
{102751}{}{Ящеры}
{102752}{}{Поголовье ящеров, истребленных вами во время путешествий по стране.}
{102761}{}{Чужие}
{102762}{}{Число инопланетных существ, погибших от вашей руки.}
{102771}{}{Муравьи}
{102772}{}{Количество мутировавших насекомых - бывших муравьев, уничтоженных вами в пустыне.}
{102781}{}{Большие боссы}
{102782}{}{Подсчет бесноватых маньяков убийства, генетически созданных киборгов - Суперагентов, павших в бою с вами.}
{102791}{}{Гигантские жуки}
{102792}{}{Количество мутировавших жуков, уничтоженных вами в Пустоши.}
{102801}{}{Гигантские осы}
{102802}{}{Количество мутировавших гигантских ос, погибших от вашей руки.}
{102811}{}{Яо-Гаи}
{102812}{}{Здесь указано число убитых вами за время путешествий и приключений медведеподобных Яо-Гаев.}
{102821}{}{Болотники}
{102822}{}{Здесь указано число убитых вами Болотников.}
{102831}{}{Кроки}
{102832}{}{Здесь указано число убитых вами Жуткохватов и Тенехватов.}

####################################################################################################################################
#
#		Perks (with PERK.MSG)
#
####################################################################################################################################

# 103000
# PE_GAIN_STRENGTH
{103001}{}{Улучшение силы}
{103002}{}{В результате операции, вы повысили Силу на 1.}
# PE_GAIN_PERCEPTION
{103011}{}{Улучшение восприятия}
{103012}{}{В результате операции, вы повысили Восприятие на 1.}
# PE_GAIN_ENDURANCE
{103021}{}{Улучшение выносливости}
{103022}{}{В результате операции, вы повысили Выносливость на 1.}
# PE_GAIN_CHARISMA
{103031}{}{Улучшение обаяния}
{103032}{}{В результате операции, вы повысили  Обаяние на 1.}
# PE_GAIN_INTELLIGENCE
{103041}{}{Улучшение интеллекта}
{103042}{}{Этот бонус повышает на одно очко ваш Интеллект.}
# PE_GAIN_AGILITY
{103051}{}{Улучшение ловкости}
{103052}{}{В результате операции, вы повысили Ловкость на 1.}
# PE_GAIN_LUCK
{103061}{}{Улучшение удачи}
{103062}{}{Этот бонус повышает на одно очко вашу Удачу.}
# PE_LOOSE_STRENGTH
{103071}{}{Ухудшение силы}
{103072}{}{В результате операции, вы ухудшили Силу на 1.}
# PE_LOOSE_PERCEPTION
{103081}{}{Ухудшение восприятия}
{103082}{}{В результате операции, вы ухудшили Восприятие на 1.}
# PE_LOOSE_ENDURANCE
{103091}{}{Ухудшение выносливости}
{103092}{}{В результате операции, вы ухудшили Выносливость на 1.}
# PE_LOOSE_CHARISMA
{103101}{}{Ухудшение обаяния}
{103102}{}{В результате операции, вы ухудшили Обаяние на 1.}
# PE_LOOSE_INTELLIGENCE
{103111}{}{Ухудшение интеллекта}
{103112}{}{Этот бонус уменьшает на одно очко ваш Интеллект.}
# PE_LOOSE_AGILITY
{103121}{}{Ухудшение ловкости}
{103122}{}{В результате операции, вы ухудшили Ловкость на 1.}
# PE_LOOSE_LUCK
{103131}{}{Ухудшение удачи}
{103132}{}{Этот бонус уменьшает на одно очко вашу Удачу.}
# PE_SEXUAL_IMPROVEMENT
{103141}{}{Интимная пластика}
{103142}{}{Вы стали сексуальнее после хирургического вмешательства (+50 очков в навык секса).}
# PE_SILENT_RUNNING
{103161}{}{Бесшумный бег}
{103162}{}{Теперь вы будете быстро двигаться, при этом, создавая не больше шума, чем если бы вы крались на цыпочках. Ранее это было совершенно неосуществимо в силу технических причин.}
# PE_MASTER_TRADER
{103181}{}{Торговля}
{103182}{}{Вы добились настоящего мастерства в одном из аспектов торговли, а именно способности покупать товары по низким ценам, торгуясь до изнеможения. Вы получаете 25 процентов скидки на любую покупку.}
# PE_QUICK_POCKETS
{103491}{}{Оптимизация}
{103492}{}{Вам удалось рассовать свои вещи по карманам так, чтобы они всегда были под рукой. Теперь манипуляции с предметами в инвентаре стоят в два раза меньше.}
# PE_SMOOTH_TALKER
{103501}{}{Говорливость}
{103502}{}{Говорун успевает вставлять два слова там, где другие еле управляются с одним, даже если не понимает, о чем речь. Каждый уровень ваш Интеллект во время диалога будет расти на 1, вплоть до 10.}

# 104700
# ADDICTION_NUKA_COLA, addictions
{104701}{}{Привыкание к Нюка-Коле}
{104702}{}{Вам хочется еще немножко Нюка-Колы.}
# ADDICTION_BUFFOUT, addictions
{104711}{}{Привыкание к Баффауту}
{104712}{}{У вас начались судороги.}
# ADDICTION_MENTATS, addictions
{104721}{}{Привыкание к Ментату}
{104722}{}{У вас кружится голова.}
# ADDICTION_PSYCHO, addictions
{104731}{}{Привыкание к Психо}
{104732}{}{Вы не ощущаете пространства.}
# ADDICTION_RADAWAY, addictions
{104741}{}{Привыкание к Рад Эвэй}
{104742}{}{Вас мучают приступы рвоты.}
# ADDICTION_JET, addictions
{104751}{}{Привыкание к Джету}
{104752}{}{Все вокруг вас движется так медленно... вам срочно надо занюхнуть еще немного Джета!}
# ADDICTION_TRAGIC, addictions
{104761}{}{Xобби Трагика}
{104762}{}{Вы страстно жаждете распаковать очередную коробку карт Трагика.}
# ADDICTION_TREB, addictions
{104771}{}{Привыкание к Требу}
{104772}{}{Все вокруг вас движется так медленно... вам срочно надо занюхнуть еще немного Треба!}
# ADDICTION_VINT, addictions
{104781}{}{Привыкание к Винту}
{104782}{}{Все вокруг вас движется так медленно... вам срочно надо занюхнуть еще немного Винта!}

# 104800
# KARMA_BERSERKER
{104801}{}{Каннибал}
{104802}{}{Вы попробовали человечину... И вам понравилось.}
# KARMA_CHAMPION
{104811}{}{Посейдоновец}
{104812}{}{Ваши действия прославили вас достаточно, что бы вы могли кататься на танкер и обратно без билета.}
# KARMA_CHILDKILLER
{104821}{}{Убийца детей}
{104822}{}{Вы убиваете маленьких, невинных детишек, надежду и будущее пустыни. Творимое вами зло не нравится никому. Это очень плохо.}
# KARMA_SEXPERT
{104831}{}{Сексперт}
{104832}{}{Вы понимаете секс. Вы умеете показать себя в постели с лучшей стороны, и это единственное место, где вы ведете себя безупречно.}
# KARMA_PRIZEFIGHTER
{104841}{}{Чемпион бокса}
{104842}{}{Схватки на ринге заслужили вам умение драться и титул первой перчатки Северной Калифорнии. Во всем нужна сноровка, закалка, тренировка, иначе вам удачи не видать!}
# KARMA_GIGOLO
{104851}{}{Сутенер}
{104852}{}{Посмотрим правде в глаза: Вы используете продажных женщин, для зарабатывания денег.}
# KARMA_GRAVE_DIGGER
{104861}{}{Гробокопатель}
{104862}{}{Вашим лозунгом стала популярная присказка "Мертвые не кусаются". Страсть к раскопкам чужих могил и краже имущества покойных - ваше хобби.}
# KARMA_MARRIED
{104871}{}{Супружество}
{104872}{}{Поздравляем вас с успешным бракосочетанием. Теперь у вас появился спутник жизни.}
# KARMA_PORN_STAR
{104881}{}{Порнозвезда}
{104882}{}{Настал день, когда на мутном небосклоне Нью-Рено взошла новая звезда. Ваши сексуальные достоинства известны всему городу.}
# KARMA_SLAVER
{104891}{}{Работорговец}
{104892}{}{Вступление в Гильдию работорговцев навсегда изменило вашу жизнь. Татуировка на лбу говорит о вашей профессии лучше всяких слов.}
# KARMA_VIRGIN_WASTES
{104901}{}{Целомудрие}
{104902}{}{Шагая по колено в грязи, вы умудрились не запачкаться и сохранить свою чистоту в жестоком мире пустыни.}
# KARMA_MAN_SALVATORE
{104911}{}{Бандит Молоха}
{104912}{}{Молох принял вас под свое покровительство. Это известно всем.}
# KARMA_MAN_BISHOP
{104921}{}{Якудза}
{104922}{}{Вы - якудза. Это известно всем.}
# KARMA_MAN_MORDINO
{104931}{}{Ши}
{104932}{}{Вы - один из Ши. Это известно всем.}
# KARMA_MAN_WRIGHT
{104941}{}{Бандит}
{104942}{}{Вы - обычный мелкий бандит. Вас знают в регионе, но не причисляют к какой-либо из известных группировок.}
# KARMA_SEPARATED
{104951}{}{Эльдорадо}
{104952}{}{Вы в числе посвящённых в детали безопасных подходов к укреплённому району некоего довоенного объекта.}
# KARMA_PEDOBEAR
{104961}{}{Педобир}
{104962}{}{Ты трахнул невинное дитя. Как ты мог. Сволочь. Ты заработал себе неприятности на всю оставшуюся жизнь.}
# KARMA_VC_GUARDSMAN
{104971}{}{СКБ}
{104972}{}{Вы - гордый представитель Сил Корабельной Безопасности. Этот статус известен всем.}

# 105000
# DAMAGE_POISONED, damages
{105001}{}{Отравление}
{105002}{}{Ваш персонаж находится под воздействием яда. Это будет отнимать очки жизней, пока вы не вылечитесь или яд не выйдет из организма.}
# DAMAGE_RADIATED, damages
{105011}{}{Облучение}
{105012}{}{Ваш персонаж находится под воздействием поражающего эффекта радиации. Чем сильнее было облучение, тем хуже будет дальнейшая жизнь героя.}
# DAMAGE_EYE, damages
{105021}{}{Травма глаза}
{105022}{}{Ваш персонаж был серьезно ранен в один или оба глаза, теперь его Восприятие понизится. Особо уже не присмотришься.}
# DAMAGE_RIGHT_ARM, damages
{105031}{}{Травма правой руки}
{105032}{}{Правая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_LEFT_ARM, damages
{105041}{}{Травма левой руки}
{105042}{}{Левая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_RIGHT_LEG, damages
{105051}{}{Травма правой ноги}
{105052}{}{Ваш персонаж сильно охромел на правую ногу.}
# DAMAGE_LEFT_LEG, damages
{105061}{}{Травма левой ноги}
{105062}{}{Ваш персонаж сильно охромел на левую ногу.}

####################################################################################################################################
#
#		Traits (with TRAIT.MSG)
#
####################################################################################################################################

# 105500
# TRAIT_FAST_METABOLISM
{105501}{}{Быстрый метаболизм}
{105502}{}{Увеличивает уровень лечения. Уменьшает время тика лечения (увеличивает скорость пассивного лечения). Убирает устойчивость к радиации. Убирает устойчивость к ядам. Увеличивает скорость жажды и голода в 2 раза. Увеличивает начисление передозировки на 30%, но ускоряет спад передозировки на 30%.}
# TRAIT_BRUISER
{105511}{}{Крушила}
{105512}{}{Дает 3 дополнительных пункта в параметр "Сила". Уменьшает очки действия на 25.}
# TRAIT_SMALL_FRAME
{105521}{}{Xилое тело}
{105522}{}{Дает 1 дополнительный пункт в параметр Ловкость +5 кг максимального переносимого веса. Каждое очко силы дает + 6 кг максимального переносимого веса вместо + 10 кг. }
# TRAIT_ONE_HANDER
{105531}{}{Однорукий}
{105532}{}{Базовый шанс попасть с Пистолетов и ПП на 20. Все остальное дальнобойное оружие имеет базовый штраф в 40.}
# TRAIT_FINESSE
{105541}{}{Точность}
{105542}{}{Увеличивает базовый шанс критического урона на 15%. Все цели получают +30% сопротивления вашему урону.}
# TRAIT_KAMIKAZE
{105551}{}{Камикадзе}
{105552}{}{Уменьшает базовый КБ до 0. Увеличивает регенерацию ОД на 0.2 за пункт Ловкости.}
# TRAIT_HEAVY_HANDED
{105561}{}{Громила}
{105562}{}{Увеличивает Рукопашный урон на 1 за каждый пункт параметра Сила. Уменьшает регенерацию ОД на 0.35 за каждый пункт Силы.}
# TRAIT_FAST_SHOT
{105571}{}{Быстрый стрелок}
{105572}{}{Все атаки тратят на 15% меньше ОД. Прицельный огонь вести нельзя, при этом 66% атак будут в случайное место.}
# TRAIT_BLOODY_MESS
{105581}{}{Маньяк}
{105582}{}{Ваши атаки и добивания приводят к анимации критической смерти. Ваша смерть так же будет критической. Все вокруг видят ваше странное поведение. Штрафа при стрельбе по добродушным отсутствует.}
# TRAIT_JINXED
{105591}{}{Дурной глаз}
{105592}{}{У вас и ваших врагов 10% промахов становятся критическими промахами.}
# TRAIT_GOOD_NATURED
{105601}{}{Добродушие}
{105602}{}{Дает 25 очков навыков к Доктору, Санитару, Торговле.	Снимает 20 очков навыков с Оружейных Скиллов. Базовый шанс попасть по вам снижен на 30, если враг не Маньяк.}
# TRAIT_CHEM_RELIANT
{105611}{}{Неуст. к химии}
{105612}{}{Побочный эффект от наркотиков (2я стадия) длится вдвое МЕНЬШЕ, шанс привыкания к любым наркотикам вдвое БОЛЬШЕ. УВЕЛИЧИВАЕТ лечение препаратами и передозировку от них на 30%. Нельзя брать с трейтом Уст. к химии.}
# TRAIT_CHEM_RESISTANT
{105621}{}{Уст. к химии}
{105622}{}{Эффект наркотиков длится вдвое МЕНЬШЕ, как и ломка от них. УМЕНЬШАЕТ лечение препаратами и передозировку от них на 30%. Нельзя брать с трейтом Неуст. к химии.}
# TRAIT_SEX_APPEAL
{105631}{}{Чуткость}
{105632}{}{Вы получаете на 50% больше опыта, но на 50% больше урона.}
# TRAIT_SKILLED
{105641}{}{Умелец}
{105642}{}{Дает бонус к стартовым навыкам. Опыт начисляется в 2 раза медленней начисление полученого опыта}
# TRAIT_NIGHT_PERSON
{105651}{}{Ночная персона}
{105652}{}{Дает 1 пункт к Интелекту и Восприятию в ночное время суток (от 18:01 до 06:00), и уменьшаются тоже на один днем (от 06:01 до 18:00). РАСЧЕТ ИДЕТ ПО ИГРОВОМУ ВРЕМЕНИ.}

# Armor race restrictions
{105663}{}{Эта броня предназначена для мутантов - вы не можете одеть ее.}
{105664}{}{Эта броня предназначена для людей - вы не можете одеть ее.}

# Reputation groups
#105700
# REPUTATION_DEN
{105701}{}{Яма}
# REPUTATION_KLAMATH
{105711}{}{Кламат}
# REPUTATION_MODOC
{105721}{}{Модок}
# REPUTATION_VAULT_CITY
{105731}{}{Город Убежище}
# REPUTATION_GECKO
{105741}{}{Гекко}
# REPUTATION_BROKEN_HILLS
{105751}{}{Брокен Хиллс}
# REPUTATION_NEW_RENO
{105761}{}{Нью Рено}
# REPUTATION_SIERRA
{105771}{}{Cьерра}
# REPUTATION_VAULT15
{105781}{}{Убежище 15}
# REPUTATION_NCR
{105791}{}{НКР}
# REPUTATION_CATHEDRAL
{105801}{}{Собор}
# REPUTATION_MARIPOSA
{105811}{}{Военная база}
# REPUTATION_REDDING
{105821}{}{Реддинг}
# REPUTATION_SF
{105831}{}{Сан-Франциско}
# REPUTATION_NAVARRO
{105841}{}{Наварро}
# REPUTATION_ARROYO
{105851}{}{Арройо}
# REPUTATION_PRIMAL_TRIBE
{105861}{}{Примитивное племя}
# REPUTATION_RANGERS
{105871}{}{Рейнджеры}
# REPUTATION_VAULT13
{105881}{}{Убежище 13}
# REPUTATION_SACRAMENTO
{105891}{}{Сакраменто}

####################################################################################################################################
#
#		Dynamic Item Lexems:
#
####################################################################################################################################

{110000}{}{STATE NAME VALUE.}
{110001}{}{DESC.}
#STATE
{120000}{}{Обычная}
{120001}{}{Свежая}
#VALUE
{130000}{}{мусора}
{130001}{}{мяса}
#DESC
{140000}{}{Вы не видите ничего обычного}
{140001}{}{Вас тошнит от одного только вида}

####################################################################################################################################
#
#		Repair
#
####################################################################################################################################

{155080}{}{Нет подходящих шкур чтобы залатать дыры}
{155090}{}{Нет подходящих кусков кожи чтобы починить броню}
{155100}{}{Нет подходящих металлических листов чтобы починить броню}
{155110}{}{Необходима кувалда для работы с металлическими листами}
{155120}{}{Необходима дрель для работы с закаленными листами}
{155130}{}{Нет подходящих закаленных металлических листов чтобы починить броню}
{155140}{}{Необходимы хитиновые пластины и панцири чтобы починить броню}
{155150}{}{Необходима дрель для работы с панцирями болотников}
{155160}{}{Необходима дрель для работы с материалами}
{155170}{}{Необходимы химикаты для починки брони}
{155180}{}{Вам кажется, что для починки этой брони явно не хватает каких то деталей. Еще бы знать каких...}
{155190}{}{Вам нужен всякий хлам для починки этого оружия}
{155200}{}{Вам нужны запчасти для починки этого оружия}
{155210}{}{Вам нужны запчасти, скорее всего - детали электроники, которая применялась в прошлом}
{155220}{}{Вам нужны механические детали чтобы починить это оружие}
{155230}{}{Вам нужны качественные заводские запчасти. Такие сейчас вряд ли найдешь}

####################################################################################################################################
#
#		Misc2 values names (100000 + pid*10 + number of val)
#
####################################################################################################################################

{1001000}{}{Заряд}
{1001001}{}{}
{1001002}{}{}

####################################################################################################################################
#
#		Update Info (1500000)
#
####################################################################################################################################

{1500000}{}{Приятной игры!}

####################################################################################################################################
#
#		Intellect words
#
####################################################################################################################################

{1999000000}{}{
я  моя
ты  твоя
вы  ваша
мы  наша
меня  мою
мне  моей
тебя  твою
сказал  сказать
скажу  сказать
скажи  сказать
убил  убивай
убили  убивай
убью  убивай
убей  убивай
украл  украсть
укради  украсть
своровал  украсть
своруй  украсть
воровать  красть
хочу  хотеть
хотел  хотеть
положил  положить
положи  положить
дал  давать
дай  давать
верни  вернуть
вернул  вернуть
верну  вернуть
отдай  отдать
отдал  отдать
отдам  отдать
могу  мочь
говорить  гварить
говорю  гварить
понимаю  понимать
они  их
думаю  думать
думайте  думать
думаем  думать
думай  думать
бежать  бечь
бегу  бечь
беги  бечь
бегите  бечь
бежим  бечь
побежал  бечь
побежали  бечь
идти  ити
идти  ходить
хожу  ходить
интеллект  ум
взял  взять
взяли  взять
возьми  взять
возьмите  взять
возьму  взять
возьмем  взять
злодей  плохой
злодей  злой
убийца  плохой
убийца  злой
бандит  плохой
бандит  злой
рейдер  плохой
рейдер  злой
злодеи  плохие
злодеи  злые
убийцы  плохие
убийцы  злые
бандиты  плохие
бандиты  злые
рейдеры  плохие
рейдеры  злые
брамин  му-му
брамины  му-му
коровы  му-му
корова  му-му
караван  корован
караваны  корованны
дерьмо  какашки
черт  шайтан
иду  ходить
иди  ходить
пошел  ходить
пошли  ходить
пойду  ходить
пойди  ходить
пришел  приходить
шел  ходил
присоединяйся  твоя ходить за моей
присоединись  твоя ходить за моей
присоединяйтесь  ваша ходить за нашей
присоединитесь  ваша ходить за нашей
присоединился  твоя ходить за моей
присоединяемся  наша ходить за вашей
присоединились  наша с вашей ходить
присоединяюсь  моя ходить за твоей
присоединюсь  моя ходить за твоей
научи  научай
научите  научайте
моего  мой
моих  мои
моего  мое
мою  мой
враг  плохой
враг  злой
враги  злые
друг  хороший
друг  приятный
друга  хорошево
друзья  други
друзья  хорошие
нормальный  хороший
нормальные  хорошие
привет  моя приветствует
здравствуй  моя здаровается
здравствуйте  моя здаровается
машина  би-бип
хамер  би-бип
джип  би-бип
оружие  пиу-пиу
наркотики  кайфуха
говорить  гварить
говори  гвари
говорил  гварил
монеты  блестяшки
деньги  бумажки
ночь  темно
ночью  теменью
день  светло
днем  светлым
вода  пить
пистолет  рукострел
пистолета  рукострела
автомат  многострел
автомата  многострела
молотов  хыдыщка
граната  бум-камень
гранату  бум-камень
гранаты  бум-камня
джет  летало
броня  панцирь
брони  панциря
мужик  чумба
парень  чумбак
геккон  ящерка
брамин  мумука
ванаминго  страшилка
скорпион  больножало
крыса  пищало
крыс  пищал
крысы  пищалы
мантис  кусало
мантисы  кусалы
мантисов  кусал
муравей  ковыряло
муравьи  ковырялы
коготь  царапка
дорога  ходилка
дороге  ходилке
секс  вуху
нюка  сладкая
нюки  сладкой
нюку  сладкую
живот  урчало
живота  урчала
глаза  смотрелки
глаз  гляделка
сердце  стучало
голова  думала
голову  думало
нога  ходило
ноги  ходила
рука  хватало
рук  хватал
руку  хватало
сэр  сер
мисс  сериха
мэм  сериха
рот  гварило
рта  гварила
губы  шептало
курок  нажимало
пуля  жало
госпожа  господюха
пропуск  проходилка
мыться  чиститься
хуй  мамук
член  джагон
женщина  самка
негр  уголек
негры  угольки
негра  уголька
полицейский  воин
солдат  воин
ура  ууууу
люди  людишки
город  племя
грудь  титька
сиски  титьки
сиська  титька
киска  рождало
копье  тыкалка
порох  взрывало
пороха  взрывала
мусор  грязь
хлам  грязь
нож  пыряло
ножа  пыряла
рана  больно
ранили  больно
солдат  воин
наемник  продавашка
замок  закрывало
замка  закрывала
ключ  открывачка
ключа  открывачки
металл  железяка
дела  важный
богатый  хозяин
бедный  раб
кентавр  страшилка
кентавра  страшилки
ванаминго  страшилка
коготь  острый
отвертка  крутило
волк  лаялка
стая  клан
дикарь  брат
дикари  братья
блять  ой
бля  уф
пиздец  пизданга
блядь  ай
сука  самка
путы  вязало
пизда  пися
пиво  газира
мудак  вонючий
мудака  вонючего
мудаков  вонючих
мразь  злюка
мрази  злюки
пидор  враг
пидар  враг
пидр  враг
пидорас  вражина
пидарас  вражина
бить  дубасить
руины  камни
жертва  битый
грабеж  отбирало
собака  гавка
щенок  тяфка
кувалда  стучало
молоток  стучало
пещера  темный
лево  тама
право  тута
влево  туда
вправо  сюда
слева  тама
справа  тута
их  ихний
его  евоный
ее  еёшный
врач  шаман
врача  шамана
книга  читало
стимулятор  лечило
стим  лечило
шило  тыка
охота  следило
порошок  сыпа
Джек  Жек
Боб  Биба
Брюс  Рюс
Том  Тум
Кейт  Эйт
Джон  Жон
Фрэнк  Рэнк
Стивен  Стива
Стив  Стива
Тонни  Тоня
мэр  главный
мэра  главного
шериф  вождь
шерифа  вождя
металлический  блестящий
металический  блестящий
ржавый  рыжий
ржавого  рыжего
гараж  стояло
бинт  моталка
бинта  моталки
пиво  жижа
дурак  глупый
дурака  глупого
бутылка  стекляха
бутылки  стекляхи
трахать  тыркать
трахаться  тыркаться
полиция  синий
полицейского  синего
винтовка  пуляло
винтовки  пулялы
дробовик  бумпалка
дробовика  бумпалки
гуль  мертвяк
гули  мертвяки
гуля  мертвяка
дерево  растило
дерева  растила
убивать  мертвить
убей  мертви
лох  дурак
чмо  слабый
рыба  плескало
удочка  ловилка
удочки  ловилки
крючок  цепляло
язык  лизало
языка  лизала
привет  здрав
приветик  здравик
амазонка  баба-воин
амазонки  бабы-воина
больной  болящий
больного  болящего
шляпа  голова
шляпы  головы
штаны  штанцы
штанов  штанцов
палец  ковыряло
пальца  ковыряло
один  адин
два  пара
три  много
четыре  пары
пять  много
шесть  много
семь  много
восемь  много
девять  много
десять  много
сто  много
тысяча  много
ударил  жмыхнул
ударила  жмыхнула
каннибал  людожуй
каннибала  людожуя
вкусно  нямно
еда  нямка
нос  нюхало
носа  нюхало
поцелуй  лабзало
целовать  лабызать
холодильник  холодный
рация  говорилка
рации  говорилки
рыбачить  удачить
рыбак  удачник
форт  застенок
стена  опиралка
стене  опиралке
бочка  подпиралка
бочки  подпиралки
бочке  подпиралке
мясо  жрало
кулак  стучало
кулака  стучала
болевой  болючий
бар  абыр
бара  абыр
бару  абыр
бармен  абырвалг
бармена  абырвалга
отмычка  ломало
отмычки  ломаты
проститутка  давала
проститутки  давалы
пернул  срень
перданул  сренюл
работа  деланье
закон  главнюк
награда  дары
зарплата  дар
платье  одежа
Мари  Марин
Мария  Маруя
Марин  Маруна
Дженни  Жени
Китти  Китя
Сара  Тара
Саре  Таре
Анна  Ана
Анне  Ане
Ренни  Реня
Руфус  Рукус
Руфусу  Рукусу
Ральф  Фальф
Ральфу  Фальфу
робот  жужало
Чарльз  Арльз
Чарльзу  Арльзу
Роджер  Воджер
Роджеру  Воджеру
Джефри  Жефри
Джеффри  Жефри
Шарлотта  Шарла
Шарлота  Шарла
Шарлотты  Шарлы
Шарлоты  Шарлы
Шарлотте  Шарле
Шарлоте  Шарле
Линдси  Линси
Майкл  Майло
Майкла  Майлу
мой  мойный
чужой  евоный
кровать  лежак
кровати  лежака
диван  лежак
дивана  лежака
постель  лежак
постели  лежака
документ  бамажки
гражданин  ражданин
процедура  обряд
регистрация  страция
умный  вумный
умного  вумного
умных  вумных
живу  сплю
дом  отдыхалка
квартира  отдыхалка
огонь  горячий
огня  огрячего
костер  горчий
костра  горячего
пожар  горячий
пожара  горячего
ферма  животиночная
братство  единство
любить  вухать
ремень  держало
ремня  держала
сапоги  ходилки
сапог  ходилка
зажигалка  горячий
сигарета  дымило
сигарет  дымилок
пачка  коробка
пачек  коробок
пачки  коробки
плазма  пиу-жижа
лазер  пиу-свет
лицензия  разрешалка
дождь  мокрый
дождя  мокрого
голод  урчила
голоден  уручил
тарелка  подавалка
тарелки  подавалки
блюдо  вкуснохава
забор  граничило
забора  граничила
пол  ходило
земля  копала
лопата  копалка
лопаты  копалки
навоз  воняло
наваза  вонялы
лицо  смотрило
лица  смотрилы
рана  болеть
ранить  болеть
ранило  болеть
душ  чистить
туалет  пщщ
унитаз  пщщ
столы  столья
стулья  стулы
свет  солнце
обувь  ходилки
яйца  звенелы
яйцо  звенело
гнездо  спальник
лагерь  отдыхало
обойма  заряжало
обоймы  заряжалы
обойму  заряжалу
обоима  заряжало
обоимы  заряжалы
обоиму  заряжалу
должен  быстра
обязан  быстра
много  во-от столько 
мало  нету
идти  ходить
далеко  во-он там
близко  здеся
очень  сильно
завтра  скоро
послезавтра  не знаю
вчера  не помнить
ходил  ходить
знаю  да
понял  наверно
послушай  твоя слушать моя
давай  моя хотеть
можно  да
пойдем  ходить
пойдём  ходить
идем  ходить
идём  ходить
очень сильна
}

{1999000001}{}{}

####################################################################################################################################
#
#		Help
#
####################################################################################################################################

# F7 - Включить/выключить подсветку имен нпц.
# F9 - Включить/выключить трассировку траектории выстрела.

{2000000000}{}{
Горячие клавиши в игре:

F1 - Включить/выключить помощь.
F2 - Сохранить сообщения в файл.
F3 - Сохранить скриншот.
F4 - Вкл./Выкл. отображение панели ввода текста.
F5 - Вкл./Выкл. расширение окна сообщений.
F6 - Включить/выключить подсветку имен игроков.
F8 - Включить/выключить скроллинг карты мышкой (помогает в оконном режиме).
F12 - Сворачивание клиента.
Указатели - скроллинг карты.
Esc - меню.
Pause/Break - пунтосвитчер в командной строке.
<,> - Вращаться против часовой или по часовой стрелке.
Home - центрирование на персонаже (на карте и на глобале).
A - Атака.
G - Подобрать итем под ногами.
C - Персонаж.
I - Инвентарь.
P - Пипбой.
F - Фиксбой.
B - Переключение активных слотов.
M - Переключение меню мыши.
N - Переключение режима итема.
S - Панель навыков.
Z - Масштабирование карты.
1-8 - Выбор навыка.
? - Текущее игровое время.
+,- - Регулирование яркости.
Ctrl + +,- - Регулирование громкости звуков.
Shift + +,- - Регулирование громкости музыки.
Alt + +,- - Регулирование Sleep.

Команды для общения:
первый символ . или / потом:
к К s S - кричать,
ш Ш w W - шептать,
э Э e E - эмоция,
р Р r R - рация.
После пробел можно не ставить, а если и поставите, то он игнорируется.
Введите сообщение и нажмите Enter.

Так же возможна отправка сообщений с помощью:
Ctrl + Enter - крик,
Alt + Enter - шепот,
Shift + Enter - рация.
}

####################################################################################################################################
#
#		Credits
#
####################################################################################################################################

# # == "|0xff8c8c84 "
# @ == "|0xff706050 "
# normal == "|0xff907824 "

{2000001000}{}{35} # Speed
{2000001010}{}{
[1997] - Fallout 1.

[1998] - Fallout 2.

[2000-2010] - Fallout modding community.

[<2013] - TLA FODEV Community.

[<2016] - TNF Roleplay Community.

[02.2019] - FO4RP Comminuty.

[06.2021] - FoRP EN Community.

Это был долгий путь.

Спасибо, что вы есть!

}
# Shift + Credits
{2000001020}{}{
Hello world!
}