
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{Глобальная карта}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

##### PERFECTION ####

# Area 1, Map 10
{110}{}{sandbox1_1}
{115}{}{34Cataclysm.ogg}
{116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{118}{}{Болото}

# Area 2, Map 12
{130}{}{sandbox1_2}
{135}{}{under_1.ogg}
{136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{138}{}{Западный склон}

# Area 3, Map 14
{150}{}{sandbox1_3}
{155}{}{03 - A Way To Anywhere.ogg}
{156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{158}{}{Вершина}

# Area 4, Map 16
{170}{}{sandbox1_4}
{175}{}{14 - Organic Shadows.ogg}
{176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{178}{}{Восточный склон}

# Area 5, Map 18
{190}{}{sandbox1_5}
{195}{}{36E3_Among_the_Friends.ogg}
{196}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{198}{}{Ферма}

# Area 6, Map 20
{210}{}{sandbox2_1}
{215}{}{55NNM_wind_of_war.ogg}
{216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{218}{}{Болотистый лес}

# Area 7, Map 22
{230}{}{sandbox2_2}
{235}{}{50NNM_radioluminescence.ogg}
{236}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{238}{}{Юго-западный склон}

# Area 7, Map 23
{240}{}{sandbox2_2dn}
{245}{}{58Tales_of_the_Past.ogg}
{246}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{248}{}{Зарядная станция}

# Area 8, Map 24
{250}{}{sandbox2_3}
{255}{}{28Rangers-journey.ogg}
{256}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{258}{}{КПП}

# Area 8, Map 25
{260}{}{sandbox2_3dn}
{265}{}{under_1.ogg}
{265}{}{41NNM_bonus.ogg}
{265}{}{42NNM_ghost_town.ogg}
{265}{}{43NNM_high_wind.ogg}
{265}{}{44NNM_improper_subdivision.ogg}
{265}{}{45NNM_jammer.ogg}
{265}{}{46NNM_line_of_policy.ogg}
{265}{}{47NNM_nevada_theme.ogg}
{265}{}{48NNM_new_vegas.ogg}
{265}{}{49NNM_radiationless.ogg}
{265}{}{50NNM_radioluminescence.ogg}
{265}{}{51NNM_ride_to_cheyenne.ogg}
{265}{}{52NNM_root_information.ogg}
{265}{}{53NNM_village.ogg}
{265}{}{54NNM_we_are_sorry.ogg}
{265}{}{55NNM_wind_of_war.ogg}
{266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{268}{}{Перфекшен}

# Area 9, Map 30
{310}{}{sandbox2_4}
{315}{}{38Into_The_ACID_Breach.ogg}
{316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{318}{}{Юго-восточный склон}

# Area 10, Map 32
{330}{}{sandbox2_5}
{335}{}{37E1_Into_the_Tower.ogg}
{336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{338}{}{Холмы}

# Area 11, Map 34
{350}{}{sandbox3_1}
{355}{}{44NNM_improper_subdivision.ogg}
{356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{358}{}{Восточный лес}

# Area 12, Map 36
{370}{}{sandbox3_2}
{375}{}{49NNM_radiationless.ogg}
{376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{378}{}{Поворот}

# Area 13, Map 38
{390}{}{sandbox3_3}
{395}{}{26A_Candle_in_the_Darkness.ogg}
{396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{398}{}{Подстанция}

# Area 13, Map 39
{400}{}{sandbox3_3dn}
{405}{}{45NNM_jammer.ogg}
{406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{408}{}{Служебные помещения}

# Area 14, Map 40
{410}{}{sandbox3_4}
{415}{}{27Lost_Knowledge.ogg}
{416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{418}{}{Магазины}

# Area 13, Map 41
{420}{}{sandbox3_4dn}
{425}{}{42NNM_ghost_town.ogg}
{426}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{428}{}{Старая лаборатория}

# Area 15, Map 42
{430}{}{sandbox3_5}
{435}{}{31old_earth.ogg}
{436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{438}{}{Окраина}

# Area 16, Map 44
{450}{}{sandbox4_1}
{455}{}{54NNM_we_are_sorry.ogg}
{456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{458}{}{Юго-западный лес}

# Area 17, Map 46
{470}{}{sandbox4_2}
{475}{}{41NNM_bonus.ogg}
{476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{478}{}{Перекрёсток}

# Area 18, Map 48
{490}{}{sandbox4_3}
{495}{}{53NNM_village.ogg}
{496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{498}{}{Холм}

# Area 18, Map 49
{500}{}{sandbox4_3dn}
{505}{}{58the25vault.ogg}
{506}{}{pebble:5, pebble1:10}
{508}{}{Старая шахта}

# Area 19, Map 50
{510}{}{sandbox4_4}
{515}{}{45NNM_jammer.ogg}
{516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{518}{}{Форт}

# Area 19, Map 50
{520}{}{sandbox4_4}
{525}{}{{26A_Candle_in_the_Darkness.ogg}
{526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{528}{}{Подвал Форта}

# Area 20, Map 52
{530}{}{sandbox4_5}
{535}{}{47NNM_nevada_theme.ogg}
{536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{538}{}{Бродвей}

# Area 21, Map 54
{550}{}{sandbox5_1}
{555}{}{57SHK_sinless_From_Seattle.ogg}
{556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{558}{}{Южный лес}

# Area 22, Map 56
{570}{}{sandbox5_2}
{575}{}{52NNM_root_information.ogg}
{576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{578}{}{Мотель}

# Area 23, Map 58
{590}{}{sandbox5_3}
{595}{}{42NNM_ghost_town.ogg}
{596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{598}{}{Сток}

# Area 24, Map 60
{610}{}{sandbox5_4}
{615}{}{51NNM_ride_to_cheyenne.ogg}
{616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{618}{}{Кэмпинг}

# Area 25, Map 62
{630}{}{sandbox5_5}
{635}{}{43NNM_high_wind.ogg}
{636}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{638}{}{Лагерь гулей}

# Area 26, Map 69
{700}{}{sandbox5_5}
{705}{}{Desert_wind.ogg}
{706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{708}{}{Могильник}

# Area 27, Map 70
{710}{}{sandbox_bos_dn1}
{715}{}{29mark-morgan-curst.ogg}
{716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{718}{}{Погреб}

# Area 27, Map 71
{720}{}{sandbox_bos_dn2}
{725}{}{Metallic Monks.ogg}
{726}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{728}{}{База "Хельхейм"}

# Area 27, Map 72
{730}{}{sandbox_bos_dn3}
{735}{}{mscTimestream.ogg}
{736}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{738}{}{База "Хельхейм" Технический уровень}

##### POSEIDON #####

# Area 110, Map 185
{1860}{}{tanker_deck0}
{1865}{}{30 - Clockwork.ogg}
{1866}{}{gntlwin1:5, gntlwind:5, gustwin1:5, gustwind:5, seagull:10, seagull1:10, seawind:5, seawind1:5, waves:15, waves1:15}
{1868}{}{Верхняя палуба}

# Area 110, Map 186
{1870}{}{tanker_deck1}
{1875}{}{01hub.acm}
{1876}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, laughte1:5, laughter:5, water:5, water1:5, waves:5, waves1:5}
{1878}{}{Торговая палубы}

# Area 110, Map 187
{1880}{}{tanker_deck2}
{1885}{}{akiss.acm}
{1886}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{1888}{}{Барная палуба}

# Area 110, Map 188
{1890}{}{tanker_deck3}
{1895}{}{06 - Cluster Decay.ogg}
{1896}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{1898}{}{Инженерная палуба}

# Area 110, Map 189
{1900}{}{tanker_deck4}
{1905}{}{29mark-morgan-curst.ogg}
{1906}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{1908}{}{Дыра}

# Area 110, Map 190
{1910}{}{tanker_str}
{1915}{}{27Lost_Knowledge.ogg}
{1916}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1918}{}{Башня}

# Area 110, Map 191
{1920}{}{tanker_sub1}
{1925}{}{29mark-morgan-curst.ogg}
{1926}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1928}{}{Подпалуба №1}

# Area 110, Map 192
{1930}{}{tanker_sub2}
{1935}{}{29mark-morgan-curst.ogg}
{1936}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1938}{}{Подпалуба №2}

# Area 110, Map 193
{1940}{}{tanker_sub3}
{1945}{}{29mark-morgan-curst.ogg}
{1946}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1948}{}{Подпалуба №3}

##### NCR LOCATIONS #####

# Area 111, Map 200
{2010}{}{NCR}
{2015}{}{24redd.acm}
{2016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2018}{}{НКР}

##### RENO LOCATIONS #####

# Area 112, Map 201
{2020}{}{new_reno}
{2025}{}{24redd.acm}
{2026}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2028}{}{Нью Рено}

##### Frisco ####

# Area 114, Map 221
{2220}{}{stop2_frisco1_2}
{2225}{}{31old_earth.ogg}
{2226}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{2228}{}{Порт Сан-Франциско}

# Area 117, Map 224
{2250}{}{stop2_frisco2_2}
{2255}{}{39SHK_Heoi.ogg}
{2256}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2258}{}{Центр Сан-Франциско}

# Area 118, Map 226
{2270}{}{stop2_frisco2_3}
{2275}{}{56SHK_Prosperity.ogg}
{2276}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2278}{}{Отель Сан-Франциско}

# Area 118, Map 227
{2280}{}{stop2_frisco2_3dn}
{2285}{}{21sf.acm}
{2286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2288}{}{Отель Сан-Франциско подвалы}

# Area 118, Map 228
{2290}{}{stop2_frisco2_3up}
{2295}{}{40SHK_Club88.ogg}
{2296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2298}{}{Отель Сан-Франциско Клуб}

# Area 118, Map 229
{2300}{}{stop2_frisco2_3up2}
{2305}{}{21sf.acm}
{2306}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2308}{}{Отель Сан-Франциско 2й этаж отеля и 2е этажи}

# Area 118, Map 230
{2310}{}{stop2_frisco2_3up3}
{2315}{}{21sf.acm}
{2316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2318}{}{Отель Сан-Франциско 3й этаж отеля }

# Area 118, Map 231
{2320}{}{stop2_frisco2_3up4}
{2325}{}{21sf.acm}
{2326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2328}{}{Отель Сан-Франциско 4й этаж отеля}


#####HELL OF ANUBIS#####

{4010}{}{hell}
{4015}{}{33DOOM.ogg}
{4016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15, pebble:25, pebble1:15, ore:10, ore1:10}
{4018}{}{АД}
	
#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{Вы наткнулись на @lex who@.}
#{10000011}{}{Вы наткнулись на @lex who@ и @lex player@.}
#{10000012}{}{Вы наткнулись на @lex who@ и банду @lex player@.}
#{10000013}{}{Вы наткнулись на @lex player@.}
#{10000014}{}{Вы наткнулись на банду @lex player@.}
#{10000020}{}{Вы хотите увидеть @lex who@?}
#{10000021}{}{Вы хотите увидеть @lex who@ и @lex player@?}
#{10000022}{}{Вы хотите увидеть @lex who@ и банду @lex player@?}
#{10000023}{}{Вы хотите увидеть @lex player@?}
#{10000024}{}{Вы хотите увидеть банду @lex player@?}
