
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{Глобальная карта}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

##### MODOC ####

# Area 1, Map 1
{20}{}{Modoc reach}
{25}{}{18modoc}
{26}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}
{28}{}{Богатый район}

# Area 2, Map 4
{50}{}{Modoc administrative}
{55}{}{18modoc}
{56}{}{gntlwin1:25, gntlwind:25, animal1:20, laughter:15, animal:20, winddoor:20, gustwin1:5, gustwin1:5}
{58}{}{Административный район}

# Area 3, Map 6
{70}{}{Modoc work}
{75}{}{18modoc}
{76}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}
{78}{}{Рабочий район : Север}

# Area 4, Map 9
{100}{}{Modoc bum}
{105}{}{18modoc}
{106}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}
{108}{}{Трущебы}

# Area 5, Map 10
{110}{}{Modoc entrance}
{115}{}{18modoc}
{116}{}{electri1:15, electric:15, gntlwin1:20, gntlwind:20}
{118}{}{Вход в город}
# Area 6, Map 13
{140}{}{Modoc work1}
{145}{}{18modoc}
{146}{}{dogbark:10, dogbark1:10, gntlwind:20, gntlwin1:20, blank:40}
{148}{}{Рабочий район : Юг}
# Area 7, Map 15
{160}{}{Modoc cemetery}
{165}{}{14necro}
{166}{}{dogbark:10, dogbark1:10, gntlwind:20, gntlwin1:20, blank:40}
{168}{}{Кладбище}
# Area 8, Map 16
{170}{}{Modoc app1}
{175}{}{03wrldmp}
{176}{}{gntlwin1:30, gntlwind:30, gustwin1:10, gustwind:10, vulture:10, vulture1:10}
{178}{}{Заправка}
# Area 9, Map 17
{180}{}{Modoc toxic}
{185}{}{03wrldmp}
{186}{}{laughter:10, laughte1:10, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{188}{}{Токсичное болото}
# Area 10, Map 18
{190}{}{Modoc app3}
{195}{}{03wrldmp}
{196}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{198}{}{Окрестности города}
# Area 11, Map 19
{200}{}{Modoc app3}
{205}{}{modapp5}
{206}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{208}{}{Пустошь}
# Area 12, Map 20
{210}{}{modapp6}
{215}{}{03wrldmp}
{216}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{218}{}{Дорога}

# Area 46, Map 30
{310}{}{phoenix_0}
{315}{}{27Lost_Knowledge.ogg}
{316}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{318}{}{Феникс, уровень 0}

# Area 41, Map 31
{320}{}{phoenix_1}
{325}{}{32Acolytes_of_the_New_God.ogg}
{326}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{328}{}{Феникс, уровень 1}

# Area 29, Map 38
{390}{}{ghostfarm}
{395}{}{54NNM_we_are_sorry.ogg}
{396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{398}{}{Ферма}

##### SATTER ####

{610}{}{Satter 1 1}
{615}{}{13carvrn}
{616}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{618}{}{Руины: Северо-Запад}

{620}{}{Satter 1 1 dn}
{625}{}{13carvrn}
{626}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{628}{}{Тоннели: Северо-Запад}

{640}{}{Satter 1 2}
{645}{}{13carvrn}
{646}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{648}{}{Кратер: Север}

{650}{}{Satter 1 2 dn}
{655}{}{13carvrn}
{656}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{658}{}{Тоннели: Север}

{660}{}{Satter 1 3}
{665}{}{13carvrn}
{666}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{668}{}{Церковь: Север}

{670}{}{Satter 1 3 dn}
{675}{}{13carvrn}
{676}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{678}{}{Тоннели: Север}

{680}{}{Satter 1 4}
{685}{}{13carvrn}
{686}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{688}{}{Магазины: Северо-Восток}

{690}{}{Satter 1 4 dn}
{695}{}{13carvrn}
{696}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{698}{}{Тоннели: Северо-Восток}

{700}{}{Satter 2 1}
{705}{}{13carvrn}
{706}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{708}{}{Руины: Запад}

{710}{}{Satter 2 1 dn}
{715}{}{13carvrn}
{716}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{718}{}{Тоннели: Запад}

{720}{}{Satter 2 4}
{725}{}{13carvrn}
{726}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{728}{}{Руины: Восток}

{730}{}{Satter 2 4 dn}
{735}{}{13carvrn}
{736}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{738}{}{Тоннели: Восток}

{740}{}{Satter 3 1}
{745}{}{13carvrn}
{746}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{748}{}{Железка: Запад}

{750}{}{Satter 3 1 dn}
{755}{}{13carvrn}
{756}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{758}{}{Тоннели: Запад}

{760}{}{Satter 3 4}
{765}{}{13carvrn}
{766}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{768}{}{Железка: Восток}

{770}{}{Satter 3 4 dn}
{775}{}{13carvrn}
{776}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{778}{}{Тоннели: Восток}

{780}{}{Satter 4 1}
{785}{}{13carvrn}
{786}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{788}{}{Станция: Юго-Запад}

{790}{}{Satter 4 1 dn}
{795}{}{13carvrn}
{796}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{798}{}{Тоннели: Юго-Запад}

{800}{}{Satter 4 2}
{805}{}{13carvrn}
{806}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{808}{}{Руины: Юг}

{810}{}{Satter 4 2 dn}
{815}{}{13carvrn}
{816}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{818}{}{Тоннели: Юг}

{820}{}{Satter 4 3}
{825}{}{13carvrn}
{826}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{828}{}{Парк: Юг}

{830}{}{Satter 4 3 dn}
{835}{}{13carvrn}
{836}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{838}{}{Тоннели: Юг}

{840}{}{Satter 4 4}
{845}{}{13carvrn}
{846}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{848}{}{Казино: Юго-Восток}

{850}{}{Satter 4 4 dn}
{855}{}{13carvrn}
{856}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{858}{}{Тоннели: Юго-Восток}

{890}{}{Satter center}
{895}{}{13carvrn}
{896}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{898}{}{Центрайльный Район}

{900}{}{Satter center dn}
{905}{}{13carvrn}
{906}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{908}{}{Тоннели: Центрайльный Район}

##### STOP 1 ####

# Area 100, Map 175
{1761}{}{stop1_ruin3_1}
{1765}{}{03wrldmp}
{1766}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1768}{}{Сток}

# Area 101, Map 176
{1771}{}{stop1_ruin3_2}
{1775}{}{17arroyo}
{1776}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1778}{}{Кэмпинг}

# Area 102, Map 177
{1780}{}{stop1_ruin1_1}
{1785}{}{02 - Into The Dust.ogg}
{1786}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{1788}{}{Подстанция}

# Area 103, Map 178
{1790}{}{stop1_ruin1_2}
{1795}{}{04 - 12H. Dusk.ogg}
{1796}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{1798}{}{Магазины}

# Area 104, Map 179
{1800}{}{stop1_ruin1_3}
{1805}{}{26A_Candle_in_the_Darkness.ogg}
{1806}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{1808}{}{Пирс}

# Area 105, Map 180
{1810}{}{stop1_ruin2_1}
{1815}{}{18modoc.acm}
{1816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1818}{}{Холм}

# Area 106, Map 181
{1820}{}{stop1_ruin2_2}
{1825}{}{12junktn.acm}
{1826}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1828}{}{Руины}

# Area 107, Map 182
{1830}{}{stop1_ruin2_3}
{1835}{}{13 - Killadrone.ogg}
{1836}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1838}{}{Главная улица}

# Area 108, Map 183
{1840}{}{stop1_ruin3_3}
{1845}{}{28Rangers-journey.ogg}
{1846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}	
{1848}{}{Старый Лагерь}

# Area 109, Map 184
{1850}{}{stop1_ruin1_0}
{1855}{}{05 - Anesthetic.ogg}
{1856}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{1858}{}{Склады}

##### POSEIDON #####

# Area 110, Map 185
{1860}{}{tanker_deck0}
{1865}{}{30 - Clockwork.ogg}
{1866}{}{gntlwin1:5, gntlwind:5, gustwin1:5, gustwind:5, seagull:10, seagull1:10, seawind:5, seawind1:5, waves:15, waves1:15}
{1868}{}{Верхняя палуба}

# Area 110, Map 186
{1870}{}{tanker_deck1}
{1875}{}{01hub.acm}
{1876}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, laughte1:5, laughter:5, water:5, water1:5, waves:5, waves1:5}
{1878}{}{Торговая палубы}

# Area 110, Map 187
{1880}{}{tanker_deck2}
{1885}{}{akiss.acm}
{1886}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{1888}{}{Барная палуба}

# Area 110, Map 188
{1890}{}{tanker_deck3}
{1895}{}{06 - Cluster Decay.ogg}
{1896}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{1898}{}{Инженерная палуба}

# Area 110, Map 189
{1900}{}{tanker_deck4}
{1905}{}{29mark-morgan-curst.ogg}
{1906}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{1908}{}{Дыра}

# Area 110, Map 190
{1910}{}{tanker_str}
{1915}{}{27Lost_Knowledge.ogg}
{1916}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1918}{}{Башня}

# Area 110, Map 191
{1920}{}{tanker_sub1}
{1925}{}{29mark-morgan-curst.ogg}
{1926}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1928}{}{Подпалуба №1}

# Area 110, Map 192
{1930}{}{tanker_sub2}
{1935}{}{29mark-morgan-curst.ogg}
{1936}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1938}{}{Подпалуба №2}

# Area 110, Map 193
{1940}{}{tanker_sub3}
{1945}{}{29mark-morgan-curst.ogg}
{1946}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1948}{}{Подпалуба №3}

##### STOP 1 EXTRA LOCATIONS ####

# Area 105, Map 194
{1950}{}{stop1_ruin2_1dn}
{1955}{}{24redd.acm}
{1956}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1958}{}{Шахта}

##### NCR LOCATIONS #####

# Area 111, Map 200
{2010}{}{NCR}
{2015}{}{24redd.acm}
{2016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2018}{}{НКР}

##### RENO LOCATIONS #####

# Area 112, Map 201
{2110}{}{new_reno}
{2115}{}{24redd.acm}
{2116}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2118}{}{Нью Рено}

##### STOP 2 ####

# Area 114, Map 221
{2220}{}{stop2_frisco1_2}
{2225}{}{31old_earth.ogg}
{2226}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{2228}{}{Порт Сан-Франциско}

# Area 117, Map 224
{2250}{}{stop2_frisco2_2}
{2255}{}{39SHK_Heoi.ogg}
{2256}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2258}{}{Центр Сан-Франциско}

# Area 118, Map 226
{2270}{}{stop2_frisco2_3}
{2275}{}{56SHK_Prosperity.ogg}
{2276}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2278}{}{Отель Сан-Франциско}

# Area 118, Map 227
{2280}{}{stop2_frisco2_3dn}
{2285}{}{21sf.acm}
{2286}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2288}{}{Отель Сан-Франциско подвалы}

# Area 118, Map 228
{2290}{}{stop2_frisco2_3up}
{2295}{}{40SHK_Club88.ogg}
{2296}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2298}{}{Отель Сан-Франциско Клуб}

# Area 118, Map 229
{2300}{}{stop2_frisco2_3up2}
{2305}{}{21sf.acm}
{2306}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2308}{}{Отель Сан-Франциско 2й этаж отеля и 2е этажи}

# Area 118, Map 230
{2310}{}{stop2_frisco2_3up3}
{2315}{}{21sf.acm}
{2316}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2318}{}{Отель Сан-Франциско 3й этаж отеля }

# Area 118, Map 231
{2320}{}{stop2_frisco2_3up4}
{2325}{}{21sf.acm}
{2326}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2328}{}{Отель Сан-Франциско 4й этаж отеля}

##### EVENT 1 ####

{3010}{}{event1_road1}
{3015}{}{05 - Anesthetic.ogg}
{3016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3018}{}{Поворот}

{3020}{}{event1_road2}
{3025}{}{05 - Anesthetic.ogg}
{3026}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3028}{}{Дорога}

{3030}{}{event1_road3}
{3035}{}{05 - Anesthetic.ogg}
{3036}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3038}{}{Заправка}

##### EVENT 2 ####

{3040}{}{event2_camp}
{3045}{}{05 - Anesthetic.ogg}
{3046}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3048}{}{Стоянка}

{3050}{}{event2_hill}
{3055}{}{05 - Anesthetic.ogg}
{3056}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3058}{}{Гора}

{3060}{}{event2_slavers_out}
{3065}{}{05 - Anesthetic.ogg}
{3066}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3068}{}{Рабторги выход}

{3070}{}{event2_slavers_in}
{3075}{}{05 - Anesthetic.ogg}
{3076}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3078}{}{Рабторги перещера}

##### EVENT 3 ####

{3080}{}{event3_hunt1_1}
{3085}{}{03wrldmp}
{3086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3088}{}{Лес С.З.}

{3090}{}{event3_hunt1_2}
{3095}{}{07desert}
{3096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3098}{}{Пустошь С.}

{3100}{}{event3_hunt1_3}
{3105}{}{07desert}
{3106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3108}{}{Пустошь С.В.}

{3110}{}{event3_hunt2_1}
{3115}{}{03wrldmp}
{3116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3118}{}{Лес З.}

{3120}{}{event3_hunt2_2}
{3125}{}{03wrldmp}
{3126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3128}{}{Лес}

{3130}{}{event3_hunt2_3}
{3135}{}{03wrldmp}
{3136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3138}{}{Лес В.}

{3140}{}{event3_hunt3_1}
{3145}{}{13carvrn}
{3146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3148}{}{Гора Ю.З.}

{3150}{}{event3_hunt3_2}
{3155}{}{13carvrn}
{3156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3158}{}{Гора Ю.}

{3160}{}{event3_hunt3_3}
{3165}{}{03wrldmp}
{3166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3168}{}{Лес Ю.В.}

##### EVENT 4 ####

{3170}{}{event4_mountains}
{3175}{}{34Cataclysm.ogg}
{3176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3178}{}{Аутпост К.К.}

{3180}{}{event4_mountains_dn}
{3185}{}{03wrldmp}
{3186}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3188}{}{Пещера К.К.}

#####HELL OF ANUBIS#####

{4010}{}{hell}
{4015}{}{33DOOM.ogg}
{4016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15, pebble:25, pebble1:15, ore:10, ore1:10}
{4018}{}{АД}
	
#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{Вы наткнулись на @lex who@.}
#{10000011}{}{Вы наткнулись на @lex who@ и @lex player@.}
#{10000012}{}{Вы наткнулись на @lex who@ и банду @lex player@.}
#{10000013}{}{Вы наткнулись на @lex player@.}
#{10000014}{}{Вы наткнулись на банду @lex player@.}
#{10000020}{}{Вы хотите увидеть @lex who@?}
#{10000021}{}{Вы хотите увидеть @lex who@ и @lex player@?}
#{10000022}{}{Вы хотите увидеть @lex who@ и банду @lex player@?}
#{10000023}{}{Вы хотите увидеть @lex player@?}
#{10000024}{}{Вы хотите увидеть банду @lex player@?}
