
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{Глобальная карта}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

# Map 30, Global, base 310
{310}{}{Modoc_mine_entrance}
{315}{}{06vault.ogg}
{316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{318}{}{Шахта}

# Map 31, Global, base 320
{320}{}{Modoc_mine_shafts}
{325}{}{06vault.ogg}
{326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{328}{}{Штольни}

# Map 32, Global, base 330
{330}{}{Modoc_getto}
{335}{}{05raider.ogg}
{336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{338}{}{Гетто}

# Map 33, Global, base 340
{340}{}{Modoc_city_main}
{345}{}{19reno.ogg}
{346}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{348}{}{Модок}

# Map 34, Global, base 350
{350}{}{Modoc_city_floors}
{355}{}{19reno.ogg}
{356}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{358}{}{Этажи}

# Map 35, Global, base 360
{360}{}{Modoc_city_underground}
{365}{}{19reno.ogg}
{366}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{368}{}{Подземка}

# Map 36, Global, base 370
{370}{}{Modoc_farm}
{375}{}{10 - Dystopian Dreams.ogg}
{376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{378}{}{Ферма}

# Map 37, Global, base 380
{380}{}{Modoc_sawmill}
{385}{}{16follow.ogg}
{386}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{388}{}{Лесопилка}

# Map 38, Global, base 390
{390}{}{Modoc_water_tower}
{395}{}{23world.ogg}
{396}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{398}{}{Вышка}

# Map 39, Global, base 400
{400}{}{Modoc_desert}
{405}{}{57SHK_sinless_From_Seattle.ogg}
{406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{408}{}{Пустырь}

# Map 40, Global, base 410
{410}{}{Modoc_grey_wood}
{415}{}{21sf.ogg}
{416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{418}{}{Бурый лес}

# Map 41, Global, base 420
{420}{}{Modoc_grey_wood}
{425}{}{21sf.ogg}
{426}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{428}{}{Серый лес}

# Map 42, Global, base 430
{430}{}{Modoc_bartergrounds}
{435}{}{28Rangers-journey.ogg}
{436}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{438}{}{Торговый пост}

# Map 43, Global, base 440
{440}{}{Modoc_swamp}
{445}{}{24redd.Ogg}
{446}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{448}{}{Болото}

# Map 44, Global, base 450
{450}{}{Modoc_wasteland1}
{455}{}{10labone.ogg}
{456}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{458}{}{Тропа в Модок}

# Map 45, Global, base 460
{460}{}{Modoc_road1}
{465}{}{23world.ogg}
{466}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{468}{}{Дорога в Модок}

# Map 46, Global, base 470
{470}{}{Modoc_swamp_blossom}
{475}{}{24redd.ogg}
{476}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{478}{}{Цветущие болота}

# Map 47, Global, base 480
{480}{}{Modoc_lake}
{485}{}{37E1_Into_the_Tower.ogg}
{486}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{488}{}{Озеро}

# Map 48, Global, base 490
{490}{}{Modoc_deathpit_surface}
{495}{}{Whiskey_Heat.mp3}
{496}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{498}{}{Подозрительные руины}

# Map 49, Global, base 500
{500}{}{Modoc_deathpit_lair}
{505}{}{Whiskey_Heat.mp3}
{506}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{508}{}{Логово Смерти}

# Map 50, Global, base 510
{510}{}{Modoc_zone_alpha}
{515}{}{11 - Face to face.ogg}
{516}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{518}{}{Зона Альфа}

# Map 51, Global, base 520
{520}{}{Modoc_wasteland2}
{525}{}{101abone.ogg}
{526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{528}{}{Пустошь}

# Map 52, Global, base 530
{530}{}{Modoc_road_cafe}
{535}{}{04Metallic Monks.ogg}
{536}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{538}{}{Кафе Путник}

# Map 53, Global, base 540
{540}{}{Modoc_ruins}
{545}{}{57SHK_sinless_From_Seattle.ogg}
{546}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{548}{}{Руины}

# Map 54, Global, base 550
{550}{}{Modoc_junkyard}
{555}{}{23world.ogg}
{556}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{558}{}{Свалка}

# Map 55, Global, base 560
{560}{}{Modoc_Phoenix_surface}
{565}{}{Where Am I.ogg}
{566}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{568}{}{Станция Феникс}

# Map 56, Global, base 570
{570}{}{Modoc_Phoenix_entrance}
{575}{}{Where Am I.ogg}
{576}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{578}{}{Вход на базу}

# Map 57, Global, base 580
{580}{}{Modoc_Phoenix_depth	}
{585}{}{Where Am I.ogg}
{586}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{588}{}{Глубины базы}

# Map 58, Global, base 590
{590}{}{Modoc_zone_beta}
{595}{}{Ultimatum.mp3}
{596}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{598}{}{Зона Бета}

# Map 59, Global, base 600
{600}{}{Modoc_wasteland2}
{605}{}{57SHK_sinless_From_Seattle.ogg}
{606}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{608}{}{Окраина}

# Map 60, Global, base 610
{610}{}{Modoc_road2}
{615}{}{57SHK_sinless_From_Seattle.ogg}
{616}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{618}{}{Дорога в Саттер}

# Map 61, Global, base 620
{620}{}{Modoc_gas_station}
{625}{}{05raider.ogg}
{626}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{628}{}{Заправка}

# Map 62, Global, base 630
{630}{}{Modoc_junktown}
{635}{}{14necro.ogg}
{636}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{638}{}{Лагерь мутантов}

# Map 63, Global, base 640
{640}{}{Modoc_train_station}
{645}{}{Under_the_Stars_Cut.ogg}
{646}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{648}{}{Депо}

#=============CLINTON===================

# Area 360, Map 500
{5010}{}{clinton_center}
{5015}{}{Save_room2.ogg}
{5016}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5018}{}{Центральный район}

# Area 360, Map 501
{5020}{}{clinton_center_dn1}
{5025}{}{last_hideout.ogg}
{5026}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5028}{}{Центральное убежище}

# Area 360, Map 502
{5030}{}{clinton_center_dn2}
{5035}{}{NNM_FS_16_One_Way.ogg}
{5036}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5038}{}{Станция}

# Area 360, Map 503
{5040}{}{clinton_center_up}
{5045}{}{48NNM_new_vegas.ogg}
{5046}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{5048}{}{Вторые этажи}

# Area 361, Map 504
{5050}{}{clinton1_1}
{5055}{}{black_dawn_1.ogg}
{5056}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5058}{}{Склады}

# Area 362, Map 506
{5070}{}{clinton1_2}
{5075}{}{52NNM_root_information.ogg}
{5076}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5078}{}{Подстанция}

# Area 363, Map 508
{5090}{}{clinton1_3}
{5095}{}{06 - Cluster Decay.ogg}
{5096}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5098}{}{Магазины}

# Area 364, Map 510
{5110}{}{clinton1_4}
{5115}{}{NNM_FS_12_Casa_Grande.ogg}
{5116}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5118}{}{Доки}

# Area 365, Map 512
{5130}{}{clinton2_1}
{5135}{}{46NNM_line_of_policy.ogg}
{5136}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5138}{}{Разрушеное КПП}

# Area 366, Map 514
{5150}{}{clinton2_2}
{5155}{}{red_life_1.ogg}
{5156}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5158}{}{Разрушенная заправка}

# Area 366, Map 515
{5160}{}{clinton2_2_dn}
{5165}{}{NNM_FS_03_ Fogbound.ogg}
{5166}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{5168}{}{Низ заправки}

# Area 367, Map 516
{5170}{}{clinton2_3}
{5175}{}{NNM_FS_15_Out-of-Service.ogg}
{5176}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5178}{}{Разрушенная мэрия}

# Area 367, Map 517
{5180}{}{clinton2_3_dn}
{5185}{}{Sleepless Ruins.ogg}
{5186}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5188}{}{Центр связи}

# Area 368, Map 518
{5190}{}{clinton2_4}
{5195}{}{Save_room1.ogg}
{5196}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5198}{}{Библиотека}

# Area 369, Map 520
{5210}{}{clinton3_1}
{5215}{}{NNM_FS_05_Collapse.ogg}
{5216}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5218}{}{Церковь}

# Area 370, Map 522
{5230}{}{clinton3_4}
{5235}{}{Deeper_and_Darker.ogg}
{5236}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5238}{}{Восточная сторона}

# Area 371, Map 524
{5250}{}{clinton4_1}
{5255}{}{31old_earth.ogg}
{5256}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5258}{}{Склад}

# Area 372, Map 526
{5270}{}{clinton4_4}
{5275}{}{58Tales_of_the_Past.ogg}
{5276}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5278}{}{Перекрёсток}

# Area 372, Map 527
{5280}{}{clinton4_4_dn}
{5285}{}{under_1.ogg}
{5286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5288}{}{Шахта клинтона}

# Area 373, Map 528
{5290}{}{clinton5_1}
{5295}{}{secrets_from_river.ogg}
{5296}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5298}{}{Пересечение Железных Дорог}

# Area 374, Map 530
{5310}{}{clinton5_2}
{5315}{}{26A_Candle_in_the_Darkness.ogg}
{5316}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5318}{}{Даунтаун}

# Area 375, Map 532
{5330}{}{clinton5_3}
{5335}{}{26A_Candle_in_the_Darkness.ogg}
{5336}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5338}{}{Парк}

# Area 376, Map 534
{5350}{}{clinton5_4}
{5355}{}{42NNM_ghost_town.ogg}
{5356}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5358}{}{Южный клуб}

# Area 377, Map 536
{5370}{}{clinton5_4}
{5375}{}{Crimson_soil.ogg}
{5376}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5378}{}{Шоссе}

#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{Вы наткнулись на @lex who@.}
#{10000011}{}{Вы наткнулись на @lex who@ и @lex player@.}
#{10000012}{}{Вы наткнулись на @lex who@ и банду @lex player@.}
#{10000013}{}{Вы наткнулись на @lex player@.}
#{10000014}{}{Вы наткнулись на банду @lex player@.}
#{10000020}{}{Вы хотите увидеть @lex who@?}
#{10000021}{}{Вы хотите увидеть @lex who@ и @lex player@?}
#{10000022}{}{Вы хотите увидеть @lex who@ и банду @lex player@?}
#{10000023}{}{Вы хотите увидеть @lex player@?}
#{10000024}{}{Вы хотите увидеть банду @lex player@?}
