# Created: 08.11.2007 03:40 Cvet
# Updated: 29.10.2008 23:18 Cvet

{1}{}{Вы прочитали бумаги.}
{2}{}{Вы не сумели прочитать бумаги.}
{3}{}{Вы не прочли ничего нового.}
{4}{}{Вы не можете запомнить прочитанное.}
{5}{}{Вы забыли ненужную информацию.}
{6}{}{Такое не так просто забыть.}
{7}{}{Вы закончили писать на бумагах.}
{8}{}{У вас не вышло записать задуманное.}

#
# Format:
# Name - Number * 10
# Text - Number * 10 + 1


# 99999
# Последний корректный номер, после него текст берется из базы данных записей игроков.
# Холодиск для записей игроков.
{999990}{}{Пустые листы.}
{999991}{}{}
