# 17.10.2007 Cvet


{4}{}{%d. }
{5}{}{Текущее состояние: }

#
# Номер
# Название
#

#
# Формулы расчетов:
#	Номер * 1000 + Значение (1-100) - Текст который появиться у игрока при данном значении переменной.
#	Номер * 1000 + 101 - Название вкладки квеста.
#	Номер * 1000 + 102 - Постоянное описание квеста.


