# Skill raise
{15}{}{Навык @lex skill@ увеличен на @lex value@ очков}

# Drug Subtypes
{149}{}{Тип Наркотика:}
{150}{}{Кайф}
{151}{}{Боевой}
{152}{}{Тяжелый}
{153}{}{Лечащий}
{154}{}{Терапевтический}

# Generic messages
{510}{}{Да} # Magic ball
{511}{}{Нет} # Magic ball
{520}{}{пудрит носик} # Cosmetic
{530}{}{затягивается} # Cigarettes

{700}{}{|0xFFFF00 Ваш инструмент сломан!}

{701}{}{Навык: |0xFFFF00 VALUE|0x3CF800 .}
{702}{}{Перк: }
{703}{}{|0xFFFF00 VALUE|0x3CF800 .}
{704}{}{|0x3CF800 ;
   |0xFFFF00 }
   
# Weapon Perks
{800}{}{|0xFFFF00 Нет|0x3CF800 }
{801}{}{Большая дальность}
{802}{}{Точный}
{803}{}{Режущий}
{804}{}{Отбрасывающий}
{805}{}{Оптика}
{806}{}{Едкий}
{807}{}{Подавляющий}
{808}{}{Одиночная зарядка}
{809}{}{Нокаутирующий}
{810}{}{Пробивающий}
{811}{}{Ненадежный}
{812}{}{Нелетальный}
{813}{}{Отравленный}
{814}{}{Нейротоксин}
{815}{}{Перезаряжается}
{816}{}{Игнорирует укрытие}
{817}{}{Беззвучный}
{818}{}{Разрушение брони}
{819}{}{}
{820}{}{}
{821}{}{}
{822}{}{}
{823}{}{}
{824}{}{}
{825}{}{}
{826}{}{}
{827}{}{}
{828}{}{}
{829}{}{}
{830}{}{}
{831}{}{}
{832}{}{}

# Ammo Perks
{900}{}{|0xFFFF00 Нет|0x3CF800 }
{901}{}{Ненадежный}
{902}{}{Отравляющий}
{903}{}{Нейротоксин}
{904}{}{Безгильзовый}
{905}{}{Нелетальный}
{906}{}{Радиоактивный}
{907}{}{Режущий}
{908}{}{Разрушающий}
{909}{}{Едкий}
{910}{}{Разброс}
{911}{}{}
{912}{}{}
{913}{}{}
{914}{}{}
{915}{}{}
{916}{}{}
{917}{}{}
{918}{}{}
{919}{}{}
{920}{}{}
{921}{}{}
{922}{}{}
{923}{}{}
{924}{}{}
{925}{}{}
{926}{}{}
{927}{}{}
{928}{}{}
{929}{}{}
{930}{}{}
{931}{}{}
{932}{}{}

# Bulletin Board System
{995}{}{Объявления}
{996}{}{Вешает объявление}
{997}{}{Срывает объявление}
{998}{}{Доска объявлений:
Объявлений: |0xFFFF00 @lex paperCount@ |0x3CF800 
Страница: |0xFFFF00 @lex currPage@/@lex maxPage@ |0x3CF800}
{999}{}{Сорвать}

# General interactive machines
{1000}{}{вставляет деньги в аппарат}
{1001}{}{|0xFFFF00 Аппарат заперт.}
{1002}{}{открывает аппарат}

# Armor Perks
{1100}{}{|0xFFFF00 Нет|0x3CF800 }
{1101}{}{+1 Силы}
{1102}{}{+2 Силы}
{1103}{}{+3 Силы}
{1104}{}{+4 Силы}
{1105}{}{Неплохая}
{1106}{}{Очень неплохая}
{1107}{}{Прекрасна}
{1108}{}{Всратая}
{1109}{}{Очень всратая}
{1110}{}{Отвратительна}
{1111}{}{РАД-сопр. I}
{1112}{}{РАД-сопр. II}
{1113}{}{РАД-сопр. III}
{1114}{}{РАД-сопр. IV}
{1115}{}{Серво-Приводы}
{1116}{}{РАД-Защита}
{1117}{}{Нательная}
{1118}{}{Имеет капюшон}
{1119}{}{Воздушный фильтр}
{1120}{}{Система наведения STA}
{1121}{}{Проворный}
{1122}{}{Неуклюжий}
{1123}{}{Шустрый}
{1124}{}{Вялый}
{1125}{}{Быстрое вставание}
{1126}{}{Медленное вставание}
{1127}{}{Прочный}
{1128}{}{Хрупкий}
{1129}{}{}
{1130}{}{}
{1131}{}{}
{1132}{}{}

# Headgear Perks
{1200}{}{|0xFFFF00 Нет|0x3CF800 }
{1201}{}{Неплохой}
{1202}{}{Очки}
{1203}{}{Очень неплохой}
{1204}{}{Счастливый}
{1205}{}{Скрывает лицо}
{1206}{}{Защита от KO}
{1207}{}{Фанат Бейсбола}
{1208}{}{Система Наведения STA}
{1209}{}{Защита от шумовой гранаты}
{1210}{}{Противогаз}
{1211}{}{Фонарь}
{1212}{}{}
{1213}{}{}
{1214}{}{}
{1215}{}{}
{1216}{}{}
{1217}{}{}
{1218}{}{}
{1219}{}{}
{1220}{}{}
{1221}{}{}
{1222}{}{}
{1223}{}{}
{1224}{}{}
{1225}{}{}
{1226}{}{}
{1227}{}{}
{1228}{}{}
{1229}{}{}
{1230}{}{}
{1231}{}{}
{1232}{}{}

# Tool Perks
{1300}{}{|0xFFFF00 Ничто|0x3CF800 }
{1301}{}{Отвертка}
{1302}{}{Нож}
{1303}{}{Мультитул}
{1304}{}{Лопата}
{1305}{}{Паяльник}
{1306}{}{Игла}
{1307}{}{Хим. трубки}
{1308}{}{Хим. набор}
{1309}{}{Топор}
{1310}{}{Гаечный ключ}
{1311}{}{Ступка}
{1312}{}{Кувалда}
{1313}{}{Молоток}
{1314}{}{Сварка}
{1315}{}{Ножницы}
{1316}{}{Штатив с трубками}
{1317}{}{Центрифуга}
{1318}{}{Дрель}
{1319}{}{Огонь}
{1320}{}{Шило}
{1321}{}{Казан}
{1322}{}{Верстак}
{1323}{}{Патронный станок}
{1324}{}{}
{1325}{}{}
{1326}{}{}
{1327}{}{}
{1328}{}{}
{1329}{}{}
{1330}{}{}
{1331}{}{}
{1332}{}{}

# Fixboy filters
{1400}{}{|0xFFFF00 Ничто|0x3CF800 }
{1401}{}{Детали}
{1402}{}{Мелкие пушки}
{1403}{}{Одежда}
{1404}{}{Холодное оружие}
{1405}{}{Инструменты}
{1406}{}{Химия}
{1407}{}{Средние пушки}
{1408}{}{Броня}
{1409}{}{Ловушки}
{1410}{}{Контейнеры}
{1411}{}{Боеприпасы}
{1412}{}{Большие пушки}
{1413}{}{Головные уборы}
{1414}{}{Метательное оружие}
{1415}{}{Мебель}
{1416}{}{}
{1417}{}{}
{1418}{}{}
{1419}{}{}
{1420}{}{}
{1421}{}{}
{1422}{}{}
{1423}{}{}
{1424}{}{}
{1425}{}{}
{1426}{}{}
{1427}{}{}
{1428}{}{}
{1429}{}{}
{1430}{}{}
{1431}{}{}
{1432}{}{}

# Dead bodies (Bones)
{1933}{}{Труп }
{1934}{}{Тело обезглавлено}
{1935}{}{Тело принадлежит |0xFFFFFF }
{1936}{}{Неизвестная личность}

# Slots
{2001}{}{|0xFFFF00 В автомате закончились деньги.}
{2002}{}{|0xFFFF00 В автомате не хватает денег для  для покрытия ставки.}
{2003}{}{|0xFFFF00 ДЖЕЕЕЕЕЕКПОТ!!! @lex result@$}
{2004}{}{|0xFFFF00 Выигрыш: @lex result@$}
{2005}{}{|0xFF0000 Проигрыш!}
{2006}{}{|0xFFFF00 У Вас нет такой суммы.}
{2007}{}{|0xFFFF00 Ставка }

# Stat rolls
{2021}{}{|0xA6EEF900 СИЛА @lex result@}
{2022}{}{|0xA6EEF900 ВОСПРИЯТИЕ @lex result@}
{2023}{}{|0xA6EEF900 ВЫНОСЛИВОСТЬ @lex result@}
{2024}{}{|0xA6EEF900 ХАРИЗМА @lex result@}
{2025}{}{|0xA6EEF900 ИНТЕЛЛЕКТ @lex result@}
{2026}{}{|0xA6EEF900 ЛОВКОСТЬ @lex result@}
{2027}{}{|0xA6EEF900 УДАЧА @lex result@}

# Coinflip
{2050}{}{подкидывает монетку: |0x7CFC00 Бермин|0xFF00FF .}
{2051}{}{подкидывает монетку: |0x7CFC00 Бак|0xFF00FF .}

# Dice use
{2053}{}{выбрасывает: |0x7CFC00 @lex result@|0xFF00FF .}

# Cards
{2054}{}{|0xFFFF00 Колода пуста!}
{2055}{}{|0xFFFF00 В колоде нет карт!}
{2056}{}{вытягивает: |0x7CFC00 @lex card@|0xFF00FF .}
{2057}{}{сдает карту}
{2058}{}{|0xFFFF00 Вам сдали карту.}
{2059}{}{тасует карты}
{2060}{}{набирает карты}
{2061}{}{|0xFFFF00 Сюда можно только добавить карты.}
{2062}{}{показывает: @lex cards@}
{2063}{}{Ваша рука: @lex cards@}
{2064}{}{|0x3CF800 - |0xFFFF00 @lex card@|0x3CF800  -}

# Vending Machines
{2100}{}{забирает товар}
{2101}{}{забирает сдачу}
{2102}{}{устанавливает новый товар}
{2103}{}{продает}

# Jukebox
{2150}{}{|0xFFFF00 Вы заметили, что выбранная пластинка отсутствует!}
{2151}{}{|0xFFFF00 Похоже, что размен закончился!}

# Terminal
{2200}{}{|0xFFFF00 Вы заблокировали доступ к терминалу.}
{2201}{}{открывает приемник терминала}
{2202}{}{|0xFFFF00 Терминал не принимает данный предмет!}
{2203}{}{устанавливает новую карту доступа}
{2204}{}{отключает пропуски}
{2205}{}{|0xFFFF00 Вас подхватили манипуляторы, надежно фиксируя ноги.}
{2206}{}{|0xFFFF00 Манипуляторы отключились, Вы вновь можете ходить.}
{2207}{}{заправляет биогель}
{2208}{}{|0xFFFF00 Вы заправили биогель под крышку бака.}
{2209}{}{|0xFF0000 Операция не принесла результата.}

# Bandage
{2300}{}{Вы вылечили |0xFFFF00 @lex rate@|0x3CF800  жизней.}
{2301}{}{|0xFFFF00 Кажется, от повязки больше нет проку.}
{2302}{}{|0xFFFF00 Вам наложили повязку.}
{2303}{}{Вы восстановили |0xFFFF00 @lex regen@|0x3CF800  жизней.}
{2304}{}{Вы восстановили |0xFFFF00 @lex regen@|0x3CF800  макс жизней.}
{2305}{}{Эффект антибиотиков кончился.}

# Homebrew
{6137}{}{|0xFF0000 Брага уже приготовилась, что-то добавлять смысла нет.}
{6138}{}{|0xFF0000 Вам кажется, что из этого браги не сделать.}
{6139}{}{наливает воду}
{6140}{}{наливает грязную воду}
{6141}{}{наливает колу}
{6142}{}{вливает пиво}
{6143}{}{вливает Гамма-гульп пиво}
{6144}{}{вливает крепкий алкоголь}
{6145}{}{вливает жидкость}
{6146}{}{добавляет ингридиенты}
{6147}{}{|0xFF0000 Такое количество ингридиентов сюда уже не добавить.}
{6148}{}{|0xFF0000 Процесс уже идет, Вам кажется, что добавлять твердые примеси не стоит.}
{6149}{}{|0xFFFF00 Вы заполнили кувшин под крышку.}
{6150}{}{:вода переливается через край:}
{6151}{}{|0xFF0000 У вас кончились дрожжи.}
{6152}{}{|0xFFFF00 Необходимо взять ножик в руку.}
{6153}{}{измельчает ингридиенты}
{6154}{}{|0xFF0000 Без воды процесс не начнется, вы зря потратили ценные дрожжи.}
{6155}{}{|0xFF0000 Без сахара процесс не начнется, вы зря потратили ценные дрожжи.}
{6156}{}{:тошнотворный запах:}
{6157}{}{открывает крышку}
{6158}{}{закрывает крышку}
{6159}{}{|0xFFFF00 Пробовать без воды не имеет никакого смысла.}
{6160}{}{|0xFFFF00 Попробовав, Вы определили, что это: @lex sugar@ @lex state@ @lex taste@ @lex alcohol@ @lex polution@}
{6161}{}{Пресная}
{6162}{}{Сладковатая}
{6163}{}{Cладкая}
{6164}{}{Приторная}
{6165}{}{, слегка горчит алкоголем}
{6166}{}{, горчит алкоголем}
{6167}{}{, сильно горчит алкоголем}
{6168}{}{, немного отдает тухлятиной}
{6169}{}{, отдает тухлятиной}
{6170}{}{, сильно отдает тухлятиной}
{6171}{}{|0xFFFF00 Недостаточно жидкости для перелива.}
{6172}{}{|0xFFFF00 Вы разлили всю брагу по бутылкам.}
{6173}{}{|0xFFFF00 У Вас закончилась тара.}
{6174}{}{наполняет бутылку}
{6175}{}{|0xFFFF00 Вы полностью наполнили бутылку брагой.}
{6176}{}{|0xFFFF00 Вы опрокинули чан и убедились, что он пуст.}
{6177}{}{вытряхивает содержимое кувшина}
{6178}{}{:ингридиенты рассыпаются по земле:}
{6179}{}{выливает содержимое кувшина}
{6180}{}{:под кувшином образовалась лужа:}
{6181}{}{добавляет дрожжи}
{6182}{}{ водичка}
{6183}{}{ закваска}
{6184}{}{ брага}
{6185}{}{ со вкусом }
{6186}{}{ не поддающимся определению }
{6187}{}{}
{6188}{}{Открыть крышку}
{6189}{}{Закрыть крышку}
{6190}{}{Добавить ингридиент}
{6191}{}{Нарезать ингридиенты}
{6192}{}{Попробовать}
{6193}{}{Добавить дрожжи}
{6194}{}{Вытряхнуть содержимое}
{6195}{}{Разлить по бутылкам}
{6196}{}{Вычистить}
{6197}{}{Крышка плотно закрыта.}
{6198}{}{@lex state@

Горшок заполнен на |0xFFFF00 @lex current@ |0x3CF800 из |0xFFFF00 @lex max@ |0x3CF800 л.}
{6199}{}{Брожение не начнется без воды, сахара и дрожжей. Что бы запустить процесс добавьте дрожжи.}
{6200}{}{Брожение в процессе.}
{6201}{}{Брожение завершено.}

{6245}{}{Является инструментом: }

# Cooking
{6246}{}{Приготовить рецепт}
{6247}{}{Вы собираетесь что-то приготовить...}
{6248}{}{что-то готовит}
{6249}{}{завершает готовку @lex name@}
{6250}{}{сжигает @lex name@}
{6251}{}{Крендель}
{6252}{}{|0xFF0000 Вы сожгли крендельки. }
{6253}{}{|0xFFFF00 Вы приготовили крендели с солью, пора пополнить запас калорий!}
{6254}{}{|0xFFFF00 Вам понадобится немного кукурузной муки, дрожжи и сахар.}
{6257}{}{Суп из личинок}
{6258}{}{|0xFF0000 Эти личинки еще живы, придурок!}
{6259}{}{|0xFFFF00 Вы приготовили суп из личинок, хорошего дня!}
{6260}{}{|0xFFFF00 Чтобы получить изысканный вкус, вам понадобится как минимум 3 личинки, чистая вода и чистая тарелка.}
{6262}{}{Крысиное рагу}
{6263}{}{|0xFF0000 Вам чудом удалось испортить даже крысиное рагу. }
{6264}{}{|0xFFFF00 Вы приготовили вкусное крысиное рагу, наслаждайтесь!}
{6265}{}{|0xFFFF00 Для хорошего рагу нужна хотя бы одна крыса, немного пейота, чистая вода и чистая тарелка.}
{6268}{}{Салат}
{6269}{}{Капустный суп}
{6270}{}{Шашлык}
{6271}{}{Лепешка}
{6272}{}{Желудок}
{6273}{}{Рагу}
{6274}{}{Бургер}
{6275}{}{Пицца}
{6276}{}{Рыбный пирог}
{6277}{}{Тако}
{6278}{}{Выберите рецепт:}
{6279}{}{греет руки}
{6280}{}{|0xFFFF00 Для этого вам понадобиться мясо в руках.}
{6281}{}{|0xFF0000 Даже после обжарки эта вещь будет несъедобна.}
{6282}{}{|0xFFFF00 Вы успешно пожарили @lex name@.}
{6283}{}{|0xFFFF00 Вы не знаете ни одного полезного рецепта для готовки.}
{6284}{}{|0xFF0000 Вы испортили салат. Это просто невозможно есть!}	
{6285}{}{|0xFFFF00 Вы приготовили вкусный салат, потратив мутафрукт и пару водорослей...}	
{6286}{}{|0xFFFF00 Вам понадобится мутафрукт, немного плотоядных водорослей и чистая тарелка.}	
{6288}{}{|0xFF0000 Вы испортили похлебку.}	
{6289}{}{|0xFFFF00 Вы приготовили похлебку.}	
{6290}{}{|0xFFFF00 Вам понадобится чистая вода, кочан капусты, корень Зандера и чистая тарелка.}
{6293}{}{|0xFF0000 Вы пережарили мясо в угли. Несъедобная хрень!}
{6294}{}{|0xFFFF00 Вы приготовили сочный шашлык, приправив мясо корнем Зандера.}
{6295}{}{|0xFFFF00 Для такого шашлыка вам понадобится Мясо и корень Зандера.}
{6297}{}{|0xFFFF00 Лепёшка сгорела и воняет.}
{6298}{}{|0xFFFF00 Вы приготовили аппетитную кукурузную лепешку, смешав кукурузу и корень Зандера.}
{6299}{}{|0xFFFF00 Для начала вам понадобится кукурузная мука и корень Зандера.}
{6301}{}{|0xFF0000 Вы испортили блюдо. Это невозможно есть.}
{6302}{}{|0xFFFF00 Вам удалось приготовить фаршированный желудок, израсходовав кусок мяса, пару цветков Брока, ну и сам желудок.}
{6303}{}{|0xFFFF00 Вам понадобится желудок кротокрыса, два цветка Брок, Мясо и чистая тарелка.}
{6306}{}{|0xFF0000 От вкуса этого рагу вас тянет блевать. Как жаль, а вы старались...}
{6307}{}{|0xFFFF00 Вы приготовили прекрасное рагу из пары кусков мяса, цветка Брока и корня Зандера.}
{6308}{}{|0xFFFF00 Вам понадобится пара кусков хорошего Мяса, цветок Брока, корень Зандера и чистая тарелка.}
{6311}{}{|0xFF0000 Ваш бургер можно поистинне назвать тошнотворным. Это дерьмо никто есть не будет.}	
{6312}{}{|0xFFFF00 Вам удалось приготовить сытный бургер из мяса геккона, лепешки и листьев капусты.}
{6313}{}{|0xFFFF00 Как можно приготовить бургер без мяса геккона, капусты и кукурузной лепешки?}
{6316}{}{|0xFF0000 Даже если бы вы жили в канализации, то не стали бы есть это.}	
{6317}{}{|0xFFFF00 Вам удалось приготовить подобие пиццы, использовав лепешку, мясо и грибы.}	
{6318}{}{|0xFFFF00 Основой для пиццы служит кукурузная лепешка, куда добавляют Черногриб и Мясо.}	
{6321}{}{|0xFF0000 Пирог испорчен. Какая досада!}	
{6322}{}{|0xFFFF00 Вы приготовили рыбный пирог из лепешки, двух порций рыбы и пары корней Зандера.}	
{6323}{}{|0xFFFF00 Разрежьте кукурузную лепешку, добавьте в нее две рыбных котлеты и два корня Зандера.}	
{6326}{}{|0xFF0000 Это провал! Тако, буррито, кесадилья... уже не важно.}	
{6327}{}{|0xFFFF00 Вам удалось приготовить тако, мелко нарезав три крысиные туши, заправив их в лепешку и приправив парой цветков Брока.}	
{6328}{}{|0xFFFF00 Фарш из трех Крысинык тушек заверните в кукурузную лепешку и измельчите два цветка Брока.}
{6331}{}{Картофель фри}
{6332}{}{|0xFFFF00 Вы сожгли картофель фри.}
{6333}{}{|0xFFFF00 Вам удалось пожарить картофель фри, пальчики оближешь.}
{6334}{}{|0xFFFF00 Для начала вам понадобится картошка, растительное масло и чистая тарелка.}
{6337}{}{Картофельные оладьи}
{6338}{}{|0xFFFF00 Вы сожгли картофельные оладьи.}
{6339}{}{|0xFFFF00 Вам удалось приготовить картофельные оладьи.}
{6340}{}{|0xFFFF00 Для начала вам понадобится картошка, мука, растительное масло и чистая тарелка.}
{6344}{}{Картофельные чипсы}
{6345}{}{|0xFFFF00 Вы сожгли картофельные чипсы.}
{6346}{}{|0xFFFF00 Вам удалось приготовить картофельные чипсы.}
{6347}{}{|0xFFFF00 Для начала вам понадобится картошка, корень зандера, растительное масло и чистая тарелка.}
{6351}{}{Пюре с котлетой}
{6352}{}{|0xFFFF00 Вы сожгли картофельное пюре с котлетой.}
{6353}{}{|0xFFFF00 Вам удалось приготовить картофельное пюре с котлетой.}
{6354}{}{|0xFFFF00 Для начала вам понадобится две картошки, цветок Брока, растительное масло, два куска мяса и чистая тарелка.}
{6359}{}{Блинчик}
{6360}{}{|0xFFFF00 Вы сожгли блинчик.}
{6361}{}{|0xFFFF00 Вам удалось приготовить блинчик.}
{6362}{}{|0xFFFF00 Для начала вам понадобится сахар, растительное масло, два мутафрукта, пара щепоток кукурузной муки, вода и чистая тарелку.}
 
# Firestarter
{6390}{}{|0xFFFF00 Огонь уже вовсю полыхает.}
{6391}{}{|0xFFFF00 Тут нечего разжигать, найдите подходящее топливо.}
{6392}{}{|0xFFFF00 Вы сточили поджиг.}
{6393}{}{разжигает огонь}
{6394}{}{|0xFFFF00 Фляга пуста.}
{6395}{}{выливает воду}
{6396}{}{|0xFF0000 Вы попусту вылили воду, разве так стоит обращаться со столь ценной жидкостью?}
{6397}{}{|0xFF0000 Вы залили водой топливо! Теперь часть непригодна для розжига...}
{6398}{}{тушит пламя}
{6399}{}{|0xFFFF00 Горючее уже некуда подкладывать, дайте ему прогореть!}
{6400}{}{подкладывает уголь}
{6401}{}{подкладывает топливо}
{6402}{}{|0xFFFF00 Кострище заполнено горючими материалами на @lex rate@%}
{6403}{}{|0xFF0000 Сжечь предмет не удалось.}
{6404}{}{кидает странный предмет в огонь}
{6405}{}{кидает предмет в огонь}
{6407}{}{|0xFFFF00 У вас нет воды.}
{6408}{}{|0xFFFF00 Вам нечем разжечь огонь.}
{6409}{}{|0xFFFF00 У вас закончилось топливо.}

# Milling
{6410}{}{|0xFFFF00 Мельница пуста.}
{6411}{}{|0xFFFF00 В мельнице нет подходящего ресурса.}
{6412}{}{завершает помолку}

# Furnace
{6413}{}{|0xFFFF00 Сперва необходимо выключить печь.}
{6414}{}{|0xFFFF00 Вам нужны инструменты для работы с горящей печью!}

# Smithing
{6415}{}{|0xFFFF00 Наковальня пуста.}
{6416}{}{|0xFFFF00 На наковальне нет подходящего бруса.}
{6417}{}{завершает ковку}
{6418}{}{|0xFFFF00 Питание отключено!}

# Waterworks
{6420}{}{крутит бобину}
{6421}{}{|0xFFFF00 Ведро сорвалось и улетело вниз...}
{6422}{}{:ведро показалось:}
{6423}{}{|0xFFFF00 У вас нет подходящей тары в руках.}
{6424}{}{|0xFFFF00 Воды больше нет.}
{6425}{}{|0xFFFF00 Помпа отключена. Включите ее сначала.}
{6426}{}{|0xFFFF00 У вас нет подходящей тары в руках.}
{6427}{}{|0xFFFF00 У Вас закончилась тара.}
{6428}{}{|0xFFFF00 Вы разлили всю воду по бутылкам.}
{6429}{}{наполняет ёмкость}
{6430}{}{|0xFFFF00 Вы полностью наполнили бутылку водой.}
{6431}{}{|0xFFFF00 Вы полностью наполнили ёмкость водой.}
{6432}{}{моет руки}
{6433}{}{моется}
{6434}{}{|0xFF0000 Вы помылись.}
{6435}{}{|0xFF0000 У вас нет воды для этого.}
{6436}{}{|0xFFFF00 Вы используете новый кусок мыла.}
{6437}{}{моет руки хозяйственным мылом}
{6438}{}{моется хозяйственным мылом}
{6439}{}{|0xFFFF00 Вы использовали последние крохи мыла.}
{6440}{}{моет руки душистым мылом}
{6441}{}{моется душистым мылом}
{6442}{}{|0xFFFF00 Помывшись душистым мылом, вы стали приятнее окружающим.}
{6443}{}{использует духи}
{6444}{}{|0xFFFF00 Применив ароматные духи, вы стали приятнее окружающим.}
{6445}{}{|0xFFFF00 Применив духи, вы поняли, что смысла в этом было не много, ведь вы и так хорошо пахли.}
{6446}{}{|0xFFFF00 Ваш флакон духов опустел.}

# Lifts
{6450}{}{вызвает лифт}
{6451}{}{|0xFFFF00 Лифт занят.}
{6452}{}{|0xFFFF00 Лифт перезаряжается.}
{6453}{}{активирует лифт}
{6454}{}{|0xFFFF00 Приёмник ключ-карты моргнул. Возможно, без неё лифт не поедет.}
{6455}{}{|0xFFFF00 Приёмник ключ-карты моргнул. Возможно, без неё вызвать лифт не удастся.}
{6456}{}{вставляет карточку в приёмник}

# Fishing
{6460}{}{привязывает леску к удочке}
{6461}{}{|0xFFFF00 Возьмите удочку в руку, чтобы привязать к ней леску.}
{6462}{}{привязывает крючок к леске}
{6463}{}{|0xFFFF00 Возьмите удочку с леской в руку, чтобы привязать к ней крючок.}
{6464}{}{насаживает @lex bait@ на крючок.}
{6465}{}{|0xFFFF00 Для насаживания наживки вам нужна удочка с леской и крючком.}
{6466}{}{|0xFFFF00 В этом месте рыба не водится.}
{6467}{}{|0xFFFF00 Возьмите снаряженную удочку в руку.}
{6468}{}{|0xFFFF00 Для ловли рыбы Вам потребуется наживка.}
{6469}{}{|0xFFFF00 Вы не можете закинуть удочку так далеко.}
{6470}{}{|0xFFFF00 В месте приземления поплавка нет воды.}
{6471}{}{закидывает удочку}
{6472}{}{вытаскивает водоросли}
{6473}{}{вытаскивает удочку}
{6474}{}{|0xFFFF00 Похоже, что рыба сорвалась, съев приманку...}
{6475}{}{|0xFFFF00 Рыба сорвалась!}
{6476}{}{|0xFFFF00 Вы чувствуете натяжение лески, рыба сопротивляется!}
{6477}{}{|0xFFFF00 Рыба поддается.}
{6478}{}{вытаскивает @lex reward@}
{6479}{}{|0xFFFF00 Вытащив удочку, Вы поняли, что леска лопнула!}
{6480}{}{|0xFFFF00 Вытащив удочку, Вы поняли, что рыба сорвалась вместе с крючком!}

# Taste
{6486}{}{У этого напитка вкус }
{6487}{}{|0xFFFF00 Картофеля}
{6488}{}{|0xFFFF00 Капусты}
{6489}{}{|0xFFFF00 Орехов}
{6490}{}{|0xFFFF00 Хлеба}
{6491}{}{|0xFFFF00 Ягод паслена}
{6492}{}{|0xFFFF00 Мутировавших фруктов}
{6493}{}{|0xFFFF00 Ванили}
{6494}{}{|0xFFFF00 Кукурузы}
{6495}{}{|0xFFFF00 Печенек}
{6496}{}{|0xFFFF00 Протеинового батончика}
{6497}{}{|0xFFFF00 Конфет}
{6498}{}{|0xFFFF00 Карамели}
{6499}{}{ Вы чувствуете запах жидкости внутри:}

# St Peter
{6500}{}{Прекрати, сын мой, это бесполезно.}
{6501}{}{Много скверны в тебе.}
{6502}{}{Твоя боль мне понятно. Успокойся же, дитя.}
{6503}{}{Гнев губит тебя, не иди у него на поводу.}
{6504}{}{Нелегкий путь тебе выпал, ты озлоблен.}
{6505}{}{Твой гнев несправедлив. Прекрати же.}
{6506}{}{Еще не время, ты не можешь пройти.}
{6507}{}{Терпение, сын мой, терпение.}
{6508}{}{Твое время еще не пришло. Я не могу тебя пропустить.}
{6509}{}{Не спеши туда, у тебя впереди целая вечность.}
{6510}{}{Ты прожил всю свою жизнь в спешке, остановись хоть сейчас.}

# Traps
{6550}{}{|0xFFFF00 Чтобы разложить капкан тот должен находиться у вас в руках.}
{6551}{}{|0xFFFF00 Вы не можете установить капкан туда где уже есть один.}
{6552}{}{|0xFFFF00 Ваша рука попала в ваш же капкан.}
{6553}{}{устанавливает капкан}
{6554}{}{|0xFFFF00 Вы чуть было не наступили в капкан, но вовремя заметили его.}
{6555}{}{наступает в капкан}
{6556}{}{|0xFFFF00 Нельзя установить растяжку здесь.}
{6557}{}{устанавливает растяжку}
{6558}{}{|0xFFFF00 Вам удалось обезвредить растяжку.}
{6559}{}{|0xFFFF00 Вам не удалось обезвредить растяжку.}
{6560}{}{|0xFFFF00 Вы чуть было не наступили на растяжку, но вовремя заметили её}
{6561}{}{наступает на растяжку}
{6562}{}{|0xFFFF00 Нельзя установить мину здесь.}
{6563}{}{устанавливает мину}
{6564}{}{|0xFFFF00 Вам удалось обезвредить мину.}
{6565}{}{|0xFFFF00 Вам не удалось обезвредить мину.}
{6566}{}{|0xFFFF00 Вы чуть было не наступили на мину, но вовремя заметили её.}
{6567}{}{наступает на мину}
{6568}{}{|0xFFFF00 Вы осторожно убрали ногу с чуть было не активированной мины.}
{6569}{}{активирует мину, убрав ногу}
{6570}{}{|0xFFFF00 Чтобы установить ловушку она должна быть у вас в руках.}
{6571}{}{|0xFFFF00 Нельзя установить ловушку здесь.}
{6572}{}{устанавливает ловушку}
{6573}{}{|0xFFFF00 Вы что-то сделали не так и ловушка взорвалась у вас в руках.}
{6574}{}{|0xFFFF00 Вы что-то сделали не так но вам повезло избежать незапланированного подрыва.}
{6575}{}{|0xFFFF00 Вы успешно деактивировали ловушку.}
{6576}{}{|0xFFFF00 Вам не удалось деактивировать ловушку.}
{6577}{}{|0xFFFF00 Вы чуть было не наступили в ловушку, но вовремя заметили её.}
{6578}{}{наступает в ловушку}
{6579}{}{:щелк:}

# Bootlegging
{6600}{}{|0xFF0000 Аппарат не готов к загрузу браги.}
{6601}{}{|0xFF0000 Вам кажется, что из этого спирт не выделить.}
{6602}{}{:брага переливается через край:}
{6603}{}{|0xFFFF00 Вы разлили весь спирт по бутылкам.}
{6604}{}{|0xFFFF00 У Вас закончились бутылки.}
{6605}{}{|0xFFFF00 Вы полностью наполнили бутылку самогоном.}
{6606}{}{завершает ремонт самогонного аппрата}
{6607}{}{завершает обслуживание самогонного аппрата}
{6608}{}{|0xFFFF00 Вы не смогли произвести обслуживание самогонного аппаратта!}
{6609}{}{Необходимый инструмент: }
{6610}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{6611}{}{Необходимые запчасти: }
{6612}{}{|0x3CF800  - |0xFFFF00 @lex proto@ - @lex amount@ шт.}
{6613}{}{|0x3CF800 Необходимо иметь навыки:
 - |0xFFFF00 Наука |0x3CF800  -  |0xFFFF00 150 |0x3CF800 ,
 - |0xFFFF00 Ремонт |0x3CF800  -  |0xFFFF00 200 |0x3CF800 .}
{6614}{}{Необходимые расходники: }
{6615}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }

# Sex
{6992}{}{|0xFF0000 Вам отказали!}
{6993}{}{принимает порцию сладкой любви}
{6994}{}{cудорога}
{6995}{}{|0xFF0000 Кажется, ваш партнер кончил преждевременно...}
{6996}{}{|0xFFFF00 Вы травмировны и не можете заниматься этим.}
{6997}{}{|0xFFFF00 Ваш партнер травмировн и не можете заниматься этим.}
{6998}{}{|0xFFFF00 Вы слишком устали, и не готовы к новым постельным приключениям.}
{6999}{}{|0xFFFF00 Ваш партнер слишком сильно устал, чтобы ублажить вас.}

# Roulette
{7001}{}{зеро}
{7002}{}{двойное зеро}
{7003}{}{красное}
{7004}{}{черное}
{7005}{}{число }
{7006}{}{Ваш выигрыш: }
{7007}{}{Неверное число}
{7008}{}{Неверная ставка}
{7009}{}{Число принято}
{7010}{}{Ставка принята}
{7011}{}{Текущая ставка: @lex betsize@}
{7012}{}{Вы поставили на числа:}
{7013}{}{@lex result@}
{7014}{}{На что ставим?}

# Rotting
{7020}{}{|0xFF828a96 :запах крови:}
{7021}{}{|0xFF828a96 :запах разложения:}
{7022}{}{|0xFF828a96 :запашок:}
{7023}{}{|0xFFFF00 Кажется, у вас сгнила какая-то еда!}
{7024}{}{запашок}

# Меню игрока
{8200}{}{Вас теперь слышно с: |0xFFFF00 @lex hexes@|0x3CF800  гексов.}
{8201}{}{Режим аватара: @lex AvatarMode@}
{8202}{}{Показать}
{8203}{}{Курсор}
{8204}{}{Скрыть}
{8205}{}{Аватар: [|0xFFFF00 @lex AvatarMode@|0x3CF800 ]}
{8206}{}{Значки NPC: [|0xFFFF00 @lex NPC_Icon@|0x3CF800 ]}
{8207}{}{Показать}
{8208}{}{Скрыть}

# Healing
{8949}{}{|0xFFFF00 Вас хотят обследовать, Согласиться?}
{8950}{}{Согласиться}
{8951}{}{Сопротивляться}
{8952}{}{|0xFFFF00 Вас обследуют.}
{8953}{}{|0xFFFF00 Вы ожидаете ответа пациента.}
{8954}{}{|0xFFFF00 На Вас хотят использовать @lex proto@. Согласиться?}
{8955}{}{|0xFFFF00 На вас использовали @lex proto@.}
{8956}{}{употребляет @lex proto@}
{8957}{}{применяет @lex proto@ на цель}
{8958}{}{|0xFFFF00 Вы слишком далеко от пациента!}
{8959}{}{|0xFFFF00 Медик слишком далеко от вас!}
{8960}{}{|0xFFFF00 Ваше зрение проясняется, ваша голова пришла в норму.}
{8961}{}{|0xFFFF00 Вашей правой руке уже значительно легче, вы снова можете ей двигать.}
{8962}{}{|0xFFFF00 Вашей левой руке уже значительно легче, вы снова можете ей двигать.}
{8963}{}{|0xFFFF00 Вашей правой ноге уже значительно легче, вы снова можете опираться на неё.}
{8964}{}{|0xFFFF00 Вашей левой ноге уже значительно легче, вы снова можете опираться на неё.}
{8965}{}{|0xFFFF00 Вы вытащили пулю из раны.}
{8966}{}{|0xFFFF00 У Вас не вышло извлечь пулю.}
{8967}{}{|0xFFFF00 У Вас нет иглы и ниток.}
{8968}{}{|0xFFFF00 У Вас Нет источника тепла, или нечем прижечь рану.}
{8969}{}{|0xFFFF00 Вы успешно зашили рану.}
{8970}{}{|0xFFFF00 Вы успешно прижгли рану.}
{8971}{}{|0xFFFF00 Операция не удалась.}
{8972}{}{|0xFFFF00 Вы наложили повязку на рану, потребуется немало времени на то что бы она зажила.}
{8973}{}{|0xFFFF00 Вы обработали и перебинтовали рану, потребуется время на то что бы она зажила.}
{8974}{}{|0xFFFF00 Вы соорудили самодельную шину, потребуется немало времени на то что бы травма зажила.}
{8975}{}{|0xFFFF00 Вам нужна медицинская шина или хотя бы верёвка и палка.}
{8976}{}{|0xFFFF00 Вы наложили медицинскую шину, потребуется некоторое время на то что травма прошла.}

# Teleport Menu
{8998}{}{|0xFFFFFF Выберите точку назначения|0x00FF00 :
|0xFFFF00 @lex name@}

# Offline teleport
{8999}{}{|0xFF0000 Вы слишком долго были в оффлайне и теперь телепортированы на стартовую зону!}

# Russian Roulette
{9000}{}{проиграл в Русскую рулетку@@вынес себе мозги@@Сегодня не его день@@зря он это затеял@@залил все своей кровью@@закричал нажав на спусковой крючок, но крик был оборван...@@застрелился@@без колебаний запачкал все своими мозгами}
{9001}{}{щелчок, но не чего не произошло@@чуть не уделался, но пронесло...@@закричал и спустил курок, но все обошлось@@фортуна улыбнулась@@выиграл в Русскую рулетку@@ПОВЕЗЛО@@затаив дыхание, нажал на спусковой крючок, но все обошлось}
{9002}{}{проиграла в Русскую рулетку@@вынесла себе мозги@@Сегодня не ее день@@зря она это затеяла@@залила все своей кровью@@закричала нажав на спусковой крючок, но крик был оборван...@@застрелилась@@без колебаний запачкала все своими мозгами}
{9003}{}{щелчок, но не чего не произошло@@чуть не уделалась, но пронесло...@@закричала и спустила курок, но все обошлось@@фортуна улыбнулась@@выиграла в Русскую рулетку@@ПОВЕЗЛО@@затаив дыхание, нажала на спусковой крючок, но все обошлось}

# Resource Gathering
{9004}{}{срывает растение}
{9005}{}{|0xFFFF00 Вы не нашли ничего полезного.}
{9006}{}{Вы добыли:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800  шт.}
{9007}{}{|0x3CF800  шт.}
{9008}{}{|0xFFFF00 Вы сорвали растение в неправильной стадии, а затем выкинули его.}
{9009}{}{|0xFFFF00 Вы слишком устали, передохните.}
{9010}{}{|0xFFFF00 Возьмите инструмент в руку.}
{9011}{}{|0xFFFF00 Вы травмированы и не в состоянии выполнить задачу.}
{9012}{}{|0xFFFF00 Это было хорошей идеей, пока вы не поняли, что в буре нет энергии.}
{9013}{}{|0xFFFF00 Бур слишком повреждён.}
{9014}{}{|0xFFFF00 Сначала добейте жертву.}
{9015}{}{|0xFFFF00 Вы не можете разделать это.}
{9016}{}{|0xFFFF00 Тут нечего разделывать.}
{9017}{}{|0xFFFF00 Вы сильно исполосовали животное.}
{9018}{}{|0xFFFF00 Этот инструмент не подходит для рубки.}
{9019}{}{|0xFFFF00 Тут нечего рубить, придется подкопать и выкорчевать.}
{9020}{}{Вы получили: }
{9021}{}{- |0xFFFF00 @lex proto@}
{9022}{}{что-то делает}
{9023}{}{Вы добыли: @lex result@}
{9024}{}{Вы потеряли: - |0xFFFF00 @lex proto@, @lex count@ шт.}

#Books
{9430}{}{|0xFFFF00 Вы уже изучили все возможные профессии.}
{9431}{}{|0xFFFF00 Вам не хватает базовых знаний для понимания содержания этой книги.}
{9432}{}{|0xFFFF00 Вы уже знаете все, что можно найти в этой книге.}
{9433}{}{начинает читать книгу}
{9434}{}{|0xFFFF00 Вы обрели новые знания.}

#Locks
{9440}{}{|0xFFFF00 Вы не можете запереть это!}
{9441}{}{}

#Radio fast failsafe switch
{9442}{}{Переключает предохранитель на рации}
{9443}{}{|0xFFFF00 Предохранитель рации: [ |0x00C800 @lex mode@ |0xFFFF00 ]}

# ItemMovement
{9445}{}{|0xFFFF00 Слишком тяжело, не достать.}
{9446}{}{берёт карту}
{9447}{}{берёт броню}
{9448}{}{берёт @lex proto@}
{9449}{}{берёт оружие}
{9450}{}{берёт патроны}
{9451}{}{достаёт что-то}
{9452}{}{|0xFFFF00 Необходимо отойти, чтобы установить предмет.}
{9453}{}{|0xFFFF00 Перенос в слот невозможен, т.к. для данного оружия отсутствуют анимации!}
{9454}{}{|0xFFFF00 Оружие в основной руке не поддерживается данным скином, перенос в инвентарь!}
{9455}{}{|0xFFFF00 Оружие во второй руке не поддерживается данным скином, перенос в инвентарь!}
{9456}{}{|0xFF00FF Электронный голос: |0xF8F993 Личность распознана. Активация!}
{9457}{}{нарастающий гул реактора}
{9458}{}{скрывает лицо}
{9459}{}{показывает лицо}
{9460}{}{снимает рюкзак}
{9461}{}{снимает экипированные предметы с цели}
{9462}{}{|0xFFFF00 Вы не в силах сопротивляться, пока у вас отбирают рюкзак.}
{9463}{}{|0xFFFF00 Вы не в силах сопротивляться, пока у вас отбирают предмет.}
{9464}{}{|0xFFFF00 Вы забрали рюкзак.}
{9465}{}{|0xFFFF00 Вы забрали предмет.}
{9466}{}{пытается снять броню}
{9467}{}{снимает броню с цели}
{9468}{}{|0xFFFF00 Вашу броню пытаются снять!}
{9469}{}{|0xFFFF00 Вы забрали у персонажа броню.}
{9470}{}{|0xFFFF00 С вас сняли броню.}
{9471}{}{|0xFFFF00 Вы сняли броню с цели.}
{9472}{}{|0xFFFF00 Вы частично сняли броню с цели.}
{9473}{}{|0xFFFF00 Вы не можете облутать цель.}

# Bond inv desc
{9474}{}{|0xFFFF00 Связывает Вас.}
{9475}{}{|0xFFFF00 Предмет готов к использованию.}

# Windup
{9476}{}{вскидывает @lex proto@}
{9477}{}{опускает @lex proto@}
{9478}{}{поднимает кулаки}
{9479}{}{поднимает кулачки}
{9480}{}{поднимает кулачищи}
{9481}{}{стучит копытом}
{9482}{}{поднимает жало}
{9483}{}{скалится}
{9484}{}{поднимается в полный рост}
{9485}{}{распахивает пасти}
{9486}{}{вскидывает манипуляторы}
{9487}{}{поднимает лапы}
{9488}{}{поднимает щупольцы}
{9489}{}{распахивает жвала}
{9490}{}{смотрит на Вас как на говно}
{9491}{}{выпускает жало}
{9492}{}{громко рычит}
{9493}{}{распахивает клешни}
{9494}{}{утробно рычит}
{9495}{}{расслабляется}

# Raising skills
{9496}{}{|0xFFFF00 Вы стали настоящим экспертом в ублажении партнеров!}
{9497}{}{|0xFFFF00 Вы не смогли повысить свой навык.}
{9498}{}{|0x3CF800 Навык: }
{9499}{}{|0x3CF800  повышен на }

# Accidental injuries
{9500}{}{|0xFFFF00 В последний момент Вы чудом избежали старшной травмы, но все же: \n}
{9501}{}{|0xFFFF00 В результате ошибки вы сильно ушиблись.}
{9502}{}{|0xFFFF00 Вы ошиблись и слегка рассекли руку.}
{9503}{}{|0xFFFF00 Вы попали инструментом по себе и сильно рассекли плоть.}
{9504}{}{|0xFFFF00 Из-за неудачного движения Вы получили тяжелую производственную травму.}
{9505}{}{|0xFFFF00 В результате ошибки Вы сильно рассекли бровь, кровь заливает лицо.}

# Blood loss
{9510}{}{|0xFFFF00 Вы чувствуете слабость от обильной кровопотери.}
{9511}{}{|0xFFFF00 Силы покидают вас, вы начинаете медленно умирать от потери большого количества крови.}

# Vomiting
{9512}{}{|0xFFFF00 Вас начало мутить...}
{9513}{}{блюет}
{9514}{}{|0xFFFF00 Кажется, Вас сейчас стошнит...}
{9515}{}{сует два пальца в рот}
{9516}{}{"|0xFFFF00 Ваш желудок пуст..."}

# Resurection
{9519}{}{медикаментозная передозировка}
{9520}{}{|0xFFFF00 Потратив препарат, вы поняли, что он тут не поможет.}
{9521}{}{|0xFFFF00 Ваш организм получил шанс на выживание, но ваше здоровье никогда не станет прежним.}
{9522}{}{|0xFFFF00 Вам четко видно, что организм этого человека не перенесет дозу стимулятора.}

# Food / drink
{9523}{}{урчит животом}
{9524}{}{облизывает сухие губы}
{9525}{}{шатается}
{9526}{}{|0xFFFF00 Полученные повреждения слишком обширны. Без медицинского вмешательства вы скоро умрёте.}
{9527}{}{|0xFFFF00 Вы страдаете от голода.}
{9528}{}{|0xFFFF00 Вы страдаете от жажды.}
{9529}{}{|0xFFFF00 Вы перестали чувствовать вкус алкоголя...}
{9530}{}{|0xFFFF00 Из-за сильной жажды Вы стали двигаться медленее.}
{9531}{}{|0xFFFF00 Из-за сильного голода Вы стали двигаться медленее.}
{9532}{}{|0xFFFF00 Вы набрались сил.}
{9533}{}{пьет}
{9534}{}{Вы употребили: |0xFFFF00 @lex proto@|0x3CF800 .}
{9535}{}{Вы потеряли: |0xFFFF00 @lex rad@|0x3CF800  рад.}
{9536}{}{Вы получили: |0xFFFF00 @lex poison@|0x3CF800  пунктов отравления.}
{9537}{}{употребляет @lex proto@}

# Dragging
{9540}{}{|0xFFFF00 Вы не можете сделать этого.}
{9541}{}{|0xFFFF00 Цель должна лежать или быть мертва!}
{9542}{}{|0xFFFF00 Цель слишком далеко.}
{9543}{}{|0xFFFF00 Тело уже тащат.}
{9544}{}{|0xFFFF00 Вы не можете тащить больше 1 тела.}
{9545}{}{|0xFFFF00 Вы тащите тело.}
{9546}{}{|0xFFFF00 Вы отпустили тело.}

# Dirt
{9550}{}{|0xFFFF00 Вы начали отталкивать окружающих обилием грязи и неприятным запахом. Вам бы не помешало помыться.}
{9551}{}{|0xFFFF00 Вы перестали отталкивать окружающих своей грязью и запахом.}

# Lie / stand
{9552}{}{|0xFFFF00 Вы не в силах подняться.}
{9553}{}{|0xFFFF00 Вы встаёте.}
{9554}{}{|0xFFFF00 Вы ложитесь.}

# Locks and lockpicking
{9568}{}{|0xFFFF00 Для установки кодового замка Вам потребуется моток медной проволки.}
{9569}{}{начинает устанавливать замок}
{9570}{}{начинает снимать замок}
{9571}{}{|0xFFFF00 Вы не можете найти ни одного места, за которое вы могли-бы ухватиться.}
{9572}{}{Кладет что-то в почтовый ящик}
{9573}{}{Щуп застрял, нужно чуть ослабить зажим и попробовать еще раз.}
{9574}{}{Вы продвинули щуп глубже.}
{9575}{}{Щуп уперся в конец.}
{9576}{}{Вы вынули щуп на ближнюю позицию.}
{9577}{}{Щуп уже в крайнем положении, остается только вытащить его.}
{9578}{}{Щуп уперся, пружина язычка уже максимально зажата.}
{9579}{}{Щуп на первой позиции.}
{9580}{}{Вы подвинули щупом язычек замка вверх.}
{9581}{}{Вы подвинули щупом язычек замка вниз.}
{9582}{}{ |0xFFFF00 Вы были не готовы и совершили ошибку.|0x3CF800 }
{9583}{}{Замок не поддался.}
{9584}{}{ |0xFFFF00 Вы слышите щелчок.|0x3CF800 }
{9585}{}{|0xFFFF00 Амбарный|0x3CF800 }
{9586}{}{|0xFFFF00 Дверной|0x3CF800 }
{9587}{}{|0xFFFF00 Сейфовый|0x3CF800 }
{9588}{}{Код двери: |0xFFFF00 @lex code@|0x3CF800 , ваш: |0xFFFF00 @lex attempt@|0x3CF800 }
{9589}{}{

   Позиция щупа - |0xFFFF00 @lex posToung@|0x3CF800 
   Глубина щупа - |0xFFFF00 @lex posLockpick@|0x3CF800 
@lex secret@}
{9590}{}{@lex state@@lex toung@}
{9591}{}{Осмотреть замок}
{9592}{}{Отмычку дальше}
{9593}{}{Отмычку ближе}
{9594}{}{Отмычку выше}
{9595}{}{Отмычку ниже}
{9596}{}{Повернуть отмычку}
{9597}{}{Вынуть отмычку}
{9598}{}{Запереть}
{9599}{}{Состояние замка неизвестно}
{9600}{}{|0xFFFF00 С этой стороны в замок вставлен ключ, который вам мешает.}
{9601}{}{|0xFFFF00 С другой стороны в замок вставлен ключ, который вам мешает.}
{9602}{}{|0xFFFF00 Вы отперли замок.}
{9603}{}{отпирает}
{9604}{}{|0xFFFF00 Вы заперли замок.}
{9605}{}{запирает}
{9606}{}{|0xFFFF00 Сначала закройте.}
{9607}{}{|0xFFFF00 Ключ не подходит.}
{9608}{}{|0xFFFF00 Что-то не даёт закрыть дверь.}
{9609}{}{|0xFFFF00 Нужна электроная отмычка.}
{9610}{}{|0xFFFF00 Вы слишком далеко от цели.}
{9611}{}{|0x606060 тук-тук}
{9612}{}{|0xFFFF00 Вы постучали.}
{9613}{}{|0xFF0000 УДАР}
{9614}{}{|0xFFFF00 Дверь и так открыта.}
{9615}{}{|0xFFFF00 Нет замка.}
{9616}{}{|0xFFFF00 Нужны отмычки или хотя бы какая-никакая шпилька.}
{9617}{}{|0xFFFF00 Отмычка сломалась, видимо ее неудачно вытащили из замка в прошлый раз.}
{9618}{}{вынимает ключ из замка}
{9619}{}{вставляет ключ в замок}
{9620}{}{|0xFFFF00 Вы слишком далеко от замка, ваши отмычки сломались.}
{9621}{}{|0xFFFF00 Вы успешно вскрыли замок.}
{9622}{}{|0xFFFF00 Вы аккуратно вытащили отмычку из замка.}
{9623}{}{|0xFFFF00 Вашего навыка недостаточно, чтобы защелкнуть замок.}
{9624}{}{|0xFFFF00 Дверь и так заперта.}
{9625}{}{|0xFFFF00 Вы защелкнули замок.}
{9626}{}{|0xFFFF00 Вы сняли замок.}
{9627}{}{|0xFFFF00 Заперто.}
{9628}{}{|0xFFFF00 Закрыто.}
{9629}{}{Код: |0xFFFF00 @lex code@|0x3CF800 .}
{9631}{}{Постучать}
{9632}{}{Выбить}
{9633}{}{Взломать}
{9634}{}{Запереть}
{9635}{}{Отпереть}
{9636}{}{Извлечь ключ}
{9637}{}{Вставить ключ}

# item taking
{9638}{}{сопротивляется}
{9639}{}{пытается что-то отобрать}
{9640}{}{|0xFFFF00 Вы слишком устали, что бы успешно отобрать вещь.}

# handcuffs
{9641}{}{Вы собираетесь связать себя: |0xFFFF00 @lex proto@|0x3CF800 .}
{9642}{}{На вас хотят надеть: |0xFFFF00 @lex proto@|0x3CF800 .}
{9643}{}{Согласиться}
{9644}{}{|0xFFFF00 Вы подчинились!}
{9645}{}{|0xFFFF00 Жертва подчинилась!}
{9646}{}{|0xFFFF00 Жертва осмелилась оказать сопротивление!}
{9647}{}{|0xFFFF00 Вы ждете подчинения жертвы!}
{9648}{}{|0xFFFF00 Ваши руки связаны!}

{9649}{}{|0xFFFF00 Вам нужно иметь подходящий ключ в инвентаре.} # TODO: reorder whole file to return that back into original position #9602

# decraft and repair
{9650}{}{|0xFFFF00 Этот объект не подлежит износу.}
{9651}{}{|0xFF0000 Вы травмированы и не в состоянии произвести ремонт.}
{9652}{}{|0xFFFF00 Не ремонтируемо!}
{9653}{}{|0xFF0000 Вы травмированы и не в состоянии разобрать предмет.}
{9654}{}{завершает разборку}
{9655}{}{|0xFF0000 Вам нехватает навыков.}
{9656}{}{завершает работу}
{9657}{}{|0xFFFF00 В этой броне уже встроена рация.}
{9658}{}{завершает установку рации в броню}
{9659}{}{|0xFFFF00 Эту броню перекрасить не удастся.}
{9660}{}{|0xFF0000 Вы травмированы и не в состоянии перекрасить броню.}
{9661}{}{завершает перекраску брони}
{9662}{}{|0xFF0000 Вы травмированы и не в состоянии установить рацию.}
{9663}{}{Необходимый инструмент: }
{9664}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9665}{}{Необходимые запчасти: }
{9666}{}{|0x3CF800  - |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800  шт.}
{9667}{}{Необходим один из инструментов в руке: }
{9668}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9669}{}{Получаемые части: }
{9670}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9671}{}{Вы разобрали |0xFFFF00 @lex proto@|0x3CF800 , получив: }
{9672}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9673}{}{|0xFFFF00 Вы не смогли произвести установку рации!}
{9674}{}{|0x3CF800 Необходимо иметь навыки:
 - |0xFFFF00 Наука |0x3CF800  -  |0xFFFF00 150 |0x3CF800 ,
 - |0xFFFF00 Ремонт |0x3CF800  -  |0xFFFF00 200 |0x3CF800 .}
{9675}{}{Вам необходимы инструменты из списка ниже и Вы должны держать один из них: }

# Flasks and bottles
{9750}{}{|0xFFFF00 Ваша анатомия не позволяет Вам открыть бутылку!}
{9751}{}{|0xFFFF00 Вам нечем открыть бутылку!}
{9752}{}{Вы открыли бутылку: |0xFFFF00" @lex proto@|0x3CF800.}
{9753}{}{открывает бутылку}
{9754}{}{|0xFFFF00 Возьмите предмет в руку!}
{9755}{}{|0xFFFF00 Попробуйте заполнить бутылку другим способом.}
{9756}{}{|0xFFFF00 У Вас закончилась тара.}
{9757}{}{|0xFFFF00 Вы разлили всю воду по бутылкам.}
{9758}{}{|0xFFFF00 Емкость заполнена чем-то другим.}
{9759}{}{наполняет @lex proto@}
{9760}{}{|0xFFFF00 Возьмите емкость в руку.}
{9761}{}{|0xFFFF00 Емкость пуста.}
{9762}{}{выливает @lex proto@}
{9763}{}{|0xFFFF00 Емкость уже заполнена.}
{9764}{}{|0xFFFF00 Вы наполнили емкость.}
{9765}{}{|0xFFFF00 Тара опустела.}
{9766}{}{|0xFFFF00 Воды больше нет.}
{9767}{}{|0xFFFF00 У вас нет подходящей бутылки в руках.}
{9768}{}{|0xFFFF00 Вы полностью наполнили бутылку водой.}

# Oxygen Tank
{9769}{}{Подключает кислородный баллон}
{9770}{}{Отключает килородный баллон}
{9771}{}{Кислородный баллон кончился.}
{9772}{}{Нет кислорода в баллоне.}
{9773}{}{Кислорода осталось: @lex charge@}
{9774}{}{Прежде чем сделать это, вы отключаете предыдущий кислородный баллон.}
{9775}{}{}

# Motion Sensor
{9780}{}{:контакт:}
{9781}{}{|0xFFFF00 В датчике движения нет заряда!}
{9782}{}{включает датчик движения}
{9783}{}{отключает датчик движения}

# Smoking
{9786}{}{поджигает курево}
{9787}{}{вскрывает пачку сигарет}
{9788}{}{|0xFFFF00 В пачке больше не осталось сигарет.}
{9789}{}{достаёт сигарету из пачки}
{9790}{}{|0xFFFF00 Вам нужен источник огня, что бы прикурить.}
{9791}{}{|0xFFFF00 Вы не можете курить через респиратор.}
{9792}{}{|0xFFFF00 Возьмите предмет в руку, чтобы закурить.}
{9793}{}{|0xFFFF00 Трубка пуста.}
{9794}{}{|0xFFFF00 Курево прогорело.}
{9795}{}{|0xFFFF00 Вы заправили трубку.}
{9796}{}{|0xFFFF00 Мешочек опустел.}
{9797}{}{|0xFFFF00 Возьмите трубку в руку, чтобы заправить ее.}
{9798}{}{|0xFFFF00 Вы чувствуете вкус табака.}
{9799}{}{|0xFFFF00 Вы чувствуете вкус пятилистника.}

# Various Items
{9800}{}{щёлкает фотоаппаратом}
{9801}{}{убирает золу}
{9802}{}{убирает останки}
{9803}{}{вытирает кровь}
{9804}{}{|0xFFFF00 Вы убрали часть останков.}
{9805}{}{|0xFFFF00 Вы собрали останки.}
{9806}{}{|0xFFFF00 Возьмите музыкальный инструмент в руку.}
{9807}{}{играет на флейте}
{9808}{}{|0xFFFF00 Попробуйте копать ближе к себе.}
{9809}{}{|0xFFFF00 В этом месте нельзя копать.}
{9810}{}{|0xFFFF00 Что в этом предмете особенного?}
{9811}{}{|0xFFFF00 Похоже, вы без понятия, что с этим можно делать.}
{9812}{}{|0xFFFF00 Сначала достаньте предмет из контейнера!}
{9813}{}{|0xFFFF00 Теперь этот предмет имеет отличительные особенности.}
{9814}{}{|0xFFFF00 Вы сделали так, что бы этот предмет больше ничем не выделялся.}
{9815}{}{разжигает лампу}
{9816}{}{|0xFFFF00 Для розжига лампы нужна зажигалка!}
{9817}{}{|0xFFFF00 В лампе нет масла.}
{9818}{}{гасит лампу}
{9819}{}{включает фонарь}
{9820}{}{|0xFFFF00 В фонаре нет заряда.}
{9821}{}{выключает фонарь}
{9822}{}{разжигает химический фонарик}
{9823}{}{гасит химический фонарик}
{9824}{}{вытирается полотенцем}
{9825}{}{вытирается грязны полотенцем}
{9826}{}{моет полотенце}
{9827}{}{меняет батарею}
{9828}{}{заправляет фонарик}
{9829}{}{|0xFFFF00 Не удалось впихнуть предмет в контейнер.}
{9830}{}{Серийный номер: }

# Ropes and shackles
{9831}{}{|0xFFFF00 Вы не можете освободить себя таким образом.}
{9832}{}{|0xFFFF00 Это здесь не поможет.}
{9833}{}{особождает цель}
{9834}{}{освобождается}
{9835}{}{|0xFFFF00 Без монтировки тут не обойтись.}
{9836}{}{высвобождает цель из капкана}
{9837}{}{высвобождается из капкана}
{9838}{}{|0xFFFF00 Вы высвобождены из капкана!}
{9839}{}{|0xFFFF00 Ключ не подходит.}
{9840}{}{|0xFFFF00 Предмет сломан и не может быть использован.}
{9841}{}{|0xFFFF00 Это бесполезно, цель мертва.}
{9842}{}{|0xFFFF00 Цель уже связана аналогичным предметом!}

{9843}{}{надевает на себя наручники}
{9844}{}{надевает наручники}
{9845}{}{|0xFFFF00 Вы надели на себя наручники.}
{9846}{}{|0xFFFF00 На вас одели наручники!}
{9847}{}{|0xFFFF00 Вы освобождены от наручников.}
{9848}{}{снимает с себя наручники}
{9849}{}{снимает наручники}

{9850}{}{связывает себя}
{9851}{}{связывает}
{9852}{}{|0xFFFF00 Вы связали сами себя.}
{9853}{}{|0xFFFF00 Вас связали!}
{9854}{}{|0xFFFF00 Вы освобождены от веревки.}
{9855}{}{режет связывающую руки веревку}
{9856}{}{режет веревку}

{9857}{}{надевает на себя кандалы}
{9858}{}{надевает кандалы}
{9859}{}{|0xFFFF00 Вы надели на себя кандалы.}
{9860}{}{|0xFFFF00 На вас одели кандалы!}
{9861}{}{|0xFFFF00 Вы освобождены от кандалов.}
{9862}{}{снимает с себя кандалы}
{9863}{}{снимает кандалы}

{9864}{}{засовывает шариковый кляп себе в рот}
{9865}{}{засовывает шариковый кляп в рот}
{9866}{}{|0xFFFF00 Вы засунули шариковый кляп себе в рот.}
{9867}{}{|0xFFFF00 Вам засунули шариковый кляп в рот.}
{9868}{}{|0xFFFF00 Из вашего рта вынут шариковый кляп.}
{9869}{}{вытаскивает шариковый кляп из своего рта}
{9870}{}{вытаскивает шариковый кляп}

{9871}{}{засовывает кляп себе в рот}
{9872}{}{засовывает кляп в рот}
{9873}{}{|0xFFFF00 Вы засунули кляп себе в рот.}
{9874}{}{|0xFFFF00 Вам засунули кляп в рот.}
{9875}{}{|0xFFFF00 Из вашего рта вынут кляп.}
{9876}{}{вытаскивает кляп из своего рта}
{9877}{}{вытаскивает кляп}

{9878}{}{надевает на себя рабский ошейник}
{9879}{}{надевает рабский ошейник}
{9880}{}{|0xFFFF00 Вы надели на себя рабский ошейник.}
{9881}{}{|0xFFFF00 На вас одели рабский ошейник!}
{9882}{}{|0xFFFF00 Вы освобождены от рабского ошейника.}
{9883}{}{снимает с себя рабский ошейник}
{9884}{}{снимает рабский ошейник}

{9885}{}{|0xFFFF00 Вы отремонтировали наручники.}
{9886}{}{|0xFFFF00 Вы отремонтировали кандалы.}
{9887}{}{|0xFFFF00 Связанные руки не позволяют Вам сделать это.}
{9888}{}{|0xFFFF00 Собаком не доступно данное действие.}
{9889}{}{|0xFFFF00 Люди не могут это носить.}

{9890}{}{|0xFFFF00 Вы освободили раба.}
{9891}{}{|0xFFFF00 Вы наказали раба.}
{9892}{}{|0xFFFF00 Шею обожгло огнем, все тело сотрясают судороги.}
{9893}{}{корчится в агонии}
{9894}{}{|0xFFFF00 Шею обожгло огнем, Вы содрагаетесь под множественными ударами тока.}
{9895}{}{|0xFFFF00 Шею обожгло огнем, все тело содрагается от мощнейшей непрекращающейся боли.}
{9896}{}{|0xFFFF00 Вы казнили раба}
{9897}{}{|0xFFFF00 Боль тысячи расскаленных игл пронзила вас}
{9898}{}{нажимает кнопку}

# Forgot to activate char
{9899}{}{с громким хлопком скукоживается в точку}

# General stuff
{9900}{}{одышка}
{9901}{}{потирает ушиб}
{9902}{}{вскрикивает от боли}
{9903}{}{хватается за окровавленную конечность}
{9904}{}{орет от боли}
{9905}{}{воет от дикой боли}
{9906}{}{поскальзывается на чем-то гадком}
{9907}{}{Вы выронили: |0xFFFF00 @lex proto@ |0x3CF800 из рук.}
{9908}{}{|0xFFFF00 Вас обжигает кислотой.}
{9909}{}{перебинтовывает}
{9910}{}{перебинтовывается}
{9911}{}{|0xFFFF00 Из этого ничего не вышло.}
{9912}{}{осматривает тело}

#Harmonica
{9913}{}{играет на гармошке}

# Key duplicate
{9914}{}{|0xFFFF00 Вы сделали копию ключа.}

# X2 X3 containers
{9915}{}{|0xFFFF00 Контейнер переполнен, освободите чаcть веса для того, чтобы снять верхний ящик.}

# Sandbags
{9916}{}{|0xFFFF00 Существо мешает установить мешки.}
{9917}{}{|0xFFFF00 Вы не можете сделать эту груду мешков выше.}

# Locks
{9918}{}{|0xFFFF00 Вы не можете запереть терминал на замок.}
{9919}{}{|0xFFFF00 Вам нужна хотя бы одна железяка для заготовки ключа под устанавливаемый замок.}
{9920}{}{|0xFFFF00 На двери итак уже есть замок, нужно снять текущий, для этого хорошо подойдут |0xABABAB Инструменты.}
{9921}{}{|0xFFFF00 Сначала закройте объект.}
{9922}{}{|0xFFFF00 Этот объект нельзя запереть.}

# Dismantling / securing items
{9923}{}{|0xFFFF00 Предмет поднимаем, теперь его можно перенести на новое место.}
{9924}{}{|0xFFFF00 Предмет надежно закреплен.}

# CarryItems
{9925}{}{|0xFFFF00 Это не поднять!}
{9926}{}{|0xFFFF00 Cлишком тяжело!}
{9927}{}{|0xFFFF00 Вы не можете это поднять, так как несете максимальный груз!}
{9928}{}{|0xFFFF00 Вы не можете это поднять, так как несете слишком много предметов!}

# Furniture
{9929}{}{|0xFFFF00 У вас нет подходящего ключа.}
{9930}{}{|0xFFFF00 Возьмите ключ или ключницу в руку.}
{9931}{}{останавливается}
{9932}{}{|0xFFFF00 Это сюда не влезет.}
{9933}{}{|0xFFFF00 Требуется демонтаж.}
{9934}{}{|0xFFFF00 Из этого ничего не вышло.}
{9935}{}{|0xFFFF00 Заперто.}
{9936}{}{|0xFFFF00 Слишком тяжело.}
{9937}{}{|0xFFFF00 Данный объект так просто не сдвинуть. Сначала снимите замок.}
{9938}{}{|0xFFFF00 Предмет поднимаем. Что бы изменить состояние - используйте ремонт.}
{9939}{}{|0xFFFF00 Предмет неподъёмен. Что бы изменить состояние - используйте ремонт.}
{9940}{}{пытается остановить}
{9941}{}{|0xFFFF00 Нельзя перемещать закрытую и запертую мебель.}
{9942}{}{толкает}
{9943}{}{|0xFFFF00 Вы не можете сделать стэк контейнеров выше.}
{9944}{}{|0xFFFF00 Существо мешает установить контейнер.}
#TODO: {9945}{}{тянет}
#TODO: {9946}{}{В телегу можно класть только пустые контейнеры!}
#TODO: {9947}{}{переворачивает}
#TODO: {9948}{}{поправляет}
#TODO: {9949}{}{|0xFFFF00 Предмет проходим.}
#TODO: {9950}{}{|0xFFFF00 Предмет непроходим.}

# No access for mob control
{9945}{}{|0xFFFF00 Требуется уровень ГМ досутпа.}

# h-attack
{9946}{}{|0xFFFF00 Этим нельзя драться.}

# use radio
{9947}{}{говорит в рацию}

# #zh - command
{9948}{}{|0xFFFF00 Вы отправили @lex npc$@ на домашнюю позицию.}
{9949}{}{|0xFFFF00 Существо @lex npc$@ и так на домашней позиции.}

# push target
{9950}{}{|0xFFFF00 Вы толкаете цель.}
{9951}{}{|0xFFFF00 Цель сопротивляется.}

# ~naked - command
{9952}{}{раздевается}

# #desc - command
{9954}{}{|0xFFFF00 Вы заметили:
|0xABABAB @lex desc@}

# Throw
{9958}{}{|0xFFFF00 Вы не в состоянии кидать так далеко.}
{9959}{}{|0xFFFF00 Вы не можете бросить это.}
{9960}{}{ловит предмет}
{9961}{}{не может поймать предмет}
{9962}{}{:разбилась вдребезги:}
{9963}{}{бросает предмет}

# Knocking
{9964}{}{|0xFFFF00 Недостаточно очков действия.}
{9965}{}{|0xFFFF00 Вы не в состоянии сделать это.}
{9966}{}{|0xFFFF00 Вы промахнулись по цели.}
{9967}{}{|0xFFFF00 Вы не можете бить так часто.}
{9968}{}{:стук:}
{9969}{}{|0xFFFF00 Вы постучали.}
{9970}{}{|0xFFFF00 Вы слишком далеко!}

# Code door password
{9971}{}{Вы установили новый код: |0xFFFF00 @lex code@}
{9972}{}{|0xFFFF00 Не допустимый код!}
{9973}{}{|0xFFFF00 Не верный код!}

# Change Lex self
{9974}{}{|0xFFFF00 Вы изменили своё описание.}
# TODO:{9975}{}{|0xFFFF00 Вы включили АФК-режим.}
# TODO:{9976}{}{|0xFFFF00 Вы отключили АФК-режим.}

# Digits input
{9975}{}{Вы установили новый пароль: |0xFFFF00 @lex digits@}
{9976}{}{|0xFFFF00 Вы ввели верный пароль!}
{9977}{}{|0xFFFF00 Пароль не подходит!}

# Suicide
{9978}{}{вспарывает себе живот}
{9979}{}{пытается душить себя}
{9980}{}{раскрутив барабан, приставляет револьвер к виску}
{9981}{}{засовывает дуло себе в рот}
{9982}{}{приставляет ствол к собстенному боку, палец ложится на спусковой крючок}
{9983}{}{прижав гранату к груди выдергивает чеку}
{9984}{}{вырвав тряпку, выливает на себя содержимое бутылки, в руке появилась зажигалка...}
{9985}{}{приставляет острый предмет к собственному животу}
{9986}{}{подносит пузырек с химикатами ко рту...}
{9987}{}{|0xFFFF00 Вам нечем убить себя.}
{9988}{}{вышибает собственные мозги}
{9989}{}{череп разлетается кровавым фонтаном, забрызгивая все вокруг}
{9991}{}{умножает себя на два}
{9992}{}{голова испараяется мнгновенно}
{9993}{}{тело содрагается от разряда}
{9994}{}{пытается застерлиться тратя заряд, неудобное оружие падает}
{9995}{}{спусковая скоба отлетает в сторону}
{9996}{}{|0xFFFF00 Граната сработала без особого эффекта.}
{9997}{}{выпивает пузырек}
{9998}{}{поджигает себя, огонь жадно пожирает все вокруг}

# Toilet
{9999}{}{смывает что-то в унитаз}

# StartMap
{10000}{}{|0xFFFF00 Ошибка, обратитесь к ГеймМастерам.}
{10001}{}{|0xFFFF00 Старт игры возможен только для новых персонажей.}
{10002}{}{|0xFFFF00 Старт игры возможен только на стартовой карте.}
{10003}{}{|0xFFFF00 Попробуйте еще раз.}
{10004}{}{|0xFFFF00 Вы выбрали режим выживания.}
{10005}{}{|0xFFFF00 Локация не найдена}
{10006}{}{|0xFFFF00 Карта не найдена}
{10007}{}{|0xFFFF00 Весь регион веет тоской, но кажется, несколько шагов вперед изменят вашу судьбу...}
{10008}{}{|0xFFFF00 Предмет был поглощен пустотой.}
{10009}{}{|0xFFFF00 Вам кажется сейчас это неуместо.}

# Gm Mode
{10010}{}{|0xFFFFFF Модерка включена.}
{10011}{}{|0x606060 Модерка выключена.}
{10012}{}{|0xFFFFFF ГМ-инвиз включен.}
{10013}{}{|0x606060 ГМ-инвиз выключен.}
{10014}{}{|0xFFFFFF Хоткеи включены.}
{10015}{}{|0x606060 Хоткеи выключены.}

{10016}{}{|0xFFFF00 Вы включили АФК-режим.} # TODO: reorder whole file to return that back into original position #9975

{10017}{}{|0xFFFF00 Предмет на вашей спине мешает вам переодеться.}	# TODO: reorder whole file to return that back into original position #9890
{10018}{}{|0xFFFF00 Ваш предмет слишком сломан, чтобы его можно было использовать.}	# TODO: reorder whole file to return that back into original position #9891
{10019}{}{|0xFFFF00 Ваш инструмент сломался.} # TODO: reorder whole file to return that back into original position #9900
{10020}{}{|0xFFFF00 В этом месте от страданий так легко не избавиться!} # TODO: reorder whole file to return that back into original position #9978

{10021}{}{|0xFFFF00 Нет доступа к БД.}
{10022}{}{начинает тянуть} # TODO: reorder whole file to return that back into original position #9945
{10023}{}{|0xFFFF00 Вы отключили АФК-режим.} # TODO: reorder whole file to return that back into original position #9976
{10024}{}{|0xFFFF00 В телегу можно класть только пустые контейнеры!} # TODO: reorder whole file to return that back into original position #9946
{10025}{}{переворачивает} # TODO: reorder whole file to return that back into original position #9947
{10026}{}{поправляет} # TODO: reorder whole file to return that back into original position #9948
{10027}{}{|0xFFFF00 Предмет проходим.} # TODO: reorder whole file to return that back into original position #9949
{10028}{}{|0xFFFF00 Предмет непроходим.} # TODO: reorder whole file to return that back into original position #9950

# Grid_to_global_warning
{15000}{}{|0xFFFF00 Вам становится страшно.}
{15000}{}{|0xFFFF00 Вам больше некуда идти.}
{15000}{}{|0xFFFF00 Впереди вы видите только мёртвый песок и понимаете, что начав путь туда, вы обречёте себя на верную смерть. Поэтому вам ничего не остаётся, кроме как влачить свое жалкое существование здесь, борясь за кусок мяса с другими людьми и животными.}
{15000}{}{|0xFFFF00 Там нет жизни.}
{15000}{}{|0xFFFF00 Там вас ничего не ждёт.}

# lifts:
# {2GG00} is key card item proto name from data/ItemNames.lst where GG is lifts group
# {2GGFF} is floor name where GG is lifts group, FF is floor

{20100}{}{PID_V15_KEYCARD}
{20101}{}{4 - Рубка}
{20102}{}{3 - Переговорная}
{20103}{}{2 - Казарма}
{20104}{}{1 - Столовая}
{20105}{}{0 - Камбуз}

{20201}{}{1 - Торговая}
{20202}{}{2 - Барная}
{20203}{}{3 - Промышленная}
{20204}{}{4 - Дыра}

{20301}{}{4 - Номера Люкс}
{20302}{}{3 - Номера Бизнес}
{20303}{}{2 - Номера Эконом}
{20304}{}{1 - Клуб}
{20305}{}{0 - Лобби}

{20400}{}{PID_SECURITY_CARD}
{20401}{}{1 - Поверхность}
{20402}{}{2 - Бункер}
{20403}{}{3 - Технический уровень}

{20500}{}{PID_TERMINAL_METAL_KEY}
{20501}{}{0 - Поверхность}
{20502}{}{1 - Химзавод}

{20601}{}{1 - Первый Этаж}
{20602}{}{0 - Лобби}

{20700}{}{PID_TERMINAL_METAL_KEY}
{20701}{}{1 - Вершина}
{20702}{}{0 - Перфекшен}

{20801}{}{1 - Вход}
{20802}{}{2 - Жилые помещения}
{20803}{}{3 - Управление Убежищем}
{20804}{}{4 - Промышленный уровень}

{20901}{}{0 - Командная палуба}
{20902}{}{1 - Вход}

{21000}{}{PID_RED_PASS_KEY}
{21001}{}{0 - Лобби}
{21002}{}{1 - Уровень 1}
{21003}{}{2 - Уровень 2}

{21100}{}{PID_BLUE_PASS_KEY}
{21101}{}{0 - Укрытие}
{21102}{}{1 - Станция}

{21200}{}{PID_BLUE_PASS_KEY}
{21201}{}{0 - Поверхность}
{21202}{}{1 - Уровень 1}

{21300}{}{PID_YELLOW_PASS_KEY}
{21301}{}{0 - Поверхность}
{21302}{}{1 - Уровень 1}

{21400}{}{PID_RED_PASS_KEY}
{21401}{}{0 - Уровень 1}
{21402}{}{1 - Уровень 2}

{21500}{}{PID_YELLOW_PASS_KEY}
{21501}{}{1 - Укрытие}
{21502}{}{2 - Станция}

{21601}{}{0 - Укрытие}
{21602}{}{1 - Станция}

{21701}{}{0 - Поверхность}
{21702}{}{1 - Уровень 1}
{21703}{}{2 - Уровень 2}

{21801}{}{0 - Уровень 3}
{21802}{}{1 - Уровень 2}
{21803}{}{2 - Уровень 1}

{21901}{}{1 - Уровень 3}
{21902}{}{2 - Уровень 2}

{22001}{}{1 - Уровень 2}
{22002}{}{0 - Уровень 1}

{22101}{}{1 - Уровень 3}
{22102}{}{0 - Уровень 2}

{22201}{}{2 - Уровень 3}
{22202}{}{1 - Уровень 2}
{22203}{}{0 - Уровень 1}

{22301}{}{1 - Уровень 3}
{22302}{}{0 - Уровень 2}

{22401}{}{1 - Уровень 1}
{22402}{}{2 - Уровень 2}
{22403}{}{3 - Уровень 3}
{22404}{}{4 - Уровень 4}

{22501}{}{0 - Поверхность}
{22502}{}{1 - Уровень 1}
{22503}{}{2 - Уровень 2}

{22600}{}{PID_BLUE_PASS_KEY}
{22601}{}{0 - Укрытие}
{22602}{}{1 - Станция}

{22701}{}{1 - Уровень 1}
{22702}{}{2 - Уровень 2}

{22801}{}{0 - Поверхность}
{22802}{}{1 - Уровень 1}

{22901}{}{1 - Уровень 1}
{22902}{}{2 - Уровень 2}

#Scav demo vault

{23001}{}{1 - Уровень 1}
{23002}{}{2 - Уровень 2}

{23100}{}{PID_TERMINAL_ADVANCED_KEY}
{23101}{}{1 - Уровень 2}
{23102}{}{2 - Уровень 3}

{23201}{}{1 - Уровень 1}
{23202}{}{2 - Уровень 2}

#Rado Springs

{23301}{}{0 - Ground Floor}
{23302}{}{1 - First Floor}
{23303}{}{2 - Second Floor}
{23304}{}{3 - Third Floor}

{23401}{}{0 - Ground Floor}
{23402}{}{1 - First Floor}
{23403}{}{2 - Second Floor}
{23404}{}{3 - Third Floor}
{23405}{}{4 - Fourth Floor}
{23406}{}{5 - Fifth Floor}
{23407}{}{6 - Sixth Floor}
{23408}{}{7 - Seventh Floor}

{23500}{}{PID_RED_PASS_KEY}
{23501}{}{0 - GrouИd}
{23502}{}{1 - TraDe}
{23503}{}{2 - MacHeeneZ}
{23504}{}{3 - RooMs I}
{23505}{}{4 - 4iLГ}

{23600}{}{PID_YELLOW_PASS_KEY}
{23601}{}{1 - tЯade}
{23602}{}{5 - Гabs}
{23603}{}{6 - Morkout}
{23604}{}{7 - Яooms II}
{23605}{}{8 - Rooms III}

{23701}{}{0 - Main Area}
{23702}{}{1 - GenOps}
{23703}{}{2 - Ref}

{23801}{}{2 - Second Floor}
{23802}{}{3 - Third Floor}
{23803}{}{4 - Fourth Floor}

{23901}{}{0 - Ground Floor}
{23902}{}{1 - First Floor}
{23903}{}{2 - Second Floor}
{23904}{}{3 - Third Floor}
{23905}{}{4 - Fourth Floor}
{23906}{}{5 - Fifth Floor}
{23907}{}{6 - Sixth Floor}
{23908}{}{7 - Seventh Floor}
{23909}{}{8 - Eighth Floor}
{23910}{}{9 - Nineth Floor}
{23911}{}{10 - Tenth Floor}

{24001}{}{0 - Ground Fxxor}
{24002}{}{1 - Fixxt Floor}
{24003}{}{2 - Second Floor}
{24004}{}{3 - Txxrd Floor}
{24005}{}{4 - Fourth Floor}
{24006}{}{5 - Fxxth Floor}

{24101}{}{Floor 0}
{24102}{}{Floor 1}
{24103}{}{Floor 2}
{24104}{}{Floor 3}
{24105}{}{Fxxxx X}

{24201}{}{G}
{24202}{}{I}
{24203}{}{II}
{24204}{}{III}

{24300}{}{PID_SECURITY_CARD}
{24301}{}{0 - Ground Floor}
{24302}{}{1 - First Floor}
{24303}{}{2 - Second Floor}
{24304}{}{3 - Third Floor}
{24305}{}{4 - Fourth Floor}
{24306}{}{5 - Fifth Floor}
{24307}{}{6 - Sixth Floor}
{24308}{}{7 - Seventh Floor}
{24309}{}{8 - Eighth Floor}
{24310}{}{9 - Nineth Floor}
{24311}{}{10 - Tenth Floor}
{24312}{}{11 - Eleventh Floor}
{24313}{}{12 - Twelfth Floor}
{24314}{}{13 - Thirteenth Floor}
{24315}{}{14 - Fourteenth Floor}

{24400}{}{PID_BLUE_PASS_KEY}
{24401}{}{0 - Reception}
{24402}{}{4 - Engineering Dept}
{24403}{}{5 - Assembly Dept}
{24404}{}{6 - Showroom}
{24405}{}{7 - Sales Dept}
{24406}{}{12 - Warehouse}
{24407}{}{13 - Top Floor}

{24501}{}{0 - Ground Floor}
{24502}{}{1 - First Floor}
{24503}{}{2 - Second Floor}
{24504}{}{3 - Third Floor}
{24505}{}{4 - Fourth Floor}

{24601}{}{0 - Ground Floor}
{24602}{}{1 - First Floor}
{24603}{}{2 - Second Floor}
{24604}{}{3 - Third Floor}
{24605}{}{4 - Fourth Floor}

# =========================
# Translation feature:
# =========================

#Устройства 99500 - 99600
{99501}{}{В сети}
{99502}{}{Не в сети}
{99503}{}{Активировать}
{99504}{}{Деактивировать}
{99505}{}{Увеличить радиус}
{99506}{}{Уменьшить радиус}
{99507}{}{Вставьте @lex balance_change@$}
{99508}{}{Сдача}
{99509}{}{Указать цену}
{99510}{}{Вкл.}
{99511}{}{Выкл.}
{99512}{}{Подкл.}
{99513}{}{Управл.}
{99514}{}{Актив.}
{99515}{}{Подключить}
{99516}{}{Обнулить}

#firestarter commands 99600 - 99700
{99601}{}{@lex firestate@ Объект заполненен топливом на |0xFFFF00 @lex occupancy_level@|0x3CF800 %

   Выберите действие:}
{99602}{}{Разжечь}
{99603}{}{Погасить}
{99604}{}{Добавить топливо}
{99605}{}{Готовка}
{99606}{}{Пожарить}
{99607}{}{Огонь не горит, вам может понадобиться топливо для розжига, кремень или зажигалка.}
{99608}{}{Огонь |0xFFFF00 горит|0x3CF800 .}
{99609}{}{Генератор |0xFFFF00 онлайн|0x3CF800 .}

#Мебель 99700 - 99800
{99701}{}{|0xF8F993 Вес: |0x00FF00 @lex weight@
@lex testInfo@
|0xF8F993 Объем: |0x00FF00 @lex volume@}
{99702}{}{Осмотреть}
{99703}{}{Открыть хранилище}
{99704}{}{Отсоединить}
{99705}{}{Установить}
{99706}{}{Поднять}
{99707}{}{Повернуть}
{99708}{}{Толкать}
{99709}{}{Остановиться}
{99710}{}{Запереть}
{99711}{}{Отпереть}
{99712}{}{Закрыть}
{99713}{}{Открыть}
{99714}{}{Заглянуть внутрь}
{99715}{}{Крафт}
{99716}{}{Печка}
{99717}{}{Интерфейс дробилки}
{99718}{}{Взлом}
{99719}{}{Растениеводство}
{99720}{}{Открыто}
{99721}{}{Закрыто}
{99722}{}{Тянуть}
{99723}{}{Перевернуть}
{99724}{}{:предметы рассыпаются по земле:}
{99725}{}{Убрать блокер}
{99726}{}{Поставить блокер}

{99750}{}{Интерфейс мельницы}

{99760}{}{Интерфейс козел}
{99761}{}{@lex contains@ 

Для работы с козлами требуется топор.}
{99762}{}{Рубить}
{99763}{}{|0x3CF800 На козлах нет подходящего бревна.}
{99764}{}{На козлах есть |0xFFFF00 @lex item@ |0x3CF800 - |0xFFFF00 @lex amount@ |0x3CF800 шт.}
{99765}{}{|0xFFFF00 Козлы пусты.}
{99766}{}{завершает работу}

{99770}{}{Интерфейс наковальни}

#Простые фразы 99800 - 99900
{99801}{}{Пусто!}
{99802}{}{Количество:}
{99803}{}{Текст:}
{99804}{}{Вкл}
{99805}{}{Выкл}
{99806}{}{Назад}
{99807}{}{Вперед}
{99808}{}{Подтвердить}
{99809}{}{Отказаться}
{99810}{}{Отмена}
{99811}{}{ не}
{99812}{}{@lex description@}
{99813}{}{есть @lex description@}
{99814}{}{нет @lex description@}
{99815}{}{Отсутствует}
{99816}{}{@lex name@}
{99817}{}{Да}
{99818}{}{Нет}
{99819}{}{Муж.}
{99820}{}{Жен.}
{99821}{}{+}
{99822}{}{-}
{99823}{}{ОШИБКА: @lex name@ не найдено!}
{99824}{}{Выберите действие:}
{99825}{}{Ничего не делать}


#Системные кнопки 99900 - 100000
{99901}{}{        Меню мебели}
{99902}{}{       Выключить меню}
{99903}{}{        Скрыть меню}
{99904}{}{           Назад}

{100000}{}{}

#player_menu.fos 100000 - 100050
{100001}{}{Скрытность: [ |0xFFFF00 @lex face@ |0x3CF800 ]   @lex STA@
Описание: [ |0xFFFF00 @lex desc@ |0x3CF800 ]     WSAD: [ |0xFFFF00 @lex WSAD@ |0x3CF800 ]
Печать: [ |0xFFFF00 @lex typing@ |0x3CF800 ]           RTS: [ |0xFFFF00 @lex RTS@ |0x3CF800 ]
Рация: [ |0xFFFF00 @lex radio@ |0x3CF800 ]
Лутовизор: [ |0xFFFF00 @lex visor@ |0x3CF800 ]
Речь: [ |0xFFFF00 @lex volume@ |0x3CF800 ]}
{100002}{}{Сокрытие лица}
{100003}{}{Подсветка целей}
{100004}{}{Скрыть описание}
{100005}{}{Скрыть печать}
{100006}{}{Безопасное радио}
{100007}{}{Движение WSAD}
{100008}{}{Движение RTS}
{100009}{}{Лутовизор }
{100010}{}{Прозрачность стен: @lex alpha@}
{100011}{}{Говорить громче}
{100012}{}{Говорить тише}
{100013}{}{Броски Кубика}
{100014}{}{Анимации}
{100015}{}{Действия}
{100016}{}{Введите Альфу: @lex vals@}
{100017}{}{STA: [ |0xFFFF00 @lex STA_status@ |0x3CF800 ]}
{100018}{}{Радиус голоса}
{100019}{}{Иконки Квестов}

{100020}{}{Выберите характеристику или тип кубика для броска.
Если выбрана характеристика, результатом будет ваша текущая характеристика + 2d6.}
{100021}{}{Бросить @lex stat@}
{100022}{}{Бросить @lex dice@}
{100023}{}{|0xFFFF00 Количество должно быть числом!}
{100024}{}{УСПЕХ}
{100025}{}{ПРОВАЛ}
{100026}{}{Лечь на живот}
{100027}{}{Лечь на спину}
{100028}{}{Пожирать}
{100029}{}{Попытка самоубийства}
{100030}{}{Предложить секс}
{100031}{}{Встать}
{100032}{}{Режим АФК}
{100033}{}{Отключить АФК}
{100034}{}{Описать себя}
{100035}{}{Описать вещь}
{100036}{}{Загрузить аватар}
{100037}{}{Проверить ID}
{100038}{}{Запомнить Имя}
{100039}{}{Попытаться сблевать}

{100040}{}{Выберите анимацию:}
{100041}{}{Подняться}
{100042}{}{Лежать}
{100043}{}{Полу-сидя}
{100044}{}{Прислониться 1}
{100045}{}{Прислониться 2}
{100046}{}{Сесть}
{100047}{}{На колено 1}
{100048}{}{На колено 2}
{100049}{}{Отжиматься}
{100050}{}{Присесть}
{100051}{}{Флексить}
{100052}{}{Пресс}

{100053}{}{Принятые вещества} #TODO: REORDER PROPERTLY
{100054}{}{Текущие зависимости:} #TODO: REORDER PROPERTLY
{100055}{}{   Стадия            Имя препарата                     Время} #TODO: REORDER PROPERTLY
{100056}{}{Эффект} #TODO: REORDER PROPERTLY
{100057}{}{Отходняк} #TODO: REORDER PROPERTLY
{100058}{}{Зависимость} #TODO: REORDER PROPERTLY
{100059}{}{Текущие эффекты:} #TODO: REORDER PROPERTLY

{100060}{}{Покрасить персонажа}

#furnace.fos 100100 - 100110
{100100}{}{|0xFFFF00 Энергопитание|0x3CF800 : [ |0xFFFF00 @lex powerStatus@ |0x3CF800 ] |0xFFFF00 Температура|0x3CF800 : @lex temp@C.
Выплавлено:
@lex empty@
@lex iron@
@lex gold@
@lex led@
@lex nf_metal@
@lex glass@}
{100101}{}{|0xFFFF00 Топливо|0x3CF800 : @lex fuel@% |0xFFFF00 Температура|0x3CF800 : @lex temp@C. Выплавлено: 
@lex empty@@lex iron@@lex gold@@lex nf_metal@@lex glass@}
{100102}{}{|0xFFFF00 Железа|0x3CF800 : @lex ironW@ кг.}
{100103}{}{|0xFFFF00 Золота|0x3CF800 : @lex goldW@ кг.}
{100104}{}{|0xFFFF00 Цветмета|0x3CF800 : @lex nf_metalW@ кг.}
{100105}{}{|0xFFFF00 Стекла|0x3CF800 : @lex glassW@ кг.}

#smithing:anvil 100110 - 100120
{100111}{}{@lex contains@ Для работы на наковальне требуется кувалда.}
{100112}{}{Ковать}
{100113}{}{|0x3CF800 На наковальне нет подходящего металлического слитка.}
{100114}{}{На наковальне есть |0xFFFF00 @lex item@ |0x3CF800 - |0xFFFF00 @lex amount@ |0x3CF800 шт.}

#smithing:crusher 100120 - 100130
{100121}{}{|0xFFFF00 Энергопитание|0x3CF800 : [ |0xFFFF00 @lex powerStatus@ |0x3CF800 ] |0xFFFF00 
@lex contains@}
{100122}{}{Бросить тело внутрь}
{100123}{}{|0x3CF800 Дробитель-2000 пуст.}
{100124}{}{Производственная линия загружена: |0xFFFF00 @lex item@ |0x3CF800 - |0xFFFF00 @lex amount@ |0x3CF800 шт.}
{100125}{}{|0x3CF800 Дробитель-2000 загружен мусором}

#Milling
{100131}{}{@lex contains@}
{100132}{}{Молоть}
{100133}{}{|0x3CF800 В мельнице нет необходимого ресурса.}
{100134}{}{Внутри мельницы находится: |0xFFFF00 @lex item@ |0xFFFF00 @lex amount@ |0x3CF800  шт.}

#bootlegging.fos	100150 - 100200
{100151}{}{Дистиллятор @lex state@
Сырья: |0xFFFF00 @lex raw@ |0x3CF800 л.
Топлива: |0xFFFF00 @lex fuel@ |0x3CF800 %
Получено |0xFFFF00 @lex product@ |0x3CF800 литров самогона.}
{100152}{}{Влить брагу}
{100153}{}{Очистить}
{100154}{}{Слить самогон}
{100155}{}{Техобслуживание}
{100156}{}{Закрыть заслонку}
{100157}{}{Открыть на 25%}
{100158}{}{Открыть на 50%}
{100159}{}{Открыть на 75%}
{100160}{}{Открыть полностью}
{100161}{}{потух}
{100162}{}{работает,
Температура: |0xFFFF00 @lex temp@ |0x3CF800 C.
Давление: |0xFFFF00 @lex press@ |0x3CF800 бар.}
{100163}{}{Закрыта}
{100164}{}{25%}
{100165}{}{50%}
{100166}{}{75%}
{100167}{}{Открыта}
{100168}{}{СБРОС ЖАРА}
{100169}{}{Выпускает пар}
{100170}{}{неисправен}

#casino 100200 - 100220
{100201}{}{Слотмашина № @lex casinoId@
Только нал!

@lex status@

@lex balance@}
{100202}{}{Ставка 5 $}
{100203}{}{Ставка 10 $}
{100204}{}{Ставка 25 $}
{100205}{}{Ставка 50 $}
{100206}{}{Ставка 100 $}
{100207}{}{Взять "руку"}
{100208}{}{Собрать колоду}
{100209}{}{ДЖЕКПОТ: |0xFFFF00 x@lex mul@ |0x3CF800 ОТ СТАВКИ!}
{100210}{}{Автомат пуст.}
{100211}{}{У вас: |0xFFFF00 @lex cash@|0x3CF800 $}
{100212}{}{Нет денег для игры.}
{100213}{}{Выберите действие:}
{100214}{}{Крышками}
{100215}{}{Монетами}
{100216}{}{Изменить тип валюты.}


#fish 100220 - 100250
{100221}{}{@lex pullOutFish@}
{100222}{}{Тянуть}
{100223}{}{Подсекать}
{100224}{}{Вытащить}
{100225}{}{Обрезать леску}
{100226}{}{Рыба уплыла!}
{100227}{}{Рыба на крючке!
Глубина: |0xFFFF00 @lex fishDepth@|0x3CF800 
Размер:  |0xFFFF00 @lex fishSize@|0x3CF800 
Рыба: |0xFFFF00 @lex fishAction@|0x3CF800 }
{100228}{}{неизвестно}
{100229}{}{тянет}
{100230}{}{мечется}


#jukebox 100250 - 100280
{100251}{}{@lex descriptionJukeBox@}
{100252}{}{Режим: @lex modeJukebox@}
{100253}{}{Включить}
{100254}{}{Автомат № |0xFFFF00 @lex jukeboxId@ |0x3CF800 @lex selectTune@ Громкость: |0xFFFF00 @lex soundRadius@
|0x3CF800 Режим: |0xFFFF00 @lex modeJukeboxDisc@ |0x3CF800 
Цена трэка: |0xFFFF00 @lex priceTune@|0x3CF800 $ Баланс: |0xFFFF00 @lex balanceJukebox@|0x3CF800 $
@lex statusJukebox@ }
{100255}{}{Одна песня}
{100256}{}{Все подряд}
{100257}{}{Выберите трэк: 
[ |0xFFFF00 @lex selectedTuneJukebox@ |0x3CF800 ]
Длительность: |0xFFFF00 @lex durationTune@|0x3CF800 .}
{100258}{}{Выберите песню!}
{100259}{}{     Нажмите [ |0xFFFF00 Включить |0x3CF800 ] !}
{100260}{}{     Музыка играет.}


#sex 100280 - 100310
{100281}{}{@lex descriptionSex@}
{100282}{}{Защита: @lex protectionSex@}
{100283}{}{Режим: @lex modeSex@}
{100284}{}{Позиция: @lex positionSex@}
{100285}{}{Предложить}
{100286}{}{@lex offeredSexDesc@
Режим: |0xFFFF00 @lex modeSexDesc@|0x3CF800 
Защита: |0xFFFF00 @lex protectionSexDesc@|0x3CF800 
Позиция: |0xFFFF00 @lex positionSexDesc@|0x3CF800 }
{100287}{}{Вы собираетесь сделать партнеру предложение заняться сексом:}
{100288}{}{Вы сделали предложение заняться сексом своему партнеру.
Ждите ответа.}
{100289}{}{Вам предлагают заняться сексом!
Решите как это делать:}
{100290}{}{Презерватив}
{100291}{}{Черный экран}
{100292}{}{Анимация}
{100293}{}{Спереди}
{100294}{}{Сзади}
{100295}{}{Орал}
{100296}{}{Миссионерская}

#repair 100310 - 100330
{100311}{}{Действие с предметом:
|0xFFFF00 @lex itemRepair@|0x3CF800 
@lex deteriorationRepair@@lex service@@lex serviceExt@
Сломан: |0xFFFF00 @lex brokenRepair@ |0x3CF800 раз.}
{100312}{}{Ремонт}
{100313}{}{Установить частоту}
{100314}{}{Разобрать}
{100315}{}{Установить радио}
{100316}{}{Покрасить}
{100317}{}{Убрать оружие}
{100318}{}{Выберите цвет краски}
{100319}{}{Износ: |0xFFFF00 @lex commonDeterioration@|0x3CF800 %}
{100320}{}{
@lex serviceState@}
{100321}{}{
@lex serviceExtState@}


#heal 100330 - 100420
{100331}{}{@lex pulse@@lex poisoning@@lex radiation@@lex bleeding@.@lex typeTraumas@}
{100332}{}{Пульс нормальный}
{100333}{}{Слабый пульс}
{100334}{}{, признаки отравления}
{100335}{}{, признаки радиационного заражения}
{100336}{}{, кровотечение}
{100337}{}{
Осколок или пуля в ране, требуется извлечение прежде чем делать что-либо другое.}
{100338}{}{
Тяжелая рана нуждается в закрытии.
}
{100339}{}{
Нет потребности в хирургическом вмешательстве.}
{100340}{}{Извлечение}
{100341}{}{Хирургия}
{100342}{}{Травмы}
{100343}{}{Приступить}	
{100344}{}{Мед осмотр}
{100345}{}{Выковырять}
{100346}{}{лезвия}
{100347}{}{обезбаливающих}
{100348}{}{зашить}
{100349}{}{прижечь}
{100350}{}{повязку}
{100351}{}{шину}
{100352}{}{фиксировать}
{100353}{}{дезинфекции}
{100354}{}{Убрать @lex subDressing@}
{100355}{}{Самодельную @lex subImprovised@}
{100356}{}{Нечем @lex subNothing@}
{100357}{}{Нет @lex subNo@}
{100358}{}{Без @lex subWithout@}
{100359}{}{@lex descMenu@}	
{100360}{}{Выберите инструмент:}
{100361}{}{Дезинфекция:}
{100362}{}{Анестезия:}
{100363}{}{Вы готовы провести @lex operationHeal@. 
Ожидаемый шанс успеха: |0xFFFF00 @lex chances@|0x3CF800 %}
{100364}{}{извлечение постороннего объекта из раны пациента}
{100365}{}{закрытие тяжелой раны}
{100366}{}{[UNKNOWN STATE #@lex stageHeal@]}
{100367}{}{Эта часть тела уже лечится.
}
{100368}{}{Этой части тела не требуется лечение.
}
{100370}{}{Выберите метод лечения:
Ожидаемое время восстановления конечности от @lex minMinutes@ до @lex maxMinutes@ минут.}
{100371}{}{Первая помощь:}
{100372}{}{глаз}
{100373}{}{правая рука}
{100374}{}{левая рука}
{100375}{}{правая нога}
{100376}{}{левая нога}


#waterworks 100420 - 100470
{100421}{}{}
{100422}{}{@lex typeWaterworks@}
{100423}{}{Сломать @lex breakWaterworks@}
{100424}{}{Починить @lex fixWaterworks@}
{100425}{}{Опустить @lex dropWaterworks@}
{100426}{}{Поднять @lex raiseWaterworks@}
{100427}{}{Проверить @lex checkWaterworks@}
{100428}{}{@lex switchWaterworks@ючить}
{100429}{}{Набрать воды}
{100430}{}{Пить}
{100435}{}{ведро}
{100436}{}{колодец}
{100437}{}{помпу}
{100438}{}{фильтр}
{100445}{}{Вода @lex chargeWell@@lex bucketWell@@lex chainWell@@lex posBucketWell@}
{100446}{}{видна у поверхности.}
{100447}{}{не видна.}
{100448}{}{сверкает в глубине.}
{100449}{}{

Цепь отсутствует.}
{100450}{}{

Все в порядке.}
{100451}{}{

Цепь в порядке.}
{100452}{}{

Ведро отсутствует.}
{100453}{}{

Нет цепи для ведра.}
{100454}{}{на глубине.}
{100455}{}{на середине.}
{100456}{}{болтается.}
{100457}{}{

Цепь}
{100458}{}{Колодец сломан.}
{100460}{}{Помпа № |0xFFFF00 @lex idWaterPump@ |0x3CF800 
Состояние: [ |0xFFFF00 @lex statusWaterPump@ |0x3CF800 ]
|0x3CF800 Вода|0xFF0000 @lex notFilterWaterPump@ |0x3CF800 фильтруется. |0x3CF800 @lex isBrokenWaterPump@ @lex filterDirtyWaterPump@ 
|0x3CF800 Накоплено: |0xFFFF00 @lex amountWaterPump@|0x3CF800 / |0xFFFF00 @lex maxAmountWaterPump@|0x3CF800  л. @lex generatorWaterPump@ 
}
{100464}{}{
Помпа сломана.}
{100465}{}{
Фильтр засорился.}
{100466}{}{
Подключено к генератору.
Состояние генератора: [ |0xFFFF00 @lex statusGeneratorWaterPump@|0x3CF800 ] }


#plants 100500 - 100550
{100501}{}{Полить}
{100502}{}{Удобрить}
{100503}{}{Собрать}
{100504}{}{Состояние растения:
Растение |0xFFFF00 @lex notWaterinedPlant@ полито|0x3CF800 .
Растение |0xFFFF00 @lex notFertilisedPlant@ удобрено|0x3CF800 .
Растение  @lex stagePlant@
Урожайность: @lex capacityPlant@
}
{100505}{}{Состояние грядки: 
Почва на грядке|0xFFFF00 @lex soil_status@|0x3CF800 .
Грядка|0xFFFF00 @lex notWatered@ полита|0x3CF800 .
Грядка|0xFFFF00 @lex notFertilised@ удобрена|0x3CF800 .
}
{100506}{}{семеносит.}
{100507}{}{созрело.}
{100508}{}{погибло!}
{100509}{}{растет...}
{100510}{}{|0xFFFF00 Это не посадить!}
{100511}{}{|0xFFFF00 Вы слишком далеко от грядки.}
{100512}{}{|0xFFFF00 Тут уже что-то есть.}
{100513}{}{|0xFFFF00 Нужна плодородная земля.}
{100514}{}{сажает гидропонику}
{100515}{}{|0xFFFF00 Нужно посадить на гидропонику.}
{100516}{}{сажает растение}
{100517}{}{|0xFFFF00 Почва должна быть полита и удобрена.}
{100518}{}{|0xFFFF00 Вам нужно посадить это на грядку.}
{100519}{}{сажает семечко}
{100520}{}{|0xFFFF00 Еще нечего собирать!}
{100521}{}{|0xFFFF00 Здесь уже достаточно удобрений.}
{100522}{}{удобряет}
{100523}{}{|0xFFFF00 Вы удобрили растение.}
{100524}{}{|0xFFFF00 Здесь уже достаточно воды.}
{100525}{}{|0xFFFF00 Возьмите контейнер с водой в руку.}
{100526}{}{|0xFFFF00 Вы полили растение.}
{100527}{}{поливает}
{100528}{}{|0xFFFF00 Вам нужно удобрение.}
{100529}{}{|0xFFFF00  удобренная}
{100530}{}{|0xFFFF00  мертвая}
{100531}{}{Удобрить Почву}
{100532}{}{|0xFFFF00 В почве не хватает минеральных удобрений.}
{100533}{}{|0xFFFF00 Вам нужны минеральные удобрения для почвы.}

#vending 100600 - 100650
{100601}{}{@lex descriptionID@
Товар: @lex merchandise@
Положите |0xFFFFFF @lex wares@ |0x3CF800 внутрь.
Balance: |0xFFFF00 @lex balance@|0x3CF800 $ @lex change@}
{100602}{}{[ Купить 1 шт. ]}
{100603}{}{[ Продать 1 шт. ]}
{100604}{}{Выбрать предмет}
{100605}{}{[ ПУСТО ]}
{100606}{}{Цена продажи}
{100607}{}{Цена покупки}
{100608}{}{Режим: @lex mode@}
{100609}{}{Продает}
{100610}{}{Покупает}
{100611}{}{Обменник}
{100612}{}{|0xFFFF00 @lex goods@|0x3CF800 , @lex lexCount@
@lex selling@ @lex buying@}
{100613}{}{|0xFF0000 ПУСТО |0x3CF800 }
{100614}{}{|0xFFFF00 @lex count@ |0x3CF800 шт.}
{100615}{}{|0xFF0000 ПРОДАНО |0x3CF800 }
{100616}{}{Продажа: |0xFFFF00 @lex sellingPrice@|0x3CF800 $}
{100617}{}{Скупка: |0xFFFF00 @lex byingPrice@|0x3CF800 $}
{100618}{}{|0xFF0000 СДАЧИ НЕТ |0x3CF800 }
{100619}{}{деньги}
{100620}{}{товары}
{100621}{}{деньги или вещи}
{100622}{}{Вендомат № |0xFFFF00 @lex ID@|0x3CF800 }
{100623}{}{@lex descriptionID@
Выбранный товар:
[ |0xFFFF00 @lex merch@ |0x3CF800 ]
Доступно: |0xFFFF00 @lex amount@ |0x3CF800 шт.
Выберите желаемый товар и нажмите |0xFFFF00 Подтвердить|0x3CF800 .}
{100624}{}{Сменить валюту}


#terminal 100700 - 100800
{100700}{}{|0x3CF800 
Состояние: [ |0xFFFF00 @lex statusTerminal@ |0x3CF800 ]}
{100701}{}{@lex descID@
@lex accessCard@@lex turrets@@lex fence@@lex noPassword@}
{100702}{}{ГМ МЕНЮ}
{100703}{}{Лазерная ограда: @lex state@}
{100704}{}{Настр. лазер. ограду}
{100705}{}{Контроль дверей}
{100706}{}{Подключение пушек}
{100707}{}{Настройка пушек}
{100708}{}{Открыть приемник}
{100709}{}{Выбрать карту}
{100710}{}{Настр. сил. полей}
{100711}{}{Подключить сил. поле}
{100712}{}{Управ. Автодоком}
{100713}{}{Подкл. Автодока}
{100714}{}{Сброс пароля}
{100715}{}{Блокировать терм.}
{100716}{}{Разблок. терм.}
{100717}{}{Закончить сеанс}
{100718}{}{|0xFFFF00 Терминал заблокирован, введите пароль!}
{100719}{}{Терминал № |0xFFFF00 @lex ID@|0x3CF800 }
{100720}{}{|0xFFFF00 Обесточен!}
{100721}{}{|0xFFFF00 Внимание, не установлен пароль! }
{100722}{}{|0x3CF800 Карта доступа: 
[ |0xFFFF00 @lex card@ |0x3CF800 ]
}
{100723}{}{|0x3CF800 Подключены пушки: [ |0xFFFF00 @lex amount@ |0x3CF800 ]
}
{100724}{}{|0x3CF800 Лазерная ограда:
[ |0xFFFF00 @lex fenceID@ |0x3CF800 ]

Состояние: |0xFFFF00 @lex fenceStatus@|0x3CF800 .
}
{100725}{}{Выключить карты доступа}
{100726}{}{@lex descID@
|0x3CF800 Доступ по карте: 
[ |0xFFFF00 @lex card@ |0x3CF800 ]
Выберите карту и нажмите |0xFFFF00 Подтвердить |0x3CF800 для окончания настройки.}
{100727}{}{@lex name@: @lex state@}
{100728}{}{@lex descID@
@lex emitters@
Подключено излучателей: [ |0xFFFF00 @lex num@ |0x3CF800 ]}
{100729}{}{Обнаружены излучатели поля.}
{100730}{}{Не обнаружены излучатели поля.}
{100731}{}{Тип поля: @lex fieldType@}
{100732}{}{Плотное}
{100733}{}{Прозрачное}
{100734}{}{|0xFFFF00 неопределимо}
{100735}{}{@lex descID@
@lex emitters@
Подключено излучателей: [ |0xFFFF00 @lex assigned@ |0x3CF800 ]
Включены излучатели: [ |0xFFFF00 @lex enabled@ |0x3CF800 ]
Тип поля: [ |0xFFFF00 @lex type@ |0x3CF800 ]}
{100736}{}{@lex name@ @lex state@}
{100737}{}{@lex descID@
@lex doors@
Включено дверей: [ |0xFFFF00 @lex enabled@ |0x3CF800 ]}
{100738}{}{Не обнаружены автоматические двери.}
{100739}{}{Обнаружено дверей: [ |0xFFFF00 @lex amount@ |0x3CF800 ]}
{100740}{}{@lex descID@
Подключено дверей: [ |0xFFFF00 @lex assigned@ |0x3CF800 ]
|0xFFFF00 Внимание!|0x3CF800  Глобальные настройки перекрывают локальные!

Выберите команду:}
{100741}{}{Блокирована}
{100742}{}{Разблокирована}
{100743}{}{@lex descID@
Дверь: [ |0xFFFF00 @lex name@ |0x3CF800 ]
Контроль обеспечен!
Статус: [ |0xFFFF00 @lex status@ |0x3CF800 ]
Положение: [ |0xFFFF00 @lex state@ |0x3CF800 ]
Выберите команду:}
{100744}{}{@lex name@ : @lex state@}
{100745}{}{Подключаемые пушки: 
@lex turretsList@}
{100746}{}{№ @lex id@ - @lex state@
}
{100747}{}{авторизована}
{100748}{}{неавторизована}
{100749}{}{занята}
{100750}{}{Подключены пушки: 
@lex turretsList@}
{100751}{}{статус:}
{100752}{}{доступ:}
{100753}{}{ГМ меню терминала:}
{100754}{}{Электричество}
{100755}{}{контр. лаз. ограды}
{100756}{}{контр. сил. полей}
{100757}{}{контр. дверей}
{100758}{}{Назначить двери}
{100759}{}{контр. пушек}
{100760}{}{Доступ по карте}
{100761}{}{контр. автодока}
{100762}{}{Пароль}
{100763}{}{@lex info@}
{100764}{}{Выключить ограду}
{100765}{}{Излучатели обнаружены:
@lex emitters@
@lex group@
}
{100766}{}{|0xFFFF00 Не обнаружено излучателей!}
{100767}{}{|0x3CF800 Выбранная группа: [ |0xFFFF00 @lex IDgroup@ |0x3CF800 ]}
{100768}{}{Музыкальный Терминал}
{100769}{}{Установить Частоту.}
{100770}{}{Вы установили новую частоту вещания: |0xFFFF00 @lex digits@}
{100771}{}{Частота музыкального вещания настроена на: }
{100772}{}{Управление Музыкой}
{100773}{}{@lex descID@
@lex frequency@}
{100774}{}{Мастер-терминал}
{100775}{}{Назначить терминалы}
{100776}{}{@lex descID@
@lex terminals@}
{100777}{}{Не обнаружены терминалы для контроля.}
{100778}{}{Обнаружено терминалов: [ |0xFFFF00 @lex amount@ |0x3CF800 ]}
{100779}{}{Контроль мейнфрейма}
{100780}{}{Подключение к мейнфрейму не удалось.}
{100781}{}{Взламываемость}
{100782}{}{Хакнуть пароль}
{100783}{}{Это не взломать.}
{100784}{}{Выбрать разряд}
{100785}{}{Обновить выборку}
{100786}{}{Подсветить @lex n@}
{100787}{}{Взломать @lex n@ разряд}
{100788}{}{@lex gminfo@
@lex state@}
{100789}{}{|0xFFFFFF Пароль: |0xFFFF00 @lex password@ |0xFFFFFF @lex percentage@|0x00FF00 % подсказок.}
{100790}{}{|0x888888      Выберите разряд..}
{100791}{}{|0x00FF00 Хакаем |0xFFFF00 @lex digit@ |0x00FF00 разряд@lex hints@:
@lex datamess@}
{100792}{}{, цифра |0xFFFF00 @lex hintedN@|0x00FF00 @lex HintingCountText@}
{100793}{}{[|0xFFFFFF @lex hintedCount@|0x00FF00 ]}
{100794}{}{|0xFFFF00 Для этого вам понадобится держать в руках пип-бой.}
{100795}{}{|0xFFFF00 Консоль:
 |0xFFFFFF Проверка системы... ОК.
 Сканирование БД... ОК.
 Выберите секцию данных.}
{100796}{}{Копировать}
{100797}{}{Прочитать}
{100798}{}{|0xFFFF00 Копирование данных... Завершено.}
{100799}{}{|0xFFFF00 Вам нужно иметь голодиск в руках чтобы скопировать данные!}
{100800}{}{База Данных}

#autodoc 100800 - 100900
{100801}{}{Автодок № |0xFFFF00 @lex Id@ |0x3CF800 @lex state@.}
{100802}{}{подключен}
{100803}{}{выбран}
{100804}{}{Пациент @lex state@}
{100805}{}{свободен}
{100806}{}{удерживается}
{100807}{}{Вылечить}
{100808}{}{Зашить раны}
{100809}{}{Извлечь пулю}
{100810}{}{Перелить кровь}
{100811}{}{Реабилитация}
{100812}{}{Меню травм}
{100813}{}{Реанимировать}
{100814}{}{Модифицировать}
{100815}{}{Эвтаназия}
{100816}{}{|0x3CF800 Автодок № |0xFFFF00 @lex ID@ |0x3CF800 Биогель: |0xFFFF00 @lex biogel@ |0x3CF800 %
@lex warning@@lex autodocScan@}
{100817}{}{|0xFFFF00 Внимание! Отсутствует биогель! |0x3CF800 
}
{100818}{}{|0xFF0000 Ошибка терминала! |0x3CF800 }
{100819}{}{|0xFF0000 Ошибка автодока! |0x3CF800 }
{100820}{}{|0xFF0000 Вы вне карты! |0x3CF800 }
{100821}{}{|0xFFFF00 Внимание, идет процедура! |0x3CF800 }
{100822}{}{|0xFFFF00 Ошибка биосканера! |0x3CF800 }
{100823}{}{|0x38F800 До окончания осталось: |0xFFFF00 @lex minute@|0x3CF800 :|0xFFFF00 @lex second@ |0x3CF800 }
{100824}{}{|0xFFFF00 Ошибка! Посторонний объект в автодоке! |0x3CF800 }
{100825}{}{|0xFFFF00 Ошибка! Множество сигнатур в автодоке! |0x3CF800 }
{100826}{}{|0xFFFF00 Ошибка! В автодоке не человек! |0x3CF800 }
{100827}{}{|0xFFFF00 Ошибка! Пациент не голый! |0x3CF800 }
{100828}{}{|0x3CF800 Пациент: |0xFFFF00 @lex gender@|0x3CF800 }
{100829}{}{|0xFF0000 Пациент мертв! |0x3CF800 }
{100830}{}{|0xFFFF00 Пациент в критическом состоянии! |0x3CF800 }
{100831}{}{|0x3CF800 ОЗ: |0xFFFF00 @lex HP@ |0x3CF800 / |0xFFFF00 @lex maxHP@ |0x3CF800 }
{100832}{}{|0x3CF800 Отклонение: @lex color@@lex BaseHP@ |0x3CF800 ОЗ.}
{100833}{}{|0xFFFF00 Обнаружена зависимость! |0x3CF800 }
{100834}{}{|0xFFFF00 Джет в крови! |0x3CF800 }
{100835}{}{|0x3CF800 Уровень алкоголя в крови: |0xFFFF00 @lex drunk@ |0x3CF800 %}
{100836}{}{|0x3CF800 Отравление: |0xFFFF00 @lex poison@ |0x3CF800 %}
{100837}{}{|0x3CF800 Радиация: |0xFFFF00 @lex radiation@ |0x3CF800 рад.}
{100838}{}{|0xFFFF00 Травмы: |0x3CF800 @lex injures@}
{100839}{}{|0xFFFF00 Посторонний объект в ране. |0x3CF800 }
{100840}{}{|0xFFFF00 Открытая рана. |0x3CF800 }
{100841}{}{|0xFFFF00 Внимание, пациент не обнаружен! |0x3CF800 }
{100842}{}{@lex strGender@ @lex stateHP@@lex baseHPState@@lex addictedState@@lex jettedState@@lex stateDrunk@@lex statePoison@@lex stateRadiation@@lex stateInjures@@lex stateBullet@@lex stateHeavy@}
{100843}{}{Сила @lex adjustment@}
{100844}{}{Восприятие @lex adjustment@}
{100845}{}{Выносливость @lex adjustment@}
{100846}{}{Харизма @lex adjustment@}
{100847}{}{Ловкость @lex adjustment@}
{100848}{}{Лабиопластика}
{100849}{}{Смена пола}


#gm 101000 - 101500
{101001}{}{Главное ГМ меню}
{101002}{}{Телепорты}
{101003}{}{Склады}
{101004}{}{Спаунеры карты}
{101005}{}{ГМ зрение}
{101006}{}{Режимы ГМ зрения}
{101007}{}{Симулятор дождя}
{101008}{}{Введите время в минутах}
{101009}{}{Мировой дождь}
{101010}{}{Введите силу от 0 до 255}
{101011}{}{Дождь на карте}
{101012}{}{Музыка}
{101013}{}{Время}
{101014}{}{Фракции}
{101015}{}{Обновить мобов}
{101016}{}{Установить все в:}
{101017}{}{Установить множитель:}
{101018}{}{Животные}
{101019}{}{Монстры}	
{101020}{}{Спаун-меню}
{101021}{}{[@lex spawners@x@lex mobSpawns@] @lex nameMob@}
{101022}{}{Количество на спаунер:}
{101023}{}{Количество на спаунер:}
{101024}{}{Количество на спаунер: 
[ Спаун X Мобов ] Тип моба}
{101025}{}{Логины}
{101026}{}{Хитпоинты Игроков}
{101027}{}{ID над головой}
{101028}{}{ID в чате}
{101029}{}{ID предметов в чате}	
{101030}{}{Координаты курсора}
{101031}{}{Маркеры радиации}
{101032}{}{Спрайты курсора}
{101033}{}{Слышать рацию}
{101034}{}{Слышать шепот}
{101035}{}{Информация ~desc}
{101036}{}{Маркеры газа}
{101037}{}{Маркеры света}
{101038}{}{@lex gmInfo@: @lex status@}
{101039}{}{Настройки ГМ зрения:}
{101040}{}{Выключить музыку}	
{101041}{}{Экшон}
{101042}{}{Напряжение}
{101043}{}{Запугивание}
{101044}{}{Спецэффекты}
{101045}{}{Музло}
{101046}{}{Фолач}
{101047}{}{NNM}
{101048}{}{Прочее}
{101049}{}{Выбор музыки для карты}	
{101050}{}{ОСТОРОЖНО, ТРЭКИ НАКЛАДЫВАЮТСЯ ДРУГ НА ДРУГА!!!}
{101051}{}{Местный год}
{101052}{}{Обнулить местный год}
{101053}{}{Глобальный год}
{101054}{}{Формат: ГГГГ}
{101055}{}{Обнулить глобальный год}
{101056}{}{Глобальный реальный день: @lex state@}
{101057}{}{Время: @lex time@
Серверное время: |0xFFFF00 @lex timeMul@x @lex yearNow@|0x3CF800 -|0xFFFF00 @lex month@|0x3CF800 -|0xFFFF00 @lex day@|0x3CF800 
Текущий глоб. год: |0xFFFF00 @lex yearGlobal@|0x3CF800 
Сдвиг по годам: |0xFFFF00 @lex yearShift@|0x3CF800 
Текущий лок. год: |0xFFFF00 @lex yearLocal@|0x3CF800 
Локальный сдвиг: |0xFFFF00 @lex yearMod@|0x3CF800 }
{101058}{}{Действие с гексом: Х @lex X@ Y @lex Y@}
{101059}{}{Спаун НПЦ}
{101060}{}{Спаун предмета}
{101061}{}{ПИД предмета}
{101062}{}{Собрать предметы}
{101063}{}{Удалить предметы}
{101064}{}{Добавить радиацию}
{101065}{}{Добавить газ}
{101066}{}{ТП сюда}
{101067}{}{Контроль}
{101068}{}{Животное}
{101069}{}{Разумное}
{101070}{}{AI: @lex type@}
{101071}{}{Фракция: @lex name@}
{101072}{}{ФРАКЦИЯ:}
{101073}{}{Агрессия: @lex state@}
{101074}{}{Пассивен}
{101075}{}{Агрессивен}
{101076}{}{№ команды: @lex id@}
{101077}{}{НОМЕР КОМАНДЫ:}
{101078}{}{PID: @lex value@}
{101079}{}{PID НПЦ:}
{101080}{}{Бонус ОЗ: @lex value@}
{101081}{}{Бонус ОЗ:}
{101082}{}{Бонус урону: @lex value@}
{101083}{}{Бонус урону:}
{101084}{}{Бонус навыку: @lex value@}
{101085}{}{Бонус навыку:}
{101086}{}{Выбор НПЦ}
{101087}{}{@lex name@}
{101088}{}{Меню спауна мобов. Бонусы суммируются с параметрами прототипа существа. Выбор моба назначит PID}
{101089}{}{Крыса}
{101090}{}{Мантис}
{101091}{}{Муравей}
{101092}{}{Муравьиный лев}
{101093}{}{Свинокрыс}
{101094}{}{Кротогризли}
{101095}{}{Кротогризли-Мутант}
{101096}{}{Серебряный геккон}
{101097}{}{Золотой геккон}
{101098}{}{Пещерный геккон}
{101099}{}{Собака}
{101100}{}{Волк}
{101101}{}{Рад-Скорпион}
{101102}{}{Б. Рад-Скорпион}
{101103}{}{Яо}
{101104}{}{Пещерный рад-скорпион}
{101105}{}{Брамин}
{101106}{}{Вы заспаунили: @lex name@}
{101107}{}{Выберите моба, он будет заспаунен мгновенно.}
{101108}{}{Вы выставили: |0xFFFF00 @lex mob@ |0x3CF800 спаун в |0xFFFF00 @lex val@|0x3CF800 .}
{101109}{}{Растение}
{101110}{}{Чужой}
{101111}{}{Коготь смерти}
{101112}{}{Крокодил}
{101113}{}{Тёмный крокодил}
{101114}{}{Огнегекко}
{101115}{}{Beast}
{101116}{}{Кентавр}
{101117}{}{Летун}
{101118}{}{Болотник}
{101119}{}{Оса}
{101120}{}{Таракан}
{101121}{}{Дикий гуль}
{101122}{}{Многоножка}
{101123}{}{Козел}
{101124}{}{Паук}
{101125}{}{Койот}
{101126}{}{Режим СТАРТ}
{101127}{}{Режим ПРИКЛЮЧЕНИЯ}
{101128}{}{Режим ВЫЖИВАНИЕ}
{101129}{}{Режим ТЕСТ}
{101130}{}{ошибка режима}
{101131}{}{Параметры}
{101132}{}{Модерация}
{101133}{}{Инвентарь}
{101134}{}{Бонусы}
{101135}{}{Эффекты}
{101136}{}{Поднять/нокаутировать}
{101137}{}{Ролл на скил}
{101138}{}{Выдать предмет}
{101139}{}{ПСИ-режимы}
{101140}{}{Отагрить NPC!}
{101141}{}{0 Режим СТАРТ}
{101142}{}{1 Режим ПРИКЛЮЧЕНИЯ}
{101143}{}{2 Режим ВЫЖИВАНИЕ}
{101144}{}{3 Режим ТЕСТЕРА}
{101145}{}{SPECIAL}
{101146}{}{SKILLS}
{101147}{}{Травмы}
{101148}{}{Моды}
{101149}{}{Трейты}
{101150}{}{Скин/Тип}
{101151}{}{Фракция: @lex name@}
{101152}{}{Дополнительные}
{101153}{}{Лексемы}
{101154}{}{Черный экран, 30 секунд}
{101155}{}{Белый экран, 30 секунд}
{101156}{}{Красный экран, 30 секунд}
{101157}{}{Черный экран, 25 с}
{101158}{}{Белый экран, 25 с}
{101159}{}{Красный экран, 25 с}
{101160}{}{Обнулить таймауты}
{101161}{}{Цель @lex state@}
{101162}{}{Не сможет встать}
{101163}{}{Скоро встанет}
{101164}{}{Введите PID:}
{101165}{}{Текущий: - @lex value@}
{101166}{}{0 - Нет}
{101167}{}{1 - Хозяин животных}
{101168}{}{2 - Безликий}
{101169}{}{3 - Голос}
{101170}{}{4 - Мимикрия}
{101171}{}{От игрока все отстали.}
{101172}{}{% ХП мобов}
{101173}{}{Список мобов}
{101174}{}{Установлен хомгекс и 'домашний' режим.}
{101175}{}{@lex name@ находится в стартовом режиме. Дайте игроку сначала активироваться у гида!}
{101176}{}{|0xFFFF00 NAME |0x00FF00 очищена.}
{101177}{}{Группа #ID}
{101178}{}{Заспавнить НПЦ}
{101179}{}{Выбор гуманоидного НПЦ}
{101180}{}{Время на карте}
{101181}{}{Статичное время: @lex mode@}
{101182}{}{Сбросить время}
{101183}{}{|0xFFFF00 @lex global@ |0xAAAAAA @lex map@ |0x00FF00 @lex delta@}
{101184}{}{статика}
{101185}{}{Количество: @lex amount@}
{101186}{}{Оповещения}
{101187}{}{Игроки}
{101189}{}{AoE Ослепление}
{101190}{}{Кислотный дождь}
{101191}{}{Добавить руду}
{101192}{}{Маркеры руды}
{101193}{}{Добавить мусор}
{101194}{}{Маркеры мусора}
{101195}{}{Отагрить мобов}
{101196}{}{Спавнер мобов}
{101197}{}{ФОРМАЦИЯ}

# GM menu NPC groups
# Mobs
{101200}{}{Крысы}
{101201}{}{Мантисы}
{101202}{}{Муравьи}
{101203}{}{Свинокрысы}
{101204}{}{Геко}
{101205}{}{Собаки и Волки}
{101206}{}{Скорпионы}
{101207}{}{Брамины и Лаваш}
{101208}{}{Растения}
{101209}{}{Яо-Гаи}
{101210}{}{Пришельцы}
{101211}{}{Когти Смерти}
{101212}{}{Тенехваты}
{101213}{}{Кентавры}
{101214}{}{Летатели}
{101215}{}{Болотники}
{101216}{}{Прочие Насекомые}

# Humanoids
{101217}{}{Дикие Гули}
{101218}{}{Супер Мутанты}
{101219}{}{Аримия НКР}
{101220}{}{Рейнджеры}
{101221}{}{Братство Стали}
{101222}{}{Анклав}
{101223}{}{Город Убежище}
{101224}{}{Ренегаты}
{101225}{}{Жители Убежища}
{101226}{}{Горожане}
{101227}{}{Охотники за головами}
{101228}{}{Дикари}
{101229}{}{Канибалы}
{101230}{}{Бандиты}
{101231}{}{Наемники}
{101232}{}{Работорговцы}
{101233}{}{Рабы}
{101234}{}{Бездомные}

#handcuffs 101500 - 101550
{101501}{}{Пульт активен.

Ожидаем команды...}
{101502}{}{Управление ошейником}
{101503}{}{Все ошейники}
{101504}{}{Установить частоту}
{101505}{}{Ошейник @lex idCollar@}
{101506}{}{Наказать}
{101507}{}{Ранить}
{101508}{}{Пытать}
{101509}{}{Убить}
{101510}{}{Отпустить}
{101511}{}{: Отключен}
{101512}{}{: Активен}
{101513}{}{Пульт |0xFFFF00 @lex idRemote@ |0x3CF800    
 
@lex stateCollar@ ошейники: [|0xFFFF00 @lex num@|0x3CF800 ]}
{101514}{}{Активен}
{101515}{}{Доступен}
{101516}{}{Ошейник |0xFFFF00 @lex idCollar@ |0x3CF800 }
{101517}{}{Введите частоту}
{101518}{}{Вы установили частоту на: |0xFFFF00 @lex digits@|0x3CF800 .}
{101519}{}{|0xFFFF00 Ваш навык недостаточен для смены пароля!}

{101550}{}{Высвечивается частота: @lex frequency@|0x3CF800 .}

#map_start 101600 - 101650
{101601}{}{		  Добро пожаловать в игру!}
{101602}{}{Информация (Вики)}
{101603}{}{Начать игру}
{101604}{}{Сменить скин}
{101605}{}{Сменить пол}
{101606}{}{Арена 1 @lex playersCount@}
{101607}{}{Арена 2 @lex playersCount@}
{101608}{}{Игроков: [ @lex count@ ]}
{101609}{}{Альфа-геймплей Арены.

Выберите арену для телепортации. Это действие необратимо!

По прибытии, вы получите максимальный уровень.}
 
{101610}{}{Стартовый терминал.

Здесь вы можете настроить скин и пол вашего персонажа.

Выберите «Начать игру», чтобы продолжить!}

{101611}{}{Терминал телепортации.

Выберите начальную локацию!}
{101612}{}{Сменить рост}
{101613}{}{Смена роста:
Текущий рост: |0xFFFF00 @lex crHeight@|0x3CF800  см.}

#recorder 101651 - 101669
{101651}{}{Грамофон.
@lex batteryCharge@ |0x3CF800  
Громкость: @lex volume@}
{101652}{}{Вставить батарейку}
{101653}{}{Открыть магнитолу}
{101654}{}{Заряд батареи: |0xFFFF00 @lex charge@ }
{101655}{}{|0xFFFF00 Батарея полна!}
{101656}{}{|0xFFFF00 Вы можете поместить сюда только пленку!}

#geiger 101670 - 101700 
#99510 & 99511 - on/off
{101670}{}{Счетчик Гейгера.
Статус:  [ |0xFFFF00 @lex geigerState@ |0x3CF800 ]
Ур-нь заряда: [ |0xFFFF00 @lex geigerCurCharge@ |0x3CF800 |0xFFFF00 @lex geigerMaxCharge@ |0x3CF800 ] 
Облучение: [ |0xFFFF00 @lex crRadLvl@ |0x3CF800 ]
Облучение местн.: [ |0xFFFF00 @lex locRadLvl@ |0x3CF800 ]
}
{101671}{}{Много странных букв и цифр на гладкой стекляшке этой железяки}
{101672}{}{Странная кнопка}	# stupid on/off
{101673}{}{Измерить ур-нь рад.}
{101674}{}{Помахать железякой}
{101675}{}{Сканировать себя}
{101676}{}{Потереть железяку}
{101677}{}{Зарядить устройство}
{101678}{}{Вставить что-нибудь}
{101679}{}{Супер-режим}
{101680}{}{Красивая кнопка}
{101681}{}{Обычный режим}
{101682}{}{Большая кнопка}

# geiger charge menu 101684 - 101691
{101684}{}{Счетчик Гейгера.
Статус:  [ |0xFFFF00 @lex geigerState@ |0x3CF800 ]
Ур-нь заряда: |0xFFFF00 @lex geigerCurCharge@ |0x3CF800 |0xFFFF00 @lex geigerMaxCharge@ |0x3CF800  
Выберите способ заряда
}
{101685}{}{Много странных букв и цифр на гладкой стекляшке этой железяки. Снизу появилось еще больше букв}
{101686}{}{Куст. энергоячейка}
{101687}{}{Желтая железяка}
{101688}{}{Энергоячейка}
{101689}{}{Красная железяка}
{101690}{}{Ядер. микрореактор}
{101691}{}{Больш. желт. железяка}
{101695}{}{Вам не хватает ума}
{101696}{}{Вам не хватает знаний, чтобы это сделать}
{101697}{}{Кажется, вы повредили эту странную штуку своими бестолковыми действиями}
{101698}{}{Благодаря вашим знаниям, вы увеличили время работы устройства}
{101699}{}{Вы увеличили мощность и скорость работы устройства. Заряд батареи будет расходоваться быстрее}

{101700}{}{База данных № |0xFFFF00 @lex Id@ |0x3CF800 @lex state@.}
{101701}{}{Подкл. Базы данных}

# Skill rolls
{102003}{}{МАЛЕНЬКИЕ ПУШКИ}
{102013}{}{СРЕДНИЕ ПУШКИ}
{102023}{}{БОЛЬШИЕ ПУШКИ}
{102033}{}{БЕЗОРУЖНЫЙ БОЙ}
{102043}{}{ХОЛОДНОЕ ОРУЖИЕ}
{102053}{}{МЕТАТЕЛЬНОЕ}
{102063}{}{САНИТАР}
{102073}{}{ДОКТОР}
{102083}{}{СКРЫТНОСТЬ}
{102093}{}{ВЗЛОМ ЗАМКОВ}
{102103}{}{ВОРОВСТВО}
{102113}{}{ЛОВУШКИ}
{102123}{}{НАУКА}
{102133}{}{РЕМОНТ}
{102143}{}{-}
{102153}{}{ТОРГОВЛЯ}
{102163}{}{-}
{102173}{}{ВЫЖИВАНИЕ}
{102183}{}{ШАХТЕРСТВО}
{102193}{}{ЛЕСОЗАГОТОВКА}
{102203}{}{СБОР МУСОРА}
{102213}{}{ОХОТА}
{102223}{}{РЫБНАЯ ЛОВЛЯ}
{102233}{}{ФЕРМЕРСТВО}
{102243}{}{КУЛИНАРИЯ}
{102253}{}{ТРАВНИЧЕСТВО}

# Headbag
{102254}{}{надевает мешок себе на голову}
{102255}{}{надевает мешок на голову}
{102256}{}{|0xFFFF00 Вы надели мешок себе на голову}
{102257}{}{|0xFFFF00 Вам надели мешок на голову}
{102258}{}{|0xFFFF00 С вашей головы сняли мешок}
{102259}{}{cнимает мешок с головы}
{102260}{}{cнимает мешок}



