#
# Created 21.04.08, Cvet
#
# В данном файле сценаристы могут создавать свои строки.
#


{10}{}{Test0}
{11}{}{Test1}
{12}{}{Test2}
{13}{}{Test3}


#
# Увеличение скила
#
{15}{}{Навык @lex skill@ увеличен на @lex value@ очков}

#
# Nuka-Cola machine
#
{100}{}{Вы видите автомат по продаже Ньюка-Колы. Как это ни удивительно, но, похоже он все еще работает.}
{101}{}{[тук тук тыдыщ... шшшшшшш]@@[тук тук чача... шии]@@[динь-динь-дзинь... вжииик]@@[чпок чпок чпок]}
{102}{}{Вы получили бутылку Нюка-Колы.}
{103}{}{Ох, черт!@@Проклятье!@@Ооооо!!!}
{104}{}{Вы увернулись от вылетевшей бутылки Нюка-Колы.}
{105}{}{@lex name @ уверено уклонился от бутылки Нюка-Колы.}
{106}{}{Похоже, автомат полностью опустошен.@@Похоже, в автомате кончился товар.}

#
# Sandbag. Barricades stuff.
#
{200}{}{Мешок порвался у вас в руках - его нельзя класть в этом месте.}
{201}{}{В этом месте больше невозможно уложить ни одного мешка. }
{202}{}{Вы развязали мешок и высыпали песок из него на землю.}

#
# Extended craft.
#
{300}{}{Для производства требуется находиться рядом со cпециальным станком или верстаком.}
{301}{}{Станок или верстак в неработоспособном состоянии. Производство невозможно. Попробуйте позже.}
{302}{}{Станок или верстак в неработоспособном состоянии. Произведен максимум возможных предметов. Производство невозможно.}

#
# Generic messages
#

{500}{}{Бросил кубик на @lex result@} # Dice
{510}{}{Да} # Magic ball
{511}{}{Нет} # Magic ball
{520}{}{Пудрит носик} # Cosmetic
{530}{}{. Курит .oO} # Cigarettes

#
# Manufacture, Alcohol
#

# Использовать
{1500}{}{Аппарат не работает.}
{1501}{}{Нужны дрова.}
{1502}{}{Вы наблюдаете за горением дров в печи.}
{1503}{}{В баке свежесваренное пиво!}
{1504}{}{Бак с самогоном наполнен до краев!}
# Использовать пустые бутылки
{1505}{}{Вы разлили пиво по бутылкам.}
{1506}{}{Вы разлили самогон по бутылкам.}
{1507}{}{У вас недостаточно тары.}
# Использовать дрова
{1508}{}{Аппарат сломан.}
{1509}{}{Мало дров, этого может не хватить.}
{1510}{}{Вы не знаете, сколько и каких ингредиентов нужно использовать.}
{1511}{}{Вы подготовили и залили сырье, разожгли печь. Процесс пошел.}
{1512}{}{Вы разожгли печь и добавили сырья. Самогон начинает наполнять бак.}
{1513}{}{В печке и без того дров достаточно.}
{1514}{}{Вначале нужно слить готовое пиво.}
{1515}{}{Вначале нужно слить готовый самогон.}
# Сломать
{1516}{}{Вы сломали установку для пивоварения.}
{1517}{}{Вы сломали самогонный аппарат.}
{1518}{}{Котел не выдержал и взорвался!}
{1519}{}{Ваши глаза обдало кипятком.}
# Ремонт
{1520}{}{Тут нужны кое-какие детали.}
{1521}{}{Для ремонта необходимы некоторые инструменты.}
{1522}{}{Вы успешно починили установку.}
{1523}{}{Ремонт не удался. Вы сломали пару деталей.}
# Наука
{1524}{}{Аппарат можно подрегулировать, но нужен гаечный ключ или нечто подобное.}
{1525}{}{Вы сломали гаечный ключ, как и сам аппарат.}
{1526}{}{В процессе регулировки вы разобрали пол аппарата. Теперь нужно как-то собрать все обратно.}
{1527}{}{Вы осторожно подрегулировали что-то, но результата это не принесло.}
{1528}{}{Вы отрегулировали установку для пивоварения, теперь дров нужно намного меньше.}
{1529}{}{Вы отрегулировали самогонный аппарат, теперь дров нужно намного меньше.}
{1530}{}{Вы не смогли настроить аппарат. Ладно хоть ничего не сломали на этот раз.}
# Scenery
{1560}{}{Здесь лежат какие-то злаки. Они очищены и высушены.}
{1561}{}{В емкостях происходит брожение сырья для изготовления спиртного.}

#
# Casino
#

{2000}{}{*Ring-a-ling*}
{2000}{}{*Zzzzzzz*}
{2000}{}{*Bing*}
{2000}{}{*Dingity-ding*}
{2000}{}{*Ding*}
{2000}{}{*Kaa-ching*}
{2001}{}{Автомат пуст.}

#
# Car, car.fos
#

{2100}{}{Номер: @lex number@. Топливо: @lex fuel@/@lex fuel_tank@. Износ: @lex wear@%.}

#
# Getting firewood from tree (use axe on tree)
#

{2200}{}{Это подходящее дерево. Вы могли бы нарубить дров… если б руки были целы.}
{2201}{}{Вам нужно немного передохнуть.}
{2202}{}{Вместо дерева, вы попали топором по своей руке!}
{2203}{}{Вы добыли немного дров.}
{2204}{}{Вы добыли дров, но всех их вам не утащить.}
{2205}{}{Вы добыли дров, но неспособны унести хотя бы некоторые из них.}





{6100}{}{Парень, мы здесь не особо любим, когда гости ходят с оружием наперевес.}
{6101}{}{Спрятал бы ты пушку, приятель...}
{6102}{}{Держал бы ты оружие в кобуре, дружище.}
{6103}{}{Эй, убери пушку! Здесь мирный город, мать твою.}
{6104}{}{Не наставляй на меня ствол!}
{6105}{}{Хватит размахивать тут пушкой, как у себя дома.}
{6106}{}{Надеюсь, это штука не выстрелит. Это в твоих же интересах.}
{6107}{}{Ты ведь не собираешься палить направо и налево, как сраный ковбой?}
{6108}{}{Твою мать, спрячь оружие!}
{6109}{}{Эй, эта штука ведь может выстрелить!}
{6110}{}{Уберите оружие, вам ведь не нужны неприятности?}

{6111}{}{Эй, подруга! Этой штукой можно убить! Спрячь.}
{6112}{}{Баба с оружием - это не к добру. А ну спрячь!}
{6113}{}{Эй, подруга, спрячь-ка ствол.}
{6114}{}{Крошка, убери ствол, пока он не выстрелил, договорились?}
{6115}{}{Уберите, пожалуйста, оружие. Вам ведь не нужны неприятности?}
{6116}{}{Так, оружие убрала!}

{6120}{}{Ну все, чертов вор! Ты допрыгался!}
{6121}{}{Тебе предупреждали, сукин сын!}
{6122}{}{Сейчас мы тебе покажем, что в этом городе делают с ворами!}
{6123}{}{Ну что, воришка? Тебе конец!}
{6124}{}{Чертов вор! Сегодня ты умрешь!}
{6125}{}{Все, ты меня достал, чертов вор!}

{6126}{}{Эй! Что ты там делаешь, засранец?}
{6127}{}{Эй! еще раз увижу за воровством - дам по шапке!}
{6128}{}{А ну не шарься по карманам, говнюк!}
{6129}{}{А ну убери руки из его карманов!}
{6130}{}{Эй, ты! Воровство здесь наказуемо, понял?}

{6131}{}{Ну все, мы сыты тобой по горло! Я лично поговорю с мэром о лишении тебя гражданства.}
{6132}{}{Все, ты надоел! Убирайся из города! Забудь про гражданство!}
{6133}{}{Ну все, засунь свой паспорт себе в задницу! Ты больше не гражданин!}
{6134}{}{Как же ты достал! Убирайся из города, тебе здесь не рады!}
{6135}{}{В Модоке нет место ворам! Забудь про свое гражданство!}

{6136}{}{Гражданин в опасности! Огонь!}
{6137}{}{Сейчас мы тебя покажем, что у нас делают за стрельбу по гражданам!}
{6138}{}{Атакован гражданин!}
{6139}{}{Думал, что любой козел может стрелять по гражданам? Ты ошибался!}
{6140}{}{Стрелять в нашем городе? По гражданам? Ты труп!}

{6141}{}{Давно пора было разобраться с этим вором!}
{6142}{}{Это ворье недостойно звания гражданина! Пусть сами разбираются!}
{6143}{}{Охрана, не стрелять! Это чертов вор, Пусть получает по заслугам!}
{6144}{}{Давно пора! Этот вор уже всех достал!}
{6145}{}{Ахаха, допрыгался, ворье?}

{6146}{}{Пусть сами разбираются! Этот козел уже давно все достал.}
{6147}{}{Ну, вот ты и до накликал справедливый гнев граждан, мудак!}
{6148}{}{Ну что, допрыгался? Нечего было доставать людей!}
{6149}{}{Ну что, чертов маньяк? Встретил того, кто тебя не боится?}
{6150}{}{Отставить огонь! Этот засранец уже давно всех достал!}

{6151}{}{Успокойтесь, граждане! Для решения конфликтов есть другие пути!}
{6152}{}{Граждане, прекратите перестрелку!}
{6153}{}{Граждане, прекратите немедленно!}
{6154}{}{Граждане, уймитесь!}
{6155}{}{Граждане, прекратить огонь немедленно!}

{6156}{}{Не стреляйте! Пусть разбираются, я сыт ими обоими по горло!}
{6157}{}{Кто бы из них не здох - они делают городу одолжение.}
{6158}{}{Пусть сами разбираются, они оба уже достали.}
{6159}{}{Пусть воюют, они оба уже достали.}
{6160}{}{Черт, наконец-то одним подонком в городе будет меньше. В любом случае.}

{6161}{}{Правильно, нечего ходить в чужом городе с оружием наперевес.}
{6162}{}{Не стреляйте! Если гражданин напал на вооруженного до зубов чужака - у него были на то причины.}
{6163}{}{Тебе предупредали - мы не любим гостей с оружием наготове!}
{6164}{}{Будешь знать, как наставлять оружие на граждан!}
{6165}{}{Не стоило тебе ходить в оружием наготове!}

{6166}{}{Гражданин, прератить стрельбу по безоружным!}
{6167}{}{Он не вооружен, прекрати немедленно!}
{6168}{}{Что за дела? Уймитесь, гражданин!}
{6169}{}{Не трогай безоружных!}
{6170}{}{Он не представляет опасности гражданин, уймитесь!}

{6171}{}{Прекратить стрельбу, гражданин!}
{6172}{}{Гражданин, прекратить произвол!}
{6173}{}{Гражданин, немедленно прекратите!}
{6173}{}{Отставить стрельбу, гражданин!}
{6175}{}{Если он умрет - отправишься вслед за ним!}

{6176}{}{Так! Прекратить драку, клоуны!}
{6177}{}{Драки - за чертой города!}
{6178}{}{Найдите другое место для разборок, идиоты!}
{6179}{}{Эй! Завязывайте, драчуны!}
{6180}{}{Стоп! Никаких драк в городе!}

{6181}{}{Эй, каратист! Ану завязывай!}
{6182}{}{Эй ты, нинзя хренов! Прекращай!}
{6183}{}{Эй, хорош махать кулаками!}
{6184}{}{Прекратить мордобой!}
{6185}{}{Отставить драку!}

{6186}{}{Гражданам? По мордам? Ну, держись!}
{6187}{}{Драка с гражданином наказуема, сукин ты сын.}
{6188}{}{Руки прочь от граждан!}
{6189}{}{Убери свои грязные руки от гражданина!}
{6190}{}{Ну все, та труп, засранец!}

{6191}{}{Не стрелять! Это вор, пусть сами разбираются!}
{6192}{}{Да, мочи вора!}
{6193}{}{Ахаха! Посмотрите-ка, вора убивают!}
{6194}{}{Ну что? Допрыгался, воришка?}
{6195}{}{Молодец, смерть ворам!}

{6196}{}{Пусть сам разбирается, это та еще тварь!}
{6197}{}{Ну что? Не надо было нарываться, козел!}
{6198}{}{Смотрите-ка, нашего крутого парня обижают! Ахаха!}
{6199}{}{Чертов маньяк наконец-то получит по заслугам.}
{6200}{}{Ну что, крутой? Встретил равного?}

{6201}{}{Ну все, мы сыты тобой по горло! Приготовься здохнуть!}
{6202}{}{Я устал от тебя, приготовься умереть!}
{6203}{}{Ты труп, слышишь? Ты - труп!}
{6204}{}{Ну все, довольно с нас! Сегодня ты умрешь!}
{6205}{}{Ты допрыгался, слышишь? Ты труп!}

{6206}{}{Прекращайте стрельбу! Это мирный город!}
{6207}{}{Отставить стрельбу!}
{6208}{}{Прекрати немедленно!}
{6209}{}{Оставить огонь!}
{6210}{}{Ты что творишь, сука?}

{6211}{}{Стрелять в безоружного? Ты перешел черту!}
{6212}{}{Стрелять по тем, кто не может защититься? Ты труп!}
{6213}{}{Ты выстрелил в безоружного человека! Приготовься к смерти!}
{6214}{}{Огонь по безоружным? Ты умрешь, сукин сын!}
{6215}{}{Я тебе покажу, что мы делаем с теми, кто стреляет в безоружных!}

{6216}{}{Нападение на охрану! Тревога!}
{6217}{}{Тревога! Нападение на караул!}
{6218}{}{Нападение на пост! Огонь по нарушителю!}
{6219}{}{Нападение на часового! Огонь!}
{6220}{}{Это была большая ошибка!}

{6221}{}{Так все, хорош!}
{6222}{}{Прекратите немедленно!}
{6223}{}{Джентльмены, завязывайте!}
{6224}{}{Отставить!}
{6225}{}{Хватит уже!}
{6226}{}{Да сколько ж можно-то!}
{6227}{}{Это мирный город, прекратить разборки!}
{6228}{}{Перестаньте!}
{6229}{}{Так, остыньте, или я вас остужу!}
{6230}{}{Прекратить!}

{6500}{}{Прекрати, сын мой, это бесполезно.}
{6501}{}{Много скверны в тебе.}
{6502}{}{Твоя боль мне понятно. Успокойся же, дитя.}
{6503}{}{Гнев губит тебя, не иди у него на поводу.}
{6504}{}{Нелегкий путь тебе выпал, ты озлоблен.}
{6505}{}{Твой гнев несправедлив. Прекрати же.}

{6506}{}{Еще не время, ты не можешь пройти.}
{6507}{}{Терпение, сын мой, терпение.}
{6508}{}{Твое время еще не пришло. Я не могу тебя пропустить.}
{6509}{}{Не спеши туда, у тебя впереди целая вечность.}
{6510}{}{Ты прожил всю свою жизнь в спешке, остановись хоть сейчас.}

{6600}{}{Судя по всему, автодок не запитан.}
{6601}{}{Питание, похоже, есть, но автодок не активирован. Наверное, он включается где-то в другом месте.}
{6602}{}{Чип успешно имплантирован. Странно, вы ожидали, что все будет гораздо сложнее и дольше.}
{6603}{}{Вам уже имплантирован записывающий чип - это ни к чему.}
{6604}{}{Память успешно записана в образец.}
{6605}{}{Ваше тело вас не слушается, голова раскалывается, но вы живы.}
{6606}{}{Идет процесс записи, это может занять несколько часов...}
{6607}{}{Индикатор питания не горит - он выключен.}
{6608}{}{Индикатор питания горит, но, похоже, его нужно активировать из другого места.}
{6609}{}{Вы успешно отремонтировали силовую броню.}
{6610}{}{Вам не удалось починить силовую броню.}
{6611}{}{Всю эту груду металла отсюда не утащить.}
{6612}{}{Автодок не расчитан на вашу физиологию.}

{7001}{}{зеро}
{7002}{}{двойное зеро}
{7003}{}{красное}
{7004}{}{черное}
{7005}{}{число }
{7006}{}{Ваш выигрыш: }
{7007}{}{Неверное число}
{7008}{}{Неверная ставка}
{7009}{}{Число принято}
{7010}{}{Ставка принята}
{7011}{}{Текущая ставка: @lex betsize@}
{7012}{}{Вы поставили на числа:}
{7013}{}{@lex result@}
{7014}{}{На что ставим?}
{7015}{}{Выберите @lex num@ число}
{7016}{}{первое}
{7017}{}{второе}

{8000}{}{Ваши карты:}
{8001}{}{у вас}
{8002}{}{В банке:}
{8003}{}{Текущая ставка:}
{8004}{}{Ваша последняя ставка:}
{8005}{}{спасовал.}
{8006}{}{поднял ставку.}
{8007}{}{еще не делал ставку.}
{8008}{}{ответил на ставку.}
{8009}{}{Игрок}
{8010}{}{Выигрышная комбинация:}
{8011}{}{Победители:}
{8012}{}{Вы!}
{8013}{}{Игрок номер}
{8014}{}{пики}
{8015}{}{червы}
{8016}{}{бубны}
{8017}{}{крести}
{8018}{}{двойка}
{8019}{}{тройка}
{8020}{}{четверка}
{8021}{}{пятерка}
{8022}{}{шестерка}
{8023}{}{семерка}
{8024}{}{восьмерка}
{8025}{}{девятка}
{8026}{}{десятка}
{8027}{}{валет}
{8028}{}{дама}
{8029}{}{король}
{8030}{}{туз}
{8031}{}{ничего}
{8032}{}{пара}
{8033}{}{две пары}
{8034}{}{сет}
{8035}{}{стрейт}
{8036}{}{флаш}
{8037}{}{фул-хаус}
{8038}{}{каре}
{8039}{}{стрейт флаш}
{8040}{}{флаш рояль}
{8041}{}{@lex gametext@}
{8042}{}{принял ставку.}
{8043}{}{Неверное значение.}
{8044}{}{Ставка повышена.}
{8045}{}{Карты игрока:}
{8046}{}{комбинация}
{8047}{}{Ты за кого нас принимаешь?! А ну @sex@|пошел||пошла|| отсюда!}
{8048}{}{Тебе мама не говорила, что подсматривать карты плохо?}
{8049}{}{Да как ты смеешь сюда приходить, обманщ@sex@|ик||ица|?!}
{8050}{}{Как твои дела, @sex@|жулик||обманщица|? Ну ладно, забудем старые обиды, играть все равно не с кем...}
{8051}{}{Карта в Вашем рукаве:}
{8052}{}{Выбрать}
{8053}{}{Отменить}
{8054}{}{Ты обобрал@sex@|||а| до нитки всех за этим столом! Больше мы с тобой играть  не будем!}
{8055}{}{Приветствую лучшего игрока в этой дыре! Почему не заходишь, Мастер?}

#russian roullet
{9000}{}{Проиграл в Русскую рулетку@@Вынес себе мозги@@Сегодня не его день@@Зря он это затеял@@Залил все своей кровью@@Закричал нажав на курок и пуля его заткнула@@Застрелился@@Без колебаний запачкал все своими мозгами}
{9001}{}{Щелчок... но не чего не произошло@@Чуть не у делался, но пронесло@@Закричал и нажал на курок, но все обошлось@@Фортуна улыбнулась@@Выиграл в Русскую рулетку@@ПОВЕЗЛО@@Затаил дыхания, нажал на курок, но все обошлось}

{15000}{}{Вам становится страшно.}
{15000}{}{Вам больше некуда идти.}
{15000}{}{Впереди вы видите только мёртвый песок и понимаете, что начав путь туда, вы обречёте себя на верную смерть. Поэтому вам ничего не остаётся, кроме как влачить свое жалкое существование здесь, борясь за кусок мяса с другими людьми и животными.}
{15000}{}{Там нет жизни.}
{15000}{}{Там вас ничего не ждёт.}

{70061}{}{Вы съели столько пончиков, что стали немного сильнее. Переносимый вес увеличен на +1 фунт.}