# Увеличение скила
{15}{}{Навык @lex skill@ увеличен на @lex value@ очков}

# Generic messages
{510}{}{Да} # Magic ball
{511}{}{Нет} # Magic ball
{520}{}{пудрит носик} # Cosmetic
{530}{}{курит} # Cigarettes

# General interactive machines
{1000}{}{вставляет деньги в аппарат}
{1001}{}{|0xFFFF00 Аппарат заперт.}
{1002}{}{открывает аппарат}

# Slots
{2001}{}{|0xFFFF00 В автомате закончились деньги.}
{2002}{}{|0xFFFF00 В автомате не хватает денег для  для покрытия ставки.}
{2003}{}{|0xFFFF00 ДЖЕЕЕЕЕЕКПОТ!!! @lex result@$}
{2004}{}{|0xFFFF00 Выигрыш: @lex result@$}
{2005}{}{|0xFF0000 Проигрыш!}
{2006}{}{|0xFFFF00 У Вас нет такой суммы.}
{2007}{}{|0xFFFF00 Ставка }

# Coinflip
{2050}{}{подкидывает монетку: |0x7CFC00 Бермин|0xFF00FF .}
{2051}{}{подкидывает монетку: |0x7CFC00 Бак|0xFF00FF .}

# Dice use
{2053}{}{выбрасывает: |0x7CFC00 @lex result@|0xFF00FF .}

# Cards
{2054}{}{|0xFFFF00 Колода пуста!}
{2055}{}{|0xFFFF00 В колоде нет карт!}
{2056}{}{вытягивает: }
{2057}{}{сдает карту}
{2058}{}{|0xFFFF00 Вам сдали карту.}
{2059}{}{тасует карты}
{2060}{}{набирает карты}
{2061}{}{|0xFFFF00 Сюда можно только добавить карты.}
{2062}{}{показывает: }
{2063}{}{Ваша рука:  }

# Vending Machines
{2100}{}{забирает товар}
{2101}{}{забирает сдачу}
{2102}{}{устанавливает новый товар}

# Jukebox
{2150}{}{|0xFFFF00 Вы заметили, что выбранная пластинка отсутствует!}
{2151}{}{|0xFFFF00 Похоже, что размен закончился!}

# Terminal
{2200}{}{|0xFFFF00 Вы заблокировали доступ к терминалу.}
{2201}{}{открывает приемник для карт}
{2202}{}{|0xFFFF00 Терминал не принимает данный предмет!}
{2203}{}{устанавливает новую карту доступа}
{2204}{}{отключает пропуски}

# Combat
{2300}{}{|0xFFFF00 Вы не можете вести огонь с этого оружия без предварительного вскидывания для раскрутки стволов!}
{2301}{}{опутан}
{2302}{}{опутана}
{2303}{}{опутано}
{2304}{}{|0xFFFF00 Ваше оружие дало осечку!}

# Taste
{6487}{}{\nБрага со вкусом }
{6488}{}{капусты}
{6489}{}{орехов}
{6490}{}{хлеба}
{6491}{}{ягод паслена}
{6492}{}{мутафруктов}
{6493}{}{ванили}
{6494}{}{кукурузы}
{6495}{}{печенья}
{6496}{}{протеинового батончика}
{6497}{}{конфет}
{6498}{}{карамели}
{6499}{}{Судя по запаху, внутри:}

# St Peter
{6500}{}{Прекрати, сын мой, это бесполезно.}
{6501}{}{Много скверны в тебе.}
{6502}{}{Твоя боль мне понятно. Успокойся же, дитя.}
{6503}{}{Гнев губит тебя, не иди у него на поводу.}
{6504}{}{Нелегкий путь тебе выпал, ты озлоблен.}
{6505}{}{Твой гнев несправедлив. Прекрати же.}

{6506}{}{Еще не время, ты не можешь пройти.}
{6507}{}{Терпение, сын мой, терпение.}
{6508}{}{Твое время еще не пришло. Я не могу тебя пропустить.}
{6509}{}{Не спеши туда, у тебя впереди целая вечность.}
{6510}{}{Ты прожил всю свою жизнь в спешке, остановись хоть сейчас.}

# Roulette
{7001}{}{зеро}
{7002}{}{двойное зеро}
{7003}{}{красное}
{7004}{}{черное}
{7005}{}{число }
{7006}{}{Ваш выигрыш: }
{7007}{}{Неверное число}
{7008}{}{Неверная ставка}
{7009}{}{Число принято}
{7010}{}{Ставка принята}
{7011}{}{Текущая ставка: @lex betsize@}
{7012}{}{Вы поставили на числа:}
{7013}{}{@lex result@}
{7014}{}{На что ставим?}

#Russian Roulette
{9000}{}{проиграл в Русскую рулетку@@вынес себе мозги@@Сегодня не его день@@зря он это затеял@@залил все своей кровью@@закричал нажав на спусковой крючок, но крик был оборван...@@застрелился@@без колебаний запачкал все своими мозгами}
{9001}{}{щелчок, но не чего не произошло@@чуть не уделался, но пронесло...@@закричал и спустил курок, но все обошлось@@фортуна улыбнулась@@выиграл в Русскую рулетку@@ПОВЕЗЛО@@затаив дыхание, нажал на спусковой крючок, но все обошлось}
{9002}{}{проиграла в Русскую рулетку@@вынесла себе мозги@@Сегодня не ее день@@зря она это затеяла@@залила все своей кровью@@закричала нажав на спусковой крючок, но крик был оборван...@@застрелилась@@без колебаний запачкала все своими мозгами}
{9003}{}{щелчок, но не чего не произошло@@чуть не уделалась, но пронесло...@@закричала и спустила курок, но все обошлось@@фортуна улыбнулась@@выиграла в Русскую рулетку@@ПОВЕЗЛО@@затаив дыхание, нажала на спусковой крючок, но все обошлось}

#Resource Gathering
{9004}{}{срывает растение}
{9005}{}{|0xFFFF00 Вы не нашли ничего полезного.}
{9006}{}{Вы добыли:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800  шт.}
{9007}{}{|0x3CF800  шт.}
{9008}{}{|0xFFFF00 Вы сорвали растение в неправильной стадии, а затем выкинули его.}
{9009}{}{|0xFFFF00 Вы слишком устали, передохните.}
{9010}{}{|0xFFFF00 Возьмите инструмент в руку.}
{9011}{}{|0xFFFF00 Вы травмированы и не в состоянии выполнить задачу.}
{9012}{}{|0xFFFF00 Это было хорошей идеей, пока вы не поняли, что в буре нет энергии.}
{9013}{}{|0xFFFF00 Бур слишком повреждён.}
{9014}{}{|0xFFFF00 Сначала добейте жертву.}
{9015}{}{|0xFFFF00 Вы не можете разделать это.}
{9016}{}{|0xFFFF00 Тут нечего разделывать.}
{9017}{}{|0xFFFF00 Вы сильно исполосовали животное.}
{9018}{}{|0xFFFF00 Этот инструмент не подходит для рубки.}
{9019}{}{|0xFFFF00 Тут нечего рубить, придется подкопать и выкорчевать.}
{9020}{}{Вы получили: }
{9021}{}{- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800  шт.}
{9022}{}{что-то делает}

#ItemMovement
{9445}{}{|0xFFFF00 Слишком тяжело, не достать.}
{9446}{}{берёт карту}
{9447}{}{берёт броню}
{9448}{}{берёт @lex proto@}
{9449}{}{берёт оружие}
{9450}{}{берёт патроны}
{9451}{}{берёт что-то}
{9452}{}{|0xFFFF00 Необходимо отойти, чтобы установить предмет.}
{9453}{}{|0xFFFF00 Перенос в слот невозможен, т.к. для данного оружия отсутствуют анимации!}
{9454}{}{|0xFFFF00 Оружие в основной руке не поддерживается данным скином, перенос в инвентарь!}
{9455}{}{|0xFFFF00 Оружие во второй руке не поддерживается данным скином, перенос в инвентарь!}
{9456}{}{|0xFF00FF Электронный голос: |0xF8F993 Личность распознана. Активация!}
{9457}{}{нарастающий гул реактора}
{9458}{}{скрывает лицо}
{9459}{}{показывает лицо}
{9460}{}{снимает рюкзак}
{9461}{}{снимает предмет}
{9462}{}{|0xFFFF00 Вы не в силах сопротивляться, пока у вас отбирают рюкзак.}
{9463}{}{|0xFFFF00 Вы не в силах сопротивляться, пока у вас отбирают предмет.}
{9464}{}{|0xFFFF00 Вы забрали рюкзак.}
{9465}{}{|0xFFFF00 Вы забрали предмет.}
{9466}{}{пытается снять броню}
{9467}{}{|0xFFFF00 Вы снимаете с цели всё что можете.}
{9468}{}{|0xFFFF00 Вашу броню пытаются снять!}
{9469}{}{|0xFFFF00 Вы забрали у персонажа броню.}
{9470}{}{|0xFFFF00 С вас сняли броню.}
{9471}{}{|0xFFFF00 Вы сняли броню с жертвы.}
{9472}{}{|0xFFFF00 Вы частично сняли броню с жертвы.}

#Windup
{9476}{}{вскидывает @lex proto@}
{9477}{}{опускает @lex proto@}
{9478}{}{поднимает кулаки}
{9479}{}{поднимает кулачки}
{9480}{}{поднимает кулачищи}
{9481}{}{стучит копытом}
{9482}{}{поднимает жало}
{9483}{}{скалится}
{9484}{}{поднимается в полный рост}
{9485}{}{распахивает пасти}
{9486}{}{вскидывает манипуляторы}
{9487}{}{поднимает лапы}
{9488}{}{поднимает щупольцы}
{9489}{}{распахивает жвала}
{9490}{}{смотрит на Вас как на говно}
{9491}{}{выпускает жало}
{9492}{}{громко рычит}
{9493}{}{распахивает клешни}
{9494}{}{утробно рычит}
{9495}{}{расслабляется}

#Raising skills
{9496}{}{|0xFFFF00 Вы стали настоящим экспертом в ублажении партнеров!}
{9497}{}{|0xFFFF00 Вы не смогли повысить свой навык.}
{9498}{}{|0x3CF800 Навык: }
{9499}{}{|0x3CF800  повышен на }

#Accidental injuries
{9500}{}{|0xFFFF00 В последний момент Вы чудом избежали старшной травмы, но все же: \n}
{9501}{}{|0xFFFF00 В результате ошибки вы сильно ушиблись.}
{9502}{}{|0xFFFF00 Вы ошиблись и слегка рассекли руку.}
{9503}{}{|0xFFFF00 Вы попали инструментом по себе и сильно рассекли плоть.}
{9504}{}{|0xFFFF00 Из-за неудачного движения Вы получили тяжелую производственную травму.}
{9505}{}{|0xFFFF00 В результате ошибки Вы сильно рассекли бровь, кровь заливает лицо.}

#Blood loss
{9510}{}{|0xFFFF00 Вы чувствуете слабость от обильной кровопотери.}
{9511}{}{|0xFFFF00 Силы покидают вас, вы начинаете медленно умирать от потери большого количества крови.}

#Vomiting
{9512}{}{|0xFFFF00 Вас начало мутить...}
{9513}{}{блюет}
{9514}{}{|0xFFFF00 Кажется, Вас сейчас стошнит...}

#Resurection
{9520}{}{|0xFFFF00 Потратив препарат, вы поняли, что он тут не поможет.}
{9521}{}{|0xFFFF00 Ваш организм получил шанс на выживание, но ваше здоровье никогда не станет прежним.}
{9522}{}{|0xFFFF00 Вам четко видно, что организм этого человека не перенесет дозу стимулятора.}

#Food / drink
{9523}{}{урчит животом}
{9524}{}{облизывает сухие губы}
{9525}{}{шатается}
{9526}{}{|0xFFFF00 Полученные повреждения слишком обширны. Без медицинского вмешательства вы скоро умрёте.}
{9527}{}{|0xFFFF00 Вы страдаете от голода.}
{9528}{}{|0xFFFF00 Вы страдаете от жажды.}
{9529}{}{|0xFFFF00 Вы перестали чувствовать вкус алкоголя...}
{9530}{}{|0xFFFF00 Из-за сильной жажды Вы стали двигаться медленее.}
{9531}{}{|0xFFFF00 Из-за сильного голода Вы стали двигаться медленее.}
{9532}{}{|0xFFFF00 Вы набрались сил.}
{9533}{}{пьет}
{9534}{}{Вы употребили: |0xFFFF00 @lex proto@|0x3CF800 .}
{9535}{}{Вы потеряли: |0xFFFF00 @lex rad@|0x3CF800  рад.}
{9536}{}{Вы получили: |0xFFFF00 @lex poison@|0x3CF800  пунктов отравления.}
{9537}{}{употребляет @lex proto@}

#Dragging
{9540}{}{|0xFFFF00 Вы не можете сделать этого.}
{9541}{}{|0xFFFF00 Цель должна лежать или быть мертва!}
{9542}{}{|0xFFFF00 Цель слишком далеко.}
{9543}{}{|0xFFFF00 Тело уже тащат.}
{9544}{}{|0xFFFF00 Вы не можете тащить больше 1 тела.}
{9545}{}{|0xFFFF00 Вы тащите тело.}
{9546}{}{|0xFFFF00 Вы отпустили тело.}

#Dirt
{9550}{}{|0xFFFF00 Вы начали отталкивать окружающих обилием грязи и неприятным запахом. Вам бы не помешало помыться.}
{9551}{}{|0xFFFF00 Вы перестали отталкивать окружающих своей грязью и запахом.}

#Lie / stand
{9552}{}{|0xFFFF00 Вы не в силах подняться.}
{9553}{}{|0xFFFF00 Вы встаёте.}
{9554}{}{|0xFFFF00 Вы ложитесь.}

#Locks and lockpicking
{9600}{}{|0xFFFF00 С этой стороны в замок вставлен ключ, который вам мешает.}
{9601}{}{|0xFFFF00 С другой стороны в замок вставлен ключ, который вам мешает.}
{9602}{}{|0xFFFF00 Вы отперли замок.}
{9603}{}{отпирает}
{9604}{}{|0xFFFF00 Вы заперли замок.}
{9605}{}{запирает}
{9606}{}{|0xFFFF00 Сначала закройте.}
{9607}{}{|0xFFFF00 Ключ не подходит.}
{9608}{}{|0xFFFF00 Что-то не даёт закрыть дверь.}
{9609}{}{|0xFFFF00 Нужна электроная отмычка.}
{9610}{}{|0xFFFF00 Вы слишком далеко от цели.}
{9611}{}{|0x606060 тук-тук}
{9612}{}{|0xFFFF00 Вы постучали.}
{9613}{}{|0xFF0000 УДАР}
{9614}{}{|0xFFFF00 Дверь и так открыта.}
{9615}{}{|0xFFFF00 Нет замка.}
{9616}{}{|0xFFFF00 Нужны отмычки или хотя бы какая-никакая шпилька.}
{9617}{}{|0xFFFF00 Отмычка сломалась, видимо ее неудачно вытащили из замка в прошлый раз.}
{9618}{}{вынимает ключ из замка}
{9619}{}{вставляет ключ в замок}
{9620}{}{|0xFFFF00 Вы слишком далеко от замка, ваши отмычки сломались.}
{9621}{}{|0xFFFF00 Вы успешно вскрыли замок.}
{9622}{}{|0xFFFF00 Вы аккуратно вытащили отмычку из замка.}
{9623}{}{|0xFFFF00 Вашего навыка недостаточно, чтобы защелкнуть замок.}
{9624}{}{|0xFFFF00 Дверь и так заперта.}
{9625}{}{|0xFFFF00 Вы защелкнули замок.}
{9626}{}{|0xFFFF00 Вы сняли замок.}

#item taking
{9630}{}{сопротивляется}
{9631}{}{пытается что-то отобрать}
{9632}{}{|0xFFFF00 Вы слишком устали, что бы успешно отобрать вещь.}

#decraft and repair
{9650}{}{|0xFFFF00 Этот объект не подлежит износу.}
{9651}{}{|0xFF0000 Вы травмированы и не в состоянии произвести ремонт.}
{9652}{}{|0xFFFF00 Не ремонтируемо!}
{9653}{}{|0xFF0000 Вы травмированы и не в состоянии разобрать предмет.}
{9654}{}{завершает разборку}
{9655}{}{|0xFF0000 Вам нехватает навыков.}
{9656}{}{завершает работу}
{9657}{}{|0xFFFF00 В этой броне уже встроена рация.}
{9658}{}{завершает установку рации в броню}
{9659}{}{|0xFFFF00 Эту броню перекрасить не удастся.}
{9660}{}{|0xFF0000 Вы травмированы и не в состоянии перекрасить броню.}
{9661}{}{завершает перекраску брони}
{9662}{}{|0xFF0000 Вы травмированы и не в состоянии установить рацию.}
{9663}{}{Необходимый инструмент: }
{9664}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9665}{}{Необходимые запчасти: }
{9666}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9667}{}{Необходим один из инструментов в руке: }
{9668}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9669}{}{Получаемые части: }
{9670}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9671}{}{Вы разобрали |0xFFFF00 @lex proto@|0x3CF800 , получив: }
{9672}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9673}{}{|0xFFFF00 Вы не смогли произвести установку рации!}
{9674}{}{|0x3CF800 Необходимо иметь навыки:
 - |0xFFFF00 Наука |0x3CF800  -  |0xFFFF00 150 |0x3CF800 ,
 - |0xFFFF00 Ремонт |0x3CF800  -  |0xFFFF00 200 |0x3CF800 .}

#Flasks and bottles
{9768}{}{|0xFFFF00 Ваша анатомия не позволяет Вам открыть бутылку!}
{9769}{}{|0xFFFF00 Вам нечем открыть бутылку!}
{9770}{}{Вы открыли бутылку: |0xFFFF00" @lex proto@|0x3CF800.}
{9771}{}{открывает бутылку}
{9772}{}{|0xFFFF00 Возьмите предмет в руку!}
{9773}{}{|0xFFFF00 Попробуйте заполнить бутылку другим способом.}
{9774}{}{|0xFFFF00 У Вас закончилась тара.}
{9775}{}{|0xFFFF00 Вы разлили всю воду по бутылкам.}
{9776}{}{|0xFFFF00 Емкость заполнена чем-то другим.}
{9777}{}{наполняет @lex proto@}
{9778}{}{|0xFFFF00 Возьмите емкость в руку.}
{9779}{}{|0xFFFF00 Емкость пуста.}
{9780}{}{выливает @lex proto@}
{9781}{}{|0xFFFF00 Емкость уже заполнена.}
{9782}{}{|0xFFFF00 Вы наполнили емкость.}
{9783}{}{|0xFFFF00 Тара опустела.}
{9784}{}{|0xFFFF00 Воды больше нет.}
{9785}{}{|0xFFFF00 У вас нет подходящей бутылки в руках.}
{9786}{}{|0xFFFF00 Вы полностью наполнили бутылку водой.}

#Smoking
{9787}{}{вскрывает пачку сигарет}
{9788}{}{|0xFFFF00 В пачке больше не осталось сигарет.}
{9789}{}{достаёт сигарету из пачки}
{9790}{}{|0xFFFF00 Вам нужен источник огня, что бы прикурить.}
{9791}{}{|0xFFFF00 Вы не можете курить через респиратор.}
{9792}{}{|0xFFFF00 Возьмите предмет в руку, чтобы закурить.}
{9793}{}{|0xFFFF00 Трубка пуста.}
{9794}{}{|0xFFFF00 Трубка прогорела.}
{9795}{}{|0xFFFF00 Вы заправили трубку.}
{9796}{}{|0xFFFF00 Мешочек опустел.}
{9797}{}{|0xFFFF00 Возьмите трубку в руку, чтобы заправить ее.}
{9798}{}{|0xFFFF00 Вы чувствуете вкус табака.}
{9799}{}{|0xFFFF00 Вы чувствуете вкус пятилистника.}

#Various Items
{9800}{}{щёлкает фотоаппаратом}
{9801}{}{убирает золу}
{9802}{}{убирает останки}
{9803}{}{вытирает кровь}
{9804}{}{|0xFFFF00 Вы убрали часть останков.}
{9805}{}{|0xFFFF00 Вы собрали останки.}
{9806}{}{|0xFFFF00 Возьмите музыкальный инструмент в руку.}
{9807}{}{играет на флейте}
{9808}{}{|0xFFFF00 Попробуйте копать ближе к себе.}
{9809}{}{|0xFFFF00 В этом месте нет пригодного песка.}
{9810}{}{|0xFFFF00 Что в этом предмете особенного?}
{9811}{}{|0xFFFF00 Похоже, вы без понятия, что с этим можно делать.}
{9812}{}{|0xFFFF00 Сначала достаньте предмет из контейнера!}
{9813}{}{|0xFFFF00 Теперь этот предмет имеет отличительные особенности.}
{9814}{}{|0xFFFF00 Вы сделали так, что бы этот предмет больше ничем не выделялся.}
{9815}{}{разжигает лампу}
{9816}{}{|0xFFFF00 Для розжига лампы нужна зажигалка!}
{9817}{}{|0xFFFF00 В лампе нет масла.}
{9818}{}{гасит лампу}
{9819}{}{включает фонарь}
{9820}{}{|0xFFFF00 В фонаре нет заряда.}
{9821}{}{выключает фонарь}
{9822}{}{разжигает химический фонарик}
{9823}{}{гасит химический фонарик}
{9824}{}{вытирается полотенцем}
{9825}{}{вытирается грязны полотенцем}
{9826}{}{моет полотенце}
{9827}{}{меняет батарею}
{9828}{}{заправляет фонарик}
{9829}{}{|0xFFFF00 Не удалось впихнуть предмет в контейнер.}
{9830}{}{Серийный номер: }

#Ropes and shackles
{9831}{}{|0xFFFF00 Вы не можете освободить себя таким образом.}
{9832}{}{|0xFFFF00 Это здесь не поможет.}
{9833}{}{особождает цель}
{9834}{}{освобождается}
{9835}{}{|0xFFFF00 Без монтировки тут не обойтись.}
{9836}{}{высвобождает цель из капкана}
{9837}{}{высвобождается из капкана}
{9838}{}{|0xFFFF00 Вы высвобождены из капкана!}
{9839}{}{|0xFFFF00 Ключ не подходит.}
{9840}{}{|0xFFFF00 Предмет сломан и не может быть использован.}
{9841}{}{|0xFFFF00 Это бесполезно, цель мертва.}
{9842}{}{|0xFFFF00 Цель уже связана аналогичным предметом!}

{9843}{}{надевает на себя наручники}
{9844}{}{надевает наручники}
{9845}{}{|0xFFFF00 Вы надели на себя наручники.}
{9846}{}{|0xFFFF00 На вас одели наручники!}
{9847}{}{|0xFFFF00 Вы освобождены от наручников.}
{9848}{}{снимает с себя наручники}
{9849}{}{снимает наручники}

{9850}{}{связывает себя}
{9851}{}{связывает}
{9852}{}{|0xFFFF00 Вы связали сами себя.}
{9853}{}{|0xFFFF00 Вас связали!}
{9854}{}{|0xFFFF00 Вы освобождены от веревки.}
{9855}{}{режет связывающую руки веревку}
{9856}{}{режет веревку}

{9857}{}{надевает на себя кандалы}
{9858}{}{надевает кандалы}
{9859}{}{|0xFFFF00 Вы надели на себя кандалы.}
{9860}{}{|0xFFFF00 На вас одели кандалы!}
{9861}{}{|0xFFFF00 Вы освобождены от кандалов.}
{9862}{}{снимает с себя кандалы}
{9863{}{снимает кандалы}

{9864}{}{засовывает шариковый кляп себе в рот}
{9865}{}{засовывает шариковый кляп в рот}
{9866}{}{|0xFFFF00 Вы засунули шариковый кляп себе в рот.}
{9867}{}{|0xFFFF00 Вам засунули шариковый кляп в рот.}
{9868}{}{|0xFFFF00 Из вашего рта вынут шариковый кляп.}
{9869}{}{вытаскивает шариковый кляп из своего рта}
{9870}{}{вытаскивает шариковый кляп}

{9871}{}{засовывает кляп себе в рот}
{9872}{}{засовывает кляп в рот}
{9873}{}{|0xFFFF00 Вы засунули кляп себе в рот.}
{9874}{}{|0xFFFF00 Вам засунули кляп в рот.}
{9875}{}{|0xFFFF00 Из вашего рта вынут кляп.}
{9876}{}{вытаскивает кляп из своего рта}
{9877}{}{вытаскивает кляп}

{9878}{}{надевает на себя рабский ошейник}
{9879}{}{надевает рабский ошейник}
{9880}{}{|0xFFFF00 Вы надели на себя рабский ошейник.}
{9881}{}{|0xFFFF00 На вас одели рабский ошейник!}
{9882}{}{|0xFFFF00 Вы освобождены от рабского ошейника.}
{9883}{}{снимает с себя рабский ошейник}
{9884}{}{снимает рабский ошейник}

{9885}{}{|0xFFFF00 Вы отремонтировали наручники.}
{9886}{}{|0xFFFF00 Вы отремонтировали кандалы.}
{9886}{}{|0xFFFF00 Связанные руки не позволяют Вам сделать это.}

{9890}{}{|0xFFFF00 Вы освободили раба.}
{9891}{}{|0xFFFF00 Вы наказали раба.}
{9892}{}{|0xFFFF00 Шею обожгло огнем, все тело сотрясают судороги.}
{9893}{}{корчится в агонии}
{9894}{}{|0xFFFF00 Шею обожгло огнем, Вы содрагаетесь под множественными ударами тока.}
{9895}{}{|0xFFFF00 Шею обожгло огнем, все тело содрагается от мощнейшей непрекращающейся боли.}
{9896}{}{|0xFFFF00 Вы казнили раба}
{9897}{}{|0xFFFF00 Боль тысячи расскаленных игл пронзила вас}
{9898}{}{нажимает кнопку}

#Forgot to activate char
{9899}{}{с громким хлопком скукоживается в точку}

#General stuff
{9900}{}{одышка}
{9901}{}{потирает ушиб}
{9902}{}{вскрикивает от боли}
{9903}{}{хватается за окровавленную конечность}
{9904}{}{орет от боли}
{9905}{}{воет от дикой боли}
{9906}{}{поскальзывается на чем-то гадком}
{9907}{}{Вы выронили: |0xFFFF00 @lex proto@ |0x3CF800 из рук.}
{9908}{}{|0xFFFF00 Вас обжигает кислотой.}
{9909}{}{перебинтовывает}
{9910}{}{перебинтовывается}
{9911}{}{|0xFFFF00 Из этого ничего не вышло.}

#Key duplicate
{9914}{}{|0xFFFF00 Вы сделали копию ключа.}

#X2 X3 containers
{9915}{}{|0xFFFF00 Контейнер переполнен, освободите чаcть веса для того, чтобы снять верхний ящик.}

#Sandbags
{9916}{}{|0xFFFF00 Существо мешает установить мешки.}
{9917}{}{|0xFFFF00 Вы не можете сделать эту груду мешков выше.}

#Locks
{9918}{}{|0xFFFF00 Вы не можете запереть терминал на замок.}
{9919}{}{|0xFFFF00 Вам нужна хотя бы одна железяка для заготовки ключа под устанавливаемый замок.}
{9920}{}{|0xFFFF00 Дверь уже заперта, сначала взломайте замок.}
{9921}{}{|0xFFFF00 Сначала закройте объект.}
{9922}{}{|0xFFFF00 Этот объект нельзя запереть.}

#Dismantling / securing items
{9923}{}{|0xFFFF00 Предмет поднимаем, теперь его можно перенести на новое место.}
{9924}{}{|0xFFFF00 Предмет надежно закреплен.}

#CarryItems
{9925}{}{|0xFFFF00 Это не поднять!}
{9926}{}{|0xFFFF00 Cлишком тяжело!}
{9927}{}{|0xFFFF00 Вы не можете это поднять, так как несете максимальный груз!}
{9928}{}{|0xFFFF00 Вы не можете это поднять, так как несете слишком много предметов!}

#Furniture
{9929}{}{|0xFFFF00 У вас нет подходящего ключа.}
{9930}{}{|0xFFFF00 Возьмите ключ или ключницу в руку.}
{9931}{}{перестаёт толкать}
{9932}{}{|0xFFFF00 Это сюда не влезет.}
{9933}{}{|0xFFFF00 Требуется демонтаж.}
{9934}{}{|0xFFFF00 Из этого ничего не вышло.}
{9935}{}{|0xFFFF00 Заперто.}
{9936}{}{|0xFFFF00 Слишком тяжело.}
{9937}{}{|0xFFFF00 Данный объект так просто не сдвинуть. Сначала снимите замок.}
{9938}{}{|0xFFFF00 Предмет поднимаем. Что бы изменить состояние - используйте ремонт.}
{9939}{}{|0xFFFF00 Предмет неподъёмен. Что бы изменить состояние - используйте ремонт.}
{9940}{}{пытается остановить}
{9941}{}{|0xFFFF00 Нельзя перемещать закрытую и запертую мебель.}
{9942}{}{толкает}
{9943}{}{|0xFFFF00 Вы не можете сделать стэк контейнеров выше.}
{9944}{}{|0xFFFF00 Существо мешает установить контейнер.}

#No access for mob control
{9945}{}{|0xFFFF00 Требуется уровень ГМ досутпа.}

#h-attack
{9946}{}{|0xFFFF00 Этим нельзя драться.}

#use radio
{9947}{}{говорит в рацию}

##zh - command
{9948}{}{|0xFFFF00 Вы отправили @lex npc$@ на домашнюю позицию.}
{9949}{}{|0xFFFF00 Существо @lex npc$@ и так на домашней позиции.}

#push target
{9950}{}{|0xFFFF00 Вы толкаете цель.}
{9951}{}{|0xFFFF00 Цель сопротивляется.}

#~naked
{9952}{}{раздевается}

#~desc
{9953}{}{|0xFFFF00 Опишите детали, характерные для этого места.}
{9954}{}{|0xFFFF00 Вы заметили некоторые особенности этого места.}
{9955}{}{|0xFFFF00 У вас ничего не вышло.}
{9956}{}{|0xFFFF00 Вы убрали всё, что могло привлечь внимание.}
{9957}{}{|0xFFFF00 У вас не вышло замести следы.}

#Throw
{9958}{}{|0xFFFF00 Вы не в состоянии кидать так далеко.}
{9959}{}{|0xFFFF00 Вы не можете бросить это.}
{9960}{}{ловит предмет}
{9961}{}{руки заняты, не может поймать предмет}
{9962}{}{:разбилась вдребезги:}
{9963}{}{бросает предмет}

#Knocking
{9964}{}{|0xFFFF00 Недостаточно очков действия.}
{9965}{}{|0xFFFF00 Вы не в состоянии сделать это.}
{9966}{}{|0xFFFF00 Вы промахнулись по цели.}
{9967}{}{|0xFFFF00 Вы не можете бить так часто.}
{9968}{}{:стук:}
{9969}{}{|0xFFFF00 Вы постучали.}
{9970}{}{|0xFFFF00 Вы слишком далеко!}

#Code door password
{9971}{}{Вы установили новый код: |0xFFFF00 @lex code@}
{9972}{}{|0xFFFF00 Не допустимый код!}
{9973}{}{|0xFFFF00 Не верный код!}

#Change Lex self
{9974}{}{|0xFFFF00 Вы изменили своё описание.}

#Digits input
{9975}{}{Вы установили новый пароль: |0xFFFF00 @lex digits@}
{9976}{}{|0xFFFF00 Вы ввели верный пароль!}
{9977}{}{|0xFFFF00 Пароль не подходит!}

#Suicide
{9978}{}{вспарывает себе живот}
{9979}{}{пытается душить себя}
{9980}{}{раскрутив барабан, приставляет револьвер к виску}
{9981}{}{засовывает дуло себе в рот}
{9982}{}{приставляет ствол к собстенному боку, палец ложится на спусковой крючок}
{9983}{}{прижав гранату к груди выдергивает чеку}
{9984}{}{вырвав тряпку, выливает на себя содержимое бутылки, в руке появилась зажигалка...}
{9985}{}{приставляет острый предмет к собственному животу}
{9986}{}{подносит пузырек с химикатами ко рту...}
{9987}{}{|0xFFFF00 Вам нечем убить себя.}
{9988}{}{вышибает собственные мозги}
{9989}{}{череп разлетается кровавым фонтаном, забрызгивая все вокруг}
{9991}{}{умножает себя на два}
{9992}{}{голова испараяется мнгновенно}
{9993}{}{тело содрагается от разряда}
{9994}{}{пытается застерлиться тратя заряд, неудобное оружие падает}
{9995}{}{спусковая скоба отлетает в сторону}
{9996}{}{|0xFFFF00 Граната сработала без особого эффекта.}
{9997}{}{выпивает пузырек}
{9998}{}{поджигает себя, огонь жадно пожирает все вокруг}

#Toilet
{9999}{}{смывает что-то в унитаз}

#StartMap
{10000}{}{|0xFFFF00 Ошибка, обратитесь к ГеймМастерам.}
{10001}{}{|0xFFFF00 Старт игры возможен только для новых персонажей.}
{10002}{}{|0xFFFF00 Старт игры возможен только на стартовой карте.}
{10003}{}{|0xFFFF00 Попробуйте еще раз.}
{10004}{}{|0xFFFF00 Вы выбрали режим выживания.}
{10005}{}{|0xFFFF00 Локация не найдена}
{10006}{}{|0xFFFF00 Карта не найдена}
{10007}{}{|0xFFFF00 Весь регион веет тоской, но кажется, несколько шагов вперед изменят вашу судьбу...}
{10008}{}{|0xFFFF00 Предмет был поглощен пустотой.}
{10009}{}{|0xFFFF00 Вам кажется сейчас это неуместо.}

#Gm Mode
{10010}{}{|0xFFFFFF Модерка выключена.}
{10011}{}{|0x606060 Модерка выключена.}

#Grid_to_global_warning
{15000}{}{|0xFFFF00 Вам становится страшно.}
{15000}{}{|0xFFFF00 Вам больше некуда идти.}
{15000}{}{|0xFFFF00 Впереди вы видите только мёртвый песок и понимаете, что начав путь туда, вы обречёте себя на верную смерть. Поэтому вам ничего не остаётся, кроме как влачить свое жалкое существование здесь, борясь за кусок мяса с другими людьми и животными.}
{15000}{}{|0xFFFF00 Там нет жизни.}
{15000}{}{|0xFFFF00 Там вас ничего не ждёт.}

# lifts:
# {2GG00} is key card item proto name from data/ItemNames.lst where GG is lifts group
# {2GGFF} is floor name where GG is lifts group, FF is floor

{20100}{}{PID_V15_KEYCARD}
{20101}{}{4 - Рубка}
{20102}{}{3 - Переговорная}
{20103}{}{2 - Казарма}
{20104}{}{1 - Столовая}
{20105}{}{0 - Камбуз}

{20201}{}{1 - Торговая}
{20202}{}{2 - Барная}
{20203}{}{3 - Промышленная}
{20204}{}{4 - Дыра}

{20301}{}{4 - Номера Люкс}
{20302}{}{3 - Номера Бизнес}
{20303}{}{2 - Номера Эконом}
{20304}{}{1 - Клуб}
{20305}{}{0 - Лобби}

{20400}{}{PID_SECURITY_CARD}
{20401}{}{1 - Поверхность}
{20402}{}{2 - Бункер}
{20403}{}{3 - Технический уровень}

{20501}{}{0 - Поверхность}
{20502}{}{1 - Химзавод}

{20601}{}{1 - Первый Этаж}
{20602}{}{0 - Лобби}

{20701}{}{0 - Лобби}