del scripts\*.fos~
del scripts\*.fosb
del scripts\*.fosp
del scripts\*.bak
del maps\*.fomapb
del maps\*.bak
del proto\critters\*.bak
del proto\items\*.bak
del text\russ\*.bak
del logs\*.txt
del logs\*.log