{10}{}{Hero}
{20}{}{Heroine}
{30}{}{Hillbillies}
{40}{}{Hillbillies}
{50}{}{Rad Scorpion}
{51}{}{A small mutated scorpion.}
{60}{}{Rad Scorpion}
{61}{}{Mutated Scorpion}
{70}{}{Claw of Death}
{71}{}{Little Death Claw}
{80}{}{Claw of Death}
{81}{}{Little Death Claw}
{90}{}{Dog}
{91}{}{A dog, probably a stray, curious breed.}
{100}{}{Brahmin}
{101}{}{Two-headed mutant cow.}
{110}{}{Rodent}
{111}{}{The most ordinary big rodent.}
{120}{}{Mantis}
{121}{}{A terribly annoying creature.}
{130}{}{The oldest}
{140}{}{Hakunin}
{150}{}{Mink}
{160}{}{Predatory Flower}
{161}{}{Carnivorous plant.}
{170}{}{Simpatichnyy rab}
{180}{}{Krasivyy rab}
{190}{}{Zdorovaya rabynya}
{200}{}{Zdorovyy rab}
{210}{}{Sil'naya rabynya}
{220}{}{Sil'nyy rab}
{230}{}{Boyevaya rabynya}
{240}{}{Boyevoy rab}
{250}{}{Umnaya rabynya}
{260}{}{Umnyy rab}
{270}{}{Obychnaya rabynya}
{280}{}{Obychnyy rab}
{290}{}{Anna}
{300}{}{Krutoy bandit}
{310}{}{Krutaya vorovka}
{320}{}{Zhestokiy bandit}
{330}{}{Likhaya razboynitsa}
{340}{}{Provornyy bandit}
{350}{}{Lovkaya potaskukha}
{360}{}{Moshchnyy bandit}
{370}{}{Sterva s pushkoy}
{380}{}{Bandit s pushkoy}
{390}{}{Deshevaya shlyukha}
{400}{}{Krutoy Okhrannik}
{410}{}{Krutaya Okhrannitsa}
{420}{}{Moshchnyy Okhrannik}
{430}{}{Moshchnaya Okhrannitsa}
{440}{}{Lovkiy Okhrannik}
{450}{}{Lovkaya Okhrannitsa}
{460}{}{Okhrannik so stvolom}
{470}{}{Okhrannitsa so stvolom}
{480}{}{Okhrannik s pushkoy}
{490}{}{Okhrannitsa s pushkoy}
{500}{}{Sirota}
{510}{}{Sirota}
{520}{}{Rebenok}
{530}{}{Rebenok}
{540}{}{Beggar}
{550}{}{Beggar}
{560}{}{Bad merchant}
{570}{}{Bad trading}
{580}{}{Regular seller}
{590}{}{Ordinary saleswoman}
{600}{}{Master Merchant}
{610}{}{Craftswoman Merchant}
{620}{}{Wick}
{630}{}{Weak peasant}
{640}{}{Weak peasant woman}
{650}{}{Ordinary peasant}
{660}{}{Ordinary peasant woman}
{670}{}{Strong peasant}
{680}{}{Strong peasant woman}
{690}{}{Weak guard}
{700}{}{Weak Guard}
{710}{}{Weak shooter}
{720}{}{Weak sniper}
{730}{}{Robot Repairman}
{740}{}{Robot repairman type 2}
{750}{}{Robo-Brain}
{760}{}{Flying Eye}
{770}{}{Guard Robot}
{780}{}{Guardian Robot Type 2}
{790}{}{Robo-Brain}
{800}{}{Shallow Raptor}
{810}{}{Cool Lizard}
{820}{}{Wolf}
{821}{}{Cruel and ferocious predatory animal.}
{830}{}{Golden Raptor}
{840}{}{Claw of Death}
{850}{}{Deathclaw Offspring}
{860}{}{Strong Golden Raptor}
{870}{}{Lynette}
{880}{}{Dr. Troy}
{890}{}{John Cassidy}
{900}{}{Gregory}
{910}{}{Citizen}
{920}{}{Citizen}
{930}{}{Rich Citizen}
{940}{}{Rich Citizen}
{950}{}{Trapper}
{960}{}{Trapper}
{970}{}{Sulik}
{980}{}{Maida Buckner}
{990}{}{Torr}
{1000}{}{Lumpy}
{1010}{}{Glowing Ghost}
{1020}{}{Phantom of the Reactor}
{1030}{}{Reactor Guard}
{1040}{}{Zomak}
{1050}{}{Skeeter}
{1060}{}{Rat Brain}
{1070}{}{Lenny}
{1080}{}{Woozie}
{1090}{}{Harold}
{1100}{}{Mole Grizzly}
{1110}{}{Big Mole Grizzly}
{1120}{}{Ratbab}
{1130}{}{Ferocious Ratman}
{1140}{}{Weak Brahmin}
{1141}{}{A mutated two-headed cow.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Mutant Rat}
{1161}{}{A mutated rat from radiation.}
{1170}{}{Mutated Mole Grizzly}
{1171}{}{Spinning and angry mole-grizzly.}
{1180}{}{Mutated Rat Boar}
{1181}{}{Heavily starving from a mutation monster.}
{1190}{}{Super Mutant}
{1200}{}{Inflated mutant}
{1210}{}{Cupronickel}
{1220}{}{Íero Andro (don't use)}
{1230}{}{Íero Andro (don't use)}
{1240}{}{Íero Male (don't use)}
{1250}{}{Íero Female (don't use)}
{1260}{}{Íero Male (don't use)}
{1270}{}{Íero Female (don't use)}
{1280}{}{Íero Male (don't use)}
{1290}{}{Íero Female (don't use)}
{1300}{}{Íero Male (don't use)}
{1310}{}{Íero Female (don't use)}
{1320}{}{Íero Male (don't use)}
{1330}{}{Íero Female (don't use)}
{1340}{}{City Guardsman}
{1350}{}{City Guardsman}
{1360}{}{Kiberdog}
{1370}{}{NCR Guard}
{1380}{}{NCR Guard}
{1390}{}{NCR Policeman}
{1400}{}{Slave Watchman}
{1410}{}{Taskmaster}
{1420}{}{Great Trader}
{1430}{}{Great Trader}
{1440}{}{Tandi}
{1450}{}{Merk}
{1460}{}{Ratch}
{1470}{}{Skiter}
{1480}{}{Mayki}
{1490}{}{NCR Barman}
{1500}{}{Storeowner}
{1510}{}{Gruntar}
{1520}{}{Goris}
{1530}{}{Mole Grizzly}
{1540}{}{Mole Grizzly}
{1550}{}{Mole Grizzly}
{1560}{}{Mole Grizzly}
{1570}{}{Mole Grizzly}
{1580}{}{Mole Grizzly}
{1590}{}{Normal Ghost}
{1600}{}{Miron}
{1610}{}{Markus}
{1620}{}{Dr. Jones}
{1630}{}{Devin}
{1640}{}{Miriya}
{1650}{}{Laddy}
{1660}{}{Rondo}
{1670}{}{Apprentice}
{1680}{}{Journeyman}
{1690}{}{Apprentice}
{1700}{}{Bouncer}
{1710}{}{Bouncer}
{1720}{}{Weak mr. Handy}
{1730}{}{Normal Glowing}
{1740}{}{Gift}
{1750}{}{Dalia}
{1760}{}{Gordon}
{1770}{}{test (don't use)}
{1780}{}{Phantom of the Reactor}
{1790}{}{Ordinary ghost}
{1800}{}{Matt}
{1810}{}{Commander of the Hunters}
{1820}{}{Bandit Hunter}
{1830}{}{Commander of the Hunters}
{1840}{}{Bandit Hunter}
{1850}{}{Bandit Hunter}
{1860}{}{Commander of the Hunters}
{1870}{}{Bandit Hunter}
{1880}{}{Bandit Hunter}
{1890}{}{Commander of the Hunters}
{1900}{}{Bandit Hunter}
{1910}{}{Bess}
{1911}{}{Two-headed mutated cow.}
{1920}{}{Baltas}
{1930}{}{Grisham}
{1940}{}{Phil}
{1950}{}{Chicken}
{1960}{}{Carl}
{1970}{}{Johnny}
{1980}{}{Joe}
{1990}{}{Zeke}
{2000}{}{The Butcher}
{2010}{}{Pitti}
{2020}{}{Tribal Warrior}
{2030}{}{Warrior of the tribe}
{2040}{}{Cannibal}
{2050}{}{Ogre}
{2060}{}{Holy husband}
{2070}{}{Holy woman}
{2080}{}{Nomad}
{2090}{}{Nomad}
{2100}{}{Nomad}
{2110}{}{Nomad}
{2120}{}{Killer}
{2130}{}{Killer}
{2140}{}{Peasant}
{2150}{}{Peasant}
{2160}{}{Mantis}
{2170}{}{Slaveholder}
{2180}{}{Slave-owner}
{2190}{}{Wild Brahmin}
{2200}{}{Migrant}
{2210}{}{Relocation}
{2220}{}{Patrol Cities}
{2230}{}{Patrol City}
{2240}{}{Strong Slaveowner}
{2250}{}{Strong Slaveowner}
{2260}{}{Choknutyy}
{2270}{}{Maroder}
{2280}{}{Choknutyy iz Glou}
{2290}{}{Maroder iz Glou}
{2300}{}{Rybak}
{2310}{}{Rybachka}
{2320}{}{Dikar'}
{2330}{}{Dikarka}
{2340}{}{Samogonshchik}
{2350}{}{Samogonshchitsa}
{2360}{}{Artel'shchik}
{2370}{}{Artel'shchitsa}
{2380}{}{Reyder}
{2390}{}{Reydersha}
{2400}{}{Ognedyshashchiy yashcher}
{2410}{}{Krutoy ognedyshashchiy yashcher}
{2420}{}{Inoplanetyanin}
{2430}{}{Chuzhoy}
{2440}{}{Melkiy sil'nyy Kogot' Smerti}
{2450}{}{Zlobnyy Kogot' Smerti}
{2460}{}{Letatel'}
{2470}{}{Podlyy Letatel'}
{2480}{}{Psevdo-kentavr}
{2490}{}{Kentavr Apdayka}
{2500}{}{Patrul'nyy ANKLAVA}
{2510}{}{Patrul'naya ANKLAVA}
{2520}{}{Sabotazhnik}
{2530}{}{Sabotazhnitsa}
{2540}{}{Nayemnik}
{2550}{}{Nayemnitsa}
{2560}{}{Nightkin}
{2570}{}{Powerful Nightkin}
{2580}{}{Cool Ghost}
{2590}{}{Mafiosi}
{2600}{}{Yakuza}
{2610}{}{NCR Ranger}
{2620}{}{NCR Ranger}
{2630}{}{Marauder}
{2640}{}{Marauder}
{2650}{}{Pretty Lloyd}
{2660}{}{Toothy Rodent}
{2670}{}{Resident of the 13th}
{2680}{}{Resident of the 13th}
{2690}{}{Guardian of the Bridge}
{2700}{}{Mysterious Stranger}
{2710}{}{Mysterious Stranger}
{2720}{}{Hakesville}
{2730}{}{Big Jesus Mordino}
{2740}{}{Dumar}
{2750}{}{Mother of the Deathclaws}
{2760}{}{Dragon}
{2770}{}{Lo Pan}
{2780}{}{Hubologist}
{2790}{}{Hubologist}
{2800}{}{Unidentified Person}
{2810}{}{Unidentified Person}
{2820}{}{Unidentified Person}
{2830}{}{Unidentified Person}
{2840}{}{Unidentified Person}
{2850}{}{Unidentified Person}
{2860}{}{Unidentified Person}
{2870}{}{Unidentified Person}
{2880}{}{Presidential Super Agent}
{2890}{}{Deathclaw Egg}
{2900}{}{Metzger}
{2910}{}{GUARDIAN ANCLAW}
{2920}{}{GUARDIAN ANCLAW}
{2930}{}{President}
{2940}{}{Vice President}
{2950}{}{Technician}
{2960}{}{Badger}
{2970}{}{Dr. Fong}
{2980}{}{Child}
{2990}{}{Child}
{3000}{}{Weapon Seller}
{3010}{}{Laboratory Assistant Shea}
{3020}{}{Guard Shi}
{3030}{}{Peasant Shi}
{3040}{}{Peasant Shea}
{3050}{}{Peasant Lo Pan}
{3060}{}{Peasant Woman Lo Pan}
{3070}{}{Docker}
{3080}{}{Shea Merchant}
{3090}{}{Kicks}
{3100}{}{Rat}
{3110}{}{Mantis}
{3120}{}{Ant}
{3130}{}{Mole rat}
{3140}{}{Mole of Grizzly}
{3150}{}{Mole rat mutant}
{3160}{}{Regular gecko}
{3170}{}{Golden gecko}
{3180}{}{Dog}
{3190}{}{Scorpio}
{3200}{}{Greater Scorpion}
{3210}{}{Brahmin}
{3220}{}{Carnivorous plant}
{3230}{}{Alien}
{3240}{}{Little Death Claw}
{3250}{}{Claw of Death}
{3260}{}{Gray Deathclaw}
{3270}{}{Fire-breathing gecko}
{3280}{}{Pseudo-Centaur}
{3290}{}{Flying}
{3300}{}{Swamp}
{3310}{}{rat}
{3320}{}{rat}
{3330}{}{rat}
{3340}{}{rat}
{3350}{}{The Ripper}
{3360}{}{The Ripper}
{3370}{}{Bandit}
{3380}{}{Bandit}
{3390}{}{Marauder}
{3400}{}{Raider}
{3410}{}{Raider}
{3420}{}{Slaver}
{3430}{}{Marauder}
{3440}{}{Raider}
{3450}{}{Raider}
{3460}{}{Traveler}
{3470}{}{Ghoul}
{3480}{}{Ghoul}
{3490}{}{Supermutant}
{3500}{}{Boy}
{3510}{}{Girl}
{3520}{}{Resident}
{3530}{}{Resident}
{3540}{}{Resident}
{3550}{}{Resident}
{3560}{}{Resident}
{3570}{}{Resident}
{3580}{}{Resident}
{3590}{}{Punk}
{3600}{}{Butcher}
{3610}{}{Type in a hoodie}
{3620}{}{Poor}
{3630}{}{Bouncer}
{3640}{}{Resident}
{3650}{}{Woman}
{3660}{}{Girl}
{3670}{}{Prostitute}
{3680}{}{Woman}
{3690}{}{Man in a suit}
{3700}{}{Guard}
{3710}{}{Sentinel}
{3720}{}{Guard}
{3730}{}{Sentinel}
{3740}{}{Guard}
{3750}{}{Vic - Stage 3}
{3760}{}{Vic - Stage 4}
{3770}{}{Vic - Stage 5}
{3780}{}{Vic - Stage 6}
{3790}{}{Robo-Brain - Chimpanzee}
{3800}{}{Robo-Brain - Abnormal}
{3810}{}{Robo-Brain - Man}
{3820}{}{Ant}
{3830}{}{Cool Ant}
{3840}{}{Pariah}
{3850}{}{Zurak}
{3860}{}{Imbot}
{3870}{}{Jimmy}
{3880}{}{Weyungh}
{3890}{}{Herb}
{3900}{}{Lupal}
{3910}{}{Job}
{3920}{}{Smitty}
{3930}{}{Roubaix}
{3940}{}{Master Krall}
{3950}{}{Ziggy}
{3960}{}{Master Kung}
{3970}{}{John Bishop}
{3980}{}{Angela Bishop}
{3990}{}{Mrs. Bishop}
{4000}{}{Bodyguard 1}
{4010}{}{Bodyguard 2}
{4020}{}{Bishop Bruiser 1}
{4030}{}{Bishop Bruiser 2}
{4040}{}{Angry Brahmin}
{4050}{}{Lesser Jesus}
{4050}{}{Lesser Jesus}
{4060}{}{Big Jesus}
{4070}{}{The Mordino Man 1}
{4080}{}{Mordino Man 2}
{4090}{}{Mordino Man 3}
{4100}{}{Bodyguard of Miron 1}
{4110}{}{Bodyguard of Miron 2}
{4120}{}{Mr. Wright}
{4130}{}{Mrs. Wright}
{4140}{}{Chris Wright}
{4150}{}{Kate Wright}
{4160}{}{Son of Wright 1}
{4170}{}{Son of Wright 2}
{4180}{}{Daughter of Wright 1}
{4190}{}{Daughter of Wright 2}
{4200}{}{Mr. Salvatore}
{4210}{}{Mason}
{4220}{}{Bouncer Salvatore 1}
{4230}{}{Bouncer Salvatore 2}
{4240}{}{Ordinary bartender 1}
{4250}{}{Ordinary bartender 2}
{4260}{}{Ordinary bartender 3}
{4270}{}{Boxer 1}
{4280}{}{Boxer 2}
{4290}{}{Boxer 3}
{4300}{}{Boxer 4}
{4310}{}{Mike Matter}
{4320}{}{Holyfield}
{4330}{}{McKneely}
{4340}{}{Baby Stuart}
{4350}{}{Brothers from Corsica}
{4360}{}{Porn Actresses}
{4370}{}{Father Tully}
{4380}{}{Bouncer Casino 1}
{4390}{}{Bouncer Casino 2}
{4400}{}{Croupier}
{4410}{}{Pimp / Drug Dealer1}
{4420}{}{Pimp / Drug Dealer1}
{4430}{}{Pimp / Drug Dealer1}
{4440}{}{Pimp / Drug Dealer1}
{4450}{}{McGee}
{4460}{}{Miss Kitty}
{4470}{}{Common Whore 1}
{4480}{}{Plain Whore 2}
{4490}{}{Jimmy Jay}
{4500}{}{Renesco}
{4510}{}{Scientist}
{4520}{}{Eldridge}
{4530}{}{Algernon}
{4540}{}{Jules}
{4550}{}{Bureaucrat 1}
{4560}{}{Bureaucrat 2}
{4570}{}{Seller 1}
{4580}{}{Seller 2}
{4590}{}{Guard 1}
{4600}{}{Guard 2}
{4610}{}{Guard 3}
{4620}{}{Guard 4}
{4630}{}{Soldier 1}
{4640}{}{Soldier 2}
{4650}{}{Soldier 3}
{4660}{}{Soldier 4}
{4670}{}{Sergeant Stark}
{4680}{}{Dr. Andrew}
{4690}{}{Bartender}
{4700}{}{Gun Tower}
{4701}{}{An automatic defensive device equipped with two plasma guns.}
{4710}{}{K-9 (base)}
{4720}{}{K-9 (stage 1)}
{4730}{}{K-9 (stage 2)}
{4740}{}{K-9 (stage 3)}
{4750}{}{K-9 (stage 4)}
{4760}{}{Regular Cyberdog}
{4770}{}{Vanamingo Egg}
{4780}{}{Guardian of Lo Pan}
{4790}{}{Mergory}
{4800}{}{Auto-gun}
{4810}{}{Special Raptor}
{4820}{}{Deadly}
{4830}{}{Frank Horrigan}
{4831}{}{Super agent and bodyguard of the president}
{4840}{}{Hubologist}
{4850}{}{Hubologist}
{4860}{}{Paladin of the Brotherhood}
{4870}{}{Giant Wasp}
{4880}{}{Mutant Beetle}
{4890}{}{Rebel}
{4900}{}{Dangerous Beetle}
{4910}{}{Engineer}
{4920}{}{Enclave Footman}
{4930}{}{Engineer}
{4940}{}{Soldier of the Brotherhood}
{4950}{}{Saboteur}
{4960}{}{Enclave Soldier}
{4970}{}{Paladin of the Brotherhood}
{4980}{}{Patrol Regulator}
{4990}{}{Bandit}
{5000}{}{Rogue}
{5010}{}{Raider}
{5020}{}{Raider}
{5030}{}{Raider}
{5040}{}{Raider}
{5050}{}{Poisonous Swamp}
{5060}{}{Swamp}
{5070}{}{Soccer ball}
{5080}{}{A man in a white robe}
{5081}{}{He is calm and silent. It seems that for all the time that you spent here he never moved.}
{5090}{}{Deathclaw Egg.}
{5100}{}{Alien's Egg.}
{5110}{}{Fire gecko egg.}
{5120}{}{Mutating trash.}
{5121}{}{Presumably this is what pilots and centaurs look like before they’re born.}
{5130}{}{The leader of the centaurs.}
{5131}{}{Looks like he's guarding the brood.}
{5140}{}{Leader of the fiery lizards.}
{5150}{}{Uterus claw uterus.}
{5180}{}{Helaciton type 1}
{5181}{}{An obscure creature resembling the freaks of the Master of super mutants.}
{5190}{}{Evil Chelacyton Type 1}
{5191}{}{An obscure creature resembling the freaks of the Master of super mutants.}
{5200}{}{Helaciton Type 2}
{5201}{}{An incomprehensible creature resembling the freaks of the Master of super mutants.}
{5210}{}{Evil Chelacyton Type 2}
{5211}{}{An incomprehensible creature resembling the freaks of the Master of super mutants.}
{5220}{}{Helaciton type 3}
{5221}{}{An obscure creature resembling the freaks of the Master of super mutants.}
{5230}{}{Henrietta}
{5231}{}{The skin of this creature resembles one big callus.}
{5240}{}{Healthy ghoul}
{5250}{}{Healthy ghoul}
{5260}{}{Fighter}
{5270}{}{Fighter}
{5280}{}{Fighter}
{5290}{}{Fighter}
{5300}{}{Fighter}
{5310}{}{Fighter}
{5320}{}{Fighter}
{5330}{}{Fighter}
{5340}{}{Healthy Raptor}
{5350}{}{Protectron}
{5360}{}{Jukebox}
{5370}{}{Chimera}
{5380}{}{Yelly}
{5390}{}{Lynn}
{5400}{}{Red Fighter}
{5410}{}{Fighter of the Reds}
{5420}{}{Mutant}
{5421}{}{Large mutated individual.}
{5430}{}{Healthy mutant}
{5431}{}{Large mutated individual.}
{5440}{}{The huge mutant}
{5441}{}{A large, mutated, well-muscled individual.}
{5450}{}{Brahmin}
{5451}{}{Ordinary Brahmin}
{5460}{}{Resident}
{5470}{}{Resident}

#-------------------------------------------------------------------
#FORP - Critters
#-------------------------------------------------------------------
#SANDBOX NPC
{9500}{}{Dubridge Lee Erwin}
{9501}{}{Old, patched in all possible places and strengthened with pieces of raw brahmin skin, the robe encircles the same old man worn by time.}
{9510}{}{Marcus Goldman}
{9511}{}{A bronze tan and cast muscles suggest that this short peasant will give odds to the most remote armwrestlers from Broken Hills.}
{9520}{}{Stephen Barr}
{9521}{}{He constantly chews some sort of chewing tobacco, spitting the lumps that come across to the side, and then, as if nothing had happened, continues to smile, exposing slightly yellowed, but even teeth.}
{9530}{}{Set Sale}
{9531}{}{Definitely a master of his craft, whose carefully selected equipment immediately reveals his occupation in him - a powerful leather sling on his belt, a sharpened spear behind his back and a cute cloak on his shoulders made of tanned leather of a fire-breathing gecko.}
{9540}{}{Andrew Mallon}
{9541}{}{Dressed in caravan rags with a bunch of army unloading fastened on them. It smells like kerosene.}
{9550}{}{Raymond Thayer}
{9551}{}{A belt with a bunch of improvised tools is tightened on the belt of this ancient ghoul. Just like an avid smoker always holds a cigarette in his mouth, he clenches an old, shabby multitool in his hand.}
{9560}{}{Karl Ruger}
{9561}{}{If technical oil was a perfume, this far from smooth-skinned guy would be a trendsetter. Belted on an old blacksmith apron.}
{9570}{}{Samuel Sachs}
{9571}{}{The amazing difference between this ghoul and all the others is the preserved shreds of gray hair on his skin tightly covered head.}
{9580}{}{Vekselberg}
{9581}{}{A ghoul whose prominent feature is the large blacksmith gloves that look very funny on his puny but very sinewy little hands.}
{9590}{}{Chester}
{9591}{}{The monster is so huge that next to it the sky seems to be a small and insignificant element of the landscape.}
{9600}{}{David "Noodles" Aaronson}
{9601}{}{A tall ghoul with a lightweight vest draped over his chest. Constantly looking around, slowly conducting a smoky look around the neighborhood}
{9610}{}{Maximilian "Max" Berkovich}
{9611}{}{A ghoul that still has a nose that gives it a more or less human appearance. Dressed in a dirty jumpsuit, tied up with a belt with various combat gear fastened on it.}
{9620}{}{Patrick "The Simpleton" Goldberg}
{9621}{}{Big-bellied ghoul wearing a straw hat. Chewing something, measured and annoyingly sniffing.}
{9630}{}{Philip "Oblique" Stein}
{9631}{}{A distinctive feature of this ghoul is the strong difference in eye level. The left eye is completely obscured, while the right eye, on the contrary, has retained human expression and depth of thought.}
{9640}{}{Baby Dominic}
{9641}{}{A miniature kid. He could be called a glorious fellow, if not for the fact that this is a vile, disgusting and extremely smelly ghoul.}



#RATS
{10000}{}{Weak Rat}
{10001}{}{Weak rat. Pretty petty creature.}
{10010}{}{Medium Rat}
{10011}{}{The average rat. Big fangs and red eyes.}
{10020}{}{Irradiated rat}
{10021}{}{Irradiated rat. It glows and there is almost no hair on it.}
{10030}{}{The average irradiated rat}
{10031}{}{The average irradiated rat. Saliva flows abundantly from her fangs.}
{10040}{}{Huge rats}
{10041}{}{Huge rats. This wicked rodent can easily jump to your face.}
{10050}{}{Alpha rats}
{10051}{}{Rat alpha. You think the rat said "Splinter."}

#MANTIS
{10300}{}{Pitiful Mantis}
{10301}{}{Pitiful mantis. The creature is trying to hide in a dried bush, pretending to be a leaf.}
{10310}{}{Mantis}
{10311}{}{Mantis. I barely hear how chirping.}
{10320}{}{Huge Mantis}
{10321}{}{The huge mantis. The claws are aggressively pressed to the neck while the triangular head moves randomly.}
{10330}{}{Mantis the leader}
{10331}{}{Mantis the leader. Cold-blooded eyes are fixed on you, very loud and unpleasant chatter.}

#ANTS
{10600}{}{Worker Ant}
{10601}{}{Worker ant. This hard worker was dragging a piece of shit until he noticed you.}
{10610}{}{Ant-soldier}
{10611}{}{Ant-soldier. The antennae point at you, followed by the eyes of a predator.}
{10620}{}{Drone Ant}
{10621}{}{Drone Ant. This hefty ant looks especially nasty and dangerous.}
{10630}{}{Guard Ant}
{10631}{}{Guard Ant. This is an alpha male: its carapace looks very thick and its mouth is huge.}

#SPOREPLANTS
{10900}{}{Carnivorous plant}
{10901}{}{Carnivorous plant. A strange, eyeless mouth rests on a thick stem.}
{10910}{}{A huge predatory plant}
{10911}{}{A huge predatory plant. This flower looks menacing, it is taller than you.}

#BRAHMINS
{11200}{}{Weak Brahmin}
{11201}{}{Weak Brahmin. This brahmin was only a calf until recently.}
{11210}{}{Brahmin}
{11211}{}{Brahmin. Flies fly overhead.}
{11220}{}{Wild Brahmin}
{11221}{}{Wild Brahmin. This skinny brahmin is trembling throughout his body, he mooing loudly.}
{11230}{}{Furious Brahmin}
{11231}{}{Furious Brahmin. This brahmin is darker than the rest of the individuals, he snorts loudly, banging his hoof on the ground.}

#DOGS
{11500}{}{Weak dog}
{11501}{}{Weak dog. It seems like you should kick this dog and it will fall apart.}
{11510}{}{Dog}
{11511}{}{The dog. Common sized mutt.}
{11520}{}{Mother Dog}
{11521}{}{Mother dog. This scarred old dog growls at you.}
{11530}{}{Big dog}
{11531}{}{Big dog. Perhaps this is a wolf who became the leader of a dog pack.}

#WOLFES
{11800}{}{Weak Wolf}
{11801}{}{Weak wolf. It looks no more dangerous than a normal dog.}
{11810}{}{Wolf}
{11811}{}{Wolf. One of the pack.}
{11820}{}{seasoned wolf}
{11821}{}{Seasoned Wolf. His ears are stuck up, he growls.}
{11830}{}{Leader of the pack of wolves}
{11831}{}{The leader of the pack of wolves. This old and big wolf is about to dine with you.}

#PIGRATS
{12100}{}{Pig Rat}
{12101}{}{Pig Rat. It makes sounds that resemble a squeak and grunt in one.}
{12110}{}{Huge Pig Rat}
{12111}{}{A huge pig-rat. If it weren’t for sharp teeth and claws, it would make a great steak.}
{12120}{}{Pig-rat alpha specimen}
{12121}{}{Pig-rat alpha. This thing is a little lower than you, but it already stinks of death.}

#MOLERATS
{12400}{}{Mole rat}
{12401}{}{Mole rat. He dug the ground until he noticed you.}
{12410}{}{Huge Mole rat}
{12411}{}{A huge mole rat. This huge creature growls loudly.}
{12420}{}{Mole rat-leader}
{12421}{}{The mole rat-leader. The leader of the underground pack threatens to sharpen its claws against each other.}

#SILVER GECKOS
{12700}{}{Silver Gecko}
{12701}{}{Silver Gecko. This is a simple small pangolin.}
{12710}{}{Silver predatory gecko}
{12711}{}{Silver predatory gecko. This specimen is more sinewy than small dinosaurs.}
{12720}{}{Large Silver Gecko}
{12721}{}{Large silver gecko. This big gecko loudly clangs with sharp teeth.}
{12730}{}{Silver Gecko Alpha}
{12731}{}{Silver Gecko Alpha. This is the leader of the pack, he calmly bares his fangs.}

#GOLDEN GECKOS
{13000}{}{Golden Gecko}
{13001}{}{Golden Gecko. Wow, luxurious hide.}
{13010}{}{Large Golden Gecko}
{13011}{}{Large golden gecko. This big gecko loudly clangs with sharp teeth.}
{13020}{}{Golden Gecko Alpha}
{13021}{}{Golden Gecko Alpha. This is the leader of the pack, he calmly bares his fangs.}

#FIREGECKOS
{13300}{}{Fire gecko}
{13301}{}{Fiery gecko. A faint smoke comes out of the nostrils.}
{13310}{}{Fire Gecko Alpha}
{13311}{}{Fiery gecko alpha. The creature is very dangerous, it seems only a nut will hunt them.}

#SMALLSCROPS
{13600}{}{Shallow Radcorspion}
{13601}{}{Shallow Radcorspion. Noticing you, he scrambles out of the sand shelter.}

#BIGSCORPS
{13900}{}{Radscorpion}
{13901}{}{Radcorspion. Knocks with claws and twists its tail.}
{13910}{}{Inveterate Radscorpion}
{13911}{}{Inveterate scorpion. This specimen is larger than ordinary adult scorpions.}

#BLACKSCORPS
{14200}{}{Small Black Radcorscorpion}
{14201}{}{Small black radcorporium. This is a small but dangerous scorpion.}
{14210}{}{Black Radcorspion}
{14211}{}{Black Radcorspion. Pointing his black tail at you.}

#DEATHCLAWS
{14500}{}{Death Claw Cub}
{14501}{}{Death Claw Cub. Slightly shorter than you, but certainly dangerous!}
{14510}{}{Young Deathclaw}
{14511}{}{Young Deathclaw. He has light hair and small horns.}
{14520}{}{Deathclaw}
{14521}{}{Big Claw of Death. With his large paws down, this Claw sniffs.}
{14530}{}{Claw of death alpha-individual}
{14531}{}{Claw of death an alpha individual. This is the leader of the pack, he is very muscular and with curves, big horns.}
{14540}{}{Deathclaw Hunter}
{14541}{}{Deathclaw hunter. This creature is gray, it is much more dangerous than the strongest claw of death in a pack.}

#SWAMPLURKERS
{14800}{}{Weak Swamp}
{14801}{}{Weak swamp. Water drains from this small swamp.}
{14810}{}{Swamp}
{14811}{}{Swamp. Terrible creature from the deep sea or swamp.}
{14820}{}{Leader of the Marshland}
{14821}{}{The leader of the swamps. This is a very large swamp, its skin is stronger than any leather armor.}

#ALIENS
{15100}{}{Strange Egg}
{15101}{}{A strange egg. You are not sure you know whose egg it is.}
{15110}{}{Vanamingo}
{15111}{}{Vanamingo. This creature has neither eyes nor fingers. A terrible sight.}
{15120}{}{Large Vanamingo}
{15121}{}{Large Vanamingo. The beast growls terribly, waving its vile paws.}

#MOTERALIENS
{15400}{}{Uterus of Vanamingo}
{15401}{}{Uterus of Vanamingo. Mucus flows from the mouth of a hefty vanamingo, and the shiny skin has a dark gray hue.}

#FLOATERS
{15700}{}{Small pilot}
{15701}{}{Small pilot. The same, but only smaller, you got out of your ass last week.}
{15710}{}{Flying}
{15711}{}{Flying. It floats in the air, emitting harmful gases through the pores of the subcutaneous sac.}
{15720}{}{The Ugly Flyer}
{15721}{}{The ugly flyer. He stinks disgustingly, and his front mouths are full of mucus.}
{15730}{}{Leader of the Pilots}
{15731}{}{The leader of the pilots. This huge pilot is crawling on the ground, swinging his wet ganglia.}

#CENTAURS
{16000}{}{Small Centaur}
{16001}{}{Small Centaur. This vile baby barely drags himself on the ground in six human hands.}
{16010}{}{Centaur.}
{16011}{}{Centaur. Muddy mucus flows from a long tentacular tongue.}
{16020}{}{The Ugly Centaur}
{16021}{}{The Ugly Centaur. For some reason, the dog’s head barks at the man’s head.}
{16030}{}{Alpha Centaur}
{16031}{}{Alpha Kentwar. This huge centaur rests on ten human hands and has three heads.}

#PRIMITIVES
{16300}{}{Skinny Savage}
{16301}{}{Skinny Savage. This savage didn't seem to eat for a very long time.}
{16310}{}{Skinny Savage}
{16311}{}{Skinny savage. She looks like a skinned skeleton. Well, or for a fresh ghoul.}
{16320}{}{The Dirty Savage}
{16321}{}{The dirty savage. This one seems to dig in the ground all day.}
{16330}{}{Smeared Wild}
{16331}{}{The smeared savage. Perhaps the clay on her face and hair is a decoration.}
{16340}{}{Tribal Elder}
{16341}{}{Elder of the tribe. He seems to be one of the leaders of the tribe.}
{16350}{}{Tribal Elder}
{16351}{}{Elder of the tribe. He seems to be one of the leaders of the tribe.}
{16360}{}{Shaman of the tribe}
{16361}{}{Shaman of the tribe. Many amulets and a drunken appearance hint to you that you have a strong sorcerer in front of you.}
{16370}{}{Savage hunter}
{16371}{}{Savage hunter. Have you ever seen a trapper without pants? There he is.}
{16380}{}{Savage Huntress}
{16381}{}{Savage huntress. It is not as accessible as it seems.}
{16390}{}{Savage warrior}
{16391}{}{Savage warrior. Strong and agile, he will defend his tribe until the last breath.}
{16400}{}{Savage Warrior}
{16401}{}{Savage warrior. War paint, wild grin and bare boobs, all right.}

#CANNIBALS & RIPPERS
{16600}{}{The Vile Eater}
{16601}{}{A vile eater. He looks at you with anger and hunger. Quickly steps in your direction, sniffing loudly and drooling.}
{16610}{}{Dirty ogre}
{16611}{}{The dirty cannibal. She looks at you with a hungry look. Her hair is tousled, some teeth are missing.}
{16620}{}{Bearded eater}
{16621}{}{The bearded cannibal. He is looking at you eagerly. This fag is going to eat you!}
{16630}{}{Crazy ogre}
{16631}{}{Crazy cannibal. His gaze runs around. He bites his teeth, stomping on the ground.}
{16640}{}{Eater Farmer}
{16641}{}{Eater farmer. He looks at you with hungry eyes. His jumpsuit is stained with blood, and his straw hat is bitten by someone.}
{16650}{}{The Hungry Eater}
{16651}{}{The Hungry Eater. He looks at you with hungry eyes. Saliva flows from his mouth, and his ribs are visible under the skin.}
{16660}{}{Slave-cannibal}
{16661}{}{Slave-cannibal. She looks at you with a hungry look. A broken collar hangs around her neck.}
{16670}{}{Bald Cannibal}
{16671}{}{The bald cannibal. He is looking at you viciously. Steam comes from his red top, apparently there he’s a piece of your leg and will fry.}
{16680}{}{The farmer-cannibal}
{16681}{}{The farmer-cannibal. She looks at you with a hungry look. MEAT is written on her apron with blood.}
{16690}{}{Strange guy}
{16691}{}{Strange guy. His face is hidden by a hood. The ragged robe has patches of dried blood.}
{16700}{}{Chinese cannibal}
{16701}{}{Chinese cannibal. He looks at you like fresh fish. Knives of different sizes are attached to the vest and pants.}
{16710}{}{Strange nigga}
{16711}{}{Strange nigga. He wheezes softly. Blood flows from his mouth, and for some reason the pupils rolled up.}
{16720}{}{Healthy Cannibal}
{16721}{}{Healthy cannibal. He is looking at you, drooling bloody. He seems to even growl.}
{16730}{}{Pale Cannibal}
{16731}{}{The pale cannibal. He looks at you with hungry eyes. His skin is almost white, very strange for the inhabitant of the Wasteland.}
{16740}{}{The mutated cannibal}
{16741}{}{The mutated cannibal. He looks at you with a hungry look. Half of his head rots alive, the other half is full of purulent growths.}
{16750}{}{Petty Cannibal}
{16751}{}{Small cannibal. He looks at you with hungry eyes. This little fag seems to feed on humanity.}
{16760}{}{Pretty cannibal}
{16761}{}{Pretty cannibal. She looks at you with a hungry look. Her clothes are already completely worn out, which is why her large breasts are clearly visible.}
{16770}{}{Fat Eater}
{16771}{}{Fat cannibal. She looks at you with an ominous smile. Her clothes are sewn from different skins, and mysterious symbols from blood are painted on them.}
{16780}{}{Elderly cannibal}
{16781}{}{Elderly cannibal. He looks at you calmly. The gray-haired old man chews his own lips.}
{16790}{}{Ripper Stalker}
{16791}{}{The Ripper Stalker. It seems like he needs you alive.}
{16800}{}{Hunting the Rippers}
{16801}{}{Hunting the Rippers. Agile and fast. She doesn't seem to mind having fun with you.}
{16810}{}{Slayer Ripper}
{16811}{}{The Slayer Ripper. Strongly built. His mouth twists into a carnivorous grin.}
{16820}{}{Slayer Ripper}
{16821}{}{The Slayer Ripper. Strong woman. Her face is stained with blood. Apparently this is not her blood.}
{16830}{}{Ripper-flayer}
{16831}{}{Ripper-flayer. Aggressive Rippers.}
{16840}{}{Ripper-flayer}
{16841}{}{Ripper-flayer. Half-naked woman. Looks at you predatoryly.}
{16850}{}{Ripper Warrior}
{16851}{}{The Ripper Warrior. His torso is hung with decorations from the bones of defeated enemies.}
{16860}{}{Ripper Warrior}
{16861}{}{The Ripper Warrior. Her eyes are clouded by a thirst for blood.}
{16870}{}{The Ripper Priest}
{16871}{}{The Ripper Priest. A necklace made of phalanges of human fingers adorns his neck.}
{16880}{}{Patriarch of the Rippers}
{16881}{}{Patriarch of the Rippers. Tall and domineering man. Ritual scars adorn his face. The rest of the rippers look at him as a living god.}
{16890}{}{The Ripper Matriarch}
{16891}{}{The Ripper Matriarch. Strongly folded woman in clothes made of human skin. Other rippers respectfully lower their eyes in her presence.}

#GANGS
{16900}{}{Thump}
{16901}{}{Thump. Addict, his hands are shaking and his eyes are running.}
{16910}{}{Addict}
{16911}{}{Addict. Judging by her absent glance, she had long been ready for anything for the sake of the dose.}
{16920}{}{Dregs}
{16921}{}{Dregs. A rascal who is trying to live at the expense of others.}
{16930}{}{Shmara}
{16931}{}{Shmara. Lack of principles is her main principle!}
{16940}{}{Petty punks}
{16941}{}{Petty punks. He does not hesitate to rob you of your wallet, but for one life.}
{16950}{}{Petty punks}
{16951}{}{Petty punks. She has long been accustomed to playing by the rules of the wasteland.}
{16960}{}{Dodger}
{16961}{}{Dodger. Petty thief.}
{16970}{}{Cheat}
{16971}{}{Cheating. Ostra on the tongue. And sharpening too sharp!}
{16980}{}{Bastard}
{16981}{}{Bastard. Ready to release your guts in a couple of caps.}
{16990}{}{Robber}
{16991}{}{Robber. Unprincipled and very dangerous.}
{17000}{}{Scumbag}
{17001}{}{Scumbag. Apparently this psychopath is about to shed your blood!}
{17010}{}{Bounced}
{17011}{}{Beat back. For him, cut the throat of a child as two fingers piss.}
{17020}{}{Authority}
{17021}{}{Authority. Local authority. Looks at you like shit.}
{17030}{}{Authority}
{17031}{}{Authority. Local authority. Looks at you like shit.}

#RAIDERS
{17200}{}{Raider scavenger}
{17201}{}{Raider scavenger. You would be confused with a vagrant if it weren’t for a weapon aimed at you.}
{17210}{}{Raider scavenger}
{17211}{}{Raider scavenger. You would be confused with a vagrant if it weren’t for a weapon aimed at you.}
{17220}{}{Raider crazy}
{17221}{}{Raider crazy. The person who has been frostbitten tightly.}
{17230}{}{Raider psycho}
{17231}{}{Raider crazy. The person who has been frostbitten tightly.}
{17240}{}{Kamikaze Raider}
{17241}{}{Kamikaze Raider. He directly asks you to shoot him.}
{17250}{}{Kamikaze Raider}
{17251}{}{Kamikaze Raider. He directly asks you to shoot him.}
{17260}{}{Raider smashed}
{17261}{}{The raider was a smash. Do not fall under his blows.}
{17270}{}{Raider smashed}
{17271}{}{The raider was a smash. Do not fall under his blows.}
{17280}{}{Raider Raider}
{17281}{}{Raider Raider. Raider or Raider? What's the difference!}
{17290}{}{Raider Raider}
{17291}{}{Raider Raider. Raider or Raider? What's the difference!}
{17300}{}{Shooter Raider}
{17301}{}{Raider shooter. You're on the fly.}
{17310}{}{Raider shooter}
{17311}{}{Raider shooter. You're on the fly.}
{17320}{}{Raider madman}
{17321}{}{Raider is crazy. This is eager for battle in the forefront. Looks very dangerous.}
{17330}{}{Raider madman}
{17331}{}{Raider is crazy. This is eager for battle in the forefront. Looks very dangerous.}
{17340}{}{Elite Raider}
{17341}{}{Elite Raider. The elite of their gang.}
{17350}{}{Elite Raider}
{17351}{}{Elite Raider. The elite of their gang.}
{17360}{}{Raider Professional}
{17361}{}{Raider is a professional. These usually have multiple battles behind them.}
{17370}{}{Raider Professional}
{17371}{}{Raider is a professional. These usually have multiple battles behind them.}
{17380}{}{Raider Professional}
{17381}{}{Raider is a professional. These usually have multiple battles behind them.}
{17390}{}{Legendary Raider Leader}
{17391}{}{Legendary Raider Leader. One of the representatives of the legendary gang "Khana". He is very strong.}

#SLAVERS
{17500}{}{Slave Newbie}
{17501}{}{The slave trader is a novice. Young guy with a stigma stamp on his forehead. Twitchy bastard who wants to prove himself.}
{17510}{}{Novice Slave Trader}
{17511}{}{The slave trader is a novice. A young girl with the stigma of a slaver on her forehead. Fucking rubbish that wants to prove itself.}
{17520}{}{Slave Trader Bull}
{17521}{}{Slave trader. Strong man with the stigma of a slaver on his forehead. He cheekily examined you, as if you were asking the price}
{17530}{}{Slave Trader}
{17531}{}{Slave trader. Strong man with the stigma of a slaver on his forehead. Dirty hands, a bad conscience and a predatory look give him a “good businessman."}
{17540}{}{Slaver of the shooter}
{17541}{}{Slaver of the shooter. Apparently this is one of the "beaters" of slave traders. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17550}{}{Slaver of the shooter}
{17551}{}{Slaver of the shooter. Apparently this is one of the "beaters" of slave traders. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17560}{}{Slave Veteran}
{17561}{}{The slaver is a veteran. Experienced thug with the stamp of a slaver on his forehead. It seems that he knows the price of everyone and you would not want to be in the zone of his "interest".}
{17570}{}{Slave Merchant Veteran}
{17571}{}{The slaver is a veteran. Experienced robber with the stamp of a slaver on his forehead. It seems that she knows the price of everyone and you would not want to be in the zone of her "interest".}
{17580}{}{Chief of the Slave Traders}
{17581}{}{Chief of the slave traders. Good looking businessman with a slave stamp on his forehead. He knows a lot about “labor collectives” and the motivation system.}
{17590}{}{Chief of slave traders}
{17591}{}{Chief of the slave traders. A stately-looking man with the stigma of a slaver on his forehead. This "Black Lord" broke a lot of fates.}

#CARAVANS
{17800}{}{Random companion}
{17801}{}{Random companion. You have a feeling that this person shouldn’t be here at all.}
{17810}{}{Random companion}
{17811}{}{Random companion. You have a feeling that this person shouldn’t be here at all.}
{17820}{}{Caravan guard newbie}
{17821}{}{The caravan guard is a beginner. Explicitly feeling insecure.}
{17830}{}{Caravan guard newbie}
{17831}{}{The guard of the caravan is a beginner. Explicitly feeling insecure.}
{17840}{}{Healthy Caravan Guard}
{17841}{}{Healthy guard of the caravan. Yes, this is a real closet!}
{17850}{}{Healthy Caravan Guard}
{17851}{}{Healthy guard of the caravan. Yes, this is a real closet!}
{17860}{}{Caravan Guard Veteran}
{17861}{}{The guard of the caravan is a veteran. An experienced person can be seen right away.}
{17870}{}{Caravan Guard Veteran}
{17871}{}{The guard of the caravan is a veteran. An experienced person can be seen right away.}
{17880}{}{Guard of the caravan shooter}
{17881}{}{The guard of the caravan of shooters. Squinting at the area.}
{17890}{}{Guard of the caravan shooter}
{17891}{}{The guard of the caravan of shooters. Squinting at the area.}
{17900}{}{Caravaner}
{17901}{}{Caravaner. This person seems to be managing everything here.}
{17910}{}{Caravaner}
{17911}{}{Caravaner. This person seems to be managing everything here.}

#STRANGERS
{18100}{}{Homeless}
{18101}{}{Homeless. Smelly tramp, which is full of wasteland. Looks bruised, behaving nervously.}
{18110}{}{Homeless}
{18111}{}{Homeless. Dirty woman with a clogged look. It is full of misfortune.}
{18120}{}{Scavenger}
{18121}{}{Scavenger. The usual collector. He jerks around, looking for something to profit from.}
{18130}{}{The Scavenger}
{18131}{}{The scavenger. Typical gatherer. She jerks around, looking for something to profit from.}
{18140}{}{Garbage}
{18141}{}{Dump. An embittered ragger, which is full in any slum. He’s busy with something and tries not to look at you.}
{18150}{}{Garbage}
{18151}{}{Dump. An embittered rag, which is full in any slum. She’s busy with something and tries not to look at you.}
{18160}{}{Hunter}
{18161}{}{The Hunter. An experienced trapper with a weathered face and a characteristic squint.}
{18170}{}{Huntress}
{18171}{}{Huntress. An experienced trapper with a weathered face and a characteristic squint.}
{18180}{}{Tramp}
{18181}{}{Tramp. The usual traveler from the wasteland. I don’t understand what places he came from, but judging by the torn burlap on it, the journey was long.}
{18190}{}{Wanderer}
{18191}{}{Wandering. The usual traveler from the wasteland. Not to understand where she came from, but judging by the torn burlap on her, the journey was a long one.}
{18200}{}{Rogue}
{18201}{}{Outcast. Smelly tramp, which is full of wasteland. This one looks sick, or just a freak.}
{18210}{}{Rogue}
{18211}{}{Outcast. Decrepit old man living his age. Sorry sight.}
{18220}{}{Lawyer}
{18221}{}{Lawyer. An experienced mercenary in strong ammunition. Armed and apparently dangerous.}
{18230}{}{Lawyer}
{18231}{}{Lawyer. An experienced mercenary in strong ammunition. Armed and apparently dangerous.}

#GHOULS
{18400}{}{The frail ghoul}
{18401}{}{The frail ghoul. Skin and bones. Literally.}
{18410}{}{The frail ghoul}
{18411}{}{The frail ghoul. Skin and bones. Literally.}
{18420}{}{Frozen ghoul}
{18421}{}{Frozen ghoul. From the fallen off pieces of leather, it would be possible to sew a bag.}
{18430}{}{Frozen ghoul}
{18431}{}{Frozen ghoul. From the fallen off pieces of leather, it would be possible to sew a bag.}
{18440}{}{Vile ghoul}
{18441}{}{The vile ghoul. It seems that one species will vomit you now.}
{18450}{}{Vile ghoul}
{18451}{}{The vile ghoul. It seems that one species will vomit you now.}
{18460}{}{Dirty ghoul}
{18461}{}{A dirty ghoul. The dirt adhering to the walking skeleton made it less noticeable.}
{18470}{}{Dirty ghoul}
{18471}{}{A dirty ghoul. The dirt adhering to the walking skeleton made it less noticeable.}
{18480}{}{Disgusting ghoul}
{18481}{}{Disgusting ghoul. This can only be seen through the scope.}
{18490}{}{Disgusting ghoul}
{18491}{}{Disgusting ghoul. This can only be seen through the scope.}
{18500}{}{Rotting ghoul}
{18501}{}{Rotting ghoul. Nothing more disgusting is your nose ... sniffing?}
{18510}{}{Rotting ghoul}
{18511}{}{Rotting ghoul. Nothing more disgusting is your nose ... sniffing?}
{18520}{}{Luminous ghoul}
{18521}{}{Glowing ghoul. How about a couple extra RAD?}
{18530}{}{Luminous ghoul}
{18531}{}{Glowing ghoul. How about a couple extra RAD?}
{18540}{}{Fast ghoul}
{18541}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}
{18550}{}{Fast ghoul}
{18551}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}
{18560}{}{Fast ghoul}
{18561}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}
{18570}{}{Fast ghoul}
{18571}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}
{18580}{}{Fast ghoul}
{18581}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}
{18590}{}{Fast ghoul}
{18591}{}{Fast ghoul. It doesn't seem like such a slow wreck like the others.}

#SUPERMUTANTS
{18700}{}{Supermutant}
{18701}{}{Supermutant. A huge piece of muscle. These creatures do not have much reason to be considered reasonable.}
{18710}{}{Supermutant}
{18711}{}{Supermutant. The living horror of the wasteland. Dumb, angry, stinks.}
{18720}{}{Supermutant Thug}
{18721}{}{The super mutant was a smash. A huge carcass consisting of muscles, malice and light armor - looks dangerous. He looks around with a dull look for what can be broken.}
{18730}{}{Supermutant Thug}
{18731}{}{The super mutant is a smug. The creature impatiently stomps on the spot. She wants to beat, break, and crush, but that’s not all.}
{18740}{}{Supermutant Berserker}
{18741}{}{Supermutant berserker. The body of this creature is covered with hematomas. It seemed to be completely insane with pain and rage.}
{18750}{}{Supermutant Berserker}
{18751}{}{Supermutant Berserker. His whole body is covered in scars. This crazy creature emerged victorious from many battles, it is very dangerous.}
{18760}{}{Super mutant master}
{18761}{}{Super mutant master. The creature is covered in armor made of rusty metal sheets and chains. The armor looks wild and rattles when moving, but it looks like the monster really likes it}
{18770}{}{Super mutant master}
{18771}{}{Super mutant master. A chained monster looks no smarter than the rest of its species, but feels clearly more important.}
{18780}{}{Shadow}
{18781}{}{Shadow. A huge piece of muscle. This creature has a surprisingly meaningful and piercing look.}
{18790}{}{Shadow}
{18791}{}{Shadow. A huge piece of muscle. This creature has a meaningful and piercing look.}
{18800}{}{Shadow Berserker}
{18801}{}{Shadow berserker. This clever and experienced creature emerged victorious from many battles, it is very dangerous.}
{18810}{}{Shadow Berserker}
{18811}{}{Shadow berserker. This clever and experienced creature emerged victorious from many battles, it is very dangerous.}
{18820}{}{Shadow Master}
{18821}{}{Shadow master. Monster with a smart and calm look. You feel small in front of him not only in height. This creature is the most you could become.}
{18830}{}{Shadow Master}
{18831}{}{Shadow master. Monster with a smart and calm look. You feel small in front of him not only in height. This creature is the most you could become.}
{18840}{}{Shadow Sniper}
{18841}{}{Shadow of a sniper. A clever and cunning creature with refined movements and a huge rifle in his hands.}
{18850}{}{Shadow Sniper}
{18851}{}{Shadow of a sniper. A clever and cunning creature with refined movements and a huge rifle in his hands.}

#ROBOTS
{19000}{}{Robo-Brain}
{19001}{}{Robo-brain. A multipurpose cybernetic organism, the processor of which uses the brain of an animal or person.}
{19010}{}{Roboglaz}
{19011}{}{Roboglaz. Armed soaring robot. As a rule, it carries repair or security functions.}
{19020}{}{Assistant}
{19021}{}{Assistant. A series of home and work robots that is very popular in the pre-war USA.}
{19030}{}{Robot Guard}
{19031}{}{Robot guard. Pre-war combat unit. Has a recognition system "friend or foe." Armed with heavy weapons but lacking mobility.}

#MODOC GUARDS
{19300}{}{Guard of Modoc}
{19301}{}{The guard of Modoc. These guys know their stuff.}
{19310}{}{Guard of Modoc}
{19311}{}{The guard of Modoc. These guys know their stuff.}
{19320}{}{Guard of Modoc}
{19321}{}{Guard of Modoc. These guys know their stuff.}
{19330}{}{Guard of Modoc}
{19331}{}{The guard of Modoc. These guys know their stuff.}
{19340}{}{Guard of Modoc}
{19341}{}{Guard of Modoc. These guys know their stuff.}
{19350}{}{Guard of Modoc}
{19351}{}{The guard of Modoc. These guys know their stuff.}
{19360}{}{Guard of Modoc}
{19361}{}{The guard of Modoc. These guys know their stuff.}
{19370}{}{Guard of Modoc}
{19371}{}{Guard of Modoc. These guys know their stuff.}
{19380}{}{Guard of Modoc}
{19381}{}{Guard of Modoc. These guys know their stuff.}
{19390}{}{Guard of Modoc}
{19391}{}{The guard of Modoc. These guys know their stuff.}
{19400}{}{Caravan Guard}
{19401}{}{The caravan guard. Steep, stern, silent. Real pros.}
{19410}{}{Lear}
{19411}{}{Lear. This man won't even miss a fly without documents.}

#FOX'S VILLA
{19600}{}{Strong Slave}
{19601}{}{Strong slave. Strong-looking slave. Want to buy?}
{19610}{}{Strong Slave}
{19611}{}{Strong slave. Strong-looking slave. Want to buy?}
{19620}{}{Strong slave}
{19621}{}{Strong slave. Strong-looking slave. Want to buy?}
{19630}{}{Strong slave}
{19631}{}{Strong slave. Strong-looking slave. Want to buy?}
{19640}{}{Strong slave}
{19641}{}{Strong slave. Strong-looking slave. Want to buy?}
{19650}{}{Strong slave}
{19651}{}{Strong slave. Strong-looking slave. Want to buy?}
{19660}{}{Strong slave}
{19661}{}{Strong slave. Strong-looking slave. This one is classic black.}
{19670}{}{Cool Fox Slaver}
{19671}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19680}{}{Cool Fox slaver}
{19681}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19690}{}{Cool Fox slaver}
{19691}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19700}{}{Cool Fox slaver}
{19701}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19710}{}{Cool Fox Slaver}
{19711}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19720}{}{Cool Fox slaver}
{19721}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19730}{}{Cool Fox slaver}
{19731}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19740}{}{Cool Fox slaver}
{19741}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19750}{}{Cool Fox slaver}
{19751}{}{The cool slaver of Fox. Proudly wears the mark on his forehead.}
{19760}{}{Metzger}
{19761}{}{This is Metzger. He clearly knows a lot about live goods trading.}
{19770}{}{Colonel Fox}
{19771}{}{Mr. Fox is the largest slave owner in these lands.}

#OTHER HUMAN NPC
{19900}{}{Baltas}
{19901}{}{Baltas. Damn strong man, famous hunter.}
{19910}{}{Inveterate Hunter}
{19911}{}{Inveterate hunter. These guys can catch any creature.}
{19920}{}{Inveterate Hunter}
{19921}{}{Inveterate hunter. These guys can catch any creature.}

#POSEYDON NPC
{20000}{}{Immortal John}
{20001}{}{A battered robot with a brain in a flask.}
{20010}{}{Kok}
{20011}{}{Fat sweaty man with a crafty gaze of lustful eyes. He wears an apron and a cook hat.}
{20020}{}{Professor Kevorkian}
{20021}{}{A wrinkled face reads interest, irritation, and tiredness. Wear glasses.}
{20030}{}{Hugo Hog Ruth}
{20031}{}{Mordatious overweight man with a red face.}
{20040}{}{Grave}
{20041}{}{A lean man with a weathered face. Owner of a luxurious horseshoe mustache.}
{20050}{}{Ash Tom}
{20051}{}{The ghoul is completely black, as if woven from mud and ash.}
{20060}{}{Chad}
{20061}{}{A fat, pot-bellied and broad-shouldered man in a bloody apron. Glance does not sparkle with intelligence.}
{20070}{}{Booger}
{20071}{}{A very short young guy.}
{20080}{}{Chog}
{20081}{}{Huge even for a super mutant, a creepy monster.}
{20090}{}{Jesse the Svender Castor}
{20091}{}{A tall hangover brunette with eternal stubble on his face.}
{20100}{}{Sean "Rattle" MarshAl}
{20101}{}{An unusually luminous ghoul.}
{20110}{}{Curtis "The Cowboy" Reidler}
{20111}{}{A young bearded man, in a well-worn jacket and a cowboy hat.}
{20120}{}{Bryce "The Trumpet"}
{20121}{}{A tall, thin man with pale skin. There is no middle finger on the left hand. A metal pipe lies on a belt in a case.}
{20130}{}{Montgomery "Monty" Tonato}
{20131}{}{A young man with a stern and strong-willed expression on his face. A thin white strip is visible on the cheek - a scar from a knife.}
{20140}{}{Gwen Tyler}
{20141}{}{A pretty young girl sparkles with a snow-white smile.}
{20150}{}{Donnie The Cleaver Trajo}
{20151}{}{Tall Mexican with rugged wrinkles and a windy face. Wears an Anchor-style beard.}
{20160}{}{Garfield "Splinter" Nelson}
{20161}{}{A cheerful looking red-haired guy.}
{20170}{}{Nera "Trudy" Argwire}
{20171}{}{Brunette with a cold look.}
{20180}{}{Oliver Iceman Ramy}
{20181}{}{He smiles ironically at you.}
{20190}{}{Charon the Salted Diclane}
{20191}{}{An extremely well-preserved military uniform.}
{20200}{}{Crook Mackenzie}
{20201}{}{A thin, long-armed, long-legged guy with dirty corn-colored hair.}
{20210}{}{Sunshine "Sunny" 209}
{20211}{}{It looks dangerous if you don’t know what it is and why, it’s better not to touch it.}
{20220}{}{Molly Bloom}
{20221}{}{Very sexy, attractive girl.}
{20230}{}{Diamond Page Dallas}
{20231}{}{Big man of age. His curly hair was covered in gray hair for a long time.}
{20240}{}{Murphy's "Old" MacDill}
{20241}{}{A lush ginger beard, gray whiskey and a clearly taut smile on his face.}
{20250}{}{Bam-Bam Bigelow}
{20251}{}{Short-cut and smooth-shaven chunky man.}
{20260}{}{Brody Javis}
{20261}{}{The glasses are tied with electrical tape to the skull, looking cunningly and arrogant.}
{20270}{}{Turk}
{20271}{}{An unshaven, short-haired sullen dude actively inviting you to trade and purchase "unique gizmos."}
{20280}{}{Gary}
{20281}{}{A jerky look, a torn robe, a large backpack behind him, his hands are constantly black.}
{20290}{}{Douglas "Shishak"}
{20291}{}{A neat-looking elderly man in a pre-war suit, wears glasses and a pile.}
{20300}{}{Winnie the Wide Fletcher}
{20301}{}{A wide-eyed babe, looking straight into the eyes, a heavy voice and a protruding lower lip.}
{20310}{}{Burger Chuck}
{20311}{}{A black man in a dark open coat and hat, a man of unpretentious and hard labor.}
{20320}{}{Tuco Amigo Salamanca}
{20321}{}{Strong-looking Mexican. He looks at you as if you owe him money.}
{20330}{}{Chung Deishu}
{20331}{}{A short Asian with short blond hair. The sword on the belt.}
{20340}{}{Tommy's "Tits"}
{20341}{}{A short man with soft features on a round face with an irritatedly wary expression.}
{20350}{}{Mr. Shaw}
{20351}{}{A huge, fat man with a wig on his head and a make-up of a clown on his face. He scares you with his appearance.}

#POSEYDON GUARDS
{21000}{}{Private PSC of Poseidon}
{21001}{}{Obviously, these mercenaries do not receive money for nothing. It's best not to mess with them.}
{21010}{}{Private PSC of Poseidon}
{21011}{}{Obviously, these mercenaries do not receive money for nothing. It's best not to mess with them.}
{21020}{}{Guardian of the Tower}
{21021}{}{Stern man, evaluates you with the professional eyes of the killer. It’s good that he is hired to protect, not to kill.}

# LARS'S GANG
{21300}{}{Double Bug}
{21301}{}{It is evident that he is a notorious pirate and a thug. The armor is covered in many traces of battle.}
{21310}{}{Black Dog}
{21311}{}{A tough guy with a red, faded bandana around his neck. Looks with a squint.}
{21320}{}{Zhokh}
{21321}{}{Long nigga of a strong physique, periodically spitting to the ground while talking.}
{21330}{}{Israel Hanks}
{21331}{}{A gloomy silent man looks at you appraisingly, as if estimating the price of your belongings.}
{21340}{}{Karnat}
{21341}{}{A seemingly cheerful guy, an eternal smile. However, the gaze is a thirst for profit and glory.}

# KASTOR'S CLERGY
{21400}{}{Guardian of the Faith Thomas the Blessed Manson}
{21401}{}{A man in a dirty robe, on which you can see the lead symbol of the Atom cult.}
{21410}{}{Keeper of the Faith Martha "Voice" Swift}
{21411}{}{The fragile figure in Atom’s dirty robe is out of size. She looks at you with light gray eyes from under the shadow of a hood.}
{21420}{}{Guardian of the Faith Harold "Lazarus" Shipman}
{21421}{}{A bearded, smiling man in Atom’s dirty robe, which shows crimson tracks.}
{21430}{}{Jealous of the Atom}
{21431}{}{A gloomy person in a scarlet mantle with the Atom symbol on it, his face is hidden by an iron mask with an opening for the eyes.}
{21440}{}{Jealous of the Atom}
{21441}{}{A gloomy person in a scarlet mantle with the Atom symbol on it, his face is hidden by an iron mask with an opening for the eyes.}

#SAN FRANCISCO NPC

{21500}{}{Hanayama Kaoru}
{21501}{}{A huge Asian, a real giant. He is dressed in a pre-war three-piece suit, wears fatherfelt.}
{21510}{}{Akisame Koetsuji}
{21511}{}{Low Japanese, calm appearance. Wisdom reads through his eyes.}
{21520}{}{Revi Ruyote}
{21521}{}{Young beautiful Japanese woman with a cocky and sassy look.}
{21530}{}{Bang Shiruba}
{21531}{}{Stooped gray-haired old man with a magnificent mustache. It seems to you that he appreciates you.}
{21540}{}{Lo-Peng}
{21541}{}{This Chinese is quite famous in the city. You definitely heard something about Master Lo-Peng.}
{21550}{}{Lam Chin Ying}
{21551}{}{He looks at you intently and as if with hostility.}
{21560}{}{Sammo Hung}
{21561}{}{Fat Asian with a funny face and a stern look.}
{21570}{}{Donnie Yen}
{21571}{}{A tall Chinese man in a strict traditional dress of the century before last.}
{21580}{}{Mr. Moloch}
{21581}{}{Incredibly large and athletically built man, you are struck by the width of his shoulders.}
{21590}{}{Arnold Mitch}
{21591}{}{A man in a greasy overalls, welder’s goggles are visible on his head among a pile of unwashed hair.}
{21600}{}{Valdis Goose}
{21601}{}{A fat man who stinks fish. Perhaps he came from the depths of the ocean? You do not know.}
{21610}{}{Sigurd Croft}
{21611}{}{A short brunette looking at you like a merchant looks at a customer.}
{21620}{}{Amelie Croft}
{21621}{}{Middle-aged woman with huge bags under her eyes. It is evident that she is very tired, but the smile on her face is quite sincere.}
{21630}{}{Billy Lee}
{21631}{}{Dragon Investigator. This guy reminds you of someone, maybe he has a brother. A large, apparently strong fighter.}
{21640}{}{Jimmy Lee}
{21641}{}{Dragon Investigator. It seems you saw him before, or he has a twin brother. It looks very strong.}
{21650}{}{Homeless Lucas}
{21651}{}{Because of the huge fallen dirty beard, a couple of eyes clouded by alcohol are looking at you.}
{21660}{}{Kintara Ainis}
{21661}{}{An ordinary-looking girl, pretty enough.}
{21670}{}{Akira Homma}
{21671}{}{An elderly woman of about fifty, by her clothes it can be assumed that she is an experienced trapper.}
{21680}{}{Sun Hei}
{21681}{}{This man is clearly an experienced survivor and hunter, his trophies speak for themselves.}
{21690}{}{Bingo Boxes}
{21691}{}{A bald, pinched little man with a sly mug, a little lisp.}
{21700}{}{Fisherman}
{21701}{}{This man probably saw more fish than you fired bullets in your life.}
{21710}{}{Peasant}
{21711}{}{Being a peasant is not an easy job, as well as being an ordinary tramp.}
{21720}{}{Peasant Girl}
{21721}{}{Because of the dirt, the true color of her skin remains a mystery to you.}
{21730}{}{Yakuza Fighter}
{21731}{}{A stern-looking Asian, he is definitely a gangster. From under the clothes you can see the edges of bright tattoos.}
{21740}{}{Yakuza Fighter}
{21741}{}{This lady will give odds to any man, it’s better not to mess with tattooed Asians.}
{21750}{}{Shi Fighter}
{21751}{}{The representative of the large Shi clan, maybe he is a peasant, or maybe a bandit.}
{21760}{}{Shi Fighter}
{21761}{}{Women are also in Shi, maybe they will accept you too? It remains to find contacts.}
{21770}{}{Soldier of Moloch}
{21771}{}{You are absolutely sure that before you, if not a raider, then something very close.}
{21780}{}{Whore}
{21781}{}{Want to have fun? Go to the circus, and this dirty whore seeks to earn.}
{21790}{}{Whore}
{21791}{}{You have heard that some Azat women have a dick, are you sure you want to check?}
{21800}{}{Pimp}
{21801}{}{This tough guy is cool enough to keep his girls in check.}
{21810}{}{Huckster}
{21811}{}{Judging by his appearance, he uses part of the product himself.}
{21820}{}{Huckster}
{21821}{}{Narcobaryga, the most ordinary, most likely it is engaged in deliveries from Renault.}
{21830}{}{Soldier of Moloch}
{21831}{}{You are absolutely sure that before you, if not a raider, then something very close.}
{21840}{}{Soldier of Moloch}
{21841}{}{You are absolutely sure that before you, if not a raider, then something very close.}
{21850}{}{Shi Commander}
{21851}{}{This Shi representative looks like a junior officer, probably somewhere around his unit.}
{21860}{}{Commander Shi}
{21861}{}{This is the case when a woman can effectively command men. All these Asians are not like humans.}
{21870}{}{Shi Fighter}
{21871}{}{The representative of the large Shi clan, maybe he is a peasant, or maybe a bandit.}
{21880}{}{Shi Fighter}
{21881}{}{Women are also in Shi, maybe they will accept you too? It remains to find contacts.}

#FORP 2019 NPC
{22000}{}{Rat}
{22001}{}{Rat. Pretty petty creature.}
{22010}{}{Mantis}
{22011}{}{Mantis. Cold-blooded eyes are fixed on you, very loud and unpleasant chatter.}
{22020}{}{Ant}
{22021}{}{Ant. The antennae point at you, followed by the eyes of a predator.}
{22030}{}{Ant-lion}
{22031}{}{Ant-lion. This hefty ant looks especially vile and dangerous, its carapace looks very thick, and its mouth is huge.}
{22040}{}{Pig Rat}
{22041}{}{Pig Rat. It makes sounds that resemble a squeak and grunt in one.}
{22050}{}{Mole rat}
{22051}{}{Mole rat. This huge creature growls loudly.}
{22060}{}{Mole rat mutant}
{22061}{}{Mole rat mutant. This huge creature growls loudly.}
{22070}{}{Silver Gecko}
{22071}{}{Silver Gecko. This is a simple small pangolin.}
{22080}{}{Golden Gecko}
{22081}{}{Golden Gecko. This big gecko loudly clangs with sharp teeth.}
{22090}{}{Cave gecko}
{22091}{}{Cave gecko. This big gecko loudly clangs with sharp teeth.}
{22100}{}{Dog}
{22101}{}{The dog. Common sized mutt.}
{22110}{}{Shallow Radcorspion}
{22111}{}{Shallow radcorscorpion. Noticing you, he scrambles out of the sand shelter.}
{22120}{}{Radscorpion}
{22121}{}{Radcorspion. Knocks with claws and twists its tail.}
{22130}{}{Small Black Radcorscorpion}
{22131}{}{Shallow black radcorporium. This is a small but dangerous scorpion.}
{22140}{}{Black Radcorspion}
{22141}{}{Black Radcorspion. Pointing his black tail at you.}
{22150}{}{Cave Radcorporion}
{22151}{}{Cave Radcorporion. Pointing his dark tail at you.}
{22160}{}{Brahmin}
{22161}{}{Brahmin. Flies fly overhead.}
{22170}{}{Prey-plant}
{22171}{}{Carnivorous plant. A strange, eyeless mouth rests on a thick stem and beckons you a smile.}
{22180}{}{Vanamingo}
{22181}{}{Vanamingo. This creature has neither eyes nor fingers. A terrible sight.}
{22190}{}{Death Claw Cub}
{22191}{}{Death Claw Cub. Slightly shorter than you, but certainly dangerous!}
{22200}{}{Claw of Death}
{22201}{}{Claw of Death. With his large paws down, this Claw sniffs.}
{22210}{}{Deathclaw Hunter}
{22211}{}{Deathclaw hunter. This creature is gray, it is much more dangerous than the strongest claw of death in a pack.}
{22220}{}{Fiery gecko}
{22221}{}{Fiery gecko. A faint smoke comes out of the nostrils.}
{22230}{}{Beast}
{22231}{}{Beast}
{22240}{}{Centaur}
{22241}{}{Centaur. Muddy mucus flows from a long tentacular tongue.}
{22250}{}{Flying}
{22251}{}{Aircraft. It floats in the air, emitting harmful gases through the pores of the subcutaneous sac.}
{22260}{}{Swamplurker}
{22261}{}{Swamplurker. Terrible creature from the deep sea or swamp.}







































