# Created: 08.11.2007 03:40 Cvet
# Updated: 29.10.2008 23:18 Cvet

{1}{}{You read the papers.}
{2}{}{You were unable to read the papers.}
{3}{}{You have not read anything new.}
{4}{}{You cannot remember what you read.}
{5}{}{You forgot unnecessary information.}
{6}{}{This is not so easy to forget.}
{7}{}{You have finished writing on papers.}
{8}{}{You didn’t manage to write down your plan.}

#
# Format:
# Name - Number * 10
# Text - Number * 10 + 1


# 99999
# Last valid number, after it the text is taken from the database of player records.
# Holodisk for player entries.
{999990}{}{Blank sheets.}
{999991}{}{}