# 17.10.2007 Cvet


{4}{}{%d. }
{5}{}{Current status:}

#
# Room
# Name
#

#
# Formulas of calculations:
# Number * 1000 + Value (1-100) - The text that appears on the player with a given variable value.
# Number * 1000 + 101 - Name of the quest tab.
# Number * 1000 + 102 - Permanent description of the quest.


