#-------------------------------------------------------------------
#TLJ - GM spawns
#-------------------------------------------------------------------

#RATS
{10}{}{Baby rat}
{11}{}{Quite a small creature.}
{20}{}{Small rat}
{21}{}{Disproportionately large fangs and red eyes.}
{30}{}{Average rat}
{31}{}{Saliva flows profusely from her fangs.}
{40}{}{Irradiated rat}
{41}{}{It glows and there is almost no fur on it.}
{50}{}{Huge rat}
{51}{}{This evil rodent can easily jump up to your face.}
{60}{}{Mutated rat}
{61}{}{A mater evil creature the size of a small dog.}
{70}{}{Rabid Rat}
{71}{}{An average rat covered in bite marks. A big part of its tail is missing.}

#MANTIS
{100}{}{Pathetic mantis}
{101}{}{A small and nasty insect with long legs.}
{110}{}{Mantis}
{111}{}{A medium-sized body with long legs that can stab you to death.}
{120}{}{Huge mantis}
{121}{}{A huge insect with no less impressive claws and a massive body. The head randomly moves in different directions.}
{130}{}{Mantis Alpha}
{131}{}{A huge and exceptional representative of the Mantis. Impressive wings and ever-aggressively clacking claws.}

#ANTS
{200}{}{Ant-worker}
{201}{}{A small creature, always wagging on the move.}
{210}{}{Ant-soldier}
{211}{}{A large creature, with medium-sized claws and long antennae. The impressive mandibles move smoothly.}
{220}{}{Drone Ant}
{221}{}{This hefty ant looks especially disgusting and over-sized. The body is disproportionately large, which makes it look unpleasant.}
{230}{}{Ant-guard}
{231}{}{This is an Alpha male: his shell looks very thick, and his mouth is huge. Powerful claws, long mandibles, and huge eyes.}
{240}{}{Ant-lion}
{241}{}{This hefty ant looks especially disgusting and dangerous, its thick shell is covered with a white viscous liquid and its mouth is huge}

#PIG RATS
{300}{}{Pig rat}
{301}{}{It makes sounds that resemble a squeak and a grunt in one. A nasty little carcass on clawed paws.}
{310}{}{Huge Pig rat}
{311}{}{A huge fleshy carcass on muscular paws with claws and sharp teeth in its mouth.}
{320}{}{Pig rat Alpha}
{321}{}{An incredibly large and muscular pig-rat. His body shows an abundance of unpleasant scars and old wounds.}

#MOLE RATS
{330}{}{Mole rat}
{331}{}{A small animal on four legs with claws and sharp teeth. Long antennae are visible on the muzzle and tail.}
{340}{}{Huge Mole rat}
{341}{}{A huge and extremely fleshy beast. The whole skin is in folds of dark pink color.}
{350}{}{Mole rat Alpha}
{351}{}{A huge mole-rat with particularly long claws. The teeth are extremely sharp and large, and numerous scars are visible on the body.}
{360}{}{Mutant mole rat}
{361}{}{A mountain of muscles and huge red eyes. Viscous saliva flows from the fangs. The mutant smells extremely bad}

#RABIT H RATS VARIANTS
{370}{}{Rabid Pig rat}
{371}{}{A pig rat fully covered in dirt and goo, with some chunks of meat where its mouth should be. It makes a loud bloodcurdling squeak as if it was burned alive.}
{380}{}{Rabid Mole rat}
{381}{}{A big stinky molerat, that lost its mind. It is constantly sniffing the ground shuffling its face onto it leaving a trail of blood.}

#SILVER GECKOS
{400}{}{Silver Gecko}
{401}{}{A small silvery gecko. Small paws on a relatively large body.}
{410}{}{Silver predatory Gecko}
{411}{}{A wiry gecko with a long tail. In the mouth, frequent and very sharp teeth are visible.}
{420}{}{Large silver Gecko}
{421}{}{A very large gecko, compared to its fellows. Long paws with dangerous claws, and iridescent skin.}
{430}{}{Silver Gecko Alpha}
{431}{}{The largest silver gecko. Its large red eyes are bloodshot, and small thorns are observed on the skin.}

#GOLDEN GECKOS
{440}{}{Golden Gecko}
{441}{}{A small and nimble golden gecko. The small tail always moves in time with the gait.}
{450}{}{Large golden Gecko}
{451}{}{A large creature with a long tail and sharp teeth. Its golden skin shimmers beautifully in the sun.}
{460}{}{Golden Gecko Alpha}
{461}{}{The largest golden gecko. His large red eyes are bloodshot, and there are frequent scars and scars on his skin.}

#CAVE GECKOS
{470}{}{Cave Gecko}
{471}{}{A small creature with a dark skin color. Scars and scuffs from being in the cave are visible all over the body. Yellow eyes constantly seem to run around the environment}

#FIREGECKOS
{480}{}{Fire Gecko}
{481}{}{A small, but extremely colorful beast. A light smoke comes from the creature's nostrils.}
{490}{}{Fire Gecko Alpha}
{491}{}{An extremely large fire gecko with an impressive build and a whole "fountain" of smoke coming out of its nostrils. The mouth always opens, releasing streams of fire.}

#RABID GECKO VARIANTS
{500}{}{Rabid silver gecko}
{501}{}{A shabby gecko with dry skin from being constantly out in the open. It is snarling at you sticking its bitten tongue out.}
{510}{}{Rabid golden gecko}
{511}{}{A hunched-over gecko with golden skin with large brownish spots on it. it grates its teeth waiting for something.}

#DOGS
{600}{}{Weak dog}
{601}{}{A skinny animal, ribs, and traces of long starvation are visible on the body. The fur has thinned.}
{610}{}{Dog}
{611}{}{An ordinary mongrel of medium size.}
{620}{}{Tough dog}
{621}{}{A lot of old scars and wounds make it clear that this dog has been through a lot.}
{630}{}{Big dog}
{631}{}{A large dog with a rough and wild face. Drool drips from the fangs, and dirt is visible on the paws.}
{640}{}{Puppy}
{641}{}{A small creature with small paws, a long muzzle, and short fur.}

#WOLVES
{650}{}{Weak wolf}
{651}{}{A small creature that somewhat resembles a dog. Sparse fur, small fangs, and claws on the paws. He looks exhausted.}
{660}{}{Wolf}
{661}{}{A medium-sized creature. Good skin, strong build, long and elongated muzzle with sharp teeth in the mouth.}
{670}{}{Tough wolf}
{671}{}{A battered wolf. There are multiple scars on the skin and dried blood on the paws.}
{680}{}{Alpha wolf}
{681}{}{A huge and old wolf. His large build and extremely long claws and teeth make it clear that he has lived a lot. There is an abundance of old scars and relatively fresh wounds on the wolf's skin.}
{690}{}{Puppy}
{691}{}{A small creature with small paws, a long muzzle, and gray fur. The presence of sharp fangs gives him a wolf puppy.}

#COYOTES
{700}{}{Coyote}
{701}{}{A wasteland coyote. This coyote is a regular dweller in Arizona.}

#RABID DOG VARIANTS
{710}{}{Rabid dog}
{711}{}{A beaten-up dog with sticky disgusting black fur. It's wandering aimlessly groaning at everything that moves.}
{720}{}{Rabid wolf}
{721}{}{A massive grey wolf with a big scar across its head. When it spots you, you can see a set of sharp teeth shining in red.}

#RAD SCORPIONS
{800}{}{Small Radscorpion}
{801}{}{A small scorpion with not very impressive claws and a small tail.}
{810}{}{Radscorpion}
{811}{}{A medium-sized scorpion. Venom drips from its tail and sting. Massive claws and fast paws.}
{820}{}{Tough Radscorpion}
{821}{}{A large scorpion with a large and swollen sting. A strong and massive shell.}

#BLACKSCORPS
{830}{}{Small Black Scorpion}
{831}{}{A small scorpion with a long tail and a black shell.}
{840}{}{Black Radscorpion}
{841}{}{A large black scorpion with a thick shell and a massive hanging tail. The sting of creation oozes poison.}

#CAVESROPS
{850}{}{Cave radscorpion}
{851}{}{A large scorpion with a gray shell and a massive black tail}

#BRAHMINS
{900}{}{Brahmin Calf}
{901}{}{A small and weak brahmin calf. He looks skinny and hungry.}
{910}{}{Brahmin}
{911}{}{Two heads, four hooves, and one big belly. One of the heads has horns.}
{920}{}{Big Brahmin}
{921}{}{A large brahmin with massive heads and body.}
{930}{}{Wild Brahmin}
{931}{}{A thin and shabby brahmin. The body of a brahmin is worn out by wild nature.}
{940}{}{Furious Brahmin}
{941}{}{A large brahmin of a dark color. The horns are longer than those of an ordinary brahmin, and the hooves look more massive.}
{950}{}{Rabid Brahmin}
{951}{}{A brahmin covered in bruises and abrasions, its heads are mindlessly hitting each other.}

#LAVASH
{960}{}{Lavash}
{961}{}{A cow-like creature.}

#SPOREPLANTS
{1000}{}{Predatory plant}
{1001}{}{A strange, eyeless mouth is held on a thick stalk.}
{1010}{}{Huge predatory plant}
{1011}{}{A huge eyeless mouth with numerous appendages on the sides. The stem is covered with thorns, and the plant itself is extremely tall.}

#YAO
{1100}{}{Yao-guai}
{1101}{}{A huge, muscular bear-like creature with impressive paws covered with sparse hair. There are ulcers and scars on the body. It has incredibly sharp teeth and long claws the size of a human hand}
{1110}{}{Rabid Yao-guai}
{1111}{}{A huge, muscular bear-like creature covered in blood and fresh wounds. Foam can be visible around its huge and sharp teeth and it's looking around furiously.}

#ALIENS
{1200}{}{Strange egg}
{1201}{}{A strange, rounded egg of unknown origin.}
{1210}{}{Wanamingo}
{1211}{}{This creature has neither eyes nor fingers. Vile long boneless tentacles come out of the body.}
{1220}{}{Large Wanamingo}
{1221}{}{A big and scary eyeless creature with long, nasty tentacles.}

#MOTERALIENS
{1230}{}{Wanamingo Matriach}
{1231}{}{Wanamingo's Matriach. Slime flows from the mouth of a hefty Wanamingo, and the shiny skin has a dark gray hue.}

#DEATHCLAWS
{1300}{}{Deathсlaw Cub}
{1301}{}{A small humanoid creature with long paws, from which sharp claws are visible.}
{1310}{}{Young Deathclaw}
{1311}{}{A medium-sized creature with light hair and small horns.}
{1320}{}{Large Deathclaw}
{1321}{}{A big and muscular scary creature. Long and extremely sharp claws on the paws. It has yellow and curved fangs.}
{1330}{}{Deathclaw Alpha}
{1331}{}{A huge death claw with long curved horns and an abundance of scars all over its body. Darkened color and bulky paws.}
{1340}{}{Deathclaw Hunter}
{1341}{}{A huge death claw of gray color. A curved body, powerful paws, and curved horns aimed forward.}

#BEAST
{1350}{}{Beast}
{1351}{}{A clawed, short, stocky gray-colored creature.}

#CROCS
{1400}{}{Creepy croc}
{1401}{}{A large, wriggling creature with long, dangerous paws, sharp fangs and a strong tail.}
{1410}{}{Shadow croc}
{1411}{}{A large, wriggling, dark creature with long, dangerous paws, sharp fangs and a strong tail.}

#CENTAURS
{1500}{}{Small centaur}
{1501}{}{A small, but extremely vile creature. It moves on six human hands. Various disfigured heads are adorned on long necks.}
{1510}{}{Centaur}
{1511}{}{Muddy mucus flows from a long tentacle-like tongue. Two disfigured heads and what looked like intestines hanging out of the body and dragging behind.}
{1520}{}{Ugly Centaur}
{1521}{}{An extremely unpleasant sight. A creature with different heads, and an abundance of organs located outside. A viscous mucus flows through the body.}
{1530}{}{Alpha Centaur}
{1531}{}{A huge centaur is supported by ten human hands. Three ugly heads and an equally disfigured semblance of a body.}

#FLOATERS
{1600}{}{Small Floater}
{1601}{}{A small snake-like thing, slowly crawling on its tail. Instead of a face, the creature has a semblance of a large mouth.}
{1610}{}{Floater}
{1611}{}{An ugly creature with a huge horizontal mouth full of teeth.}
{1620}{}{Ugly Floater}
{1621}{}{He stinks abominably, and his front mouths bleed profusely with mucus.}
{1630}{}{Floater Alpha}
{1631}{}{A huge Floater with several huge mouths full of an abundance of sharp teeth in acrid mucus. The creature stinks very much.}

#SWAMPLURKERS
{1700}{}{Weak Mirelurk}
{1701}{}{A small creature in a thick shell and massive claws.}
{1710}{}{Mirelurk}
{1711}{}{A smelly, large, and bulky creature, covered with a solid, strong shell. Sharp claws look extremely dangerous and sharp.}
{1720}{}{Mirelurk Alpha}
{1721}{}{Incredibly massive and strong, an exceptional swamper. Its huge shell is covered with swamp waste and an abundance of algae.}

#OTHER_INSECTS
{1800}{}{Wasp}
{1801}{}{A large mutated insect with large wings. Greenish eyes and sharp thorns are all over the body.}
{1810}{}{Cockroach}
{1811}{}{A nasty, large, and extremely nimble cockroach. It has long antennae and legs, as well as a relatively strong shell.}
{1820}{}{Giant Millipede}
{1821}{}{A giant millipede.}
{1830}{}{Giant Spider}
{1831}{}{A giant spider.}

#WILD GHOULS
{1900}{}{Decaying ghoul}
{1901}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{1910}{}{Wild ghoul}
{1911}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{1920}{}{Mutated ghoul}
{1921}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{1930}{}{Huge mutated ghoul}
{1931}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{1940}{}{Лоботомит}
{1941}{}{Чудовищное творение чьего-то больного разума. Из мозга этого бедолаги была удалена некоторая часть, что сделало его бездумным болванчиком, что даже свою смерть не заметит.}
{1990}{}{Feral Ghoul}
{1991}{}{Ghoul looks for something to bite into.}
{2000}{}{Big Feral Ghoul}
{2001}{}{This ghouls is bigger than others. Dangerous.}


# Red Radscorpion
{1950}{}{Red Radscorpion}
{1951}{}{This scorpion's chitin is a fiery red. It looks unusual.}
# Toxic Gecko
{1960}{}{Toxic Gecko}
{1961}{}{Its skin is iridescent green, with spikes protruding from it. Its eyes are blood red. It looks creepy.}
# Rare monsters
{1970}{}{"Horror"}
{1971}{}{This creature seems out of this world. Sharp teeth oozing green liquid, long tentacles. Brrr...}
{1980}{}{Night Wanderer}
{1981}{}{A huge, monstrous creature, the size of a truck. An unnatural body, one arm larger than the other.}

#FORP NCR SOLDIERS
{2100}{}{Soldier}
{2101}{}{He has a visible patch with the image of a two-headed bear.}
{2110}{}{Soldier}
{2111}{}{He has a visible patch with the image of a two-headed bear.}
{2120}{}{Soldier}
{2121}{}{He has a visible patch with the image of a two-headed bear.}
{2130}{}{Soldier}
{2131}{}{He has a visible patch with the image of a two-headed bear.}
{2140}{}{Soldier}
{2141}{}{He has a visible patch with the image of a two-headed bear.}
{2150}{}{Soldier}
{2151}{}{He has a visible patch with the image of a two-headed bear.}

#FORP RANGERS
{2200}{}{Soldier}
{2201}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{2210}{}{Soldier}
{2211}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{2220}{}{Soldier}
{2221}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{2230}{}{Soldier}
{2231}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{2240}{}{Soldier}
{2241}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{2250}{}{Soldier}
{2251}{}{On the chest there is a badge in the form of a five-pointed golden star.}

#FORP BoS SOLDIERS
{2300}{}{Soldier}
{2301}{}{The armor depicts a winged sword and gears.}
{2310}{}{Soldier}
{2311}{}{The armor depicts a winged sword and gears.}
{2320}{}{Soldier}
{2321}{}{The armor shows a winged sword and gears.}
{2330}{}{Soldier}
{2331}{}{The armor shows a winged sword and gears.}
{2340}{}{Soldier}
{2341}{}{The armor shows a winged sword and gears.}
{2350}{}{Soldier}
{2351}{}{The armor depicts a winged sword and gears.}

#FORP ENCLAVE SOLDIERS
{2400}{}{Soldier}
{2401}{}{On their chest is the "E" emblem surrounded by stars.}
{2410}{}{Soldier}
{2411}{}{On their chest is the "E" emblem surrounded by stars.}
{2420}{}{Soldier}
{2421}{}{On their chest is the "E" emblem surrounded by stars.}
{2430}{}{Soldier}
{2431}{}{On their chest is the "E" emblem surrounded by stars.}
{2440}{}{Soldier}
{2441}{}{On their chest is the "E" emblem surrounded by stars.}
{2450}{}{Soldier}
{2451}{}{On their chest is the "E" emblem surrounded by stars.}

#FORP VAULT_CITY SOLDIERS
{2500}{}{Soldier}
{2501}{}{On their shoulder pad is an emblem "VC".}
{2510}{}{Soldier}
{2511}{}{The logo on the shoulder pad there is an emblem "VC".}
{2520}{}{Soldier}
{2521}{}{On their shoulder pad is an emblem "VC".}
{2530}{}{Soldier}
{2531}{}{On their shoulder pad is an emblem "VC".}
{2540}{}{Soldier}
{2541}{}{On their shoulder pad is an emblem "VC".}
{2550}{}{Soldier}
{2551}{}{On their shoulder pad is an emblem "VC".}

#FORP RENEGADE SOLDIERS
{2600}{}{Soldier}
{2601}{}{There are no distinguishing features on their armor.}
{2610}{}{Soldier}
{2611}{}{There are no distinguishing features on their armor.}
{2620}{}{Soldier}
{2621}{}{There are no distinguishing features on their armor.}
{2630}{}{Soldier}
{2631}{}{There are no distinguishing features on their armor.}
{2640}{}{Soldier}
{2641}{}{There are no distinguishing features on their armor.}
{2650}{}{Soldier}
{2651}{}{There are no distinguishing features on their armor.}

#VAULT DWELLERS
{2700}{}{Vault Resident} 
{2701}{}{A typical vault resident.}
{2710}{}{Vault Resident} 
{2711}{}{A typical vault resident.}
{2720}{}{Vault Security Officer} 
{2721}{}{The vault's enforcer is in charge of the order.}
{2730}{}{Vault Security Officer} 
{2731}{}{The vault's enforcer is in charge of the order.}
{2740}{}{Scientist} 
{2741}{}{A neaty-looking scientist.}
{2750}{}{Scientist} 
{2751}{}{A neaty-looking scientist.}
{2760}{}{Mr. Handy} 
{2761}{}{A Pre-War robotic best-seller. The all-known Mr. Handy - the best buddy to help you around in anything.}
{2770}{}{Vault Technician} 
{2771}{}{A regular Vault worker from the technical department.}
{2780}{}{Vault Technician} 
{2781}{}{A regular Vault worker from the technical department.}
{2790}{}{Chief Security Officer} 
{2791}{}{A chief officer standing in charge of the entire Vault security service.}
{2800}{}{High Class Resident} 
{2801}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2810}{}{High Class Resident} 
{2811}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2820}{}{High Class Resident} 
{2821}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2830}{}{High Class Resident} 
{2831}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2840}{}{High Class Resident} 
{2841}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2850}{}{High Class Resident} 
{2851}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}
{2860}{}{High Class Resident} 
{2861}{}{It seems like this particular resident is rather very important or has certain privileges in the Vault.}

#GENERIC NPC
{3000}{}{Whore} 
{3001}{}{A typical prostitute.}
{3010}{}{Drunk}
{3011}{}{This man has an absent gaze and a very bad breath.}
{3020}{}{Drunk}
{3021}{}{A drunk woman. She has a big trouble walking straight without tripping.}
{3030}{}{Punk}
{3031}{}{You see a fairly young man with some spray cans and a confident look.}
{3040}{}{Punk}
{3041}{}{You see a fairly young woman in a stylish leather jacket. There are also some piercings on her face.}
{3050}{}{Beggar}
{3051}{}{He looks like a corpse and doesn't move, only taking a shallow breath once a time.}
{3060}{}{Beggar}
{3061}{}{A poor dirty woman. Walking by you can hear quiet sobbing.}
{3070}{}{Cheap Fuck}
{3071}{}{A middle-aged woman in a revealing worn outfit. She is looking at you blankly.}
{3080}{}{Homeless Ghoul}
{3081}{}{A rotting pile of muscle and bones. You can't tell if he's even alive.}
{3090}{}{Traveller}
{3091}{}{A regular traveler, still covered in sand from roaming the wastes.}
{3100}{}{Traveller}
{3101}{}{A regular traveler, still covered in sand from roaming the wastes.}
{3110}{}{Robber}
{3111}{}{A robber. An ordinary robber looking for his next prey.}
{3120}{}{Robber}
{3121}{}{A robber. An ordinary robber looking for her next prey.}
{3130}{}{Child}
{3131}{}{A young child. There is nothing particular about it.}
{3140}{}{Child}
{3141}{}{A young child. There is nothing particular about it.}
{3150}{}{Trader}
{3151}{}{A trader. You see a man in a sleeveless jacket and a sack with bottlecaps pushed through his belt.}
{3160}{}{Guard}
{3161}{}{A guard. He is wearing a metal armor. His eyes are lazily following every passing person.}
{3170}{}{Guard}
{3171}{}{A guard. She is wearing a metal armor. Her eyes are lazily following every passing person.}
{3180}{}{Tough guard}
{3181}{}{A tough guard. Wearing full combat armor this guard is standing steadly.}
{3190}{}{Tough guard}
{3191}{}{A tough guard. Wearing full combat armor this guard is standing steadly.}
{3200}{}{Doctor}
{3201}{}{A doctor. Wearing a white coat he rummages through his bag full of medical equipment.}
{3210}{}{Farmer}
{3211}{}{A farmer. This man has a wimpy posture and dirty clothes, but he doesn't look hungry or homeless.}
{3220}{}{Farmer}
{3221}{}{A farmer. This man has a wimpy posture and dirty clothes, but he doesn't look hungry or homeless.}
{3230}{}{Farmer}
{3231}{}{A farmer. This man has a wimpy posture and dirty clothes, but he doesn't look hungry or homeless.}
{3240}{}{Farmer}
{3241}{}{A farmer. This woman has a wimpy posture and dirty clothes, but she doesn't look hungry or homeless.}
{3250}{}{Citizen}
{3251}{}{A citizen. This man looks like he has been living here for a long time.}
{3260}{}{Citizen}
{3261}{}{A citizen. This man looks like he has been living here for a long time.}
{3270}{}{Citizen}
{3271}{}{A citizen. This woman looks like she has been living here for a long time.}
{3280}{}{Мужчина}
{3281}{}{Представитель мужского пола.}
{3290}{}{Женщина}
{3291}{}{Представительница женского пола.}
{3300}{}{Мэр}
{3301}{}{Этот человек за управление всем городом.}
{3310}{}{Шериф}
{3311}{}{Этот человек за поддержание порядка во всём городе.}


#BOUNTY HUNTERS
{3500}{}{Bounty hunter}
{3501}{}{You see a regular bounty hunter wearing combat armor.}
{3510}{}{Bounty hunter}
{3511}{}{You see a regular bounty hunter wearing combat armor.}
{3520}{}{Tough bounty hunter}
{3521}{}{A tough bounty hunter. A big man wearing combat armor casually smoking a cigarette.}
{3530}{}{Tough bounty hunter}
{3531}{}{A tough bounty hunter. A big woman wearing combat armor with crossed hands on her chest.}
{3540}{}{Bounty hunter veteran}
{3541}{}{A bounty hunter veteran. A man with a sharp look and a serious expression. His combat armor has an integrated bandoiler.}
{3550}{}{Bounty hunter veteran}
{3551}{}{A bounty hunter veteran. A woman with a sharp look and a serious expression. Her combat armor has an integrated bandoiler.}
{3560}{}{Bounty hunter sadist}
{3561}{}{A bounty hunter sadist. His face is hidden behind a shawl. You can see a collection of knives and cut-off fingers on his armor.}
{3570}{}{Bounty hunter sadist}
{3571}{}{A bounty hunter sadist. Her face is hidden behind a shawl. You can see a collection of knives and cut-off fingers on her armor.}
{3580}{}{Bounty hunter leader}
{3581}{}{A bounty hunter leader. On his combat armor, you can see a patch resembling a dragon and a rifle.}
{3590}{}{Bounty hunter leader}
{3591}{}{A bounty hunter leader. On her combat armor, you can see a patch resembling a dragon and a rifle.}

#MUTANTS
{3700}{}{Super mutant}
{3701}{}{A super mutant. Big green pile of muscles born to rip and tear.}
{3710}{}{Super mutant brute}
{3711}{}{A super mutant brute. A mountain of muscles tangled by some rusty chains waiting to crush someone.}
{3720}{}{Super mutant savage}
{3721}{}{A super mutant savage. From the awful scars on his body, you can tell he went through a lot and he doesn't look like stopping now.}
{3730}{}{Super mutant berserker}
{3731}{}{A super mutant berserker. This menace in heavy metal armor is ready to beat your soul out of your body.}
{3740}{}{Super mutant master}
{3741}{}{Super mutant master. This super mutant in sturdy metal armor decorated with skulls of his foes looks like he could choke you to death with just two fingers.}
{3750}{}{Nightkin}
{3751}{}{A nightkin. Extremely strong and smart creature with blue skin.}
{3760}{}{Tough nightkin}
{3761}{}{A tough nightkin. It looks like the skin of this nightkin is thicker than the rest.}
{3770}{}{Nightkin goon}
{3771}{}{A nightkin goon. A massive mutant, that could carry a whole car on his back.}
{3780}{}{Nightkin master}
{3781}{}{A nightkin master. Small spots of blue skin are to be seen between the metal plates of his armor. His eyes calmly wander around.}

#TRIBALS
{4000}{}{Tribal}
{4001}{}{An ordinary tribal. Living in the wild made him strong and agile.}
{4010}{}{Tribal}
{4011}{}{An ordinary tribal. She looks healthy in this environment.}
{4020}{}{Tribal Hunter}
{4021}{}{A tribal hunter with a quiver on a strap. You can see scars from scratches on his chest and arms.}
{4030}{}{Tribal Huntress}
{4031}{}{A tribal huntress playing with her knife. Her hands are covered in some scars.}
{4040}{}{Tribal Shaman}
(4041}{}{Tribal shaman. An elderly man is covered in symbols painted with red paint. His face is expressionless.}
{4050}{}{Tribal Shamaness}
{4051}{}{Tribal shaman. A calm-looking woman wearing a shirt made of brahmin hide. She looks at you with curiosity.}
{4060}{}{Tribal Warrior}
{4061}{}{Warrior of the tribe. Wearing only a gecko pelt and necklaces of animal teeth, he gives you a cold look.}
{4070}{}{Tribal Warrior}
{4071}{}{Warrior of the tribe. Wearing only a gecko pelt the rest of her body is covered in black and paint.}

#CANNIBALS
{4200}{}{Cannibal}
{4201}{}{A cannibal. This man craves human meat, and he looks in your direction.}
{4210}{}{Cannibal}
{4211}{}{A cannibal. This woman craves human meat, and she looks in your direction licking her lips.}
{4220}{}{Pathetic cannibal}
{4221}{}{You see a skinny miserable man covered in worn clothing stained by blood. He gives you a hungry look.}
{4230}{}{Pathetic cannibal}
{4231}{}{You see a skinny pale woman covered in worn clothing stained by blood. when she sees you a faint smile appears on her face.}
{4240}{}{Cannibal butcher}
{4241}{}{A cannibal butcher. A big man who wears an apron, that is completely brown from dried blood. He looks well-fed.}
{4250}{}{Cannibal butcher}
{4251}{}{A cannibal butcher. A thick woman with an apron, that is completely brown from dried blood. She gives you a playful look running her finger on a kitchen knife.}
{4260}{}{Insane cannibal}
{4261}{}{An insane cannibal. A man covered in both dirt and blood. There are no fingernails on his hands instead there are spots of dried blood. when he looks at you a wave of shivers goes down your spine.}
{4270}{}{Insane cannibal}
{4271}{}{An insane cannibal. A woman covered both in dirt and blood. she is hunched and her long messy hair almost touches the ground. when she smiles at you there's nothing but a void in her mouth.}
{4280}{}{Wild cannibal}
{4281}{}{A wild cannibal. This poorly clothed man doesn't look any different from the rest, but you can feel, that something is off.}
{4290}{}{Wild cannibal}
{4291}{}{A wild cannibal. This poorly clothed woman doesn't look any different from the rest, but you can feel, that something is off.}
{4300}{}{Cannibal hunter}
{4301}{}{A cannibal hunter. His hands and chest are cut with some kind of bladed weapon leaving straight scars. He stands unbothered.}
{4310}{}{Cannibal huntress}
{4311}{}{A cannibal huntress. There is a collection of knives strapped to her belt. She looks at you with a predatory grin on her face.}
{4320}{}{Tough cannibal}
{4321}{}{A tough cannibal. His muscular body with rough pale skin is invading your view. He looks at you with proudness and superiority in his eyes.}
{4330}{}{Tough cannibal}
{4331}{}{A tough cannibal. Her impressive fit body is only tainted by a few scars and dirt. Seeing you she cracks her knuckles.}
{4340}{}{Cannibal feastmaster}
{4341}{}{A cannibal feastmaster. A tall bald man covered in straps of human leather decorated with teeth. The white paint on his face resembles a skull.}
{4350}{}{Cannibal feastmastress}
{4351}{}{A cannibal feastmastress. A woman wearing a skimpy outfit with a tattered dress all made of human leather. Her black facepaint resembles a skull.}

#BANDITS
{4500}{}{Bandit}
{4501}{}{An ordinary bandit looking impatiently for an occasion to rob someone.}
{4510}{}{Bandit}
{4511}{}{An ordinary bandit looking impatiently for an occasion to rob someone.}
{4520}{}{Tough bandit}
{4521}{}{A strong man with a leather jacket revealing his biceps. His face shows a rather numb expression.}
{4530}{}{Tough bandit}
{4531}{}{A strong woman wearing a leather jacket. Her expression shows superiority.}
{4540}{}{Bandit Leader}
{4541}{}{A bandit leader. There are many scratches on his armor. He looks confident.}
{4550}{}{Bandit leader}
{4551}{}{A bandit leader. There are many scratches on her armor. She looks confident.}
{4560}{}{Bandit Scout}
{4561}{}{A skinny young man in a leather jacket wearing a bandana trying to spot anyone who can be robbed.}
{4570}{}{Bandit Scout}
{4571}{}{A young woman in a leather jacket wearing a bandana trying to spot anyone who can be robbed.}
{4580}{}{Bandit Veteran}
{4581}{}{A bandit veteran wearing a cloak and some bandoilers filled with bullets giving him a dangerous look.}
{4590}{}{Bandit Veteran}
{4591}{}{A bandit veteran wearing a cloak and some bandoilers filled with bullets giving her a dangerous look.}
{4600}{}{Bandit Scum}
{4601}{}{A poorly clothed bandit. There are plenty of weird tattoos on his body giving him a freakish look.}
{4610}{}{Bandit Scum}
{4611}{}{A poorly clothed bandit. There are plenty of weird tattoos on her body and her hair is dyed green making her look like a psycho.}

# MERCENARIES
{4700}{}{Mercenary}
{4701}{}{He has his own opinion about everything; often causing arguments.}
{4710}{}{Mercenary}
{4711}{}{She makes it clear that it is better not to mess with her.}
{4720}{}{Mercenary Veteran}
{4721}{}{A handsome man with a serious look, owner of a large jaw and developed muscles.}
{4730}{}{Mercenary Veteran}
{4731}{}{A young girl with a short bob haircut and long strong legs.}
{4740}{}{Mercenary Commander}
{4741}{}{He has many patches with state names on his shoulder.}
{4750}{}{Mercenary Commander}
{4751}{}{A seasoned Valkyrie of the Wasteland.}
{4760}{}{Bounty Hunter}
{4761}{}{Not much different from any other hardened killer, besides still having all of their teeth.}
{4770}{}{Bounty Huntress}
{4771}{}{She is always on guard. Always. Even now.}
{4780}{}{Experienced Bounty Hunter}
{4781}{}{Numerous trophies adorn his outfit.}
{4790}{}{Experienced Bounty Huntress}
{4791}{}{Her determined facial expression and tanned face reveal her as an experienced traveler.}
{4800}{}{Bounty Hunter Veteran}
{4801}{}{Looks at you as if you are just another potential target.}

# SLAVERS
{4900}{}{Slaver}
{4901}{}{An ordinary young man with a tattooed forehead and a dirty neck.}
{4910}{}{Slaver}
{4911}{}{Her slave trader tattoo was done by some talentless person.}
{4920}{}{Slaver Veteran}
{4921}{}{A large middle-aged man with rings on his hands.}
{4930}{}{Slaver Veteran}
{4931}{}{Her face is decorated with scars, and her eyes are full of confidence and restrained anger.}
{4940}{}{Tough Slaver}
{4941}{}{An experienced herder, scalps of defeated savages hang on his belt.}
{4950}{}{Tough Slaver}
{4951}{}{A tattooed girl with a wicked smile, looks tipsy and relaxed.}
{4960}{}{Slaver Leader}
{4961}{}{A well-dressed and groomed man with languid manners and a tattoo.}
{4970}{}{Slaver Commander}
{4971}{}{A woman in high boots, with a whip under her arm and a tattoo.}

# SLAVES
{5100}{}{Weak Slave}
{5101}{}{A weak, skinny slave. Not worth much money.}
{5110}{}{Weak Slave}
{5111}{}{The girl is exhausted from hard work and hunger.}
{5120}{}{Slave}
{5121}{}{A slave whose scarred wrists clearly show has spent a lot of time in chains.}
{5130}{}{Slave}
{5131}{}{A girl who appears to have accepted her fate as a slave.}
{5140}{}{Strong Slave}
{5141}{}{A strong and muscular slave, not afraid of heavy tools.}
{5150}{}{Strong Slave}
{5151}{}{A tough, strong-looking slave girl. She looks extremely serious.}

# HOMELESS
{5800}{}{Scavenger}
{5801}{}{Their clothes are torn and stained with rust, characteristic of a scavenger.}
{5810}{}{Scavenger}
{5811}{}{A woman with a blank stare. She had seen better days.}
{5820}{}{Outcast}
{5821}{}{This miserable-looking individual seems disinterested in his surroundings.}
{5830}{}{Vagabond}
{5831}{}{They look haggard, likely they have been traveling for some time.}
{5840}{}{Wanderer}
{5841}{}{A typical vagabond of the post-nuclear Wasteland.}
{5850}{}{Junkie}
{5851}{}{He appears to have given up and accepted his lot in life.}
{5860}{}{Homeless}
{5861}{}{It is no longer possible to tell what his clothes used to be.}
{5870}{}{Homeless}
{5871}{}{Dressed in rags, it doesn’t seem to bother her much.}
{5880}{}{Street Kid}
{5881}{}{Grimy and unpretentious.}
{5890}{}{Street Kid}
{5891}{}{The whole world is a game for her.}
{5900}{}{Commoner}
{5901}{}{Nothing remarkable. His eyes constantly dart around, looking for danger.}
{5910}{}{Commoner}
{5911}{}{Her expression is of boredom, clearly used to a mundane life}
{5920}{}{Dealer}
{5921}{}{A shifty looking man. He stares at you, seemingly evaluating your worth.}

#ROBOTS
{6000}{}{Robobrain}
{6001}{}{A robobrain. A very advanced robot using an organic brain as its processor.}
{6010}{}{Eye bot}
{6011}{}{An eye bot. A small floating machine armed with a laser weapon. Very fast and agile.}
{6020}{}{Mr. Handy}
{6021}{}{Mr. Handy. Moving using a thruster with multiple eyes and even more arms this robot was commonly used by US families and not only.}
{6030}{}{Sentry bot}
{6031}{}{A sentry bot. A heavy-duty military robot is usually armed with a minigun and a rocket launcher. due to its weight, it's rather slow.}
{6040}{}{Sentry bot}
{6041}{}{A sentry bot. A heavy-duty military robot is usually armed with a minigun and a rocket launcher. due to its weight, it's rather slow. This one is coated with gray paint.}
{6050}{}{Sentry bot}
{6051}{}{A sentry bot. A heavy-duty military robot is usually armed with a minigun and a rocket launcher. due to its weight, it's rather slow. Its blue paint makes it visible.}
{6060}{}{Cyber-dog}
{6061}{}{A cybernetically enhanced dog, with sharp metal claws and a strong body protected by metal plating.}
{6070}{}{Protectron}
{6071}{}{A protectron. A widespread robot with a basic directive to protect and serve. It's designed for public use, but it's still a dangerous machine.}
{6080}{}{Protectron}
{6081}{}{A protectron. A widespread robot with a basic directive to protect and serve. It's designed for public use, but it's still a dangerous machine.}

#TURRETS
{6200}{}{Laser turret}
{6201}{}{Robotized defence system.}
{6210}{}{Laser tower}
{6211}{}{Robotized defence system.}
{6220}{}{Plasma turret}
{6221}{}{Robotized defence system.}
{6230}{}{Gatling turret}
{6231}{}{Robotized defence system.}

#-------------------------------------------------------------------
#FORP - Critters
#-------------------------------------------------------------------
#RIVERDALE NPC
{8000}{}{Saul's Sniper}
{8001}{}{A cold-blooded ranged fighter. They may acquaint you with their bullets, rather than get to know you. A slaver's mark is on their forehead.}
{8010}{}{Morgan's Mercenary}
{8011}{}{Morgan's professional fighter. The abundance of scars and marks on their weapon is not from a quiet life.}
{8020}{}{Morgan's mercenary}
{8021}{}{An experienced mercenary who devoted their life to working for the "random wallet", and then for Morgan.}
{8030}{}{Steel Romulus}
{8031}{}{A tall, strong man with long gray hair. Instead of a left arm, there is a metal prosthetic from the elbow.}
{8040}{}{Fat Morgan}
{8041}{}{A very fat man in formal clothes with a strange Hawaiian shirt under a vest. It is easy to understand from his appearance that he values only personal gain in people.}
{8050}{}{Saul}
{8051}{}{A pumped-up, big black man in metal armor. His cold look suggests that he is in charge here. A large slaver's mark is visible on their forehead.}
{8100}{}{Lita}
{8101}{}{An extremely pumped-up girl with a bright acid mohawk. There are many notches on her armor, and there are old scars on her cheek.}
{8110}{}{Nikki}
{8111}{}{An extremely relaxed girl rocking a careless hairstyle in purple tones, several tattoos around her body, and shiny clean armor.}
{8120}{}{Dogman Duke}
{8121}{}{An adult man in a thick jacket with frayed sleeves. There is a scar on his eyebrow and his clothes smell of dogs.}
{8130}{}{Michelin}
{8131}{}{A girl of medium height with neat hands, clothes slightly open, and a sly smile on her face.}
{8140}{}{Dayron}
{8141}{}{A strong man in mirrored metal armor. The minigun on his back does not portray anything good-natured.}
{8150}{}{Naira}
{8151}{}{A sharp look, a predatory grin, and a strong physique. The girl has seen a lot and will surely see more.}
{8160}{}{Sebastian}
{8161}{}{A businessman in fireproof armor. There is a thoughtful look on his face, occasionally shifting to a neutral one.}
{8170}{}{Reggie}
{8171}{}{A calm man of Asian appearance. Some notches are visible on the jacket.}
{8180}{}{Jean}
{8181}{}{A man in a business suit and with a thick long mustache. They appear to look pompous. He gives off a foreign feeling.}
{8190}{}{Oswald}
{8191}{}{A strong man with a lot of bags and bags on his shoulders and legs. It seems that he is waiting for someone.}
{8200}{}{Sherry}
{8201}{}{An adult girl with a short hairstyle and several scars on her lip. Her camouflage armor looks dirty.}

#ROBOTS
{9000}{}{Robobrain}
{9001}{}{A robobrain. A multi-purpose cybernetic organism, which uses the brain of an animal or a human as a processor.}
{9010}{}{Floating eye bot}
{9011}{}{A floating eye bot. It is an armed floating robot. Usually, it carries repair or security functions.}
{9020}{}{Mr. Handy}
{9021}{}{Mr. Handy. A series of home and work robots that were very popular in the pre-war US}
{9030}{}{Sentury bot}
{9031}{}{A sentury bot. A pre-war combat unit. It has a "Friend or Foe" recognition system. They are armed with heavy weapons but lack mobility.}

#Riverdale NPC
{9040}{}{Laser turret}
{9041}{}{Robotized defence system.}
{9050}{}{Laser tower}
{9051}{}{Robotized defence system.}
{9060}{}{Plasma turret}
{9061}{}{Robotized defence system.}
{9070}{}{Gatling turret}
{9071}{}{Robotized defence system.}

#SANDBOX NPC
{9500}{}{Dubridge Lee Erwin}
{9501}{}{An old robe, patched in all possible places and reinforced with pieces of raw brahmin skin, encircles an elderly man who is also worn out by time.}
{9510}{}{Marcus Goldman}
{9511}{}{A bronze tan and cast muscles indicate that this short man will give a head start to the most daring arm wrestlers from Broken Hills.}
{9520}{}{Stephen Barr}
{9521}{}{He constantly chews some kind of chewing tobacco, spitting out the lumps that come across to the side, after which, as if nothing had happened, he continues to smile, exposing slightly yellowed, but even teeth.}
{9530}{}{Seth Sale}
{9531}{}{a master of his craft, whose carefully selected equipment immediately reveals his occupation - a powerful leather sling on his belt, a sharpened spear on his back, and a cute cape on his shoulders made of tanned leather of a fire-breathing gecko.}
{9540}{}{Andrew Mallon}
{9541}{}{He is dressed in the rags of a caravan driver with a bunch of army unloads attached to them. It smells like kerosene.}
{9550}{}{Raymond Thayer}
{9551}{}{On the belt of this ancient ghoul, a belt with a bunch of improvised tools is tightened. Just as an avid smoker always holds a cigarette in his teeth, he clutches an old, worn multitool in his hand.}
{9560}{}{Karl Ruger}
{9561}{}{If technical oil were a perfume, this far-from-smooth-skinned guy would be a trendsetter. Girded with an old blacksmith's apron.}
{9570}{}{Samuel Sax}
{9571}{}{The amazing difference between this ghoul and all the others is the preserved tufts of gray hair on a sparingly skin-covered head.}
{9580}{}{Vekselberg}
{9581}{}{A ghoul whose outstanding feature is large blacksmith's gloves, which look very funny on his puny, but very wiry hands.}
{9590}{}{Chester}
{9591}{}{A huge man with even bigger muscles, he looks down at you with a smirk.}
{9600}{}{David "Noodles" Aaronson}
{9601}{}{A tall ghoul with a light bulletproof vest thrown over his chest. He constantly looks around, slowly passing through the surroundings with his smoky gaze.}
{9610}{}{Maximilian " Max " Berkovich}
{9611}{}{A ghoul who still has a nose that gives him a more or less human appearance. He is dressed in a dirty jumpsuit, tied with a belt with various combat equipment attached to it.}
{9620}{}{Patrick "Simpleton" Goldberg}
{9621}{}{A pot-bellied ghoul wearing a straw hat. He chews something, making a measured and irritating sound.}
{9630}{}{Philip "Oblique" Stein}
{9631}{}{A distinctive feature of this ghoul is a strong difference in eye level. The left eye is completely clouded, but the right, on the contrary, has retained a human expression and depth of thought.}
{9640} {} {Baby Dominic}
{9641}{}{A miniature boy. He could be called a nice guy, if not for the fact that he is a vile, disgusting, and extremely smelly ghoul.}
{9650}{}{Alice}
{9651}{}{Very cool, but peaceful-looking, huntress.}
{9660}{}{Chase, the leader of the miners}
{9661}{}{A stocky guy in fairly clean clothes. His hands show that he had to work as a prospector at the mine.}
{9670}{}{Lincoln, the caravan master}
{9671}{}{A dusty raincoat, torn boots, a worn-out holster... you can immediately see that he is a seasoned traveler.}
{9680}{}{Sarah, the miner's storekeeper}
{9681}{}{A girl of about thirty, of pleasant appearance. You can't tell from her tanned skin that she spent a lot of time in the mines.}
{9690}{}{Strike}
{9691}{}{A guy with a smug look and a toothpick in his mouth. He is so busy with his decks of cards that he does not notice anything around.}
{9700}{}{Lana}
{9701}{}{A young girl of a very attractive appearance with appetizing forms and a playful look.}
{9710}{}{Roger, the merchant}
{9711}{}{A middle-aged guy, dressed in a dusty jacket with patches. Looks like a typical huckster.}
{9720}{}{May, a representative of the "Red Dawn"}
{9721}{}{A girl in leather armor with the badge of the organization "Red Dawn".}
{9730}{}{Jessica Rowman}
{9731}{}{A girl with freckles and even bangs. The glasses on her face add to her importance, which can not be said about her shabby suit.}

#RIVERDALE NPC
{9740}{}{Susie}
{9741}{}{A young girl with blond hair, a very beautiful one.}
{9750}{}{Terminal}
{9751}{}{A machine for issuing coupons.}
{9760}{}{Set}
{9761}{}{A stern-looking trapper. One eye is covered with a blindfold. Maybe you've seen it somewhere, or not...}
{9770}{}{Varg}
{9771}{}{A huge shaggy dog, he is majestic and calm.}
{9780}{}{Geri}
{9781}{}{A lean red wolf, it's better not to turn your back on him.}
{9790}{}{Freki}
{9791}{}{This is apparently a bitch, but her teeth are not inferior to any male.}
{9800}{}{Ray Swanson}
{9801}{}{Who will you go to when you feel so bad that you can even die? That's right, to the doctor. It's him.}
{9810}{}{Fred Bobcat}
{9811}{}{He looks like an ordinary slum dweller, although his eyes are somehow "clouded".}
{9820}{}{Abe Zuckerman}
{9821}{}{An elderly man, of a dry build.}
{9830}{}{Casino croupier}
{9831}{}{A very beautiful and sexy girl. A beautiful necklace is around her neck, and cute ballet flats are on her feet.}
{9840}{}{Casino security guard}
{9841}{}{A tall guy with a protocol mug, is watching you closely. When you come closer, he smiles at you. You are not sure that this is a smile of politeness.}
{9850}{}{Avid junkie}
{9851}{}{A hunchbacked drug addict, clearly looking at you with a mute question.}
{9860}{}{Prostitute}
{9861}{}{A worn-out woman who has clearly been visited by many.}
{9870}{}{Gandhi}
{9871}{}{A sturdy mercenary with a small smile on his face. He looks young.}
{9880}{}{Travor}
{9881}{}{A tall and young guy, looking around sternly.}
{9890}{}{Celestia}
{9891}{}{A young girl with a scar on her neck. A bandolier filled with cartridges runs through the entire chest.}
{9900}{}{Funny fat man}
{9901}{}{A strange little man, slowly stroking his bulging belly.}
{9910}{}{Bazil}
{9911}{}{A big man in a bulletproof vest, always writing something down in his notebook.}
{9920}{}{Lewis}
{9921}{}{Business guy in metal armor. It seems that he is waiting for someone.}
{9930}{}{Garfield}
{9931}{}{A tall, bald man. He looks at you with a certain impatience.}
{9940}{}{Sally}
{9941}{}{A young, well-groomed girl. She is clearly expecting someone and smiles gently.}
{9950}{}{Romulus bandit}
{9951}{}{A repulsed Romulus fighter, ready to get into a fight, even if it wasn't necessary.}
{9960}{}{Romulus bandit}
{9961}{}{A dangerous" chain dog " of the syndicate, ready to do any dirty work.}
{9970}{}{Romulus thug}
{9971}{}{A bloodthirsty killer, who by some miracle is in the service of Romulus.}
{9980}{}{Saul Shooter}
{9981}{}{A skilled slave trader fighter in a bulletproof vest. His strict look suggests that it is better not to approach him with empty conversations. The slaver's mark is on his forehead.}
{9990}{}{Saul Overseer}
{9991}{}{A slave watcher with a lot of old scars and a heavy look. The slaver's mark is on his forehead.}

#RATS
{10000}{}{Baby rat}
{10001}{}{Quite a small creature.}
{10010}{}{Small rat}
{10011}{}{Disproportionately large fangs and red eyes.}
{10020}{}{Average rat}
{10021}{}{Saliva flows profusely from her fangs.}
{10030}{}{Irradiated rat}
{10031}{}{It glows and there is almost no fur on it.}
{10040}{}{Huge rat}
{10041}{}{This evil rodent can easily jump up to your face.}
{10050}{}{Mutated rat}
{10051}{}{A mater evil creature the size of a small dog.}

#MANTIS
{10300}{}{Pathetic mantis}
{10301}{}{A small and nasty insect with long legs.}
{10310}{}{Mantis}
{10311}{}{A medium-sized body with long legs that can stab you to death.}
{10320}{}{Huge mantis}
{10321}{}{A huge insect with no less impressive claws and a massive body. The head randomly moves in different directions.}
{10330}{}{Mantis Alpha}
{10331}{}{A huge and exceptional representative of the Mantis. Impressive wings and ever-aggressively clacking claws.}

#ANTS
{10600}{}{Ant-worker}
{10601}{}{A small creature, always wagging on the move.}
{10610}{}{Ant-soldier}
{10611}{}{A large creature, with medium-sized claws and long antennae. The impressive mandibles move smoothly.}
{10620}{}{Drone Ant}
{10621}{}{This hefty ant looks especially disgusting and over-sized. The body is disproportionately large, which makes it look unpleasant.}
{10630}{}{Ant-guard}
{10631}{}{This is an Alpha male: his shell looks very thick, and his mouth is huge. Powerful claws, long mandibles, and huge eyes.}

#SPOREPLANTS
{10900}{}{Predatory plant}
{10901}{}{A strange, eyeless mouth is held on a thick stalk.}
{10910}{}{Huge predatory plant}
{10911}{}{A huge eyeless mouth with numerous appendages on the sides. The stem is covered with thorns, and the plant itself is extremely tall.}

#BRAHMINS
{11200}{}{Brahmin calf}
{11201}{}{A small and weak brahmin calf. He looks skinny and hungry.}
{11210}{}{Brahmin}
{11211}{}{Two heads, four hooves, and one big belly. One of the heads has horns.}
{11220}{}{Big Brahmin}
{11221}{}{A large brahmin with massive heads and body.}
{11230}{}{Wild Brahmin}
{11231}{}{A thin and shabby brahmin. The body of a brahmin is worn out by wild nature.}
{11240}{}{Furious Brahmin}
{11241}{}{A large brahmin of a dark color. The horns are longer than those of an ordinary brahmin, and the hooves look more massive.}

#DOGS
{11500}{}{Weak dog}
{11501}{}{A skinny animal, ribs, and traces of long starvation are visible on the body. The fur has thinned.}
{11510}{}{Dog}
{11511}{}{An ordinary mongrel of medium size.}
{11520}{}{Tough dog}
{11521}{}{A lot of old scars and wounds make it clear that this dog has been through a lot.}
{11530}{}{Big dog}
{11531}{}{A large dog with a rough and wild face. Drool drips from the fangs, and dirt is visible on the paws.}
{11540}{}{Puppy}
{11541}{}{A small creature with small paws, a long muzzle, and short fur.}

#WOLVES
{11800}{}{Weak wolf}
{11801}{}{A small creature that somewhat resembles a dog. Sparse fur, small fangs, and claws on the paws. He looks exhausted.}
{11810}{}{Wolf}
{11811}{}{A medium-sized creature. Good skin, strong build, long and elongated muzzle with sharp teeth in the mouth.}
{11820}{}{Tough wolf}
{11821}{}{A battered wolf. There are multiple scars on the skin and dried blood on the paws.}
{11830}{}{Alpha wolf}
{11831}{}{A huge and old wolf. His large build and extremely long claws and teeth make it clear that he has lived a lot. There is an abundance of old scars and relatively fresh wounds on the wolf's skin.}
{11840}{}{Puppy}
{11841}{}{A small creature with small paws, a long muzzle, and gray fur. The presence of sharp fangs gives him a wolf puppy.}

#PIG RATS
{12100}{}{Pig rat}
{12101}{}{It makes sounds that resemble a squeak and a grunt in one. A nasty little carcass on clawed paws.}
{12110}{}{Huge Pig rat}
{12111}{}{A huge fleshy carcass on muscular paws with claws and sharp teeth in its mouth.}
{12120}{}{Pig rat Alpha}
{12121}{}{An incredibly large and muscular pig-rat. His body shows an abundance of unpleasant scars and old wounds.}

#MOLE RATS
{12400}{}{Mole rat}
{12401}{}{A small animal on four legs with claws and sharp teeth. Long antennae are visible on the muzzle and tail.}
{12410}{}{Huge Mole rat}
{12411}{}{A huge and extremely fleshy beast. The whole skin is in folds of dark pink color.}
{12420}{}{Mole rat Alpha}
{12421}{}{A huge mole-rat with particularly long claws. The teeth are extremely sharp and large, and numerous scars are visible on the body.}

#SILVER GECKOS
{12700}{}{Silver Gecko}
{12701}{}{A small silvery gecko. Small paws on a relatively large body.}
{12710}{}{Silver predatory Gecko}
{12711}{}{A wiry gecko with a long tail. In the mouth, frequent and very sharp teeth are visible.}
{12720}{}{Large silver Gecko}
{12721}{}{A very large gecko, compared to its fellows. Long paws with dangerous claws, and iridescent skin.}
{12730}{}{Silver Gecko Alpha}
{12731}{}{The largest silver gecko. Its large red eyes are bloodshot, and small thorns are observed on the skin.}

#GOLDEN GECKOS
{13000}{}{Golden Gecko}
{13001}{}{A small and nimble golden gecko. The small tail always moves in time with the gait.}
{13010}{}{Large golden Gecko}
{13011}{}{A large creature with a long tail and sharp teeth. Its golden skin shimmers beautifully in the sun.}
{13020}{}{Golden Gecko Alpha}
{13021}{}{The largest golden gecko. His large red eyes are bloodshot, and there are frequent scars and scars on his skin.}

#FIREGECKOS
{13300}{}{Fire Gecko}
{13301}{}{A small, but extremely colorful beast. A light smoke comes from the creature's nostrils.}
{13310}{}{Fire Gecko Alpha}
{13311}{}{An extremely large fire gecko with an impressive build and a whole "fountain" of smoke coming out of its nostrils. The mouth always opens, releasing streams of fire.}

#SCORPS
{13900}{}{Radscorpion}
{13901}{}{A medium-sized scorpion. Venom drips from its tail and sting. Massive pincers and fast legs.}
{13910}{}{Tough Radscorpion}
{13911}{}{A large scorpion with a large and swollen sting. A strong and massive shell.}
{13920}{}{Small Radscorpion}
{13931}{}{A small scorpion with not very impressive pincers and a small tail.}

#BLACKSCORPS
{14200}{}{Small Black Scorpion}
{14201}{}{A small scorpion with a long tail and a black shell.}
{14210}{}{Black Radscorpion}
{14211}{}{A large black scorpion with a thick shell and a massive hanging tail. The sting of creation oozes poison.}

#DEATHCLAWS
{14500}{}{Deathсlaw Cub}
{14501}{}{A small humanoid creature with long paws, from which sharp claws are visible.}
{14510}{}{Young Deathclaw}
{14511}{}{A medium-sized creature with light hair and small horns.}
{14520}{}{Large Deathclaw}
{14521}{}{A big and muscular scary creature. Long and extremely sharp claws on the paws. It has yellow and curved fangs.}
{14530}{}{Deathclaw Alpha}
{14531}{}{A huge death claw with long curved horns and an abundance of scars all over its body. Darkened color and bulky paws.}
{14540}{}{Deathclaw Hunter}
{14541}{}{A huge death claw of gray color. A curved body, powerful paws, and curved horns aimed forward.}

#SWAMPLURKERS
{14800}{}{Weak Mirelurk}
{14801}{}{A small creature in a thick shell and massive claws.}
{14810}{}{Mirelurk}
{14811}{}{A smelly, large, and bulky creature, covered with a solid, strong shell. Sharp claws look extremely dangerous and sharp.}
{14820}{}{Mirelurk Alpha}
{14821}{}{Incredibly massive and strong, an exceptional swamper. Its huge shell is covered with swamp waste and an abundance of algae.}

#ALIENS
{15100}{}{Strange egg}
{15101}{}{A strange, rounded egg of unknown origin.}
{15110}{}{Wanamingo}
{15111}{}{This creature has neither eyes nor fingers. Vile long boneless tentacles come out of the body.}
{15120}{}{Large Wanamingo}
{15121}{}{A big and scary eyeless creature with long, nasty tentacles.}
{15130}{}{Wanamingo Matriach}
{15131}{}{Wanamingo's Matriach. Slime flows from the mouth of a hefty Wanamingo, and the shiny skin has a dark gray hue.}

#MOTERALIENS
{15400}{}{Wanamingo Matriach}
{15401}{}{Wanamingo's Matriach. Slime flows from the mouth of a hefty Wanamingo, and the shiny skin has a dark gray hue.}

#FLOATERS
{15700}{}{Small Floater}
{15701}{}{A small snake-like thing, slowly crawling on its tail. Instead of a face, the creature has a semblance of a large mouth.}
{15710}{}{Floater}
{15711}{}{An ugly creature with a huge horizontal mouth full of teeth.}
{15720}{}{Ugly Floater}
{15721}{}{He stinks abominably, and his front mouths bleed profusely with mucus.}
{15730}{}{Floater Alpha}
{15731}{}{A huge Floater with several huge mouths full of an abundance of sharp teeth in acrid mucus. The creature stinks very much.}

#CENTAURS
{16000}{}{Small centaur}
{16001}{}{A small, but extremely vile creature. It moves on six human hands. Various disfigured heads are adorned on long necks.}
{16010}{}{Centaur}
{16011}{}{Muddy mucus flows from a long tentacle-like tongue. Two disfigured heads and what looked like intestines hanging out of the body and dragging behind.}
{16020}{}{Ugly Centaur}
{16021}{}{An extremely unpleasant sight. A creature with different heads, and an abundance of organs located outside. A viscous mucus flows through the body.}
{16030}{}{Alpha Centaur}
{16031}{}{A huge centaur is supported by ten human hands. Three ugly heads and an equally disfigured semblance of a body.}

#PRIMITIVES
{16300}{}{Skinny savage}
{16301}{}{A skinny savage. This savage seems to have not eaten for a very long time.}
{16310}{}{Skinny savage}
{16311}{}{A skinny savage. She looks like a skin-covered skeleton. Well, or on a fresh ghoul.}
{16320}{}{Dirty savage}
{16321}{}{A dirty savage. This one seems to be digging in the ground all day.}
{16330}{}{Smeared savage}
{16331}{}{A smeared savage. Perhaps the clay on her face and hair is an ornament.}
{16340}{}{Tribal Elder}
{16341}{}{The elder of the tribe. It seems that he is one of the leaders of the tribe.}
{16350}{}{Tribal Elder}
{16351}{}{The elder of the tribe. It seems that he is one of the leaders of the tribe.}
{16360}{}{Tribe Shaman}
{16361}{}{A shaman of the tribe. A lot of amulets and an intoxicated look hint to you that you are facing a strong sorcerer.}
{16370}{}{Tribe hunter}
{16371}{}{A tribe hunter. Have you ever seen a trapper without pants? Here it is.}
{16380}{}{Tribe hunter}
{16381}{}{A tribe huntress. It is not as accessible as it seems.}
{16390}{}{Tribe warrior}
{16391}{}{A tribe warrior. Strong and agile, he will protect his tribe until his last breath.}
{16400}{}{Tribe worrior}
{16401}{}{A tribe warrior. War paint, wild grin, and naked tits, everything is as it should be.}

#CANNIBALS & RIPPERS
{16600}{}{Vile cannibal}
{16601}{}{A vile cannibal. He looks at you with anger and hunger. He walks quickly in your direction, sniffing loudly and drooling.}
{16610}{}{Dirty cannibal}
{16611}{}{A dirty cannibal. She looks at you with a hungry look. Her hair is tousled, some teeth are missing.}
{16620}{}{Bearded cannibal}
{16621}{}{A bearded cannibal. He looks at you greedily. This faggot is going to eat you!}
{16630}{}{Crazy cannibal}
{16631}{}{A mad cannibal. His gaze runs around the area. He snaps his teeth, trampling on the ground.}
{16640}{}{Cannibal farmer}
{16641}{}{The cannibal farmer. He looks at you with hungry eyes. His overalls are stained with blood, and his straw hat has been bitten by someone.}
{16650}{}{Hungry cannibal}
{16651}{}{A hungry cannibal. He looks at you with hungry eyes. Saliva flows from his mouth, and his ribs are noticeably visible under the skin.}
{16660}{}{Cannibal slave}
{16661}{}{A cannibal slave. She looks at you with a hungry look. A broken collar hangs around her neck.}
{16670}{}{Bald cannibal}
{16671}{}{A bald cannibal. He looks at you angrily. Steam is coming from his red top he will fry a piece of your leg there.}
{16680}{}{Cannibal farmer}
{16681}{}{The cannibal farmer. She looks at you with a hungry look. MEAT is written in blood on her apron.}
{16690}{}{Strange guy}
{16691}{}{A strange guy. His face is hidden by a hood. The torn robe has areas with dried blood.}
{16700}{}{Chinese cannibal}
{16701}{}{A Chinese is a cannibal. He looks at you as if you are a fresh fish. Knives of different sizes are attached to the vest and pants.}
{16710}{}{Strange black guy}
{16711}{}{A strange black guy. He wheezes softly. Blood is dripping from his mouth, and for some reason, his pupils have rolled up.}
{16720}{}{Tough cannibal}
{16721}{}{A tough cannibal. He looks at you, drooling bloody. It looks like he's even growling.}
{16730}{}{Pale cannibal}
{16731}{}{A pale cannibal. He looks at you with hungry eyes. His skin is almost white, very strange for an inhabitant of the Wasteland.}
{16740}{}{Mutated cannibal}
{16741}{}{A mutated cannibal. He looks at you with a hungry look. Half of his head is rotting alive, the other half is full of purulent growths.}
{16750}{}{Small cannibal}
{16751}{}{A small cannibal. He looks at you with hungry eyes. This little faggot most likely feeds on human flesh.}
{16760}{}{Cute cannibal}
{16761}{}{A cute cannibal. She looks at you with a hungry look. Her clothes are already completely worn out, which makes her large breasts visible.}
{16770}{}{Fat cannibal}
{16771}{}{A fat cannibal. She looks at you with a sinister smile. Her clothes are made of different skins, and they are painted with mysterious symbols made of blood.}
{16780}{}{Elderly cannibal}
{16781}{}{An elderly cannibal. He looks at you coolly. The white-haired old man chews his lips.}
{16790}{}{Ripper Hunter}
{16791}{}{The ripper hunter. It looks like he needs you alive.}
{16800}{}{Ripper Hunter}
{16801}{}{The ripper hunter. Agile and fast. It seems that she is not averse to "having fun" with you.}
{16810}{}{Ripper-slaughterer}
{16811}{}{The Ripper-slaughterer. Strongly built. His mouth is twisted in a carnivorous grin.}
{16820}{}{Ripper-slaughterer}
{16821}{}{The Ripper-slaughterer. A strong woman. Her face is smeared with blood. Most likely it's not her blood.}
{16830}{}{Ripper-flesher}
{16831}{}{The Ripper-flesher. An aggressive member of the Ripper tribe.}
{16840}{}{Ripper-flesher}
{16841}{}{The Ripper-flesher. A half-naked woman. Looks at you predatory.}
{16850}{}{Ripper Warrior}
{16851}{}{A Ripper warrior. His torso is hung with ornaments made from the bones of defeated enemies.}
{16860}{}{Ripper Warrior}
{16861}{}{A Ripper warrior. Her eyes are clouded with bloodlust.}
{16870}{}{Ripper Priest}
{16871}{}{The Ripper priest. His neck is decorated with a necklace of phalanges of human fingers.}
{16880}{}{Patriarch of the Rippers}
{16881}{}{The patriarch of the Rippers. A tall and domineering man. His face is decorated with ritual scars. The rest of the Rippers look at him as a living god.}
{16890}{}{Ripper Matriarch}
{16891}{}{The Ripper Matriarch. A powerfully built woman in clothes made of human skin. The other Rippers respectfully lower their eyes in her presence.}

#GANGS
{16900}{}{Junkie}
{16901}{}{A junkie. A true drug addict. His hands are shaking, and his eyes are running.}
{16910}{}{Junkie}
{16911}{}{A junkie. Judging by her absent look, she's been ready to do anything for a dose for a long time.}
{16920}{}{Scum}
{16921}{}{A scum. A ragamuffin who tries to live at someone else's expense.}
{16930}{}{Scum}
{16931}{}{A scum. The absence of principles is her main principle!}
{16940}{}{Small punk}
{16941}{}{A small punk. He will not hesitate to deprive you of your wallet... and your life as well.}
{16950}{}{Small punk} 
{16951}{}{Small punk. She is used to playing by the rules of the wasteland.}
{16960}{}{Rogue}
{16961}{}{A rogue. A petty thief.}
{16970}{}{Rogue}
{16971}{}{A rogue. Sharp-tongued, and so is her switchblade!} 
{16980}{}{Scumbag}
{16981}{}{A scumbag. He's ready to gut you for a couple of caps.}
{16990}{}{Robber}
{16991}{}{A robber. Unprincipled and very dangerous.}
{17000}{}{Thug}
{17001}{}{A thug. Most likely, this psychopath is going to spill your blood!}
{17010}{}{Madman}
{17011}{}{A madman. For him, cutting a child's throat is as easy as pissing.}
{17020}{}{Authority}
{17021}{}{Authority. A local authority. To them, you are a pile of crap.}
{17030}{}{Authority}
{17031}{}{Authority. A local authority. To them, you are a pile of crap.}

#RAIDERS
{17200}{}{Raider scavenger}
{17201}{}{A raider scavenger. You would have confused them with a hobo if it wasn't for the weapon pointed at you.}
{17210}{}{Raider scavenger}
{17211}{}{A raider scavenger. You would have confused them with a hobo if it wasn't for the weapon pointed at you.}
{17220}{}{Crazy raider}
{17221}{}{A crazy raider. A completely insane person.}
{17230}{}{Crazy raider}
{17231}{}{A crazy raider. A completely insane person.}
{17240}{}{Kamikaze Raider}
{17241}{}{A kamikaze raider. His outlook just screams for this person to be shot.}
{17250}{}{Kamikaze Raider}
{17251}{}{A kamikaze raider. His outlook just screams for this person to be shot.}
{17260}{}{Raider goon}
{17261}{}{A raider goon. Do not fall under his blows.}
{17270}{}{Raider goon}
{17271}{}{A raider goon. Do not fall under his blows.}
{17280}{}{Raider}
{17281}{}{A raider. A raider or a simple bandit? What's the difference?}
{17290}{}{Raider}
{17291}{}{A raider. A raider or a simple bandit? What's the difference?}
{17300}{}{Raider Shooter}
{17301}{}{A raider shooter. You are at gunpoint.}
{17310}{}{Raider Shooter}
{17311}{}{A raider shooter. You're in the crosshairs.}
{17320}{}{Raider madman}
{17321}{}{A raider madman. This one is eager to fight on the front line and looks very dangerous.}
{17330}{}{Raider madman}
{17331}{}{A raider madman. This one is eager to fight on the front line and looks very dangerous.}
{17340}{}{Elite raider}
{17341}{}{An elite raider. The elite of their gang.}
{17350}{}{Elite raider}
{17351}{}{An elite raider. The elite of their gang.}
{17360}{}{Professional raider}
{17361}{}{A professional raider. Such people usually have a lot of battles behind them.}
{17370}{}{Professional raider}
{17371}{}{A professional raider. Such people usually have a lot of battles behind them.}
{17380}{}{Professional raider}
{17381}{}{A professional raider. Such people usually have a lot of battles behind them.}
{17390}{}{Legendary Raider Leader}
{17391}{}{The legendary raider leader. One of the representatives of the legendary "Khans" gang. He is very strong.}

#SLAVERS
{17500}{}{Rookie slaver}
{17501}{}{A rookie slaver. A young guy with the slaver's mark on his forehead. A twitchy scoundrel who wants to prove himself.}
{17510}{}{Rookier slaver}
{17511}{}{A rookie slaver. A young girl with the slaver's mark on her forehead. A twitchy bitch who wants to prove herself.}
{17520}{}{Slaver bull}
{17521}{}{A slaver bull. A strong man with the mark of a slaver on his forehead. He was audaciously examining you as if he was estimating your value.}
{17530}{}{Slaver bull}
{17531}{}{A slaver bull. A strong man with the mark of a slaver on his forehead. Dirty hands, dirty conscience, and a predatory look describe him as a "good businessman".}
{17540}{}{Slaver shooter}
{17541}{}{A slaver shooter. Apparently, this is one of the "beaters " of the slavers. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17550}{}{Slaver shooter}
{17551}{}{A slaver shooter. Apparently, this is one of the "beaters " of the slavers. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17560}{}{Veteran slaver}
{17561}{}{A veteran slaver. An experienced bandit with the mark of a slaver on his forehead. It seems that he knows the price of everyone and you would not like to be in the zone of his "interest".}
{17570}{}{Veteran slaver}
{17571}{}{A veteran slaver. An experienced robber with the brand of a slaver on her forehead. It seems that she knows the price of everyone and you would not like to be in the zone of her "interest".}
{17580}{}{Slavers Chief}
{17581}{}{The head of the slavers. A good-looking businessman with the slaver mark on his forehead. He knows a lot about "labor parties" and the system of motivations.}
{17590}{}{Slavers Chief}
{17591}{}{The head of the slavers. A handsome-looking man with the slaver mark on his forehead. This "Black Lord" has broken a lot of destinies.}

#CARAVANS
{17800}{}{Random traveler}
{17801}{}{A random traveler. You do not let go of the feeling that this person should not be here at all.}
{17810}{}{Random traveler}
{17811}{}{A random traveler. You do not let go of the feeling that this person should not be here at all.}
{17820}{}{Rookie caravan guard}
{17821}{}{A rookie caravan guard. Clearly feeling insecure.}
{17830}{}{Caravan guard rookie}
{17831}{}{A caravan guard rookie. Clearly feeling insecure.}
{17840}{}{Heavy caravan guard}
{17841}{}{A heavy caravan guard. This guy is huge!}
{17850}{}{Heavy caravan guard}
{17851}{}{A heavy caravan guard. This guy is huge!}
{17860}{}{Veteran caravan guard}
{17861}{}{A veteran caravan guard. This person is obviously experienced.}
{17870}{}{Veteran caravan guard}
{17871}{}{A veteran caravan guard. This person is obviously experienced.}
{17880}{}{Caravan guard shooter}
{17881}{}{A caravan guard shooter. They are squinting at the terrain.}
{17890}{}{Caravan guard shooter}
{17891}{}{A caravan guard shooter. They are squinting at the terrain.}
{17900}{}{Caravan leader}
{17901}{}{A caravan leader. It seems that this person is in charge of everything here.}
{17910}{}{Caravan leader}
{17911}{}{A caravan leader. It seems that this person is in charge of everything here.}

#STRANGERS
{18100}{}{Homeless}
{18101}{}{A homeless person. Just a stinking hobo. The Wasteland is filled with them. Looks beaten up, and behaves nervously.}
{18110}{}{Homeless}
{18111}{}{A homeless person. A dirty woman with a downtrodden look. She reeks of misery.}
{18120}{}{Scavenger}
{18121}{}{Scavenger. An ordinary collector. He jerkily looks around, looking for something profitable.}
{18130}{}{Scavenger}
{18131}{}{Scavenger. A typical collector. She jerkily looks around, looking for something profitable.}
{18140}{}{Lowlife}
{18141}{}{An angry beggar. Such kind roams every slum. He is busy with something and tries not to look at you.}
{18150}{}{Lowlife}
{18151}{}{An angry beggar. Such kind roams every slum. She is busy with something and tries not to look at you.}
{18160}{}{Hunter}
{18161}{}{A hunter. An experienced trapper with a weathered face and a characteristic squint.}
{18170}{}{Hunter}
{18171}{}{A hunter. An experienced trapper with a weathered face and a characteristic squint.}
{18180}{}{Wanderer}
{18181}{}{A wanderer. An ordinary traveler from the Wasteland. It's not certain from where he comes, but judging by the torn burlap on him it seems like he has traveled a long way.}
{18190}{}{Wanderer}
{18191}{}{A wanderer. An ordinary traveler from the Wasteland. It's not certain from where he comes, but judging by the torn burlap on him it seems like she has traveled a long way.}
{18200}{}{Outcast}
{18201}{}{An outcast. A stinking hobo. The Wasteland is filled with them. This one looks sick, or maybe he is just a freak.}
{18210}{}{Outcast}
{18211}{}{An outcast. A decrepit old man, living out his life. A pitiful sight.}
{18220}{}{Enforcer}
{18221}{}{An enforcer. An experienced mercenary with strong ammunition. Armed and most likely dangerous.}
{18230}{}{Enforcer}
{18231}{}{An enforcer. An experienced mercenary with strong ammunition. Armed and most likely dangerous.}

#GHOULS
{18400}{}{Frail ghoul}
{18401}{}{A frail ghoul. Skin and bones. Literally.}
{18410}{}{Frail ghoul}
{18411}{}{A frail ghoul. Skin and bones. Literally.}
{18420}{}{Mangy ghoul}
{18421}{}{A mangy ghoul. From the fallen pieces of his skin, it would be quite possible to sew a bag.}
{18430}{}{Mangy ghoul}
{18431}{}{A mangy ghoul. From the fallen pieces of his skin, it would be quite possible to sew a bag.}
{18440}{}{Nasty ghoul}
{18441}{}{A nasty ghoul. The very sight of this one makes you sick.}
{18450}{}{Nasty ghoul}
{18451}{}{A nasty ghoul. The very sight of this one makes you sick.}
{18460}{}{Dirty Ghoul}
{18461}{}{A dirty ghoul. The dirt stuck to the walking skeleton made this one less noticeable.}
{18470}{}{Dirty Ghoul}
{18471}{}{A dirty ghoul. The dirt stuck to the walking skeleton made this one less noticeable.}
{18480}{}{Disgusting ghoul}
{18481}{}{A disgusting ghoul. It looks better through a scope.}
{18490}{}{Disgusting ghoul}
{18491}{}{A disgusting ghoul. It looks better through a scope.}
{18500}{}{Rotting ghoul}
{18501}{}{A rotting ghoul. Your nose has never smelled anything more terrible.}
{18510}{}{Rotting ghoul}
{18511}{}{A rotting ghoul. Your nose has never smelled anything more terrible}
{18520}{}{Glowing Ghoul}
{18521}{}{A glowing ghoul. How about a couple of extra rads?}
{18530}{}{Glowing Ghoul}
{18531}{}{A glowing ghoul. How about a couple of extra rads?}
{18540}{}{Fast Ghoul}
{18541}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18550}{}{Fast Ghoul}
{18551}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18560}{}{Fast Ghoul}
{18561}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18570}{}{Fast Ghoul}
{18571}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18580}{}{Fast Ghoul}
{18581}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18590}{}{Fast Ghoul}
{18591}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}

#SUPERMUTANTS
{18700}{}{Super mutant}
{18701}{}{A Super mutant. A huge chunk of muscles. These creatures do not have many reasons to be called intelligent.}
{18710}{}{Super mutant}
{18711}{}{A Super mutant. The living horror of the Wasteland. Stupid, angry, stinky.}
{18720}{}{Super mutant goon}
{18721}{}{A Super mutant goon. A huge carcass consisting of muscles, anger, and light armor that seems very dangerous. He looks around with a dumb stare in search of something to crush.}
{18730}{}{Super mutant goon}
{18731}{}{A Super mutant goon. The creature is impatiently marking time. It wants to beat, break, and destroy... and the sooner - the better.}
{18740}{}{Super mutant berserker}
{18741}{}{A Super mutant berserker. The body of this creature is covered with bruises. It seems that this creature has gone completely mad from pain and rage.}
{18750}{}{Super mutant berserker}
{18751}{}{A Super mutant berserker. Its whole body is covered with scars. This crazy creature has emerged victorious from many fights. It is very dangerous.}
{18760}{}{Super mutant master}
{18761}{}{A Super mutant master. The creature is covered with armor made of rusty sheets of metal and chains. The armor looks nasty and rattles when moving, but the monster seems to like it very much.}
{18770}{}{Super mutant master}
{18771}{}{A Super mutant master. The armored monster looks no smarter than the rest of its kind, but it clearly feels more important.}
{18780}{}{Nightkin}
{18781}{}{A nightkin. A huge chunk of muscles. This creature has a surprisingly meaningful and piercing look.}
{18790}{}{Nightkin}
{18791}{}{A nightkin. A huge chunk of muscles. This creature has a meaningful and piercing look.}
{18800}{}{Nightkin berserker}
{18801}{}{A nightkin berserker. This intelligent and experienced creature has emerged victorious from many fights. It is very dangerous.}
{18810}{}{Nightkin berserker}
{18811}{}{A nightkin berserker. This intelligent and experienced creature has emerged victorious from many fights. It is very dangerous.}
{18820}{}{Nightkin master}
{18821}{}{A nightkin master. A monster with a smart and calm look. You feel small in front of him not only in terms of height. This creature is "bigger" than anything you could become.}
{18830}{}{Nightkin master}
{18831}{}{A nightkin master. A monster with a smart and calm look. You feel small in front of him not only in terms of height. This creature is "bigger" than anything you could become.}
{18840}{}{Nightkin sniper}
{18841}{}{A nightkin sniper. A clever and cunning creature with honed movements and a huge rifle in his hands.}
{18850}{}{Nightkin sniper}
{18851}{}{A nightkin sniper. A clever and cunning creature with honed movements and a huge rifle in his hands.}

#POSEYDON NPC
{20000}{}{Immortal John}
{20001}{}{A battered robot with a brain in a flask.}
{20010}{}{Cook}
{20011}{}{A fat, sweaty man with a sly look in his lustful eyes. He wears an apron and a chef's hat.}
{20020}{}{Professor Kevorkian}
{20021}{}{The wrinkled face shows interest, irritation, and fatigue. He also wears glasses.}
{20030}{}{Hugo "The Hog" Ruth}
{20031}{}{A big man with a red face.}
{20040}{}{Grave}
{20041}{}{A gaunt man with a weathered face. The owner of a luxurious horseshoe mustache.}
{20050}{}{Ash Tom}
{20051}{}{This ghoul is completely black as if woven from dirt and ashes.}
{20060}{}{Chad}
{20061}{}{A fat, pot-bellied and broad-shouldered man in a bloody apron. His face does not shine with intelligence.}
{20070}{}{Booger}
{20071}{}{A very short young guy.}
{20080}{}{Chog}
{20081}{}{A huge, even for a super mutant, and terrible monster.}
{20090}{}{Jessie "Saint" Castor}
{20091}{}{A tall, dark, hungover-looking man with eternal stubble on his face.}
{20100}{}{Shawn "Rattle" Marshal}
{20101}{}{An unusually luminous ghoul.}
{20110}{}{Curtis "Cowboy" Raidler}
{20111}{}{A young bearded man, in a worn jacket and a cowboy hat.}
{20120}{}{Bryce "Trumpet"}
{20121}{}{A tall, thin man with pale skin. He lacks a middle finger on the left hand. There is a metal pipe in a case on his belt.}
{20130}{}{Montgomery "Monty" Tonato}
{20131}{}{A young man with a stern and strong-willed expression on his face. A thin white stripe is visible on the cheek - must be a scar from a knife.}
{20140}{}{Gwen Tyler}
{20141}{}{A pretty young girl, sparkling with a snow-white smile.}
{20150}{}{Donny "Cleaver" Tracho}
{20151}{}{A tall Mexican man with a face scarred by wrinkles and wind. He wears an anchor-style beard.}
{20160}{}{Garfield "Splinter" Nelson}
{20161}{}{A cheerful-looking red-haired guy.}
{20170}{}{Nera "Trudy" Argwire}
{20171}{}{A brunette with a cold look.}
{20180}{}{Oliver "Iceman" Remy}
{20181}{}{He grins ironically, looking at you.}
{20190}{}{Charon "Salted" Diklane}
{20191}{}{An extremely well-preserved ghoul in a military uniform.}
{20200}{}{Crook Mackenzie}
{20201}{}{A thin, long-armed, and long-legged guy with dirty corn-colored hair.}
{20210}{}{Sunshine "Sunny" 209}
{20211}{}{It looks dangerous, if you don't know what it is and why it is here then it's better not to touch it.}
{20220}{}{Molly Bloom}
{20221}{}{A very sexy and attractive girl.}
{20230}{}{Diamond "Page" Dallas}
{20231}{}{A large man with age. His curly hair has long been covered with a touch of gray.}
{20240}{}{Merfus "Old " MacDill}
{20241}{}{A red beard, gray temples, and a strained smile can be seen on his face.}
{20250}{}{Bam-Bam Bigelow}
{20251}{}{Short-haired and smooth-shaven stocky man.}
{20260}{}{Brody Travis}
{20261}{}{His glasses are taped to his skull with duct tape, he looks cunning and arrogant.}
{20270}{}{Turok}
{20271}{}{An unshaven, short-haired, sullen dude who actively offers you to trade and buy "unique things".}
{20280}{}{Garry}
{20281}{}{Twitchy appearance, torn robe, and a large backpack on his back... His hands are constantly black.}
{20290}{}{Douglas "Bigwig"}
{20291}{}{A neat-looking elderly man in a pre-war suit, he wears glasses and a kippah.}
{20300}{}{Vinnie "Broad" Fletcher}
{20301}{}{Big guy, looks you straight in the eyes, heavy voice and protruding lower lip.}
{20310}{}{Burger Chuck}
{20311}{}{A Negro in a dark unbuttoned raincoat and a hat, a man of unpretentious and hard work.}
{20320}{}{Tuco "Amigo" Salamanca}
{20321}{}{A strong-looking Mexican. He glares at you as if you owe him money.}
{20330}{}{Chung Daishu}
{20331}{}{A small Asian man with short blond hair. He has a sword on the belt.}
{20340}{}{Tommy "Titty"}
{20341}{}{A short man with soft features on a round face with an irritated and wary expression.}
{20350}{}{Mr. Shaw}
{20351}{}{A huge, obese man with a wig on his head and clown makeup on his face. He scares you with his appearance.}

#POSEYDON GUARDS
{21000}{}{"Poseidon" SDU private}
{21001}{}{It is obvious that these mercenaries do not get money for nothing. It is better not to mess with them.}
{21010}{}{"Poseidon" SDU private}
{21011}{}{It is obvious that these mercenaries do not get money for nothing. It is better not to mess with them.}
{21020}{}{Tower Guard}
{21021}{}{A stern man, evaluates you with a professional look of a killer. It's good that he's hired to protect instead of killing.}

#LARS'S GANG
{21300}{}{Thunder Dave}
{21301}{}{It is clear that he is a notorious pirate and a thug. His armor is covered with traces of many battles.}
{21310}{}{Black Dog}
{21311}{}{A strong man with a red, faded bandanna around his neck. He looks with a squint.}
{21320}{}{Zhoh}
{21321}{}{A long nigger of a strong build. He occasionally spits on the ground when talking.}
{21330}{}{Israel Hanks}
{21331}{}{A gloomy, silent man, looks at you with an appraising glance, as if he is calculating the price of your belongings.}
{21340}{}{Carnat}
{21341}{}{First impression shows you a cheerful guy with an eternal smile. However, the thirst for profit and fame is visible in his eyes.}

#KASTOR'S CLERGY
{21400}{}{Guardian of the Faith Thomas "Blessed" Manson}
{21401}{}{A man in a dirty robe, on which the lead symbol of the "Atom" cult is visible.}
{21410}{}{Guardian of the Faith Martha "The Voice" Swift}
{21411}{}{A frail figure in a dirty oversized Atom-themed robe. She looks at you with light gray eyes from under the shadow of the hood.}
{21420}{}{Guardian of the Faith Harold "Lazarus" Shipman}
{21421}{}{A bearded, smiling man in a dirty Atom robe, on which purple traces are visible.}
{21430}{}{Zealot of Atom}
{21431}{}{A gloomy person in a scarlet robe with an Atom symbol on it, his face is hidden by an iron mask with a slit for eyes.}
{21440}{}{Zealot of Atom}
{21441}{}{A gloomy person in a scarlet robe with an Atom symbol on it, his face is hidden by an iron mask with a slit for eyes.}

#SAN FRANCISCO NPC
{21500}{}{Hanayama Kaoru}
{21501}{}{A huge Asian, a real giant. He is dressed in a pre-war three-piece suit and wears sneakers.}
{21510}{}{Akisame Koetsuji}
{21511}{}{A short calm-looking Japanese man. There is wisdom in his eyes.}
{21520}{}{Revi Ruete}
{21521}{}{A young beautiful Japanese woman with a bold and cheeky look.}
{21530}{}{Bang Shiruba}
{21531}{}{A stooped, gray-haired old man with a bushy mustache. It seems to you that he is evaluating you.}
{21540}{}{Lo-Peng}
{21541}{}{This Chinese man is quite famous in the city. You've definitely heard something about Master Lo-Peng.}
{21550}{}{Lam Chin Ying}
{21551}{}{He looks at you intently, almost with hostility.}
{21560}{}{Sammo Hung}
{21561}{}{A fat Asian man with a funny face and a stern look.}
{21570}{}{Donnie Yen}
{21571}{}{A tall Chinese man in a strict traditional outfit of the century before last.}
{21580}{}{Mr. Moloch}
{21581}{}{An incredibly large and athletic man, you are amazed by the width of his shoulders.}
{21590}{}{Arnold Mitch}
{21591}{}{A man in an oiled jumpsuit, and welder's glasses are visible on his head among a pile of unwashed hair.}
{21600}{}{Valdis Goose}
{21601}{}{An obese man who stinks of fish. Maybe he came from the depths of the ocean? You have no idea.}
{21610}{}{Sigurd Kroft}
{21611}{}{A short, dark-haired man who looks at you like a merchant looks at a customer.}
{21620}{}{Amelie Croft}
{21621}{}{A middle-aged woman with huge bags under her eyes. You can see that she is very tired, but the smile on her face is quite sincere.}
{21630}{}{Billy Lee}
{21631}{}{The Dragon's Follower. This guy reminds you of someone, or maybe he has a brother. A big, obviously strong fighter.}
{21640}{}{Jimmy Lee}
{21641}{}{The Dragon's Follower. It seems like you've seen him before, or maybe he has a twin brother. He looks very strong.}
{21650}{}{Bum Lucas}
{21651}{}{A couple of alcohol-clouded eyes are looking at you from behind a huge matted dirty beard.}
{21660}{}{Quintara Ainis}
{21661}{}{An ordinary-looking pretty girl.}
{21670}{}{Akira Homma}
{21671}{}{An elderly woman of about fifty, from her clothes it can be assumed that she is an experienced trapper.}
{21680}{}{Sun Hei}
{21681}{}{This guy is clearly an experienced survivalist and a hunter, his trophies speak for themselves.}
{21690}{}{Bingo Box}
{21691}{}{A bald, gap-toothed little lisp peasant with a cunning face.}
{21700}{}{Fisherman}
{21701}{}{This person has probably seen more fish than you have fired bullets in your entire life.}
{21710}{}{Peasant}
{21711}{}{Being a peasant is not easy work, it's good that you are an ordinary wanderer.}
{21720}{}{Peasant}
{21721}{}{Because of the dirt, the true color of her skin remains a mystery to you.}
{21730}{}{Yakuza Fighter}
{21731}{}{A stern-looking Asian, he's definitely a bandit. The edges of bright tattoos are visible from under the clothes.}
{21740}{}{Yakuza Fighter}
{21741}{}{This lady will give a head start to any man, it's better not to mess with tattooed Asians.}
{21750}{}{Shi Fighter}
{21751}{}{A representative of a large Shi clan, perhaps he is a peasant, or maybe even a bandit.}
{21760}{}{Shi Fighter}
{21761}{}{There are also women in Shi, perhaps they will accept you as well... it's up to you to find connections.}
{21770}{}{Moloch's Soldier}
{21771}{}{You are absolutely sure that if you are not facing a raider, then it is something very close to a raider in front of you.}
{21780}{}{Whore}
{21781}{}{Do you want to have fun? Then go to the circus. This dirty whore is trying to earn some money.}
{21790}{}{Whore}
{21791}{}{Have you heard that some Asian women have a dick? Are you sure that you want to check?}
{21800}{}{Pimp}
{21801}{}{This cool guy is cool enough to keep his girls in check.}
{21810}{}{Dealer}
{21811}{}{Judging by his appearance he uses part of the goods himself.}
{21820}{}{Dealer}
{21821}{}{A drug dealer, the most ordinary one, most likely he is engaged in deliveries from Reno.}
{21830}{}{Moloch's Soldier}
{21831}{}{You are absolutely sure that if you are not facing a raider, then something very close is in front of you.}
{21840}{}{Moloch's Soldier}
{21841}{}{You are absolutely sure that if you are not facing a raider, then it is something very close to a raider in front of you.}
{21850}{}{Shi Commander}
{21851}{}{This Shi representative looks like a junior officer, probably his squad is somewhere nearby.}
{21860}{}{Shi Commander}
{21861}{}{This is an example of a woman who effectively commands men. Everything about these Asians is wrong.}
{21870}{}{Shi Fighter}
{21871}{}{A representative of the large Shi clan, perhaps he is a peasant, or maybe even a bandit.}
{21880}{}{Shi Fighter}
{21881}{}{There are also women in the Shi, perhaps they will accept you as well... it's up to you to find connections.}

#FORP 2019 NPC
{22000}{}{Rat}
{22001}{}{A rat. Quite a small bastard.}
{22010}{}{Mantis}
{22011}{}{A mantis. Its cold-blooded eyes are fixed on you, it chirps very loudly and unpleasantly.}
{22020}{}{Ant}
{22021}{}{An ant. The antennae point at you, accompanied by the gaze of a predator.}
{22030}{}{Ant-lion}
{22031}{}{This hefty ant looks especially disgusting and dangerous, its thick shell is covered with a white viscous liquid and its mouth is huge.}
{22040}{}{Pig-rat}
{22041}{}{A pig-rat. It makes sounds that resemble a squeak and a grunt all together.}
{22050}{}{Mole Rat}
{22051}{}{The mole rat. This huge creature is growling loudly.}
{22060}{}{Mutant mole rat}
{22061}{}{A mountain of muscles and huge red eyes. Viscous saliva flows from the fangs. The mutant smells extremely bad.}
{22070}{}{Silver Gecko}
{22071}{}{A silver gecko. This is a simple small lizard.}
{22080}{}{Golden Gecko}
{22081}{}{A golden Gecko. This big gecko clacks its sharp teeth loudly.}
{22090}{}{Cave Gecko}
{22091}{}{A small creature with a dark skin color. Scars and scuffs from being in the cave are visible all over the body. Yellow eyes constantly seem to run around the environment.}
{22100}{}{Dog}
{22101}{}{A dog. A mongrel of normal sizes.}
{22110}{}{Wasp}
{22111}{}{A large mutated insect with large wings. Greenish eyes and sharp thorns are all over the body.}
{22120}{}{Cockroach}
{22121}{}{A nasty, large, and extremely nimble cockroach. It has long antennae and legs, as well as a relatively strong shell.}
{22130}{}{Small black radscorpion}
{22131}{}{A small black radscorpion. This is a small but dangerous scorpion.}
{22140}{}{Black radscorpion}
{22141}{}{A black radscorpion. Directs his black tail at you.}
{22150}{}{Cave radscorpion}
{22151}{}{A large scorpion with a gray shell and a massive black tail.}
{22160}{}{Brahmin}
{22161}{}{A brahmin. Flies fly over its heads.}
{22170}{}{Predator plant}
{22171}{}{A predator plant. A strange, eyeless mouth is held on a thick stalk and beckons you with a smile.}
{22180}{}{Wanamingo}
{22181}{}{A wanamingo. This thing has no eyes, no fingers. What a terrible sight.}
{22190}{}{Deathclaw cub}
{22191}{}{A deathlaw cub. Slightly smaller than you, but is certainly dangerous.}
{22200}{}{Deathclaw}
{22201}{}{A deathclaw. It's lowering its large paws, sniffing the prey.}
{22210}{}{Hunter Deathclaw}
{22211}{}{Hunter Deathclaw. This creature is gray, it is much more dangerous than the strongest deathclaw in the pack.}
{22220}{}{Fire Gecko}
{22221}{}{A fire gecko. Faint smoke comes from the nostrils.}
{22230}{}{Beast}
{22231}{}{A clawed, short, stocky gray-colored creature.}
{22240}{}{Centaur}
{22241}{}{A centaur. Muddy mucus flows from a long tentacle-like tongue.}
{22250}{}{Floater}
{22251}{}{A floater. It floats in the air, emitting harmful gases through the pores of the subcutaneous sac.}
{22260}{}{Mirelurk}
{22261}{}{A mirelurk. A formidable creature from the depths of a sea or a swamp.}
{22270}{}{Yao-gai}
{22271}{}{A huge, muscular bear-like creature with impressive paws covered with sparse hair. There are ulcers and scars on the body. It has incredibly sharp teeth and long claws the size of a human hand.}
{22280}{}{Creepy croc}
{22281}{}{A large, wriggling creature with long, dangerous paws, sharp fangs and a strong tail.}
{22290}{}{Shadow croc}
{22291}{}{A large, wriggling, dark creature with long, dangerous paws, sharp fangs and a strong tail.}
{22300}{}{Decaying ghoul}
{22301}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22310}{}{Wild ghoul}
{22311}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22320}{}{Mutated ghoul}
{22321}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22330}{}{Huge mutated ghoul}
{22331}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}

{22900}{}{Giant Millipede}
{22901}{}{A giant millipede.}
{22910}{}{Lavash}
{22911}{}{A cow-like creature.}
{22920}{}{Giant Spider}
{22921}{}{A giant spider.}
{22930}{}{Coyote}
{22931}{}{A wasteland coyote. This coyote is a regular dweller in Arizona.}

{25010}{}{Теодор Рейк}
{25011}{}{Этот мужчина среднего возраста и в аккуратном деловом костюме является Мэром города Сильверлейк, важная персона, которая отвечает за функционирование города.}

{30000}{}{Dog}
{30001}{}{This dog looks domesticated.}