{10}{}{Герой}
{20}{}{Героиня}
{30}{}{Деревенщина}
{40}{}{Деревенщина}
{50}{}{Рад-скорпион}
{51}{}{Небольшой мутировавший скорпион.}
{60}{}{Рад-скорпион}
{61}{}{Мутировавший скорпион}
{70}{}{Коготь Смерти}
{71}{}{Маленький Коготь Смерти}
{80}{}{Коготь Смерти}
{81}{}{Маленький Коготь Смерти}
{90}{}{Пес}
{91}{}{Собака, наверняка бездомная, дворняжьей породы.}
{100}{}{Брамин}
{101}{}{Двухголовая корова-мутант.}
{110}{}{Грызун}
{111}{}{Самый обыкновенный большой грызун.}
{120}{}{Мантис}
{121}{}{Страшно надоедливое существо.}
{130}{}{Старейшая}
{140}{}{Хакунин}
{150}{}{Минок}
{160}{}{Хищный Цветок}
{161}{}{Плотоядное растение.}
{170}{}{Симпатичный раб}
{180}{}{Красивый раб}
{190}{}{Здоровая рабыня}
{200}{}{Здоровый раб}
{210}{}{Сильная рабыня}
{220}{}{Сильный раб}
{230}{}{Боевая рабыня}
{240}{}{Боевой раб}
{250}{}{Умная рабыня}
{260}{}{Умный раб}
{270}{}{Обычная рабыня}
{280}{}{Обычный раб}
{290}{}{Анна}
{300}{}{Крутой бандит}
{310}{}{Крутая воровка}
{320}{}{Жестокий бандит}
{330}{}{Лихая разбойница}
{340}{}{Проворный бандит}
{350}{}{Ловкая потаскуха}
{360}{}{Мощный бандит}
{370}{}{Стерва с пушкой}
{380}{}{Бандит с пушкой}
{390}{}{Дешевая шлюха}
{400}{}{Крутой Охранник}
{410}{}{Крутая Охранница}
{420}{}{Мощный Охранник}
{430}{}{Мощная Охранница}
{440}{}{Ловкий Охранник}
{450}{}{Ловкая Охранница}
{460}{}{Охранник со стволом}
{470}{}{Охранница со стволом}
{480}{}{Охранник с пушкой}
{490}{}{Охранница с пушкой}
{500}{}{Сирота}
{510}{}{Сирота}
{520}{}{Ребенок}
{530}{}{Ребенок}
{540}{}{Нищий}
{550}{}{Нищенка}
{560}{}{Плохой торговец}
{570}{}{Плохая торговка}
{580}{}{Обычный продавец}
{590}{}{Обычная продавщица}
{600}{}{Мастер-купец}
{610}{}{Мастерица-купчиха}
{620}{}{Вик}
{630}{}{Слабый крестьянин}
{640}{}{Слабая крестьянка}
{650}{}{Обычный крестьянин}
{660}{}{Обычная крестьянка}
{670}{}{Сильный крестьянин}
{680}{}{Сильная крестьянка}
{690}{}{Слабый охранник}
{700}{}{Слабая охранница}
{710}{}{Слабый стрелок}
{720}{}{Слабая снайперша}
{730}{}{Робот-ремонтник}
{740}{}{Робот-ремонтник тип 2}
{750}{}{Робомозг}
{760}{}{Летучий Глаз}
{770}{}{Робот-страж}
{780}{}{Робот-страж тип 2}
{790}{}{Робомозг}
{800}{}{Мелкий ящер}
{810}{}{Крутой ящерок}
{820}{}{Волк}
{821}{}{Жестокое и свирепое хищное животное.}
{830}{}{Золотой ящер}
{840}{}{Коготь Смерти}
{850}{}{Отродье Когтя Смерти}
{860}{}{Сильный Золотой ящер}
{870}{}{Линетта}
{880}{}{Доктор Трой}
{890}{}{Джон Кэссиди}
{900}{}{Грегори}
{910}{}{Гражданка}
{920}{}{Гражданин}
{930}{}{Богатая гражданка}
{940}{}{Богатый гражданин}
{950}{}{Траппер}
{960}{}{Траппер}
{970}{}{Сулик}
{980}{}{Майда Бакнер}
{990}{}{Торр}
{1000}{}{Лумпи}
{1010}{}{Светящийся призрак}
{1020}{}{Призрак реактора}
{1030}{}{Стражник реактора}
{1040}{}{Зомак}
{1050}{}{Скитер}
{1060}{}{Крысиный Мозг}
{1070}{}{Ленни}
{1080}{}{Вузи}
{1090}{}{Гарольд}
{1100}{}{Крот-гризли}
{1110}{}{Большой крот-гризли}
{1120}{}{Крысокабан}
{1130}{}{Свирепый крысокабан}
{1140}{}{Слабый брамин}
{1141}{}{Мутировавшая двухголовая корова.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Крыса-мутант}
{1161}{}{Мутировавшая от радиации крыса.}
{1170}{}{Мутировавший крот-гризли}
{1171}{}{Покрутевший и злой крот-гризли.}
{1180}{}{Мутировавший крысокабан}
{1181}{}{Сильно оголодавший от мутации монстр.}
{1190}{}{Супер Мутант}
{1200}{}{Накачанный мутант}
{1210}{}{Мельхиор}
{1220}{}{Нero Andro (don't use)}
{1230}{}{Нero Andro (don't use)}
{1240}{}{Нero Male (don't use)}
{1250}{}{Нero Female (don't use)}
{1260}{}{Нero Male (don't use)}
{1270}{}{Нero Female (don't use)}
{1280}{}{Нero Male (don't use)}
{1290}{}{Нero Female (don't use)}
{1300}{}{Нero Male (don't use)}
{1310}{}{Нero Female (don't use)}
{1320}{}{Нero Male (don't use)}
{1330}{}{Нero Female (don't use)}
{1340}{}{Гвардеец Города}
{1350}{}{Гвардеец Города}
{1360}{}{Кибердог}
{1370}{}{Стражник НКР}
{1380}{}{Стражник НКР}
{1390}{}{Полицейский НКР}
{1400}{}{Сторож рабов}
{1410}{}{Надсмотрщик}
{1420}{}{Великий торговец людьми}
{1430}{}{Великая торговка людьми}
{1440}{}{Танди}
{1450}{}{Мерк}
{1460}{}{Ратч}
{1470}{}{Скитер}
{1480}{}{Майки}
{1490}{}{Бармен НКР}
{1500}{}{Владелец магазина}
{1510}{}{Грунтар}
{1520}{}{Горис}
{1530}{}{Хищный крот-гризли}
{1540}{}{Хищный крот-гризли}
{1550}{}{Хищный крот-гризли}
{1560}{}{Хищный крот-гризли}
{1570}{}{Хищный крот-гризли}
{1580}{}{Хищный крот-гризли}
{1590}{}{Обычный призрак}
{1600}{}{Мирон}
{1610}{}{Маркус}
{1620}{}{Доктор Джонс}
{1630}{}{Дэвин}
{1640}{}{Мирия}
{1650}{}{Лэдди}
{1660}{}{Рондо}
{1670}{}{Подмастерье}
{1680}{}{Подмастерье}
{1690}{}{Подмастерье}
{1700}{}{Вышибала}
{1710}{}{Вышибала}
{1720}{}{Слабый мр. Хэнди}
{1730}{}{Обычный Светящийся}
{1740}{}{Дар}
{1750}{}{Далиа}
{1760}{}{Гордон}
{1770}{}{test (don't use)}
{1780}{}{Призрак реактора}
{1790}{}{Обычный призрак}
{1800}{}{Мэтт}
{1810}{}{Командир охотников}
{1820}{}{Охотник за бандитами}
{1830}{}{Командир охотников}
{1840}{}{Охотник за бандитами}
{1850}{}{Охотник за бандитами}
{1860}{}{Командир охотников}
{1870}{}{Охотник за бандитами}
{1880}{}{Охотник за бандитами}
{1890}{}{Командир охотников}
{1900}{}{Охотник за бандитами}
{1910}{}{Бесс}
{1911}{}{Двухголовая мутировавшая корова.}
{1920}{}{Балтас}
{1930}{}{Гришэм}
{1940}{}{Фил}
{1950}{}{Цыпленок}
{1960}{}{Карл}
{1970}{}{Джонни}
{1980}{}{Джо}
{1990}{}{Зеке}
{2000}{}{Мясник}
{2010}{}{Питти}
{2020}{}{Воин племени}
{2030}{}{Воительница племени}
{2040}{}{Каннибал}
{2050}{}{Людоедка}
{2060}{}{Святой муж}
{2070}{}{Святая женщина}
{2080}{}{Кочевник}
{2090}{}{Кочевник}
{2100}{}{Кочевница}
{2110}{}{Кочевница}
{2120}{}{Убийца}
{2130}{}{Убийца}
{2140}{}{Крестьянин}
{2150}{}{Крестьянка}
{2160}{}{Мантис}
{2170}{}{Рабовладелец}
{2180}{}{Рабовладелица}
{2190}{}{Дикий брамин}
{2200}{}{Переселенец}
{2210}{}{Переселенка}
{2220}{}{Патрульный Города}
{2230}{}{Патрульная Города}
{2240}{}{Сильный рабовладелец}
{2250}{}{Сильная рабовладелица}
{2260}{}{Чокнутый}
{2270}{}{Мародер}
{2280}{}{Чокнутый из Глоу}
{2290}{}{Мародер из Глоу}
{2300}{}{Рыбак}
{2310}{}{Рыбачка}
{2320}{}{Дикарь}
{2330}{}{Дикарка}
{2340}{}{Самогонщик}
{2350}{}{Самогонщица}
{2360}{}{Артельщик}
{2370}{}{Артельщица}
{2380}{}{Рейдер}
{2390}{}{Рейдерша}
{2400}{}{Огнедышащий ящер}
{2410}{}{Крутой огнедышащий ящер}
{2420}{}{Инопланетянин}
{2430}{}{Чужой}
{2440}{}{Мелкий сильный Коготь Смерти}
{2450}{}{Злобный Коготь Смерти}
{2460}{}{Летатель}
{2470}{}{Подлый Летатель}
{2480}{}{Псевдо-кентавр}
{2490}{}{Кентавр Апдайка}
{2500}{}{Патрульный АНКЛАВА}
{2510}{}{Патрульная АНКЛАВА}
{2520}{}{Саботажник}
{2530}{}{Саботажница}
{2540}{}{Наемник}
{2550}{}{Наемница}
{2560}{}{Найткин}
{2570}{}{Мощный Найткин}
{2580}{}{Крутой Призрак}
{2590}{}{Мафиози}
{2600}{}{Якудза}
{2610}{}{Рейнджер НКР}
{2620}{}{Рейнджер НКР}
{2630}{}{Мародер}
{2640}{}{Мародер}
{2650}{}{Симпатяга Ллойд}
{2660}{}{Зубастый грызун}
{2670}{}{Житель 13-го}
{2680}{}{Жительница 13-го}
{2690}{}{Хранитель Моста}
{2700}{}{Таинственный незнакомец}
{2710}{}{Таинственная незнакомка}
{2720}{}{Хэйксвилл}
{2730}{}{Большой Езус Мордино}
{2740}{}{Думар}
{2750}{}{Мать Когтей Смерти}
{2760}{}{Дракон}
{2770}{}{Ло Пан}
{2780}{}{Хабологист}
{2790}{}{Хабологистка}
{2800}{}{Неопознанная личность}
{2810}{}{Неопознанная личность}
{2820}{}{Неопознанная личность}
{2830}{}{Неопознанная личность}
{2840}{}{Неопознанная личность}
{2850}{}{Неопознанная личность}
{2860}{}{Неопознанная личность}
{2870}{}{Неопознанная личность}
{2880}{}{Суперагент Президента}
{2890}{}{Яйцо Когтя Смерти}
{2900}{}{Метцгер}
{2910}{}{Гвардеец АНКЛАВА}
{2920}{}{Гвардеец АНКЛАВА}
{2930}{}{Президент}
{2940}{}{Вице-президент}
{2950}{}{Техник}
{2960}{}{Бадгер}
{2970}{}{Доктор Фонг}
{2980}{}{Дитя}
{2990}{}{Дитя}
{3000}{}{Продавец оружия}
{3010}{}{Лаборант Ши}
{3020}{}{Страж Ши}
{3030}{}{Крестьянин Ши}
{3040}{}{Крестьянка Ши}
{3050}{}{Крестьянин Ло Пана}
{3060}{}{Крестьянка Ло Пана}
{3070}{}{Докер}
{3080}{}{Торговец Ши}
{3090}{}{Пинки}
{3100}{}{Крыса}
{3110}{}{Мантис}
{3120}{}{Муравей}
{3130}{}{Кротокрыс}
{3140}{}{Крот Гриззли}
{3150}{}{Кротокрыс мутант}
{3160}{}{Обычный геккон}
{3170}{}{Золотой геккон}
{3180}{}{Собака}
{3190}{}{Скорпион}
{3200}{}{Большой скорпион}
{3210}{}{Брамин}
{3220}{}{Хищное растение}
{3230}{}{Чужой}
{3240}{}{Маленький коготь смерти}
{3250}{}{Коготь смерти}
{3260}{}{Серый коготь смерти}
{3270}{}{Огнедышащий геккон}
{3280}{}{Псевдо-кентавр}
{3290}{}{Летатель}
{3300}{}{Болотник}
{3310}{}{крыса}
{3320}{}{крыса}
{3330}{}{крыса}
{3340}{}{крыса}
{3350}{}{Потрошитель}
{3360}{}{Потрошительница}
{3370}{}{Бандит}
{3380}{}{Бандитка}
{3390}{}{Мародер}
{3400}{}{Рейдер}
{3410}{}{Рейдерша}
{3420}{}{Работорговец}
{3430}{}{Мародер}
{3440}{}{Налетчик}
{3450}{}{Налетчица}
{3460}{}{Путник}
{3470}{}{Гуль}
{3480}{}{Гуль}
{3490}{}{Супермутант}
{3500}{}{Мальчик}
{3510}{}{Девочка}
{3520}{}{Житель}
{3530}{}{Житель}
{3540}{}{Житель}
{3550}{}{Житель}
{3560}{}{Житель}
{3570}{}{Житель}
{3580}{}{Житель}
{3590}{}{Панк}
{3600}{}{Мясник}
{3610}{}{Тип в балахоне}
{3620}{}{Бедняк}
{3630}{}{Вышибала}
{3640}{}{Житель}
{3650}{}{Женщина}
{3660}{}{Девушка}
{3670}{}{Проститутка}
{3680}{}{Женщина}
{3690}{}{Человек в костюме}
{3700}{}{Стражник}
{3710}{}{Стражница}
{3720}{}{Стражник}
{3730}{}{Стражница}
{3740}{}{Стражник}
{3750}{}{Вик - Стадия 3}
{3760}{}{Вик - Стадия 4}
{3770}{}{Вик - Стадия 5}
{3780}{}{Вик - Стадия 6}
{3790}{}{Робомозг - Шимпанзе}
{3800}{}{Робомозг - Ненормальный}
{3810}{}{Робомозг - Человек}
{3820}{}{Муравей}
{3830}{}{Крутой муравей}
{3840}{}{Пария}
{3850}{}{Зурак}
{3860}{}{Имбот}
{3870}{}{Джимми}
{3880}{}{Вейунгх}
{3890}{}{Херб}
{3900}{}{Лупал}
{3910}{}{Джобе}
{3920}{}{Смитти}
{3930}{}{Рубе}
{3940}{}{Мастер Кралл}
{3950}{}{Зигги}
{3960}{}{Мастер Кунг}
{3970}{}{Джон Бишоп}
{3980}{}{Анжела Бишоп}
{3990}{}{Миссис Бишоп}
{4000}{}{Телохранитель 1}
{4010}{}{Телохранитель 2}
{4020}{}{Громила Бишопа 1}
{4030}{}{Громила Бишопа 2}
{4040}{}{Сердитый брамин}
{4050}{}{Малый Езус}
{4060}{}{Большой Езус}
{4070}{}{Человек Мордино 1}
{4080}{}{Человек Мордино 2}
{4090}{}{Человек Мордино 3}
{4100}{}{Телохранитель Мирона 1}
{4110}{}{Телохранитель Мирона 2}
{4120}{}{Мистер Врайт}
{4130}{}{Миссис Врайт}
{4140}{}{Крис Врайт}
{4150}{}{Кейт Врайт}
{4160}{}{Сын Врайта 1}
{4170}{}{Сын Врайта 2}
{4180}{}{Дочь Врайта 1}
{4190}{}{Дочь Врайта 2}
{4200}{}{Мистер Сальваторе}
{4210}{}{Мэйсон}
{4220}{}{Вышибала Сальваторе 1}
{4230}{}{Вышибала Сальваторе 2}
{4240}{}{Обычный бармен 1}
{4250}{}{Обычный бармен 2}
{4260}{}{Обычный бармен 3}
{4270}{}{Боксер 1}
{4280}{}{Боксер 2}
{4290}{}{Боксер 3}
{4300}{}{Боксер 4}
{4310}{}{Майк Мастикатор}
{4320}{}{Холифелд}
{4330}{}{МакКнили}
{4340}{}{Малыш Стюарт}
{4350}{}{Братья с Корсики}
{4360}{}{Порноактрисы}
{4370}{}{Отец Тулли}
{4380}{}{Вышибала Казино 1}
{4390}{}{Вышибала Казино 2}
{4400}{}{Крупье}
{4410}{}{Сутенер/Наркоторговец1}
{4420}{}{Сутенер/Наркоторговец1}
{4430}{}{Сутенер/Наркоторговец1}
{4440}{}{Сутенер/Наркоторговец1}
{4450}{}{МакГи}
{4460}{}{Мисс Китти}
{4470}{}{Обычная Шлюха 1}
{4480}{}{Обычная Шлюха 2}
{4490}{}{Джимми Джей}
{4500}{}{Ренеско}
{4510}{}{Ученый}
{4520}{}{Элдридж}
{4530}{}{Алжернон}
{4540}{}{Джулс}
{4550}{}{Бюрократ 1}
{4560}{}{Бюрократ 2}
{4570}{}{Продавец 1}
{4580}{}{Продавец 2}
{4590}{}{Охранник 1}
{4600}{}{Охранник 2}
{4610}{}{Охранник 3}
{4620}{}{Охранник 4}
{4630}{}{Солдат 1}
{4640}{}{Солдат 2}
{4650}{}{Солдат 3}
{4660}{}{Солдат 4}
{4670}{}{Сержант Старк}
{4680}{}{Доктор Эндрью}
{4690}{}{Бармен}
{4700}{}{Орудийная башня}
{4701}{}{Автоматическое оборонительное устройство, снабженное двумя плазма-пушками.}
{4710}{}{К-9 (базовый)}
{4720}{}{К-9 (стадия 1)}
{4730}{}{К-9 (стадия 2)}
{4740}{}{К-9 (стадия 3)}
{4750}{}{К-9 (стадия 4)}
{4760}{}{Обычный Кибердог}
{4770}{}{Яйцо Ванаминго}
{4780}{}{Страж Ло Пана}
{4790}{}{Мэрджори}
{4800}{}{Авто-пушка}
{4810}{}{Особенный ящер}
{4820}{}{Смертушка}
{4830}{}{Фрэнк Хорриган}
{4831}{}{Суперагент и телохранитель президента}
{4840}{}{Хаболог}
{4850}{}{Хаболог}
{4860}{}{Паладин Братства}
{4870}{}{Гигантская оса}
{4880}{}{Жук-мутант}
{4890}{}{Мятежник}
{4900}{}{Опасный жук}
{4910}{}{Инженер}
{4920}{}{Пехотинец Анклава}
{4930}{}{Инженер}
{4940}{}{Солдат Братства}
{4950}{}{Диверсант}
{4960}{}{Солдат Анклава}
{4970}{}{Паладин Братства}
{4980}{}{Патрульный регулятор}
{4990}{}{Бандит}
{5000}{}{Разбойница}
{5010}{}{Рейдер}
{5020}{}{Рейдер}
{5030}{}{Рейдер}
{5040}{}{Рейдер}
{5050}{}{Ядовитый болотник}
{5060}{}{Болотник}
{5070}{}{Футбольный мяч}
{5080}{}{Человек в белом одеянии}
{5081}{}{Он спокоен и молчалив. Кажется, за все время, что вы здесь провели он ни разу не шевельнулся.}
{5090}{}{Яйцо смертекогта.}
{5100}{}{Яйцо чужого.}
{5110}{}{Яйцо огненного гекко.}
{5120}{}{Мутирующая дрянь.}
{5121}{}{Предположительно, так выглядят летатели и кентавры до "рождения".}
{5130}{}{Вожак кентавров.}
{5131}{}{Похоже, он сторожит "выводок".}
{5140}{}{Вожак огненных ящеров.}
{5150}{}{Матка смертекогтов.}
{5180}{}{Хелацитон тип 1}
{5181}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5190}{}{Злобный хелацитон тип 1}
{5191}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5200}{}{Хелацитон тип 2}
{5201}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5210}{}{Злобный хелацитон тип 2}
{5211}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5220}{}{Хелацитон тип 3}
{5221}{}{Непонятное существо, напоминающее уродцев Мастера супер-мутантов.}
{5230}{}{Генриетта}
{5231}{}{Кожа этого существа напоминает одну большую мозоль.}
{5240}{}{Здоровый гуль}
{5250}{}{Здоровый гуль}
{5260}{}{Боец}
{5270}{}{Боец}
{5280}{}{Боец}
{5290}{}{Боец}
{5300}{}{Боец}
{5310}{}{Боец}
{5320}{}{Боец}
{5330}{}{Боец}
{5340}{}{Здоровый ящер}
{5350}{}{Протектрон}
{5360}{}{Музыкальный автомат}
{5370}{}{Химера}
{5380}{}{Йелли}
{5390}{}{Линн}
{5400}{}{Боец красных}
{5410}{}{Боец красных}
{5420}{}{Мутант}
{5421}{}{Крупная мутировавшая особь.}
{5430}{}{Здоровый мутант}
{5431}{}{Крупная мутировавшая особь.}
{5440}{}{Огромный мутант}
{5441}{}{Крупная мутировавшая особь с развитой мускулатурой.}
{5450}{}{Брамин}
{5451}{}{Обычный брамин}
{5460}{}{Житель}
{5470}{}{Житель}

#-------------------------------------------------------------------
#FORP - Critters
#-------------------------------------------------------------------
#RIVERDALE NPC
{8000}{}{Снайпер Саула}
{8001}{}{Хладнокровный боец дальнего боя. Первым делом вы познакомитесь с её пулей, нежели с ней. На лбу метка работорговца.}
{8010}{}{Наёмник Моргана}
{8011}{}{Профессиональный боец Моргана. Очевидно, обилие его шрамов и отметин на оружии - не от спокойной жизни.}
{8020}{}{Наёмница Моргана}
{8021}{}{Опытная наёмница, посвятившая свою жизнь работе на "случайный кошелёк", а после - на Моргана.}
{8030}{}{Стальной Ромул}
{8031}{}{Высокий, сильный мужчина с седоватыми длинными волосами. Вместо левой руки, от локтя идёт металлический протез.}
{8040}{}{Жирный Морган}
{8041}{}{Очень толстый мужчина в официальной одежде, но что странно - гавайской рубашке под жилетом. По его виду легко понять, что ценит он в людях лишь личную выгоду.}
{8050}{}{Саул}
{8051}{}{Накачанный, большой негр в металлической броне. Его холодный взгляд подсказывает, что он здесь главный. На лбу видна большая метка работорговцев.}
{8100}{}{Лита}
{8101}{}{Крайне накаченная девушка с ярким кислотным ирокезом. На её броне видно множество зарубок, а на щеке имеются старые шрамы.}
{8110}{}{Никки}
{8111}{}{Небрежная прическа в фиолетовых тонах, множество татуировок по всему телу, а так же вычищенная броня до блеска. Девушка выглядит крайне расслабленно.}
{8120}{}{Псарь Дюк}
{8121}{}{Взрослый мужик в плотной куртке с потрепанными рукавами. На брови виднеется шрам, а от одежды пахнет собаками.}
{8130}{}{Мишлен}
{8131}{}{Девушка среднего роста с аккуратными руками. Одежда слегка приоткрыта, а на лице держится хитрая улыбка.}
{8140}{}{Дайрон}
{8141}{}{Крепкий мужчина в зеркальной металлической броне. Миниган на его спине не предвещает ничего добродушного.}
{8150}{}{Найра}
{8151}{}{Острый взгляд, хищный оскал и крепкое телосложение. Девушка явно повидала многое и уверенно повидает столько же.}
{8160}{}{Себастиан}
{8161}{}{Деловой мужчина в огнеупорной броне. На лице задумчивая мина, изредка сменяющаяся на нейтральную.}
{8170}{}{Реджи}
{8171}{}{Спокойный мужчина азиатской наружности. На куртке видны какие-то зарубки.}
{8180}{}{Жан}
{8181}{}{Мужчина в деловом костюмы и с густыми длинными усами. Выглядит напыщенно. От него веет странным ощущением чего-то инородного.}
{8190}{}{Освальд}
{8191}{}{Крепкий мужчина с множеством мешочков и сумок на его плечах и ногах. Кажется, он кого-то ждёт.}
{8200}{}{Шерри}
{8201}{}{Взрослая девушка с короткой прической и несколькими шрамами на губе. Её камуфляжная броня выглядит запачканной.}

#SANDBOX NPC
{9500}{}{Дюбридж Ли Эрвин}
{9501}{}{Старая, залатанная во всех возможных местах и укрепленная кусками сырой браминей кожи, роба опоясывает такого же истертого временем пожилого человека.}
{9510}{}{Маркус Голдман}
{9511}{}{Бронзовый загар и литые мышцы говорят о том, что этот невысокий мужичок даст фору самым удалым армреслерам из Брокен-Хиллс.}
{9520}{}{Стивен Барр}
{9521}{}{Постоянно жует какой-то сорт жевательного табака, сплевывая попадающиеся комки в сторону, после чего, как ни в чем не бывало, продолжает улыбаться, обнажая слегка пожелтевшие, но ровные зубы.}
{9530}{}{Сэт Сэйл}
{9531}{}{Определенно мастер своего дела, тщательно подобранная экипировка которого сразу же выдает в нем его род занятий - мощная кожаная праща на поясе, заточенное копье за спиной и милая накидка на плечах из дубленой кожи огнедышащего геккона.}
{9540}{}{Эндрю Мэллон}
{9541}{}{Одет в лохмотья караванщика с кучей нацепленных на них армейский разгрузок. Пахнет керосином.}
{9550}{}{Раймонд Тайер}
{9551}{}{На поясе у этого древнего гуля затянут ремень с кучей подручных инструментов. Также как заядлый курильщик всегда держит в зубах сигарету, он сжимает в руке старый, потертый мультитул.}
{9560}{}{Карл Ругер}
{9561}{}{Если бы техническое масло было парфюмом, этот далеко не гладкокожий парень был бы законодателем моды. Опоясан старым кузнечным фартуком.}
{9570}{}{Сэмуэль Сакс}
{9571}{}{Удивительное отличие этого гуля от всех других - сохранившиеся клочки седых волос на скупо обтянутой кожей голове.}
{9580}{}{Вексельберг}
{9581}{}{Гуль, выдающейся чертой которого являются крупные кузнечные перчатки, которые очень смешно смотрятся на его тщедушных, но очень жилистых ручонках.}
{9590}{}{Честер}
{9591}{}{Чудовище столь огромных размеров, что рядом с ним небо кажется мелким и незначительным элементом пейзажа.}
{9600}{}{Дэвид «Лапша» Ааронсон}
{9601}{}{Высокого роста гуль с накинутым на грудь легким брнежилетом. Постоянно осматривается по сторонам, медленно проводя по окрестностям своим дымным взглядом}
{9610}{}{Максимилиан «Макс» Беркович}
{9611}{}{Гуль, у которого всё ещё сохранился нос, придающий ему более менее человеческий облик. Одет в грязный комбинезон, подвязанный ремнем с нацепленной на него различной боевой снарягой.}
{9620}{}{Патрик «Простак» Голдберг}
{9621}{}{Пузатый гуль, носящий соломенную шляпу. Жует что-то, размеренно и раздражающе почавкивая.}
{9630}{}{Филипп «Косой» Штейн}
{9631}{}{Отличительная особенность этого гуля в сильной разнице уровня глаз. Левый глаз совсе замутнен, а правый же, наоборот, сохранил человеческое выражение и глубину мысли.}
{9640}{}{Малыш Доминик}
{9641}{}{Миниатюрный паренек. Его можно было бы назвать славным малым, если бы не тот факт, что это мерзкий, отвратительный и крайне вонючий гуль.}
{9650}{}{Элис}
{9651}{}{Очень крутая, но выглядящая миролюбиво, охотница.}
{9660}{}{Чейз, лидер шахтеров}
{9661}{}{Коренастый парень в довольно чистой одежде. По его рукам видно, что ему приходилось работать на шахте старателем.}
{9670}{}{Линкольн, караванщик}
{9671}{}{Пыльный плащ, драные сапоги, разношенная кобура... сразу видно - бывалый путешественник.}
{9680}{}{Сара, кладовщик шахтеров}
{9681}{}{Девушка лет тридцати, приятной наружности. По её загарелой коже нельзя сказать, что она много времени провела в шахтах.}
{9690}{}{Страйк}
{9691}{}{Парень с самодовольным видом и зубочисткой во рту. Он так занят своими колодами карт, что ничего вокруг не замечает.}
{9700}{}{Лана}
{9701}{}{Молодая девушка весьма привлекательного вида с аппетитными формами и игривым взглядом.}
{9710}{}{Роджер, торговец}
{9711}{}{Парень средних лет, одет в пыльную куртку с заплатками. Выглядит как типичный торгаш.}
{9720}{}{Мей, представитель "Красного Рассвета"}
{9721}{}{Девушка в кожаной броне со значком организации "Красный Рассвет".}
{9730}{}{Джессика Роуман}
{9731}{}{Девушка с веснушками и ровной челкой. Очки на её лице добавляют ей важности, что нельзя сказать о её потрепанном костюме}

#RIVERDALE NPC
{9740}{}{Сьюзи}
{9741}{}{Молодая девушка со светлыми волосами, очень красивая}
{9750}{}{Терминал}
{9751}{}{Машина по выдаче талонов.}
{9760}{}{Сэт}
{9761}{}{Сурового вида траппер. Один глаз закрыт повязкой. Кажется вы его уже видели где-то, или нет...}
{9770}{}{Варг}
{9771}{}{Огромный лохматый пес, он величественнен и спокоен.}
{9780}{}{Гери}
{9781}{}{Поджарый рыжий волчара, лучше не поворачиваться к нему спиной.}
{9790}{}{Фреки}
{9791}{}{Это судя по всему сука, однако зубы у нее не уступают любому кобелю.}
{9800}{}{Рей Свонсон}
{9801}{}{К кому вы пойдете когда вам будет так плохо что хоть помирай? Правильно, к доктору. Это он.}
{9810}{}{Фрэд Бобкэт}
{9811}{}{С виду обыкновенный житель трущоб, правда глаза у него какие-то "затуманенные".}
{9820}{}{Эйб Цукерман}
{9821}{}{Пожилой мужчина, сухого телосложения.}
{9830}{}{Крупье казино}
{9831}{}{Очень красивая и сексуальная девушка. На шее красивое ожерелье, а на ногах милые балетки.}
{9840}{}{Охранник казино}
{9841}{}{Рослый парень с протокольной рожей, он внимательно следит за вами. Когда вы подходите ближе, он улыбается вам, разумеется из вежливости.}
{9850}{}{Заядлый торчок}
{9851}{}{Горбатый наркоман, явно смотрящий на вас с немым вопросом.}
{9860}{}{Проститутка}
{9861}{}{Потасканная женщина, которую явно проведали многие.}
{9870}{}{Ганди}
{9871}{}{Крепкий наёмник с небольшой улыбкой на лице. Он выглядит молодо.}
{9880}{}{Трэвор}
{9881}{}{Высокий и молодой парень, строго осматривающийся вокруг.}
{9890}{}{Селестия}
{9891}{}{Молодая девушка со шрамом на шее. Через всю грудь проходит патронташ, заполненный патронами.}
{9900}{}{Забавный толстяк}
{9901}{}{Странный мужичок, медленно поглаживающий своё выпирающее пузо.}
{9910}{}{Базил}
{9911}{}{Крупный мужчина в бронежилете, вечно что-то записывающий в свою тетрадь.}
{9920}{}{Льюис}
{9921}{}{Деловой парень в металлической броне. Кажется, он кого-то ждёт.}
{9930}{}{Гарфилд}
{9931}{}{Высокий, лысый мужик. Он смотрит на вас с неким нетерпением.}
{9940}{}{Салли}
{9941}{}{Молодая, ухоженная девушка. Она явно кого-то ожидает и мягко улыбается.}
{9950}{}{Отморозок Ромула}
{9951}{}{Отбитый боец Ромула, готовый ввязаться в драку, даже если это было не нужно.}
{9960}{}{Бандит Ромула}
{9961}{}{Опасный "цепной пёс" синдиката, готовый выполнить любую грязную работу.}
{9970}{}{Головорез Ромула}
{9971}{}{Кровожадный убийца, каким-то чудом находящийся на службе у Ромула.}
{9980}{}{Стрелок Саула}
{9981}{}{Умелый боец-работорговец в бронежилете. Его строгий взгляд подсказывает, что с пустыми разговорами к нему лучше не подходить. На лбу метка работорговца.}
{9990}{}{Надсмотрщик Саула}
{9991}{}{Наблюдатель за рабами с множеством старых шрамов и тяжелым взглядом. На лбу метка работорговца.}

#RATS
{10000}{}{Детеныш крысы}
{10001}{}{Довольно мелкая тварь.}
{10010}{}{Мелкая крыса}
{10011}{}{Непропорционально большие клыки и красные глаза.}
{10020}{}{Средняя крыса}
{10021}{}{С её клыков обильно течёт слюна.}
{10030}{}{Облученная крыса}
{10031}{}{Она светится и на ней почти нет шерсти.}
{10040}{}{Огромный крыс}
{10041}{}{Этот злобный грызун может легко допрыгнуть до вашего лица.}
{10050}{}{Крыса-мутант}
{10051}{}{Матерая злая тварь размером с небольшую собаку.}

#MANTIS
{10300}{}{Жалкий мантис} 
{10301}{}{Мелкое и противное насекомое с длинными лапками.} 
{10310}{}{Мантис} 
{10311}{}{Среднее тельце с длинными лапками, способными заколоть вас досмерти. } 
{10320}{}{Огромный мантис} 
{10321}{}{Огромное насекомое с не менее внушительными клешнями и массивным тельцем. Голова хаотично ходит в разные стороны.}
{10330}{}{Мантис вожак}
{10331}{}{Громадный и исключительный представитель мантисов. Внушительные крылья и вечно агрессивно клацающие клешни.}

#ANTS
{10600}{}{Муравей-рабочий}
{10601}{}{Небольшое существо, вечно виляющее на ходу.} 
{10610}{}{Муравей-солдат} 
{10611}{}{Крупное существо, среднего размера лапы и длинные усики. Внушительные жвалы плавно двигаются.} 
{10620}{}{Муравей-трутень} 
{10621}{}{Этот здоровенный муравей выглядит особенно мерзко и габаритно. Тело непропорционально большое, отчего он выглядит неприятно.} 
{10630}{}{Муравей-охранник} 
{10631}{}{Это Альфа-самец: его панцирь выглядит очень толстым, а пасть огромной. Мощные лапы, длинные жвалы и огромные глазища.}

#SPOREPLANTS
{10900}{}{Хищное растение} 
{10901}{}{Странная, безглазая пасть держится на толстом стебле.} 
{10910}{}{Огромное хищное растение} 
{10911}{}{Громадная безглазая пасть с многочисленными отростками по сторонам. Стебель покрыт шипами, а само растение крайне высокое.} 

#BRAHMINS
{11200}{}{Слабый брамин} 
{11201}{}{Небольшой и слабенький брамин. Выглядит тощим и изголодавшимся.} 
{11210}{}{Брамин} 
{11211}{}{Две головы, четыре копыта и одно большое брюхо. У одной из голов имеются рога.}
{11220}{}{Большой Брамин} 
{11221}{}{Крупный брамин с массивными головами и телом.}
{11230}{}{Дикий брамин} 
{11231}{}{Худой и потрепанный брамин. Тело брамина истрёпано дикой природой.} 
{11240}{}{Яростный брамин} 
{11241}{}{Крупный брамин с тёмным окрасом. Рога длиннее, чем у обычного брамина, а копыта выглядят массивнее.}

#DOGS
{11500}{}{Слабая собака} 
{11501}{}{Тощее животное, по телу видны рёбра и следы долгого голодания. Шерсть поредела.} 
{11510}{}{Собака} 
{11511}{}{Обычная дворняга средних размеров.} 
{11520}{}{Матёрая собака} 
{11521}{}{Множество старых шрамов и ранений, дают понять, что этот пёс через многое прошёл.} 
{11530}{}{Большая собака} 
{11531}{}{Крупная собака с грубой и диковатой мордой. С клыков стекают слюни, а на лапах видна грязь.}
{11540}{}{Щенок} 
{11541}{}{Маленькое создание с мелкими лапками, длинной мордочкой и короткой шерсткой.}

#WOLFES
{11800}{}{Слабый волк} 
{11801}{}{Небольшое существо, чем-то напоминающее собаку. Редкая шерсть, небольшие клыки и когти на лапах. Выглядит истощенным.} 
{11810}{}{Волк} 
{11811}{}{Среднего размера существо. Хорошая шкура, крепкое телосложение, длинная и вытянутая морда с острыми зубами в пасти.} 
{11820}{}{Матёрый волк} 
{11821}{}{Потрёпанный жизнью волк. На шкуре видны множественные шрамы, на лапах запекшаяся кровь.} 
{11830}{}{Вожак стаи волков} 
{11831}{}{Огромный и старый волк. Крупное телосложение и крайне длинные когти и зубы дают понять, что он прожил многое. По шкуре волка наблюдается обилие старых шрамов и относительно свежих ран.} 
{11840}{}{Щенок} 
{11841}{}{Маленькое создание с мелкими лапками, длинной мордочкой и серой шерсткой. Наличие острых клыков выдает в нём щенка волка.}


#PIGRATS
{12100}{}{Свинокрыс} 
{12101}{}{Он издаёт звуки, напоминающие писк и хрюканье в одном. Маленькая противная тушка на когтистых лапках.} 
{12110}{}{Огромный свинокрыс} 
{12111}{}{Громадная мясистая туша на мускулистых лапищах с когтями и острыми зубищами в пасти.} 
{12120}{}{Свинокрыс альфа-особь} 
{12121}{}{Невероятно большой и мускулистый свинокрыс. По его телу видно обилие неприятных шрамов и старых ранений.} 

#MOLERATS
{12400}{}{Кротокрыс} 
{12401}{}{Небольшое животное на четырех лапах с когтями и острыми зубами. На морде и хвосте видны длинные усики.} 
{12410}{}{Огромный кротокрыс} 
{12411}{}{Огромный и крайне мясистый зверь. Вся кожа в складках тёмно-розового цвета.} 
{12420}{}{Кротокрыс-вожак} 
{12421}{}{Громадный кротокрыс с особенно длинными когтями. Зубы крайне острые и большие, а на теле видны многочисленные шрамы.} 

#SILVER GECKOS
{12700}{}{Серебряный гекко} 
{12701}{}{Небольшой серебристый геккон. Маленькие лапки на относительно большом тельце.} 
{12710}{}{Серебряный хищный гекко} 
{12711}{}{Жилистый геккон с длинным хвостом. В пасти видны частые и очень острые зубы.} 
{12720}{}{Крупный серебряный гекко} 
{12721}{}{Очень большой геккон, по сравнению с его собратьями. Длинные лапы с опасными когтями, переливающаяся шкурка.} 
{12730}{}{Серебряный гекко альфа-особь} 
{12731}{}{Самый большой серебряный геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются мелкие шипы.} 

#GOLDEN GECKOS
{13000}{}{Золотой гекко} 
{13001}{}{Маленький и юркий золотой гекко. Мелкий хвостик вечно двигается в такт походке.} 
{13010}{}{Крупный золотой гекко} 
{13011}{}{Большое существо с длинным хвостом и острыми зубами. Его золотая шкурка красиво переливается на солнце.} 
{13020}{}{Золотой гекко альфа-особь} 
{13021}{}{Самый большой золотой геккон. Его большие красные глаза налиты кровью, а на шкуре наблюдаются частые рубцы и шрамы.} 

#FIREGECKOS
{13300}{}{Огненный гекко} 
{13301}{}{Небольшой, но крайне красочный зверь. Из ноздрей твари исходит легкий дымок.} 
{13310}{}{Огненный гекко альфа-особь} 
{13311}{}{Крайне крупный огненный гекко с внушительным телосложением и целым "фонтаном" дыма, выходящим из его ноздрей. Пасть вечно открывается, выпуская на волю струйки огня.} 

#SMALLSCROPS
{13600}{}{Мелкий радскорпион} 
{13601}{}{Маленький скорпион с не сильно внушительными клешнями и мелким хвостом.} 

#BIGSCORPS
{13900}{}{Радскорпион} 
{13901}{}{Среднего размера скорпион. С его хвоста и жала стекает яд. Массивные клешни и быстрые лапки.} 
{13910}{}{Матёрый радскорпион} 
{13911}{}{Крупный скорпион с большим и набухшим жалом. Крепкий и массивный панцирь.} 

#BLACKSCORPS
{14200}{}{Мелкий чёрный радскорпион} 
{14201}{}{Малый скорпион с длинным хвостом и чёрным панцирем.} 
{14210}{}{Чёрный радскорпион} 
{14211}{}{Крупный чёрный скорпион с толстым панцирем и массивным свисающим хвостом. Жало твори сочится ядом.} 

#DEATHCLAWS
{14500}{}{Детёныш Когтя смерти} 
{14501}{}{Маленькое гуманоидное существо с длиннющими лапами, из которых виднеются острые когти.} 
{14510}{}{Молодой Коготь смерти} 
{14511}{}{Среднего размера существо со светлой шерстью и небольшими рожками.} 
{14520}{}{Крупный Коготь смерти} 
{14521}{}{Большая и мускулистая страшная тварь. Длинные и крайне острые когти на лапах. Жёлтые и изогнутые клыки.} 
{14530}{}{Коготь смерти альфа-особь} 
{14531}{}{Громадный коготь-смерти с длинными изогнутыми рогами и обилием шрамов на всему телу. Потемневший окрас и громоздкие лапы.} 
{14540}{}{Коготь смерти охотник} 
{14541}{}{Огромный коготь-смерти серого окраса. Изогнутое тело, могучие лапы и изогнутые рога, нацеленные вперёд.} 

#SWAMPLURKERS
{14800}{}{Слабый болотник} 
{14801}{}{Небольшое существо в толстом панцире и массивными клешнями.} 
{14810}{}{Болотник} 
{14811}{}{Вонючая, большая и громоздкая тварь, покрытая цельным крепким панцирем. Острые клешни выглядят крайне опасно и остро.} 
{14820}{}{Вожак болотников} 
{14821}{}{Невероятно массивный и крепкий, исключительный болотник. Его громадный панцирь покрыт болотными отходами и обилием водорослей.} 

#ALIENS
{15100}{}{Странное яйцо} 
{15101}{}{Странное, округлое яйцо неизвестного происхождения.} 
{15110}{}{Ванаминго} 
{15111}{}{У этой твари нет ни глаз, ни пальцев. Из тела выходят мерзкие длинные безкостные щупальца.} 
{15120}{}{Крупный ванаминго} 
{15121}{}{Большая и страшная безглазая тварь с длинными мерзкими щупальцами.} 

#MOTERALIENS
{15400}{}{Матка ванаминго} 
{15401}{}{Матка ванаминго. С пасти здоровенного ванаминго течёт слизь, а блестящая шкура имеет тёмно-серый оттенок.} 

#FLOATERS
{15700}{}{Мелкий летатель} 
{15701}{}{Маленькое змееподобное нечто, медленно ползущее на хвосте. Вместо лица у существа есть подобие большого рта.} 
{15710}{}{Летатель} 
{15711}{}{Безобразная тварь с огромным, полным зубов горизонтальным ртом.} 
{15720}{}{Гадкий летатель} 
{15721}{}{Он мерзко воняет, а его передние рты обильно истекают слизью.} 
{15730}{}{Вожак летателей} 
{15731}{}{Огромный летатель с несколькими громадными ртами, полными обилием острых зубов в едкой слизи. Существо очень сильно воняет.} 

#CENTAURS
{16000}{}{Мелкий кентавр} 
{16001}{}{Небольшое, но крайне мерзкое создание. Передвигается на шести человеческих руках. На длинных шеях красуются разные обезображенные головы.} 
{16010}{}{Кентавр.} 
{16011}{}{С длинного щупальцеобразного языка течёт мутная слизь. Две обезображенные головы и нечто, похожее на кишки, свисающие из тела и волочащиеся следом.} 
{16020}{}{Гадкий кентавр} 
{16021}{}{Крайне неприятное зрелище. Существо с разными головами, обилием органов, находящихся снаружи. По телу течёт вязкая слизь.} 
{16030}{}{Альфа кентавр} 
{16031}{}{Громадный кентавр держится на десяти человеческих руках. Три уродливые головы и не менее обезображенное подобие тела.}

#PRIMITIVES
{16300}{}{Тощий дикарь} 
{16301}{}{Тощий дикарь. Этот дикарь похоже очень давно не ел.} 
{16310}{}{Тощая дикарка} 
{16311}{}{Тощая дикарка. Она похожа на обтянутый кожей скелет. Ну или на свеженького гуля.}
{16320}{}{Грязый дикарь} 
{16321}{}{Грязый дикарь. Этот похоже целыми днями копается в земле.}
{16330}{}{Перемазанная дикарка} 
{16331}{}{Перемазанная дикарка. Возможно глина на ее лице и волосах - это украшение.}
{16340}{}{Старейшина племени} 
{16341}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16350}{}{Старейшина племени} 
{16351}{}{Старейшина племени. Похоже что он один из предводителей племени.}
{16360}{}{Шаман племени} 
{16361}{}{Шаман племени. Множество амулетов и опьяненный вид намекаютвам, что перед вами сильный колдун.}
{16370}{}{Дикарь охотник} 
{16371}{}{Дикарь охотник. Вы когда нибудь видели траппера без штанов? Вот он.}
{16380}{}{Дикарка охотница} 
{16381}{}{Дикарка охотница. Она не так доступна как кажется.}
{16390}{}{Дикарь воин} 
{16391}{}{Дикарь воин. Сильный и ловкий, он будет защищать свое племя до последнего вздоха.}
{16400}{}{Дикарка воительница} 
{16401}{}{Дикарка воительница. Боевая раскраска, дикий оскал и голые сиськи, все как положено.}

#CANNIBALS & RIPPERS
{16600}{}{Мерзкий людоед} 
{16601}{}{Мерзкий людоед. Он смотрит на вас со злобой и голодом. Быстро шагает в Вашу сторону, громко принюхиваясь и пуская слюну.}
{16610}{}{Грязная людоедка} 
{16611}{}{Грязная людоедка. Она смотрит на вас голодным взглядом. Её волосы взъерошены, некоторые зубы отсутствуют.}
{16620}{}{Бородатый людоед} 
{16621}{}{Бородатый людоед. Он жадно смотрит на вас. Этот пидор собирается вас сожрать!}
{16630}{}{Сумасшедший людоед} 
{16631}{}{Сумасшедший людоед. Его взгляд бегает по округе. Он клацает зубами, топчась на земле.}
{16640}{}{Фермер-людоед} 
{16641}{}{Фермер-людоед. Он смотрит на вас голодными глазами. Его комбинезон заляпан кровью, а соломенная шляпа кем-то надкусана.}
{16650}{}{Голодный людоед} 
{16651}{}{Голодный людоед. Он смотрит на вас голодными глазами. С его рта течёт слюна, а рёбра заметно проступают под кожей.}
{16660}{}{Рабыня-людоедка} 
{16661}{}{Рабыня-людоедка. Она смотрит на вас голодным взглядом. На её шее висит сломанный ошейник.}
{16670}{}{Лысый каннибал} 
{16671}{}{Лысый каннибал. Он злобно смотрит на вас. От его красной макушки исходит пар, видимо, там он кусочек Вашей ноги и зажарит.}
{16680}{}{Фермерша-людоедка} 
{16681}{}{Фермерша-людоедка. Она смотрит на вас голодным взглядом. На её фартуке кровью написано МЯСО.}
{16690}{}{Странный парень} 
{16691}{}{Странный парень. Его лицо скрыто капюшоном. Рваная роба имеет участки с засохшей кровью.}
{16700}{}{Китаец-каннибал} 
{16701}{}{Китаец-каннибал. Он смотрит вас, как на свежую рыбу. К жилетке и штанам прикреплены ножи разных размеров.}
{16710}{}{Странный нигер} 
{16711}{}{Странный нигер. Он негромко хрипит. С его рта стекает кровь, а зрачки почему-то закатились вверх.}
{16720}{}{Здоровый каннибал} 
{16721}{}{Здоровый каннибал. Он смотрит на вас, пуская кровавые слюни. Похоже, он даже рычит.}
{16730}{}{Бледный каннибал} 
{16731}{}{Бледный каннибал. Он смотрит на вас голодными глазами. Его кожа почти что белая, очень странно для обитателя Пустоши.}
{16740}{}{Мутированный каннибал} 
{16741}{}{Мутированный каннибал. Он смотрит на вас голодным взглядом. Половина его головы гниёт заживо, другая половина полна гнойных наростов.}
{16750}{}{Мелкий каннибал} 
{16751}{}{Мелкий каннибал. Он смотрит на вас голодными глазами. Этот мелкий пидор, по всей видимости, питается человечиной.}
{16760}{}{Симпатичная людоедка} 
{16761}{}{Симпатичная людоедка. Она смотрит на вас голодным взглядом. Одежда на ней уже полностью изношена, из-за чего хорошо видна её большая грудь.}
{16770}{}{Жирная людоедка} 
{16771}{}{Жирная людоедка. Она смотрит на вас со зловещей улыбкой. Её одежда сшита из разных шкур, а на них нарисованы загадочные символы из крови.}
{16780}{}{Престарелый каннибал} 
{16781}{}{Престарелый каннибал. Он смотрит на вас хладнокровно. Седовласый старик жуёт собственные губы.}
{16790}{}{Ловчий потрошителей} 
{16791}{}{Ловчий потрошителей. Похоже, что вы нужны ему живым.} 
{16800}{}{Ловчая потрошителей} 
{16801}{}{Ловчая потрошителей. Ловкая и быстрая. Похоже, что она не прочь с вами "позабавиться".}
{16810}{}{Потрошитель-забойщик} 
{16811}{}{Потрошитель-забойщик. Крепко сложен. Его рот искривлен в плотоядной ухмылке.}
{16820}{}{Потрошитель-забойщик} 
{16821}{}{Потрошитель-забойщик. Сильная женщина. Ее лицо испачкано кровью. Судя по всему это не ее кровь.}
{16830}{}{Потрошитель-свежеватель} 
{16831}{}{Потрошитель-свежеватель. Агрессивно настроенный представитель племени потрошителей.}
{16840}{}{Потрошитель-свежеватель} 
{16841}{}{Потрошитель-свежеватель. Полуобнаженная женщина. Хищно смотрит на вас.}
{16850}{}{Потрошитель-воин} 
{16851}{}{Потрошитель-воин. Его торс увешен украшениями из костей поверженных врагов.}
{16860}{}{Воительница потрошителей} 
{16861}{}{Воительница потрошителей. Ее взгляд затуманен жаждой крови.}
{16870}{}{Потрошитель жрец } 
{16871}{}{Потрошитель жрец. Его шею украшает ожерелье из фаланг человеческих пальцев.}
{16880}{}{Патриарх потрошителей} 
{16881}{}{Патриарх потрошителей. Высокий и властный мужчина. Его лицо украшают ритуальные шрамы. Остальные потрошители смотрят на него как на живого бога.}
{16890}{}{Матриарх потрошителей} 
{16891}{}{Матриарх потрошителей. Крепко сложенная женщина в одежде из человеческой кожи. Другие потрошители почтительно опускают глаза в ее присутствии.}

#GANGS
{16900}{}{Торчок} 
{16901}{}{Торчок. Наркоман, его руки дрожат, а глаза бегают.} 
{16910}{}{Наркоманка} 
{16911}{}{Наркоманка. Судя по ее отсутствующему взгляду - она уже давным давно готова на что угодно ради дозы.}
{16920}{}{Отребье} 
{16921}{}{Отребье. Оборванец, который пытается жить за чужой счет.}
{16930}{}{Шмара} 
{16931}{}{Шмара. Отсутствие принципов - вот ее главный принцип!}
{16940}{}{Small punk}
{16941}{}{A small punk. He will not hesitate to deprive you of your wallet... and your life as well.}
{16950}{}{Small punk} 
{16951}{}{Small punk. She is used to playing by the rules of the wasteland.}
{16960}{}{Rogue}
{16961}{}{A rogue. A petty thief.}
{16970}{}{Rogue}
{16971}{}{A rogue. Sharp-tongued, and so is her switchblade!} 
{16980}{}{Scumbag}
{16981}{}{A scumbag. He's ready to gut you for a couple of caps.}
{16990}{}{Robber}
{16991}{}{A robber. Unprincipled and very dangerous.}
{17000}{}{Thug}
{17001}{}{A thug. Apparently, this psychopath is going to spill your blood!}
{17010}{}{Madman}
{17011}{}{A madman. For him, cutting a child's throat is as easy as pissing.}
{17020}{}{Authority}
{17021}{}{Authority. A local authority. To them you are a pile of crap.}
{17030}{}{Authority}
{17031}{}{Authority. A local authority. To them you are a pile of crap.}

#RAIDERS
{17200}{}{Raider scavenger}
{17201}{}{A raider scavenger. You would have confused them with a hobo if it wasn't for the weapon pointed at you.}
{17210}{}{Raider scavenger}
{17211}{}{A raider scavenger. You would have confused them with a hobo if it wasn't for the weapon pointed at you.}
{17220}{}{Crazy raider}
{17221}{}{A crazy raider. A completely insane person.}
{17230}{}{Crazy raider}
{17231}{}{A crazy raider. A completely insane person.}
{17240}{}{Kamikaze Raider}
{17241}{}{A kamikaze raider. His outlook just screams for this person to be shot.}
{17250}{}{Kamikaze Raider}
{17251}{}{A kamikaze raider. His outlook just screams for this person to be shot.}
{17260}{}{Raider goon}
{17261}{}{A raider goon. Do not fall under his blows.}
{17270}{}{Raider goon}
{17271}{}{A raider goon. Do not fall under his blows.}
{17280}{}{Raider}
{17281}{}{A raider. A raider or a simple bandit? What's the difference!}
{17290}{}{Raider}
{17291}{}{A raider. A raider or a simple bandit? What's the difference!}
{17300}{}{Raider Shooter}
{17301}{}{A raider shooter. You are at gunpoint.}
{17310}{}{Raider Shooter}
{17311}{}{A raider shooter. You're in the crosshairs.}
{17320}{}{Raider madman}
{17321}{}{A raider madman. This one is eager to fight on the front line and looks very dangerous.}
{17330}{}{Raider madman}
{17331}{}{A raider madman. This one is eager to fight on the front line and looks very dangerous.}
{17340}{}{Elite raider}
{17341}{}{An elite raider. The elite of their gang.}
{17350}{}{Elite raider}
{17351}{}{An elite raider. The elite of their gang.}
{17360}{}{Professional raider}
{17361}{}{A prfessional raider. Such people usually have a lot of battles behind them.}
{17370}{}{Professional raider}
{17371}{}{A professional raider. Such people usually have a lot of battles behind them.}
{17380}{}{Professional raider}
{17381}{}{A professional raider. Such people usually have a lot of battles behind them.}
{17390}{}{Legendary Raider Leader}
{17391}{}{The legendary raider leader. One of the representatives of the legendary "Khans" gang. He is very strong.}

#SLAVERS
{17500}{}{Rookie slaver}
{17501}{}{A rookie slaver. A young guy with the slaver's mark on his forehead. A twitchy scoundrel who wants to prove himself.}
{17510}{}{Rookier slaver}
{17511}{}{A rookie slaver. A young girl with the slaver's mark on her forehead. A twitchy bitch who wants to prove herself.}
{17520}{}{Slaver bull}
{17521}{}{A slaver bull. A strong man with the mark of a slaver on his forehead. He was audaciously examining you, as if he was estimating your value.}
{17530}{}{Slaver bull}
{17531}{}{A slaver bull. A strong man with the mark of a slaver on his forehead. Dirty hands, dirty conscience and a predatory look describe him as a "good businessman".}
{17540}{}{Slaver shooter}
{17541}{}{A slaver shooter. Apparently, this is one of the "beaters " of the slavers. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17550}{}{Slaver shooter}
{17551}{}{A slaver shooter. Apparently, this is one of the "beaters " of the slavers. The task of this trapper is to track down and catch a person, preferably with the whole family.}
{17560}{}{Veteran slaver}
{17561}{}{A veteran slaver. An experienced bandit with the mark of a slaver on his forehead. It seems that he knows the price of everyone and you would not like to be in the zone of his "interest".}
{17570}{}{Veteran slaver}
{17571}{}{A veteran slaver. An experienced robber with the brand of a slaver on her forehead. It seems that she knows the price of everyone and you would not like to be in the zone of her "interest".}
{17580}{}{Slavers Chief}
{17581}{}{The head of the slavers. A good-looking businessman with the slaver mark on his forehead. He knows a lot about "labor parties" and the system of motivations.}
{17590}{}{Slavers Chief}
{17591}{}{The head of the slavers. A handsome-looking man with the slaver mark on his forehead. This "Black Lord" has broken a lot of destinies.}

#CARAVANS
{17800}{}{Random traveler}
{17801}{}{A random traveler. You do not let go of the feeling that this person should not be here at all.}
{17810}{}{Random traveler}
{17811}{}{A random traveler. You do not let go of the feeling that this person should not be here at all.}
{17820}{}{Rookie caravan guard}
{17821}{}{A rookie caravan guard. Clearly feeling insecure.}
{17830}{}{Caravan guard rookie}
{17831}{}{A caravan guard rookie. Clearly feeling insecure.}
{17840}{}{Heavy caravan guard}
{17841}{}{A heavy caravan guard. This guy is huge!}
{17850}{}{Heavy caravan guard}
{17851}{}{A heavy caravan guard. This guy is huge!}
{17860}{}{Veteran caravan guard}
{17861}{}{A veteran caravan guard. This person is obviously experienced.}
{17870}{}{Veteran caravan guard}
{17871}{}{A veteran caravan guard. This person is obviously experienced.}
{17880}{}{Caravan guard shooter}
{17881}{}{A caravan guard shooter. They are squinting at the terrain.}
{17890}{}{Caravan guard shooter}
{17891}{}{A caravan guard shooter. They are squinting at the terrain.}
{17900}{}{Caravan leader}
{17901}{}{A caravan leader. It seems that this person is in charge of everything here.}
{17910}{}{Caravan leader}
{17911}{}{A caravan leader. It seems that this person is in charge of everything here.}

#STRANGERS
{18100}{}{Homeless}
{18101}{}{A homeless person. Just a stinking hobo. The Wasteland is filled with them. Looks beaten up, behaves nervously.}
{18110}{}{Homeless}
{18111}{}{A homeless person. A dirty woman with a downtrodden look. She reeks of misery.}
{18120}{}{Scavenger}
{18121}{}{Scavenger. An ordinary collector. He jerkily looks around, looking for something profitable.}
{18130}{}{Scavenger}
{18131}{}{Scavenger. A typical collector. She jerkily looks around, looking for something profitable.}
{18140}{}{Lowlife}
{18141}{}{An angry beggar. Such kind roams every slums. He is busy with something and tries not to look at you.}
{18150}{}{Lowlife}
{18151}{}{An angry beggar. Such kind roams every slums. She is busy with something and tries not to look at you.}
{18160}{}{Hunter}
{18161}{}{A hunter. An experienced trapper with a weathered face and a characteristic squint.}
{18170}{}{Hunter}
{18171}{}{A hunter. An experienced trapper with a weathered face and a characteristic squint.}
{18180}{}{Wanderer}
{18181}{}{A wanderer. An ordinary traveler from the Wasteland. It's not certain from where he comes, but judging by the torn burlap on him it seems like he has traveled a long way. }
{18190}{}{Wanderer}
{18191}{}{A wanderer. An ordinary traveler from the Wasteland. It's not certain from where he comes, but judging by the torn burlap on him it seems like she has traveled a long way.}
{18200}{}{Outcast}
{18201}{}{An outcast. A stinking hobo. The Wasteland is filled with them. This one looks sick, or maybe he is just a freak.}
{18210}{}{Outcast}
{18211}{}{An outcast. A decrepit old man, living out his life. A pitiful sight.}
{18220}{}{Enforcer}
{18221}{}{An enforcer. An experienced mercenary with strong ammunition. Armed and apparently dangerous.}
{18230}{}{Enforcer}
{18231}{}{An enforcer. An experienced mercenary with strong ammunition. Armed and apparently dangerous.}

#GHOULS
{18400}{}{Frail ghoul}
{18401}{}{A frail ghoul. Skin and bones. Literally.}
{18410}{}{Frail ghoul}
{18411}{}{A frail ghoul. Skin and bones. Literally.}
{18420}{}{Mangy ghoul}
{18421}{}{A mangy ghoul. From the fallen pieces of his skin, it would be quite possible to sew a bag.}
{18430}{}{Mangy ghoul}
{18431}{}{A mangy ghoul. From the fallen pieces of his skin, it would be quite possible to sew a bag.}
{18440}{}{Nasty ghoul}
{18441}{}{A nasty ghoul. The very sight of this one makes you sick.}
{18450}{}{Nasty ghoul}
{18451}{}{A nasty ghoul. The very sight of this one makes you sick.}
{18460}{}{Dirty Ghoul}
{18461}{}{A dirty ghoul. The dirt stuck to the walking skeleton made this one less noticeable.}
{18470}{}{Dirty Ghoul}
{18471}{}{A dirty ghoul. The dirt stuck to the walking skeleton made this one less noticeable.}
{18480}{}{Disgusting ghoul}
{18481}{}{A disgusting ghoul. It looks better through a scope.}
{18490}{}{Disgusting ghoul}
{18491}{}{A disgusting ghoul. It looks better through a scope.}
{18500}{}{Rotting ghoul}
{18501}{}{A rotting ghoul. Your nose has never smelled anything more terrible.}
{18510}{}{Rotting ghoul}
{18511}{}{A rotting ghoul. Your nose has never smelled anything more terrible}
{18520}{}{Glowing Ghoul}
{18521}{}{A glowing ghoul. How about a couple of extra rads?}
{18530}{}{Glowing Ghoul}
{18531}{}{A glowing ghoul. How about a couple of extra rads?}
{18540}{}{Fast Ghoul}
{18541}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18550}{}{Fast Ghoul}
{18551}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18560}{}{Fast Ghoul}
{18561}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18570}{}{Fast Ghoul}
{18571}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18580}{}{Fast Ghoul}
{18581}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}
{18590}{}{Fast Ghoul}
{18591}{}{A fast ghoul. It seems that this one is not such a slow wreck as the others.}

#SUPERMUTANTS
{18700}{}{Supermutant}
{18701}{}{A supermutant. A huge chunk of muscles. These creatures do not have many reasons to be called intelligent.}
{18710}{}{Supermutant}
{18711}{}{A supermutant. The living horror of the Wasteland. Stupid, angry, stinky.}
{18720}{}{Supermutant goon}
{18721}{}{A supermutant goon. A huge carcass consisting of muscles, anger and light armor that seems very dangerous. He looks around with a dumb stare in search of something to crush.}
{18730}{}{Supermutant goon}
{18731}{}{A supermutant goon. The creature is impatiently marking time. It wants to beat, break and destroy... and the sooner - the better.}
{18740}{}{Supermutant berserker}
{18741}{}{A supermutant berserker. The body of this creature is covered with bruises. It seems that this creature has gone completely mad from pain and rage.}
{18750}{}{Supermutant berserker}
{18751}{}{A supermutant berserker. Its whole body is covered with scars. This crazy creature has emerged victorious from many fights. It is very dangerous.}
{18760}{}{Supermutant master}
{18761}{}{A supermutant master. The creature is covered with armor made of rusty sheets of metal and chains. The armor looks nasty and rattles when moving, but the monster seems to like it very much.}
{18770}{}{Supermutant master}
{18771}{}{A supermutant master. The armored monster looks no smarter than the rest of its kind, but it clearly feels more important.}
{18780}{}{Nightkin}
{18781}{}{A nightkin. A huge chunk of muscles. This creature has a surprisingly meaningful and piercing look.}
{18790}{}{Nightkin}
{18791}{}{A nightkin. A huge chunk of muscles. This creature has a meaningful and piercing look.}
{18800}{}{Nightkin berserker}
{18801}{}{A nightkin berserker. This intelligent and experienced creature has emerged victorious from many fights. It is very dangerous.}
{18810}{}{Nightkin berserker}
{18811}{}{A nightkin berserker. This intelligent and experienced creature has emerged victorious from many fights. It is very dangerous.}
{18820}{}{Nightkin master}
{18821}{}{A nightkin master. A monster with a smart and calm look. You feel small in front of him not only in terms of height. This creature is "bigger" than anything you could become.}
{18830}{}{Nightkin master}
{18831}{}{A nightkin master. A monster with a smart and calm look. You feel small in front of him not only in terms of height. This creature is "bigger" than anything you could become.}
{18840}{}{Nightkin sniper}
{18841}{}{A nightkin sniper. A clever and cunning creature with honed movements and a huge rifle in his hands.}
{18850}{}{Nightkin sniper}
{18851}{}{A nightkin sniper. A clever and cunning creature with honed movements and a huge rifle in his hands.}

#ROBOTS
{19000}{}{Robobrain}
{19001}{}{A robobrain. A multi-purpose cybernetic organism, which uses the brain of an animal or a human as a processor.}
{19010}{}{Floating eye bot}
{19011}{}{A floating eye bot. It is an armed floating robot. Usually, it carries repair or security functions.}
{19020}{}{Mr. Handy}
{19021}{}{Mr. Handy. A series of home and work robots that was very popular in the pre-war USA.}
{19030}{}{Sentury bot}
{19031}{}{A sentury bot. A pre-war combat unit. It has a "Friend or Foe" recognition system. They are armed with heavy weapons but lack mobility.}

#Не знаю, кто догадался засунуть сюда прототип турели Ривердейла. Но я исправлять прототипы (а там куча кода и правок в игре ГМкой) не собираюсь.
{19040}{}{Laser turret}
{19041}{}{Robotized defence system.}
{19050}{}{Laser tower}
{19051}{}{Robotized defence system.}
{19060}{}{Plasma turret}
{19061}{}{Robotized defence system.}
{19070}{}{Gatling turret}
{19071}{}{Robotized defence system.}

#MODOC GUARDS
{19300}{}{Modoc Guard}
{19301}{}{A guard of Modoc. These guys know their job.}
{19310}{}{Modoc Guard}
{19311}{}{A guard of Modoc. These guys know their job.}
{19320}{}{Modoc Guard}
{19321}{}{A guard of Modoc. These guys know their job.}
{19330}{}{Modoc Guard}
{19331}{}{A guard of Modoc. These guys know their job.}
{19340}{}{Modoc Guard}
{19341}{}{A guard of Modoc. These guys know their job.}
{19350}{}{Modoc Guard}
{19351}{}{A guard of Modoc. These guys know their job.}
{19360}{}{Modoc Guard}
{19361}{}{A guard of Modoc. These guys know their job.}
{19370}{}{Modoc Guard}
{19371}{}{A guard of Modoc. These guys know their job.}
{19380}{}{Modoc Guard}
{19381}{}{A guard of Modoc. These guys know their job.}
{19390}{}{Modoc Guard}
{19391}{}{A guard of Modoc. These guys know their job.}
{19400}{}{Caravan guard}
{19401}{}{A caravan guard. Cool, stern, silent. A real pro.}
{19410}{}{Leroy}
{19411}{}{It's Leroy. This guy won't let even a fly go without documents.}

#FOX'S VILLA
{19600}{}{Strong slave}
{19601}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19610}{}{Strong slave}
{19611}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19620}{}{Strong slave}
{19621}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19630}{}{Strong slave}
{19631}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19640}{}{Strong slave}
{19641}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19650}{}{Strong slave}
{19651}{}{A strong slave. A strong-looking slave. Do you wish to buy this one?}
{19660}{}{Strong slave}
{19661}{}{A strong slave. A strong-looking slave. This one is a classic black color.}
{19670}{}{Fox's tough slaver}
{19671}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19680}{}{Fox's tough slaver}
{19681}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19690}{}{Fox's tough slaver}
{19691}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19700}{}{Fox's tough slaver}
{19701}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19710}{}{Fox's tough slaver}
{19711}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19720}{}{Fox's tough slaver}
{19721}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19730}{}Fox's tough slaver}
{19731}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19740}{}{Fox's tough slaver}
{19741}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19750}{}{Fox's tough slaver}
{19751}{}{Fox's tough slaver. He proudly wears a mark on his forehead.}
{19760}{}{Metzger}
{19761}{}{This is Metzger. He clearly knows a lot about the trade in live goods.}
{19770}{}{Colonel Fox}
{19771}{}{It's Mr. Fox - the most known slaveholder in these lands.}

#OTHER HUMAN NPC
{19900}{}{Baltas}
{19901}{}{It's Baltas. A really strong man and a famous hunter.}
{19910}{}{Skilled hunter}
{19911}{}{A skilled hunter. These guys can catch any creature.}
{19920}{}{Skilled hunter}
{19921}{}{A skilled hunter. These guys can catch any creature.}

#POSEYDON NPC
{20000}{}{Immortal John}
{20001}{}{A battered robot with a brain in a flask.}
{20010}{}{Cook}
{20011}{}{A fat, sweaty man with a sly look in his lustful eyes. He wears an apron and a chef's hat.}
{20020}{}{Professor Kevorkian}
{20021}{}{The wrinkled face shows interest, irritation and fatigue. He also wears glasses.}
{20030}{}{Hugo "The Hog" Ruth}
{20031}{}{A big man with a red face.}
{20040}{}{Grave}
{20041}{}{A gaunt man with a weathered face. The owner of a luxurious horseshoe mustache.}
{20050}{}{Ash Tom}
{20051}{}{This ghoul is completely black, as if woven from dirt and ashes.}
{20060}{}{Chad}
{20061}{}{A fat, pot-bellied and broad-shouldered man in a bloody apron. His face does not shine with intelligence.}
{20070}{}{Booger}
{20071}{}{A very short young guy.}
{20080}{}{Chog}
{20081}{}{A huge, even for a super mutant, and terrible monster.}
{20090}{}{Jessie "Saint" Castor}
{20091}{}{A tall, dark, hungover-looking man with eternal stubble on his face.}
{20100}{}{Shawn "Rattle" Marshal}
{20101}{}{An unusually luminous ghoul.}
{20110}{}{Curtis "Cowboy" Raidler}
{20111}{}{A young bearded man, in a worn jacket and a cowboy hat.}
{20120}{}{Bryce "Trumpet"}
{20121}{}{A tall, thin man with pale skin. He lacks a middle finger on the left hand. There is a metal pipe in a case on his belt.}
{20130}{}{Montgomery "Monty" Tonato}
{20131}{}{A young man with a stern and strong-willed expression on his face. A thin white stripe is visible on the cheek - must be a scar from a knife.}
{20140}{}{Gwen Tyler}
{20141}{}{A pretty young girl, sparkling with a snow-white smile.}
{20150}{}{Donny "Cleaver" Tracho}
{20151}{}{A tall Mexican man with a face scarred by wrinkles and wind. He wears an anchor-style beard.}
{20160}{}{Garfield "Splinter" Nelson}
{20161}{}{A cheerful-looking red-haired guy.}
{20170}{}{Nera "Trudy" Argwire}
{20171}{}{A brunette with a cold look.}
{20180}{}{Oliver "Iceman" Remy}
{20181}{}{He grins ironically, looking at you.}
{20190}{}{Charon "Salted" Diklane}
{20191}{}{An extremely well-preserved ghoul in a military uniform.}
{20200}{}{Crook Mackenzie}
{20201}{}{A thin, long-armed and long-legged guy with dirty corn-colored hair.}
{20210}{}{Sunshine "Sunny" 209}
{20211}{}{It looks dangerous, if you don't know what it is and why it is here then it's better not to touch it.}
{20220}{}{Molly Bloom}
{20221}{}{A very sexy and attractive girl.}
{20230}{}{Diamond "Page" Dallas}
{20231}{}{A large man with age. His curly hair has long been covered with a touch of gray.}
{20240}{}{Merfus "Old " MacDill}
{20241}{}{A red beard, gray temples and a clearly strained smile can be seen on his face.}
{20250}{}{Bam-Bam Bigelow}
{20251}{}{Short-haired and smooth-shaven stocky man.}
{20260}{}{Brody Travis}
{20261}{}{His glasses are taped to his skull with duct tape, he looks cunning and arrogant.}
{20270}{}{Turok}
{20271}{}{An unshaven, short-haired, sullen dude who actively offers you to trade and buy "unique things".}
{20280}{}{Garry}
{20281}{}{Twitchy appearance, torn robe, and a large backpack on his back... His hands are constantly black.}
{20290}{}{Douglas "Bigwig"}
{20291}{}{A neat-looking elderly man in a pre-war suit, he wears glasses and a kippah.}
{20300}{}{Vinnie "Broad" Fletcher}
{20301}{}{Big guy, looks you straight in the eyes, heavy voice and protruding lower lip.}
{20310}{}{Burger Chuck}
{20311}{}{A Negro in a dark unbuttoned raincoat and a hat, a man of unpretentious and hard work.}
{20320}{}{Tuco "Amigo" Salamanca}
{20321}{}{A strong-looking Mexican. He glares at you as if you owe him money.}
{20330}{}{Chung Daishu}
{20331}{}{A small Asian man with short blond hair. He has a sword on the belt.}
{20340}{}{Tommy "Titty"}
{20341}{}{A short man with soft features on a round face with an irritated and wary expression.}
{20350}{}{Mr. Shaw}
{20351}{}{A huge, obese man with a wig on his head and clown makeup on his face. He scares you with his appearance.}

#POSEYDON GUARDS
{21000}{}{"Poseidon" SDU private}
{21001}{}{It is obvious that these mercenaries do not get money for nothing. It is better not to mess with them.}
{21010}{}{"Poseidon" SDU private}
{21011}{}{It is obvious that these mercenaries do not get money for nothing. It is better not to mess with them.}
{21020}{}{Tower Guard}
{21021}{}{A stern man, evaluates you with a professional look of a killer. It's good that he's hired to protect intead of killing.}

#LARS'S GANG
{21300}{}{Thunder Dave}
{21301}{}{It is clear that he is a notorious pirate and a thug. His armor is covered with traces of many battles.}
{21310}{}{Black Dog}
{21311}{}{A strong man with a red, faded bandana around his neck. He looks with a squint.}
{21320}{}{Zhoh}
{21321}{}{A long nigger of a strong build. He occasionally spits on the ground when talking.}
{21330}{}{Israel Hanks}
{21331}{}{A gloomy, silent man, looks at you with an appraising glance, as if he is calculating the price of your belongings.}
{21340}{}{Carnat}
{21341}{}{First impression shows you a cheerful guy with an eternal smile. However, the thirst for profit and fame is visible in his eyes.}

#KASTOR'S CLERGY
{21400}{}{Guardian of the Faith Thomas "Blessed" Manson}
{21401}{}{A man in a dirty robe, on which the lead symbol of the "Atom" cult is visible.}
{21410}{}{Guardian of the Faith Martha "The Voice" Swift}
{21411}{}{A frail figure in a dirty ovesized Atom themed robe. She looks at you with light gray eyes from under the shadow of the hood.}
{21420}{}{Guardian of the Faith Harold "Lazarus" Shipman}
{21421}{}{A bearded, smiling man in a dirty Atom robe, on which purple traces are visible.}
{21430}{}{Zealot of Atom}
{21431}{}{A gloomy person in a scarlet robe with an Atom symbol on it, his face is hidden by an iron mask with a slit for eyes.}
{21440}{}{Zealot of Atom}
{21441}{}{A gloomy person in a scarlet robe with an Atom symbol on it, his face is hidden by an iron mask with a slit for eyes.}

#SAN FRANCISCO NPC
{21500}{}{Hanayama Kaoru}
{21501}{}{A huge Asian, a real giant. He is dressed in a pre-war three-piece suit and wears sneakers.}
{21510}{}{Akisame Koetsuji}
{21511}{}{A short calm-looking Japanese man. There is wisdom in his eyes.}
{21520}{}{Revi Ruete}
{21521}{}{A young beautiful Japanese woman with a bold and cheeky look.}
{21530}{}{Bang Shiruba}
{21531}{}{A stooped, gray-haired old man with a bushy mustache. It seems to you that he is evaluating you.}
{21540}{}{Lo-Peng}
{21541}{}{This Chinese man is quite famous in the city. You've definitely heard something about Master Lo-Peng.}
{21550}{}{Lam Chin Ying}
{21551}{}{He looks at you intently, almost with hostility.}
{21560}{}{Sammo Hung}
{21561}{}{A fat Asian man with a funny face and a stern look.}
{21570}{}{Donnie Yen}
{21571}{}{A tall Chinese man in a strict traditional outfit of the century before last.}
{21580}{}{Mr. Moloch}
{21581}{}{An incredibly large and athletic man, you are amazed by the width of his shoulders.}
{21590}{}{Arnold Mitch}
{21591}{}{A man in an oiled jumpsuit, welder's glasses are visible on his head among a pile of unwashed hair.}
{21600}{}{Valdis Goose}
{21601}{}{An obese man who stinks of fish. Maybe he came from the depths of the ocean? You have no idea.}
{21610}{}{Sigurd Kroft}
{21611}{}{A short, dark-haired man who looks at you like a merchant looks at a customer.}
{21620}{}{Amelie Croft}
{21621}{}{A middle-aged woman with huge bags under her eyes. You can see that she is very tired, but the smile on her face is quite sincere.}
{21630}{}{Billy Lee}
{21631}{}{The Dragon's Follower. This guy reminds you of someone, or maybe he has a brother. A big, obviously strong fighter.}
{21640}{}{Jimmy Lee}
{21641}{}{The Dragon's Follower. It seems like you've seen him before, or maybe he has a twin brother. He looks very strong.}
{21650}{}{Bum Lucas}
{21651}{}{A couple of alcohol-clouded eyes are looking at you from behind a huge matted dirty beard.}
{21660}{}{Quintara Ainis}
{21661}{}{An ordinary-looking pretty girl.}
{21670}{}{Akira Homma}
{21671}{}{An elderly woman of about fifty, from her clothes it can be assumed that she is an experienced trapper.}
{21680}{}{Sun Hei}
{21681}{}{This guy is clearly an experienced survivalist and a hunter, his trophies speak for themselves.}
{21690}{}{Bingo Box}
{21691}{}{A bald, gap-toothed little lisp peasant with a cunning face.}
{21700}{}{Fisherman}
{21701}{}{This person has probably seen more fish than you have fired bullets in your entire life.}
{21710}{}{Peasant}
{21711}{}{Being a peasant is not easy work, it's good that you are an ordinary wanderer.}
{21720}{}{Peasant}
{21721}{}{Because of the dirt, the true color of her skin remains a mystery to you.}
{21730}{}{Yakuza Fighter}
{21731}{}{A stern-looking Asian, he's definitely a bandit. The edges of bright tattoos are visible from under the clothes.}
{21740}{}{Yakuza Fighter}
{21741}{}{This lady will give a head start to any man, it's better not to mess with tattooed Asians.}
{21750}{}{Shi Fighter}
{21751}{}{A representative of a large Shi clan, perhaps he is a peasant, or maybe even a bandit.}
{21760}{}{Shi Fighter}
{21761}{}{There are also women in Shi, perhaps they will accept you as well... it's up to you to find connections.}
{21770}{}{Moloch's Soldier}
{21771}{}{You are absolutely sure that if you are not facing a raider, then it is something very close to a raider in front of you.}
{21780}{}{Whore}
{21781}{}{Do you want to have fun? Then go to the circus. This dirty whore is trying to earn some money.}
{21790}{}{Whore}
{21791}{}{Have you heard that some Asian women have a dick? Are you sure that you want to check?}
{21800}{}{Pimp}
{21801}{}{This cool guy is cool enough to keep his girls in check.}
{21810}{}{Dealer}
{21811}{}{Judging by his appearance he uses part of the goods himself.}
{21820}{}{Dealer}
{21821}{}{A drug dealer, the most ordinary one, most likely he is engaged in deliveries from Reno.}
{21830}{}{Moloch's Soldier}
{21831}{}{You are absolutely sure that if you are not facing a raider, then something very close is in front of you.}
{21840}{}{Moloch's Soldier}
{21841}{}{You are absolutely sure that if you are not facing a raider, then it is something very close to a raider in front of you.}
{21850}{}{Shi Commander}
{21851}{}{This Shi representative looks like a junior officer, probably his squad is somewhere nearby.}
{21860}{}{Shi Commander}
{21861}{}{This is an example of a woman who effectively commands men. Everything about these Asians is wrong.}
{21870}{}{Shi Fighter}
{21871}{}{A representative of the large Shi clan, perhaps he is a peasant, or maybe even a bandit.}
{21880}{}{Shi Fighter}
{21881}{}{There are also women in the Shi, perhaps they will accept you as well... it's up to you to find connections.}

#FORP 2019 NPC
{22000}{}{Rat}
{22001}{}{A rat. Quite a small bastard.}
{22010}{}{Mantis}
{22011}{}{A mantis. Its cold-blooded eyes are fixed on you, it chirps very loudly and unpleasantly.}
{22020}{}{Ant}
{22021}{}{An ant. The antennae point at you, accompanied by the gaze of a predator.}
{22030}{}{Ant-lion}
{22031}{}{This hefty ant looks especially disgusting and dangerous, its thick shell is covered with a white viscous liquid and its mouth is huge.}
{22040}{}{Pig-rat}
{22041}{}{A pig-rat. It makes sounds that resemble a squeak and a grunt all together.}
{22050}{}{Mole Rat}
{22051}{}{The mole rat. This huge creature is growling loudly.}
{22060}{}{Mutant mole rat}
{22061}{}{A mountain of muscles and huge red eyes. Viscous saliva flows from the fangs. The mutant smells extremely bad.}
{22070}{}{Silver Gecko}
{22071}{}{A silver gecko. This is a simple small lizard.}
{22080}{}{Golden Gecko}
{22081}{}{A golden Gecko. This big gecko clacks its sharp teeth loudly.}
{22090}{}{Cave Gecko}
{22091}{}{A small creature with a dark skin color. Scars and scuffs from being in the cave are visible all over the body. Yellow eyes constantly seem to run around the environment.}
{22100}{}{Dog}
{22101}{}{A dog. A mongrel of normal sizes.}
{22110}{}{Wasp}
{22111}{}{A large mutated insect with large wings. Greenish eyes and sharp thorns are all over the body.}
{22120}{}{Cockroach}
{22121}{}{A nasty, large and extremely nimble cockroach. It has long antennae and legs, as well as a relatively strong shell.}
{22130}{}{Small black radscorpion}
{22131}{}{A small black radscorpion. This is a small but dangerous scorpion.}
{22140}{}{Black radscorpion}
{22141}{}{A black radscorpion. Directs his black tail at you.}
{22150}{}{Cave radscorpion}
{22151}{}{A large scorpion with a gray shell and a massive black tail.}
{22160}{}{Brahmin}
{22161}{}{A brahmin. Flies fly over its heads.}
{22170}{}{Predator plant}
{22171}{}{A predator plant. A strange, eyeless mouth is held on a thick stalk and beckons you with a smile.}
{22180}{}{Wanamingo}
{22181}{}{A wanamingo. This thing has no eyes, no fingers. What a terrible sight.}
{22190}{}{Deathclaw cub}
{22191}{}{A deathlaw cub. Slightly smaller than you, but is certainly dangerous!}
{22200}{}{Deathclaw}
{22201}{}{A deathclaw. It's lowering its large paws down, sniffing the prey.}
{22210}{}{Hunter Deathclaw}
{22211}{}{Hunter Deathclaw. This creature is gray in color, it is much more dangerous than the strongest deathclaw in the pack.}
{22220}{}{Fire Gecko}
{22221}{}{A fire gecko. Faint smoke comes from the nostrils.}
{22230}{}{Beast}
{22231}{}{A clawed, short, stocky gray colored creature.}
{22240}{}{Centaur}
{22241}{}{A centaur. Muddy mucus flows from a long tentacle-like tongue.}
{22250}{}{Floater}
{22251}{}{A floater. It floats in the air, emitting harmful gases through the pores of the subcutaneous sac.}
{22260}{}{Mirelurk}
{22261}{}{A mirelurk. A formidable creature from the depths of a sea or a swamp.}
{22270}{}{Yao-gai}
{22271}{}{A huge, muscular bear-like creature with impressive paws covered with sparse hair. There are ulcers and scars on the body. It has incredibly sharp teeth and long claws the size of a human hand.}
{22280}{}{Creepy croc}
{22281}{}{A large, wriggling creature with long, dangerous paws, sharp fangs and a strong tail.}
{22290}{}{Shadow croc}
{22291}{}{A large, wriggling, dark creature with long, dangerous paws, sharp fangs and a strong tail.}
{22300}{}{Decaying ghoul}
{22301}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22310}{}{Wild ghoul}
{22311}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22320}{}{Mutated ghoul}
{22321}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
{22330}{}{Huge mutated ghoul}
{22331}{}{A wild ghoul, not an ounce of humanity can be seen in its eyes.}
#FORP NCR SOLDIERS
{22340}{}{Soldier}
{22341}{}{He has a visible patch with the image of a two-headed bear.}
{22350}{}{Soldier}
{22351}{}{He has a visible patch with the image of a two-headed bear.}
{22360}{}{Soldier}
{22361}{}{He has a visible patch with the image of a two-headed bear.}
{22370}{}{Soldier}
{22371}{}{He has a visible patch with the image of a two-headed bear.}
{22380}{}{Soldier}
{22381}{}{He has a visible patch with the image of a two-headed bear.}
{22390}{}{Soldier}
{22391}{}{He has a visible patch with the image of a two-headed bear.}
#FORP RAINGERS
{22400}{}{Soldier}
{22401}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{22410}{}{Soldier}
{22411}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{22420}{}{Soldier}
{22421}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{22430}{}{Soldier}
{22431}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{22440}{}{Soldier}
{22441}{}{On the chest there is a badge in the form of a five-pointed golden star.}
{22450}{}{Soldier}
{22451}{}{On the chest there is a badge in the form of a five-pointed golden star.}
#FORP BoS SOLDIERS
{22460}{}{Soldier}
{22461}{}{The armor depicts a winged sword and gears.}
{22470}{}{Soldier}
{22471}{}{The armor depicts a winged sword and gears.}
{22480}{}{Soldier}
{22481}{}{The armor shows a winged sword and gears.}
{22490}{}{Soldier}
{22491}{}{The armor shows a winged sword and gears.}
{22500}{}{Soldier}
{22501}{}{The armor shows a winged sword and gears.}
{22510}{}{Soldier}
{22511}{}{The armor depicts a winged sword and gears.}
#FORP ENCLAVE SOLDIERS
{22520}{}{Soldier}
{22521}{}{On their chest is the "E" emblem surrounded by stars.}
{22530}{}{Soldier}
{22531}{}{On their chest is the "E" emblem surrounded by stars.}
{22540}{}{Soldier}
{22541}{}{On their chest is the "E" emblem surrounded by stars.}
{22550}{}{Soldier}
{22551}{}{On their chest is the "E" emblem surrounded by stars.}
{22560}{}{Soldier}
{22561}{}{On their chest is the "E" emblem surrounded by stars.}
{22570}{}{Soldier}
{22571}{}{On their chest is the "E" emblem surrounded by stars.}
#FORP VAULT_CITY SOLDIERS
{22580}{}{Soldier}
{22581}{}{On their shoulder pad is the emblem "VC".}
{22590}{}{Soldier}
{22591}{}{The logo on the shoulder pad there is the emblem "VC".}
{22600}{}{Soldier}
{22601}{}{On their shoulder pad is the emblem "VC".}
{22610}{}{Soldier}
{22611}{}{On their shoulder pad is the emblem "VC".}
{22620}{}{Soldier}
{22621}{}{On their shoulder pad is the emblem "VC".}
{22630}{}{Soldier}
{22631}{}{On their shoulder pad is the emblem "VC".}
#FORP RENEGADE SOLDIERS
{22640}{}{Soldier}
{22641}{}{There are no distinguishing features on the armor.}
{22650}{}{Soldier}
{22651}{}{There are no distinguishing features on the armor.}
{22660}{}{Soldier}
{22661}{}{There are no distinguishing features on the armor.}
{22670}{}{Soldier}
{22671}{}{There are no distinguishing features on the armor.}
{22680}{}{Soldier}
{22681}{}{There are no distinguishing features on the armor.}
{22690}{}{Soldier}
{22691}{}{There are no distinguishing features on the armor.}
#GENERIC DWELLERS
{22700}{}{Whore} 
{22711}{}{A typical prostitute.}

