# 08.2007 Cvet

# Version info
{1}{}{FalloutRP}

####################################################################################################################################
#
#		Months, Day of week
#
####################################################################################################################################

{21}{}{January}
{22}{}{February}
{23}{}{March}
{24}{}{April}
{25}{}{May}
{26}{}{June}
{27}{}{July}
{28}{}{August}
{29}{}{September}
{30}{}{October}
{31}{}{November}
{32}{}{December}

{33}{}{Sunday}
{34}{}{Monday}
{35}{}{Tuesday}
{36}{}{Wednesday}
{37}{}{Thursday}
{38}{}{Friday}
{39}{}{Saturday}

####################################################################################################################################
#
#		Material Types (from PROTO.MSG)
#
####################################################################################################################################

{40}{}{Glass}
{41}{}{Metal}
{42}{}{Plastic}
{43}{}{Wood}
{44}{}{Dirt}
{45}{}{Stone}
{46}{}{Cement}
{47}{}{Leather}

####################################################################################################################################
#
#		Misc
#
####################################################################################################################################

{50}{}{.}
{52}{}{,}
{53}{}{ }
{54}{}{ and }
{55}{}{ or }

####################################################################################################################################
#
#		Music/Video
#
####################################################################################################################################

# Main theme
{80}{}{Sleepless Ruins.ogg}
# Intro, from 90 to 99
#{90}{}{}
#{91}{}{}

####################################################################################################################################
#
#		Chat
#
####################################################################################################################################

# On head messages
{100}{}{|0xF8F993 %s}                     # Normal
{102}{}{|0xFF0000 !!!%s!!!}               # Shout
{104}{}{|0xFF00FF **%s**}                 # Emote
{106}{}{|0x00FFFF ...%s...}               # Whisp
{108}{}{|0xFFFFFF %s}                     # Social

# Message box
{120}{}{%s: |0xF8F993 %s}                 # Normal
{122}{}{%s: |0xFF0000 !!!%s!!!}           # Shout
{124}{}{%s: |0xFF00FF **%s**}             # Emote
{126}{}{%s: |0x00FFFF ...%s...}           # Whisp
{128}{}{%s: |0xFFFFFF %s}                 # Social
{130}{}{Рация %u> |0xFFFFFE ..%s..}       # Radio
{132}{}{%s}                               # NetMsg

{135}{}{name mode off}                    # radio names
{136}{}{bad chars in name. must be a(A)-z(Z) && 0-9}                   # radio names
{137}{}{min name length is 3}		 # radio names
{138}{}{max name length is 8}
{139}{}{radio name changed}
{140}{}{|0xFFFF00 Cant send - radio is on a failsafe.}
{141}{}{|0xFFFF00 Can't use commands during waiting.}
{142}{}{Symbols: |0xFFFF00 ()[]{}<>@#~^_ are prohibited for use in direct speech!}
{143}{}{mumbling}
{144}{}{unintelligible mumbling}
{145}{}{mumbles}
{146}{}{unintelligible sounds}

#Naming
{150}{}{Choose whom to name: "|}
{151}{}{You memorise: "|}
{152}{}{Names remembered: |0xFFFF00 }

####################################################################################################################################
#
#		FixBoy
#
####################################################################################################################################

{200}{}{Demands:}
{201}{}{Tools:}
{202}{}{Materials:}
{205}{}{pc.}
{206}{}{You have }
{210}{}{You have successfully created an item.}
{211}{}{You didn't manage to create the item.}
{212}{}{You are too tired, try again later.}

####################################################################################################################################
#
#		Interface text
#
####################################################################################################################################

{250}{}{|4291317840 This feature is not yet implemented. Use the FOConfig.exe to edit the game settings.}
{251}{}{Screenshot saved.}
{252}{}{Unable to save screenshot.}
{253}{}{Log saved.}
{254}{}{Unable to save log.}

{260}{}{Zoom %d %%}
{265}{}{Game paused}

# Dialog
{275}{}{Barter}
{276}{}{Say}
{277}{}{Log}
# Barter
{280}{}{Offer}
{281}{}{Talk}
{282}{}{Finish}
{283}{}{Say}
# Menu
{290}{}{Save game}    # Singleplayer
{291}{}{Load game}    # Singleplayer
{292}{}{Options}
{293}{}{Exit}
{294}{}{Resume}
# Login
{300}{}{New game}     # Singleplayer
{301}{}{Load game}    # Singleplayer
{302}{}{Start}        # Multiplayer
{303}{}{Registration} # Multiplayer
{304}{}{Options}
{305}{}{Credits}
{306}{}{Exit}
# Dialog box
{310}{}{Cancel}
{311}{}{Ok}
{312}{}{Follow}
{313}{}{Open mode}
{314}{}{Hide mode}
{315}{}{Real-time}
{316}{}{Turn-based}
# Reg name
{320}{}{Name}
{321}{}{Password}
# Reg Skin
{322}{}{hmjmps hmlwar hmbwar HMLWTRB hfprim HFPUNP hfblpr hfrprim nfprem HFYTRB HMBPRS nmhair hm2bsb HMBPRM nmfatt nmmyrn nmwarr}
{323}{}{62 110 120 418 61 151 279 392 256 396 140 236 284 353 91 88 64}
{324}{}{This skin doesn't match character gender.}
# Cha
{325}{}{Done}
{326}{}{Back}
{327}{}{Print}
{328}{}{Skills}
{329}{}{Skill points}
# Reg
{335}{}{Tag skills}
{336}{}{Char points}
# Perk
{340}{}{Take}
{341}{}{Back}
# Global map
{350}{}{You can not lead this group.}
{351}{}{}
{352}{}{}
{353}{}{}
# Aim
{360}{}{Aim is blocked.}
# Split
{365}{}{Move items}
{366}{}{All}
# Timer
{370}{}{Timer}
# Say screen
{375}{}{Done}
{376}{}{Back}
{377}{}{Say...}
# Input box
{380}{}{Write}
{381}{}{Back}
# Town view
{385}{}{Back}
{386}{}{Enter}
{387}{}{Contours}
# Save/Load
{390}{}{Save}
{391}{}{Load}
{392}{}{Done}
{393}{}{Back}
{394}{}{New record}
{395}{}{Enter record name}

####################################################################################################################################
#
#		Inventory (with INVENTRY.MSG + 400)
#
####################################################################################################################################

{400}{}{ST}
{401}{}{PE}
{402}{}{EN}
{403}{}{CH}
{404}{}{IN}
{405}{}{AG}
{406}{}{LK}
{407}{}{HP:}
{408}{}{Armor Class: VALUE}
{409}{}{  Normal}
{410}{}{  Laser}
{411}{}{  Fire}
{412}{}{  Plasma}
{413}{}{  Explode}
{414}{}{No Item}
{415}{}{Damage:}
{416}{}{Eff. Range: }
{417}{}{Ammo Count: }
{418}{}{Loaded Ammo: }
{419}{}{You don't have enough action points to access the inventory.}
{420}{}{Total Weight:}
{421}{}{MOVE ITEMS}
{422}{}{ALL}
{423}{}{SET TIMER}
{424}{}{Unarmed dmg:}
{425}{}{You cannot pick that up. You are at your maximum weight capacity.}
{426}{}{There is no space left for that item.}
{427}{}{Dmg. Organ}
{428}{}{AP Regen: VALUE}
{429}{}{For your successful thievery you receive %d experience.}
{430}{}{Wt.}
{431}{}{Volume: |0xE5C62B VALUE|0x3CF800 .}
{433}{}{You find nothing useful.}
{434}{}{Ammo: |0xE5C62B VALUE|0x3CF800| /|0xE5C62B| MAX_VALUE|0x3CF800 .}
{435}{}{Weight: |0xE5C62B VALUE |0x3CF800 grams.}
{436}{}{Weight: |0xE5C62B VALUE |0x3CF800 lb.}
{437}{}{Cost: |0xE5C62B VALUE |0x3CF800 dollars.}
{438}{}{Trader cost: |0xE5C62B VALUE |0x3CF800 dollars.}
{439}{}{Reloading}
{440}{}{Overweight}
{441}{}{Sneak}
{442}{}{Level}
{443}{}{Poisoned}
{444}{}{Radiated}
{445}{}{Injured}
{446}{}{Addict}
{447}{}{Timeout VALUE}
{448}{}{Oversize}
{449}{}{Your turn VALUE}
{450}{}{Turn-based}

####################################################################################################################################
#
#		Radio
#
####################################################################################################################################

{455}{}{Radio}
{456}{}{Channel}
{457}{}{Refresh}
{458}{}{Broadcast}
{459}{}{Reception}
{460}{}{Everywhere}
{461}{}{5 zones}
{462}{}{2 zones}
{463}{}{Location}
{464}{}{Map}
{465}{}{Broadcasting has begun.}
{466}{}{Broadcasting has ended.}
{467}{}{Broadcasting has changed.}
{468}{}{Radio reception has begun.}
{469}{}{Radio reception has ended.}
{470}{}{Radio reception has changed.}
{471}{}{Channel changed.}
{474}{}{Unable to switch channel.}
{475}{}{Unable to switch broadcast.}
{476}{}{Unable to switch reception.}
{477}{}{Unable to switch broadcast type.}
{478}{}{Unable to switch reception type.}
{479}{}{You do not have the radio tuned to the transmission channel.}

####################################################################################################################################
#
#		Barter
#
####################################################################################################################################

{480}{}{Ok, that's a good trade.}
{481}{}{No, your offer is not good enough.}
{482}{}{Sorry, you can't carry that much.}
{483}{}{Sorry, that's too much to carry.}
{484}{}{No item was selected at the moment of the deal.}
{485}{}{Sorry, but I've already sold a couple of those things.}
{486}{}{You can't trade right now.}
{487}{}{You can't trade with this person.}
{490}{}{%s wants to trade with you. Trade mode : %s.}
{491}{}{open}
{492}{}{hidden}
{493}{}{You can't trade with this person right now. Try again later.}
{495}{}{Trading with %s. Your mode: %s, opponent's mode: %s.}
{496}{}{%s is ready for the deal.}

####################################################################################################################################
#
#		Items info
#
####################################################################################################################################

# Wear
{500}{}{|0x3CF800 Condition: |0xE5C62B| VALUE%|0x3CF800| .}
{501}{}{Has been repaired.}
{502}{}{Had extensive maintenance.}
{503}{}{Minor damage.}
{504}{}{Looks broken.}
{505}{}{Looks severely broken.}
{506}{}{Item beyond repair.}
{507}{}{Broken: |0xE5C62B| VALUE |0x3CF800| times.}

{510}{}{Maintenance already performed.}
{511}{}{Maintenance successful.}
{512}{}{Maintenance failed.}
{515}{}{Item repaired successfully.}
{516}{}{You failed to repair the item.}

{520}{}{Your armor has broken.}
{521}{}{Your weapon has broken.}

# Key
{550}{}{Key number: |0xE5C62B KEY_ID|0x3CF800 .}

# Car
{560}{}{Car number CAR_ID.}
{561}{}{Fuel: |0xE5C62B VALUE|0x3CF800| /|0xE5C62B| MAX_VALUE|0x3CF800 .}
{562}{}{Damage: |0xE5C62B VALUE%|0x3CF800 .}

# FORP Additional Enduser Info
{563}{}{Min. Strength: |0xE5C62B VALUE|0x3CF800 .}
{564}{}{Delay: |0xE5C62B VALUE |0x3CF800 ms.}
{565}{}{Use: |0xE5C62B VALUE |0x3CF800 AP.}
{567}{}{Electro}

{568}{}{Reloading: |0xE5C62B VALUEAP |0x3CF800 AP, |0xE5C62B VALUEMS |0x3CF800 ms.}
{569}{}{Reloading: |0xE5C62B VALUE |0x3CF800 AP.}
{570}{}{Perks:}
{571}{}{Caliber: |0xE5C62B AMMO |0x3CF800 }

{576}{}{Armor Class: -VALUE.}

# Ammo inventory stats
{600}{}{Armor Class Mod: |0xE5C62B ACMOD|0x3CF800 .}
{601}{}{Damage Mul.: |0xE5C62B MULT|0x3CF800 \|0xE5C62B DIV|0x3CF800 .}
{602}{}{Resist Mod.: |0xE5C62B DRMOD|0x3CF800 .}
{603}{}{Threshold Mod.: |0xE5C62B DTMOD|0x3CF800 .}
{604}{}{Damage Type: |0xE5C62B DMGTYPE|0x3CF800 .}

####################################################################################################################################
#
#		PipBoy, Timeouts
#
####################################################################################################################################

{700}{}{----- Status -----}
{701}{}{Replication balance}
{702}{}{%d dollars}
{703}{}{Replication cost}
{704}{}{%d dollars}
{705}{}{Total replications}
{706}{}{%d times}
{720}{}{----- Quests -----}
{723}{}{<<<<< Statistics >>>>>}
{725}{}{----- Maps -----}
{730}{}{----- Info -----}

{740}{}{----- Timeouts -----}
{741}{}{%s second}
{742}{}{%s minute}
{790}{}{|0xFFFF00 Transition timeout. Wait.}
{791}{}{|0xFFFF00 Combat timeout. Wait.}
{792}{}{|0xFFFF00 Sneak timeout. Wait.}

{795}{}{Loading information...}
{796}{}{Loading error! Please restart your PipBoy.}

####################################################################################################################################
#
#		Dialogs
#
####################################################################################################################################

{800}{}{They don't seem interested in talking to you.}
{801}{}{They don't seem to be able to talk now.}
{802}{}{They seem to be busy. Speak to them later.}
{803}{}{You need to get closer to talk to them.}
{804}{}{Hi.} # No dialigues.
{805}{}{NPC is talking to another player. Try talking to them later.}
{806}{}{Pre-dialogue settings error.}
{807}{}{Broken dialog link.}
{808}{}{Dialog layout error.}
{809}{}{NPC not found.}
{810}{}{Invalid dialog pointer.}

####################################################################################################################################
#
#		Global map
#
####################################################################################################################################

{900}{}{|0xFFFF00 You haven't found the location. It was absorbed by the desert.}
{901}{}{|0xFFFF00 Surprisingly, the location has moved.}
{902}{}{|0xFFFF00 You haven't found the location entrance.}
{903}{}{|0xFFFF00 You haven't found a suitable place to park your vehicle.}
{904}{}{|0xFFFF00 The location is full, try to enter later.}
{905}{}{|0xFFFF00 You can't move in that direction.}
{906}{}{|0xFFFF00 You are too far from exit grid.}
{907}{}{|0xFFFF00 Access to this location is forbidden, it will be opened when the plot unfolds.}
{908}{}{|0xFFFF00 You use secret paths to avoid natural obstacles.}
{909}{}{|0xFFFF00 You have no idea how to trespass this terrain.}
{910}{}{|0xFFFF00 You can't move in that direction; there are no free hexes.}
{911}{}{|0xFFFF00 Something went wrong.}
{912}{}{You feel danger. Move in this direction?}
{913}{}{Yes}
{914}{}{|0xFFFF00 The air in here restricts breathing. It seems, you better find a respirator.}
{915}{}{Unavailable}
{916}{}{Wasteland}

{950}{}{|0xFFFF00 Are you ready to follow %s into %s?}
{952}{}{|0xFFFF00 Get ready to follow %s into %s.}
{970}{}{|0xFFFF00 the stranger}
{972}{}{|0xFFFF00 the wasteland}

####################################################################################################################################
#
#		Maintenance
#
####################################################################################################################################

{1001}{}{|4291317840 Incorrect login.}
{1002}{}{|4291317840 Incorrect password.}
{1003}{}{|4291317840 An account with this login already exists, choose another login.}
{1004}{}{|4291317840 A player with this login is already in game.}
{1005}{}{|4291317840 Incorrect SPECIAL data.}
{1006}{}{|4291317840 Registration was successful.}
{1007}{}{|4291317840 Connecting to server.}
{1008}{}{|4291317840 Connection failure! In case of repetition contact the server administrator.}
{1009}{}{|4291317840 Incorrect login or password.}
{1010}{}{|4291317840 Connection established, authentication...}
{1012}{}{|4291317840 Hexes for spawning are in use, try to enter the game a little bit later.}
{1013}{}{|4291317840 Switching off on the player's instruction.}
{1014}{}{|4291317840 Incorrect name. Probably too long or short.}
{1015}{}{|4291317840 One of name declinations is incorrect. Probably too long or short.}
{1016}{}{|4291317840 Incorrect sex.}
{1017}{}{|4291317840 Incorrect age.}
{1018}{}{|4291317840 It was not possible to connect to the server.}
{1019}{}{|4291317840 Incorrect data entered.}
{1020}{}{|4291317840 Searching starting location error, contact serever's administration.}
{1021}{}{|4291317840 Searching starting map error, contact server's administration.}
{1022}{}{|4291317840 Searching starting coordinates error, contact server's administration.
{1023}{}{|4291317840 Database error, contact server administrator.}
{1024}{}{|4291317840 Version of the network protocol is incorrect, please update the client.}
{1025}{}{|4291317840 Data transmission error, try once again.}
{1026}{}{|4291317840 The network message is incorrect.}
{1027}{}{|4291317840 A server #1 internal error, please contact server's administration.}
{1028}{}{|4291317840 Authentication successful, loading map.}
{1029}{}{|4291317840 Choose 3 tag skills.}
{1030}{}{|4291317840 Name must be in one language.}
{1031}{}{|4291317840 Name must consist of letters by 70% at least.}
{1032}{}{|4291317840 You can't use space as first or last symbol for your name.}
{1033}{}{|4291317840 You can't use two spaces in a row for your name.}
{1034}{}{|4291317840 Your account is banned.}
{1035}{}{|4291317840 Invalid characters in name.}
{1036}{}{|4291317840 Invalid characters in password.}
{1037}{}{|4291317840 Loading user interface failure.}
{1038}{}{|4291317840 Executing start script failure.}
{1039}{}{|4291317840 Selected language not supported. Using default language.}
{1040}{}{|4291317840 The game may not work properly at resolutions less than 800x600 or greater than 1280x1024.}
{1041}{}{|4291317840 Knock-knock, anybody here?}
{1042}{}{|4291317840 Discovered frequent registration from one IP address. Please try again later.}
{1043}{}{|4291317840 Your IP is banned.}
{1044}{}{|4291317840 Minimum time from one computer to one account is 1 minute.}
{1045}{}{|4291317840 Time left: @lex time@ minutes.}
{1046}{}{|4291317840 You have been banned.}
{1047}{}{|4291317840 Ban from: @lex banby@, Duration: @lex time@ часов, Comment: @lex reason@.}
{1048}{}{|4291317840 Script error, please contact server administrator.}
{1049}{}{|4291317840 Your character is dead, it is not possible to continue playing on this account. Get used to it, wipe your tears and make a new one.}
{1050}{}{|4291317840 The selected traits can't be combined together!}

#Client info chat messages 1059 <-> 1069
{1059}{}{ }
{1060}{}{ }
{1061}{}{You can set a custom screen resolution of the game in the file "|0xF2E519 FOConfig.exe|0x3CF800| ".}
{1062}{}{Loading config "|0xF2E519 default.ini|0x3CF800| "... Successfully completed. Classic interface activated. 
Welcome to FalloutRP!}
{1063}{}{Loading config "|0xF2E519 rp_default.ini|0x3CF800| "... Successfully completed. New interface activated. 
Welcome to FalloutRP!}
{1064}{}{|4291317840 Interface loading error, no game configuration files found. It is recommended to use "|0xF2E519 Updater.exe|0x3CF800| ".}

# Singleplayer messages
{1070}{}{|4291317840 Game saved.}
{1071}{}{|4291317840 Error saving game.}
{1072}{}{|4291317840 Game loaded.}
{1073}{}{|4291317840 Error loading game.}
{1074}{}{|4291317840 New game beginning.}
{1075}{}{|4291317840 Failed to start a new game.}

####################################################################################################################################
#
#		Character
#
####################################################################################################################################

#
# STAT LEVEL DESCRIPTIONS
#
{2301}{}{V. Bad}
{2302}{}{Bad}
{2303}{}{Poor}
{2304}{}{Fair}
{2305}{}{Average}
{2306}{}{Good}
{2307}{}{V. Good}
{2308}{}{Great}
{2309}{}{Excellent}
{2310}{}{Heroic}

#Abbreviated, for editor
{2311}{}{V.Bad}
{2312}{}{Bad}
{2313}{}{Poor}
{2314}{}{Fair}
{2315}{}{Avrg}
{2316}{}{Good}
{2317}{}{V.Good}
{2318}{}{Great}
{2319}{}{Exl.}
{2320}{}{Heroic}

#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{3300}{}{+ (4 x AG)}
{3301}{}{+ (2 x AG)}
{3302}{}{+ (2 x AG)}
{3303}{}{+ (AG + ST)х2}
{3304}{}{+ (AG + ST)х2}
{3305}{}{+ (4 х AG)}
{3306}{}{+ (PE + IN)х2}
{3307}{}{+ (PE + IN)}
{3308}{}{+ (3 х AG)}
{3309}{}{+ (PE + AG)}
{3310}{}{+ (3 х AG)}
{3311}{}{+ (PE + AG)}
{3312}{}{+ (4 x IN)}
{3313}{}{+ (3 х IN)}
{3314}{}{+ (5 x CH)}
{3315}{}{+ (4 x CH)}
{3316}{}{+ (5 x LK)}
{3317}{}{+ (EN + IN)х2}
#
# SKILLDEX
#
{3340}{}{SKILLDEX}
{3341}{}{CANCEL}

#
#   Skill Use Text
#
{3400}{}{|0xFFFF00 You can't heal the dead.}
{3400}{}{|0xFFFF00 Let the dead rest in peace.}
{3400}{}{|0xFFFF00 Clearly dead, get over it.}
{3401}{}{|0xFFFF00 You've taxed your ability with that skill. Wait a while.}
{3401}{}{|0xFFFF00 You're too tired.}
{3401}{}{|0xFFFF00 The strain might kill you.}
{3402}{}{|0xFFFF00 First aid isn't needed.}
{3403}{}{|0xFFFF00 Surgery isn't needed.}
{3404}{}{|0xFFFF00 To heal this trauma, you need a Doctor.}
{3405}{}{|0xFFFF00 To heal these wounds, you need First Aid.}

{3412}{}{|0xFFFF00 You heal the damaged eye.}
{3413}{}{|0xFFFF00 You heal the crippled right arm.}
{3414}{}{|0xFFFF00 You heal the crippled left arm.}
{3415}{}{|0xFFFF00 You heal the crippled right leg.}
{3416}{}{|0xFFFF00 You heal the crippled left leg.}
{3422}{}{|0xFFFF00 You fail to heal the damaged eye.}
{3423}{}{|0xFFFF00 You fail to heal the crippled right arm.}
{3424}{}{|0xFFFF00 You fail to heal the crippled left arm.}
{3425}{}{|0xFFFF00 You fail to heal the crippled right leg.}
{3426}{}{|0xFFFF00 You fail to heal the crippled left leg.}

{3430}{}{|0xFFFF00 Someone tried to rob you!}
{3431}{}{|0xFFFF00 Someone tried to plant something on you!}

{3440}{}{|0xFFFF00 You failed to pick the lock.}
{3441}{}{|0xFFFF00 You failed to set the trap.}
{3442}{}{|0xFFFF00 You set the trap.}
{3443}{}{|0xFFFF00 You failed to remove the trap.}
{3444}{}{|0xFFFF00 You failed to deactivate the trap.}
{3445}{}{|0xFFFF00 You can't enter sneak mode when somebody sees you.}

{3450}{}{|0xFFFF00 You heal %d hit points.}
{3451}{}{|0xFFFF00 You look healthy already.}
{3452}{}{|0xFFFF00 %s looks healthy already.}
{3453}{}{|0xFFFF00 You fail to do any healing.}
{3455}{}{|0xFFFF00 You earn %d XP for honing your skills.}
{3459}{}{|0xFFFF00 \nskill_use: invalid skill used.}
{3461}{}{|0xFFFF00 You fail to find any traps.}
{3462}{}{|0xFFFF00 You fail to learn anything.}
{3463}{}{|0xFFFF00 You cannot repair that.}
{3470}{}{|0xFFFF00 You're caught stealing the %s.}
{3471}{}{|0xFFFF00 You steal the %s.}
{3472}{}{|0xFFFF00 You're caught planting the %s.}
{3473}{}{|0xFFFF00 You plant the %s.}
{3495}{}{|0xFFFF00 You aren't skilled enough to heal crippling injuries.}
{3496}{}{|0xFFFF00 This robot is beyond repair.}
{3497}{}{|0xFFFF00 This skill is disabled and can't be leveled up.}
{3498}{}{|0xFFFF00 This skill is leveled by using it.}

#
#	 PC STAT NAMES
#
{4000}{}{Character Points}
{4001}{}{Next Level}
{4002}{}{Unspent Skill Points}
{4003}{}{Level}
{4004}{}{Experience}
{4005}{}{Reputation}
{4006}{}{Karma}
{4007}{}{Perks}
{4008}{}{Kills}
{4009}{}{Skill Points}
{4010}{}{Tag Skills}
{4011}{}{Optional Traits}
{4012}{}{Skills}
#
#	 PC STAT DESCRIPTIONS
#
{4050}{}{Amount of free character points that can be added to one of the basic stats.}
{4051}{}{The amount of experience points needed to move up to the next level.}
{4052}{}{Points earned by going up a Level. Can be used to increase a skill.}
{4053}{}{The general competency of the player character. A measure of your experience and abilities.}
{4054}{}{A reward for completing specific tasks, or defeating enemies in combat. More experience points are required to attain higher Levels.}
{4055}{}{What the world knows of your actions and deeds. This will modify NPC reactions.}
{4056}{}{These are the effects of the choices you make during the game.}
{4057}{}{Perks add additional abilities. Every third experience level, you can choose one perk.}
{4058}{}{A counter that keeps track of the type and numbers of creatures you have slaughtered.}
{4059}{}{Use free skill points to increase the level of a skill. As you get better at a given skill, however, it takes more points to raise that skill. Mastering a skill can take a lot of time and effort.}
{4060}{}{Tag skills are skills your character specializes in. Each tag skill gains +20%, and increases twice as fast. You must pick three tag skills.}
{4061}{}{Optional traits describe your character in more detail. All traits will have positive and negative effects. You may choose up to two traits during creation.}
{4062}{}{Skills are learned knowledge. Skills increase by experience, or during the course of the game by special events. The higher the skill level, the better you are at that skill.}

#
#  Experience-gain messages
#
{4090}{}{You have gone up a level.}
{4091}{}{|0xCDCBCB You have gained VALUE experience points.}
{4092}{}{You gained %d experience points for killing : %s.}
{4093}{}{%s you gained %d experience points.}
{4094}{}{For defeating your enemies, }  # 622-626 prepend to line 621
{4095}{}{For slaying your opponents, }
{4096}{}{You are victorious in combat, }
{4097}{}{For crushing your enemies, }
{4098}{}{For destroying your enemies without taking a scratch, }

#
# Editor
#
{4104}{}{AGE}
{4105}{}{SEX}
{4106}{}{NAME}
{4107}{}{MALE}
{4108}{}{FEMALE}
{4109}{}{PERKS}
{4110}{}{KARMA}
{4111}{}{KILLS}
{4112}{}{SKILL POINTS}
{4113}{}{Level: %d}
{4114}{}{Exp: %d}
{4115}{}{Next Level: %d}

#
# Damage info texts
#

{4250}{}{Hit Points  %d/%d}

#
# Karma
#

{6000}{}{Karma}
{6001}{}{: %d (%s)}  # Value, Desc
{6002}{}{This is a ranged stat that represents your general reputation. The higher the number, the better known and respected you are. If your rep is negative, you are hated by some for your evil actions.}

{6099}{}{9} # Max values
{6100}{}{1000} # Min value
{6101}{}{Savior of the Damned} # Desc
{6102}{}{2000} # Picture index
{6103}{}{750}
{6104}{}{Guardian of the Wastes}
{6105}{}{2001}
{6106}{}{500}
{6107}{}{Shield of Hope}
{6108}{}{2002}
{6109}{}{250}
{6110}{}{Defender}
{6111}{}{2003}
{6112}{}{-249}
{6113}{}{Wanderer}
{6114}{}{2004}
{6115}{}{-500}
{6116}{}{Betrayer}
{6117}{}{2005}
{6118}{}{-750}
{6119}{}{Sword of Despair}
{6120}{}{2006}
{6121}{}{-1000}
{6122}{}{Scourge of the Wastes}
{6123}{}{2007}
{6124}{}{-2147483648}
{6125}{}{Demon Spawn}
{6126}{}{2008}

# Town reputation
{6405}{}{Reputation}
{6406}{}{Represents your reputation for a particular location.}

# Name
{6500}{}{Idolized}
{6501}{}{Liked}
{6502}{}{Accepted}
{6503}{}{Neutral}
{6504}{}{Antipathy}
{6505}{}{Hated}
{6506}{}{Vilified}

# Desc
{6550}{}{Everyone in this area would like to be you. You're the toast-of-the-town and are held up as a shining example of all that a person can be.}
{6551}{}{People wave and greet you wherever you go in this area. Everyone has heard talk of you, and they like what they've heard.}
{6552}{}{Although you're not greeted with open arms, most people in this area will at least nod in acknowledgment when you meet. You fit in as well as most.}
{6553}{}{Though normally suspicious of strangers, the people of this area haven't made up their minds about you yet.}
{6554}{}{You're just another out-of-towner in this area, probably up to no good.}
{6555}{}{You've proven to the people in this area that their initial distrust was well founded. People in this area look at you and mutter to one another when you come near. They know you're up to no good.}
{6556}{}{Staring and muttering, some cross the street to avoid walking near you, while others spit and turn away when you come near. Everyone knows that you're one of the worst things that has ever slithered into this area.}

# Addiction title
{6900}{}{Addictions}
{6901}{}{Things you have become addicted to.}

# Critter status title
{7000}{}{Heavy. Dmg.}
{7001}{}{Bullet. Dmg.}
{7002}{}{Bleeding}
{7003}{}{Blood Poison}
{7004}{}{Dirtiness}
{7005}{}{Blood Loss}
{7006}{}{Poisoned}
{7007}{}{Radiated}
{7008}{}{Suffocated}
{7009}{}{Hunger}
{7010}{}{Thirst}
{7011}{}{Drunk}
{7012}{}{Paralysis }
{7013}{}{Cooldown }
{7014}{}{Aim: }
{7015}{}{Weight }
{7016}{}{Volume }
{7017}{}{Combat}
{7018}{}{Tiredness}
{7019}{}{Transfer}
{7020}{}{Action}
{7021}{}{Lockpicking}
{7022}{}{First Aid}
{7023}{}{Doctor}
{7024}{}{Repair}
{7025}{}{Science}
{7026}{}{Overdose}

# Autoaim title
{7500}{}{Eyes}
{7501}{}{Head}
{7502}{}{L. Arm}
{7503}{}{Torso}
{7504}{}{R. Arm}
{7505}{}{L. Leg}
{7506}{}{Abdomen}
{7507}{}{R. Leg}

# Client_main inventory
{7510}{}{The description cant be more than 127 symbols! There are: }
{7511}{}{ symbols remaining!}
{7512}{}{Command not found!}
{7513}{}{Dead can't talk!}
{7514}{}{You have: }
{7515}{}{ Burst: x }
{7516}{}{. Radius: }
{7517}{}{accumulator.}
{7518}{}{Total Volume:}
{7519}{}{kg.}
{7520}{}{Extra Equipment:}
{7521}{}{Head Slot Empty}
{7522}{}{Backpack Slot Empty}
{7523}{}{Utility Slot Empty}

####################################################################################################################################
#
#		Items games
#
####################################################################################################################################

# Message when pointing the cursor on an object
{10000}{}{You see: NAME.}
# Object inspecting message
{10004}{}{NAME}
# Name or info not found
{10010}{}{You see nothing out of the ordinary.}
# Item not found in container (possible another critter take it)
{10020}{}{Item not found, it may have been picked up by someone else.}

# Container
{10100}{}{|0xFFFF00 Need key.}
{10101}{}{|0xFFFF00 You search the %s.}
{10102}{}{|0xFFFF00 You close the %s.}

#
# Use text messages
#
{10200}{}{|0xFFFF00 You use the %s.}
{10201}{}{|0xFFFF00 You use the %s on %s.}
{10202}{}{|0xFFFF00 That does nothing.}
{10203}{}{|0xFFFF00 To your dismay, you realize that it is already dead.}
{10204}{}{|0xFFFF00 As you reach down, you realize that it is already dead.}
{10205}{}{|0xFFFF00 Alas, you are too late.} # This is relating to a critter being dead.
{10206}{}{|0xFFFF00 That won't work on the dead.}
{10207}{}{|0xFFFF00 You light the flare.}
{10208}{}{|0xFFFF00 The flare is already lit.}
{10209}{}{|0xFFFF00 You set the timer.}
{10210}{}{|0xFFFF00 The timer is already ticking!}
{10211}{}{|0xFFFF00 The doorway seems to be blocked.}

# Solar scotcher
{10230}{}{|0xFFFF00 There is not enough light to recharge this item.}

# Car
{10240}{}{You charge the vehicle with more power.}
{10241}{}{The vehicle is already fully charged.}
{10242}{}{The vehicle was repaired successfully.}
{10243}{}{This vehicle doesn't need any maintenance.}
{10244}{}{The engine can't use this type of fuel.}
{10245}{}{This vehicle is out of fuel.}
{10246}{}{The vehicle has broken down.}
{10247}{}{The vehicle can't take so many people, leave some behind.}
{10248}{}{Your charisma doesn't let you lead so many people, leave some behind.}
{10251}{}{Can't leave the group while being on the water.}

# Drugs
{10300}{}{You gained |0xFFFF00 @lex value@ @lex name@|0x3CF800 .}
{10301}{}{You lost |0xFFFF00 @lex value@ @lex name@|0x3CF800 .}
{10302}{}{|0xFFFF00 You have got rid of all addictions and drug effects.}
{10303}{}{|0xFFFF00 You suffer a fatal heart attack from chem overdose.}
{10304}{}{|0xFFFF00 That didn't seem to do that much.}
{10305}{}{|0xFFFF00 %s succumbs to the adverse effects of chems.}
{10306}{}{|0xFFFF00 You have been drugged with something!}
{10307}{}{|0xFFFF00 Somebody tried to drug you with something!}

{10310}{}{injects stimpak}
{10311}{}{injects RadAway}
{10312}{}{drinks antidote}
{10313}{}{swallows mentats pill}
{10314}{}{eats fruit}
{10315}{}{eats iguana on a stick}
{10316}{}{swallows buffout pill}
{10317}{}{eats iguana bits}
{10318}{}{drinks nuka-cola}
{10319}{}{swallows Rad-X pill}
{10320}{}{injects psycho}
{10321}{}{drinks beer}
{10322}{}{drinks booze}
{10323}{}{injects superstimulator}
{10324}{}{inhales jet}
{10325}{}{drinks jet antidote}
{10326}{}{uses healing powder}
{10327}{}{drinks gamma-gulp}
{10328}{}{drinks roentgen-rum}
{10329}{}{eats cookie}
{10330}{}{drinks booze}
{10331}{}{eats meat}
{10332}{}{  .}
{10333}{}{  .}
{10334}{}{  .}
{10335}{}{  .}
{10336}{}{  .}
{10337}{}{  .}
{10338}{}{  .}
{10339}{}{  .}
{10340}{}{  .}
{10341}{}{  .}
{10342}{}{  .}
{10343}{}{  .}
{10344}{}{  .}
{10345}{}{  .}
{10346}{}{  .}
{10347}{}{  .}
{10348}{}{  .}
{10349}{}{  .}

# Geiger
{10350}{}{Geiger counter has no charges left.}
{10351}{}{Geiger counter is on.}
{10352}{}{Geiger counter is off.}
{10353}{}{You pass the Geiger counter over your body. The rem counter reads: @lex rem@.}
{10354}{}{The rem counter reads: @lex rem@.}
{10355}{}{Nothing happens.}
{10356}{}{Geiger counter charged.}
{10357}{}{Geiger counter charge is @lex cur@/@lex max@.}

# Weapon Damage
{10400}{}{Light}
{10401}{}{Medium}
{10402}{}{Heavy}
{10403}{}{Extreme}

# Weapon Range
{10410}{}{Short}
{10411}{}{Medium}
{10412}{}{Long}

# Books
{10450}{}{You read the book.}
{10451}{}{You learn nothing new.}
{10452}{}{You learn new science information.}
{10453}{}{You learn a lot about repairing broken electronics.}
{10454}{}{You learn new ways to heal injury.}
{10455}{}{You learn how to handle your small guns better.}
{10456}{}{You learn how to handle your energy guns better.}
{10457}{}{You learn a lot about wilderness survival.}

# Use on
{10500}{}{The supplies in the Doctor's Bag run out.}
{10501}{}{The supplies in the First Aid Kit run out.}
{10502}{}{You cannot do that in combat.}
{10503}{}{This person will not barter with you.}
{10504}{}{This person has nothing to tell you about.}
{10505}{}{You cannot pick up that item. You are at your maximum weight capacity.}
{10506}{}{The supplies in the Paramedic's Bag run out.}
{10507}{}{The supplies in the Field Medic First Aid Kit run out.}
{10508}{}{This critter can't carry anything.}

# Grave
{10550}{}{|0xFFFF00 This grave has been dug.}
{10551}{}{|0xFFFF00 This grave is filled in.}

# Reloading
{10552}{}{|0xFFFF00 This weapon has no magazine.}
{10553}{}{|0xFFFF00 You are loading from a bandoleer.}
{10554}{}{|0xFFFF00 Current ammo depleted, loading alternative.}
{10555}{}{|0xFFFF00 You have run out of ammo for this caliber.}
{10556}{}{|0xFFFF00 Ammo type changed.}
{10557}{}{|0xFFFF00 You are already busy reloading.}
{10558}{}{changes ammo type}
{10559}{}{You have extracted:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex count@ |0x3CF800 rounds.}
{10560}{}{unloads weapon}
{10561}{}{cocks weapon}
{10562}{}{checks charge}
{10563}{}{reloads weapon}
{10564}{}{You have loaded:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex count@ |0x3CF800 rounds.}

####################################################################################################################################
#
#		Calibers (from PROTO.MSG)
#
####################################################################################################################################

#
# Caliber Types for weapons
#
{10900}{}{None}
{10901}{}{Rocket}
{10902}{}{Falmer fuel}
{10903}{}{Energy pack C}
{10904}{}{Energy pack D}
{10905}{}{.223}
{10906}{}{5.56mm}
{10907}{}{.40 cal.}
{10908}{}{10mm}
{10909}{}{.44 cal.}
{10910}{}{14mm}
{10911}{}{12cal}
{10912}{}{9mm}
{10913}{}{BB}
{10914}{}{.45 cal.}
{10915}{}{2mm}
{10916}{}{4.7mm caseless}
{10917}{}{HN needler}
{10918}{}{7.62mm}
{10919}{}{Bolt}
{10920}{}{40 mm}
{10921}{}{Signal rockets}
{10922}{}{22 mm}
{10923}{}{Spikes}
{10924}{}{.50 cal.}
{10925}{}{12.7mm}
{10930}{}{Nails}

####################################################################################################################################
#
#		Critters game
#
####################################################################################################################################

# CrType
{10950}{}{monster}
{10951}{}{centaur}
{10952}{}{radscorpion}
{10953}{}{ghoul}
{10954}{}{brahmin}
{10955}{}{molerat}
{10956}{}{floater}
{10957}{}{cyber dog}
{10958}{}{dog}
{10959}{}{mantis}
{10960}{}{deathclaw}
{10961}{}{plant}
{10962}{}{silver gecko}
{10963}{}{alien}
{10964}{}{ant}
{10965}{}{mr. handy}
{10966}{}{robobrain}
{10967}{}{roboeye}
{10968}{}{sentury bot}
{10969}{}{turret}
{10970}{}{rat}
{10971}{}{pig rat}
{10972}{}{rat king}
{10973}{}{golden gecko}
{10974}{}{fire gecko}
{10975}{}{alien queen}

#For age and conditions
{11000}{}{You see: }

#Default view
{11010}{}{You see: NAME.}
{11011}{}{You see an unconscious: NAME.}
{11012}{}{You see a dead: NAME.}
{11013}{}{You see the remains of: NAME.}
{11014}{}{You see nothing out of the ordinary.}

# Male
##Age, max age 99
#<=16
{11116}{}{а teenager}
#<=30
{11130}{}{a young man}
#<=40
{11140}{}{a middle-aged man}
#<=60
{11160}{}{an old man}
#>60
{11199}{}{an elderly man}

# Female
##Age, max age 99
#<=16
{12116}{}{teenager}
#<=30
{12130}{}{young woman}
#<=40
{12140}{}{a middle-aged woman}
#<=60
{12160}{}{an old woman}
#>60
{12199}{}{an elderly woman}

//Descriptions for look at char
{12200}{}{Face hidden by the hood}
{12201}{}{Appearance is hidden by armour}
{12202}{}{The body is indistinguishable because of armour}

//General line
{12203}{}{Looks}

//Maniac
{12205}{}{looks angrily at you}
{12206}{}{mumbles something negative about you}
{12207}{}{looks at you with hatred}
{12208}{}{is mocking you you}
{12209}{}{looks contemptuously}
{12210}{}{looks ugly}
{12211}{}{squints in your particualr direction}
{12212}{}{looks hostile}
{12213}{}{grinning at you}
{12214}{}{whispers for you to die}

//Charisma modifier
{12215}{}{|0x3CF8FA alluring|0x3CF800 }
{12216}{}{|0x3CF8FA handsome|0x3CF800 }
{12217}{}{|0x3CF8D2 charming|0x3CF800 }
{12218}{}{|0x3CF8D2 good-looking|0x3CF800 }
{12219}{}{|0x3CF8AA beautiful|0x3CF800 }
{12220}{}{|0x3CF8AA nice-looking|0x3CF800 }
{12221}{}{|0x3CF882 appealing|0x3CF800 }
{12222}{}{|0x3CF882 attractive|0x3CF800 }
{12223}{}{|0xFF0000 sickening|0x3CF800 }
{12224}{}{|0xFF0000 sickening|0x3CF800 }
{12225}{}{|0xFF0000 disgusting|0x3CF800 }
{12226}{}{|0xFF0000 disgusting|0x3CF800 }
{12227}{}{|0xFF0000 unpleasant|0x3CF800 }
{12228}{}{|0xFF0000 unpleasant|0x3CF800 }

//Strength modifier
{12229}{}{very strong}
{12230}{}{very strong}
{12231}{}{strong}
{12232}{}{strong}
{12233}{}{quite weak}
{12234}{}{quite weak}
{12235}{}{weak}
{12236}{}{weak}

//Endurance modifier
{12237}{}{tough}
{12238}{}{tough}
{12239}{}{well built}
{12240}{}{well built}
{12241}{}{delicate}
{12242}{}{delicate}
{12243}{}{slim}
{12244}{}{slim}

//Agility modifier
{12245}{}{agile}
{12246}{}{agile}
{12247}{}{nimble}
{12248}{}{nimble}
{12249}{}{clumsy}
{12250}{}{clumsy}
{12251}{}{graceless}
{12252}{}{graceless}

//General stat
{12253}{}{normal}
{12254}{}{normal}
{12255}{}{normal}

//Gender endings
{12256}{}{}
{12257}{}{}
{12258}{}{}

//Look full
{12500}{}{ He looks: }    # Male
{12501}{}{ She looks: }   # Female
{12502}{}{ It looks: }    # It
{12510}{}{|0xFFFF00 Dead}
{12511}{}{|0xFFFF00 Almost Dead}
{12512}{}{|0xFFFF00 Uncontious} 
{12512}{}{|0xFFFF00 Severely wounded}    
{12513}{}{|0xFFFF00 Badly wounded} 
{12514}{}{|0xFFFF00 Wounded}        
{12515}{}{|0xFFFF00 Lightly wounded} 
{12516}{}{|0x3CF800 Unhurt}       
{12520}{}{|0x3CF800 and has serious damage}               # Male hurt
{12521}{}{|0x3CF800, but has serious damage}              # Male unhurt
{12522}{}{|0x3CF800 and has serious damage}               # Female hurt
{12523}{}{|0x3CF800, but has serious damage}              # Female unhurt
{12524}{}{|0x3CF800 and has serious damage}               # It hurt
{12525}{}{|0x3CF800, but has serious damage}              # It unhurt

# SLOT_HAND1
{12538}{}{Wields}                        
{12539}{}{Wields}                        
{12540}{}{Armament:}
{12541}{}{Holds in mouth:}
{12542}{}{Is carrying MISC}	# Any other item
{12543}{}{Holds in chaps:}
{12544}{}{Holds in mandibles:}
{12545}{}{Holds in pincers:}
{12546}{}{Holds in pincer:}
{12547}{}{Holds in tentacles:}
{12548}{}{Holds in tentacle:}
{12549}{}{Holds in manipulators:}
{12550}{}{Holds in manipulator:}
{12551}{}{Holds in claws:}
{12552}{}{Holds in claw:}

# Other slots
{12570}{}{ She is wearing }
{12571}{}{ He is wearing }
{12572}{}{ She has  }
{12573}{}{ He has  }
{12574}{}{ There is a }
{12575}{}{ on her back.}
{12576}{}{ on his back.}

# items with charges
{12599}{}{Remaining uses: }
# character move restriction
{12600}{}{You can't move.}
# Текст по хоткею - слишком частое использование
{12601}{}{You can't send messages so frequently.}
# robot repair
{12750}{}{You have successfully repaired the robot.}
{12751}{}{You were unable to fix the robot.}
{12752}{}{You have successfully repaired the sensors.}
{12753}{}{You were unable to fix your sensors.}
{12754}{}{You have successfully repaired the right handlebar.}
{12755}{}{You were unable to fix the right manipulator.}
{12756}{}{You have successfully repaired the left manipulator.}
{12757}{}{You were unable to fix the left manipulator.}
{12758}{}{You have successfully repaired the right suspension.}
{12759}{}{You were unable to fix the right chassis.}
{12760}{}{You have successfully repaired the right suspension.}
{12761}{}{You were unable to fix the right chassis.}
{12762}{}{The robot needs no repair.}

####################################################################################################################################
#
#		Plagues
#
####################################################################################################################################

{12800}{}{You feel very nauseous.}
{12801}{}{You feel very nauseous, and after some mild vomiting, slightly fatigued.}
{12802}{}{You are very fatigued, the vomiting does not stop, and your recovery time is impaired.}
{12803}{}{You are hemorrhaging violently. You are very sick, and your hair is falling out.}
{12804}{}{There is bleeding from your intestines and you have severe diarrhea. You feel bloated and are in intense agony.}
{12805}{}{You are hemorrhaging violently and continuously. Your vomit is stained red from your blood. Your skin is falling off of your bones.}
{12806}{}{You have died from radiation sickness.}
{12807}{}{You have received a large dose of radiation.}
{12808}{}{The geiger counter is clicking.}
{12809}{}{The geiger counter is clicking wildly.}
{12810}{}{You have been poisoned!}
{12811}{}{You take damage from poison.}
{12812}{}{You feel a little better.}
{12813}{}{You feel better.}
{12814}{}{You feel poison, but this has no effect on you.}

{12815}{}{You feel weak, your head is dizzy.}
{12816}{}{You're are choking because of the cough.}
{12817}{}{Your skin's pale-white and  your eyes become watery.}

{12818}{}{You have chills and veins appear in nodules on your skin.}
{12819}{}{The skin loses sensitivity in places, other areas itch wildly.}
{12820}{}{Muscles are periodically twisted by spasms of pain.}

{12821}{}{You get hot, your bones ache, your ears ring, everything is in a fog ...}
{12822}{}{Sore wounds ooze blood and ichor and smell foul.}
{12823}{}{Your gums, eyelids and ears are bleeding and you have difficulty breathing.}

{12824}{}{You feel a bit better.}

{12830}{}{Regular}
{12831}{}{Scream}
{12832}{}{Emotion}
{12833}{}{Whisper}
{12834}{}{Description}
{12835}{}{Text}
{12836}{}{Done}
{12837}{}{Fill in the description.}
{12838}{}{Fill in the text.}
{12839}{}{The text type is not selected.}

{12900}{}{You feel weakness all over your body, everything is floating in your eyes.} # Paralytic poison
{12901}{}{You can hardly see and almost can't feel your body.}
{12902}{}{Your body doesn't listen to you. You are completely blind.}
{12903}{}{The effect of the poison is over.}
{12904}{}{vomits}
{12905}{}{staggering}
{12906}{}{face contorts grimace}
{12907}{}{rolls his eyes}
{12908}{}{It's getting a little easier for you.}
{12909}{}{You injected yourself with neurotoxin. Oh, you shouldn't have done that...}
{12910}{}{You've been stung by something!}

{12920}{}{|0xFFFF00 You lack medical knowledge.}
{12921}{}{|0xFFFF00 You have successfully applied the defibrillator.}
{12922}{}{|0xFFFF00 This won't help here.}
{12923}{}{|0xFFFF00 This is not necessary.}
{12924}{}{checks the patient's pulse@@charges the defibrillator}
{12925}{}{|0xFFFF00 You recharge the defibrillator.}
{12926}{}{|0xFFFF00 You require 3 regular type-c cells to charge the defibrillator.}
{12927}{}{recharges the defibrillator}

{12930}{}{You get a warning. Reason: @lex reason@. After the third warning, you will be blocked. Have a nice game.}
{12931}{}{NUMBER OF WARNINGS:}
{12932}{}{OK}
{12934}{}{You were blocked by @lex admin@ for repeatedly violating the server rules. The reason is @lex reason@. Goodbye, we will not miss you.}
{12935}{}{You are going to issue a warning to the player @lex PlayerName@ He already has @lex WarnCount@ warnings.
Confirm?}
{12936}{}{There is no such player.}
{12937}{}{Specify the reason for the warning:}

{12960}{}{You feel better now. But you feel strange... Something is definitely wrong.}
{12961}{}{Radiation is... it tickles!}
{12962}{}{When you feel a wave of radiation piercing your chest, you are glad that you are no longer a person.}
{12963}{}{Something is driving you to sleep... probably the radiation is off the scale again.}
{12964}{}{Hmm... Say, there is a crazy level of radiation here... You can have a picnic.}

{12970}{}{You were violently sick, a shiver went through your body, but it seems that you have defeated the infection.}

{12971}{}{You are thrown into a fever, your bones ache, your muscules are filled with thick blood, your ears are ringing, everything is like a fog... It looks like you are changing.}
{12972}{}{A wave of convulsions passes through your body, the temperature rises. You have an irresistible desire to rip out someone's guts.}
{12973}{}{Your muscles get stronger, your skin gets rougher, but at the same time you feel disgusting.}
{12974}{}{You feel sick, your eyes roll up, everything around you becomes somehow unreal. You are changing.}
{12975}{}{You feel dizzy, you do not understand what is happening around you, you feel a strong pain inside, as if something is tearing out from there.}

{12980}{}{You feel stronger, smarter, faster... It seems that the virus has only changed you for the better.}
{12981}{}{The disease has overcome you.}

# Rope
{12985}{}{You don't have a lighter.}
{12986}{}{It looks like you don't have a knife.}
{12987}{}{Surprisingly, you tried to cut the rope with your fingers. It didn't work out.}
{12988}{}{You have freed yourself from the rope.}
{12989}{}{You failed to tie up the victim.}
{12990}{}{You have tied yourself up.}
{12991}{}{You have tied @lex victim@ up.}
{12992}{}{You have been tied up!}
{12993}{}{The character is already tied up.}

####################################################################################################################################
#
#		Scores
#
####################################################################################################################################

{13000}{}{Transgender}
{13001}{}{Evil for an hour (minimal karma)}
{13011}{}{Hero for an hour (maximum karma)}
{13021}{}{Event of an hour (maximum karma change in an hour)}

{13030}{}{The Leaders}
{13031}{}{Chit-chat Master - most chat messages}
{13041}{}{Best Trader - most trading}
{13051}{}{Embarrassment Award - most deaths}
{13061}{}{Charmer - the most charming}
{13071}{}{Berserker Award - most kills}
{13081}{}{True Man of the Wastes - the most well-travelled}
{13091}{}{Gold Stethoscope award: the Wasteland's best doctor}
{13101}{}{Cassidy Award - best marksman}
{13111}{}{Sulik Award - melee master}
{13121}{}{Jungle Gym Platinum Club - best fist-fighter}
{13131}{}{Loxley Award - best thief}
{13141}{}{Best Protector - the guard of wasteland}

{13150}{}{Professionals}
{13151}{}{Leader of Men (Most people transported)}
{13161}{}{Ice-Cold Killer (Most creatures killed)}
{13171}{}{Sniper (Most critical hits)}
{13181}{}{True Adventurer (Most quests completed)}
{13191}{}{Cat Burglar (Most successful break ins)}
{13201}{}{Bonecrusher (Highest sum of unarmed damage)}

{13210}{}{Chosen one}
{13211}{}{Chosen one (best of the best)}

{13400}{}{Bases}
{13401}{}{Current Sierra Army Depot controller}
{13411}{}{Current Mariposa controller}
{13421}{}{Current Cathedral controller}
{13431}{}{Best Sierra Army Depot controller}
{13441}{}{Best Mariposa controller}
{13451}{}{Best Cathedral controller}
{13461}{}{Sierra base belongs}
{13471}{}{Mariposa base belongs}
{13481}{}{Cathedral belongs}
{13491}{}{More preference is given to the organization}

####################################################################################################################################
#
#		Stats (with STAT.MSG + 2000)
#
####################################################################################################################################

# ST_STRENGTH
{100001}{}{Strength}
{100002}{}{Each  point increases Hit Points by 3, Melee damage by 2, maximum carry weight by 10kg and throw range by 3 hexes.}
# ST_PERCEPTION
{100011}{}{Perception}
{100012}{}{Each point increases the basifc field of view by 5 hexes, the hearing distance by 2 hexes, gives an additional 4% to the chance of hitting the target.}
# ST_ENDURANCE
{100021}{}{Endurance}
{100022}{}{Each point increases Hit Points by 5, Poison Resistance by 5, Radiation Resistance by 2, Treatment Level by 1, AP Regeneration by 0.23, the limit of negative HP before death by 5.}
# ST_CHARISMA
{100031}{}{Charisma}
{100032}{}{Each point increases the limit of negative HP before death by 10. It also affects the reaction of people and the dialogues of NPCs. With your low charisma they may not want to do business with you or even talk to you.}
# ST_INTELLECT
{100041}{}{Intelligence}
{100042}{}{Each point makes a multiplier of skill points for each character level 5 + Level * Intelligence. If the intelligence is below 4, the character will begin to twist the words.}n, Experience Bonus to gear, respawn time, chance to get materials from dismantling.}
# ST_AGILITY
{100051}{}{Agility}
{100052}{}{Each point increases the Armor Class by 5 and the regeneration of AP by 0.57.}
# ST_LUCK
{100061}{}{Luck}
{100062}{}{Each point increases the chance of critical damage by 3%, critical damage protection by 1%, 2% accident protection, 9.5% slip protection.}
# ST_MAX_LIFE
{100071}{}{Maximum Hit Points}
{100072}{}{Determines how much damage the character can take before dying (150 + Strength * 3 + Endurance * 5 ). Death occurs with negative HP( Charisma * 10 + Stamina * 5).}
# ST_ACTION_POINTS
{100081}{}{Maximum action points}
{100082}{}{Action points are spent on any activity other than walking. Regeneration occurs every 250ms according to the following formula: ( 1.5 * Endurance * 0.23 + Agility * 0.57 ). The regeneration of AP cannot be higher than 10.}
{100083}{}{Action Points}
# ST_ARMOR_CLASS
{100091}{}{Armor Class}
{100092}{}{Reduces the base chance of hitting the AC value, gives 1% protection against critical hits for each AC point.}
{100093}{}{Armor Class}
# ST_MELEE_DAMAGE
{100101}{}{Melee Damage}
{100102}{}{The amount of damage caused by your character in hand-to-hand combat. The value is added to the value of melee and cold weapon damage and 50% of the value to the throwing weapon without a radius of destruction.}
{100103}{}{Melee Damage}
# ST_CARRY_WEIGHT
{100111}{}{Carry Weight}
{100112}{}{The maximum weight  that your character can carry(in kg.)}
{100113}{}{Maximum Carry Weight}
# ST_SEQUENCE
{100121}{}{Sequence}
{100122}{}{Is not used.}
{100123}{}{Sequence}
# ST_HEALING_RATE
{100131}{}{Healing Rate}
{100132}{}{The number of regenerated AP. Passive regeneration occurs every 4 minutes standing and every 2 minutes lying down.}
{100133}{}{Healing Rate}
# ST_CRITICAL_CHANCE
{100141}{}{Critical Chance}
{100142}{}{The basic probability of causing critical damage to the enemy.}
{100143}{}{Critical Chance}
# ST_MAX_CRITICAL
{100151}{}{Better Critical}
{100152}{}{Better Critical}
# ST_NORMAL_ABSORB
{100161}{}{Damage Threshold}
{100162}{}{Damage Threshold}
# ST_LASER_ABSORB
{100171}{}{Damage Threshold Laser}
{100172}{}{Damage Threshold Laser}
# ST_FIRE_ABSORB
{100181}{}{Damage Threshold Fire}
{100182}{}{Damage Threshold Fire}
# ST_PLASMA_ABSORB
{100191}{}{Damage Threshold Plasma}
{100192}{}{Damage Threshold Plasma}
# ST_ELECTRO_ABSORB
{100201}{}{Damage Threshold Electro}
{100202}{}{Damage Threshold Electrical}
# ST_EMP_ABSORB
{100211}{}{Damage Threshold EMP}
{100212}{}{Damage Threshold EMP}
# ST_EXPLODE_ABSORB
{100221}{}{Damage Threshold Explosion}
{100222}{}{Damage Threshold Explosion}
# ST_NORMAL_RESIST
{100231}{}{Damage Resistance}
{100232}{}{Any damage taken is reduced by this amount. Damage Resistance can be increased by wearing armor.}
{100233}{}{Damage Res.}
# ST_LASER_RESIST
{100241}{}{Damage Resistance Laser}
{100242}{}{Damage Resistance Laser}
# ST_FIRE_RESIST
{100251}{}{Damage Resistance Fire}
{100252}{}{Damage Resistance Fire}
# ST_PLASMA_RESIST
{100261}{}{Damage Resistance Plasma}
{100262}{}{Damage Resistance Plasma}
# ST_ELECTRO_RESIST
{100271}{}{Damage Resistance Electrical}
{100272}{}{Damage Resistance Electrical}
# ST_EMP_RESIST
{100281}{}{Damage Resistance EMP}
{100282}{}{Damage Resistance EMP}
# ST_EXPLODE_RESIST
{100291}{}{Damage Resistance Explosion}
{100292}{}{Damage Resistance Explosion}
# ST_RADIATION_RESISTANCE
{100301}{}{Radiation Resistance}
{100302}{}{The amount of radiation you are exposed to is reduced by this percentage. Radiation Resistance can be modified by the type of armor worn, and anti-radiation chems.}
{100303}{}{Radiation Res.}
# ST_POISON_RESISTANCE
{100311}{}{Poison Resistance}
{100312}{}{Reduces chance to be poisoned and damage taken from poison.}
{100313}{}{Poison Res.}

# 100700
# ST_AGE
{100701}{}{Age}
{100702}{}{Age}
# ST_GENDER
{100711}{}{Gender}
{100712}{}{Gender}
# ST_CURRENT_HP
{100721}{}{Current Hit Points}
{100722}{}{Current Hit Points}
# ST_POISONING_LEVEL
{100731}{}{Current Poison Level}
{100732}{}{Current Poison Level}
{100733}{}{Cur. Pois. Lvl}
# ST_RADIATION_LEVEL
{100741}{}{Current Radiation Level}
{100742}{}{Current Radiation Level}
{100743}{}{Cur. Rad. Lvl}

# 100760
# ST_EXPERIENCE
{100761}{}{Experience}
{100762}{}{A reward for completing specific tasks, or defeating enemies in combat. More experience points are required to attain higher Levels.}
# ST_LEVEL
{100771}{}{Level}
{100772}{}{The general competency of the player character. A measure of your experience and abilities.}
# ST_UNSPENT_SKILL_POINTS
{100781}{}{Unspent Skill Points}
{100782}{}{Points earned by going up a Level. Can be used to increase a skill by 1% per point spent up to a certain level.}

# 100800
# ST_KARMA
{100801}{}{Карма}
{100802}{}{This parameter is responsible for your reputation. The higher it is, the better you will be treated by good characters and civilians. With a negative reputation, everyone will hate you.}

# 112, ST_BASE_CRTYPE
{101121}{}{Body Type}

# 150..165, 3d layers
{101501}{}{Skin}
{101511}{}{R. Handle}
{101521}{}{L. Handle}
{101531}{}{Body}
{101541}{}{Feet}
{101551}{}{Hands}
{101561}{}{Head}
{101571}{}{Hair}
{101581}{}{Eye}
{101591}{}{Mustache}
{101601}{}{Ponytail}
{101611}{}{Beard}
{101621}{}{Shoulder}
{101631}{}{Armlet}
{101641}{}{Back}
{101651}{}{Backpack}

# 195, ST_TRAUMATIN_OVERDOSE
{101951}{}{The dose of Traumatin}
{101952}{}{Overdose of traumatin-notes how many times you can use traumatin before the restriction on further use comes.}

####################################################################################################################################
#
#		Skills (with SKILL.MSG + 3000)
#
####################################################################################################################################

# 102000
# SK_SMALL_GUNS
{102001}{}{Small Guns}
{102002}{}{The use, care, and general knowledge of small firearms - pistols, SMGs and rifles.}
{102003}{}{Small Guns}
# SK_BIG_GUNS
{102011}{}{Big Guns}
{102012}{}{The operation and maintenance of really big guns - miniguns, rocket launchers, flamethrowers and such.}
{102013}{}{Big Guns}
# SK_ENERGY_WEAPONS
{102021}{}{Energy Weapons}
{102022}{}{The care and feeding of energy-based weapons.  How to arm and operate weapons that use laser or plasma technology.}
{102023}{}{Energy Weapons}
# SK_UNARMED
{102031}{}{Unarmed Сombat}
{102032}{}{A combination of martial arts, non-ranged weapons in hand-to-hand, or melee combat - knives, sledgehammers, spears, clubs and so on.}
{102033}{}{Unarmed}
# SK_MELEE_WEAPONS
{102041}{}{Melee Weapons}
{102042}{}{Use of diffenrent melee weapons. Knives, clubs, spears, sledgehammers, poles and all similar crap.}
{102043}{}{Melee}
# SK_THROWING
{102051}{}{Throwing}
{102052}{}{The skill of muscle-propelled ranged weapons, such as throwing knives, spears and grenades.}
{102053}{}{Throwing}
# SK_FIRST_AID
{102061}{}{First aid}
{102062}{}{General healing skill. Used to heal small cuts, abrasions and other minor ills. The use of first aid can heal some hit points immediately.}
{102063}{}{First Aid}
# SK_DOCTOR
{102071}{}{Doctor}
{102072}{}{The healing of major wounds and crippled limbs.  Without this skill, it will take a much longer period of time to restore crippled limbs to use.}
{102073}{}{Doctor}
# SK_SNEAK
{102081}{}{-}
{102082}{}{Disabled.}
{102083}{}{Sneak}
# SK_LOCKPICK
{102091}{}{Lockpicking}
{102092}{}{The skill of opening locks without the proper key, and the ability to make the things of others your own. The use of lock picks or electronic lock picks will greatly enhance this skill. Can be used to steal from people or places.}
{102093}{}{Lockpick}
# SK_STEAL
{102101}{}{Stealing}
{102102}{}{Often you find yourself in a position to borrow other people's things without the owner's knowledge. Not bad for a career as a thief.}
{102103}{}{Stealing}
# SK_TRAPS
{102111}{}{Traps}
{102112}{}{The finding and removal of traps. Also the setting of explosives for demolition purposes.}
{102113}{}{Traps}
# SK_SCIENCE
{102121}{}{Science}
{102122}{}{Covers a variety of high technology skills, such as computers, biology, physics, and geology.}
{102123}{}{Science}
# SK_REPAIR
{102131}{}{Repair}
{102132}{}{The practical application of the Science skill for fixing broken equipment, machinery and electronics.}
{102133}{}{Repair}
# SK_SPEECH
{102141}{}{-}
{102142}{}{Disabled.}
{102143}{}{Speech}
# SK_BARTER
{102151}{}{Barter}
{102152}{}{Trading and trade-related tasks. The ability to get better prices for items you sell, and lower prices for items you buy.}
{102153}{}{Barter}
# SK_GAMBLING
{102161}{}{-}
{102162}{}{Disabled}
{102163}{}{Gambling}
# SK_OUTDOORSMAN
{102171}{}{Outdoorsman}
{102172}{}{Practical knowledge of the outdoors, and the ability to live off the land. The knowledge of plants and animals.}
{102173}{}{Outdoorsman}
# SK_MINING
{102181}{}{Mining}
{102182}{}{Breaking stones with a pickaxe or a sledgehammer, extracting something valuable from them, what could be easier? Though, if you find a drill...											                 This skill is improved with usage.}
{102183}{}{Mining}
# SK_CHOPPING
{102191}{}{Chopping}
{102192}{}{It would seem that hitting a tree with an axe and everything is fine, but ideally you should make sure that you are not crushed by a heavy trunk. 			    			    						             This skill is improved with usage.}
{102193}{}{Chopping}
# SK_SCAVENGING
{102201}{}{Scavenging}
{102202}{}{And let the rich citizens look down on you, but you got this rusty walkie-talkie for free!  						            					                          This skill is improved with usage.}
{102203}{}{Scavenging}
# SK_HUNTING
{102211}{}{Hunting}
{102212}{}{Aim, hold your breath, pull the trigger. Well, you've ruined the skin of a rare gecko again, you idiot! No one will give more than $ 10 for it now! 		            														             This skill is improved with usage.}
{102213}{}{Hunting}
# SK_FISHING
{102221}{}{Fishing}
{102222}{}{Silence, calm, nasty mosquitoes.. and the chance to feed the family almost without risking their own health.  														This skill is improved with usage.}
{102223}{}{Fishing}
# SK_FARMING
{102231}{}{Farming}
{102232}{}{If growing cabbage for months causes a sense of calm in you, and the smell of brahmin shit does not make your eyes water-then this is clearly your vocation! 							    					    This skill is improved with usage.}
{102233}{}{Farming}
# SK_COOKING
{102241}{}{Cooking}
{102242}{}{Boil the vegetables? Fry the meat? Bake fish? I don't care, the main thing is to kill all pathogens, and if it's also delicious, then you are the king in this kitchen. 					    							    This skill is improved with usage.}
{102243}{}{Cooking}
# SK_SEX
{102251}{}{Sex}
{102252}{}{How much can you earn by hard work in the mine? Learn to give pleasure and live at someone else's expense! The skill is practiced through application.  														    This skill is improved with usage.}
{102253}{}{Sex}

# 102300
# TO_SK_FIRST_AID, timeouts
{102301}{}{First aid}
# TO_SK_DOCTOR, timeouts
{102311}{}{Doctor}
# TO_SK_REPAIR, timeouts
{102321}{}{Repair}
# TO_SK_SCIENCE, timeouts
{102331}{}{Science}
# TO_SK_LOCKPICK, timeouts
{102341}{}{Robbery}
# TO_SK_STEAL, timeouts
{102351}{}{Stealing}

# 102380
# TO_BATTLE, timeouts
{102381}{}{Battle}
# TO_TRANSFER, timeouts
# {102391}{}{Transitions}
# TO_REMOVE_FROM_GAME, timeouts
# {102401}{}{Exit game}
# TO_REPLICATION, timeouts
{102411}{}{Replication}
# TO_TIREDNESS, timeouts
{102421}{}{Tiredness}
# TO_SNEAK, timeouts
{102431}{}{Stealth}

####################################################################################################################################
#
#		Kills (from PROTO.MSG)
#
####################################################################################################################################

#
# Kill Types names
#

# 102600
# BT_MEN..BT_BIG_BAD_BOSS, bodytypes
{102601}{}{Men}
{102602}{}{This line shows the number of male humans you have killed during the course of your adventures.}
{102611}{}{Women}
{102612}{}{This line shows the number of female humans you have killed during the course of your adventures.}
{102621}{}{Children}
{102622}{}{This line shows the number of young human children you have killed during the course of your adventures.  You cad.}
{102631}{}{Super Mutants}
{102632}{}{The number of Super Mutants you have slain during the course of your adventures.}
{102641}{}{Ghouls}
{102642}{}{This line shows the number of male and female ghoul mutants you have killed during the course of your adventures.}
{102651}{}{Brahmin}
{102652}{}{This line shows the number of Brahmin (mutated cows) you have chopped up during your travels.}
{102661}{}{Radscorpions}
{102662}{}{The number of mutated Radscorpions that you have put to death during your adventure.}
{102671}{}{Rats}
{102672}{}{The number of rats you have killed.  Includes all members of the rat family.}
{102681}{}{Floaters}
{102682}{}{This is the number of mutant Floaters that you have put to death.}
{102691}{}{Centaurs}
{102692}{}{Your tally of dead mutant Centaurs.}
{102701}{}{Robots}
{102702}{}{This is the number of robots that you have destroyed or dismantled.}
{102711}{}{Dogs}
{102712}{}{The total number of dogs that you have sent to the great kennel in the sky.}
{102721}{}{Manti}
{102722}{}{This line shows the total number of dead Manti, or large mutated mantis-like insects, that you have squashed so far.}
{102731}{}{Deathclaws}
{102732}{}{This line shows that you have slain the Deathclaw, and any of his spawn.}
{102741}{}{Plants}
{102742}{}{This line shows the number of plants you have weeded out of the world.}
{102751}{}{Geckos}
{102752}{}{The number of cute lizards you have wiped off the face of the planet.}
{102761}{}{Aliens}
{102762}{}{A count of alien things slain by your hand.}
{102771}{}{Giant Ants}
{102772}{}{The number of insectoids that you have exterminated in the wasteland.}
{102781}{}{Big Bad Boss}
{102782}{}{The count of genetically-engineered total homicidal maniac cyborg bodyguards you have wasted.}
{102791}{}{Giant beetles}
{102792}{}{The number of mutated beetles that you destroyed in the Wasteland.}
{102801}{}{Giant wasps}
{102802}{}{The number of mutated giant wasps that died by your hand.}
{102811}{}{Yao-Gai}
{102812}{}{Here is the number of bear-like Yao-Gai killed by you during your travels and adventures.}
{102821}{}{Mirelurks}
{102822}{}{Here is the number of mirelurks you killed.}
{102831}{}{Crocs}
{102832}{}{Here is the number of Creepy-Grabs and Shadow-Grabs you have killed.}

####################################################################################################################################
#
#		Perks (with PERK.MSG)
#
####################################################################################################################################

# 103000
# PE_GAIN_STRENGTH
{103001}{}{Gain Strength}
{103002}{}{This perk increases your Strength by one point.}
# PE_GAIN_PERCEPTION
{103011}{}{Gain Perception}
{103012}{}{This perk increases your Perception by one point.}
# PE_GAIN_ENDURANCE
{103021}{}{Gain Endurance}
{103022}{}{This perk increases your Endurance by one point.}
# PE_GAIN_CHARISMA
{103031}{}{Gain Charisma}
{103032}{}{This perk increases your Charisma by one point.}
# PE_GAIN_INTELLIGENCE
{103041}{}{Gain Intelligence}
{103042}{}{This perk increases your Intelligence by one point.}
# PE_GAIN_AGILITY
{103051}{}{Gain Agility}
{103052}{}{This perk increases your Agility by one point.}
# PE_GAIN_LUCK
{103061}{}{Gain Luck}
{103062}{}{This perk increases your Luck by one point.}
# PE_LOOSE_STRENGTH
{103071}{}{Lose Strength}
{103072}{}{Your Strength has been reduced by one for each level of this perk!}
# PE_LOOSE_PERCEPTION
{103081}{}{Lose Perception}
{103082}{}{Your Perception has been reduced by one for each level of this perk!}
# PE_LOOSE_ENDURANCE
{103091}{}{Lose Endurance}
{103092}{}{Your Endurance has been reduced by one for each level of this perk!}
# PE_LOOSE_CHARISMA
{103101}{}{Lose Charisma}
{103102}{}{Your Charisma has been reduced by one for each level of this perk!}
# PE_LOOSE_INTELLIGENCE
{103111}{}{Lose Intelligence}
{103112}{}{Your Intelligence has been reduced by one for each level of this perk!}
# PE_LOOSE_AGILITY
{103121}{}{Lose Agility}
{103122}{}{Your Agility has been reduced by one for each level of this perk!}
# PE_LOOSE_LUCK
{103131}{}{Lose Luck}
{103132}{}{Your Luck has been reduced by one for each level of this perk!}
# PE_SEXUAL_IMPROVEMENT
{103141}{}{Intimate plastic surgery}
{103142}{}{You have become sexier after the surgery (+50 points in the sex skill).}
# PE_SILENT_RUNNING
{103161}{}{Silent running}
{103162}{}{Now you will move quickly, while creating no more noise than if you were sneaking on tiptoe. Previously, this was completely impossible due to technical reasons.}
# PE_MASTER_TRADER
{103181}{}{Master trader}
{103182}{}{You have achieved real mastery in one of the aspects of trading, namely the ability to buy goods at low prices, haggling to exhaustion. You get a 25 percent discount on any purchase.}
# PE_QUICK_POCKETS
{103491}{}{Optimization}
{103492}{}{You managed to put your things in your pockets so that they were always at hand. Now manipulations with items in the inventory cost half as much.}
# PE_SMOOTH_TALKER
{103501}{}{Smooth talker}
{103502}{}{The talker manages to insert two words where others barely manage one, even if he does not understand what he is talking about. Each level of your Intelligence during the dialogue will increase by 1, up to 10.}

# 104700
# ADDICTION_NUKA_COLA, addictions
{104701}{}{Nuka Cola addiction}
{104702}{}{You want a little more Nuka Cola.}
# ADDICTION_BUFFOUT, addictions
{104711}{}{Buffout addiction}
{104712}{}{You started having seizures.}
# ADDICTION_MENTATS, addictions
{104721}{}{Mentat addiction}
{104722}{}{Your head is spinning.}
# ADDICTION_PSYCHO, addictions
{104731}{}{Psycho addiction}
{104732}{}{You don't feel the space.}
# ADDICTION_RADAWAY, addictions
{104741}{}{RadAway addiction}
{104742}{}{You are suffering from vomiting attacks.}
# ADDICTION_JET, addictions
{104751}{}{Jet addiction}
{104752}{}{Everything around you is moving so slowly... you urgently need to sniff some more Jet!}
# ADDICTION_TRAGIC, addictions
{104761}{}{Tragic Hobby}
{104762}{}{You are eager to unpack another box of Tragic cards.}
# ADDICTION_TREB, addictions
{104771}{}{Treb addiction}
{104772}{}{Everything around you is moving so slowly... you urgently need to sniff a little more Treb!}
# ADDICTION_VINT, addictions
{104781}{}{Jet addiction}
{104782}{}{Everything around you is moving so slowly... you urgently need to sniff some more Jet!}

# 104800
# KARMA_BERSERKER
{104801}{}{Cannibal}
{104802}{}{You have tasted human flesh... And you liked it.}
# KARMA_CHAMPION
{104811}{}{Poseidonite}
{104812}{}{Your actions have made you famous enough that you could ride to the tanker and back without a ticket.}
# KARMA_CHILDKILLER
{104821}{}{Child killer}
{104822}{}{You are killing small, innocent children, the hope and the future of the Wasteland. No one likes the evil you do. This is very bad.}
# KARMA_SEXPERT
{104831}{}{Sexpert}
{104832}{}{You understand sex. You know how to show your best side in bed, and this is the only place where you behave flawlessly.}
# KARMA_PRIZEFIGHTER
{104841}{}{Boxing Champion}
{104842}{}{Fights in the ring have earned you the ability to fight and the title of the first glove of Northern California. Everything needs skill, hardening, training, otherwise you will not see good luck!}
# KARMA_GIGOLO
{104851}{}{Pimp}
{104852}{}{Let's face it: You use corrupt women to make money.}
# KARMA_GRAVE_DIGGER
{104861}{}{The Grave Digger}
{104862}{}{Your slogan is the popular saying "The dead don't bite". The passion for digging up other people's graves and stealing the property of the deceased is your hobby.}
# KARMA_MARRIED
{104871}{}{Marriage}
{104872}{}{We congratulate you on a successful marriage. Now you have a life partner.}
# KARMA_PORN_STAR
{104881}{}{Porn star}
{104882}{}{The day came when a new star rose in the murky sky of New Reno. Your sexual virtues are known all over the city.}
# KARMA_SLAVER
{104891}{}{The slaver}
{104892}{}{Joining the Slavers Guild has changed your life forever. A tattoo on your forehead speaks about your profession better than any words.}
# KARMA_VIRGIN_WASTES
{104901}{}{Chastity}
{104902}{}{Walking knee-deep in mud, you managed not to get dirty and keep your purity in the cruel world of the desert.}
# KARMA_MAN_SALVATORE
{104911}{}{The Bandit of Moloch}
{104912}{}{Moloch has taken you under his protection. Everyone knows this.}
# KARMA_MAN_BISHOP
{104921}{}{Yakuza}
{104922}{}{You are a yakuza. Everyone knows this.}
# KARMA_MAN_MORDINO
{104931}{}{Shi}
{104932}{}{You are one of the Shi. Everyone knows this.}
# KARMA_MAN_WRIGHT
{104941}{}{Bandit}
{104942}{}{You are an ordinary little bandit. You are known in the region, but do not belong to any of the known groups.}
# KARMA_SEPARATED
{104951}{}{El Dorado}
{104952}{}{You are among those who are privy to the details of safe approaches to the fortified area of a certain pre-war object.}
# KARMA_PEDOBEAR
{104961}{}{Pedobir}
{104962}{}{You fucked an innocent child. How could you. Asshole. You've earned yourself trouble for the rest of your life.}
# KARMA_VC_GUARDSMAN
{104971}{}{SSF}
{104972}{}{You are a proud representative of the Ship's Security Forces. This status is known to everyone.}

# 105000
# DAMAGE_POISONED, damages
{105001}{}{Poisoned}
{105002}{}{Your character has been poisoned. Poison will do damage over a period of time, until cured or it passes from your system.}
# DAMAGE_RADIATED, damages
{105011}{}{Radiated}
{105012}{}{Your character is suffering from a significant amount of Radiation poisoning. The more radiation damage, the more deadly the effect.}
# DAMAGE_EYE, damages
{105021}{}{Eye Damage}
{105022}{}{This means your character has been seriously hit in one or both of your eyes. This affects your Perception.}
# DAMAGE_RIGHT_ARM, damages
{105031}{}{Crippled Right Arm}
{105032}{}{Your character's right arm has been severely hurt, and cannot function well. If one arm is crippled, you cannot use two-handed weapons.  If both arms are crippled, you cannot attack with weapons at all.}
# DAMAGE_LEFT_ARM, damages
{105041}{}{Crippled Left Arm}
{105042}{}{Your character's left arm has been severely hurt, and cannot function well. If one arm is crippled, you cannot use two-handed weapons.  If both arms are crippled, you cannot attack with weapons at all.}
# DAMAGE_RIGHT_LEG, damages
{105051}{}{Crippled Right Leg}
{105052}{}{Your character has a crippled right leg.}
# DAMAGE_LEFT_LEG, damages
{105061}{}{Crippled Left Leg}
{105062}{}{Your character has a crippled left leg.}


####################################################################################################################################
#
#		Traits (with TRAIT.MSG)
#
####################################################################################################################################

# TRAIT_FAST_METABOLISM
{105501}{}{Fast Metabolism}
{105502}{}{Increases the level of healing. Reduces the healing tick time (increases the speed of passive treatment). Removes resistance to radiation. Removes resistance to poisons. Increases the speed of thirst and hunger by 2 times.Increases the overdose charge by 30%, but accelerates the decline of overdose by 30%.}
# TRAIT_BRUISER
{105511}{}{Bruiser}
{105512}{}{Gives 3 additional points in the "Strength" parameter. Reduces action points by 25.}
# TRAIT_SMALL_FRAME
{105521}{}{Small Frame}
{105522}{}{With this trait, each point of Agility now gives + 5 kg carry weight, but each point of strength now gives + 6 kg of the maximum weight carried instead of + 10 kg.}
# TRAIT_ONE_HANDER
{105531}{}{One Hander}
{105532}{}{The basic chance to hit with Pistols and SMG is 20. All other long-range weapons have a base penalty of 40.}
# TRAIT_FINESSE
{105541}{}{Finesse}
{105542}{}{Increases the base chance of critical damage by 15%. All targets receive +30% resistance to your damage.}
# TRAIT_KAMIKAZE
{105551}{}{Kamikaze}
{105552}{}{Reduces the base DR to 0. Increases the regeneration of AP by 0.2 per Agility point.}
# TRAIT_HEAVY_HANDED
{105561}{}{Heavy handed}
{105562}{}{Increases Melee damage by 1 for each point of the Strength parameter. Reduces AP regeneration by 0.35 for each Strength point.}
# TRAIT_FAST_SHOT
{105571}{}{Fast Shot}
{105572}{}{All attacks spend 15% less AP. Targeted fire cannot be conducted, while 66% of attacks will be in a random place.}
# TRAIT_BLOODY_MESS
{105581}{}{Bloody Mess}
{105582}{}{Your attacks and finishing blows lead to critical death animations. Your death will also be critical. Everyone around sees your strange behavior. There is no penalty when shooting at good-natured people.}
# TRAIT_JINXED
{105591}{}{Jinxed}
{105592}{}{For you and your enemies, 10% of the misses become critical misses.}
# TRAIT_GOOD_NATURED
{105601}{}{Good Natured}
{105602}{}{Gives 25 skill points to Doctor, First Aid, and Trade. Removes 20 skill points from Weapon Skills. The base chance of hitting you is reduced by 30 if the enemy has no Bloody Mess.}
# TRAIT_CHEM_RELIANT
{105611}{}{Chem Reliant}
{105612}{}{The side effect of drugs (stage 2) lasts half as LONG, but the chance of getting addicted to any drugs is twice as MUCH. Increases drug treatment and overdose from them by 30%. You can not take it with a cheam resistant trait.}
# TRAIT_CHEM_RESISTANT
{105621}{}{Chem Resistant}
{105622}{}{The effect of drugs lasts half as LONG as the withdrawal from them. Reduces drug treatment and overdose from them by 30%. You can not take it with chem reliant trait.}
# TRAIT_SEX_APPEAL
{105631}{}{Sensitivity}
{105632}{}{You get 50% more experience, but 50% more damage.}
# TRAIT_SKILLED
{105641}{}{Skilled}
{105642}{}{Gives a bonus to the starting skills, but all experience gains are reduced by %50.}
# TRAIT_NIGHT_PERSON
{105651}{}{Night person}
{105652}{}{This trait gives 1 point to Intelligence and Perception at night (from 18: 01 to 06: 00), but decreases by one during the day (from 06:01 to 18: 00). THE CALCULATION IS BASED ON GAME TIME.}

# Armor race restrictions
{105663}{}{This armor is designed for mutants - you can't wear it.}
{105664}{}{This armor is designed for humans - you can't wear it.}

# Reputation groups
#105700
# REPUTATION_DEN
{105701}{}{Den}
# REPUTATION_KLAMATH
{105711}{}{Klamath}
# REPUTATION_MODOC
{105721}{}{Modoc}
# REPUTATION_VAULT_CITY
{105731}{}{Vault City}
# REPUTATION_GECKO
{105741}{}{Gecko}
# REPUTATION_BROKEN_HILLS
{105751}{}{Broken Hills}
# REPUTATION_NEW_RENO
{105761}{}{New Rebo}
# REPUTATION_SIERRA
{105771}{}{Sierra}
# REPUTATION_VAULT15
{105781}{}{Vault 15}
# REPUTATION_NCR
{105791}{}{NCR}
# REPUTATION_CATHEDRAL
{105801}{}{Cathedral}
# REPUTATION_MARIPOSA
{105811}{}{Mariposa}
# REPUTATION_REDDING
{105821}{}{Redding}
# REPUTATION_SF
{105831}{}{San-Francisco}
# REPUTATION_NAVARRO
{105841}{}{Navarro}
# REPUTATION_ARROYO
{105851}{}{Arroyo}
# REPUTATION_PRIMAL_TRIBE
{105861}{}{Primal Tribe}
# REPUTATION_RANGERS
{105871}{}{Rangers}
# REPUTATION_VAULT13
{105881}{}{Vault 13}
# REPUTATION_SACRAMENTO
{105891}{}{Sacramento}

####################################################################################################################################
#
#		Динамические лексемы объектов:
#
####################################################################################################################################

{110000}{}{STATE NAME VALUE.}
{110001}{}{DESC.}
#STATE
{120000}{}{Regular}
{120001}{}{Fresh}
#VALUE
{130000}{}{junk}
{130001}{}{meat}
#DESC
{140000}{}{You see nothing interesting}
{140001}{}{It makes you sick}

####################################################################################################################################
#
#		Repair
#
####################################################################################################################################

{155080}{}{There are no suitable skins to patch the holes.}
{155090}{}{There are no suitable pieces of leather to repair the armor.}
{155100}{}{There are no suitable metal sheets to repair the armor.}
{155110}{}{A sledgehammer is needed to work with metal sheets.}
{155120}{}{A drill is needed to work with hardened sheets.}
{155130}{}{There are no suitable hardened metal sheets to repair the armor.}
{155140}{}{Chitin plates and shells are needed to repair the armor.}
{155150}{}{A drill is needed to work with the shells of boggies.}
{155160}{}{You need a drill to work with materials.}
{155170}{}{Chemicals are needed to repair the armor.}
{155180}{}{It seems to you that there are clearly not enough parts to repair this armor. I would still like to know which ones...}
{155190}{}{You need all the junk to fix this weapon.}
{155200}{}{You need spare parts to repair this weapon.}
{155210}{}{You need spare parts, most likely-parts of electronics that were used in the past.}
{155220}{}{You need mechanical parts to repair this weapon.}
{155230}{}{You need high-quality factory spare parts. These are getting rare!}

####################################################################################################################################
#
#		Misc2 values names (100000 + pid*10 + number of val)
#
####################################################################################################################################

{1001000}{}{Charge}
{1001001}{}{}
{1001002}{}{}

####################################################################################################################################
#
#		Update Info (1500000)
#
####################################################################################################################################

{1500000}{}{Have a nice game!}

####################################################################################################################################
#
#		Intellect words
#
####################################################################################################################################

{1999000000}{}{}







































































































































































































































































































































































































































































































































{1999000001}{}{}

####################################################################################################################################
#
#		Help
#
####################################################################################################################################

# F7 - Enable / disable the highlighting of NPC names.
# F9 - Enable / disable tracing the trajectory of the shot.

{2000000000}{}{
Game hotkeys:

F1 - Enable / disable help.
F2 - Save messages to a file.
F3 - Save the screenshot.
F4 - On / Off display of the text input panel.
F5 - On / Off extension of the message window.
F6 - Turn on / off the highlighting of the players ' names.
F8 - Turn on/off the scrolling of the map with the mouse (helps in windowed mode).
F12 - Collapsing the client.
Pointers - scrolling the map.
Esc - menu.
Pause/Break-puntswitcher on the command line.
< , > - Rotate counterclockwise or clockwise.
Home-centering on the character (on the map and on the global).
A - Attack.
G - Pick up an item under your feet.
C is a Character.
I - Inventory.
P - Pipboy.
F - Fixboy.
B - Switching of active slots.
M - Switching the mouse menu.
N - Switching the item mode.
S - Skill panel.
Z - Zoom of the map.
1-8 - Skill selection.
? - Current game time.
+ ,- - Brightness control.
Ctrl + +, - - Adjust the volume of sounds.
Shift + +, - - Adjust the music volume.
Alt + +, - - Sleep control.

Commands for communication: the
first character . or / then:
s S - to shout,
w W-to whisper,
e E-emotion,
r R-radio.
After that, you can avoid using space key, but if you do, it will be ignored.
Enter the message and press Enter.

It is also possible to send messages using:
Ctrl + Enter - shout,
Alt + Enter - whisper,
Shift + Enter - radio.
}

####################################################################################################################################
#
#		Credits
#
####################################################################################################################################

# # == "|0xff8c8c84 "
# @ == "|0xff706050 "
# normal == "|0xff907824 "

{2000001000}{}{35} # Speed
{2000001010}{}{
[1997] - Fallout 1.

[1998] - Fallout 2.

[2000-2010] - Fallout modding community.

[<2013] - TLA FODEV Community.

[<2016] - TNF Roleplay Community.

[02.2019] - FoRP Comminuty.

[06.2021] - FoRP EN Community.

It was a long way.

Thank you for being there!

}
# Shift + Credits
{2000001020}{}{
Hello world!
}