
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{World Map}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

##### PERFECTION ####

# Area 1, Map 10
{110}{}{sandbox1_1}
{115}{}{34Cataclysm.ogg}
{116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{118}{}{Swamp}

# Area 2, Map 12
{130}{}{sandbox1_2}
{135}{}{under_1.ogg}
{136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{138}{}{West Cliff}

# Area 3, Map 13
{140}{}{tanker_deck4}
{145}{}{29mark-morgan-curst.ogg}
{146}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{148}{}{Caves}

# Area 3, Map 14
{150}{}{sandbox1_3}
{155}{}{03 - A Way To Anywhere.ogg}
{156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{158}{}{Hight}

# Area 3, Map 15
{160}{}{sandbox1_3dn}
{165}{}{58Tales_of_the_Past.ogg}
{166}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{168}{}{Train Tunnel}

# Area 4, Map 16
{170}{}{sandbox1_4}
{175}{}{14 - Organic Shadows.ogg}
{176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{178}{}{East Cliff}

# Area 5, Map 18
{190}{}{sandbox1_5}
{195}{}{36E3_Among_the_Friends.ogg}
{196}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{198}{}{Farm}

# Area 6, Map 20
{210}{}{sandbox2_1}
{215}{}{55NNM_wind_of_war.ogg}
{216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{218}{}{Swamp forest}

# Area 7, Map 22
{230}{}{sandbox2_2}
{235}{}{50NNM_radioluminescence.ogg}
{236}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{238}{}{South-west cliff}

# Area 7, Map 23
{240}{}{sandbox2_2dn}
{245}{}{58Tales_of_the_Past.ogg}
{246}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{248}{}{Charging station}

# Area 8, Map 24
{250}{}{sandbox2_3}
{255}{}{28Rangers-journey.ogg}
{256}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{258}{}{Checkpoint}

# Area 8, Map 25
{260}{}{sandbox2_3dn}
{265}{}{under_1.ogg}
{265}{}{41NNM_bonus.ogg}
{265}{}{42NNM_ghost_town.ogg}
{265}{}{43NNM_high_wind.ogg}
{265}{}{44NNM_improper_subdivision.ogg}
{265}{}{45NNM_jammer.ogg}
{265}{}{46NNM_line_of_policy.ogg}
{265}{}{47NNM_nevada_theme.ogg}
{265}{}{48NNM_new_vegas.ogg}
{265}{}{49NNM_radiationless.ogg}
{265}{}{50NNM_radioluminescence.ogg}
{265}{}{51NNM_ride_to_cheyenne.ogg}
{265}{}{52NNM_root_information.ogg}
{265}{}{53NNM_village.ogg}
{265}{}{54NNM_we_are_sorry.ogg}
{265}{}{55NNM_wind_of_war.ogg}
{266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{268}{}{Perfection}

# Area 9, Map 30
{310}{}{sandbox2_4}
{315}{}{38Into_The_ACID_Breach.ogg}
{316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{318}{}{South-east cliff}

# Area 10, Map 32
{330}{}{sandbox2_5}
{335}{}{37E1_Into_the_Tower.ogg}
{336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{338}{}{Hills}

# Area 11, Map 34
{350}{}{sandbox3_1}
{355}{}{44NNM_improper_subdivision.ogg}
{356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{358}{}{East forest}

# Area 12, Map 36
{370}{}{sandbox3_2}
{375}{}{49NNM_radiationless.ogg}
{376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{378}{}{The turn}

# Area 13, Map 38
{390}{}{sandbox3_3}
{395}{}{26A_Candle_in_the_Darkness.ogg}
{396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{398}{}{Substation}

# Area 13, Map 39
{400}{}{sandbox3_3dn}
{405}{}{45NNM_jammer.ogg}
{406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{408}{}{Service rooms}

# Area 14, Map 40
{410}{}{sandbox3_4}
{415}{}{27Lost_Knowledge.ogg}
{416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{418}{}{Shops}

# Area 13, Map 41
{420}{}{sandbox3_4dn}
{425}{}{42NNM_ghost_town.ogg}
{426}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{428}{}{Old lab}

# Area 15, Map 42
{430}{}{sandbox3_5}
{435}{}{31old_earth.ogg}
{436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{438}{}{Outskirts}

# Area 15, Map 43
{440}{}{sandbox3_5dn}
{445}{}{27Lost_Knowledge.ogg}
{446}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{448}{}{Robotic Control}

# Area 16, Map 44
{450}{}{sandbox4_1}
{455}{}{54NNM_we_are_sorry.ogg}
{456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{458}{}{South-west forest}

# Area 16, Map 45
{460}{}{sandbox4_1dn}
{465}{}{05raider.mp3}
{466}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{468}{}{South-west forest}

# Area 17, Map 46
{470}{}{sandbox4_2}
{475}{}{41NNM_bonus.ogg}
{476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{478}{}{Intersection}

# Area 18, Map 48
{490}{}{sandbox4_3}
{495}{}{53NNM_village.ogg}
{496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{498}{}{Hill}

# Area 18, Map 49
{500}{}{sandbox4_3dn}
{505}{}{58the25vault.ogg}
{506}{}{pebble:5, pebble1:10}
{508}{}{Old mines}

# Area 19, Map 50
{510}{}{sandbox4_4}
{515}{}{45NNM_jammer.ogg}
{516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{518}{}{Ruins}

# Area 19, Map 51
{520}{}{sandbox4_4dn}
{525}{}{{26A_Candle_in_the_Darkness.ogg}
{526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{528}{}{Fort's basement}

# Area 20, Map 52
{530}{}{sandbox4_5}
{535}{}{47NNM_nevada_theme.ogg}
{536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{538}{}{Broadway}

# Area 21, Map 54
{550}{}{sandbox5_1}
{555}{}{57SHK_sinless_From_Seattle.ogg}
{556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{558}{}{South forest}

# Area 22, Map 56
{570}{}{sandbox5_2}
{575}{}{52NNM_root_information.ogg}
{576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{578}{}{Motel}

# Area 23, Map 58
{590}{}{sandbox5_3}
{595}{}{42NNM_ghost_town.ogg}
{596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{598}{}{Drain}

# Area 24, Map 60
{610}{}{sandbox5_4}
{615}{}{51NNM_ride_to_cheyenne.ogg}
{616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{618}{}{Camping sight}

# Area 25, Map 62
{630}{}{sandbox5_5}
{635}{}{43NNM_high_wind.ogg}
{636}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{638}{}{Camp Montana}

# Area 26, Map 64
{650}{}{perfection_ext}
{655}{}{UnderRail Expedition Main Theme.ogg}
{656}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{658}{}{Tunnels}

# Area 26, Map 68
{690}{}{perfection_ext4}
{695}{}{UnderRail Expedition Main Theme.ogg}
{696}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{698}{}{Chem. plant}

# Area 27, Map 69
{700}{}{sandbox_bos}
{705}{}{07desert.ogg}
{706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{708}{}{Boneyard}

# Area 27, Map 70
{710}{}{sandbox_bos_dn1}
{715}{}{29mark-morgan-curst.ogg}
{716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{718}{}{Basement}

# Area 27, Map 71
{720}{}{sandbox_bos_dn2}
{725}{}{04Metallic Monks.ogg}
{726}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{728}{}{"Helheim" compound}

# Area 27, Map 72
{730}{}{sandbox_bos_dn3}
{735}{}{mscTimestream.ogg}
{736}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{738}{}{"Helheim" compound Tech level}

# Area 28, Map 73
{740}{}{sandbox0_2}
{745}{}{UnderRail Expedition Main Theme.ogg}
{746}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{748}{}{Camp in the gorge}

# Area 28, Map 74
{750}{}{sandbox0_2dn}
{755}{}{UnderRail Expedition Main Theme.ogg}
{756}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{758}{}{Camp in the gorge}

# Area 29, Map 77 
{780}{}{sandbox0_5}
{785}{}{Lacrimosa.mp3}
{786}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{788}{}{Sacred Hill}

# Area 29, Map 78
{790}{}{sandbox0_5dn}
{795}{}{UnderRail Expedition Main Theme.ogg}
{796}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{798}{}{Hill cave}

# Area 29, Map 79
{800}{}{sandbox0_5dn2}
{805}{}{04 - 12H. Dusk.ogg}
{806}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{808}{}{Hill Bunker}

# Area 29, Map 80
{810}{}{sandbox0_5dn3}
{815}{}{04 - 12H. Dusk.ogg}
{816}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{818}{}{Caves}

# Area 30, Map 81
{820}{}{sandbox1_6}
{825}{}{31old_earth.ogg}
{826}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{828}{}{Holy Grove}

# Area 30, Map 82
{830}{}{sandbox1_6dn}
{835}{}{05 - Anesthetic.ogg}
{836}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{838}{}{Holy Grove Basement}

# Area 31, Map 83
{840}{}{sandbox0_6}
{845}{}{13 - Killadrone.ogg}
{846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{848}{}{Toxic Dump}

# Area 32, Map 84
{850}{}{sandbox1_7}
{855}{}{58Tales_of_the_Past.ogg}
{856}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{858}{}{Holy Grove East}

# Area 33, Map 85
{860}{}{sandbox0_7}
{865}{}{38Into_The_ACID_Breach.ogg}
{866}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{868}{}{Abandoned Cafe}

##### TECH_MAPS #####

# Area 92, Map 92
{930}{}{startloc}
{935}{}{}
{936}{}{}
{938}{}{Activation}

# Area 93, Map 93
{940}{}{dreamloc}
{945}{}{}
{946}{}{}
{948}{}{Dream}

##### EVENTS #####

# Area 50, Map 100
{1010}{}{event4_hill2}
{1015}{}{F1_Drums_of_Battle.ogg}
{1016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1018}{}{Old ruins}

# Area 51, Map 101
{1020}{}{event2_slavers_out}
{1025}{}{F3_The_Rain_of_Steel.ogg}
{1026}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1028}{}{Rock}

# Area 51, Map 102
{1030}{}{event2_slavers_in}
{1035}{}{F7_Against_the_Odds.ogg}
{1036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1038}{}{Rangers' camp}

##### RIVERDALE #####

# Area 52, Map 103
{1040}{}{fort_riverdale}
{1045}{}{Out_of_Business.ogg}
{1045}{}{The_Courier_Walks_Softly.ogg}
{1045}{}{Under_the_Stars_Cut.ogg}
{1046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1048}{}{Fort Riverdale}

# Area 52, Map 104
{1050}{}{fort_riverdale_dn}
{1055}{}{Deeper_and_Darker.ogg}
{1056}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1058}{}{Fort Riverdale - underground}

# Area 52, Map 105
{1060}{}{fort_riverdale_up1}
{1065}{}{51NNM_ride_to_cheyenne.ogg}
{1066}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1068}{}{Fort Riverdale2}

# Area 52, Map 106
{1070}{}{fort_riverdale_up2}
{1075}{}{08 - Blue Grass.ogg}
{1076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1078}{}{Fort Riverdale3}

# Area 53, Map 107
{1080}{}{riverdale1_2}
{1085}{}{NNM_FS_16_One_Way.ogg}
{1086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1088}{}{Road}

# Area 54, Map 109
{1100}{}{riverdale1_3}
{1105}{}{44NNM_improper_subdivision.ogg}
{1106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1108}{}{Coast}

# Area 55, Map 111
{1120}{}{riverdale2_2}
{1125}{}{NNM_FS_03_ Fogbound.ogg}
{1126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1128}{}{Bridge}

# Area 56, Map 113
{1140}{}{riverdale2_3}
{1145}{}{24redd.mp3}
{1146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1148}{}{Cliff}

# Area 57, Map 115
{1160}{}{riverdale3_1}
{1165}{}{50NNM_radioluminescence.ogg}
{1166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1168}{}{Ore mines}

# Area 57, Map 117
{1180}{}{riverdale3_1_mine1}
{1185}{}{08vats.mp3}
{1186}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1188}{}{Copper mine}

# Area 57, Map 118
{1190}{}{riverdale3_1_mine2}
{1195}{}{09glow.mp3}
{1196}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1198}{}{Iron mine}

# Area 52, Map 119
{1200}{}{fort_riverdale_dn2}
{1205}{}{Deeper_and_Darker.ogg}
{1206}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1208}{}{Fort Riverdale - tunnel}

# Area 52, Map 120
{1210}{}{fort_riverdale_dn3}
{1215}{}{02Flame_of_the_Ancient_World.ogg}
{1216}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1218}{}{Fort Riverdale - crypt}

# Area 60, Map 123
{1240}{}{riverdale4_1}
{1245}{}{52NNM_root_information.ogg}
{1246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1248}{}{Lead Mine}

# Area 60, Map 125
{1260}{}{riverdale4_1_mine1}
{1265}{}{07desert.ogg}
{1266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1268}{}{Lead Mine}

# Area 61, Map 126
{1270}{}{riverdale5_2}
{1275}{}{55NNM_wind_of_war.ogg}
{1276}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1278}{}{Hills}

# Area 62, Map 128
{1290}{}{riverdale5_3}
{1295}{}{NNM_FS_12_Casa_Grande.ogg}
{1296}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1298}{}{Beach}

# Area 63, Map 130
{1310}{}{riverdale6_1}
{1315}{}{NNM_FS_14_Motel.ogg}
{1316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1318}{}{Old Mine}

# Area 63, Map 132
{1330}{}{riverdale6_1_mine1}
{1335}{}{NNM_FS_10_Jackals.ogg}
{1336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1338}{}{Goldshtein's Mine}

# Area 64, Map 133
{1340}{}{riverdale6_2}
{1345}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1346}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1348}{}{Ruins}

# Area 65, Map 135
{1360}{}{riverdale6_3}
{1365}{}{NNM_FS_05_Collapse.ogg}
{1366}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1368}{}{Cemetery}

# Area 65, Map 136
{1370}{}{riverdale6_3dn}
{1375}{}{11chilrn.ogg}
{1376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1378}{}{Catacombs}

# Area 66, Map 137
{1380}{}{riverdale_dogs_motel}
{1385}{}{City_of_the_Fallen-The_Hourglass.ogg}
{1385}{}{City_of_the_fallen-Hour_of_Destiny.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Hour.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Before_the_Dawn.ogg}
{1386}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1388}{}{Мотель Псов}

# Area 67, Map 139
{1400}{}{riverdale2_1}
{1405}{}{17arroyo.mp3}
{1406}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1408}{}{Fishing camp}

# Area 67, Map 140
{1410}{}{riverdale2_1dn}
{1415}{}{NNM_FS_15_Out-of-Service.ogg}
{1416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1418}{}{Fishing camp, cave}

# Area 68, Map 141
{1420}{}{riverdale1_1}
{1425}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{1426}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1428}{}{West Slope}

# Area 69, Map 143
{1440}{}{riverdale0_1}
{1445}{}{34Cataclysm.ogg}
{1446}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1448}{}{Toxic pit}

# Area 69, Map 144
{1450}{}{toxic_pit}
{1455}{}{38Into_The_ACID_Breach.ogg}
{1456}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1458}{}{Toxic pit, cave}

# Area 70, Map 146
{1470}{}{riverdale0_2}
{1475}{}{26A_Candle_in_the_Darkness.ogg}
{1476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1478}{}{Gorge, South}

# Area 71, Map 148
{1490}{}{riverdale0_3}
{1495}{}{57SHK_sinless_From_Seattle.ogg}
{1496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1498}{}{The Lair of Death}

# Area 71, Map 149
{1500}{}{lair_of_death}
{1505}{}{07desert.ogg}
{1506}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1508}{}{The Lair of Death, cave}

# Area 72, Map 151
{1520}{}{riverdale_canyon}
{1525}{}{NNM_FS_16_One_Way.ogg}
{1526}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1528}{}{Canyon}

# Area 73, Map 153
{1540}{}{riverdale_up_3_1}
{1545}{}{NNM_FS_14_Motel.ogg}
{1546}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1548}{}{Tribe's grave}

# Area 73, Map 154
{1550}{}{riverdale_up_3_1dn}
{1555}{}{10labone.mp3}
{1556}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1558}{}{Tribal grave - temple}

# Area 74, Map 155
{1560}{}{riverdale_up_3_2}
{1565}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1566}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1568}{}{Intersection}

# Area 75, Map 157
{1580}{}{riverdale_up_3_3}
{1585}{}{NNM_FS_04_City_of_Phoenix.ogg}
{1586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1588}{}{Road to Shady}

# Area 76, Map 159
{1600}{}{riverdale_up_2_1}
{1605}{}{49NNM_radiationless.ogg}
{1606}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1608}{}{West cliff}

##### TECH_MAPS #####

# Area 95, Map 170
{1710}{}{Deadloc}
{1715}{}{}
{1716}{}{}
{1718}{}{Purgatory}

##### RIVERDALE_CONTINUE ####

# Area 77, Map 172
{1730}{}{riverdale_up_2_2}
{1735}{}{NNM_FS_15_Out-of-Service}
{1736}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1738}{}{Hounds' Motel}

# Area 78, Map 174
{1750}{}{riverdale_up_2_3}
{1755}{}{NNM_FS_12_Casa_Grande.ogg}
{1756}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1758}{}{Abandoned mine}

# Area 79, Map 176
{1770}{}{riverdale7_1}
{1775}{}{29mark-morgan-curst.ogg}
{1776}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1778}{}{Industrial sector}

# Area 80, Map 178
{1790}{}{riverdale7_2}
{1795}{}{07desert.ogg}
{1796}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1798}{}{Center}

# Area 81, Map 180
{1810}{}{riverdale7_3}
{1815}{}{NNM_FS_06_Out_of_The_World.ogg}
{1816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1818}{}{Residential area}

# Area 81, Map 181
{1820}{}{riverdale7_3_mine1}
{1825}{}{NNM_FS_14_Motel.ogg}
{1826}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1828}{}{Worked-out mine}

# Area 82, Map 183
{1840}{}{riverdale8_2}
{1845}{}{NNM_FS_15_Out-of-Service.ogg}
{1846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1848}{}{Forest of Bones}

##### POSEIDON #####

# Area 110, Map 185
{1860}{}{tanker_deck0}
{1865}{}{30 - Clockwork.ogg}
{1866}{}{gntlwin1:5, gntlwind:5, gustwin1:5, gustwind:5, seagull:10, seagull1:10, seawind:5, seawind1:5, waves:15, waves1:15}
{1868}{}{Upper deck}

# Area 110, Map 186
{1870}{}{tanker_deck1}
{1875}{}{01hub.mp3}
{1876}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, laughte1:5, laughter:5, water:5, water1:5, waves:5, waves1:5}
{1878}{}{Trading decks}

# Area 110, Map 187
{1880}{}{tanker_deck2}
{1885}{}{akiss.mp3}
{1886}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{1888}{}{Bar deck}

# Area 110, Map 188
{1890}{}{tanker_deck3}
{1895}{}{06 - Cluster Decay.ogg}
{1896}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{1898}{}{Engineer deck}

# Area 110, Map 189
{1900}{}{tanker_deck4}
{1905}{}{29mark-morgan-curst.ogg}
{1906}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{1908}{}{Pit}

# Area 110, Map 190
{1910}{}{tanker_str}
{1915}{}{27Lost_Knowledge.ogg}
{1916}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1918}{}{Tower}

# Area 110, Map 191
{1920}{}{tanker_sub1}
{1925}{}{29mark-morgan-curst.ogg}
{1926}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1928}{}{Subdeck №1}

# Area 110, Map 192
{1930}{}{tanker_sub2}
{1935}{}{29mark-morgan-curst.ogg}
{1936}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1938}{}{Subdeck №2}

# Area 110, Map 193
{1940}{}{tanker_sub3}
{1945}{}{29mark-morgan-curst.ogg}
{1946}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1948}{}{Subdeck №3}

##### RIVERDALE_CONTINUE ####

# Area 83, Map 196
{1970}{}{riverdale8_2}
{1975}{}{16follow.mp3}
{1976}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1978}{}{Blossom}

# Area 83, Map 187
{1980}{}{riverdale8_2up}
{1985}{}{09glow.mp3}
{1986}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1988}{}{Institute - 2nd floor}

##### NCR LOCATIONS #####

# Area 111, Map 200
{2010}{}{NCR}
{2015}{}{01hub.mp3}
{2016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2018}{}{NCR}

##### RENO LOCATIONS #####

# Area 112, Map 201
{2020}{}{new_reno}
{2025}{}{19reno.mp3}
{2026}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2028}{}{New Reno}

##### Frisco ####

# Area 114, Map 221
{2220}{}{stop2_frisco1_2}
{2225}{}{31old_earth.ogg}
{2226}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{2228}{}{San-Francisco Port}

# Area 117, Map 224
{2250}{}{stop2_frisco2_2}
{2255}{}{39SHK_Heoi.ogg}
{2256}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2258}{}{San-Francisco Center}

# Area 118, Map 226
{2270}{}{stop2_frisco2_3}
{2275}{}{56SHK_Prosperity.ogg}
{2276}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2278}{}{San-Francisco Hotel}

# Area 118, Map 227
{2280}{}{stop2_frisco2_3dn}
{2285}{}{21sf.mp3}
{2286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2288}{}{San-Francisco Hotel basement}

# Area 118, Map 228
{2290}{}{stop2_frisco2_3up}
{2295}{}{40SHK_Club88.ogg}
{2296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2298}{}{San-Francisco Hotel Club}

# Area 118, Map 229
{2300}{}{stop2_frisco2_3up2}
{2305}{}{21sf.mp3}
{2306}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2308}{}{San-Francisco Hotel 2nd floor and 2nd floors}

# Area 118, Map 230
{2310}{}{stop2_frisco2_3up3}
{2315}{}{21sf.mp3}
{2316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2318}{}{San-Francisco Hotel 3d floors}

# Area 118, Map 231
{2320}{}{stop2_frisco2_3up4}
{2325}{}{21sf.mp3}
{2326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2328}{}{San-Francisco Hotel 4th Hotel floor}

##### MORE_RIVERDALE #####

# Area 130, Map 250
{2510}{}{riverdale_up_1_1}
{2515}{}{07desert.mp3}
{2516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2518}{}{Forest tribe}

# Area 131, Map 252
{2530}{}{riverdale_canyon_3}
{2535}{}{07desert.mp3}
{2536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2538}{}{Radar station}

# Area 132, Map 254
{2550}{}{riverdale_canyon_5}
{2555}{}{NNM_FS_15_Out-of-Service.ogg}
{2556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2558}{}{Miners' town - West}

# Area 133, Map 256
{2570}{}{riverdale_canyon_5}
{2575}{}{NNM_FS_15_Out-of-Service.ogg}
{2576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2578}{}{Miners Town - East}

# Area 133, Map 257
{2580}{}{miner_town_cave_01}
{2585}{}{NNM_FS_14_Motel.ogg}
{2586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2588}{}{Miners' Town - Mine}

# Area 133, Map 258
{2590}{}{miner_town_cave_02}
{2595}{}{NNM_FS_14_Motel.ogg}
{2596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2598}{}{Uranium mine}

# Area 134, Map 261
{2620}{}{riverdale0_4}
{2625}{}{49NNM_radiationless.ogg}
{2626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2628}{}{East slope}

# Area 135, Map 263
{2640}{}{riverdale0_5}
{2645}{}{NNM_FS_04_City_of_Phoenix.ogg}
{2646}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2648}{}{Gorge}

# Area 136, Map 265
{2660}{}{riverdale1_4}
{2665}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{2666}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2668}{}{Devil's Island}

# Area 137, Map 267
{2680}{}{riverdale1_5}
{2685}{}{07desert.ogg}
{2686}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2688}{}{Foothills}

# Area 138, Map 269
{2700}{}{riverdale_up_0_1}
{2705}{}{29mark-morgan-curst.ogg}
{2706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2708}{}{Bog}

# Area 139, Map 271
{2720}{}{riverdale_up_0_2}
{2725}{}{09glow.mp3}
{2726}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2728}{}{Old church}

##### SILVERLAKE #####

# Area 200, Map 300
{3010}{}{silverlake_quarry}
{3015}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{3016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3018}{}{Quarry}

# Area 200, Map 301
{3020}{}{silverlake_quarry_mine1}
{3025}{}{09glow.mp3}
{3026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3028}{}{Iron Mine}

# Area 200, Map 302
{3030}{}{silverlake_quarry_mine2}
{3035}{}{NNM_FS_14_Motel.ogg}
{3036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3038}{}{Copper Mine}

# Area 201, Map 303
{3040}{}{silverlake_mine}
{3045}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3048}{}{Uranium Mine}

# Area 201, Map 305
{3060}{}{uranium_fever}
{3065}{}{29mark-morgan-curst.ogg}
{3066}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3068}{}{Uranium Mine Inside}

# Area 202, Map 306
{3070}{}{silverlake}
{3075}{}{Xcentric-Noiz-Crotalinae.ogg}
{3076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3078}{}{Silverlake}

# Area 202, Map 307
{3080}{}{silverlake_dn}
{3085}{}{NNM_FS_15_Out-of-Service.ogg}
{3086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3088}{}{Silverlake Underground}

# Area 202, Map 308
{3090}{}{silverlake_up}
{3095}{}{48NNM_new_vegas.ogg}
{3096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3098}{}{Silverlake Up}

# Area 203, Map 309
{3100}{}{silverlake_downtown}
{3105}{}{NNM_FS_12_Casa_Grande.ogg}
{3106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3108}{}{Silverlake Downtown}

# Area 204, Map 311
{3120}{}{silverlake_ruin1}
{3125}{}{29mark-morgan-curst.ogg}
{3126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3128}{}{Warehouses}

# Area 205, Map 313
{3140}{}{silverlake_wasteland}
{3145}{}{under_1.ogg}
{3146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3148}{}{Trailer Park}

# Area 206, Map 315
{3160}{}{silverlake_crossroads}
{3165}{}{43NNM_high_wind.ogg}
{3166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3168}{}{Crossroads}

# Area 204, Map 317
{3180}{}{silverlake_waterplant}
{3185}{}{02 - Into The Dust.ogg}
{3186}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3188}{}{Waterplant}

# Area 205, Map 319
{3200}{}{silverlake_ruin2}
{3205}{}{PathofExileTheBellyOfTheBeast.ogg}
{3206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3208}{}{Paradise Avenue}

# Area 209, Map 321
{3220}{}{silverlake_hive}
{3225}{}{PathofExileTheBellyOfTheBeast.ogg}
{3226}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3228}{}{Spider Hive}

# Area 210, Map 323
{3240}{}{silverlake_road2}
{3245}{}{07desert.mp3}
{3246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3248}{}{Highway}

# Area 211, Map 325
{3260}{}{silverlake_hill}
{3265}{}{49NNM_radiationless.ogg}
{3266}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3268}{}{Hills}

# Area 212, Map 327
{3280}{}{silverlake_ruin3}
{3285}{}{54NNM_we_are_sorry.ogg}
{3286}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3288}{}{Coal Mine}

# Area 212, Map 328
{3290}{}{silverlake_ruin3_mine}
{3295}{}{54NNM_we_are_sorry.ogg}
{3296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3298}{}{Coal Mine In}

# Area 213, Map 330
{3310}{}{silverlake_radiotower}
{3315}{}{UnderRail Expedition Main Theme.ogg}
{3316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3318}{}{Old Radiotower}

# Area 213, Map 331
{3320}{}{silverlake_radiotower_dn}
{3325}{}{27Lost_Knowledge.ogg}
{3326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3328}{}{Old Radiotower basement}

# Area 214, Map 332
{3330}{}{silverlake_road_south1}
{3335}{}{02 - Into The Dust.ogg}
{3336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3338}{}{South Interstate}

# Area 215, Map 334
{3350}{}{silverlake_road_south2}
{3355}{}{05raider.mp3}
{3356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3358}{}{Road to Elbrus}

# Area 216, Map 336
{3370}{}{silverlake_elbrus}
{3375}{}{NNM_FS_11_Desert_Rangers.ogg}
{3376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3378}{}{Elbrus Outpost}

# Area 218, Map 338
{3390}{}{silverlake_radio_desert}
{3395}{}{NNM_FS_06_Out_of_The_World.ogg}
{3396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3398}{}{Desert}

# Area 219, Map 340
{3410}{}{silverlake_shop}
{3415}{}{13 - Killadrone.ogg}
{3416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3418}{}{Ruined mall}

# Area 220, Map 342
{3430}{}{silverlake_dump_mount}
{3435}{}{12junktn.mp3}
{3436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3438}{}{Junkyard}

# Area 221, Map 344
{3450}{}{silverlake_dump_mount}
{3455}{}{28Rangers-journey.ogg}
{3456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3458}{}{Hacienda}

##### EDD_SESSION #####

# Area 250, Map 350
{3510}{}{edbox1_1}
{3515}{}{Where Am I.ogg}
{3516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3518}{}{Junkyard}

# Area 251, Map 352
{3530}{}{edbox1_2}
{3535}{}{05raider.mp3}
{3536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3538}{}{The Tribe}

# Area 251, Map 353
{3540}{}{43NNM_high_wind.ogg}
{3545}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3546}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3548}{}{Mine}

# Area 252, Map 354
{3550}{}{edbox2_1}
{3555}{}{02 - Into The Dust.ogg}
{3556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3558}{}{Road}

# Area 253, Map 356
{3570}{}{edbox2_2}
{3575}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3578}{}{Water pump}

# Area 254, Map 358
{3590}{}{edbox3_1}
{3595}{}{Xcentric-Noiz-Crotalinae.ogg}
{3596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3598}{}{Settlement}

# Area 254, Map 359
{3600}{}{edbox3_1dn}
{3605}{}{Institute of Tchort.ogg}
{3606}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3608}{}{Settlement, basement}

# Area 255, Map 360
{3610}{}{edbox3_2}
{3615}{}{PathofExileTheBellyOfTheBeast.ogg}
{3616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3618}{}{Forest}

# Area 256, Map 362
{3630}{}{edbox3_3}
{3635}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3636}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3638}{}{Coal mine}

# Area 256, Map 363
{3640}{}{edbox3_3dn}
{3645}{}{58the25vault.ogg}
{3646}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3648}{}{Coal mine - mine level}

##### NEWTON #####

# Area 280, Map 380
{3810}{}{intro6}
{3815}{}{Memories of the Lost (Main Title) - Endless Space 2 Original Soundtrack.ogg}
{3816}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{3818}{}{Temple of Control, 3rd floor. Conference hall.}

##### RDR_EVENT #####

# Area 281, Map 384
{3850}{}{event_frost_camp}
{3855}{}{05raider.mp3}
{3856}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3858}{}{Camp in the desert.}

# Area 298, Map 398
{3990}{}{rebel_hideout}
{3995}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3996}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3998}{}{Подполье.}

# Area 299, Map 399
{4000}{}{raiders_cave}
{4005}{}{05raider.ogg}
{4006}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4008}{}{Пещера Рейдеров.}

##### TECH_MAPS #####

# Area 300, Map 400
{4010}{}{hell}
{4015}{}{33DOOM.ogg}
{4016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15, pebble:25, pebble1:15, ore:10, ore1:10}
{4018}{}{HELL}

##### OLD_MAPS #####

# Area 357, Map 491
{4920}{}{junk_new}
{4925}{}{57SHK_sinless_From_Seattle.ogg}
{4926}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{4928}{}{Scrapheap}

# Area 357, Map 492
{4930}{}{junk_new_dn}
{4935}{}{07desert.ogg}
{4936}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4938}{}{Scrapheap,underground}

# Area 358, Map 493
{4940}{}{lake}
{4945}{}{NNM_FS_12_Casa_Grande.ogg}
{4946}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4948}{}{Phoenix, level 0}

# Area 359, Map 494
{4950}{}{phoenix_0}
{4955}{}{27Lost_Knowledge.ogg}
{4956}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4958}{}{Phoenix, level 0}

# Area 359, Map 495
{4960}{}{phoenix_1}
{4965}{}{11chilrn.ogg}
{4966}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{4968}{}{Phoenix, level 1}

# Area 360, Map 496
{4970}{}{stop1_ruin1_0}
{4975}{}{05 - Anesthetic.ogg}
{4976}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{4978}{}{Warehouse}

# Area 361, Map 497
{4980}{}{stop1_ruin1_1}
{4985}{}{02 - Into The Dust.ogg}
{4986}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{4988}{}{Substation}

# Area 362, Map 498
{4990}{}{stop1_ruin1_2}
{4995}{}{04 - 12H. Dusk.ogg}
{4996}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{4998}{}{Market}

# Area 363, Map 499
{5000}{}{stop1_ruin1_3}
{5005}{}{26A_Candle_in_the_Darkness.ogg}
{5006}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{5008}{}{Docks}

# Area 364, Map 500
{5010}{}{stop1_ruin2_1}
{5015}{}{18modoc.mp3}
{5016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5018}{}{Hills}

# Area 365, Map 502
{5030}{}{stop1_ruin2_2}
{5035}{}{12junktn.mp3}
{5036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5038}{}{Ruins}

# Area 366, Map 503
{5040}{}{stop1_ruin2_3}
{5045}{}{13 - Killadrone.ogg}
{5046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5048}{}{Main Street}

# Area 367, Map 504
{5051}{}{stop1_ruin3_1}
{5055}{}{03wrldmp}
{5056}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5058}{}{Sink}

# Area 368, Map 505
{5061}{}{stop1_ruin3_2}
{5065}{}{17arroyo}
{5066}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5068}{}{Camping}

# Area 369, Map 506
{5070}{}{stop1_ruin3_3}
{5075}{}{28Rangers-journey.ogg}
{5076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{5078}{}{Old Camp}

##### ELKFOLS_SESSION #####

# Area 400, Map 600
{6010}{}{vbbox_town}
{6015}{}{Crimson_soil.ogg}
{6016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6018}{}{Элк-Фолс}

# Area 401, Map 602
{6030}{}{vbbox_road}
{6035}{}{41NNM_bonus.ogg}
{6036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6038}{}{Перекресток}

# Area 402, Map 604
{6050}{}{vbbox_gasstation}
{6055}{}{49NNM_radiationless.ogg}
{6056}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6058}{}{Старая заправка}

# Area 403, Map 606
{6070}{}{vbbox_stok}
{6075}{}{42NNM_ghost_town.ogg}
{6076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6078}{}{Сток}

# Area 404, Map 608
{6090}{}{vbbox_river_w}
{6095}{}{50NNM_radioluminescence.ogg}
{6096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6098}{}{Западный склон}

# Area 405, Map 610
{6110}{}{vbbox_ruin6}
{6115}{}{47NNM_nevada_theme.ogg}
{6116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6118}{}{Бродвей}

# Area 406, Map 612
{6130}{}{vbbox_swamp1}
{6135}{}{under_1.ogg}
{6136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6138}{}{Болотное предгорье}

# Area 407, Map 614
{6150}{}{vbbox_swamp2}
{6155}{}{34Cataclysm.ogg}
{6156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6158}{}{Гадкая топь}

# Area 408, Map 616
{6170}{}{vbbox_ruin1}
{6175}{}{26A_Candle_in_the_Darkness.ogg}
{6176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6178}{}{Магазины}

# Area 408, Map 617
{6180}{}{vbbox_ruin1_dn}
{6185}{}{45NNM_jammer.ogg}
{6186}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6188}{}{Канализация}

# Area 409, Map 618
{6190}{}{vbbox_ruin2}
{6195}{}{27Lost_Knowledge.ogg}
{6196}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6198}{}{Подстанция}

# Area 409, Map 619
{6200}{}{vbbox_ruin2_dn}
{6205}{}{42NNM_ghost_town.ogg}
{6206}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6208}{}{Технические помещения}

# Area 410, Map 620
{6210}{}{vbbox_ruin3}
{6215}{}{31old_earth.ogg}
{6216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6218}{}{Окраина}

# Area 411, Map 622
{6230}{}{vbbox_ruin4}
{6235}{}{53NNM_village.ogg}
{6236}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6238}{}{Старая свалка}

# Area 412, Map 624
{6250}{}{vbbox_ruin5}
{6255}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{6256}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6258}{}{Старый проезд}

# Area 413, Map 626
{6270}{}{vbbox_camp}
{6275}{}{17arroyo}
{6276}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6278}{}{Кэмпинг}

# Area 414, Map 628
{6290}{}{vbbox_forestroad}
{6295}{}{57SHK_sinless_From_Seattle.ogg}
{6296}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6298}{}{Лесная дорога}

# Area 415, Map 630
{6310}{}{vbbox_forest1}
{6315}{}{30 - Clockwork.ogg}
{6316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6318}{}{Лесное озерцо}

# Area 416, Map 632
{6330}{}{vbbox_forest2}
{6335}{}{05raider.mp3}
{6336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6338}{}{Новая свалка}

# Area 417, Map 634
{6350}{}{vbbox_river_e}
{6355}{}{38Into_The_ACID_Breach.ogg}
{6356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6358}{}{Река восток}

# Area 418, Map 636
{6370}{}{vbbox_mine}
{6375}{}{54NNM_we_are_sorry.ogg}
{6376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6378}{}{Шахта}

# Area 418, Map 637
{6380}{}{vbbox_mine_main}
{6385}{}{City_of_the_Fallen-Darkest_Before_the_Dawn.ogg}
{6386}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6388}{}{Подземное озеро}

# Area 418, Map 638
{6390}{}{vbmine_ne}
{6395}{}{NNM_FS_14_Motel.ogg}
{6396}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6398}{}{Штольня Северо-Восток}

# Area 418, Map 639
{6400}{}{vbmine_nw}
{6405}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{6406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6408}{}{Штольня Северо-Запад}

# Area 418, Map 640
{6410}{}{vbmine_sw}
{6415}{}{58the25vault.ogg}
{6416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6418}{}{Штольня Юго-Запад}

# Area 419, Map 641
{6420}{}{vbbox_religion_warriors_avanpost}
{6425}{}{47NNM_nevada_theme.ogg}
{6426}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{6428}{}{Аванпост Ревнителей}

#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{You have stumbled upon @lex who@.}
#{10000011}{}{You have stumbled upon @lex who@ and @lex player@.}
#{10000012}{}{You have stumbled upon @lex who@ and the @lex player @ gang.}
#{10000013}{}{You have stumbled upon @lex player@.}
#{10000014}{}{You've stumbled upon the @lex player gang@.}
#{10000020}{}{Do you want to see @lex who@?}
#{10000021}{}{Do you want to see @lex who@ and @lex player@?}
#{10000022}{}{Do you want to see @lex who@ and the @lex player gang@?}
#{10000023}{}{Do you want to see @lex player@?}
#{10000024}{}{Do you want to see the @lex player @ gang?}
