
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{World Map}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

##### PERFECTION ####

# Area 27, Map 69
{700}{}{sandbox_bos}
{705}{}{07desert.ogg}
{706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{708}{}{Boneyard}

# Area 27, Map 70
{710}{}{sandbox_bos_dn1}
{715}{}{29mark-morgan-curst.ogg}
{716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{718}{}{Basement}

# Area 27, Map 71
{720}{}{sandbox_bos_dn2}
{725}{}{04Metallic Monks.ogg}
{726}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{728}{}{"Helheim" compound}

# Area 27, Map 72
{730}{}{sandbox_bos_dn3}
{735}{}{mscTimestream.ogg}
{736}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{738}{}{"Helheim" compound Tech level}

##### TECH_MAPS #####

# Area 92, Map 92
{930}{}{startloc}
{935}{}{}
{936}{}{}
{938}{}{Activation}

# Area 93, Map 93
{940}{}{dreamloc}
{945}{}{}
{946}{}{}
{948}{}{Dream}

##### EVENTS #####

# Area 50, Map 100
{1010}{}{event4_hill2}
{1015}{}{F1_Drums_of_Battle.ogg}
{1016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1018}{}{Old ruins}

# Area 51, Map 101
{1020}{}{event2_slavers_out}
{1025}{}{F3_The_Rain_of_Steel.ogg}
{1026}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1028}{}{Rock}

# Area 51, Map 102
{1030}{}{event2_slavers_in}
{1035}{}{F7_Against_the_Odds.ogg}
{1036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1038}{}{Rangers' camp}

##### RIVERDALE #####

# Area 52, Map 103
{1040}{}{fort_riverdale}
{1045}{}{Out_of_Business.ogg}
{1045}{}{The_Courier_Walks_Softly.ogg}
{1045}{}{Under_the_Stars_Cut.ogg}
{1046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1048}{}{Fort Riverdale}

# Area 52, Map 104
{1050}{}{fort_riverdale_dn}
{1055}{}{Deeper_and_Darker.ogg}
{1056}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1058}{}{Fort Riverdale - underground}

# Area 52, Map 105
{1060}{}{fort_riverdale_up1}
{1065}{}{51NNM_ride_to_cheyenne.ogg}
{1066}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1068}{}{Fort Riverdale2}

# Area 52, Map 106
{1070}{}{fort_riverdale_up2}
{1075}{}{08 - Blue Grass.ogg}
{1076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1078}{}{Fort Riverdale3}

# Area 53, Map 107
{1080}{}{riverdale1_2}
{1085}{}{NNM_FS_16_One_Way.ogg}
{1086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1088}{}{Road}

# Area 54, Map 109
{1100}{}{riverdale1_3}
{1105}{}{44NNM_improper_subdivision.ogg}
{1106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1108}{}{Coast}

# Area 55, Map 111
{1120}{}{riverdale2_2}
{1125}{}{NNM_FS_03_ Fogbound.ogg}
{1126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1128}{}{Bridge}

# Area 56, Map 113
{1140}{}{riverdale2_3}
{1145}{}{43NNM_high_wind.ogg}
{1146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1148}{}{Cliff}

# Area 57, Map 115
{1160}{}{riverdale3_1}
{1165}{}{50NNM_radioluminescence.ogg}
{1166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1168}{}{Ore mines}

# Area 57, Map 117
{1180}{}{riverdale3_1_mine1}
{1185}{}{08vats.ogg}
{1186}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1188}{}{NF_METAL mine}

# Area 57, Map 118
{1190}{}{riverdale3_1_mine2}
{1195}{}{09glow.ogg}
{1196}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1198}{}{Iron mine}

# Area 52, Map 119
{1200}{}{fort_riverdale_dn2}
{1205}{}{Deeper_and_Darker.ogg}
{1206}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1208}{}{Fort Riverdale - tunnel}

# Area 52, Map 120
{1210}{}{fort_riverdale_dn3}
{1215}{}{02Flame_of_the_Ancient_World.ogg}
{1216}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1218}{}{Fort Riverdale - crypt}

# Area 60, Map 123
{1240}{}{riverdale4_1}
{1245}{}{52NNM_root_information.ogg}
{1246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1248}{}{Lead Mine}

# Area 60, Map 125
{1260}{}{riverdale4_1_mine1}
{1265}{}{07desert.ogg}
{1266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1268}{}{Lead Mine}

# Area 61, Map 126
{1270}{}{riverdale5_2}
{1275}{}{55NNM_wind_of_war.ogg}
{1276}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1278}{}{Hills}

# Area 62, Map 128
{1290}{}{riverdale5_3}
{1295}{}{NNM_FS_12_Casa_Grande.ogg}
{1296}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1298}{}{Beach}

# Area 63, Map 130
{1310}{}{riverdale6_1}
{1315}{}{NNM_FS_14_Motel.ogg}
{1316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1318}{}{Old Mine}

# Area 44, Map 131
{1320}{}{riverdale6_1_dn}
{1325}{}{NNM_FS_10_Jackals.ogg}
{1326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1328}{}{Slaves Settlement}

# Area 63, Map 132
{1330}{}{riverdale6_1_mine1}
{1335}{}{NNM_FS_10_Jackals.ogg}
{1336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1338}{}{Goldshtein's Mine}

# Area 64, Map 133
{1340}{}{riverdale6_2}
{1345}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1346}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1348}{}{Ruins}

# Area 65, Map 135
{1360}{}{riverdale6_3}
{1365}{}{NNM_FS_05_Collapse.ogg}
{1366}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1368}{}{Cemetery}

# Area 65, Map 136
{1370}{}{riverdale6_3dn}
{1375}{}{11chilrn.ogg}
{1376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1378}{}{Catacombs}

# Area 66, Map 137
{1380}{}{riverdale_dogs_motel}
{1385}{}{City_of_the_Fallen-The_Hourglass.ogg}
{1385}{}{City_of_the_fallen-Hour_of_Destiny.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Hour.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Before_the_Dawn.ogg}
{1386}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1388}{}{Dogs Motel}

# Area 67, Map 139
{1400}{}{riverdale2_1}
{1405}{}{58Tales_of_the_Past.ogg}
{1406}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1408}{}{Fishing camp}

# Area 67, Map 140
{1410}{}{riverdale2_1dn}
{1415}{}{NNM_FS_15_Out-of-Service.ogg}
{1416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1418}{}{Fishing camp, cave}

# Area 68, Map 141
{1420}{}{riverdale1_1}
{1425}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{1426}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1428}{}{West Slope}

# Area 69, Map 143
{1440}{}{riverdale0_1}
{1445}{}{34Cataclysm.ogg}
{1446}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1448}{}{Toxic pit}

# Area 69, Map 144
{1450}{}{toxic_pit}
{1455}{}{38Into_The_ACID_Breach.ogg}
{1456}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1458}{}{Toxic pit, cave}

# Area 70, Map 146
{1470}{}{riverdale0_2}
{1475}{}{26A_Candle_in_the_Darkness.ogg}
{1476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1478}{}{Gorge, South}

# Area 71, Map 148
{1490}{}{riverdale0_3}
{1495}{}{57SHK_sinless_From_Seattle.ogg}
{1496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1498}{}{The Lair of Death}

# Area 71, Map 149
{1500}{}{lair_of_death}
{1505}{}{Fresh_Meat.ogg}
{1506}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1508}{}{The Lair of Death, cave}

# Area 72, Map 151
{1520}{}{riverdale_canyon}
{1525}{}{NNM_FS_16_One_Way.ogg}
{1526}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1528}{}{Canyon}

# Area 73, Map 153
{1540}{}{riverdale_up_3_1}
{1545}{}{NNM_FS_14_Motel.ogg}
{1546}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1548}{}{Tribe's grave}

# Area 73, Map 154
{1550}{}{riverdale_up_3_1dn}
{1555}{}{10labone.ogg}
{1556}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1558}{}{Tribal grave - temple}

# Area 74, Map 155
{1560}{}{riverdale_up_3_2}
{1565}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1566}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1568}{}{Intersection}

# Area 75, Map 157
{1580}{}{riverdale_up_3_3}
{1585}{}{NNM_FS_04_City_of_Phoenix.ogg}
{1586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1588}{}{Road to Shady}

# Area 76, Map 159
{1600}{}{riverdale_up_2_1}
{1605}{}{49NNM_radiationless.ogg}
{1606}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1608}{}{West cliff}

##### TECH_MAPS #####

# Area 95, Map 170
{1710}{}{Deadloc}
{1715}{}{}
{1716}{}{}
{1718}{}{Purgatory}

##### RIVERDALE_CONTINUE ####

# Area 77, Map 172
{1730}{}{riverdale_up_2_2}
{1735}{}{NNM_FS_10_Jackals.ogg}
{1736}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1738}{}{Hounds' Motel}

# Area 78, Map 174
{1750}{}{riverdale_up_2_3}
{1755}{}{NNM_FS_12_Casa_Grande.ogg}
{1756}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1758}{}{Abandoned mine}

# Area 79, Map 176
{1770}{}{riverdale7_1}
{1775}{}{29mark-morgan-curst.ogg}
{1776}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1778}{}{Industrial sector}

# Area 80, Map 178
{1790}{}{riverdale7_2}
{1795}{}{NNM_FS_05_Collapse.ogg}
{1796}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1798}{}{Center}

# Area 81, Map 180
{1810}{}{riverdale7_3}
{1815}{}{NNM_FS_06_Out_of_The_World.ogg}
{1816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1818}{}{Residential area}

# Area 81, Map 181
{1820}{}{riverdale7_3_mine1}
{1825}{}{NNM_FS_14_Motel.ogg}
{1826}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1828}{}{Worked-out mine}

# Area 82, Map 183
{1840}{}{riverdale8_2}
{1845}{}{NNM_FS_15_Out-of-Service.ogg}
{1846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1848}{}{Forest of Bones}

##### POSEIDON #####

# Area 110, Map 185
{1860}{}{tanker_deck0}
{1865}{}{50NNM_radioluminescence.ogg}
{1866}{}{gntlwin1:5, gntlwind:5, gustwin1:5, gustwind:5, seagull:10, seagull1:10, seawind:5, seawind1:5, waves:15, waves1:15}
{1868}{}{Upper deck}

# Area 110, Map 186
{1870}{}{tanker_deck1}
{1875}{}{01hub.ogg}
{1876}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, laughte1:5, laughter:5, water:5, water1:5, waves:5, waves1:5}
{1878}{}{Trading decks}

# Area 110, Map 187
{1880}{}{tanker_deck2}
{1885}{}{akiss.ogg}
{1886}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{1888}{}{Bar deck}

# Area 110, Map 188
{1890}{}{tanker_deck3}
{1895}{}{06 - Cluster Decay.ogg}
{1896}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{1898}{}{Engineer deck}

# Area 110, Map 189
{1900}{}{tanker_deck4}
{1905}{}{29mark-morgan-curst.ogg}
{1906}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{1908}{}{The Pit}

# Area 110, Map 190
{1910}{}{tanker_str0}
{1915}{}{27Lost_Knowledge.ogg}
{1916}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1918}{}{Tower0}

# Area 110, Map 191
{1920}{}{tanker_str1}
{1925}{}{27Lost_Knowledge.ogg}
{1926}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1928}{}{Tower1}

# Area 110, Map 192
{1930}{}{tanker_str2}
{1935}{}{27Lost_Knowledge.ogg}
{1936}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1938}{}{Tower2}

# Area 110, Map 193
{1940}{}{tanker_str3}
{1945}{}{27Lost_Knowledge.ogg}
{1946}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1948}{}{Tower3}

# Area 110, Map 194
{1950}{}{tanker_str4}
{1955}{}{27Lost_Knowledge.ogg}
{1956}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1958}{}{Tower4}

# Area 110, Map 195
{1960}{}{tanker_sub1}
{1965}{}{29mark-morgan-curst.ogg}
{1966}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1968}{}{Subdeck 1}

##### RIVERDALE_CONTINUE ####

# Area 83, Map 196
{1970}{}{riverdale8_2}
{1975}{}{black_dawn_1.ogg}
{1976}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1978}{}{Blossom}

# Area 83, Map 187
{1980}{}{riverdale8_2up}
{1985}{}{09glow.ogg}
{1986}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1988}{}{Institute - 2nd floor}

##### NCR LOCATIONS #####

# Area 111, Map 200
{2010}{}{NCR}
{2015}{}{01hub.ogg}
{2016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2018}{}{NCR}

##### RENO LOCATIONS #####

# Area 112, Map 210
{2110}{}{new_reno}
{2115}{}{19reno.ogg}
{2116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2118}{}{New Reno}

# Area 112, Map 211
{2120}{}{new_reno_dn}
{2125}{}{19reno.ogg}
{2126}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2128}{}{New Reno}

# Area 112, Map 212
{2130}{}{new_reno_up1}
{2135}{}{19reno.ogg}
{2136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5 }
{2138}{}{New Reno}

# Area 112, Map 213
{2140}{}{new_reno_up2}
{2145}{}{19reno.ogg}
{2146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5 }
{2148}{}{New Reno}

# Area 115, Map 214
{2150}{}{new_reno_westside}
{2155}{}{19reno.ogg}
{2156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5 }
{2158}{}{Westside}

# Area 116, Map 216
{2170}{}{new_reno_south}
{2175}{}{NNM_FS_04_City_of_Phoenix.ogg}
{2176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5 }
{2178}{}{Road to Reno}

# Area 113, Map 219
{2200}{}{golgofa}
{2205}{}{FO1_City_of_Lost_Angels.ogg}
{2206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5 }
{2208}{}{Golgofa}

##### Frisco ####

# Area 114, Map 221
{2220}{}{stop2_frisco1_2}
{2225}{}{31old_earth.ogg}
{2226}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{2228}{}{San-Francisco Port}

# Area 117, Map 224
{2250}{}{stop2_frisco2_2}
{2255}{}{39SHK_Heoi.ogg}
{2256}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2258}{}{San-Francisco Center}

# Area 118, Map 226
{2270}{}{stop2_frisco2_3}
{2275}{}{56SHK_Prosperity.ogg}
{2276}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2278}{}{San-Francisco Hotel}

# Area 118, Map 227
{2280}{}{stop2_frisco2_3dn}
{2285}{}{21sf.ogg}
{2286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2288}{}{San-Francisco Hotel basement}

# Area 118, Map 228
{2290}{}{stop2_frisco2_3up}
{2295}{}{40SHK_Club88.ogg}
{2296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2298}{}{San-Francisco Hotel Club}

# Area 118, Map 229
{2300}{}{stop2_frisco2_3up2}
{2305}{}{21sf.ogg}
{2306}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2308}{}{San-Francisco Hotel 2nd floor and 2nd floors}

# Area 118, Map 230
{2310}{}{stop2_frisco2_3up3}
{2315}{}{21sf.ogg}
{2316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2318}{}{San-Francisco Hotel 3d floors}

# Area 118, Map 231
{2320}{}{stop2_frisco2_3up4}
{2325}{}{21sf.ogg}
{2326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2328}{}{San-Francisco Hotel 4th Hotel floor}

# Area 119, Map 232
{2330}{}{stop2_frisco3_2}
{2335}{}{06 - Cluster Decay.ogg}
{2336}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2338}{}{San-Francisco Southern Ruins}

##### MORE_RIVERDALE #####

# Area 130, Map 250
{2510}{}{riverdale_up_1_1}
{2515}{}{07desert.ogg}
{2516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2518}{}{Forest tribe}

# Area 131, Map 252
{2530}{}{riverdale_canyon_3}
{2535}{}{07desert.ogg}
{2536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2538}{}{Radar station}

# Area 132, Map 254
{2550}{}{riverdale_canyon_5}
{2555}{}{NNM_FS_15_Out-of-Service.ogg}
{2556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2558}{}{Miners' town - West}

# Area 133, Map 256
{2570}{}{riverdale_canyon_5}
{2575}{}{NNM_FS_15_Out-of-Service.ogg}
{2576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2578}{}{Miners Town - East}

# Area 133, Map 257
{2580}{}{miner_town_cave_01}
{2585}{}{NNM_FS_14_Motel.ogg}
{2586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2588}{}{Miners' Town - Mine}

# Area 133, Map 258
{2590}{}{miner_town_cave_02}
{2595}{}{NNM_FS_14_Motel.ogg}
{2596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2598}{}{Uranium mine}

# Area 134, Map 261
{2620}{}{riverdale0_4}
{2625}{}{49NNM_radiationless.ogg}
{2626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2628}{}{East slope}

# Area 135, Map 263
{2640}{}{riverdale0_5}
{2645}{}{NNM_FS_04_City_of_Phoenix.ogg}
{2646}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2648}{}{Gorge}

# Area 136, Map 265
{2660}{}{riverdale1_4}
{2665}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{2666}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2668}{}{Devil's Island}

# Area 137, Map 267
{2680}{}{riverdale1_5}
{2685}{}{NNM_FS_16_One_Way.ogg}
{2686}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2688}{}{Foothills}

# Area 138, Map 269
{2700}{}{riverdale_up_0_1}
{2705}{}{29mark-morgan-curst.ogg}
{2706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2708}{}{Bog}

# Area 139, Map 271
{2720}{}{riverdale_up_0_2}
{2725}{}{09glow.ogg}
{2726}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2728}{}{Old church}

# Area 75, Map 273
{2740}{}{riverdale_nf_1_0}
{2745}{}{LastHideout.ogg}
{2746}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2748}{}{Депо}

# Area 75, Map 274
{2750}{}{riverdale_nf_1_0dn}
{2755}{}{under_1.ogg}
{2756}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2758}{}{Депо - тоннель}

# Area 76, Map 275
{2760}{}{riverdale_nf_1_1}
{2765}{}{LastHideout.ogg}
{2766}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2768}{}{Железка}

# Area 77, Map 277
{2780}{}{riverdale_nf_1_2}
{2785}{}{}
{2786}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2788}{}{Станция}

# Area 78, Map 279
{2790}{}{riverdale_nf_2_0}
{2795}{}{}
{2796}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2798}{}{Лагерь Племени}

# Area 79, Map 281
{2820}{}{riverdale_nf_2_1}
{2825}{}{}
{2826}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2828}{}{Густой Лес}

# Area 80, Map 283
{2840}{}{riverdale_nf_2_2}
{2845}{}{}
{2846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2848}{}{Лесная Дорога}

##### SILVERLAKE #####

# Area 200, Map 300
{3010}{}{silverlake_quarry}
{3015}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{3016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3018}{}{Quarry}

# Area 200, Map 301
{3020}{}{silverlake_quarry_mine1}
{3025}{}{09glow.ogg}
{3026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3028}{}{Iron Mine}

# Area 200, Map 302
{3030}{}{silverlake_quarry_mine2}
{3035}{}{NNM_FS_14_Motel.ogg}
{3036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3038}{}{NF_METAL Mine}

# Area 201, Map 303
{3040}{}{silverlake_mine}
{3045}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3048}{}{Uranium Mine}

# Area 201, Map 305
{3060}{}{uranium_fever}
{3065}{}{29mark-morgan-curst.ogg}
{3066}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3068}{}{Uranium Mine Inside}

# Area 202, Map 306
{3070}{}{silverlake}
{3075}{}{Xcentric-Noiz-Crotalinae.ogg}
{3076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3078}{}{Silverlake}

# Area 202, Map 307
{3080}{}{silverlake_dn}
{3085}{}{NNM_FS_15_Out-of-Service.ogg}
{3086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3088}{}{Silverlake Underground}

# Area 202, Map 308
{3090}{}{silverlake_up}
{3095}{}{48NNM_new_vegas.ogg}
{3096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3098}{}{Silverlake Up}

# Area 203, Map 309
{3100}{}{silverlake_downtown}
{3105}{}{NNM_FS_12_Casa_Grande.ogg}
{3106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3108}{}{Silverlake Downtown}

# Area 204, Map 311
{3120}{}{silverlake_ruin1}
{3125}{}{29mark-morgan-curst.ogg}
{3126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3128}{}{Warehouses}

# Area 205, Map 313
{3140}{}{silverlake_wasteland}
{3145}{}{under_1.ogg}
{3146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3148}{}{Trailer Park}

# Area 206, Map 315
{3160}{}{silverlake_crossroads}
{3165}{}{43NNM_high_wind.ogg}
{3166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3168}{}{Crossroads}

# Area 204, Map 317
{3180}{}{silverlake_waterplant}
{3185}{}{02 - Into The Dust.ogg}
{3186}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3188}{}{Waterplant}

# Area 205, Map 319
{3200}{}{silverlake_ruin2}
{3205}{}{PathofExileTheBellyOfTheBeast.ogg}
{3206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3208}{}{Paradise Avenue}

# Area 209, Map 321
{3220}{}{silverlake_hive}
{3225}{}{PathofExileTheBellyOfTheBeast.ogg}
{3226}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3228}{}{Spider Hive}

# Area 210, Map 323
{3240}{}{silverlake_road2}
{3245}{}{07desert.ogg}
{3246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3248}{}{Highway}

# Area 211, Map 325
{3260}{}{silverlake_hill}
{3265}{}{49NNM_radiationless.ogg}
{3266}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3268}{}{Hills}

# Area 212, Map 327
{3280}{}{silverlake_ruin3}
{3285}{}{54NNM_we_are_sorry.ogg}
{3286}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3288}{}{Coal Mine}

# Area 212, Map 328
{3290}{}{silverlake_ruin3_mine}
{3295}{}{54NNM_we_are_sorry.ogg}
{3296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3298}{}{Coal Mine In}

# Area 213, Map 330
{3310}{}{silverlake_radiotower}
{3315}{}{UnderRail Expedition Main Theme.ogg}
{3316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3318}{}{Old Radiotower}

# Area 213, Map 331
{3320}{}{silverlake_radiotower_dn}
{3325}{}{27Lost_Knowledge.ogg}
{3326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3328}{}{Old Radiotower basement}

# Area 214, Map 332
{3330}{}{silverlake_road_south1}
{3335}{}{02 - Into The Dust.ogg}
{3336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3338}{}{South Interstate}

# Area 215, Map 334
{3350}{}{silverlake_road_south2}
{3355}{}{05raider.ogg}
{3356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3358}{}{Road to Elbrus}

# Area 216, Map 336
{3370}{}{silverlake_elbrus}
{3375}{}{NNM_FS_11_Desert_Rangers.ogg}
{3376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3378}{}{Elbrus Outpost}

# Area 218, Map 338
{3390}{}{silverlake_radio_desert}
{3395}{}{NNM_FS_06_Out_of_The_World.ogg}
{3396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3398}{}{Desert}

# Area 219, Map 340
{3410}{}{silverlake_shop}
{3415}{}{13 - Killadrone.ogg}
{3416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3418}{}{Ruined mall}

# Area 220, Map 342
{3430}{}{silverlake_dump_mount}
{3435}{}{12junktn.ogg}
{3436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3438}{}{Junkyard}

# Area 221, Map 344
{3450}{}{silverlake_ranch}
{3455}{}{28Rangers-journey.ogg}
{3456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3458}{}{Hacienda}

# Area 221, Map 345
{3460}{}{silverlake_ranch_dn}
{3465}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3466}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3468}{}{Hacienda Cave}

# Area 222, Map 346
{3470}{}{silverlake_gas_road}
{3475}{}{57SHK_sinless_From_Seattle.ogg}
{3476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3478}{}{Road to "GasCO"}

# Area 223, Map 348
{3490}{}{silverlake_gas}
{3495}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3498}{}{"GasCO" Ruins}

# Area 224, Map 350
{3510}{}{silverlake_hill_road}
{3515}{}{05raider.ogg}
{3516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3518}{}{Hillside Road}

# Area 225, Map 352
{3530}{}{silverlake_space_port}
{3535}{}{30 - Clockwork.ogg}
{3536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3538}{}{Launch Site}

# Area 226, Map 354
{3550}{}{silverlake_shuttle}
{3555}{}{38Into_The_ACID_Breach.ogg}
{3556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3558}{}{Shuttle}

# Area 226, Map 355
{3560}{}{silverlake_shuttle_inside}
{3565}{}{34Cataclysm.ogg}
{3566}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5}
{3568}{}{Shuttle Inside}

# Area 226, Map 356
{3570}{}{silverlake_lab1}
{3575}{}{49NNM_radiationless.ogg}
{3576}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{3578}{}{X-01 level 1}

# Area 226, Map 557
{3580}{}{silverlake_lab2}
{3585}{}{49NNM_radiationless.ogg}
{3586}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{3588}{}{X-01 level 2}

# Area 227, Map 358
{3590}{}{wood_road1}
{3595}{}{47NNM_nevada_theme.ogg}
{3596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3598}{}{Gates of the Heart}

# Area 227, Map 359
{3600}{}{wood_road_turn}
{3605}{}{34Cataclysm.ogg}
{3606}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3608}{}{Turn}

# Area 227, Map 360
{3610}{}{wood_road2}
{3615}{}{50NNM_radioluminescence.ogg}
{3616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3618}{}{Scout post "Alpha"}

# Area 227, Map 361
{3620}{}{wood_road3}
{3625}{}{PathofExileTheBellyOfTheBeast.ogg}
{3626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3628}{}{Church}

# Area 227, Map 362
{3630}{}{wood_road3_dn}
{3635}{}{42NNM_ghost_town.ogg}
{3636}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3638}{}{Church basement}

# Area 227, Map 363
{3640}{}{wood_road4}
{3645}{}{PathofExileTheBellyOfTheBeast.ogg}
{3646}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3648}{}{Jaeger's House}

# Area 227, Map 364
{3650}{}{wood_road_outpost}
{3655}{}{Crimson_soil.ogg}
{3656}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3658}{}{Outpost "Black Crow"}

# Area 227, Map 365
{3660}{}{wolferin}
{3665}{}{30 - Clockwork.ogg}
{3666}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3668}{}{X-01 East Entrance}

# Area 227, Map 366
{3670}{}{wolferin_in}
{3675}{}{41NNM_bonus.ogg}
{3676}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3678}{}{X-01 East Entrance Bunker}

##### NEWTON #####

# Area 280, Map 380
{3810}{}{intro6}
{3815}{}{Memories of the Lost (Main Title) - Endless Space 2 Original Soundtrack.ogg}
{3816}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{3818}{}{Temple of Control, 3rd floor. Conference hall.}

##### RDR_EVENT #####

# Area 281, Map 384
{3850}{}{event_frost_camp}
{3855}{}{05raider.ogg}
{3856}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3858}{}{Camp in the desert.}

# Area 298, Map 398
{3990}{}{rebel_hideout}
{3995}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3996}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3998}{}{Underground}

# Area 299, Map 399
{4000}{}{raiders_cave}
{4005}{}{05raider.ogg}
{4006}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4008}{}{Raiders Cave}

##### TECH_MAPS #####

# Area 300, Map 400
{4010}{}{hell}
{4015}{}{33DOOM.ogg}
{4016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15, pebble:25, pebble1:15, ore:10, ore1:10}
{4018}{}{HELL}

##### TNF_MAPS #####

# Area 357, Map 491
{4920}{}{junk_new}
{4925}{}{57SHK_sinless_From_Seattle.ogg}
{4926}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{4928}{}{Scrapheap}

# Area 357, Map 492
{4930}{}{junk_new_dn}
{4935}{}{07desert.ogg}
{4936}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4938}{}{Scrapheap,underground}

# Area 358, Map 493
{4940}{}{lake}
{4945}{}{NNM_FS_12_Casa_Grande.ogg}
{4946}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4948}{}{Phoenix, level 0}

# Area 359, Map 494
{4950}{}{phoenix_0}
{4955}{}{14necro.ogg}
{4956}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4958}{}{Phoenix, level 0}

# Area 359, Map 495
{4960}{}{phoenix_1}
{4965}{}{22vcity.ogg}
{4966}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{4968}{}{Phoenix, level 1}

#=============CLINTON===================

# Area 360, Map 500
{5010}{}{clinton_center}
{5015}{}{Best_Memories_Are_Hers.ogg}
{5015}{}{Someone_Lived_This.ogg}
{5016}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5018}{}{Central District}

# Area 360, Map 501
{5020}{}{clinton_center_dn1}
{5025}{}{last_hideout.ogg}
{5026}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5028}{}{Central Shelter}

# Area 360, Map 502
{5030}{}{clinton_center_dn2}
{5035}{}{NNM_FS_16_One_Way.ogg}
{5036}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5038}{}{Station}

# Area 360, Map 503
{5040}{}{clinton_center_up}
{5045}{}{48NNM_new_vegas.ogg}
{5046}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{5048}{}{Second Floor}

# Area 361, Map 504
{5050}{}{clinton1_1}
{5055}{}{black_dawn_1.ogg}
{5056}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5058}{}{Warehouses}

# Area 362, Map 506
{5070}{}{clinton1_2}
{5075}{}{52NNM_root_information.ogg}
{5076}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5078}{}{Substation}

# Area 362, Map 507
{5080}{}{clinton1_2_dn}
{5085}{}{45NNM_jammer.ogg}
{5086}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5088}{}{Maintenance Room}

# Area 363, Map 508
{5090}{}{clinton1_3}
{5095}{}{06 - Cluster Decay.ogg}
{5096}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5098}{}{Shops}

# Area 363, Map 509
{5100}{}{clinton1_3_dn}
{5105}{}{42NNM_ghost_town.ogg}
{5106}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5107}{}{Old Lab}

# Area 364, Map 511
{5120}{}{clinton1_4_dn}
{5125}{}{NNM_FS_12_Casa_Grande.ogg}
{5126}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5128}{}{Control Room}

# Area 364, Map 510
{5110}{}{clinton1_4}
{5115}{}{NNM_FS_12_Casa_Grande.ogg}
{5116}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5118}{}{Docks}

# Area 365, Map 512
{5130}{}{clinton2_1}
{5135}{}{46NNM_line_of_policy.ogg}
{5136}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5138}{}{Checkpoint}

# Area 366, Map 514
{5150}{}{clinton2_2}
{5155}{}{red_life_1.ogg}
{5156}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5158}{}{Gas Station}

# Area 366, Map 515
{5160}{}{clinton2_2_dn}
{5165}{}{NNM_FS_03_ Fogbound.ogg}
{5166}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{5168}{}{Gas Station dn}

# Area 367, Map 516
{5170}{}{clinton2_3}
{5175}{}{NNM_FS_15_Out-of-Service.ogg}
{5176}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5178}{}{City Hall}

# Area 367, Map 517
{5180}{}{clinton2_3_dn}
{5185}{}{Sleepless Ruins.ogg}
{5186}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5188}{}{Telecom Center}

# Area 368, Map 518
{5190}{}{clinton2_4}
{5195}{}{Save_room1.ogg}
{5196}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5198}{}{Library}

# Area 369, Map 520
{5210}{}{clinton3_1}
{5215}{}{NNM_FS_05_Collapse.ogg}
{5216}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5218}{}{Convoy}

# Area 370, Map 522
{5230}{}{clinton3_4}
{5235}{}{Deeper_and_Darker.ogg}
{5236}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5238}{}{East Side}

# Area 371, Map 524
{5250}{}{clinton4_1}
{5255}{}{31old_earth.ogg}
{5256}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5258}{}{Police Department}

# Area 372, Map 526
{5270}{}{clinton4_4}
{5275}{}{58Tales_of_the_Past.ogg}
{5276}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5278}{}{Crossroads}

# Area 372, Map 527
{5280}{}{clinton4_4_dn}
{5285}{}{under_1.ogg}
{5286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5288}{}{Clinton Mine}

# Area 373, Map 528
{5290}{}{clinton5_1}
{5295}{}{secrets_from_river.ogg}
{5296}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5298}{}{Rail Crossing}

# Area 374, Map 530
{5310}{}{clinton5_2}
{5315}{}{26A_Candle_in_the_Darkness.ogg}
{5316}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5318}{}{Downtown}

# Area 375, Map 532
{5330}{}{clinton5_3}
{5335}{}{26A_Candle_in_the_Darkness.ogg}
{5336}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5338}{}{Clinton Park}

# Area 376, Map 534
{5350}{}{clinton5_4}
{5355}{}{42NNM_ghost_town.ogg}
{5356}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5358}{}{Excavation}

# Area 377, Map 536
{5370}{}{clinton5_4}
{5375}{}{Crimson_soil.ogg}
{5376}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5378}{}{Highway}

# Area 378, Map 542
{5430}{}{dv_scav_1}
{5435}{}{42NNM_ghost_town.ogg}
{5436}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5438}{}{Vault5 - 1}

# Area 378, Map 543
{5440}{}{dv_scav_3}
{5445}{}{42NNM_ghost_town.ogg}
{5446}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5448}{}{Vault5 - 2}

# Area 378, Map 544
{5450}{}{dv_scav_3}
{5455}{}{42NNM_ghost_town.ogg}
{5456}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5458}{}{Vault5 - 3}

##### ELKFALLS_SESSION #####

# Area 400, Map 600
{6010}{}{vbbox_town}
{6015}{}{Crimson_soil.ogg}
{6016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6018}{}{Elks Falls}

##### VAULT66_SESSION #####

# Area 420, Map 643
{6440}{}{vault66_dn1}
{6445}{}{31old_earth.ogg}
{6446}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6448}{}{Vault 66, Entrance}

# Area 420, Map 644
{6450}{}{vault66_dn2}
{6455}{}{27Lost_Knowledge.ogg}
{6456}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6458}{}{Vault 66, Living Blocks}

# Area 420, Map 645
{6460}{}{vault66_dn3}
{6465}{}{29mark-morgan-curst.ogg}
{6466}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6468}{}{Vault 66, Vault Command Center}

# Area 420, Map 646
{6470}{}{vault66_dn4}
{6475}{}{06 - Cluster Decay.ogg}
{6476}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6478}{}{Vault 66, Industrial Level}

##### CARAVAN #####

# Area 450, Map 700
{7010}{}{caravan_dest_n1}
{7015}{}{01hub.ogg}
{7016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7018}{}{Caravan Camp}

# Area 451, Map 701
{7020}{}{bridge_road_ns2}
{7025}{}{05raider.ogg}
{7026}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7028}{}{Caravan Road}

# Area 452, Map 702
{7030}{}{desert_road_ns1}
{7035}{}{07desert.ogg}
{7036}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7038}{}{Caravan Road}

# Area 453, Map 703
{7040}{}{desert_road_ns2}
{7045}{}{23world.ogg}
{7046}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7048}{}{Caravan Road}

# Area 454, Map 704
{7050}{}{forest_road_ns2}
{7055}{}{03wrldmp.ogg}
{7056}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7058}{}{Caravan Road}

################################## CLINTON NEW ##################################
# Area 498, Map 4994
{49950}{}{clinton6_0}
{49955}{}{NNM_FS_14_Motel.ogg}
{49956}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{49958}{}{Old Mine}

# Area 498, Map 4995
{49960}{}{clinton6_0_dn}
{49965}{}{NNM_FS_10_Jackals.ogg}
{49966}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{49968}{}{Old Working Mine}

# Area 498, Map 4996
{49970}{}{clinton_lab1}
{49975}{}{31old_earth}
{49976}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{49978}{}{Lab Level 1}

# Area 498, Map 4997
{49980}{}{clinton_lab2}
{49985}{}{27Lost_Knowledge.ogg}
{49986}{}bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{49988}{}{Lab Level 2}

# Area 499, Map 4998
{49990}{}{clinton6_1}
{49995}{}{45NNM_jammer.ogg}
{49996}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{49998}{}{West Coast}

# Area 500, Map 5000
{50010}{}{clinton6_2}
{50015}{}{45NNM_jammer.ogg}
{50016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50018}{}{Hill}

# Area 500, Map 5002
{50030}{}{clinton6_2_dn2}
{50035}{}{58the25vault.ogg}
{50036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{50038}{}{Old Mines}

# Area 501, Map 5010
{50110}{}{clinton6_3}
{50115}{}{53NNM_village.ogg}
{50116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50118}{}{Ruins}

# Area 502, Map 5020
{50210}{}{clinton6_4}
{50215}{}{47NNM_nevada_theme.ogg}
{50216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50218}{}{Broadway}

# Area 505, Map 5030
{50310}{}{clinton7_2}
{50315}{}{42NNM_ghost_town.ogg}
{50316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50318}{}{Drain}

# Area 506, Map 5040
{50410}{}{clinton7_3}
{50415}{}{51NNM_ride_to_cheyenne.ogg}
{50416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50418}{}{Camp}

# Area 507, Map 5050
{50510}{}{clinton7_4}
{50515}{}{43NNM_high_wind.ogg}
{50516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50518}{}{Center Camp}

# Area 508, Map 5060
{50610}{}{clinton8_2}
{50615}{}{43NNM_high_wind.ogg}
{50616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50618}{}{Forest}

# Area 509, Map 5070
{50710}{}{clinton8_3}
{50715}{}{12junktn.ogg}
{50716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50718}{}{Dump}

# Area 510, Map 5080
{50810}{}{clinton8_4}
{50815}{}{02 - Into The Dust.ogg}
{50816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50818}{}{Southern Motorway}

# Area 511, Map 5090
{50910}{}{clinton9_2}
{50915}{}{55NNM_wind_of_war.ogg}
{50916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50918}{}{Forest}

# Area 512, Map 5100
{51010}{}{clinton9_3}
{51015}{}{27Lost_Knowledge.ogg}
{51016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51018}{}{Gas Station}

# Area 513, Map 5110
{51110}{}{clinton9_4}
{51115}{}{07desert.ogg}
{51116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51118}{}{Factory Ruins}

# Area 514, Map 5120
{51210}{}{clinton10_2}
{51215}{}{57SHK_sinless_From_Seattle.ogg}
{51216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51218}{}{Southern Forest}

# Area 514, Map 5121
{51220}{}{clinton10_2_dn}
{51225}{}{58Tales_of_the_Past.ogg}
{51226}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51228}{}{Fisherman's House}

# Area 515, Map 5130
{51310}{}{clinton10_3}
{51315}{}{12junktn.ogg}
{51316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51318}{}{Forest Road}

# Area 515, Map 5131
{51320}{}{clinton10_3_dn}
{51325}{}{NNM_FS_15_Out-of-Service.ogg}
{51326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51328}{}{Forest Road Cave}

# Area 516, Map 5132
{51330}{}{clinton10_3_dn_2}
{51335}{}{58Tales_of_the_Past.ogg}
{51336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51338}{}{Deep Cave}

# Area 516, Map 5140
{51410}{}{clinton11_4}
{51415}{}{NNM_FS_11_Desert_Rangers.ogg}
{51416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51418}{}{Elbrus}

##### BLAIRE #####

# Area 650, Map 5800
{58010}{}{blaire1_1}
{58015}{}{07desert.ogg}
{58016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58018}{}{The Lake}

# Area 650, Map 5801
{58020}{}{blaire1_1_dn1}
{58025}{}{07desert.ogg}
{58026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58028}{}{Lake, Down}

# Area 651, Map 5802
{58030}{}{blaire1_2}
{58035}{}{07desert.ogg}
{58036}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58038}{}{Northern Road}

# Area 651, Map 5803
{58040}{}{blaire1_2_dn1}
{58045}{}{07desert.ogg}
{58046}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58048}{}{Northern Road, Down}

# Area 652, Map 5804
{58050}{}{blaire1_3}
{58055}{}{07desert.ogg}
{58056}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58058}{}{Ruined Farms}

# Area 652, Map 5805
{58060}{}{blaire1_3_dn1}
{58065}{}{07desert.ogg}
{58066}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58068}{}{Ruined Farm, Down}

# Area 653, Map 5806
{58070}{}{blaire2_1}
{58075}{}{17arroyo.ogg}
{58076}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58078}{}{Western Cliffs}

# Area 653, Map 5807
{58080}{}{blaire2_1_cav1}
{58085}{}{13carvrn.ogg}
{58086}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58088}{}{Uranium Caves}

# Area 654, Map 5808
{58090}{}{blaire2_2}
{58095}{}{24redd.ogg}
{58096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58098}{}{Blaire}

# Area 654, Map 5809
{58100}{}{blaire2_2_dn1}
{58105}{}{13carvrn.ogg}
{58106}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58108}{}{Blaire Mines Level 1}

# Area 654, Map 5810
{58110}{}{blaire2_2_dn2}
{58115}{}{13carvrn.ogg}
{58116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58118}{}{Blaire Mines Level 2}

# Area 654, Map 5811
{58120}{}{v16_1}
{58125}{}{13carvrn.ogg}
{58126}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58128}{}{Vault 16 Level 1}

# Area 654, Map 5812
{58130}{}{v16_2}
{58135}{}{18modoc.ogg}
{58136}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58138}{}{Vault 16 Level 2}

# Area 654, Map 5813
{58140}{}{v16_3}
{58145}{}{06vault.ogg}
{58146}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58148}{}{Vault 16 Level 3}

# Area 655, Map 5814
{58150}{}{blaire2_3}
{58155}{}{17arroyo.ogg}
{58156}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58158}{}{Eastern Cliffs}

# Area 655, Map 5815
{58160}{}{blaire2_3_cav1}
{58165}{}{13carvrn.ogg}
{58166}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58168}{}{NF_METAL Caves}

# Area 655, Map 5816
{58170}{}{blaire2_3_cav2}
{58175}{}{13carvrn.ogg}
{58176}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58178}{}{Coal Caves}

# Area 656, Map 5817
{58180}{}{blaire3_1}
{58185}{}{07desert.ogg}
{58186}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58188}{}{Desert}

# Area 657, Map 5818
{58190}{}{blaire3_2}
{58195}{}{07desert.ogg}
{58196}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58198}{}{Southern Road}

# Area 658, Map 5819
{58200}{}{blaire3_3}
{58205}{}{15shady.ogg}
{58206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58208}{}{Red Rock}

# Area 658, Map 5820
{58210}{}{blaire3_3_dn1}
{58215}{}{15shady.ogg}
{58216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58218}{}{Red Rock, Down}

# Area 659, Map 5821
{58220}{}{v23_ext}
{58225}{}{07desert.ogg}
{58226}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58228}{}{Vault 23 Exterior}

# Area 659, Map 5822
{58230}{}{v23_1}
{58235}{}{02Flame_of_the_Ancient_World.ogg}
{58236}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58238}{}{Vault 23 Level 1}

# Area 659, Map 5823
{58240}{}{v23_2}
{58245}{}{09glow.ogg}
{58246}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58248}{}{Vault 23 Level 2}

# Area 659, Map 5824
{58250}{}{v23_3}
{58255}{}{14necro.ogg}
{58256}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58258}{}{Vault 23 Level 3}

# Area 660, Map 5825
{58260}{}{v28_ext}
{58265}{}{07desert.ogg}
{58266}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58268}{}{Vault 28 Exterior}

# Area 660, Map 5826
{58270}{}{v28_1}
{58275}{}{02Flame_of_the_Ancient_World.ogg}
{58276}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58278}{}{Vault 28 Level 1}

# Area 660, Map 5827
{58280}{}{v28_2}
{58285}{}{14necro.ogg}
{58286}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58288}{}{Vault 23 Level 2}

# Area 660, Map 5828
{58290}{}{v28_3}
{58295}{}{08vats.ogg}
{58296}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58298}{}{Vault 23 Level 3}

# Area 661, Map 5829
{58300}{}{dv_ext2}
{58305}{}{labone.ogg}
{58306}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58308}{}{Demo Vault Exterior 2}

# Area 662, Map 5830
{58310}{}{dv_ext1}
{58315}{}{labone.ogg}
{58316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58318}{}{Demo Vault Exterior 1}

# Area 662, Map 5831
{58320}{}{dv_1}
{58325}{}{09glow.ogg}
{58326}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58328}{}{Demo Vault Level 1}

# Area 662, Map 5832
{58330}{}{dv_2}
{58335}{}{09glow.ogg}
{58336}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58338}{}{Demo Vault Level 2}

# Area 662, Map 5833
{58340}{}{dv_3}
{58345}{}{09glow.ogg}
{58346}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58348}{}{Demo Vault Level 3}

# Area 663, Map 5834
{58350}{}{cara_nw}
{58355}{}{07desert.ogg}
{58356}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58358}{}{Caravan Road North-West}

# Area 664, Map 5835
{58360}{}{cara_n1}
{58365}{}{07desert.ogg}
{58366}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58368}{}{Caravan Road North}

# Area 665, Map 5836
{58370}{}{cara_n2}
{58375}{}{07desert.ogg}
{58376}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58378}{}{Caravan Road North}

# Area 666, Map 5837
{58380}{}{cara_n3}
{58385}{}{07desert.ogg}
{58386}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58388}{}{Caravan Road North}

# Area 667, Map 5838
{58390}{}{cara_dest_n}
{58395}{}{01hub.0gg}
{58396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58398}{}{Caravan Destination North}

# Area 668, Map 5839
{58400}{}{cara_w1}
{58405}{}{07desert.ogg}
{58406}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58408}{}{Caravan Road West}

# Area 669, Map 5840
{58410}{}{cara_w2}
{58415}{}{07desert.ogg}
{58416}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58418}{}{Caravan Road West}

# Area 670, Map 5841
{58420}{}{cara_w3}
{58425}{}{07desert.ogg}
{58426}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58428}{}{Caravan Road West}

# Area 671, Map 5842
{58430}{}{cara_dest_w}
{58435}{}{01hub.ogg}
{58436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58438}{}{Caravan Destination West}

# DUKE'S ASHHILL

# Area 707, Map 7070
{70710}{}{ashhill_center}
{70715}{}{07desert.ogg}
{70716}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70718}{}{Ashhill}

# RADO SPRINGS

# Area 800, Map 8000
{80010}{}{rs3_4}
{80015}{}{last_hideout.ogg}
{80016}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, neptune:5, water:5, water1:5, pebble:5, pebble1:5}
{80018}{}{Highway}

# Area 800, Map 8001
{80020}{}{rs3_4_up1}
{80025}{}{47NNM_nevada_theme.ogg}
{80026}{}{seawind:10, seawind1:5, bangpip1:10, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5}
{80028}{}{Highway}

# Area 800, Map 8002
{80030}{}{rs3_4_up2}
{80035}{}{Mark Morgan - Radiation Cloud.ogg}
{80036}{}{gntlwin1:5, gntlwind:5, blowout_amb_01:10, clang:5, clang1:5, clank:5, clank1:5, water:5, water1:5}
{80038}{}{Highway}

# Area 800, Map 8003
{80040}{}{rs3_4_up3}
{80045}{}{NNM_FS_03_ Fogbound.ogg}
{80046}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80048}{}{Highway}

# Area 800, Map 8004
{80050}{}{rs3_4_up4}
{80055}{}{47NNM_nevada_theme.ogg}
{80056}{}{clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5, water:5, water1:5}
{80058}{}{Highway}

# Area 800, Map 8005
{80060}{}{rs3_4_up5}
{80065}{}{Mark Morgan - Radiation Cloud.ogg}
{80066}{}{gntlwin1:5, gntlwind:5, clang:5, clang1:5, clank:5, clank1:5}
{80068}{}{Highway}

# Area 800, Map 8006
{80070}{}{rs3_4_up6}
{80075}{}{04 - 12h. Dusk.ogg}
{80076}{}{seawind:10, seawind1:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80078}{}{Highway}

# Area 801, Map 8010
{80110}{}{rs3_5}
{80115}{}{11chilrn.ogg}
{80116}{}{bangpip1:5, bangpipe:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5}
{80118}{}{Business Center}

# Area 801, Map 8011
{80120}{}{rs3_5_up1}
{80125}{}{under_1.ogg}
{80126}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, seawind:10, seawind1:5}
{80128}{}{Business Center}

# Area 801, Map 8012
{80130}{}{rs3_5_up2}
{80135}{}{29mark-morgan-curst.ogg}
{80136}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80138}{}{Business Center}

# Area 801, Map 8013
{80140}{}{rs3_5_up3}
{80145}{}{NNM_FS_03_ Fogbound.ogg}
{80146}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80148}{}{Business Center}

# Area 801, Map 8014
{80150}{}{rs3_5_up4}
{80155}{}{under_1.ogg}
{80156}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, seawind:10, seawind1:5}
{80158}{}{Business Center}

# Area 801, Map 8015
{80160}{}{rs3_5_up5}
{80165}{}{29mark-morgan-curst.ogg}
{80166}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80168}{}{Business Center}

# Area 801, Map 8016
{80170}{}{rs3_5_up6}
{80175}{}{NNM_FS_03_ Fogbound.ogg}
{80176}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80178}{}{Business Center}

# Area 801, Map 8017
{80180}{}{rs3_5_up7}
{80185}{}{under_1.ogg}
{80186}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, seawind:10, seawind1:5}
{80188}{}{Business Center}

# Area 801, Map 8018
{80190}{}{rs3_5_up8}
{80195}{}{29mark-morgan-curst.ogg}
{80196}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80198}{}{Business Center}

# Area 801, Map 8019
{80200}{}{rs3_5_up9}
{80205}{}{NNM_FS_03_ Fogbound.ogg}
{80206}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80208}{}{Business Center}

# Area 801, Map 8020
{80210}{}{rs3_5_up10}
{80215}{}{under_1.ogg}
{80216}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, seawind:10, seawind1:5}
{80218}{}{Business Center}

# Area 801, Map 8021
{80220}{}{rs3_5_up11}
{80225}{}{29mark-morgan-curst.ogg}
{80226}{}{bangpip1:5, gntlwin1:5, gntlwind:5, clank:5, clank1:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80228}{}{Business Center}

# Area 801, Map 8022
{80230}{}{rs3_5_up12}
{80235}{}{NNM_FS_03_ Fogbound.ogg}
{80236}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5}
{80238}{}{Business Center}

# Area 801, Map 8023
{80240}{}{rs3_5_up13}
{80245}{}{29mark-morgan-curst.ogg}
{80246}{}{seawind:10, seawind1:5, bangpip1:5, clank1:5, clang:5, clang1:5, neptune:5}
{80248}{}{Business Center}

# Area 803, Map 8030
{80310}{}{rs3_6_noburner}
{80315}{}{19reno.ogg}
{80316}{}{drunkla1:20, drunklaf:20, animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80318}{}{FairTrade Districtн}

# Area 803, Map 8031
{80320}{}{rs3_6_up1}
{80325}{}{13carvrn.ogg}
{80326}{}{bangpip1:5, clank:5, clank1:5, coolant:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80328}{}{FairTrade District}

# Area 803, Map 8032
{80330}{}{rs3_6_up2}
{80335}{}{19reno.ogg}
{80336}{}{bangpip1:5, clank:5, clank1:5, coolant:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80338}{}{FairTrade District}

# Area 803, Map 8033
{80340}{}{rs3_6_up3}
{80345}{}{51NNM_ride_to_cheyenne.ogg}
{80346}{}{bangpip1:5, clank:5, clank1:5, coolant:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80348}{}{FairTrade District}

# Area 803, Map 8034
{80350}{}{rs3_6_up4}
{80355}{}{10labone.ogg}
{80356}{}{bangpip1:5, clank:5, clank1:5, coolant:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80358}{}{FairTrade District}

# Area 803, Map 8035
{80360}{}{rs3_6_up5}
{80365}{}{51NNM_ride_to_cheyenne.ogg}
{80366}{}{bangpip1:5, clank:5, clank1:5, coolant:5, clang:5, clang1:5, mechpum1:5, mechpum:5, neptune:5}
{80368}{}{FairTrade District}

# Area 804, Map 8040
{80410}{}{rs2_5_noburner}
{80415}{}{22vcity.ogg}
{80416}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, pebble:5, pebble1:10, vulture:5, vulture1:5, clank:5, clank1:5, seawind:10, seawind1:5}
{80418}{}{Bombed Land}

# Area 804, Map 8041
{80420}{}{rs2_5_dn1_novault}
{80425}{}{51NNM_ride_to_cheyenne.ogg}
{80426}{}{bats1:10, bats:5, clang1:5, clank:5, clank1:5, fixstill:5, water1:5, pebble:5, pebble1:5, bangpip1:5}
{80428}{}{Bombed Land}

# Area 805, Map 8050
{80510}{}{rs_burner}
{80515}{}{09 - D.S.Brudge.ogg}
{80516}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80518}{}{The Burner}

# Area 805, Map 8051
{80520}{}{rs_burner_up1}
{80525}{}{29mark-morgan-curst.ogg}
{80526}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, electri1:5, electric:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80528}{}{The Burner}

# Area 805, Map 8052
{80530}{}{rs_burner_up2}
{80535}{}{10labone.ogg}
{80536}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80538}{}{The Burner}

# Area 805, Map 8053
{80540}{}{rs_burner_up3}
{80545}{}{27Lost_Knowledge.ogg}
{80546}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80548}{}{The Burner}

# Area 805, Map 8054
{80550}{}{rs_burner_up4}
{80555}{}{50NNM_radioluminescence.ogg}
{80556}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80558}{}{The Burner}

# Area 806, Map 8060
{80610}{}{rs3_7}
{80615}{}{05raider.ogg}
{80616}{}{cart:10, cart1:10, electri1:5, electric:5, drunkla1:20, drunklaf:20, animal1:20, animal:20, dogbark2:5, gustwin1:5, gustwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80618}{}{FairTrade Headquarters}

# Area 806, Map 8061
{80620}{}{rs3_7_up1}
{80625}{}{13carvrn.ogg}
{80626}{}{electri1:5, electric:5, drunkla1:20, drunklaf:20, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80628}{}{FairTrade Headquarters}

# Area 806, Map 8062
{80630}{}{rs3_7_up2}
{80635}{}{NNM_FS_06_Out_of_The_World.ogg}
{80636}{}{electri1:5, electric:5, cart:10, cart1:10, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80638}{}{FairTrade Headquarters}

# Area 806, Map 8063
{80640}{}{rs3_7_up3}
{80645}{}{UnderRail Expedition Main Theme.ogg}
{80646}{}{cart:10, cart1:10, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80648}{}{FairTrade Headquarters}

# Area 806, Map 8064
{80650}{}{rs3_7_up4}
{80655}{}{Crimson_soil.ogg}
{80656}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80658}{}{FairTrade Headquarters}

# Area 806, Map 8065
{80660}{}{rs3_7_up5}
{80665}{}{13carvrn.ogg}
{80666}{}{cart:10, cart1:10, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80668}{}{FairTrade Headquarters}

# Area 806, Map 8066
{80670}{}{rs3_7_up6}
{80675}{}{NNM_FS_06_Out_of_The_World.ogg}
{80676}{}{cart:10, cart1:10, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80678}{}{FairTrade Headquarters}

# Area 806, Map 8067
{80680}{}{rs3_7_up7}
{80685}{}{UnderRail Expedition Main Theme.ogg}
{80686}{}{cart:10, cart1:10, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80688}{}{FairTrade Headquarters}

# Area 806, Map 8068
{80690}{}{rs3_7_up8}
{80695}{}{Crimson_soil.ogg}
{80696}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80698}{}{FairTrade Headquarters}

# Area 806, Map 8069
{80700}{}{rs3_7_up9}
{80705}{}{13carvrn.ogg}
{80706}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80708}{}{FairTrade Headquarters}

# Area 807, Map 8070
{80710}{}{rs4_4}
{80715}{}{28Rangers-journey.ogg}
{80716}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80718}{}{Highway Bridge}

# Area 807, Map 8071
{80720}{}{rs4_4_up1}
{80725}{}{42NNM_ghost_town.ogg}
{80726}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80728}{}{Highway Bridge}

# Area 807, Map 8072
{80730}{}{rs4_4_up2}
{80735}{}{Xcentric-Noiz-Crotalinae.ogg}
{80736}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80738}{}{Highway Bridge}

# Area 807, Map 8073
{80740}{}{rs4_4_up3}
{80745}{}{04 - 12h. Dusk.ogg}
{80746}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80748}{}{Highway Bridge}

# Area 807, Map 8074
{80750}{}{rs4_4_up4}
{80755}{}{28Rangers-journey.ogg}
{80756}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80758}{}{Highway Bridge}

# Area 807, Map 8075
{80760}{}{rs4_4_up5}
{80765}{}{42NNM_ghost_town.ogg}
{80766}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80768}{}{Highway Bridge}

# Area 807, Map 8076
{80770}{}{rs4_4_up6}
{80775}{}{Xcentric-Noiz-Crotalinae.ogg}
{80776}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{80778}{}{Highway Bridge}

# Area 808, Map 8080
{80810}{}{rs4_5}
{80815}{}{The_Courier_Walks_Softly.ogg}
{80816}{}{pebble1:10, vulture:5, vulture1:5, clank:5, clank1:5, water:5, water1:5}
{80818}{}{Old Factor}

# Area 808, Map 8081
{80820}{}{rs4_5_up1}
{80825}{}{04Metallic Monks.ogg}
{80826}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80828}{}{Old Factory}

# Area 808, Map 8082
{80830}{}{rs4_5_up2}
{80835}{}{12junktn.ogg}
{80836}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80838}{}{Old Factory}

# Area 808, Map 8083
{80840}{}{rs4_5_up3}
{80845}{}{10labone.ogg}
{80846}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80848}{}{Old Factory}

# Area 808, Map 8084
{80850}{}{rs4_5_up4}
{80855}{}{NNM_FS_03_ Fogbound.ogg}
{80856}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80858}{}{Old Factory}

# Area 8808, Map 8085
{80860}{}{rs4_5_dn}
{80865}{}{Mark Morgan - Ambush Site Dam.ogg}
{80866}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{80868}{}{Subway}

# Area 809, Map 8090
{80910}{}{rs4_6}
{80915}{}{47NNM_nevada_theme.ogg}
{80916}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80918}{}{Pre-war Hospital}

# Area 809, Map 8091
{80920}{}{rs4_6_up1}
{80925}{}{04Metallic Monks.ogg}
{80926}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, electri1:5, electric:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80928}{}{Pre-war Hospital}

# Area 809, Map 8092
{80930}{}{rs4_6_up2}
{80935}{}{29mark-morgan-curst.ogg}
{80936}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80938}{}{Pre-war Hospital}

# Area 809, Map 8093
{80940}{}{rs4_6_up3}
{80945}{}{10labone.ogg}
{80946}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{80948}{}{Pre-war Hospital}

# Area 809, Map 8094
{80950}{}{rs4_6_up4}
{80955}{}{50NNM_radioluminescence.ogg}
{80956}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{80958}{}{Pre-war Hospital}

# Area 810, Map 8100
{81010}{}{rs4_7}
{81015}{}{13carvrn.ogg}
{81016}{}{drunkla1:20, drunklaf:20, dogbark2:5, gustwin1:5, gustwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81018}{}{Abandoned Project}

# Area 810, Map 8101
{81020}{}{rs4_7_up1}
{81025}{}{42NNM_ghost_town.ogg}
{81026}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81028}{}{Abandoned Project}

# Area 810, Map 8102
{81030}{}{rs4_7_up2}
{81035}{}{Xcentric-Noiz-Crotalinae.ogg}
{81036}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81038}{}{Abandoned Project}

# Area 810, Map 8103
{81040}{}{rs4_7_up3}
{81045}{}{04 - 12h. Dusk.ogg}
{81046}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81048}{}{Abandoned Project}

# Area 810, Map 8104
{81050}{}{rs4_7_up4}
{81055}{}{28Rangers-journey.ogg}
{81056}{}{clank:5, clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81058}{}{Abandoned Project}

# Area 810, Map 8105
{81060}{}{rs4_7_up5}
{81065}{}{42NNM_ghost_town.ogg}
{81066}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81068}{}{Abandoned Project}

# Area 810, Map 8106
{81070}{}{rs4_7_up6}
{81075}{}{Xcentric-Noiz-Crotalinae.ogg}
{81076}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81078}{}{Abandoned Project}

# Area 811, Map 8110
{81110}{}{rs5_4}
{81115}{}{07desert.ogg}
{81116}{}{clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81118}{}{Deserted Library}

# Area 811, Map 8111
{81120}{}{rs5_4_up1}
{81125}{}{Edwin Montgomery - Desert Nomads.ogg}
{81125}{}{Choices-And-Decisions.ogg}
{81126}{}{clank1:5, gustwin1:5, gustwind:5, bats1:10, bats:5, gntlwin1:5, vulture:5, vulture1:5}
{81128}{}{Deserted Library}

# Area 811, Map 8112
{81130}{}{rs5_4_up2}
{81135}{}{07desert.ogg}
{81136}{}{clank:5, clank1:5, booze:10, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81138}{}{Deserted Library}

# Area 811, Map 8113
{81140}{}{rs5_4_up3}
{81145}{}{NNM_FS_10_Jackals.ogg}
{81146}{}{seawind:10, seawind1:5, bangpip1:5, clank1:5, clang:5, clang1:5, neptune:5}
{81148}{}{Deserted Library}

# Area 811, Map 8114
{81150}{}{rs5_4_up4}
{81155}{}{07desert.ogg}
{81156}{}{clank:5, clank1:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81158}{}{Deserted Library}

# Area 812, Map 8120
{81210}{}{rs5_5}
{81215}{}{51NNM_ride_to_cheyenne.ogg}
{81216}{}{animal1:20, animal:20, drunklaf:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81218}{}{Cafe Of Broken Dreams}

# Area 812, Map 8121
{81220}{}{rs5_5_up1}
{81225}{}{12junktn.ogg}
{81226}{}{drunkla1:20, drunklaf:20, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81228}{}{Cafe Of Broken Dreams}

# Area 812, Map 8122
{81230}{}{rs5_5_up2}
{81235}{}{29mark-morgan-curst.ogg}
{81236}{}{drunkla1:20, drunklaf:20, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10}
{81238}{}{Cafe Of Broken Dreams}

# Area 812, Map 8123
{81240}{}{rs5_5_up3}
{81245}{}{27Lost_Knowledge.ogg}
{81246}{}{drunkla1:20, drunklaf:20, pebble:5, clang1:5, clank:5, clank1:5, pebble1:10}
{81248}{}{Cafe Of Broken Dreams}

# Area 812, Map 8124
{81250}{}{rs5_5_up4}
{81255}{}{The_Courier_Walks_Softly.ogg}
{81256}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5, clank1:5, pebble1:10, vulture:5, vulture1:5}
{81258}{}{Cafe Of Broken Dreams}

# Area 813, Map 8130
{81310}{}{rs5_6}
{81315}{}{Edwin Montgomery - Guardian Citadel.ogg}
{81316}{}{gustwind:5, bats1:10, bats:5, animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81318}{}{Police Station}

# Area 813, Map 8131
{81320}{}{rs5_6_up1}
{81325}{}{04Metallic Monks.ogg}
{81326}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81328}{}{Police Station}

# Area 813, Map 8132
{81330}{}{rs5_6_up2}
{81335}{}{10labone.ogg}
{81336}{}{clang1:5, clank:5, gntlwin1:5, mechpum1:5, mechpum:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81338}{}{Police Station}

# Area 813, Map 8133
{81340}{}{rs5_6_up3}
{81345}{}{50NNM_radioluminescence.ogg}
{81346}{}{clang1:5, clank:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, gntlwin1:5, gntlwind:5, clank1:5, pebble1:10, vulture:5, vulture1:55}
{81348}{}{Police Station}

# Area 813, Map 8134
{81350}{}{rs5_6_up4}
{81355}{}{10 - Dystopian Dreams.ogg}
{81356}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81358}{}{Police Station}

# Area 813, Map 8135
{81360}{}{rs5_6_up5}
{81365}{}{04Metallic Monks.ogg}
{81366}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81368}{}{Police Station}

# Area 813, Map 8136
{81370}{}{rs5_6_up6}
{81375}{}{10labone.ogg}
{81376}{}{clang1:5, clank:5, gntlwin1:5, mechpum1:5, mechpum:5, gntlwind:5, clank1:5, pebble1:10, vulture:5, vulture1:55}
{81378}{}{Police Station}

# Area 813, Map 8137
{81380}{}{rs5_6_up7}
{81385}{}{50NNM_radioluminescence.ogg}
{81386}{}{clang1:5, clank:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81388}{}{Police Station}

# Area 813, Map 8138
{81390}{}{rs5_6_up8}
{81395}{}{10 - Dystopian Dreams.ogg}
{81396}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81398}{}{Police Station}

# Area 813, Map 8139
{81400}{}{rs5_6_up9}
{81405}{}{04Metallic Monks.ogg}
{81406}{}{clang1:5, clank:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81408}{}{Police Station}

# Area 813, Map 8140
{81410}{}{rs5_6_up10}
{81415}{}{10labone.ogg}
{81416}{}{clang1:5, clank:5, gntlwin1:5, mechpum1:5, mechpum:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81418}{}{Police Station}

# Area 813, Map 8141
{81420}{}{rs5_6_up11}
{81425}{}{50NNM_radioluminescence.ogg}
{81426}{}{clang1:5, clank:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, gntlwin1:5, gntlwind:5,  clank1:5, pebble1:10, vulture:5, vulture1:55}
{81428}{}{Police Station}

# Area 815, Map 8150
{81510}{}{rs5_7}
{81515}{}{15 - Phagocyte Disaster.ogg}
{81515}{}{Breakdown.ogg}
{81516}{}{beltoll:5, beltol1:10, dogbark2:5, clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81518}{}{Cathedral}

# Area 815, Map 8151
{81520}{}{rs5_7_up1}
{81525}{}{08vats.ogg}
{81526}{}{gustwind:5, bats1:10, bats:5, dogbark2:5, clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81528}{}{Cathedral}

# Area 815, Map 8152
{81530}{}{rs5_7_up2}
{81535}{}{11chilrn.ogg}
{81536}{}{dogbark2:5, beltol1:10, clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81538}{}{Cathedral}

# Area 816, Map 8160
{81610}{}{rs4_2}
{81615}{}{Choices-And-Decisions.ogg}
{81615}{}{NNM_FS_09_Ghosts.ogg}
{81616}{}{gustwind:5, bats1:10, bats:5, dogbark2:5, clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81618}{}{Loom}

# Area 816, Map 8161
{81620}{}{rs4_2_up1}
{81625}{}{Breakdown.ogg}
{81625}{}{NNM_FS_09_Ghosts.ogg}
{81626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81628}{}{Loom}

# Area 816, Map 8162
{81630}{}{rs4_2_up2}
{81635}{}{NNM_FS_06_Out_of_The_World.ogg}
{81636}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81638}{}{Loom}

# Area 816, Map 8163
{81640}{}{rs4_2_up3}
{81645}{}{13carvrn.ogg}
{81646}{}{clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81648}{}{Loom}

# Area 817, Map 8170
{81710}{}{rs4_1}
{81715}{}{13 - Killadrone.ogg}
{81715}{}{Choices-And-Decisions.ogg}
{81716}{}{gustwind:5, bats1:10, bats:5, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81718}{}{Shops}

# Area 817, Map 8171
{81720}{}{rs4_1_up1}
{81725}{}{Edwin Montgomery - Desert Nomads.ogg}
{81726}{}{clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81728}{}{Shops}

# Area 817, Map 8172
{81730}{}{rs4_1_up2}
{81735}{}{42NNM_ghost_town.ogg}
{81736}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81738}{}{Shops}

# Area 818, Map 8180
{81810}{}{rs3_2}
{81815}{}{09glow.ogg}
{81816}{}{gustwind:5, bats1:10, bats:5, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81818}{}{Shopping Mall}

# Area 818, Map 8181
{81820}{}{rs3_2_up1}
{81825}{}{50NNM_radioluminescence.ogg}
{81826}{}{clang1:5, clank:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, vulture:5, vulture1:5}
{81828}{}{Shopping Mall}

# Area 818, Map 8182
{81830}{}{rs3_2_up2}
{81835}{}{45NNM_jammer.ogg}
{81836}{}{clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5, gustwind:5}
{81838}{}{Shopping Mall}

# Area 819, Map 8190
{81910}{}{rs2_2}
{81915}{}{NNM_FS_05_Collapse.ogg}
{81915}{}{Breakdown.ogg}
{81916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{81918}{}{Train Station}

# Area 819, Map 8191
{81920}{}{rs2_2_up1}
{81925}{}{50NNM_radioluminescence.ogg}
{81926}{}{clang1:5, clank:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, vulture:5, vulture1:5}
{81928}{}{Train Station}

# Area 819, Map 8192
{81930}{}{rs2_2_up2}
{81935}{}{45NNM_jammer.ogg}
{81936}{}{clank1:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5, gustwind:5 }
{81938}{}{Train Station}

# Area 820, Map 8200
{82010}{}{rs1_2}
{82015}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{82015}{}{House_heartbeat.ogg}
{82016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82018}{}{Platforms}

# Area 820, Map 8201
{82020}{}{rs1_2_dn}
{82025}{}{06vault.ogg}
{82026}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5,}
{82028}{}{Train Platforms}

# Area 820, Map 8202
{82030}{}{rs1_2_dn2}
{82035}{}{14necro.ogg}
{82035}{}{Grounded.ogg}
{82036}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{82038}{}{Train Platforms}

# Area 821, Map 8210
{82110}{}{rs6_5}
{82115}{}{53NNM_village.ogg}
{82116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, clank1:5, gvulture:5, vulture1:5, gustwind:5}
{82118}{}{Ruins}

# Area 822, Map 8220
{82210}{}{rs6_6}
{82215}{}{43NNM_high_wind.ogg}
{82216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82218}{}{Ruins}

# Area 823, Map 8230
{82310}{}{rs6_7}
{82315}{}{NNM_FS_11_Desert_Rangers.ogg}
{82316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82318}{}{Ruins}

# Area 824, Map 8240
{82410}{}{rs7_5}
{82415}{}{NNM_FS_14_Motel.ogg}
{82416}{}{pebble:5, clang1:5, clank:5, clank1:5, pebble1:10}
{82418}{}{University}

# Area 825, Map 8250
{82510}{}{rs7_6}
{82515}{}{18modoc.ogg}
{82516}{}{gntlwin1:5, gntlwind:5, animal1:20, animal:20, dogbark2:5, drunkla1:20, drunklaf:20, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82518}{}{Green Heaven}

# Area 826, Map 8260
{82610}{}{rs7_7}
{82615}{}{15shady.ogg}
{82616}{}{gntlwin1:5, gntlwind:5, animal1:20, animal:20, dogbark2:5, drunkla1:20, drunklaf:20, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82618}{}{Green Heaven}

# Area 826, Map 8261
{82620}{}{rs7_7_up1}
{82625}{}{NNM_FS_04_City_of_Phoenix.ogg}
{82626}{}{gntlwin1:5, gntlwind:5, animal1:20, animal:20, dogbark2:5, drunkla1:20, drunklaf:20, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82628}{}{East Green Heaven}

# Area 826, Map 8262
{82630}{}{rs7_7_up2}
{82635}{}{16follow.ogg}
{82636}{}{gntlwin1:5, gntlwind:5, animal1:20, animal:20, dogbark2:5, drunkla1:20, drunklaf:20, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82638}{}{East Green Heaven}

# Area 826, Map 8263
{82640}{}{rs7_7_up3}
{82645}{}{18modoc.ogg}
{82646}{}{gntlwin1:5, gntlwind:5, animal1:20, animal:20, dogbark2:5, drunkla1:20, drunklaf:20, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82648}{}{East Green Heaven}

# Area 827, Map 8270
{82710}{}{rs8_5}
{82715}{}{01hub.ogg}
{82716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82718}{}{Swamps}

# Area 827, Map 8271
{82720}{}{rs8_5_dn}
{82725}{}{Mark Morgan - Radiation Cloud.ogg}
{82726}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82728}{}{Swamps Bottom}

# Area 828, Map 8280
{82810}{}{rs1_1}
{82815}{}{24redd.ogg}
{82816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82818}{}{Mines}

# Area 828, Map 8281
{82820}{}{rs1_1_dn}
{82825}{}{08vats.ogg}
{82826}{}{bats1:10, bats:5, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{82828}{}{Mines}

# Area 829, Map 8290
{82910}{}{rs4_0}
{82915}{}{42NNM_ghost_town.ogg}
{82916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{82918}{}{Ruins}

# Area 830, Map 8300
{83010}{}{rs_sub}
{83015}{}{02Flame_of_the_Ancient_World.ogg}
{83016}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{83018}{}{Subway}

# Area 830, Map 8301
{83020}{}{rs_sub1}
{83025}{}{Mark Morgan - Radiation Cloud.ogg}
{83026}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10, ore:10, ore1:10}
{83028}{}{Subway}

# Area 830, Map 8302
{83030}{}{rs_sub2}
{83035}{}{last_hideout.ogg}
{83035}{}{Grounded.ogg}
{83036}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{83038}{}{Subway}

# Area 830, Map 8303
{83040}{}{rs_sub3}
{83045}{}{11chilrn.ogg}
{83046}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10, ore:10, ore1:10}
{83048}{}{Subway}

# Area 830, Map 8304
{83050}{}{rs_sub4}
{83055}{}{14necro.ogg}
{83055}{}{Grounded.ogg}
{83056}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{83058}{}{Subway}

# Area 830, Map 8305
{83060}{}{rs_sub5}
{83065}{}{NNM_FS_14_Motel.ogg}
{83066}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10, ore:10, ore1:10}
{83068}{}{Subway}

# Area 830, Map 8306
{83070}{}{rs_sub_dn}
{83075}{}{Mark Morgan - Ambush Site Dam.ogg}
{83075}{}{Grounded.ogg}
{83076}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{83078}{}{Subway}

# Area 830, Map 8307
{83080}{}{rs_sub3_dn}
{83085}{}{Mark Morgan - Ambush Site Dam.ogg}
{83086}{}{bangpip1:5, clang1:5, clank:5, clank1:5, pebble:5, pebble1:10, bats1:10, bats:5, steam:5, water:10}
{83088}{}{Subway}

# Area 831, Map 8310
{83110}{}{rs3_3}
{83115}{}{Breakdown.ogg}
{83115}{}{NNM_FS_14_Motel.ogg}
{83116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{83118}{}{Ruins}

#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{You have stumbled upon @lex who@.}
#{10000011}{}{You have stumbled upon @lex who@ and @lex player@.}
#{10000012}{}{You have stumbled upon @lex who@ and the @lex player@ gang.}
#{10000013}{}{You have stumbled upon @lex player@.}
#{10000014}{}{You've stumbled upon the @lex player@ gang.}
#{10000020}{}{Do you want to see @lex who@?}
#{10000021}{}{Do you want to see @lex who@ and @lex player@?}
#{10000022}{}{Do you want to see @lex who@ and the @lex player@ gang?}
#{10000023}{}{Do you want to see @lex player@?}
#{10000024}{}{Do you want to see the @lex player@ gang?}
