
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7
# Transit Name, (pid + 1) * 10 + 8 pm added

# Map 0, Global, base 10
{10}{}{World Map}
{15}{}{20car}
{15}{}{23world}
{15}{}{03 - A Way To Anywhere.ogg}
{15}{}{04 - 12h. Dusk.ogg}
{15}{}{08 - Blue Grass.ogg}
{15}{}{12 - Kill Klesk.ogg}
{16}{}{blank:100}

##### PERFECTION ####

# Area 1, Map 9
{100}{}{sandbox1_1}
{105}{}{34Cataclysm.ogg}
{106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{108}{}{Swamp}

# Area 2, Map 11
{120}{}{sandbox1_2}
{125}{}{under_1.ogg}
{126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{128}{}{West Cliff}

# Area 2, Map 12
{130}{}{sandbox1_2dn}
{135}{}{29mark-morgan-curst.ogg}
{136}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{138}{}{Cave}

# Area 2, Map 13
{140}{}{sandbox1_2dn2}
{145}{}{29mark-morgan-curst.ogg}
{146}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{148}{}{Lab Breakthrough}

# Area 3, Map 14
{150}{}{sandbox1_3}
{155}{}{03 - A Way To Anywhere.ogg}
{156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{158}{}{Summit}

# Area 3, Map 15
{160}{}{sandbox1_3dn}
{165}{}{58Tales_of_the_Past.ogg}
{166}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{168}{}{Train Tunnel}

# Area 4, Map 16
{170}{}{sandbox1_4}
{175}{}{14 - Organic Shadows.ogg}
{176}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{178}{}{East Cliff}

# Area 5, Map 18
{190}{}{sandbox1_5}
{195}{}{36E3_Among_the_Friends.ogg}
{196}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{198}{}{Northhill}

# Area 5, Map 19
{200}{}{perfect_lair}
{205}{}{Fresh_Meat.ogg}
{206}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{208}{}{Perfect Lair}

# Area 6, Map 20
{210}{}{sandbox2_1}
{215}{}{55NNM_wind_of_war.ogg}
{216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{218}{}{Swamp forest}

# Area 7, Map 22
{230}{}{sandbox2_2}
{235}{}{50NNM_radioluminescence.ogg}
{236}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{238}{}{South-west cliff}

# Area 7, Map 23
{240}{}{sandbox2_2dn}
{245}{}{58Tales_of_the_Past.ogg}
{246}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{248}{}{Charging station}

# Area 8, Map 24
{250}{}{sandbox2_3}
{255}{}{28Rangers-journey.ogg}
{256}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{258}{}{Perfection}

# Area 8, Map 25
{260}{}{sandbox2_3dn}
{265}{}{under_1.ogg}
{265}{}{41NNM_bonus.ogg}
{265}{}{42NNM_ghost_town.ogg}
{265}{}{43NNM_high_wind.ogg}
{265}{}{44NNM_improper_subdivision.ogg}
{265}{}{45NNM_jammer.ogg}
{265}{}{46NNM_line_of_policy.ogg}
{265}{}{47NNM_nevada_theme.ogg}
{265}{}{48NNM_new_vegas.ogg}
{265}{}{49NNM_radiationless.ogg}
{265}{}{50NNM_radioluminescence.ogg}
{265}{}{51NNM_ride_to_cheyenne.ogg}
{265}{}{52NNM_root_information.ogg}
{265}{}{53NNM_village.ogg}
{265}{}{54NNM_we_are_sorry.ogg}
{265}{}{55NNM_wind_of_war.ogg}
{266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{268}{}{Perfection}

# Area 9, Map 30
{310}{}{sandbox2_4}
{315}{}{38Into_The_ACID_Breach.ogg}
{316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{318}{}{South-east cliff}

# Area 10, Map 32
{330}{}{sandbox2_5}
{335}{}{37E1_Into_the_Tower.ogg}
{336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{338}{}{Hills}

# Area 11, Map 34
{350}{}{sandbox3_1}
{355}{}{44NNM_improper_subdivision.ogg}
{356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{358}{}{East forest}

# Area 12, Map 36
{370}{}{sandbox3_2}
{375}{}{49NNM_radiationless.ogg}
{376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{378}{}{The turn}

# Area 13, Map 38
{390}{}{sandbox3_3}
{395}{}{26A_Candle_in_the_Darkness.ogg}
{396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{398}{}{Substation}

# Area 13, Map 39
{400}{}{sandbox3_3dn}
{405}{}{45NNM_jammer.ogg}
{406}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{408}{}{Service rooms}

# Area 14, Map 40
{410}{}{sandbox3_4}
{415}{}{27Lost_Knowledge.ogg}
{416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{418}{}{Shops}

# Area 13, Map 41
{420}{}{sandbox3_4dn}
{425}{}{42NNM_ghost_town.ogg}
{426}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{428}{}{Old lab}

# Area 15, Map 42
{430}{}{sandbox3_5}
{435}{}{31old_earth.ogg}
{436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{438}{}{Outskirts}

# Area 15, Map 43
{440}{}{sandbox3_5dn}
{445}{}{27Lost_Knowledge.ogg}
{446}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{448}{}{Robotic Control}

# Area 16, Map 44
{450}{}{sandbox4_1}
{455}{}{54NNM_we_are_sorry.ogg}
{456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{458}{}{South-west forest}

# Area 16, Map 45
{460}{}{sandbox4_1dn}
{465}{}{05raider.mp3}
{466}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{468}{}{South-west forest}

# Area 17, Map 46
{470}{}{sandbox4_2}
{475}{}{41NNM_bonus.ogg}
{476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{478}{}{Intersection}

# Area 18, Map 48
{490}{}{sandbox4_3}
{495}{}{53NNM_village.ogg}
{496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{498}{}{Hill}

# Area 18, Map 49
{500}{}{sandbox4_3dn}
{505}{}{58the25vault.ogg}
{506}{}{pebble:5, pebble1:10}
{508}{}{Old mines}

# Area 19, Map 50
{510}{}{sandbox4_4}
{515}{}{45NNM_jammer.ogg}
{516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{518}{}{Ruins}

# Area 19, Map 51
{520}{}{sandbox4_4dn}
{525}{}{{26A_Candle_in_the_Darkness.ogg}
{526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{528}{}{Fort's basement}

# Area 20, Map 52
{530}{}{sandbox4_5}
{535}{}{47NNM_nevada_theme.ogg}
{536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{538}{}{Broadway}

# Area 21, Map 54
{550}{}{sandbox5_1}
{555}{}{57SHK_sinless_From_Seattle.ogg}
{556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{558}{}{South forest}

# Area 22, Map 56
{570}{}{sandbox5_2}
{575}{}{52NNM_root_information.ogg}
{576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{578}{}{Motel}

# Area 23, Map 58
{590}{}{sandbox5_3}
{595}{}{42NNM_ghost_town.ogg}
{596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{598}{}{Drain}

# Area 24, Map 60
{610}{}{sandbox5_4}
{615}{}{51NNM_ride_to_cheyenne.ogg}
{616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{618}{}{Camping sight}

# Area 25, Map 62
{630}{}{sandbox5_5}
{635}{}{43NNM_high_wind.ogg}
{636}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{638}{}{Base Camp}

# Area 26, Map 64
{650}{}{perfection_ext}
{655}{}{UnderRail Expedition Main Theme.ogg}
{656}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{658}{}{Tunnels}

# Area 26, Map 68
{690}{}{perfection_ext4}
{695}{}{UnderRail Expedition Main Theme.ogg}
{696}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{698}{}{Chem. plant}

# Area 27, Map 69
{700}{}{sandbox_bos}
{705}{}{07desert.ogg}
{706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{708}{}{Boneyard}

# Area 27, Map 70
{710}{}{sandbox_bos_dn1}
{715}{}{29mark-morgan-curst.ogg}
{716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{718}{}{Basement}

# Area 27, Map 71
{720}{}{sandbox_bos_dn2}
{725}{}{04Metallic Monks.ogg}
{726}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{728}{}{"Helheim" compound}

# Area 27, Map 72
{730}{}{sandbox_bos_dn3}
{735}{}{mscTimestream.ogg}
{736}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{738}{}{"Helheim" compound Tech level}

# Area 28, Map 73
{740}{}{sandbox0_2}
{745}{}{UnderRail Expedition Main Theme.ogg}
{746}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{748}{}{The Gorge}

# Area 28, Map 74
{750}{}{sandbox0_2dn}
{755}{}{UnderRail Expedition Main Theme.ogg}
{756}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{758}{}{The Gorge Cave}

##### TECH_MAPS #####

# Area 92, Map 92
{930}{}{startloc}
{935}{}{}
{936}{}{}
{938}{}{Activation}

# Area 93, Map 93
{940}{}{dreamloc}
{945}{}{}
{946}{}{}
{948}{}{Dream}

##### EVENTS #####

# Area 50, Map 100
{1010}{}{event4_hill2}
{1015}{}{F1_Drums_of_Battle.ogg}
{1016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1018}{}{Old ruins}

# Area 51, Map 101
{1020}{}{event2_slavers_out}
{1025}{}{F3_The_Rain_of_Steel.ogg}
{1026}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1028}{}{Rock}

# Area 51, Map 102
{1030}{}{event2_slavers_in}
{1035}{}{F7_Against_the_Odds.ogg}
{1036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1038}{}{Rangers' camp}

##### RIVERDALE #####

# Area 52, Map 103
{1040}{}{fort_riverdale}
{1045}{}{Out_of_Business.ogg}
{1045}{}{The_Courier_Walks_Softly.ogg}
{1045}{}{Under_the_Stars_Cut.ogg}
{1046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1048}{}{Fort Riverdale}

# Area 52, Map 104
{1050}{}{fort_riverdale_dn}
{1055}{}{Deeper_and_Darker.ogg}
{1056}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1058}{}{Fort Riverdale - underground}

# Area 52, Map 105
{1060}{}{fort_riverdale_up1}
{1065}{}{51NNM_ride_to_cheyenne.ogg}
{1066}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1068}{}{Fort Riverdale2}

# Area 52, Map 106
{1070}{}{fort_riverdale_up2}
{1075}{}{08 - Blue Grass.ogg}
{1076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1078}{}{Fort Riverdale3}

# Area 53, Map 107
{1080}{}{riverdale1_2}
{1085}{}{NNM_FS_16_One_Way.ogg}
{1086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1088}{}{Road}

# Area 54, Map 109
{1100}{}{riverdale1_3}
{1105}{}{44NNM_improper_subdivision.ogg}
{1106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1108}{}{Coast}

# Area 55, Map 111
{1120}{}{riverdale2_2}
{1125}{}{NNM_FS_03_ Fogbound.ogg}
{1126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1128}{}{Bridge}

# Area 56, Map 113
{1140}{}{riverdale2_3}
{1145}{}{43NNM_high_wind.ogg}
{1146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1148}{}{Cliff}

# Area 57, Map 115
{1160}{}{riverdale3_1}
{1165}{}{50NNM_radioluminescence.ogg}
{1166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1168}{}{Ore mines}

# Area 57, Map 117
{1180}{}{riverdale3_1_mine1}
{1185}{}{08vats.mp3}
{1186}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1188}{}{Copper mine}

# Area 57, Map 118
{1190}{}{riverdale3_1_mine2}
{1195}{}{09glow.mp3}
{1196}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1198}{}{Iron mine}

# Area 52, Map 119
{1200}{}{fort_riverdale_dn2}
{1205}{}{Deeper_and_Darker.ogg}
{1206}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1208}{}{Fort Riverdale - tunnel}

# Area 52, Map 120
{1210}{}{fort_riverdale_dn3}
{1215}{}{02Flame_of_the_Ancient_World.ogg}
{1216}{}{{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}}
{1218}{}{Fort Riverdale - crypt}

# Area 60, Map 123
{1240}{}{riverdale4_1}
{1245}{}{52NNM_root_information.ogg}
{1246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1248}{}{Lead Mine}

# Area 60, Map 125
{1260}{}{riverdale4_1_mine1}
{1265}{}{07desert.ogg}
{1266}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1268}{}{Lead Mine}

# Area 61, Map 126
{1270}{}{riverdale5_2}
{1275}{}{55NNM_wind_of_war.ogg}
{1276}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1278}{}{Hills}

# Area 62, Map 128
{1290}{}{riverdale5_3}
{1295}{}{NNM_FS_12_Casa_Grande.ogg}
{1296}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1298}{}{Beach}

# Area 63, Map 130
{1310}{}{riverdale6_1}
{1315}{}{NNM_FS_14_Motel.ogg}
{1316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1318}{}{Old Mine}

# Area 63, Map 132
{1330}{}{riverdale6_1_mine1}
{1335}{}{NNM_FS_10_Jackals.ogg}
{1336}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1338}{}{Goldshtein's Mine}

# Area 64, Map 133
{1340}{}{riverdale6_2}
{1345}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1346}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1348}{}{Ruins}

# Area 65, Map 135
{1360}{}{riverdale6_3}
{1365}{}{NNM_FS_05_Collapse.ogg}
{1366}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1368}{}{Cemetery}

# Area 65, Map 136
{1370}{}{riverdale6_3dn}
{1375}{}{11chilrn.ogg}
{1376}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1378}{}{Catacombs}

# Area 66, Map 137
{1380}{}{riverdale_dogs_motel}
{1385}{}{City_of_the_Fallen-The_Hourglass.ogg}
{1385}{}{City_of_the_fallen-Hour_of_Destiny.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Hour.ogg}
{1385}{}{City_of_the_Fallen-Darkest_Before_the_Dawn.ogg}
{1386}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1388}{}{Dogs Motel}

# Area 67, Map 139
{1400}{}{riverdale2_1}
{1405}{}{58Tales_of_the_Past.ogg}
{1406}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1408}{}{Fishing camp}

# Area 67, Map 140
{1410}{}{riverdale2_1dn}
{1415}{}{NNM_FS_15_Out-of-Service.ogg}
{1416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1418}{}{Fishing camp, cave}

# Area 68, Map 141
{1420}{}{riverdale1_1}
{1425}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{1426}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1428}{}{West Slope}

# Area 69, Map 143
{1440}{}{riverdale0_1}
{1445}{}{34Cataclysm.ogg}
{1446}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1448}{}{Toxic pit}

# Area 69, Map 144
{1450}{}{toxic_pit}
{1455}{}{38Into_The_ACID_Breach.ogg}
{1456}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1458}{}{Toxic pit, cave}

# Area 70, Map 146
{1470}{}{riverdale0_2}
{1475}{}{26A_Candle_in_the_Darkness.ogg}
{1476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1478}{}{Gorge, South}

# Area 71, Map 148
{1490}{}{riverdale0_3}
{1495}{}{57SHK_sinless_From_Seattle.ogg}
{1496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1498}{}{The Lair of Death}

# Area 71, Map 149
{1500}{}{lair_of_death}
{1505}{}{Fresh_Meat.ogg}
{1506}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1508}{}{The Lair of Death, cave}

# Area 72, Map 151
{1520}{}{riverdale_canyon}
{1525}{}{NNM_FS_16_One_Way.ogg}
{1526}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1528}{}{Canyon}

# Area 73, Map 153
{1540}{}{riverdale_up_3_1}
{1545}{}{NNM_FS_14_Motel.ogg}
{1546}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1548}{}{Tribe's grave}

# Area 73, Map 154
{1550}{}{riverdale_up_3_1dn}
{1555}{}{10labone.mp3}
{1556}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1558}{}{Tribal grave - temple}

# Area 74, Map 155
{1560}{}{riverdale_up_3_2}
{1565}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{1566}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1568}{}{Intersection}

# Area 75, Map 157
{1580}{}{riverdale_up_3_3}
{1585}{}{NNM_FS_04_City_of_Phoenix.ogg}
{1586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1588}{}{Road to Shady}

# Area 76, Map 159
{1600}{}{riverdale_up_2_1}
{1605}{}{49NNM_radiationless.ogg}
{1606}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1608}{}{West cliff}

##### TECH_MAPS #####

# Area 95, Map 170
{1710}{}{Deadloc}
{1715}{}{}
{1716}{}{}
{1718}{}{Purgatory}

##### RIVERDALE_CONTINUE ####

# Area 77, Map 172
{1730}{}{riverdale_up_2_2}
{1735}{}{NNM_FS_10_Jackals.ogg}
{1736}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1738}{}{Hounds' Motel}

# Area 78, Map 174
{1750}{}{riverdale_up_2_3}
{1755}{}{NNM_FS_12_Casa_Grande.ogg}
{1756}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1758}{}{Abandoned mine}

# Area 79, Map 176
{1770}{}{riverdale7_1}
{1775}{}{29mark-morgan-curst.ogg}
{1776}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1778}{}{Industrial sector}

# Area 80, Map 178
{1790}{}{riverdale7_2}
{1795}{}{NNM_FS_05_Collapse.ogg}
{1796}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1798}{}{Center}

# Area 81, Map 180
{1810}{}{riverdale7_3}
{1815}{}{NNM_FS_06_Out_of_The_World.ogg}
{1816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1818}{}{Residential area}

# Area 81, Map 181
{1820}{}{riverdale7_3_mine1}
{1825}{}{NNM_FS_14_Motel.ogg}
{1826}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{1828}{}{Worked-out mine}

# Area 82, Map 183
{1840}{}{riverdale8_2}
{1845}{}{NNM_FS_15_Out-of-Service.ogg}
{1846}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1848}{}{Forest of Bones}

##### POSEIDON #####

# Area 110, Map 185
{1860}{}{tanker_deck0}
{1865}{}{50NNM_radioluminescence.ogg}
{1866}{}{gntlwin1:5, gntlwind:5, gustwin1:5, gustwind:5, seagull:10, seagull1:10, seawind:5, seawind1:5, waves:15, waves1:15}
{1868}{}{Upper deck}

# Area 110, Map 186
{1870}{}{tanker_deck1}
{1875}{}{01hub.ogg}
{1876}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, laughte1:5, laughter:5, water:5, water1:5, waves:5, waves1:5}
{1878}{}{Trading decks}

# Area 110, Map 187
{1880}{}{tanker_deck2}
{1885}{}{akiss.mp3}
{1886}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{1888}{}{Bar deck}

# Area 110, Map 188
{1890}{}{tanker_deck3}
{1895}{}{06 - Cluster Decay.ogg}
{1896}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{1898}{}{Engineer deck}

# Area 110, Map 189
{1900}{}{tanker_deck4}
{1905}{}{29mark-morgan-curst.ogg}
{1906}{}{animal:10; bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, steam:10, steam1:10, water:5, water1:5}
{1908}{}{The Pit}

# Area 110, Map 190
{1910}{}{tanker_str0}
{1915}{}{27Lost_Knowledge.ogg}
{1916}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1918}{}{Tower0}

# Area 110, Map 191
{1920}{}{tanker_str1}
{1925}{}{27Lost_Knowledge.ogg}
{1926}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1928}{}{Tower1}

# Area 110, Map 192
{1930}{}{tanker_str2}
{1935}{}{27Lost_Knowledge.ogg}
{1936}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1938}{}{Tower2}

# Area 110, Map 193
{1940}{}{tanker_str3}
{1945}{}{27Lost_Knowledge.ogg}
{1946}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1948}{}{Tower3}

# Area 110, Map 194
{1950}{}{tanker_str4}
{1955}{}{27Lost_Knowledge.ogg}
{1956}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{1958}{}{Tower4}

# Area 110, Map 195
{1960}{}{tanker_sub1}
{1965}{}{29mark-morgan-curst.ogg}
{1966}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}
{1968}{}{Subdeck 1}

##### RIVERDALE_CONTINUE ####

# Area 83, Map 196
{1970}{}{riverdale8_2}
{1975}{}{black_dawn_1.ogg}
{1976}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1978}{}{Blossom}

# Area 83, Map 187
{1980}{}{riverdale8_2up}
{1985}{}{09glow.mp3}
{1986}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{1988}{}{Institute - 2nd floor}

##### NCR LOCATIONS #####

# Area 111, Map 200
{2010}{}{NCR}
{2015}{}{01hub.mp3}
{2016}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2018}{}{NCR}

##### RENO LOCATIONS #####

# Area 112, Map 201
{2020}{}{new_reno}
{2025}{}{19reno.mp3}
{2026}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2028}{}{New Reno}

##### Frisco ####

# Area 114, Map 221
{2220}{}{stop2_frisco1_2}
{2225}{}{31old_earth.ogg}
{2226}{}{brdchir1:5, brdchirp:5, gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15}
{2228}{}{San-Francisco Port}

# Area 117, Map 224
{2250}{}{stop2_frisco2_2}
{2255}{}{39SHK_Heoi.ogg}
{2256}{}{animal1:10, animal:10, water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2258}{}{San-Francisco Center}

# Area 118, Map 226
{2270}{}{stop2_frisco2_3}
{2275}{}{56SHK_Prosperity.ogg}
{2276}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2278}{}{San-Francisco Hotel}

# Area 118, Map 227
{2280}{}{stop2_frisco2_3dn}
{2285}{}{21sf.mp3}
{2286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2288}{}{San-Francisco Hotel basement}

# Area 118, Map 228
{2290}{}{stop2_frisco2_3up}
{2295}{}{40SHK_Club88.ogg}
{2296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2298}{}{San-Francisco Hotel Club}

# Area 118, Map 229
{2300}{}{stop2_frisco2_3up2}
{2305}{}{21sf.mp3}
{2306}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2308}{}{San-Francisco Hotel 2nd floor and 2nd floors}

# Area 118, Map 230
{2310}{}{stop2_frisco2_3up3}
{2315}{}{21sf.mp3}
{2316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2318}{}{San-Francisco Hotel 3d floors}

# Area 118, Map 231
{2320}{}{stop2_frisco2_3up4}
{2325}{}{21sf.mp3}
{2326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{2328}{}{San-Francisco Hotel 4th Hotel floor}

##### MORE_RIVERDALE #####

# Area 130, Map 250
{2510}{}{riverdale_up_1_1}
{2515}{}{07desert.mp3}
{2516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2518}{}{Forest tribe}

# Area 131, Map 252
{2530}{}{riverdale_canyon_3}
{2535}{}{07desert.mp3}
{2536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2538}{}{Radar station}

# Area 132, Map 254
{2550}{}{riverdale_canyon_5}
{2555}{}{NNM_FS_15_Out-of-Service.ogg}
{2556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2558}{}{Miners' town - West}

# Area 133, Map 256
{2570}{}{riverdale_canyon_5}
{2575}{}{NNM_FS_15_Out-of-Service.ogg}
{2576}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2578}{}{Miners Town - East}

# Area 133, Map 257
{2580}{}{miner_town_cave_01}
{2585}{}{NNM_FS_14_Motel.ogg}
{2586}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2588}{}{Miners' Town - Mine}

# Area 133, Map 258
{2590}{}{miner_town_cave_02}
{2595}{}{NNM_FS_14_Motel.ogg}
{2596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2598}{}{Uranium mine}

# Area 134, Map 261
{2620}{}{riverdale0_4}
{2625}{}{49NNM_radiationless.ogg}
{2626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2628}{}{East slope}

# Area 135, Map 263
{2640}{}{riverdale0_5}
{2645}{}{NNM_FS_04_City_of_Phoenix.ogg}
{2646}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2648}{}{Gorge}

# Area 136, Map 265
{2660}{}{riverdale1_4}
{2665}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{2666}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2668}{}{Devil's Island}

# Area 137, Map 267
{2680}{}{riverdale1_5}
{2685}{}{NNM_FS_16_One_Way.ogg}
{2686}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2688}{}{Foothills}

# Area 138, Map 269
{2700}{}{riverdale_up_0_1}
{2705}{}{29mark-morgan-curst.ogg}
{2706}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2708}{}{Bog}

# Area 139, Map 271
{2720}{}{riverdale_up_0_2}
{2725}{}{09glow.mp3}
{2726}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{2728}{}{Old church}

##### SILVERLAKE #####

# Area 200, Map 300
{3010}{}{silverlake_quarry}
{3015}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{3016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3018}{}{Quarry}

# Area 200, Map 301
{3020}{}{silverlake_quarry_mine1}
{3025}{}{09glow.mp3}
{3026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3028}{}{Iron Mine}

# Area 200, Map 302
{3030}{}{silverlake_quarry_mine2}
{3035}{}{NNM_FS_14_Motel.ogg}
{3036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3038}{}{Copper Mine}

# Area 201, Map 303
{3040}{}{silverlake_mine}
{3045}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3048}{}{Uranium Mine}

# Area 201, Map 305
{3060}{}{uranium_fever}
{3065}{}{29mark-morgan-curst.ogg}
{3066}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3068}{}{Uranium Mine Inside}

# Area 202, Map 306
{3070}{}{silverlake}
{3075}{}{Xcentric-Noiz-Crotalinae.ogg}
{3076}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3078}{}{Silverlake}

# Area 202, Map 307
{3080}{}{silverlake_dn}
{3085}{}{NNM_FS_15_Out-of-Service.ogg}
{3086}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3088}{}{Silverlake Underground}

# Area 202, Map 308
{3090}{}{silverlake_up}
{3095}{}{48NNM_new_vegas.ogg}
{3096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3098}{}{Silverlake Up}

# Area 203, Map 309
{3100}{}{silverlake_downtown}
{3105}{}{NNM_FS_12_Casa_Grande.ogg}
{3106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3108}{}{Silverlake Downtown}

# Area 204, Map 311
{3120}{}{silverlake_ruin1}
{3125}{}{29mark-morgan-curst.ogg}
{3126}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3128}{}{Warehouses}

# Area 205, Map 313
{3140}{}{silverlake_wasteland}
{3145}{}{under_1.ogg}
{3146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3148}{}{Trailer Park}

# Area 206, Map 315
{3160}{}{silverlake_crossroads}
{3165}{}{43NNM_high_wind.ogg}
{3166}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3168}{}{Crossroads}

# Area 204, Map 317
{3180}{}{silverlake_waterplant}
{3185}{}{02 - Into The Dust.ogg}
{3186}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3188}{}{Waterplant}

# Area 205, Map 319
{3200}{}{silverlake_ruin2}
{3205}{}{PathofExileTheBellyOfTheBeast.ogg}
{3206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3208}{}{Paradise Avenue}

# Area 209, Map 321
{3220}{}{silverlake_hive}
{3225}{}{PathofExileTheBellyOfTheBeast.ogg}
{3226}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3228}{}{Spider Hive}

# Area 210, Map 323
{3240}{}{silverlake_road2}
{3245}{}{07desert.mp3}
{3246}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3248}{}{Highway}

# Area 211, Map 325
{3260}{}{silverlake_hill}
{3265}{}{49NNM_radiationless.ogg}
{3266}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3268}{}{Hills}

# Area 212, Map 327
{3280}{}{silverlake_ruin3}
{3285}{}{54NNM_we_are_sorry.ogg}
{3286}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3288}{}{Coal Mine}

# Area 212, Map 328
{3290}{}{silverlake_ruin3_mine}
{3295}{}{54NNM_we_are_sorry.ogg}
{3296}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3298}{}{Coal Mine In}

# Area 213, Map 330
{3310}{}{silverlake_radiotower}
{3315}{}{UnderRail Expedition Main Theme.ogg}
{3316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3318}{}{Old Radiotower}

# Area 213, Map 331
{3320}{}{silverlake_radiotower_dn}
{3325}{}{27Lost_Knowledge.ogg}
{3326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3328}{}{Old Radiotower basement}

# Area 214, Map 332
{3330}{}{silverlake_road_south1}
{3335}{}{02 - Into The Dust.ogg}
{3336}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3338}{}{South Interstate}

# Area 215, Map 334
{3350}{}{silverlake_road_south2}
{3355}{}{05raider.mp3}
{3356}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3358}{}{Road to Elbrus}

# Area 216, Map 336
{3370}{}{silverlake_elbrus}
{3375}{}{NNM_FS_11_Desert_Rangers.ogg}
{3376}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3378}{}{Elbrus Outpost}

# Area 218, Map 338
{3390}{}{silverlake_radio_desert}
{3395}{}{NNM_FS_06_Out_of_The_World.ogg}
{3396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3398}{}{Desert}

# Area 219, Map 340
{3410}{}{silverlake_shop}
{3415}{}{13 - Killadrone.ogg}
{3416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3418}{}{Ruined mall}

# Area 220, Map 342
{3430}{}{silverlake_dump_mount}
{3435}{}{12junktn.mp3}
{3436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3438}{}{Junkyard}

# Area 221, Map 344
{3450}{}{silverlake_ranch}
{3455}{}{28Rangers-journey.ogg}
{3456}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3458}{}{Hacienda}

# Area 221, Map 345
{3460}{}{silverlake_ranch_dn}
{3465}{}{City_of_the_Fallen-The_Hourglass.ogg}
{3466}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3468}{}{Hacienda Cave}

# Area 222, Map 346
{3470}{}{silverlake_gas_road}
{3475}{}{57SHK_sinless_From_Seattle.ogg}
{3476}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3478}{}{Road to "GasCO"}

# Area 223, Map 348
{3490}{}{silverlake_gas}
{3495}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3496}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3498}{}{"GasCO" Ruins}

# Area 224, Map 350
{3510}{}{silverlake_hill_road}
{3515}{}{05raider.mp3}
{3516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3518}{}{Hillside Road}

# Area 225, Map 352
{3530}{}{silverlake_space_port}
{3535}{}{30 - Clockwork.ogg}
{3536}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3538}{}{Launch Site}

# Area 226, Map 354
{3550}{}{silverlake_shuttle}
{3555}{}{38Into_The_ACID_Breach.ogg}
{3556}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3558}{}{Shuttle}

# Area 226, Map 355
{3560}{}{silverlake_shuttle_inside}
{3565}{}{34Cataclysm.ogg}
{3566}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5}
{3568}{}{Shuttle Inside}

# Area 226, Map 356
{3570}{}{silverlake_lab1}
{3575}{}{49NNM_radiationless.ogg}
{3576}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{3578}{}{X-01 level 1}

# Area 226, Map 557
{3580}{}{silverlake_lab2}
{3585}{}{49NNM_radiationless.ogg}
{3586}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{3588}{}{X-01 level 2}

# Area 227, Map 358
{3590}{}{wood_road1}
{3595}{}{47NNM_nevada_theme.ogg}
{3596}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3598}{}{Gates of the Heart}

# Area 227, Map 359
{3600}{}{wood_road_turn}
{3605}{}{34Cataclysm.ogg}
{3606}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3608}{}{Turn}

# Area 227, Map 360
{3610}{}{wood_road2}
{3615}{}{50NNM_radioluminescence.ogg}
{3616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3618}{}{Scout post "Alpha"}

# Area 227, Map 361
{3620}{}{wood_road3}
{3625}{}{PathofExileTheBellyOfTheBeast.ogg}
{3626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3628}{}{Church}

# Area 227, Map 362
{3630}{}{wood_road3_dn}
{3635}{}{42NNM_ghost_town.ogg}
{3636}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3638}{}{Church basement}

# Area 227, Map 363
{3640}{}{wood_road4}
{3645}{}{PathofExileTheBellyOfTheBeast.ogg}
{3646}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3648}{}{Jaeger's House}

# Area 227, Map 364
{3650}{}{wood_road_outpost}
{3655}{}{Crimson_soil.ogg}
{3656}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3658}{}{Outpost "Black Crow"}

# Area 227, Map 365
{3660}{}{wolferin}
{3665}{}{30 - Clockwork.ogg}
{3666}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3668}{}{X-01 East Entrance}

# Area 227, Map 366
{3670}{}{wolferin_in}
{3675}{}{41NNM_bonus.ogg}
{3676}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3678}{}{X-01 East Entrance Bunker}

##### NEWTON #####

# Area 280, Map 380
{3810}{}{intro6}
{3815}{}{Memories of the Lost (Main Title) - Endless Space 2 Original Soundtrack.ogg}
{3816}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, fixstill:5, seawind:10, seawind1:5, waves:15, waves1:15}
{3818}{}{Temple of Control, 3rd floor. Conference hall.}

##### RDR_EVENT #####

# Area 281, Map 384
{3850}{}{event_frost_camp}
{3855}{}{05raider.mp3}
{3856}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{3858}{}{Camp in the desert.}

# Area 298, Map 398
{3990}{}{rebel_hideout}
{3995}{}{Underrail Expedition O.S.T. - Lemuria Outside.ogg}
{3996}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{3998}{}{Underground}

# Area 299, Map 399
{4000}{}{raiders_cave}
{4005}{}{05raider.ogg}
{4006}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4008}{}{Raiders Cave}

##### TECH_MAPS #####

# Area 300, Map 400
{4010}{}{hell}
{4015}{}{33DOOM.ogg}
{4016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3, ore:2, ore1:2, pebble:2, pebble1:2, seagull:5, seagull1:5, seawind:5, seawind1:5, waves:15, waves1:15, pebble:25, pebble1:15, ore:10, ore1:10}
{4018}{}{HELL}

##### TNF_MAPS #####

# Area 357, Map 491
{4920}{}{junk_new}
{4925}{}{57SHK_sinless_From_Seattle.ogg}
{4926}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{4928}{}{Scrapheap}

# Area 357, Map 492
{4930}{}{junk_new_dn}
{4935}{}{07desert.ogg}
{4936}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{4938}{}{Scrapheap,underground}

# Area 358, Map 493
{4940}{}{lake}
{4945}{}{NNM_FS_12_Casa_Grande.ogg}
{4946}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4948}{}{Phoenix, level 0}

# Area 359, Map 494
{4950}{}{phoenix_0}
{4955}{}{14necro.ogg}
{4956}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{4958}{}{Phoenix, level 0}

# Area 359, Map 495
{4960}{}{phoenix_1}
{4965}{}{22vcity.ogg}
{4966}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{4968}{}{Phoenix, level 1}

#=============CLINTON===================

# Area 360, Map 500
{5010}{}{clinton_center}
{5015}{}{Save_room2.ogg}
{5016}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5018}{}{Central District}

# Area 360, Map 501
{5020}{}{clinton_center_dn1}
{5025}{}{last_hideout.ogg}
{5026}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5028}{}{Central Shelter}

# Area 360, Map 502
{5030}{}{clinton_center_dn2}
{5035}{}{NNM_FS_16_One_Way.ogg}
{5036}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{5038}{}{Station}

# Area 360, Map 503
{5040}{}{clinton_center_up}
{5045}{}{48NNM_new_vegas.ogg}
{5046}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{5048}{}{Second Floor}

# Area 361, Map 504
{5050}{}{clinton1_1}
{5055}{}{black_dawn_1.ogg}
{5056}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5058}{}{Warehouses}

# Area 362, Map 506
{5070}{}{clinton1_2}
{5075}{}{52NNM_root_information.ogg}
{5076}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5078}{}{Substation}

# Area 363, Map 508
{5090}{}{clinton1_3}
{5095}{}{06 - Cluster Decay.ogg}
{5096}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5098}{}{Shops}

# Area 364, Map 510
{5110}{}{clinton1_4}
{5115}{}{NNM_FS_12_Casa_Grande.ogg}
{5116}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5118}{}{Docks}

# Area 365, Map 512
{5130}{}{clinton2_1}
{5135}{}{46NNM_line_of_policy.ogg}
{5136}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5138}{}{Checkpoint}

# Area 366, Map 514
{5150}{}{clinton2_2}
{5155}{}{red_life_1.ogg}
{5156}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5158}{}{Gas Station}

# Area 366, Map 515
{5160}{}{clinton2_2_dn}
{5165}{}{NNM_FS_03_ Fogbound.ogg}
{5166}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{5168}{}{Gas Station dn}

# Area 367, Map 516
{5170}{}{clinton2_3}
{5175}{}{NNM_FS_15_Out-of-Service.ogg}
{5176}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5178}{}{City Hall}

# Area 367, Map 517
{5180}{}{clinton2_3_dn}
{5185}{}{Sleepless Ruins.ogg}
{5186}{}{clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5}
{5188}{}{Telecom Center}

# Area 368, Map 518
{5190}{}{clinton2_4}
{5195}{}{Save_room1.ogg}
{5196}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5198}{}{Library}

# Area 369, Map 520
{5210}{}{clinton3_1}
{5215}{}{NNM_FS_05_Collapse.ogg}
{5216}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5218}{}{Convoy}

# Area 370, Map 522
{5230}{}{clinton3_4}
{5235}{}{Deeper_and_Darker.ogg}
{5236}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5238}{}{East Side}

# Area 371, Map 524
{5250}{}{clinton4_1}
{5255}{}{31old_earth.ogg}
{5256}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5258}{}{Police Department}

# Area 372, Map 526
{5270}{}{clinton4_4}
{5275}{}{58Tales_of_the_Past.ogg}
{5276}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5278}{}{Crossroads}

# Area 372, Map 527
{5280}{}{clinton4_4_dn}
{5285}{}{under_1.ogg}
{5286}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{5288}{}{Clinton Mine}

# Area 373, Map 528
{5290}{}{clinton5_1}
{5295}{}{secrets_from_river.ogg}
{5296}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5298}{}{Rail Crossing}

# Area 374, Map 530
{5310}{}{clinton5_2}
{5315}{}{26A_Candle_in_the_Darkness.ogg}
{5316}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5318}{}{Downtown}

# Area 375, Map 532
{5330}{}{clinton5_3}
{5335}{}{26A_Candle_in_the_Darkness.ogg}
{5336}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5338}{}{Clinton Park}

# Area 376, Map 534
{5350}{}{clinton5_4}
{5355}{}{42NNM_ghost_town.ogg}
{5356}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5358}{}{Excavation}

# Area 377, Map 536
{5370}{}{clinton5_4}
{5375}{}{Crimson_soil.ogg}
{5376}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{5378}{}{Highway}

##### ELKFALLS_SESSION #####

# Area 400, Map 600
{6010}{}{vbbox_town}
{6015}{}{Crimson_soil.ogg}
{6016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{6018}{}{Elks Falls}

##### VAULT66_SESSION #####

# Area 420, Map 643
{6440}{}{vault66_dn1}
{6445}{}{31old_earth.ogg}
{6446}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6448}{}{Vault 66, Entrance}

# Area 420, Map 644
{6450}{}{vault66_dn2}
{6455}{}{27Lost_Knowledge.ogg}
{6456}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6458}{}{Vault 66, Living Blocks}

# Area 420, Map 645
{6460}{}{vault66_dn3}
{6465}{}{29mark-morgan-curst.ogg}
{6466}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6468}{}{Vault 66, Vault Command Center}

# Area 420, Map 646
{6470}{}{vault66_dn4}
{6475}{}{06 - Cluster Decay.ogg}
{6476}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{6478}{}{Vault 66, Industrial Level}

##### CARAVAN #####

# Area 450, Map 700
{7010}{}{caravan_dest_n1}
{7015}{}{01hub.ogg}
{7016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7018}{}{Caravan Camp}

# Area 451, Map 701
{7020}{}{bridge_road_ns2}
{7025}{}{05raider.ogg}
{7026}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7028}{}{Caravan Road}

# Area 452, Map 702
{7030}{}{desert_road_ns1}
{7035}{}{07desert.ogg}
{7036}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7038}{}{Caravan Road}

# Area 453, Map 703
{7040}{}{desert_road_ns2}
{7045}{}{23world.ogg}
{7046}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7048}{}{Caravan Road}

# Area 454, Map 704
{7050}{}{forest_road_ns2}
{7055}{}{03wrldmp.ogg}
{7056}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{7058}{}{Caravan Road}

################################## CLINTON NEW ##################################
# Area 498, Map 4994
{49950}{}{clinton6_0}
{49955}{}{NNM_FS_14_Motel.ogg}
{49956}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{49958}{}{Old Mine}

# Area 498, Map 4995
{49960}{}{clinton6_0_dn}
{49965}{}{NNM_FS_10_Jackals.ogg}
{49966}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{49968}{}{Old Working Mine}

# Area 498, Map 4996
{49970}{}{clinton_lab1}
{49975}{}{31old_earth}
{49976}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{49978}{}{Lab Level 1}

# Area 498, Map 4997
{49980}{}{clinton_lab2}
{49985}{}{27Lost_Knowledge.ogg}
{49986}{}bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{49988}{}{Lab Level 2}

# Area 499, Map 4998
{49990}{}{clinton6_1}
{49995}{}{45NNM_jammer.ogg}
{49996}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{49998}{}{West Coast}

# Area 500, Map 5000
{50010}{}{clinton6_2}
{50015}{}{45NNM_jammer.ogg}
{50016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50018}{}{Ruins}

# Area 500, Map 5001
{50020}{}{clinton6_2dn}
{50025}{}{26A_Candle_in_the_Darkness.ogg}
{50026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{50028}{}{Fort Basement}

# Area 501, Map 5010
{50110}{}{clinton6_3}
{50115}{}{53NNM_village.ogg}
{50116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50118}{}{Hill}

# Area 501, Map 5012
{50130}{}{clinton6_3_dn2}
{50135}{}{58the25vault.ogg}
{50136}{}{pebble:5, pebble1:10}
{50138}{}{Old Mines}

# Area 502, Map 5020
{50210}{}{clinton6_4}
{50215}{}{47NNM_nevada_theme.ogg}
{50216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50218}{}{Broadway}

# Area 503, Map 5030
{50310}{}{clinton7_2}
{50315}{}{42NNM_ghost_town.ogg}
{50316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50318}{}{Drain}

# Area 504, Map 5040
{50410}{}{clinton7_3}
{50415}{}{51NNM_ride_to_cheyenne.ogg}
{50416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50418}{}{Camp}

# Area 505, Map 5050
{50510}{}{clinton7_4}
{50515}{}{43NNM_high_wind.ogg}
{50516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50518}{}{Center Camp}

# Area 506, Map 5060
{50610}{}{clinton8_2}
{50615}{}{43NNM_high_wind.ogg}
{50616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50618}{}{Forest}

# Area 507, Map 5070
{50710}{}{clinton8_3}
{50715}{}{12junktn.mp3}
{50716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50718}{}{Dump}

# Area 508, Map 5080
{50810}{}{clinton8_4}
{50815}{}{02 - Into The Dust.ogg}
{50816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50818}{}{Southern Motorway}

# Area 509, Map 5090
{50910}{}{clinton9_2}
{50915}{}{55NNM_wind_of_war.ogg}
{50916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{50918}{}{Forest}

# Area 510, Map 5100
{51010}{}{clinton9_3}
{51015}{}{27Lost_Knowledge.ogg}
{51016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51018}{}{Gas Station}

# Area 511, Map 5110
{51110}{}{clinton9_4}
{51115}{}{07desert.ogg}
{51116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51118}{}{Fork}

# Area 512, Map 5120
{51210}{}{clinton10_2}
{51215}{}{57SHK_sinless_From_Seattle.ogg}
{51216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51218}{}{Southern Forest}

# Area 513, Map 5130
{51310}{}{clinton10_3}
{51315}{}{12junktn.mp3}
{51316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51318}{}{Forest Road}

# Area 514, Map 5140
{51410}{}{clinton10_4}
{51415}{}{44NNM_improper_subdivision.ogg}
{51416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51418}{}{Forest}

# Area 515, Map 5150
{51510}{}{clinton11_2}
{51515}{}{49NNM_radiationless.ogg}
{51516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51518}{}{Cliff}

# Area 516, Map 5160
{51610}{}{clinton11_3}
{51615}{}{49NNM_radiationless.ogg}
{51616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51618}{}{Highway}

# Area 517, Map 5170
{51710}{}{clinton11_4}
{51715}{}{27Lost_Knowledge.ogg}
{51716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51718}{}{Forest}

# Area 518, Map 5180
{51810}{}{clinton12_2}
{51815}{}{NNM_FS_14_Motel.ogg}
{51816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51818}{}{Tribal Graves}

# Area 518, Map 5181
{51820}{}{clinton12_2_dn}
{51825}{}{10labone.mp3}
{51826}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{51828}{}{Tribal Graves, Temple}

# Area 519, Map 5190
{51910}{}{clinton12_3}
{51915}{}{NNM_FS_07_City_of_Flagstaff.ogg}
{51916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{51918}{}{Intersection}

# Area 520, Map 5200
{52010}{}{clinton12_4}
{52015}{}{NNM_FS_04_City_of_Phoenix.ogg}
{52016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52018}{}{Road to Frisco}

# Area 521, Map 5210
{52110}{}{clinton13_3}
{52115}{}{NNM_FS_16_One_Way.ogg}
{52116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52118}{}{Canyon}

# Area 522, Map 5220
{52210}{}{clinton13_4}
{52215}{}{07desert.mp3}
{52216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52218}{}{Radar Station}

# Area 523, Map 5230
{52310}{}{clinton13_6}
{52315}{}{NNM_FS_15_Out-of-Service.ogg}
{52316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52318}{}{Mining Town - West}

# Area 524, Map 5240
{52410}{}{clinton13_7}
{52415}{}{NNM_FS_15_Out-of-Service.ogg}
{52416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52418}{}{Mining City - East}

# Area 524, Map 5241
{52420}{}{clinton13_7_dn}
{52425}{}{NNM_FS_14_Motel.ogg}
{52426}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52428}{}{Mining Town - Mine}

# Area 524, Map 5242
{52430}{}{clinton13_7_dn_2}
{52435}{}{NNM_FS_14_Motel.ogg}
{52436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52438}{}{Uranium Mine}

# Area 525, Map 5250
{52510}{}{clinton14_2}
{52515}{}{34Cataclysm.ogg}
{52516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52518}{}{Toxic Pit}

# Area 525, Map 5251
{52520}{}{clinton14_2_dn}
{52525}{}{38Into_The_ACID_Breach.ogg}
{52526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{52528}{}{Toxic Pit, Cave}

# Area 526, Map 5260
{52610}{}{clinton14_3}
{52615}{}{26A_Candle_in_the_Darkness.ogg}
{52616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52618}{}{Ravine}

# Area 527, Map 5270
{52710}{}{clinton14_4}
{52715}{}{57SHK_sinless_From_Seattle.ogg}
{52716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52718}{}{Den of Death}

# Area 527, Map 5271
{52720}{}{clinton14_4_dn}
{52725}{}{Fresh_Meat.ogg}
{52726}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{52728}{}{Den of Death, Cave}

# Area 528, Map 5280
{52810}{}{clinton14_5}
{52815}{}{49NNM_radiationless.ogg}
{52816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52818}{}{Slope}

# Area 529, Map 5290
{52910}{}{clinton14_6}
{52915}{}{NNM_FS_04_City_of_Phoenix.ogg}
{52916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{52918}{}{Ravine}

# Area 530, Map 5300
{53010}{}{clinton15_2}
{53015}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{53016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53018}{}{Western Slope}

# Area 531, Map 5310
{53110}{}{clinton15_3}
{53115}{}{NNM_FS_16_One_Way.ogg}
{53116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53118}{}{Road}

# Area 532, Map 5320
{53210}{}{clinton15_4}
{53215}{}{44NNM_improper_subdivision.ogg}
{53216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53218}{}{Coast}

# Area 533, Map 5330
{53310}{}{clinton15_5}
{53315}{}{NNM_FS_08_La_Ciudad_del_Sol.ogg}
{53316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53318}{}{Devil's Island}

# Area 534, Map 5340
{53410}{}{clinton15_6}
{53415}{}{NNM_FS_16_One_Way.ogg}
{53416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53418}{}{Foothills}

# Area 535, Map 5350
{53510}{}{clinton16_2}
{53515}{}{58Tales_of_the_Past.ogg}
{53516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53518}{}{Fishing Camp}

# Area 535, Map 5351
{53520}{}{clinton16_2_dn}
{53525}{}{NNM_FS_15_Out-of-Service.ogg}
{53526}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{53528}{}{Fishing Camp, Cave}

# Area 536, Map 5360
{53610}{}{clinton16_3}
{53615}{}{NNM_FS_03_ Fogbound.ogg}
{53616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53618}{}{Bridge}

# Area 537, Map 5370
{53710}{}{clinton16_4}
{53715}{}{43NNM_high_wind.ogg}
{53716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53718}{}{Cliff}

# Area 538, Map 5380
{53810}{}{clinton17_3}
{53815}{}{NNM_FS_11_Desert_Rangers.ogg}
{53816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{53818}{}{Camp Elbrus}

# Area 539, Map 5390
{53910}{}{en_clinton_center}
{53915}{}{Best_Memories_Are_Hers.ogg}
{53915}{}{Someone_Lived_This.ogg}
{53916}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{53918}{}{Central District}

# Area 539, Map 5391
{53920}{}{en_clinton_center_dn1}
{53925}{}{last_hideout.ogg}
{53926}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{53928}{}{Central Shelter}

# Area 539, Map 5392
{53930}{}{en_clinton_center_dn2}
{53935}{}{NNM_FS_16_One_Way.ogg}
{53936}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5, pebble:5, pebble1:5}
{53938}{}{Station}

# Area 539, Map 5393
{53940}{}{en_clinton_center_up}
{53945}{}{48NNM_new_vegas.ogg}
{53946}{}{dice:5, dice1:5, potspan1:5, potspsns:5, laughte1:10, laughter:10, saloon:5, saloon1:5, shuffle:5, steam:5, steam1:5, water:5, water1:5, winner:5}
{53948}{}{Second Floor}

##### AZMA SESSION ####

# Area 540, Map 5400
{54010}{}{azm_session_1_2}
{54015}{}{11chilrn.ogg}
{54016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54018}{}{Greene Mine}

# Area 540, Map 5401
{54020}{}{azm_session_1_2dn}
{54025}{}{26A_Candle_in_the_Darkness.ogg}
{54026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{54028}{}{Greene Mine}

# Area 541, Map 5410
{54110}{}{azm_session_1_3}
{54115}{}{04Metallic Monks.ogg}
{54116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54118}{}{Greene Dale}

# Area 541, Map 5411
{54120}{}{azm_session_1_3dn}
{54125}{}{04Metallic Monks.ogg}
{54126}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{54128}{}{Greene Dale}

# Area 541, Map 5412
{54130}{}{azm_session_1_3up}
{54135}{}{04Metallic Monks.ogg}
{54136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54138}{}{Greene Dale}

# Area 542, Map 5420
{54210}{}{azm_session_1_5}
{54215}{}{13carvrn.ogg}
{54216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54218}{}{Abandoned Camp}

# Area 542, Map 5421
{54220}{}{azm_session_1_5dn}
{54225}{}{26A_Candle_in_the_Darkness.ogg}
{54226}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{54228}{}{Abandoned Camp}

# Area 543, Map 5430
{54310}{}{azm_session_2_2}
{54315}{}{secrets_from_river.ogg}
{54316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54318}{}{Radiotower}

# Area 543, Map 5431
{54320}{}{azm_session_2_2dn}
{54325}{}{secrets_from_river.ogg}
{54326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{54328}{}{Radiotower}

# Area 544, Map 5440
{54410}{}{azm_session_2_5}
{54415}{}{15shady.ogg}
{54416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54418}{}{Greene Swamps}

# Area 545, Map 5450
{54510}{}{azm_session_2_6}
{54515}{}{15shady.ogg}
{54516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54518}{}{Lake}

# Area 546, Map 5460
{54610}{}{azm_session_3_2}
{54615}{}{11chilrn.ogg}
{54616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54618}{}{Road to Radiotower}

# Area 547, Map 5470
{54710}{}{azm_session_3_3}
{54715}{}{Crimson_Soil.ogg}
{54716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54718}{}{Abandoned Gas Station}

# Area 548, Map 5480
{54810}{}{azm_session_3_4}
{54815}{}{Crimson_Soil.ogg}
{54816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54818}{}{Road to Green Dale}

# Area 549, Map 5490
{54910}{}{azm_session_3_5}
{54915}{}{13carvrn.ogg}
{54916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{54918}{}{Farm}

# Area 550, Map 5500
{55010}{}{azm_session_4_1}
{55015}{}{secrets_from_river.ogg}
{55016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55018}{}{Substation}

# Area 551, Map 5510
{55110}{}{azm_session_4_2}
{55115}{}{23world.ogg}
{55116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55118}{}{Quagmire}

# Area 552, Map 5520
{55210}{}{azm_session_4_3}
{55215}{}{Crimson_Soil.ogg}
{55216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55218}{}{Suburb}

# Area 553, Map 5530
{55310}{}{azm_session_4_4}
{55315}{}{Crimson_Soil.ogg}
{55316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55318}{}{Road}

# Area 554, Map 5540
{55410}{}{azm_session_4_5}
{55415}{}{23world.ogg}
{55416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55418}{}{Sawmill}

# Area 555, Map 5550
{55510}{}{azm_session_4_6}
{55515}{}{10labone.ogg}
{55516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55518}{}{Junkyard}

# Area 556, Map 5560
{55610}{}{azm_session_5_1}
{55615}{}{secrets_from_river.ogg}
{55616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55618}{}{Station Greene}

# Area 556, Map 5561
{55620}{}{azm_session_5_1dn}
{55625}{}{secrets_from_river.ogg}
{55626}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{55628}{}{Station Greene}

# Area 557, Map 5570
{55710}{}{azm_session_5_2}
{55715}{}{15shady.ogg}
{55716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55718}{}{Mirage}

# Area 558, Map 5580
{55810}{}{azm_session_5_3}
{55815}{}{10labone.ogg}
{55816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55818}{}{Trading Camp}

# Area 559, Map 5590
{55910}{}{azm_session_5_4}
{55915}{}{Save_room1.ogg}
{55916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{55918}{}{Outpost}

# Area 560, Map 5600
{56010}{}{azm_session_5_5}
{56015}{}{23world.ogg}
{56016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56018}{}{Forest}

# Area 561, Map 5610
{56110}{}{azm_session_5_6}
{56115}{}{14necro.ogg}
{56116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56118}{}{Abandoned Camp}

# Area 562, Map 5620
{56210}{}{azm_session_6_4}
{56215}{}{secrets_from_river.ogg}
{56216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56218}{}{Canyon}

# Area 563, Map 5630
{56310}{}{azm_session_7_3}
{56315}{}{10labone.ogg}
{56316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56318}{}{Portland Mine}

# Area 563, Map 5631
{56320}{}{azm_session_7_3dn}
{56325}{}{26A_Candle_in_the_Darkness.ogg}
{56326}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{56328}{}{Portland Mine}

# Area 564, Map 5640
{56410}{}{azm_session_7_4}
{56415}{}{08vats.ogg}
{56416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56418}{}{Crossroad}

# Area 565, Map 5650
{56510}{}{azm_session_7_5}
{56515}{}{10labone.ogg}
{56516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56518}{}{Town Ruins}

# Area 566, Map 5660
{56610}{}{azm_session_8_3}
{56615}{}{02Flame_of_the_Ancient_World.ogg}
{56616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56618}{}{Hole}

# Area 567, Map 5670
{56710}{}{azm_session_8_4}
{56715}{}{08vats.ogg}
{56716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56718}{}{Road to Portland}

# Area 568, Map 5680
{56810}{}{azm_session_8_5}
{56815}{}{22vcity.ogg}
{56816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56818}{}{Portland Abandonments}

# Area 569, Map 5690
{56910}{}{azm_session_9_3}
{56915}{}{02Flame_of_the_Ancient_World.ogg}
{56916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{56918}{}{Station}

# Area 570, Map 5700
{57010}{}{azm_Portland}
{57015}{}{19reno.ogg}
{57016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57018}{}{Fort Portland}

# Area 570, Map 5701
{57020}{}{azm_Portland_dn1}
{57025}{}{19reno.ogg}
{57026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{57028}{}{Fort Portland}

# Area 570, Map 5702
{57030}{}{azm_Portland_dn2}
{57035}{}{19reno.ogg}
{57036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{57038}{}{Fort Portland}

# Area 570, Map 5703
{57040}{}{azm_Portland_up}
{57045}{}{19reno.ogg}
{57046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57048}{}{Fort Portland}

# Area 571, Map 5710
{57110}{}{azm_session_10_3}
{57115}{}{10labone.ogg}
{57116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57118}{}{Ruins}

# Area 572, Map 5720
{57210}{}{azm_session_11_3}
{57215}{}{24redd.ogg}
{57216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57218}{}{Abandoned Mine}

# Area 572, Map 5721
{57220}{}{azm_session_11_3dn}
{57225}{}{26A_Candle_in_the_Darkness.ogg}
{57226}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{57228}{}{Abandoned Mine}

# Area 573, Map 5730
{57310}{}{azm_session_11_4}
{57315}{}{24redd.ogg}
{57316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57318}{}{Ruins near Portland}

# Area 574, Map 5740
{57410}{}{azm_session_11_5}
{57415}{}{02Flame_of_the_Ancient_World.ogg}
{57416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{57418}{}{Forgotten Mine}

##### BLAIRE #####

# Area 650, Map 5800
{58010}{}{blaire1_1}
{58015}{}{07desert.ogg}
{58016}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58018}{}{The Lake}

# Area 650, Map 5801
{58020}{}{blaire1_1_dn1}
{58025}{}{07desert.ogg}
{58026}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58028}{}{Lake, Down}

# Area 651, Map 5802
{58030}{}{blaire1_2}
{58035}{}{07desert.ogg}
{58036}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58038}{}{Northern Road}

# Area 651, Map 5803
{58040}{}{blaire1_2_dn1}
{58045}{}{07desert.ogg}
{58046}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58048}{}{Northern Road, Down}

# Area 652, Map 5804
{58050}{}{blaire1_3}
{58055}{}{07desert.ogg}
{58056}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58058}{}{Ruined Farms}

# Area 652, Map 5805
{58060}{}{blaire1_3_dn1}
{58065}{}{07desert.ogg}
{58066}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58068}{}{Ruined Farm, Down}

# Area 653, Map 5806
{58070}{}{blaire2_1}
{58075}{}{17arroyo.ogg}
{58076}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58078}{}{Western Cliffs}

# Area 653, Map 5807
{58080}{}{blaire2_1_cav1}
{58085}{}{13carvrn.ogg}
{58086}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58088}{}{Uranium Caves}

# Area 654, Map 5808
{58090}{}{blaire2_2}
{58095}{}{24redd.ogg}
{58096}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58098}{}{Blaire}

# Area 654, Map 5809
{58100}{}{blaire2_2_dn1}
{58105}{}{13carvrn.ogg}
{58106}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58108}{}{Blaire Mines Level 1}

# Area 654, Map 5810
{58110}{}{blaire2_2_dn2}
{58115}{}{13carvrn.ogg}
{58116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58118}{}{Blaire Mines Level 2}

# Area 654, Map 5811
{58120}{}{v16_1}
{58125}{}{13carvrn.ogg}
{58126}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58128}{}{Vault 16 Level 1}

# Area 654, Map 5812
{58130}{}{v16_2}
{58135}{}{18modoc.ogg}
{58136}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58138}{}{Vault 16 Level 2}

# Area 654, Map 5813
{58140}{}{v16_3}
{58145}{}{06vault.ogg}
{58146}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58148}{}{Vault 16 Level 3}

# Area 655, Map 5814
{58150}{}{blaire2_3}
{58155}{}{17arroyo.ogg}
{58156}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58158}{}{Eastern Cliffs}

# Area 655, Map 5815
{58160}{}{blaire2_3_cav1}
{58165}{}{13carvrn.ogg}
{58166}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58168}{}{Copper Caves}

# Area 655, Map 5816
{58170}{}{blaire2_3_cav2}
{58175}{}{13carvrn.ogg}
{58176}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{58178}{}{Coal Caves}

# Area 656, Map 5817
{58180}{}{blaire3_1}
{58185}{}{07desert.ogg}
{58186}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58188}{}{Desert}

# Area 657, Map 5818
{58190}{}{blaire3_2}
{58195}{}{07desert.ogg}
{58196}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58198}{}{Southern Road}

# Area 658, Map 5819
{58200}{}{blaire3_3}
{58205}{}{15shady.ogg}
{58206}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58208}{}{Red Rock}

# Area 658, Map 5820
{58210}{}{blaire3_3_dn1}
{58215}{}{15shady.ogg}
{58216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58218}{}{Red Rock, Down}

# Area 659, Map 5821
{58220}{}{v23_ext}
{58225}{}{07desert.ogg}
{58226}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58228}{}{Vault 23 Exterior}

# Area 659, Map 5822
{58230}{}{v23_1}
{58235}{}{02Flame_of_the_Ancient_World.ogg}
{58236}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58238}{}{Vault 23 Level 1}

# Area 659, Map 5823
{58240}{}{v23_2}
{58245}{}{09glow.ogg}
{58246}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58248}{}{Vault 23 Level 2}

# Area 659, Map 5824
{58250}{}{v23_3}
{58255}{}{14necro.ogg}
{58256}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58258}{}{Vault 23 Level 3}

# Area 660, Map 5825
{58260}{}{v28_ext}
{58265}{}{07desert.ogg}
{58266}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58268}{}{Vault 28 Exterior}

# Area 660, Map 5826
{58270}{}{v28_1}
{58275}{}{02Flame_of_the_Ancient_World.ogg}
{58276}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58278}{}{Vault 28 Level 1}

# Area 660, Map 5827
{58280}{}{v28_2}
{58285}{}{14necro.ogg}
{58286}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58288}{}{Vault 23 Level 2}

# Area 660, Map 5828
{58290}{}{v28_3}
{58295}{}{08vats.ogg}
{58296}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58298}{}{Vault 23 Level 3}

# Area 661, Map 5829
{58300}{}{dv_ext2}
{58305}{}{labone.ogg}
{58306}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58308}{}{Demo Vault Exterior 2}

# Area 662, Map 5830
{58310}{}{dv_ext1}
{58315}{}{labone.ogg}
{58316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58318}{}{Demo Vault Exterior 1}

# Area 662, Map 5831
{58320}{}{dv_1}
{58325}{}{09glow.ogg}
{58326}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58328}{}{Demo Vault Level 1}

# Area 662, Map 5832
{58330}{}{dv_2}
{58335}{}{09glow.ogg}
{58336}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58338}{}{Demo Vault Level 2}

# Area 662, Map 5833
{58340}{}{dv_3}
{58345}{}{09glow.ogg}
{58346}{}{bangpip1:5, bangpipe:5, clang:5, clang1:5, clank:5, clank1:5, coolant:5, fixstill:5, jupiter:5, mechpum1:5, mechpum:5, neptune:5, steam:5, steam1:5, water:5, water1:5}
{58348}{}{Demo Vault Level 3}

# Area 663, Map 5834
{58350}{}{cara_nw}
{58355}{}{07desert.ogg}
{58356}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58358}{}{Caravan Road North-West}

# Area 664, Map 5835
{58360}{}{cara_n1}
{58365}{}{07desert.ogg}
{58366}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58368}{}{Caravan Road North}

# Area 665, Map 5836
{58370}{}{cara_n2}
{58375}{}{07desert.ogg}
{58376}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58378}{}{Caravan Road North}

# Area 666, Map 5837
{58380}{}{cara_n3}
{58385}{}{07desert.ogg}
{58386}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58388}{}{Caravan Road North}

# Area 667, Map 5838
{58390}{}{cara_dest_n}
{58395}{}{01hub.0gg}
{58396}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58398}{}{Caravan Destination North}

# Area 668, Map 5839
{58400}{}{cara_w1}
{58405}{}{07desert.ogg}
{58406}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58408}{}{Caravan Road West}

# Area 669, Map 5840
{58410}{}{cara_w2}
{58415}{}{07desert.ogg}
{58416}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58418}{}{Caravan Road West}

# Area 670, Map 5841
{58420}{}{cara_w3}
{58425}{}{07desert.ogg}
{58426}{}{gntlwin1:3, gntlwind:3, gustwin1:3, gustwind:3}
{58428}{}{Caravan Road West}

# Area 671, Map 5842
{58430}{}{cara_dest_w}
{58435}{}{01hub.ogg}
{58436}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{58438}{}{Caravan Destination West}
##### SALTON #####
# Area 672, Map 5900
{59010}{}{seaton4_4}
{59015}{}{01hub.ogg}
{59016}{}{animal1:20, animal:20, dogbark2:5, pebble:5, pebble1:10, vulture:5, vulture1:5, gustwin1:3, gustwind:3}
{59018}{}{Bombay}

# Area 673, Map 5901
{59020}{}{seaton5_4}
{59025}{}{15shady.ogg}
{59026}{}{animal1:20, animal:20, dogbark2:5, pebble:5, pebble1:10, vulture:5, vulture1:5, gustwin1:3, gustwind:3}
{59028}{}{The Forest}

# Area 673, Map 5902
{59030}{}{seaton5_4dn}
{59035}{}{07desert.ogg}
{59036}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{59038}{}{The Forest - Under}

# Area 674, Map 5903
{59040}{}{seaton6_4}
{59045}{}{27Lost_Knowledge.ogg}
{59046}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59048}{}{The Farm}

# Area 675, Map 5904
{59050}{}{seaton4_3}
{59055}{}{03 - A Way To Anywhere.ogg}
{59056}{}{animal1:20, animal:20, dogbark2:5, pebble:5, pebble1:10, vulture:5, vulture1:5, gustwin1:3, gustwind:3}
{59058}{}{The Church}

# Area 676, Map 5905
{59060}{}{seaton5_3}
{59065}{}{14 - Organic Shadows.ogg}
{59066}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59068}{}{Scrap Swamp}

# Area 676, Map 5906
{59070}{}{seaton5_3dn}
{59075}{}{07desert.ogg}
{59076}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{59078}{}{Scrap Swamp - Under}

# Area 677, Map 5907
{59080}{}{seaton6_3}
{59085}{}{03wrldmp.ogg}
{59086}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{59088}{}{Gas Station}

# Area 678, Map 5908
{59090}{}{seaton4_2}
{59095}{}{07desert.ogg}
{59096}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{59098}{}{Wiston Coast - North}

# Area 679, Map 5909
{59100}{}{seaton5_2}
{59105}{}{05raider.mp3}
{59106}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59108}{}{The Hole}

# Area 680, Map 5910
{59110}{}{seaton6_2}
{59115}{}{14necro.ogg}
{59116}{}{animal:20, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}
{59118}{}{Wiston Hall}

# Area 680, Map 5911
{59120}{}{seaton6_2dn}
{59125}{}{07desert.ogg}
{59126}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{59128}{}{Wiston Hall - Under}

# Area 681, Map 5912
{59130}{}{seaton4_1}
{59135}{}{02Flame_of_the_Ancient_World.ogg}
{59136}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59138}{}{Wiston Coast - South}

# Area 682, Map 5913
{59140}{}{seaton5_1}
{59145}{}{02 - Into The Dust.ogg}
{59146}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59148}{}{Wiston Ruins}

# Area 683, Map 5914
{59150}{}{seaton6_1}
{59155}{}{07desert.ogg}
{59156}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{59158}{}{Wiston Mine}

# Area 683, Map 5915
{59160}{}{seaton6_1mine}
{59165}{}{07desert.ogg}
{59166}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{59168}{}{Wiston Mine - Proper}

# DUKE'S ASHHILL

# Area 700, Map 7000
{70010}{}{ashhill_1_2}
{70015}{}{07desert.ogg}
{70016}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70018}{}{Quarry}

# Area 701, Map 7010
{70110}{}{ashhill_2_1}
{70115}{}{07desert.ogg}
{70116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70118}{}{Mine}

# Area 702, Map 7020
{70210}{}{ashhill_2_2}
{70215}{}{07desert.ogg}
{70216}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70218}{}{Mine complex Admin.}

# Area 703, Map 7030
{70310}{}{ashhill_2_3}
{70315}{}{07desert.ogg}
{70316}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70318}{}{Miners settlement}

# Area 704, Map 7040
{70410}{}{ashhill_2_4}
{70415}{}{07desert.ogg}
{70416}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70418}{}{Ruins N-E}

# Area 705, Map 7050
{70510}{}{ashhill_2_5}
{70515}{}{07desert.ogg}
{70516}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70518}{}{Cliff N-E}

# Area 706, Map 7060
{70610}{}{ashhill_3_1}
{70615}{}{07desert.ogg}
{70616}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70618}{}{Nomads stop}

# Area 707, Map 7070
{70710}{}{ashhill_center}
{70715}{}{07desert.ogg}
{70716}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70718}{}{Ashhill}

# Area 708, Map 7080
{70810}{}{ashhill_3_4}
{70815}{}{07desert.ogg}
{70816}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70818}{}{Ruins E}

# Area 709, Map 7090
{70910}{}{ashhill_3_5}
{70915}{}{07desert.ogg}
{70916}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{70918}{}{Road E}

# Area 710, Map 7100
{71010}{}{ashhill_4_1}
{71015}{}{07desert.ogg}
{71016}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{71018}{}{Anthill}

# Area 711, Map 7110
{71110}{}{ashhill_4_4}
{71115}{}{07desert.ogg}
{71116}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{71118}{}{Ruins S-E}

# Area 712, Map 7120
{71210}{}{ashhill_5_2}
{71215}{}{07desert.ogg}
{71216}{}{water:10, water1:10, pebble:25, pebble1:15, ore:10, ore1:10}
{71218}{}{Road S}

# KHATUM'S SILVERDALE

# Area 715, Map 7150
{71510}{}{wood_outpost}
{71515}{}{NNM_FS_05_Collapse.ogg}
{71516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71518}{}{Shenjou Trading Outpost}

# Area 716, Map 7160
{71610}{}{sdale0_3}
{71615}{}{NNM_FS_16_One_Way.ogg}
{71616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71618}{}{Hive}

# Area 717, Map 7170
{71710}{}{wood_road5}
{71715}{}{07desert.ogg}
{71716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71718}{}{Forest road}

# Area 718, Map 7180
{71810}{}{sdale1_1}
{71815}{}{24redd.mp3}
{71816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71818}{}{Abandoned mine}

# Area 718, Map 7181
{71820}{}{sdale1_1_mine_no_entire}
{71825}{}{24redd.mp3}
{71826}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71828}{}{Abandoned mine}

# Area 719, Map 7190
{71910}{}{sdale1_2}
{71915}{}{17arroyo.ogg}
{71916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{71918}{}{Tribe}

# Area 720, Map 7200
{72010}{}{sdale1_3}
{72015}{}{07desert.ogg}
{72016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72018}{}{Toxic waste junkyard}

# Area 721, Map 7210
{72110}{}{sdale1_4}
{72115}{}{NNM_FS_16_One_Way.ogg}
{72116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72118}{}{Junkyard}

# Area 722, Map 7220
{72210}{}{sdale1_5}
{72215}{}{07desert.ogg}
{72216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72218}{}{Abandoned mine}

# Area 722, Map 7221
{72220}{}{sdale1_5_mine_no_entire}
{72225}{}{07desert.ogg}
{72226}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72228}{}{Abandoned mine}

# Area 723, Map 7230
{72310}{}{wood_road4}
{72315}{}{07desert.ogg}
{72316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72318}{}{Church in forest}

# Area 723, Map 7231
{72320}{}{wood_road4_dn}
{72325}{}{07desert.ogg}
{72326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72328}{}{Church in forest}

# Area 724, Map 7240
{72410}{}{sdale2_1}
{72415}{}{07desert.ogg}
{72416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72418}{}{Uplift to mine}

# Area 725, Map 7250
{72510}{}{sdale2_2}
{72515}{}{07desert.ogg}
{72516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72518}{}{Abandoned mine}

# Area 725, Map 7251
{72520}{}{sdale2_2_mine_no_entire}
{72525}{}{07desert.ogg}
{72526}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72528}{}{Abandoned mine}

# Area 726, Map 7260
{72610}{}{sdale2_3}
{72615}{}{NNM_FS_02_Villa.ogg}
{72616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72618}{}{Camp in the forest}

# Area 727, Map 7270
{72710}{}{sdale2_4}
{72715}{}{07desert.ogg}
{72716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72718}{}{Mountain ridge}

# Area 728, Map 7280
{72810}{}{wood_road3}
{72815}{}{30 - Clockwork.ogg}
{72816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72818}{}{Forest road}

# Area 729, Map 7290
{72910}{}{wood_road2}
{72915}{}{07desert.ogg}
{72916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{72918}{}{Forest road}

# Area 730, Map 7300
{73010}{}{sdale3_1}
{73015}{}{07desert.ogg}
{73016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73018}{}{Camp near lake}

# Area 731, Map 7310
{73110}{}{sdale3_2}
{73115}{}{NNM_FS_16_One_Way.ogg}
{73116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73118}{}{Hut on swamp}

# Area 732, Map 7320
{73210}{}{sdale3_3}
{73215}{}{07desert.ogg}
{73216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73218}{}{Silverdale cemetery}

# Area 733, Map 7330
{73310}{}{sdale3_4}
{73315}{}{08vats.ogg}
{73316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73318}{}{Trailer park}

# Area 733, Map 7331
{73320}{}{sdale3_4_mine_no_entire}
{73325}{}{08vats.ogg}
{73326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73328}{}{Trailer park}

# Area 734, Map 7340
{73410}{}{wood_oasis}
{73415}{}{07desert.ogg}
{73416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73418}{}{Oasis}

# Area 735, Map 7350
{73510}{}{wood_road1}
{73515}{}{07desert.ogg}
{73516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73518}{}{Crossroad}

# Area 736, Map 7360
{73610}{}{sdale4_1}
{73615}{}{NNM_FS_16_One_Way.ogg}
{73616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73618}{}{Bridge}

# Area 737, Map 7370
{73710}{}{sdale4_2}
{73715}{}{NNM_FS_16_One_Way.ogg}
{73716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73718}{}{Road to west}

# Area 738, Map 7380
{73810}{}{sdale_center}
{73815}{}{NNM_FS_16_One_Way.ogg}
{73816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73818}{}{Silverdale}

# Area 738, Map 7381
{73820}{}{sdale_center_up}
{73825}{}{NNM_FS_16_One_Way.ogg}
{73826}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73828}{}{Silverdale}

# Area 738, Map 7382
{73830}{}{sdale_center_dn}
{73835}{}{NNM_FS_16_One_Way.ogg}
{73836}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73838}{}{Silverdale}

# Area 739, Map 7390
{73910}{}{sdale4_5}
{73915}{}{NNM_FS_05_Collapse.ogg}
{73916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{73918}{}{Pre-war industrial district}

# Area 740, Map 7400
{74010}{}{wood_boloto2}
{74015}{}{43NNM_high_wind.ogg}
{74016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74018}{}{Swamp}

# Area 741, Map 7410
{74110}{}{wood_boloto}
{74115}{}{NNM_FS_16_One_Way.ogg}
{74116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74118}{}{Swamp}

# Area 742, Map 7420
{74210}{}{sdale5_1}
{74215}{}{43NNM_high_wind.ogg}
{74216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74218}{}{Bridge}

# Area 743, Map 7430
{74310}{}{sdale5_2}
{74315}{}{43NNM_high_wind.ogg}
{74316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74318}{}{Sawmill}

# Area 744, Map 7440
{74410}{}{sdale5_5}
{74415}{}{NNM_FS_16_One_Way.ogg}
{74416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74418}{}{Pre-war business center}

# Area 745, Map 7450
{74510}{}{sdale6_1}
{74515}{}{17arroyo.ogg}
{74516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74518}{}{Riverbed}

# Area 746, Map 7460
{74610}{}{sdale6_2}
{74615}{}{NNM_FS_16_One_Way.ogg}
{74616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74618}{}{Forest}

# Area 746, Map 7461
{74620}{}{sdale6_2_dn}
{74625}{}{NNM_FS_16_One_Way.ogg}
{74626}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74628}{}{Forest}

# Area 747, Map 7470
{74710}{}{sdale6_3}
{74715}{}{NNM_FS_16_One_Way.ogg}
{74716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74718}{}{Road to old shop}

# Area 748, Map 7480
{74810}{}{sdale6_4}
{74815}{}{NNM_FS_16_One_Way.ogg}
{74816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74818}{}{Abandoned shop}

# Area 749, Map 7490
{74910}{}{sdale6_5}
{74915}{}{04Metallic Monks.ogg}
{74916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{74918}{}{Pre-war residential}

# Area 750, Map 7500
{75010}{}{sdale6_6}
{75015}{}{13carvrn.ogg}
{75016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75018}{}{Railroad station}

# Area 750, Map 7501
{75020}{}{sdale6_6_dn}
{75025}{}{under_1.ogg}
{75026}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75028}{}{Railroad station}

# Area 751, Map 7510
{75110}{}{sdale7_3}
{75115}{}{13carvrn.ogg}
{75116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75118}{}{Crossroad}

# Area 752, Map 7520
{75210}{}{sdale7_4}
{75215}{}{NNM_FS_12_Casa_Grande.ogg}
{75216}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75218}{}{Pre-war pump station}

# Area 753, Map 7530
{75310}{}{sdale7_5}
{75315}{}{NNM_FS_16_One_Way.ogg}
{75316}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75318}{}{Pre-war residential}

# Area 753, Map 7531
{75320}{}{sdale7_5_mine_no_entire}
{75325}{}{NNM_FS_16_One_Way.ogg}
{75326}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75328}{}{Pre-war residential}

# Area 754, Map 7540
{75410}{}{sdale8_3}
{75415}{}{07desert.mp3}
{75416}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75418}{}{South road}

# Area 755, Map 7550
{75510}{}{sdale8_4}
{75515}{}{07desert.mp3}
{75516}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75518}{}{Mountain ridge}

# Area 756, Map 7560
{75610}{}{sdale9_3}
{75615}{}{07desert.mp3}
{75616}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75618}{}{South road}

# Area 757, Map 7570
{75710}{}{sdale9_4}
{75715}{}{NNM_FS_13 Garage_City.ogg}
{75716}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75718}{}{Radio station}

# Area 757, Map 7571
{75720}{}{sdale9_4_dn}
{75725}{}{NNM_FS_13 Garage_City.ogg}
{75726}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75728}{}{Radio station}

# Area 758, Map 7580
{75810}{}{sdale10_3}
{75815}{}{07desert.mp3}
{75816}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75818}{}{South road}

# Area 759, Map 7590
{75910}{}{sdale11_3}
{75915}{}{NNM_FS_16_One_Way.ogg}
{75916}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{75918}{}{Pre-war workshop}

# Area 760, Map 7600
{76010}{}{sdale12_3}
{76015}{}{NNM_FS_15_Out-of-Service.ogg}
{76016}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{76018}{}{Bridge}

# Area 760, Map 7601
{76020}{}{sdale12_3_mine_dn}
{76025}{}{NNM_FS_15_Out-of-Service.ogg}
{76026}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{76028}{}{Bridge}

# Area 760, Map 7602
{76030}{}{sdale12_3_mine_dn_2}
{76035}{}{NNM_FS_15_Out-of-Service.ogg}
{76036}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{76038}{}{Bridge}

# Area 761, Map 7610
{76110}{}{sdale13_3}
{76115}{}{Crimson_soil.ogg}
{76116}{}{animal1:20, animal:20, dogbark2:5, gntlwin1:5, gntlwind:5, pebble:5, pebble1:10, vulture:5, vulture1:5}
{76118}{}{Elbrus-13 Trading Outpost}

#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Location picture, (pid + 100) * 1000 + 20
# Tab picture, (pid + 100) * 1000 + 30
# Count entries, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3


#
# Worldmap Encounter messages
#

#{10000010}{}{You have stumbled upon @lex who@.}
#{10000011}{}{You have stumbled upon @lex who@ and @lex player@.}
#{10000012}{}{You have stumbled upon @lex who@ and the @lex player@ gang.}
#{10000013}{}{You have stumbled upon @lex player@.}
#{10000014}{}{You've stumbled upon the @lex player@ gang.}
#{10000020}{}{Do you want to see @lex who@?}
#{10000021}{}{Do you want to see @lex who@ and @lex player@?}
#{10000022}{}{Do you want to see @lex who@ and the @lex player@ gang?}
#{10000023}{}{Do you want to see @lex player@?}
#{10000024}{}{Do you want to see the @lex player@ gang?}
