# Created: 08.11.2007 03:40 Cvet
# Updated: 29.10.2008 23:18 Cvet

{1}{}{You've read empty papers.}
{2}{}{You were not able to read the papers.}
{3}{}{You've read nothing new.}
{4}{}{You can't remember anything you've just read.}
{5}{}{You forgot the useless information.}
{6}{}{Such things are hard to forget.}
{7}{}{You've finished writing on papers.}
{8}{}{You failed writing down your thoughts.}

#
# Format:
# Name - Number * 10
# Text - Number * 10 + 1


# 99999
# The last correct number, after which the text is taken from the database of player records.
# Holodisc for player records.
{999990}{}{Empty papers.}
{999991}{}{}
