# 17.10.2007 Cvet


{4}{}{%d. }
{5}{}{Current state: }

#
# Number
# Name
#

#
# Countring formulas:
#	Number * 1000 + Value (1-100) - The text that the player will have with the current param value.
#	Number * 1000 + 101 - The name of the quest tab.
#	Number * 1000 + 102 - A permanent description of the quest.


