# Skill raise
{15}{}{Skill @lex skill@ is increased by @lex value@ points}

# Generic messages
{510}{}{Yes} # Magic ball
{511}{}{No} # Magic ball
{520}{}{powders nose} # Cosmetic
{530}{}{smokes} # Cigarettes

# General interactive machines
{1000}{}{inserts money into machine}
{1001}{}{|0xFFFF00 Machine is locked.}
{1002}{}{opens the machine}

# Slots
{2001}{}{|0xFFFF00 There is no money left in the machine.}
{2002}{}{|0xFFFF00 There is not enough money in the machine to cover the bet.}
{2003}{}{|0xFFFF00 JACKPOT!!! @lex result@}
{2004}{}{|0xFFFF00 Win: @lex result@}
{2005}{}{|0xFF0000 Lose!}
{2006}{}{|0xFFFF00 You dont have enough money.}
{2007}{}{|0xFFFF00 Bet }

# Coinflip
{2050}{}{flips a coin: |0x7CFC00 Bermin|0xFF00FF .}
{2051}{}{flips a coin: |0x7CFC00 Buck|0xFF00FF .}

# Dice use
{2053}{}{rolls: |0x7CFC00 @lex result@|0xFF00FF .}

# Cards
{2054}{}{|0xFFFF00 The deck is empty!}
{2055}{}{|0xFFFF00 There are no cards in the deck!}
{2056}{}{draws: }
{2057}{}{deals a card}
{2058}{}{|0xFFFF00 You were delt a card.}
{2059}{}{shufles the deck}
{2060}{}{collects cards}
{2061}{}{|0xFFFF00 You can only add cards to this hand.}
{2062}{}{shows: }
{2063}{}{Your hand:  }

# Vending Machines
{2100}{}{collects goods}
{2101}{}{collects change}
{2102}{}{selects new item}

# Jukebox
{2150}{}{|0xFFFF00 You realize that the selected treck is not present!}
{2151}{}{|0xFFFF00 Seams like there is no change!}

# Terminal
{2200}{}{|0xFFFF00 You have blocked access to the terminal.}
{2201}{}{opens security card reciever}
{2202}{}{|0xFFFF00 The terminal does not accept this item!}
{2203}{}{selects the security card}
{2204}{}{disables security card}

# Combat
{2300}{}{|0xFFFF00 You can not fire from this weapon without windup to spin the barrels!}
{2301}{}{entangled}
{2302}{}{entangled}
{2303}{}{entangled}
{2304}{}{|0xFFFF00 Your weapon has missfired!}

# Taste
{6487}{}{\nHomebrew with taste of }
{6488}{}{cabbage}
{6489}{}{nuts}
{6490}{}{bread}
{6491}{}{paslena berries}
{6492}{}{mutated fruits}
{6493}{}{vanilla}
{6494}{}{corn}
{6495}{}{cookies}
{6496}{}{protein bar}
{6497}{}{candies}
{6498}{}{caramer}
{6499}{}{You smell liquid inside canteen to be:}

# St Peter
{6500}{}{Stop it, my son, it's useless.}
{6501}{}{There is a lot of filth in you.}
{6502}{}{I understand your pain. Calm down, child.}
{6503}{}{Anger destroys you, don't go on about it.}
{6504}{}{It's not an easy path for you, you're embittered.}
{6505}{}{Your anger is unfair. Stop it now.}

{6506}{}{It's not time yet, you can't pass.}
{6507}{}{Patience, my son, patience.}
{6508}{}{Your time hasn't come yet. I can't let you pass.}
{6509}{}{Don't rush there, you have a whole eternity ahead of you.}
{6510}{}{You've lived your whole life in a hurry, take a break at least for now.}

# Roulette
{7001}{}{zero}
{7002}{}{double zero}
{7003}{}{red}
{7004}{}{black}
{7005}{}{number }
{7006}{}{Your winnings: }
{7007}{}{Invalid number}
{7008}{}{Incorrect bid}
{7009}{}{Number accepted}
{7010}{}{Bid accepted}
{7011}{}{Current bid: @lex betsize@}
{7012}{}{You bet on the numbers:}
{7013}{}{@lex result@}
{7014}{}{Make your bet}

#Russian Roulette
{9000}{}{he lost at "Russian Roulette"@@his brains got blown out@@today is not his lucky day@@he shouldn't have agreed to this@@he splattered everything around with his blood@@he screamed and pulled the trigger, the scream was cut off...@@he shot himself@@he did not hesitate to splatter the area with his brains}
{9001}{}{the gun clicked, but nothing happens@@he almost shit himself, but nothing happened...@@he screamed as he pulled the trigger, but everything turned out ok!@@fortune smiled to him!@@he won at "Russian Roulette"@@LUCKY!@@he held his breath and pulled the trigger, but everything went fine}
{9002}{}{she lost at "Russian Roulette"@@she took her brains out@@today is not her day@@she shouldn't have agreed to this@@she poured her blood all over the place@@she screamed as she pulled the trigger, but the scream was cut off...@@she shot herself@@without hesitation, she splattered the area with her brains}
{9003}{}{the gun clicked, but nothing happened@@she almost shit herself, but nothing happened...@@she screamed and pulled the trigger, but everything turned out ok!@@fortune smiled on her@@she won at the "Russian Roulette"@@LUCKY@@she held her breath and pulled the trigger, but everything went fine}

#Resource Gathering
{9004}{}{picks a plant}
{9005}{}{|0xFFFF00 You haven't found anything useful.}
{9006}{}{You've collected:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800 .}
{9007}{}{|0x3CF800 .}
{9008}{}{|0xFFFF00 You've picked the plant during the wrong growth stage and decided to dump it away.}
{9009}{}{|0xFFFF00 You are too tired, take a rest.}
{9010}{}{|0xFFFF00 You must have a tool equipped in your hand.}
{9011}{}{|0xFFFF00 You are injured and can't perform the task.}
{9012}{}{|0xFFFF00 It was a good idea before you realized there is no juice left in the drill.}
{9013}{}{|0xFFFF00 The drill is too damaged.}
{9014}{}{|0xFFFF00 You have to kill your prey first.}
{9015}{}{|0xFFFF00 You can't skin this.}
{9016}{}{|0xFFFF00 There is nothing to skin.}
{9017}{}{|0xFFFF00 You've damaged the skin during the process.}
{9018}{}{|0xFFFF00 This tool is not good for chopping.}
{9019}{}{|0xFFFF00 There is nothing to chop, you have to uproot it.}
{9020}{}{You've crafted: }
{9021}{}{- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@}
{9022}{}{crafts something}

#ItemMovement
{9445}{}{|0xFFFF00 This is too heavy for you.}
{9446}{}{takes a card}
{9447}{}{takes armour}
{9448}{}{takes @lex proto@}
{9449}{}{takes weapon}
{9450}{}{takes ammo}
{9451}{}{takes something}
{9452}{}{|0xFFFF00 You have to move away in order to place an item.}
{9453}{}{|0xFFFF00 Moving the item to slot is restricted because the character model does not have required animations!}
{9454}{}{|0xFFFF00 Weapon in main hand is not supported by character animations, moved to inventory!}
{9455}{}{|0xFFFF00 Weapon in main hand is not supported by character animations, moved to inventory!}
{9456}{}{|0xFF00FF Synthesized voice: |0xF8F993 Identity recognized. Activation!}
{9457}{}{sound of reactor powering up}
{9458}{}{hides face}
{9459}{}{shows face}
{9460}{}{takes backpack}
{9461}{}{takes item}
{9462}{}{|0xFFFF00 You can't resist while your backpack is being taken away.}
{9463}{}{|0xFFFF00 You can't resist while your item is being taken away.}
{9464}{}{|0xFFFF00 You have taken a backpack.}
{9465}{}{|0xFFFF00 You have taken an item.}
{9466}{}{attempts to take armour}
{9467}{}{|0xFFFF00 You take everything you can from the victim.}
{9468}{}{|0xFFFF00 Someone is trying to remove your armour!}
{9469}{}{|0xFFFF00 You have taken the victim's armour.}
{9470}{}{|0xFFFF00 Your armour was removed.}
{9471}{}{|0xFFFF00 You have taken armour off the victim.}
{9472}{}{|0xFFFF00 You have partially taken armour off the victim.}

#Windup
{9476}{}{raises @lex proto@}
{9477}{}{lowers @lex proto@}
{9478}{}{raises fists}
{9479}{}{raises fists}
{9480}{}{raises fists}
{9481}{}{raises horns}
{9482}{}{raises stinger}
{9483}{}{grins}
{9484}{}{raises to full height}
{9485}{}{opens jaws}
{9486}{}{raises manipulators}
{9487}{}{raises claws}
{9488}{}{raises tentacles}
{9489}{}{opens mandible}
{9490}{}{looks upon you as if you were a mere insect}
{9491}{}{emits a stinger}
{9492}{}{roars loudly}
{9493}{}{opens pincers}
{9494}{}{emits a low roar}
{9495}{}{relaxes}

#Raising skills
{9496}{}{|0xFFFF00 You have become a real sex expert!}
{9497}{}{|0xFFFF00 You did not manage to raise your skill.}
{9498}{}{|0x3CF800 Skill: }
{9499}{}{|0x3CF800  is raised by }

#Accidental injuries
{9500}{}{|0xFFFF00 You've managed to avoid a terrible injury at the last moment, but still: \n}
{9501}{}{|0xFFFF00 You've recieved a heavy bruise as a result of your mistake.}
{9502}{}{|0xFFFF00 You've made a mistake and cut your hand.}
{9503}{}{|0xFFFF00 You've hit yourself with a tool and made a deep cut in your flesh.}
{9504}{}{|0xFFFF00 Because of a bad move you have received a serious production injury.}
{9505}{}{|0xFFFF00 You have received a deep brow cut as a result of your mistake.}

#Blood loss
{9510}{}{|0xFFFF00 You start feeling weak from heavy blood loss.}
{9511}{}{|0xFFFF00 You feel cold and weak, you slowly start to die from massive blood loss.}

#Vomiting
{9512}{}{|0xFFFF00 You feel sick...}
{9513}{}{vomits}
{9514}{}{|0xFFFF00 Seems like you are about to vomit...}

#Resurrection
{9520}{}{|0xFFFF00 You've used the item but it hasn't helped}
{9521}{}{|0xFFFF00 Your body survived but you health is significantly damaged.}
{9522}{}{|0xFFFF00 You realize that this will cause the patient to have a heart attack.}

#Food / drink
{9523}{}{the belly rumbles}
{9524}{}{licks dry lips}
{9525}{}{staggers}
{9526}{}{|0xFFFF00 The damage received is too high, you will die soon without outside medical help.}
{9527}{}{|0xFFFF00 You suffer from hunger.}
{9528}{}{|0xFFFF00 You suffer from dehydration.}
{9529}{}{|0xFFFF00 You no longer feel the taste of alcohol...}
{9530}{}{|0xFFFF00 You have become slower because of dehydration.}
{9531}{}{|0xFFFF00 You have become slower because of hunger.}
{9532}{}{|0xFFFF00 You've restored your strength.}
{9533}{}{drinks}
{9534}{}{You have drunk: |0xFFFF00 @lex proto@|0x3CF800 .}
{9535}{}{You lost: |0xFFFF00 @lex rad@|0x3CF800  rad.}
{9536}{}{You gained: |0xFFFF00 @lex poison@|0x3CF800  poison.}
{9537}{}{consumes @lex proto@}

#Dragging
{9540}{}{|0xFFFF00 You can't do that.}
{9541}{}{|0xFFFF00 The target must be prone or be dead!}
{9542}{}{|0xFFFF00 The target is too far away.}
{9543}{}{|0xFFFF00 The body is being dragged.}
{9544}{}{|0xFFFF00 You can't drag more than one body.}
{9545}{}{|0xFFFF00 You start dragging the body.}
{9546}{}{|0xFFFF00 You've dropped the body.}

#Dirt
{9550}{}{|0xFFFF00 Your look and stench start to disgust everyone around you. You better take a bath.}
{9551}{}{|0xFFFF00 You have stopped being repulsive.}

#Lie / stand
{9552}{}{|0xFFFF00 You don't have the strength to get up.}
{9553}{}{|0xFFFF00 You begin to get up.}
{9554}{}{|0xFFFF00 You are lying down.}

#Locks and lockpicking
{9600}{}{|0xFFFF00 An inserted key in front of you is preventing you from doing this.}
{9601}{}{|0xFFFF00 An inserted key from the other side is preventing you from doing this.}
{9602}{}{|0xFFFF00 You unlocked the door.}
{9603}{}{unlocks}
{9604}{}{|0xFFFF00 You locked the door.}
{9605}{}{locks}
{9606}{}{|0xFFFF00 You must close it first.}
{9607}{}{|0xFFFF00 The key does not match.}
{9608}{}{|0xFFFF00 Something is preventing the door from being closed.}
{9609}{}{|0xFFFF00 You require electronic lockpick.}
{9610}{}{|0xFFFF00 You are too far from target.}
{9611}{}{|0x606060 knock-knock}
{9612}{}{|0xFFFF00 You've knocked.}
{9613}{}{|0xFF0000 BANG}
{9614}{}{|0xFFFF00 The door is already open.}
{9615}{}{|0xFFFF00 There is no lock.}
{9616}{}{|0xFFFF00 You require a lockpick or a pin at least.}
{9617}{}{|0xFFFF00 The lockpick broke, it seams you did not properly remove it from the lock the last time.}
{9618}{}{takes key out of the lock}
{9619}{}{puts key in the lock}
{9620}{}{|0xFFFF00 You are too far away from the lock, your lockpicks break.}
{9621}{}{|0xFFFF00 You have successfully picked a lock.}
{9622}{}{|0xFFFF00 You carefully extract the lockpick.}
{9623}{}{|0xFFFF00 You skill is not enough to lock the door with a lockpick.}
{9624}{}{|0xFFFF00 The door is already locked.}
{9625}{}{|0xFFFF00 You locked the door.}
{9626}{}{|0xFFFF00 You removed the lock.}

#item taking
{9630}{}{resists}
{9631}{}{tries to take something from target}
{9632}{}{|0xFFFF00 You are too tired to take anything from the target.}

#decraft and repair
{9650}{}{|0xFFFF00 This item is not subject to deterioration.}
{9651}{}{|0xFF0000 You are injured and can't perform maintenance.}
{9652}{}{|0xFFFF00 This can't be repaired!}
{9653}{}{|0xFF0000 You are injured and can't de-craft the item.}
{9654}{}{completes disassembly}
{9655}{}{|0xFF0000 You lack the skill to do this.}
{9656}{}{completes repairing}
{9657}{}{|0xFFFF00 This armour already has an internal radio set.}
{9658}{}{completes installing radio set into the armour}
{9659}{}{|0xFFFF00 This armour can't be repainted.}
{9660}{}{|0xFF0000 You are injured and are unable to repaint the armour.}
{9661}{}{completes repainting the armour}
{9662}{}{|0xFF0000 You are injured and are unable to install the radio.}
{9663}{}{Required instrument: }
{9664}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9665}{}{Required parts: }
{9666}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9667}{}{You require to hold any of: }
{9668}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9669}{}{Acquired parts: }
{9670}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9671}{}{You've de-crafted |0xFFFF00 @lex proto@|0x3CF800 , gaining: }
{9672}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9673}{}{|0xFFFF00 You did not manage to install the radio!}
{9674}{}{|0x3CF800 You need the following skills:
 - |0xFFFF00 Science |0x3CF800  -  |0xFFFF00 150|0x3CF800 ,
 - |0xFFFF00 Repair |0x3CF800  -  |0xFFFF00 200|0x3CF800 .}


#Flasks and bottles
{9768}{}{|0xFFFF00 Your anatomy prevents you from opening the bottle!}
{9769}{}{|0xFFFF00 You have nothing to open the bottle with!}
{9770}{}{You have opened the bottle of |0xFFFF00" @lex proto@|0x3CF800.}
{9771}{}{opens the bottle}
{9772}{}{|0xFFFF00 You must hold the item!}
{9773}{}{|0xFFFF00 Try another way to fill the bottle.}
{9774}{}{|0xFFFF00 You have run out of bottles.}
{9775}{}{|0xFFFF00 You have poured out all water.}
{9776}{}{|0xFFFF00 Container is filled with something else.}
{9777}{}{fills @lex proto@}
{9778}{}{|0xFFFF00 You must hold the container in your hand.}
{9779}{}{|0xFFFF00 The container is empty.}
{9780}{}{pours out of @lex proto@}
{9781}{}{|0xFFFF00 Container is already filled up.}
{9782}{}{|0xFFFF00 You have filled up the container.}
{9783}{}{|0xFFFF00 Container is empty.}
{9784}{}{|0xFFFF00 There is no more water.}
{9785}{}{|0xFFFF00 You don't have a bottle in your hands.}
{9786}{}{|0xFFFF00 You have filled the bottle with water.}

#Smoking
{9787}{}{opens a pack of cigarettes}
{9788}{}{|0xFFFF00 There are no cigarettes left in the pack.}
{9789}{}{takes a cigarette out of the pack}
{9790}{}{|0xFFFF00 You need a fire source to light a cigarette.}
{9791}{}{|0xFFFF00 You can't smoke through a gas mask.}
{9792}{}{|0xFFFF00 You have to hold object in order to start smoking.}
{9793}{}{|0xFFFF00 Smoking pipe is empty.}
{9794}{}{|0xFFFF00 Smoking pipe has burned out.}
{9795}{}{|0xFFFF00 You fill the smoking pipe.}
{9796}{}{|0xFFFF00 You emptied the bag.}
{9797}{}{|0xFFFF00 You have to hold a smoking pipe in order to fill it.}
{9798}{}{|0xFFFF00 You taste tobacco.}
{9799}{}{|0xFFFF00 You taste fiveleaf.}

#Various Items
{9800}{}{takes a picture}
{9801}{}{removes ash}
{9802}{}{removes remains}
{9803}{}{wipes blood}
{9804}{}{|0xFFFF00 You have partially removed some remains.}
{9805}{}{|0xFFFF00 You have collected remains.}
{9806}{}{|0xFFFF00 You must have the musical instrument in your hand.}
{9807}{}{plays the flute}
{9808}{}{|0xFFFF00 Try digging closer to yourself.}
{9809}{}{|0xFFFF00 There is no sand in this spot.}
{9810}{}{|0xFFFF00 Input item description.}
{9811}{}{|0xFFFF00 It looks like you have no idea what to do with that.}
{9812}{}{|0xFFFF00 You have to take the item out of the container first!}
{9813}{}{|0xFFFF00 This item now has distinct description.}
{9814}{}{|0xFFFF00 You have removed all special features from the item.}
{9815}{}{lights the lamp}
{9816}{}{|0xFFFF00 You require a lighter to fire up the lamp!}
{9817}{}{|0xFFFF00 There is no oil in the lamp.}
{9818}{}{extinguishes the lamp}
{9819}{}{turns on the flashlight}
{9820}{}{|0xFFFF00 The flashlight has no charge left.}
{9821}{}{turns off the flashlight}
{9822}{}{ignites flare}
{9823}{}{extinguishes the flare}
{9824}{}{whips with a towel}
{9825}{}{whips with a dirty towel}
{9826}{}{washes the towel}
{9827}{}{replaces battery}
{9828}{}{fuels the lamp}
{9829}{}{|0xFFFF00 You did not manage to fit the item in the container.}
{9830}{}{Serial number: }

#Ropes and shackles
{9831}{}{|0xFFFF00 You can't free yourself this way.}
{9832}{}{|0xFFFF00 This won't help here.}
{9833}{}{frees the target}
{9834}{}{gets free}
{9835}{}{|0xFFFF00 You really require a crowbar.}
{9836}{}{frees the target from the snare}
{9837}{}{gets free from the snare}
{9838}{}{|0xFFFF00 You are free from the snare!}
{9839}{}{|0xFFFF00 The key does not fit.}
{9840}{}{|0xFFFF00 The bound is broken.}
{9841}{}{|0xFFFF00 This is pointless, the target is dead!}
{9842}{}{|0xFFFF00 Target already bound by similar item!}

{9843}{}{binds their hands with handcuffs}
{9844}{}{binds the subject's hands with handcuffs}
{9845}{}{|0xFFFF00 You have handcuffed yourself.}
{9846}{}{|0xFFFF00 Your hands are now bound by handcuffs!}
{9847}{}{|0xFFFF00 Your hands have been freed from the handcuffs.}
{9848}{}{takes their handcuffs off}
{9849}{}{takes the subject's handcuffs off}

{9850}{}{ties their hands}
{9851}{}{ties the subject}
{9852}{}{|0xFFFF00 You have tied up yourself.}
{9853}{}{|0xFFFF00 You have been tied up!}
{9854}{}{|0xFFFF00 Your hands have been untied.}
{9855}{}{cuts their bindings}
{9856}{}{cuts the subject's bindings}

{9857}{}{puts shackles around their leg}
{9858}{}{binds the subject's leg with shackles}
{9859}{}{|0xFFFF00 You have put shackles on yourself.}
{9860}{}{|0xFFFF00 Your legs are now bound by shackles!}
{9861}{}{|0xFFFF00 Your legs have been freed from shackles.}
{9862}{}{takes their shackles off}
{9863}{}{takes the subject's shackles off}

{9864}{}{puts ball gag in their mouth}
{9865}{}{puts ball gag in subject's mouth}
{9866}{}{|0xFFFF00 You've put a ball gag in your own mouth.}
{9867}{}{|0xFFFF00 A ball gag has been put in your mouth.}
{9868}{}{|0xFFFF00 A ball gag has been taken out your mouth.}
{9869}{}{removes the ball gag from their mouth}
{9870}{}{removes the ball gag from the subject's mouth}

{9871}{}{puts gag in their mouth}
{9872}{}{puts gag in subject's mouth}
{9873}{}{|0xFFFF00 You've put a gag in your own mouth.}
{9874}{}{|0xFFFF00 A gag has been put in your mouth.}
{9875}{}{|0xFFFF00 A gag has been taken out your mouth.}
{9876}{}{removes the gag from their mouth}
{9877}{}{removes the gag from the subject's mouth}

{9878}{}{puts a slave collar on their neck}
{9879}{}{puts a slave collar on the slave's neck}
{9880}{}{|0xFFFF00 You've put a slave collar on a yourself.}
{9881}{}{|0xFFFF00 You now have your own personal decorative slave collar.}
{9882}{}{|0xFFFF00 The slave collar on your neck opened.}
{9883}{}{removes the slave collar from their neck}
{9884}{}{removes the slave collar from the slave's neck}

{9885}{}{|0xFFFF00 You have repaired the handcuffs.}
{9886}{}{|0xFFFF00 You have repaired the shackles.}
{9886}{}{|0xFFFF00 You have to untie your hands to do that.}

{9890}{}{|0xFFFF00 You have released the slave.}
{9891}{}{|0xFFFF00 You have punished the slave.}
{9892}{}{|0xFFFF00 Your neck is burning, your body is shaking.}
{9893}{}{shakes in agony}
{9894}{}{|0xFFFF00 Your neck is burning and your body shakes with multiple electric strikes.}
{9895}{}{|0xFFFF00 Your neck is burning your body shakes under intolerable pain.}
{9896}{}{|0xFFFF00 You have executed the slave.}
{9897}{}{|0xFFFF00 The pain of a thousand needles shakes you.}
{9898}{}{presses a button}

#Forgot to activate character
{9899}{}{takes one step too many and is reduced to nothing}

#General stuff
{9900}{}{panting}
{9901}{}{rubs a bruise}
{9902}{}{shouts in pain}
{9903}{}{grabs wounded limb, trying to stop blood}
{9904}{}{screams in pain}
{9905}{}{screams in agony}
{9906}{}{slipped on something disgusting}
{9907}{}{You have dropped |0xFFFF00 @lex proto@ |0x3CF800 from your hands.}
{9908}{}{|0xFFFF00 You are damaged by acid.}
{9909}{}{bandages target}
{9910}{}{applies bandage}
{9911}{}{|0xFFFF00 This did nothing.}

#Key duplicate
{9914}{}{|0xFFFF00 You have successfully duplicated a key.}

#X2 X3 containers
{9915}{}{|0xFFFF00 Container is full. You have to free up some space in order to take take the top container.}

#Sandbags
{9916}{}{|0xFFFF00 You can't make a sandbag stack any higher.}
{9917}{}{|0xFFFF00 A critter is preventing you from placing the sandbag.}

#Locks
{9918}{}{|0xFFFF00 You can't put a lock on the terminal.}
{9919}{}{|0xFFFF00 You require a single metal part to make a key for the lock.}
{9920}{}{|0xFFFF00 The door is already locked, you need to lock-pick it first.}
{9921}{}{|0xFFFF00 You must close the door for this.}
{9922}{}{|0xFFFF00 This door can't be locked.}

#Dismantling / securing items
{9923}{}{|0xFFFF00 The item is dismantled, you can now move it to a new place.}
{9924}{}{|0xFFFF00 The item is firmly secured.}

#CarryItems
{9925}{}{|0xFFFF00 You can't pick this up!}
{9926}{}{|0xFFFF00 It's too heavy!}
{9927}{}{|0xFFFF00 You can't pick this up because you are already carrying the maximum allowed weight!}
{9928}{}{|0xFFFF00 You can't pick this up because your items take up too much volume.}

#Furniture
{9929}{}{|0xFFFF00 You don't have the right key.}
{9930}{}{|0xFFFF00 You must have the key or the key-ring containing the right key in your hand.}
{9931}{}{stops pushing}
{9932}{}{|0xFFFF00 This won't fit in here.}
{9932}{}{|0xFFFF00 Dismantling is required.}
{9933}{}{|0xFFFF00 That did nothing.}
{9934}{}{|0xFFFF00 The container is locked.}
{9936}{}{|0xFFFF00 The object is too heavy!}
{9937}{}{|0xFFFF00 You can't move this object without opening the lock first.}
{9938}{}{|0xFFFF00 The object is movable. Use [Repair] to change object state.}
{9939}{}{|0xFFFF00 The object is immovable. Use [Repair] to change object state.}
{9940}{}{tries to stop}
{9941}{}{|0xFFFF00 You can't move locked or closed furniture.}
{9942}{}{starts pushing}
{9943}{}{|0xFFFF00 You can't make a container stack any higher.}
{9944}{}{|0xFFFF00 A critter is preventing you from placing the container.}

#No access for mob control
{9945}{}{|0xFFFF00 You require GM access.}

#h-attack
{9946}{}{|0xFFFF00 You can't fight with that.}

#use radio
{9947}{}{speaks through radio set}

##zh - command
{9948}{}{|0xFFFF00 You have sent @lex critter@ to home position.}
{9949}{}{|0xFFFF00 Critter @lex critter@ is already at home position.}

#push target
{9950}{}{|0xFFFF00 You push the target.}
{9951}{}{|0xFFFF00 Target resisted.}

#~naked
{9952}{}{undresses}

#~desc
{9953}{}{|0xFFFF00 Describe this spot.}
{9954}{}{|0xFFFF00 Something about this spot catches your eye.}
{9955}{}{|0xFFFF00 You did not manage to do anything.}
{9956}{}{|0xFFFF00 You have removed everything that could have attracted attention to this spot.}
{9957}{}{|0xFFFF00 You did not manage to clear the spot.}

#Throw
{9958}{}{|0xFFFF00 You can't throw that far.}
{9959}{}{|0xFFFF00 You can't throw that object.}
{9960}{}{catches item}
{9961}{}{failed to catch item}
{9962}{}{:shatters into pieces:}
{9963}{}{throws item}

#Knocking
{9964}{}{|0xFFFF00 Not enough action points.}
{9965}{}{|0xFFFF00 You can't do that.}
{9966}{}{|0xFFFF00 You've missed the target.}
{9967}{}{|0xFFFF00 You can't knock that often.}
{9968}{}{:knock:}
{9969}{}{|0xFFFF00 You have knocked.}
{9970}{}{|0xFFFF00 You are too far!}

#Code door password
{9971}{}{You set a new code: |0xFFFF00 @lex code@}
{9972}{}{|0xFFFF00 Wrong code format!}
{9973}{}{|0xFFFF00 You input a code!}

#Change Lex self
{9974}{}{|0xFFFF00 You have changed your own description.}

#Digits input
{9975}{}{You set a new password: |0xFFFF00 @lex digits@}
{9976}{}{|0xFFFF00 You input the correct password!}
{9977}{}{|0xFFFF00 You input an incorrect password!}

#Suicide
{9978}{}{performs harakiri...}
{9979}{}{tries to choke them self...}
{9980}{}{spins the cylinder and puts the gun to their own head...}
{9981}{}{puts the barrel in their mouth...}
{9982}{}{points the gun at their abdomen, with the finger on the trigger...}
{9983}{}{holds grenade to their chest and pulls the pin...}
{9984}{}{opens a bottle and pours liquid all over them self, takes a lighter from their pocket...}
{9985}{}{presses sharp object to their own belly...}
{9986}{}{is about to swallow the contents of a vial...}
{9987}{}{|0xFFFF00 You have nothing to kill yourself with.}
{9988}{}{blows own brains out}
{9989}{}{skull explodes with a fountain of blood, covering everything nearby with it}
{9991}{}{multiplies by two}
{9992}{}{head evaporates in an instant}
{9993}{}{body is shaking under electrical charge}
{9994}{}{tried to kill oneself wasting ammo, while weapon awkwardly falls to the ground}
{9995}{}{trigger guard flies to the side}
{9996}{}{|0xFFFF00 The  grenade went off without any effect.}
{9997}{}{drinks the vial}
{9998}{}{sets them self ablaze, the fire consumes everything nearby}

#Toilet
{9999}{}{flushes something down the toilet}

#StartMap
{10000}{}{|0xFFFF00 Error, please contact GM.}
{10001}{}{|0xFFFF00 Start of the game is possible for new characters only.}
{10002}{}{|0xFFFF00 Start of the game is possible only on a starting location.}
{10003}{}{|0xFFFF00 Please try again.}
{10004}{}{|0xFFFF00 Survival mode selected.}
{10005}{}{|0xFFFF00 Area not found.}
{10006}{}{|0xFFFF00 Map not found.}
{10007}{}{|0xFFFF00 This region is filled with sadness, but it seems like the next few steps forward will change your destiny...}
{10008}{}{|0xFFFF00 The item was consumed by the void.}
{10009}{}{|0xFFFF00 You can't do that}

#Gm Mode
{10010}{}{|0xFFFFFF GM mode enabled.}
{10011}{}{|0x606060 GM mode disabled.}

#Grid_to_global_warning
{15000}{}{|0xFFFF00 You are getting scared.}
{15000}{}{|0xFFFF00 You have nowhere else to go.}
{15000}{}{|0xFFFF00 You see only dead wasteland in front of you and understand that going there, will condemn you to certain death. You have no choice but to continue your miserable existence here, fighting for a piece of meat with other people and animals.}
{15000}{}{|0xFFFF00 There is no life there.}
{15000}{}{|0xFFFF00 There is nothing waiting for you there.}

# lifts:
# {2GG00} is key card item proto name from data/ItemNames.lst where GG is lifts group
# {2GGFF} is floor name where GG is lifts group, FF is floor

{20100}{}{PID_V15_KEYCARD}
{20101}{}{4 - Control room}
{20102}{}{3 - Meeting room}
{20103}{}{2 - Barracks}
{20104}{}{1 - Dining Room}
{20105}{}{0 - Galley}

{20201}{}{1 - Trading}
{20202}{}{2 - Bar}
{20203}{}{3 - Industrial area}
{20204}{}{4 - Hole}

{20301}{}{4 - Suites}
{20302}{}{3 - Business rooms}
{20303}{}{2 - Economy rooms}
{20304}{}{1 - Club}
{20305}{}{0 - Lobby}

{20400}{}{PID_SECURITY_CARD}
{20401}{}{1 - Surface}
{20402}{}{2 - Bunker}
{20403}{}{3 - Technical level}

{20501}{}{0 - Surface}
{20502}{}{1 - Chemical Plant}

{20601}{}{1 - First Floor}
{20602}{}{0 - Lobby}

{20701}{}{0 - Lobby}