# Skill raise
{15}{}{Skill @lex skill@ is increased by @lex value@ points}

# Drug Subtypes
{149}{}{Drug Type:}
{150}{}{Dope}
{151}{}{Combat}
{152}{}{Heavy}
{153}{}{Healing}
{154}{}{Therapy}

# Generic messages
{510}{}{Yes} # Magic ball
{511}{}{No} # Magic ball
{520}{}{powders nose} # Cosmetic
{530}{}{smokes} # Cigarettes

{700}{}{|0xFFFF00 Your tool is broken!}

{701}{}{Skill: |0xFFFF00 VALUE|0x3CF800 .}
{702}{}{Perk: }
{703}{}{|0xFFFF00 VALUE|0x3CF800 .}
{704}{}{|0x3CF800 ;
  	   |0xFFFF00 }

# Weapon Perks
{800}{}{|0xFFFF00 None|0x3CF800 }
{801}{}{Long Range}
{802}{}{Accurate}
{803}{}{Shred}
{804}{}{Knockback}
{805}{}{Scoped Range}
{806}{}{Corrosive}
{807}{}{Suppresive}
{808}{}{Single Reload}
{809}{}{Extra Knockout}
{810}{}{Penetrate}
{811}{}{Unreliable}
{812}{}{Non-lethal}
{813}{}{Poisoned}
{814}{}{Neuro-toxin}
{815}{}{Recharge}
{816}{}{Ignore Cover}
{817}{}{Silent}
{818}{}{Armorbane}
{819}{}{Flashlight}
{820}{}{}
{821}{}{}
{822}{}{}
{823}{}{}
{824}{}{}
{825}{}{}
{826}{}{}
{827}{}{}
{828}{}{}
{829}{}{}
{830}{}{}
{831}{}{}
{832}{}{}

# Ammo Perks
{900}{}{|0xFFFF00 None|0x3CF800 }
{901}{}{Unreliable}
{902}{}{Poisoned}
{903}{}{Neuro-toxin}
{904}{}{Caseless}
{905}{}{Non-leathal}
{906}{}{Radioactive}
{907}{}{Shred}
{908}{}{Eroding}
{909}{}{Corrosive}
{910}{}{Spreadshot}
{911}{}{}
{912}{}{}
{913}{}{}
{914}{}{}
{915}{}{}
{916}{}{}
{917}{}{}
{918}{}{}
{919}{}{}
{920}{}{}
{921}{}{}
{922}{}{}
{923}{}{}
{924}{}{}
{925}{}{}
{926}{}{}
{927}{}{}
{928}{}{}
{929}{}{}
{930}{}{}
{931}{}{}
{932}{}{}

# Bulletin Board System
{995}{}{Look at notes}
{996}{}{Pins a note to board}
{997}{}{Rips down a note}
{998}{}{Bulletin board:
Notes: |0xFFFF00 @lex paperCount@ |0x3CF800 
Page: |0xFFFF00 @lex currPage@/@lex maxPage@ |0x3CF800}
{999}{}{Rip down}

# General interactive machines
{1000}{}{inserts money into machine}
{1001}{}{|0xFFFF00 Machine is locked.}
{1002}{}{opens the machine}

# Armor Perks
{1100}{}{|0xFFFF00 None|0x3CF800 }
{1101}{}{+1 Strength}
{1102}{}{+2 Strength}
{1103}{}{+3 Strength}
{1104}{}{+4 Strength}
{1105}{}{Cool}
{1106}{}{Very Cool}
{1107}{}{Awesome}
{1108}{}{Ugly}
{1109}{}{Very Ugly}
{1110}{}{Awful}
{1111}{}{RAD-Res Mk. I}
{1112}{}{RAD-Res Mk. II}
{1113}{}{RAD-Res Mk. III}
{1114}{}{RAD-Res Mk. IV}
{1115}{}{Powered}
{1116}{}{RAD-Protection}
{1117}{}{Full-Body}
{1118}{}{Has Hood}
{1119}{}{Air Filter}
{1120}{}{STA Module}
{1121}{}{Nimble}
{1122}{}{Clumsy}
{1123}{}{Brisk}
{1124}{}{Sluggish}
{1125}{}{Quick Standup}
{1126}{}{Slow Standup}
{1127}{}{Durable}
{1128}{}{Fragile}
{1129}{}{}
{1130}{}{}
{1131}{}{}
{1132}{}{}

# Headgear Perks
{1200}{}{|0xFFFF00 None|0x3CF800 }
{1201}{}{Cool}
{1202}{}{Glasses}
{1203}{}{Very cool}
{1204}{}{Lucky charm}
{1205}{}{Hides face}
{1206}{}{No knockout}
{1207}{}{Baseball fan}
{1208}{}{STA Module}
{1209}{}{Flashbang resist}
{1210}{}{Gasmask}
{1211}{}{Flashlight}
{1212}{}{}
{1213}{}{}
{1214}{}{}
{1215}{}{}
{1216}{}{}
{1217}{}{}
{1218}{}{}
{1219}{}{}
{1220}{}{}
{1221}{}{}
{1222}{}{}
{1223}{}{}
{1224}{}{}
{1225}{}{}
{1226}{}{}
{1227}{}{}
{1228}{}{}
{1229}{}{}
{1230}{}{}
{1231}{}{}
{1232}{}{}

# Tool Perks
{1300}{}{|0xFFFF00 Nothing|0x3CF800 }
{1301}{}{Screwdriver}
{1302}{}{Knife}
{1303}{}{Multitool}
{1304}{}{Shovel}
{1305}{}{Solderer}
{1306}{}{Needle}
{1307}{}{Chem. tubes}
{1308}{}{Chem. kit}
{1309}{}{Axe}
{1310}{}{Wrench}
{1311}{}{Mortar}
{1312}{}{Sledge}
{1313}{}{Hammer}
{1314}{}{Welding}
{1315}{}{Scissors}
{1316}{}{Tripod with tubes}
{1317}{}{Centrifuge}
{1318}{}{Drill}
{1319}{}{Fire}
{1320}{}{Shiv}
{1321}{}{Kazan}
{1322}{}{Workbench}
{1323}{}{Ammo bench}
{1324}{}{}
{1325}{}{}
{1326}{}{}
{1327}{}{}
{1328}{}{}
{1329}{}{}
{1330}{}{}
{1331}{}{}
{1332}{}{}

# Fixboy filters
{1400}{}{|0xFFFF00 Nothing|0x3CF800 }
{1401}{}{Parts}
{1402}{}{Small Guns}
{1403}{}{Apparel}
{1404}{}{Melee}
{1405}{}{Tools}
{1406}{}{Chemistry}
{1407}{}{Medium Guns}
{1408}{}{Armor}
{1409}{}{Traps}
{1410}{}{Containers}
{1411}{}{Ammo}
{1412}{}{Big Guns}
{1413}{}{Headgear}
{1414}{}{Thrown weapons}
{1415}{}{Furniture}
{1416}{}{}
{1417}{}{}
{1418}{}{}
{1419}{}{}
{1420}{}{}
{1421}{}{}
{1422}{}{}
{1423}{}{}
{1424}{}{}
{1425}{}{}
{1426}{}{}
{1427}{}{}
{1428}{}{}
{1429}{}{}
{1430}{}{}
{1431}{}{}
{1432}{}{}

# Dead bodies (Bones)
{1933}{}{Corpse of }
{1934}{}{The body is beheaded}
{1935}{}{The body belongs to |0xFFFFFF }
{1936}{}{Unidentified person}

# Slots
{2001}{}{|0xFFFF00 There is no money left in the machine.}
{2002}{}{|0xFFFF00 There is not enough money in the machine to cover the bet.}
{2003}{}{|0xFFFF00 JACKPOT!!! @lex result@}
{2004}{}{|0xFFFF00 Win: @lex result@}
{2005}{}{|0xFF0000 Lose!}
{2006}{}{|0xFFFF00 You don't have enough money.}
{2007}{}{|0xFFFF00 Bet }

# Stat rolls
{2021}{}{|0xA6EEF900 STRENGTH @lex result@}
{2022}{}{|0xA6EEF900 PERCEPTION @lex result@}
{2023}{}{|0xA6EEF900 ENDURANCE @lex result@}
{2024}{}{|0xA6EEF900 CHARISMA @lex result@}
{2025}{}{|0xA6EEF900 INTELLECT @lex result@}
{2026}{}{|0xA6EEF900 AGILITY @lex result@}
{2027}{}{|0xA6EEF900 LUCK @lex result@}

# Coinflip
{2050}{}{flips a coin: |0x7CFC00 Bermin|0xFF00FF .}
{2051}{}{flips a coin: |0x7CFC00 Buck|0xFF00FF .}

# Dice use
{2053}{}{rolls: |0x7CFC00 @lex result@|0xFF00FF .}

# Cards
{2054}{}{|0xFFFF00 The deck is empty!}
{2055}{}{|0xFFFF00 There are no cards in the deck!}
{2056}{}{draws: |0x7CFC00 @lex card@|0xFF00FF .}
{2057}{}{deals a card}
{2058}{}{|0xFFFF00 You were delt a card.}
{2059}{}{shufles the deck}
{2060}{}{collects cards}
{2061}{}{|0xFFFF00 You can only add cards to this hand.}
{2062}{}{shows: @lex cards@}
{2063}{}{Your hand: @lex cards@}
{2064}{}{|0x3CF800 - |0xFFFF00 @lex card@|0x3CF800  -}

# Vending Machines
{2100}{}{collects goods}
{2101}{}{collects change}
{2102}{}{selects new item}
{2103}{}{sells}

# Jukebox
{2150}{}{|0xFFFF00 You realize that the selected track is not present!}
{2151}{}{|0xFFFF00 Seams like there is no change!}

# Terminal
{2200}{}{|0xFFFF00 You blocked access to the terminal.}
{2201}{}{opens terminal receiver}
{2202}{}{|0xFFFF00 The terminal does not accept this item!}
{2203}{}{selects the security card}
{2204}{}{disables security card}
{2205}{}{|0xFFFF00 You are grabbed by the manipulators. Your legs are locked.}
{2206}{}{|0xFFFF00 You are released by the manipulators and can walk again.}
{2207}{}{charges bio-gel}
{2208}{}{|0xFFFF00 You have charged auto-doc with bio-gel up to the lid.}
{2209}{}{|0xFF0000 The surgery had no effect.}

# Bandage
{2300}{}{You have healed |0xFFFF00 @lex rate@|0x3CF800  HP.}
{2301}{}{|0xFFFF00 Your bandage has become soaked with blood, so you disposed of it.}
{2302}{}{|0xFFFF00 You have been bandaged.}
{2303}{}{You have restored |0xFFFF00 @lex regen@|0x3CF800  HP.}
{2304}{}{You have regained |0xFFFF00 @lex regen@|0x3CF800  Max HP.}
{2305}{}{The effect of the vitamins has worn off.}

# Homebrew
{6137}{}{|0xFFFF00 Homebrew is ready, there is no point in adding anything else to it.}
{6138}{}{|0xFFFF00 You can't make homebrew out of this.}
{6139}{}{adds water}
{6140}{}{adds dirty water}
{6141}{}{adds cola}
{6142}{}{adds beer}
{6143}{}{adds Gamma Gulp beer}
{6144}{}{adds strong alcohol}
{6145}{}{adds liquid}
{6146}{}{adds ingredients}
{6147}{}{|0xFFFF00 You can not add any more ingredients, the pot is filled to the brim.}
{6148}{}{|0xFFFF00 The brewing process is already underway, it's too late to add anything solid to the pot.}
{6149}{}{|0xFFFF00 You have filled the pot up to the brim.}
{6150}{}{:the water is overflowing:}
{6151}{}{|0xFFFF00 You have run out of yeast.}
{6152}{}{|0xFFFF00 You need to take a knife in your hand.}
{6153}{}{grinds the ingredients}
{6154}{}{|0xFFFF00 The process will not start without water, you have wasted the valuable yeast.}
{6155}{}{|0xFFFF00 The process will not start without sugar, you have wasted the valuable yeast.}
{6156}{}{:sickening smell:}
{6157}{}{opens the lid}
{6158}{}{closes the lid}
{6159}{}{|0xFFFF00 It doesn't make any sense to taste the brew without any water inside.}
{6160}{}{Having tasted the brew, you have determined that it is: |0xFFFF00 @lex sugar@ @lex state@ with a taste of @lex taste@ @lex alcohol@ @lex polution@}
{6161}{}{Plain}
{6162}{}{Slightly sweet}
{6163}{}{Sweet}
{6164}{}{Sugary}
{6165}{}{, has a slightly bitter alcohol taste}
{6166}{}{, has a bitter alcohol taste}
{6167}{}{, has a very bitter alcohol taste}
{6168}{}{, it smells a rather rotten}
{6169}{}{, it smells rotten}
{6170}{}{, it has a strong rotten smell}
{6171}{}{|0xFFFF00 There is not enough liquid to pour out.}
{6172}{}{|0xFFFF00 You have bottled all the homebrew.}
{6173}{}{|0xFFFF00 You have run out of bottles.}
{6174}{}{fills the bottle}
{6175}{}{|0xFFFF00 You have completely filled the bottle with homebrew.}
{6176}{}{|0xFFFF00 You have poured out the pot and cleaned it.}
{6177}{}{shakes out the contents of the pot}
{6178}{}{:the ingredients are scattered on the ground:}
{6179}{}{pours out the contents of the pot}
{6180}{}{:a puddle has formed under the pot:}
{6181}{}{adds yeast}
{6182}{}{ water}
{6183}{}{ fermented water}
{6184}{}{ homebrew}
{6185}{}{ with a taste of }
{6186}{}{ nothing special }
{6187}{}{}
{6188}{}{Open pot}
{6189}{}{Close pot}
{6190}{}{Add ingridient}
{6191}{}{Slice ingridients}
{6192}{}{Taste}
{6193}{}{Add yeast}
{6194}{}{Pour everything out}
{6195}{}{Pour into bottles}
{6196}{}{Take out}
{6197}{}{The lid is closed firmly.}
{6198}{}{@lex state@

The pot is filled for |0xFFFF00 @lex current@ |0x3CF800 out of |0xFFFF00 @lex max@ |0x3CF800 l.}
{6199}{}{Brewing will not start without water, sugar, and yeast. You will begin the process by adding the yeast.}
{6200}{}{The brewing is still undergoing.}
{6201}{}{It seems the the brewing has ended.}

{6245}{}{Type of tool: }

# Cooking
{6246}{}{Cooking recepie}
{6247}{}{You are about to cook something...}
{6248}{}{cooks something}
{6249}{}{prepares @lex name@}
{6250}{}{burns @lex name@}
{6251}{}{Pretzel}
{6252}{}{|0xFF0000 You have burned the pretzels. }
{6253}{}{|0xFFFF00 You have prepared some pretzels, time to get those calories up!}
{6254}{}{|0xFFFF00 You require some corn flour, yeast and sugar for it.}
{6257}{}{Maggot Soup}
{6258}{}{|0xFF0000 Those maggots are still alive, moron!}
{6259}{}{|0xFFFF00 You have prepared a maggot soup, have a nice day!}
{6260}{}{|0xFFFF00 You need at least 3 maggots and clean water if you want to get the exquisite flavour!}
{6262}{}{Rat Stew}
{6263}{}{|0xFF0000 You have miraculously managed to spoil even a rat Stew. }
{6264}{}{|0xFFFF00 You have prepared a nice rat stew, enjoy!}
{6265}{}{|0xFFFF00 You need at least one rat, peyote and clean water for a good stew!}
{6268}{}{Salad}
{6269}{}{Soup}
{6270}{}{Kebab}
{6271}{}{Tortilla}
{6272}{}{Stomach}
{6273}{}{Stew}
{6274}{}{Burger}
{6275}{}{Pizza}
{6276}{}{Fish Pie}
{6277}{}{Taco}
{6278}{}{Select Recipe:}
{6279}{}{warms hands}
{6280}{}{|0xFFFF00 You’ll need raw meat in your hands for this.}
{6281}{}{|0xFF0000 Even after roasting, this thing is still inedible.}
{6282}{}{|0xFFFF00 You successfully grilled @lex name@.}
{6283}{}{|0xFFFF00 You don’t know a single useful recipe for cooking.}
{6284}{}{|0xFF0000 You ruined the salad. Totally impossible to eat!}
{6285}{}{|0xFFFF00 You made a tasty salad, using a mutfruit and a couple of algae.}
{6286}{}{|0xFFFF00 You’ll need a mutfruit, some carnivorous algae, and a clean plate.}
{6288}{}{|0xFF0000 You ruined the stew.}
{6289}{}{|0xFFFF00 You cooked up a stew.}
{6290}{}{|0xFFFF00 You’ll need clean water, a cabbage, a Xander root, and a clean plate.}
{6293}{}{|0xFF0000 You burned the meat to ashes. Totally inedible crap!}
{6294}{}{|0xFFFF00 You cooked a juicy kebab, seasoned with Xander root.}
{6295}{}{|0xFFFF00 For this kebab you’ll need Meat and a Xander root.}
{6297}{}{|0xFFFF00 The flatbread burned and reeks.}
{6298}{}{|0xFFFF00 You baked a tasty corn flatbread, mixing corn and Xander root.}
{6299}{}{|0xFFFF00 First you’ll need cornmeal and a Xander root.}
{6301}{}{|0xFF0000 You ruined the dish. No way anyone can eat this.}
{6302}{}{|0xFFFF00 You managed to cook a stuffed stomach, using a chunk of meat, a couple of Broc flowers, and the stomach itself.}
{6303}{}{|0xFFFF00 You’ll need a molerat stomach, two Broc flowers, Meat, and a clean plate.}
{6306}{}{|0xFF0000 The taste of this stew makes you gag. Shame, you really tried…}
{6307}{}{|0xFFFF00 You cooked a fine stew from a couple pieces of meat, a Broc flower, and a Xander root.}
{6308}{}{|0xFFFF00 You’ll need two good pieces of Meat, a Broc flower, a Xander root, and a clean plate.}
{6311}{}{|0xFF0000 Your burger could honestly be called nauseating. No one’s eating this crap.}
{6312}{}{|0xFFFF00 You managed to make a hearty burger with gecko meat, flatbread, and cabbage leaves.}
{6313}{}{|0xFFFF00 How can you make a burger without gecko meat, cabbage, and a corn flatbread?}
{6316}{}{|0xFF0000 Even if you lived in a sewer, you wouldn’t eat this.}
{6317}{}{|0xFFFF00 You cooked up something like a pizza, using flatbread, meat, and mushrooms.}
{6318}{}{|0xFFFF00 The base for pizza is a corn flatbread topped with Black Mushroom and Meat.}
{6321}{}{|0xFF0000 The pie is ruined. What a shame!}
{6322}{}{|0xFFFF00 You baked a fish pie from flatbread, two portions of fish, and a couple of Xander roots.}
{6323}{}{|0xFFFF00 Slice open a corn flatbread, add two fish patties and two Xander roots.}
{6326}{}{|0xFF0000 Total failure! Taco, burrito, quesadilla… doesn’t matter anymore.}
{6327}{}{|0xFFFF00 You made a taco by chopping three rat corpses, stuffing them into a flatbread, and seasoning with a couple of Broc flowers.}
{6328}{}{|0xFFFF00 Mince three rat corpses, wrap them in a corn flatbread, and chop up two Broc flowers.}
{6331}{}{French Fries}
{6332}{}{|0xFFFF00 You burned the fries.}
{6333}{}{|0xFFFF00 You fried up some crispy fries. Finger-lickin’ good.}
{6334}{}{|0xFFFF00 First you’ll need potatoes, vegetable oil, and a clean plate.}
{6337}{}{Potato Pancakes}
{6338}{}{|0xFFFF00 You burned the potato pancakes.}
{6339}{}{|0xFFFF00 You cooked up some potato pancakes.}
{6340}{}{|0xFFFF00 First you’ll need potatoes, flour, vegetable oil, and a clean plate.}
{6344}{}{Potato Chips}
{6345}{}{|0xFFFF00 You burned the potato chips.}
{6346}{}{|0xFFFF00 You made a batch of potato chips.}
{6347}{}{|0xFFFF00 First you’ll need potatoes, a Xander root, vegetable oil, and a clean plate.}
{6351}{}{Mashed Potatoes with Cutlet}
{6352}{}{|0xFFFF00 You burned the mashed potatoes with cutlet.}
{6353}{}{|0xFFFF00 You cooked mashed potatoes with a cutlet.}
{6354}{}{|0xFFFF00 First you’ll need two potatoes, a Broc flower, vegetable oil, two pieces of meat, and a clean plate.}
{6359}{}{Pancake}
{6360}{}{|0xFFFF00 You burned the pancake.}
{6361}{}{|0xFFFF00 You managed to cook a pancake.}
{6362}{}{|0xFFFF00 First you’ll need sugar, vegetable oil, two mutfruits, a couple pinches of cornmeal, water, and a clean plate.}

# Firestarter
{6390}{}{|0xFFFF00 The fire is already burning.}
{6391}{}{|0xFFFF00 There is nothing to burn, you have to find some fire fuel.}
{6392}{}{|0xFFFF00 You have used up the flint.}
{6393}{}{ignites the fire}
{6394}{}{|0xFFFF00 The flask is empty.}
{6395}{}{pours water}
{6396}{}{|0xFFFF00 You have poured out the water for no effect. Is this the right way to treat the precious liquid?}
{6397}{}{|0xFFFF00 You have ruined some fuel with water, it's totally wasted now...}
{6398}{}{extinguishes flames}
{6399}{}{|0xFFFF00 There is no more space for fuel, let some of it burn!}
{6400}{}{adds coal}
{6401}{}{adds fuel}
{6402}{}{|0xFFFF00 The fireplace is filled with flammables at @lex rate@% of maximum capacity.}
{6403}{}{|0xFFFF00 You can't burn this.}
{6404}{}{chunks something into the fire}
{6405}{}{throws an item into the fire}
{6407}{}{|0xFFFF00 You require water.}
{6408}{}{|0xFFFF00 You have nothing to light the fire with.}
{6409}{}{|0xFFFF00 You don't have any common fire fuel.}

# Milling
{6410}{}{|0xFFFF00 The mill is empty.}
{6411}{}{|0xFFFF00 The mill does not contain approporiate resource.}
{6412}{}{finishes milling}

# Furnace
{6413}{}{|0xFFFF00 First you need to turn off the furnace.}
{6414}{}{|0xFFFF00 You require tools to work with a hot furnace!}

# Smithing
{6415}{}{|0xFFFF00 The anvil is empty.}
{6416}{}{|0xFFFF00 There is no ingot on the anvil.}
{6417}{}{finishes smithing}
{6418}{}{|0xFFFF00 Power is offline!}

# Waterworks
{6420}{}{spins the bobbin}
{6421}{}{|0xFFFF00 The bucked fell into the darkness...}
{6422}{}{:the bucket appears:}
{6423}{}{|0xFFFF00 You don't have anything to pour the water into.}
{6424}{}{|0xFFFF00 There is no water left.}
{6425}{}{|0xFFFF00 The pump is offline. You have to turn it on first.}
{6426}{}{|0xFFFF00 You are not holding anything to pour the water into.}
{6427}{}{|0xFFFF00 You are out of bottles.}
{6428}{}{|0xFFFF00 You have poured out all water.}
{6429}{}{fills the tare}
{6430}{}{|0xFFFF00 You have filled up the bottle.}
{6431}{}{|0xFFFF00 You have filled up the canister.}
{6432}{}{washes hands}
{6433}{}{starts washing}
{6434}{}{|0xFFFF00 You have washed yourself.}
{6435}{}{|0xFFFF00 You require water for that.}
{6436}{}{|0xFFFF00 You are using a fresh piece of soap.}
{6437}{}{washes hands with utility soap}
{6438}{}{washes with utility soap}
{6439}{}{|0xFFFF00 You have used up all the soap.}
{6440}{}{washes hands with perfumed soap}
{6441}{}{washes with perfumed soap}
{6442}{}{|0xFFFF00 After being washed with perfumed soap you became more pleasant for everyone around you.}
{6443}{}{uses perfume}
{6444}{}{|0xFFFF00 Applying scented perfumes made you more pleasant to others.}
{6445}{}{|0xFFFF00 Applying perfumes made you realize that it didn't make much sense, because you already smelled good.}
{6446}{}{|0xFFFF00 Your perfume phial is empty.}

# Lifts
{6450}{}{calls the elevator}
{6451}{}{|0xFFFF00 Elevator is busy.}
{6452}{}{|0xFFFF00 Elevator is recharging.}
{6453}{}{activates elevator}
{6454}{}{|0xFFFF00 The card slot blinked. Looks like you require an access card to use the elevator.}
{6455}{}{|0xFFFF00 The card slot blinked. Looks like you can't call the elevator without an access card.}
{6456}{}{inserts the access card}

# Fishing
{6460}{}{ties the fishing line to the rod.}
{6461}{}{|0xFFFF00 You must hold the rod to attach the fishing line to it.}
{6462}{}{ties the hook to the fishing line}
{6463}{}{|0xFFFF00 You must hold the rod to attach the hook to it.}
{6464}{}{attaches the @lex bait@ on the hook.}
{6465}{}{|0xFFFF00 You must hold the rod to attach the bait.}
{6466}{}{|0xFFFF00 There is no fish in this place.}
{6467}{}{|0xFFFF00 You must hold the fishing rod.}
{6468}{}{|0xFFFF00 You require bait for fishing.}
{6469}{}{|0xFFFF00 You can't cast the fishing rod that far.}
{6470}{}{|0xFFFF00 There is no deep water in the place you are targeting.}
{6471}{}{casts the fishing rod}
{6472}{}{catches algae}
{6473}{}{takes the hook out of the water}
{6474}{}{|0xFFFF00 Looks like the fish got away with the bait...}
{6475}{}{|0xFFFF00 The fish got away!}
{6476}{}{|0xFFFF00 You feel the tension of the fishing line, the fish resists!}
{6477}{}{|0xFFFF00 The fish submits.}
{6478}{}{catches @lex reward@}
{6479}{}{|0xFFFF00 You realize the line snapped!}
{6480}{}{|0xFFFF00 You realize the fish has taken the hook with it!}

# Taste
{6486}{}{This beverage has a taste of }
{6487}{}{|0xFFFF00 Potato}
{6488}{}{|0xFFFF00 Cabbage}
{6489}{}{|0xFFFF00 Nuts}
{6490}{}{|0xFFFF00 Bread}
{6491}{}{|0xFFFF00 Nightshade berries}
{6492}{}{|0xFFFF00 Mutated fruits}
{6493}{}{|0xFFFF00 Vanilla}
{6494}{}{|0xFFFF00 Corn}
{6495}{}{|0xFFFF00 Cookies}
{6496}{}{|0xFFFF00 Protein bar}
{6497}{}{|0xFFFF00 Candies}
{6498}{}{|0xFFFF00 Caramel}
{6499}{}{ You smell the liquid inside to be:}

# St Peter
{6500}{}{Stop it, my son, it's useless.}
{6501}{}{There is a lot of filth in you.}
{6502}{}{I understand your pain. Calm down, child.}
{6503}{}{Anger destroys you, don't go on about it.}
{6504}{}{It's not an easy path for you, you're embittered.}
{6505}{}{Your anger is unfair. Stop it now.}
{6506}{}{It's not time yet, you can't pass.}
{6507}{}{Patience, my son, patience.}
{6508}{}{Your time hasn't come yet. I can't let you pass.}
{6509}{}{Don't rush there, you have a whole eternity ahead of you.}
{6510}{}{You've lived your whole life in a hurry, take a break at least for now.}

# Traps
{6550}{}{|0xFFFF00 You must hold the snare to set it up.}
{6551}{}{|0xFFFF00 You can't set a snare on top of another one.}
{6552}{}{|0xFFFF00 Your hand got caught by your own snare.}
{6553}{}{sets up a snare}
{6554}{}{|0xFFFF00 You have almost stepped into the snare, but avoided it at the last second.}
{6555}{}{gets snared}
{6556}{}{|0xFFFF00 You can't place a trip-wire here.}
{6557}{}{sets up a trip-wire}
{6558}{}{|0xFFFF00 You managed to disarm the trip-wire.}
{6559}{}{|0xFFFF00 You did not manage to disarm the trip-wire.}
{6560}{}{|0xFFFF00 You have almost triggered a trip-wire, but avoided it at the last second.}
{6561}{}{triggers the trip-wire}
{6562}{}{|0xFFFF00 You can't plant a mine here.}
{6563}{}{plants a mine}
{6564}{}{|0xFFFF00 You have managed to disarm the mine.}
{6565}{}{|0xFFFF00 You failed to disarm the mine.}
{6566}{}{|0xFFFF00 You have almost stepped on a mine, but avoided it at the last second.}
{6567}{}{steps on the mine}
{6568}{}{|0xFFFF00 You carefully remove the leg from an activated mine.}
{6569}{}{removed the leg from the mine, activating it}
{6570}{}{|0xFFFF00 You must hold the trap to set it up.}
{6571}{}{|0xFFFF00 You can't set up a trap here.}
{6572}{}{sets up a trap}
{6573}{}{|0xFFFF00 You did something wrong and the trap went off in your hands.}
{6574}{}{|0xFFFF00 You did something wrong, but luckily managed to avoid an explosion.}
{6575}{}{|0xFFFF00 You have successfully disarmed the trap.}
{6576}{}{|0xFFFF00 You have failed to disarm the trap.}
{6577}{}{|0xFFFF00 You have almost stepped on a trap, but avoided it at the last second.}
{6578}{}{steps on a trap}
{6579}{}{:click:}

# Bootlegging
{6600}{}{|0xFFFF00 The still is not ready for distiling.}
{6601}{}{|0xFFFF00 You feel that you can't distill spirit out of that.}
{6602}{}{:homebrew is spilling over the top:}
{6603}{}{|0xFFFF00 You have poured out all the spirit.}
{6604}{}{|0xFFFF00 You have run our of bottles.}
{6605}{}{|0xFFFF00 You have filled up a bottle.}
{6606}{}{completes repairs on the still}
{6607}{}{completes still maintenance}
{6608}{}{|0xFFFF00 You failed to perform still maintenance!}
{6609}{}{You require instruments: }
{6610}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{6611}{}{You require parts: }
{6612}{}{|0x3CF800  - |0xFFFF00 @lex proto@ - @lex amount@ pcs.}
{6613}{}{|0x3CF800 You lack the skills:
 - |0xFFFF00 Science |0x3CF800  -  |0xFFFF00 150 |0x3CF800 ,
 - |0xFFFF00 Repair |0x3CF800  -  |0xFFFF00 200 |0x3CF800 .}
{6614}{}{You require consumables: }
{6615}{}{|0x3CF800  - |0xFFFF00 @lex proto@}

# Sex
{6992}{}{|0xFF0000 You have been rejected!}
{6993}{}{gets some sweet love}
{6994}{}{trembles}
{6995}{}{|0xFF0000 Looks like your partner was a little bit too fast...}
{6996}{}{|0xFFFF00 The injury is preventing you from doing this.}
{6997}{}{|0xFFFF00 Your partner's injury is preventing them from doing this.}
{6998}{}{|0xFFFF00 You are too tired and are not ready for sexual intercourse.}
{6999}{}{|0xFFFF00 Your partner is too tired and is not ready for sexual intercourse.}

# Roulette
{7001}{}{zero}
{7002}{}{double zero}
{7003}{}{red}
{7004}{}{black}
{7005}{}{number }
{7006}{}{Your winnings: }
{7007}{}{Invalid number}
{7008}{}{Incorrect bid}
{7009}{}{Number accepted}
{7010}{}{Bid accepted}
{7011}{}{Current bid: @lex betsize@}
{7012}{}{You bet on the numbers:}
{7013}{}{@lex result@}
{7014}{}{Make your bet}

# Rotting
{7020}{}{|0xFF828a96 :smell of blood:}
{7021}{}{|0xFF828a96 :smell of decay:}
{7022}{}{|0xFF828a96 :bad smell:}
{7023}{}{|0xFFFF00 It looks like something has rotted in your inventory.}
{7024}{}{bad smell}

# Player Menu
{8200}{}{You can now be heard from: |0xFFFF00 @lex hexes@|0x3CF800  hex.}
{8201}{}{Avatar mode: @lex AvatarMode@}
{8202}{}{Show}
{8203}{}{Cursor}
{8204}{}{Hide}
{8205}{}{Avatar: [|0xFFFF00 @lex AvatarMode@|0x3CF800 ]}
{8206}{}{NPC Icons: [|0xFFFF00 @lex NPC_Icon@|0x3CF800 ]}
{8207}{}{Show}
{8208}{}{Hide}

# Healing
{8949}{}{|0xFFFF00 You are being examined. Agree?}
{8950}{}{Agree}
{8951}{}{Resist}
{8952}{}{|0xFFFF00 You are being examined.}
{8953}{}{|0xFFFF00 You are waiting for the patient's answer.}
{8954}{}{|0xFFFF00 A @lex proto@ is being used on you. Agree?"}
{8955}{}{|0xFFFF00 A @lex proto@ is being used on you.}
{8956}{}{consumes @lex proto@}
{8957}{}{applies @lex proto@ on target}
{8958}{}{|0xFFFF00 You are too far from your patient!}
{8959}{}{|0xFFFF00 Your doctor is too far!}
{8960}{}{|0xFFFF00 Your vision clears, and your eyes are back to the norm again.}
{8961}{}{|0xFFFF00 Your right hand feels much better now.}
{8962}{}{|0xFFFF00 Your left hand feels much better now.}
{8963}{}{|0xFFFF00 Your right leg is much better now.}
{8964}{}{|0xFFFF00 Your left leg is much better now.}
{8965}{}{|0xFFFF00 You have removed the bullet from the wound.}
{8966}{}{|0xFFFF00 You have failed to remove the bullet from the wound.}
{8967}{}{|0xFFFF00 You require a needle and thread.}
{8968}{}{|0xFFFF00 You don't have a fire source or anything to cauterize the wound with.}
{8969}{}{|0xFFFF00 You successfully stiched the wound.}
{8970}{}{|0xFFFF00 You successfully cauterized the wound.}
{8971}{}{|0xFFFF00 Surgery attempt failed.}
{8972}{}{|0xFFFF00 You have applied patch onto eye. Healing may take some time.}
{8973}{}{|0xFFFF00 You have applied bandage onto eye.}
{8974}{}{|0xFFFF00 You have successfully made an improvised brace.}
{8975}{}{|0xFFFF00 You require a medical brace or at least a rope and a stick.}
{8976}{}{|0xFFFF00 You have applied a medical brace on your patient.}

# Teleport Menu
{8998}{}{|0xFFFFFF Select your destination|0x00FF00 :
|0xFFFF00 @lex name@}

# Offline teleport
{8999}{}{|0xFF0000 You have been offline for too long and have now been teleported to the starting area!}

# Russian Roulette
{9000}{}{he lost at "Russian Roulette"@@his brains got blown out@@today is not his lucky day@@he shouldn't have agreed to this@@he splattered everything around with his blood@@he screamed and pulled the trigger, the scream was cut off...@@he shot himself@@he did not hesitate to splatter the area with his brains}
{9001}{}{the gun clicked, but nothing happens@@he almost shit himself, but nothing happened...@@he screamed as he pulled the trigger, but everything turned out ok!@@fortune smiled at him!@@he won at "Russian Roulette"@@LUCKY!@@he held his breath and pulled the trigger, but everything went fine}
{9002}{}{she lost at "Russian Roulette"@@she took her brains out@@today is not her day@@she shouldn't have agreed to this@@she poured her blood all over the place@@she screamed as she pulled the trigger, but the scream was cut off...@@she shot herself@@without hesitation, she splattered the area with her brains}
{9003}{}{the gun clicked, but nothing happened@@she almost shit herself, but nothing happened...@@she screamed and pulled the trigger, but everything turned out ok!@@fortune smiled on her@@she won at the "Russian Roulette"@@LUCKY@@she held her breath and pulled the trigger, but everything went fine}

# Resource Gathering
{9004}{}{picks a plant}
{9005}{}{|0xFFFF00 You haven't found anything useful.}
{9006}{}{You've collected:
- |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800 .}
{9007}{}{|0x3CF800 .}
{9008}{}{|0xFFFF00 You've picked the plant during the wrong growth stage and decided to dump it away.}
{9009}{}{|0xFFFF00 You are too tired, so take a rest.}
{9010}{}{|0xFFFF00 You must have a tool equipped in your hand.}
{9011}{}{|0xFFFF00 You are injured and can't perform the task.}
{9012}{}{|0xFFFF00 It was a good idea before you realized there is no juice left in the drill.}
{9013}{}{|0xFFFF00 The drill is too damaged.}
{9014}{}{|0xFFFF00 You have to kill your prey first.}
{9015}{}{|0xFFFF00 You can't skin this.}
{9016}{}{|0xFFFF00 The creature is too damaged to skin.}
{9017}{}{|0xFFFF00 You've damaged the skin during the process.}
{9018}{}{|0xFFFF00 This tool is not suitable for chopping stuff.}
{9019}{}{|0xFFFF00 There is nothing to chop, you have to uproot it.}
{9020}{}{You've crafted: }
{9021}{}{- |0xFFFF00 @lex proto@}
{9022}{}{crafts something}
{9023}{}{You've collected: @lex result@}
{9024}{}{You've lost: - |0xFFFF00 @lex proto@, @lex count@ .}
{9025}{}{|0xFFFF00 You've picked the plant during the wrong growth stage, but managed to gain some plant fibers.}

#Books
{9430}{}{|0xFFFF00 You have already learned all possible professions.}
{9431}{}{|0xFFFF00 You require more base knowlege before comprehending this book.}
{9432}{}{|0xFFFF00 You already know everything this book has to offer.}
{9433}{}{starts reading a book}
{9434}{}{|0xFFFF00 You've absorbed new knowlege.}

#Locks
{9440}{}{|0xFFFF00 You can't lock this door!}
{9441}{}{}

#Radio fast failsafe switch
{9442}{}{Switches failsafe on radio}
{9443}{}{|0xFFFF00 Radio failsafe: [ |0x00C800 @lex mode@ |0xFFFF00 ]}

# ItemMovement
{9445}{}{|0xFFFF00 This is too heavy for you.}
{9446}{}{takes a card}
{9447}{}{takes armor}
{9448}{}{takes @lex proto@}
{9449}{}{takes weapon}
{9450}{}{takes ammo}
{9451}{}{takes something}
{9452}{}{|0xFFFF00 You have to move away to place an item.}
{9453}{}{|0xFFFF00 Moving the item to a slot is restricted because the character model does not have required animations!}
{9454}{}{|0xFFFF00 Weapon in main hand is not supported by character animations, moved to inventory!}
{9455}{}{|0xFFFF00 Weapon in the main hand is not supported by character animations, moved to inventory!}
{9456}{}{|0xFF00FF Synthesized voice: |0xF8F993 Identity recognized. Activation!}
{9457}{}{sound of reactor powering up}
{9458}{}{hides face}
{9459}{}{shows face}
{9460}{}{takes backpack}
{9461}{}{removes equipped items from target}
{9462}{}{|0xFFFF00 You can't resist while your backpack is being taken away.}
{9463}{}{|0xFFFF00 You can't resist while your item is being taken away.}
{9464}{}{|0xFFFF00 You have taken a backpack.}
{9465}{}{|0xFFFF00 You have taken an item.}
{9466}{}{attempts to take armor}
{9467}{}{removes armor from the target}
{9468}{}{|0xFFFF00 Someone is trying to remove your armor!}
{9469}{}{|0xFFFF00 You have taken the target's armor.}
{9470}{}{|0xFFFF00 Your armor was removed.}
{9471}{}{|0xFFFF00 You have taken armor off the target.}
{9472}{}{|0xFFFF00 You have partially taken armor off the target.}
{9473}{}{|0xFFFF00 You can't loot this critter.}

# Bond inv desc
{9474}{}{|0xFFFF00 Bounds you.}
{9475}{}{|0xFFFF00 Ready for use.}

# Windup
{9476}{}{raises @lex proto@}
{9477}{}{lowers @lex proto@}
{9478}{}{raises fists}
{9479}{}{raises fists}
{9480}{}{raises fists}
{9481}{}{raises horns}
{9482}{}{raises stinger}
{9483}{}{grins}
{9484}{}{raises to full height}
{9485}{}{opens jaws}
{9486}{}{raises manipulators}
{9487}{}{raises claws}
{9488}{}{raises tentacles}
{9489}{}{opens mandible}
{9490}{}{looks upon you as if you were a mere insect}
{9491}{}{emits a stinger}
{9492}{}{roars loudly}
{9493}{}{opens pincers}
{9494}{}{emits a low roar}
{9495}{}{relaxes}

# Raising skills
{9496}{}{|0xFFFF00 You have become a real sex expert!}
{9497}{}{|0xFFFF00 You did not manage to raise your skill.}
{9498}{}{|0x3CF800 Skill: }
{9499}{}{|0x3CF800  is raised by }

# Accidental injuries
{9500}{}{|0xFFFF00 You've managed to avoid a terrible injury at the last moment, but still: \n}
{9501}{}{|0xFFFF00 You've received a heavy bruise as a result of your mistake.}
{9502}{}{|0xFFFF00 You've made a mistake and cut your hand.}
{9503}{}{|0xFFFF00 You've hit yourself with a tool and made a deep cut in your flesh.}
{9504}{}{|0xFFFF00 Because of a bad move you have received a serious production injury.}
{9505}{}{|0xFFFF00 You have received a deep brow cut as a result of your mistake.}

# Blood loss
{9510}{}{|0xFFFF00 You start feeling weak from heavy blood loss.}
{9511}{}{|0xFFFF00 You feel cold and weak, and you slowly start to die from massive blood loss.}

# Vomiting
{9512}{}{|0xFFFF00 You feel sick...}
{9513}{}{vomits}
{9514}{}{|0xFFFF00 Seems like you are about to vomit...}
{9515}{}{puts two fingers in their mouth}
{9516}{}{"|0xFFFF00 Your stomach is empty..."}

# Resurrection
{9519}{}{overdosed with meds}
{9520}{}{|0xFFFF00 You've used the item but it hasn't helped}
{9521}{}{|0xFFFF00 Your body survived but your health is significantly damaged.}
{9522}{}{|0xFFFF00 You realize that this will cause the patient to have a heart attack.}

# Food/drink
{9523}{}{the belly rumbles}
{9524}{}{licks dry lips}
{9525}{}{staggers}
{9526}{}{|0xFFFF00 The damage received is too high, you will die soon without outside medical help.}
{9527}{}{|0xFFFF00 You suffer from hunger.}
{9528}{}{|0xFFFF00 You suffer from dehydration.}
{9529}{}{|0xFFFF00 You no longer feel the taste of alcohol...}
{9530}{}{|0xFFFF00 You have become slower because of dehydration.}
{9531}{}{|0xFFFF00 You have become slower because of hunger.}
{9532}{}{|0xFFFF00 You've restored your strength.}
{9533}{}{drinks}
{9534}{}{You have drunk: |0xFFFF00 @lex proto@|0x3CF800 .}
{9535}{}{You lost: |0xFFFF00 @lex rad@|0x3CF800  rad.}
{9536}{}{You gained: |0xFFFF00 @lex poison@|0x3CF800  poison.}
{9537}{}{consumes @lex proto@}

# Dragging
{9540}{}{|0xFFFF00 You can't do that.}
{9541}{}{|0xFFFF00 The target must be prone or be dead!}
{9542}{}{|0xFFFF00 The target is too far away.}
{9543}{}{|0xFFFF00 The body is being dragged.}
{9544}{}{|0xFFFF00 You can't drag more than one body.}
{9545}{}{|0xFFFF00 You start dragging the body.}
{9546}{}{|0xFFFF00 You've dropped the body.}

# Dirt
{9550}{}{|0xFFFF00 Your look and stench start to disgust everyone around you. You better take a bath.}
{9551}{}{|0xFFFF00 You have stopped being repulsive.}

# Lie/stand
{9552}{}{|0xFFFF00 You don't have the strength to get up.}
{9553}{}{|0xFFFF00 You begin to get up.}
{9554}{}{|0xFFFF00 You are lying down.}

# Locks and lockpicking
{9568}{}{|0xFFFF00 You require wire to install a code lock.}
{9569}{}{begins installing a lock}
{9570}{}{begins removing a lock}
{9571}{}{|0xFFFF00 You cant find any hold on the door.}
{9572}{}{Puts something in a mailbox}
{9573}{}{The lockpick is stuck, you need to release it a bit and try again.}
{9574}{}{You have moved the lockpick further.}
{9575}{}{The lockpick reached the end.}
{9576}{}{You moved the lockpick backward.}
{9577}{}{The lockpick is in the closest position, you only have to remove it now.}
{9578}{}{The lockpick has pushed the spring to its maximum}
{9579}{}{You have to move the lockpick to the first position.}
{9580}{}{You have moved the lock toung up with a lockpick.}
{9581}{}{You have moved the lock toung down with a lockpick.}
{9582}{}{ |0xFFFF00 You were not careful and made a bad move.|0x3CF800 }
{9583}{}{The lock won't budge.}
{9584}{}{ |0xFFFF00 You hear a click.|0x3CF800 }
{9585}{}{|0xFFFF00 Padlock|0x3CF800 }
{9586}{}{|0xFFFF00 Door lock|0x3CF800 }
{9587}{}{|0xFFFF00 Safe lock|0x3CF800 }
{9588}{}{Door code: |0xFFFF00 @lex code@|0x3CF800 , your: |0xFFFF00 @lex attempt@|0x3CF800 }
{9589}{}{
   
   Toung position - |0xFFFF00 @lex posToung@|0x3CF800 
   Lockpick position - |0xFFFF00 @lex posLockpick@|0x3CF800 
@lex secret@}
{9590}{}{@lex state@@lex toung@}
{9591}{}{Examine the lock}
{9592}{}{Move further}
{9593}{}{Move backward}
{9594}{}{Move up}
{9595}{}{Move down}
{9596}{}{Turn}
{9597}{}{Remove lockpick}
{9598}{}{Lock the lock}
{9599}{}{State of lock is unknown}
{9600}{}{|0xFFFF00 An inserted key in front of you is preventing you from doing this.}
{9601}{}{|0xFFFF00 An inserted key from the other side is preventing you from doing this.}
{9602}{}{|0xFFFF00 You unlocked the door.}
{9603}{}{unlocks}
{9604}{}{|0xFFFF00 You locked the door.}
{9605}{}{locks}
{9606}{}{|0xFFFF00 You must close it first.}
{9607}{}{|0xFFFF00 The key does not match.}
{9608}{}{|0xFFFF00 Something is preventing the door from being closed.}
{9609}{}{|0xFFFF00 You require electronic lockpick.}
{9610}{}{|0xFFFF00 You are too far from target.}
{9611}{}{|0x606060 knock-knock}
{9612}{}{|0xFFFF00 You've knocked.}
{9613}{}{|0xFF0000 BANG}
{9614}{}{|0xFFFF00 The door is already open.}
{9615}{}{|0xFFFF00 There is no lock.}
{9616}{}{|0xFFFF00 You require a lockpick or a pin at least.}
{9617}{}{|0xFFFF00 The lockpick broke, it seems you did not properly remove it from the lock the last time.}
{9618}{}{takes key out of the lock}
{9619}{}{puts key in the lock}
{9620}{}{|0xFFFF00 You are too far away from the lock, your lockpicks break.}
{9621}{}{|0xFFFF00 You have successfully picked a lock.}
{9622}{}{|0xFFFF00 You carefully extract the lockpick.}
{9623}{}{|0xFFFF00 Your skill is not enough to lock the door with a lockpick.}
{9624}{}{|0xFFFF00 The door is already locked.}
{9625}{}{|0xFFFF00 You locked the door.}
{9626}{}{|0xFFFF00 You removed the lock.}
{9627}{}{|0xFFFF00 It is locked.}
{9628}{}{|0xFFFF00 It is closed.}
{9629}{}{Code: |0xFFFF00 @lex code@|0x3CF800 .}
{9631}{}{Knock}
{9632}{}{Smash}
{9633}{}{Lockpick}
{9634}{}{Lock}
{9635}{}{Unlock}
{9636}{}{Extract Key}
{9637}{}{Insert Key}

# item taking
{9638}{}{resists}
{9639}{}{tries to take something from target}
{9640}{}{|0xFFFF00 You are too tired to take anything from the target.}

# handcuffs
{9641}{}{You are about to bound yourself by: |0xFFFF00 @lex proto@|0x3CF800 .}
{9642}{}{You are being bound by: |0xFFFF00 @lex proto@|0x3CF800 .}
{9643}{}{Agree}
{9644}{}{|0xFFFF00 You submit!}
{9645}{}{|0xFFFF00 The subject submits!}
{9646}{}{|0xFFFF00 The subject dared to resist!}
{9647}{}{|0xFFFF00 You are waiting for the subject to submit.}
{9648}{}{|0xFFFF00 Your hands are tied!}

{9649}{}{|0xFFFF00 You must have a key in your inventory.} # TODO: reorder the whole file to return that into the original position #9602

# Decraft and repair
{9650}{}{|0xFFFF00 This item is not subject to deterioration.}
{9651}{}{|0xFF0000 You are injured and can't perform maintenance.}
{9652}{}{|0xFFFF00 This can't be repaired!}
{9653}{}{|0xFF0000 You are injured and can't de-craft the item.}
{9654}{}{completes disassembly}
{9655}{}{|0xFF0000 You lack the skill to do this.}
{9656}{}{completes repairing}
{9657}{}{|0xFFFF00 This armor already has an internal radio set.}
{9658}{}{completes installing radio set into the armor}
{9659}{}{|0xFFFF00 This armor can't be repainted.}
{9660}{}{|0xFF0000 You are injured and are unable to repaint the armor.}
{9661}{}{completes repainting the armor}
{9662}{}{|0xFF0000 You are injured and are unable to install the radio.}
{9663}{}{Required instrument: }
{9664}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9665}{}{Required parts: }
{9666}{}{|0x3CF800  - |0xFFFF00 @lex proto@|0x3CF800  - |0xFFFF00 @lex amount@|0x3CF800  pcs.}
{9667}{}{You need to hold any of: }
{9668}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9669}{}{Acquired parts: }
{9670}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9671}{}{You've de-crafted |0xFFFF00 @lex proto@|0x3CF800 , gaining: }
{9672}{}{|0x3CF800  - |0xFFFF00 @lex proto@ }
{9673}{}{|0xFFFF00 You did not manage to install the radio!}
{9674}{}{|0x3CF800 You need the following skills:
 - |0xFFFF00 Science |0x3CF800  -  |0xFFFF00 150|0x3CF800 ,
 - |0xFFFF00 Repair |0x3CF800  -  |0xFFFF00 200|0x3CF800 .}
{9675}{}{You require the tools below and must hold any one of them: }

# Flasks and bottles
{9750}{}{|0xFFFF00 Your anatomy prevents you from opening the bottle!}
{9751}{}{|0xFFFF00 You have nothing to open the bottle with!}
{9752}{}{You have opened the bottle of |0xFFFF00 @lex proto@|0x3CF800.}
{9753}{}{opens the bottle}
{9754}{}{|0xFFFF00 You must hold the item!}
{9755}{}{|0xFFFF00 Try another way to fill the bottle.}
{9756}{}{|0xFFFF00 You have run out of bottles.}
{9757}{}{|0xFFFF00 You have poured out all the liquid.}
{9758}{}{|0xFFFF00 Container is filled with something else.}
{9759}{}{fills @lex proto@}
{9760}{}{|0xFFFF00 You must hold the container in your hand.}
{9761}{}{|0xFFFF00 The container is empty.}
{9762}{}{pours out of @lex proto@}
{9763}{}{|0xFFFF00 Container is already filled up.}
{9764}{}{|0xFFFF00 You have filled up the container.}
{9765}{}{|0xFFFF00 Container is empty.}
{9766}{}{|0xFFFF00 There is no more liquid.}
{9767}{}{|0xFFFF00 You don't have a bottle in your hands.}
{9768}{}{|0xFFFF00 You have filled the bottle.}

# Oxygen Tank
{9769}{}{Turns on the oxygen tank}
{9770}{}{Turns off the oxygen tank}
{9771}{}{Oxygen tank depleted.}
{9772}{}{Tere is no oxygen in the tank.}
{9773}{}{Oxygen left: @lex charge@}
{9774}{}{Before doing that, you turned off the previous oxygen tank you've used.}
{9775}{}{}

# Motion Sensor
{9780}{}{:ping:}
{9781}{}{|0xFFFF00 The motion sensor has no charge left!}
{9782}{}{enables motion sensor}
{9783}{}{disables motion sensor}

# Smoking
{9786}{}{ignites smokeable}
{9787}{}{opens a pack of cigarettes}
{9788}{}{|0xFFFF00 There are no cigarettes left in the pack.}
{9789}{}{takes a cigarette out of the pack}
{9790}{}{|0xFFFF00 You need to ignite your item to smoke.}
{9791}{}{|0xFFFF00 You can't smoke through a gas mask.}
{9792}{}{|0xFFFF00 You have to hold the object to start smoking.}
{9793}{}{|0xFFFF00 Smoking pipe is empty.}
{9794}{}{|0xFFFF00 Your smoking item has burned out.}
{9795}{}{|0xFFFF00 You fill the smoking pipe.}
{9796}{}{|0xFFFF00 You emptied the bag.}
{9797}{}{|0xFFFF00 You have to hold a smoking pipe to fill it.}
{9798}{}{|0xFFFF00 You taste tobacco.}
{9799}{}{|0xFFFF00 You taste fiveleaf.}

# Various Items
{9800}{}{takes a picture}
{9801}{}{removes ash}
{9802}{}{removes remains}
{9803}{}{wipes blood}
{9804}{}{|0xFFFF00 You have partially removed some remains.}
{9805}{}{|0xFFFF00 You have collected remains.}
{9806}{}{|0xFFFF00 You must have the musical instrument in your hand.}
{9807}{}{plays the flute}
{9808}{}{|0xFFFF00 Try digging closer to yourself.}
{9809}{}{|0xFFFF00 There is no sand in this spot.}
{9810}{}{|0xFFFF00 Input item description.}
{9811}{}{|0xFFFF00 It looks like you have no idea what to do with that.}
{9812}{}{|0xFFFF00 You have to take the item out of the container first!}
{9813}{}{|0xFFFF00 This item now has distinct description.}
{9814}{}{|0xFFFF00 You have removed all special features from the item.}
{9815}{}{lights the lamp}
{9816}{}{|0xFFFF00 You require a lighter to fire up the lamp!}
{9817}{}{|0xFFFF00 There is no oil in the lamp.}
{9818}{}{extinguishes the lamp}
{9819}{}{turns on the flashlight}
{9820}{}{|0xFFFF00 The flashlight has no charge left.}
{9821}{}{turns off the flashlight}
{9822}{}{ignites flare}
{9823}{}{extinguishes the flare}
{9824}{}{wipes with a towel}
{9825}{}{wipes with a dirty towel}
{9826}{}{washes the towel}
{9827}{}{replaces battery}
{9828}{}{fuels the lamp}
{9829}{}{|0xFFFF00 You did not manage to fit the item in the container.}
{9830}{}{ Serial number: }

# Ropes and shackles
{9831}{}{|0xFFFF00 You can't free yourself this way.}
{9832}{}{|0xFFFF00 This won't help here.}
{9833}{}{frees the target}
{9834}{}{gets free}
{9835}{}{|0xFFFF00 You really require a crowbar.}
{9836}{}{frees the target from the snare}
{9837}{}{gets free from the snare}
{9838}{}{|0xFFFF00 You are free from the snare!}
{9839}{}{|0xFFFF00 The key does not fit.}
{9840}{}{|0xFFFF00 The bound is broken.}
{9841}{}{|0xFFFF00 This is pointless, the target is dead!}
{9842}{}{|0xFFFF00 Target already bound by similar item!}

{9843}{}{binds their hands with handcuffs}
{9844}{}{binds the subject's hands with handcuffs}
{9845}{}{|0xFFFF00 You have handcuffed yourself.}
{9846}{}{|0xFFFF00 Your hands are now bound by handcuffs!}
{9847}{}{|0xFFFF00 Your hands have been freed from the handcuffs.}
{9848}{}{takes their handcuffs off}
{9849}{}{takes the subject's handcuffs off}

{9850}{}{ties their hands}
{9851}{}{ties the subject}
{9852}{}{|0xFFFF00 You have tied yourself up!}
{9853}{}{|0xFFFF00 You have been tied up!}
{9854}{}{|0xFFFF00 Your hands have been untied.}
{9855}{}{cuts their bindings}
{9856}{}{cuts the subject's bindings}

{9857}{}{puts shackles around their leg}
{9858}{}{binds the subject's legs with shackles}
{9859}{}{|0xFFFF00 You have put shackles on yourself.}
{9860}{}{|0xFFFF00 Your legs are now bound by shackles!}
{9861}{}{|0xFFFF00 Your legs have been freed from the shackles.}
{9862}{}{takes their shackles off}
{9863}{}{takes the subject's shackles off}

{9864}{}{puts ball gag in their mouth}
{9865}{}{puts ball gag in subject's mouth}
{9866}{}{|0xFFFF00 You've put a ball gag in your mouth.}
{9867}{}{|0xFFFF00 A ball gag has been put in your mouth.}
{9868}{}{|0xFFFF00 A ball gag has been taken out of your mouth.}
{9869}{}{removes the ball gag from their mouth}
{9870}{}{removes the ball gag from the subject's mouth}

{9871}{}{puts gag in their mouth}
{9872}{}{puts gag in subject's mouth}
{9873}{}{|0xFFFF00 You've put a gag in your mouth.}
{9874}{}{|0xFFFF00 A gag has been put in your mouth.}
{9875}{}{|0xFFFF00 A gag has been taken out of your mouth.}
{9876}{}{removes the gag from their mouth}
{9877}{}{removes the gag from the subject's mouth}

{9878}{}{puts a slave collar on their neck}
{9879}{}{puts a slave collar on the slave's neck}
{9880}{}{|0xFFFF00 You've put a slave collar on yourself.}
{9881}{}{|0xFFFF00 You now have your own personal decorative slave collar.}
{9882}{}{|0xFFFF00 The slave collar on your neck opened.}
{9883}{}{removes the slave collar from their neck}
{9884}{}{removes the slave collar from the slave's neck}

{9885}{}{|0xFFFF00 You have repaired the handcuffs.}
{9886}{}{|0xFFFF00 You have repaired the shackles.}
{9887}{}{|0xFFFF00 You have to untie your hands to do that.}
{9888}{}{|0xFFFF00 Dogs are incapable of this action.}
{9889}{}{|0xFFFF00 This armor is not designed for your race.}

{9890}{}{|0xFFFF00 You have released the slave.}
{9891}{}{|0xFFFF00 You have punished the slave.}
{9892}{}{|0xFFFF00 Your neck is burning, your body is shaking.}
{9893}{}{shakes in agony}
{9894}{}{|0xFFFF00 Your neck is burning and your body shakes with multiple electric strikes.}
{9895}{}{|0xFFFF00 Your neck is burning your body shakes under intolerable pain.}
{9896}{}{|0xFFFF00 You have executed the slave.}
{9897}{}{|0xFFFF00 The pain of a thousand needles shakes you.}
{9898}{}{presses a button}

# Forgot to activate character
{9899}{}{takes one step too many and is reduced to nothing}

# General stuff
{9900}{}{panting}
{9901}{}{rubs a bruise}
{9902}{}{shouts in pain}
{9903}{}{grabs wounded limb, trying to stop blood}
{9904}{}{screams in pain}
{9905}{}{screams in agony}
{9906}{}{slipped on something disgusting}
{9907}{}{You have dropped |0xFFFF00 @lex proto@ |0x3CF800 from your hands.}
{9908}{}{|0xFFFF00 You are damaged by acid.}
{9909}{}{bandages target}
{9910}{}{applies bandage}
{9911}{}{|0xFFFF00 This did nothing.}
{9912}{}{starts inspecting the body}

#Harmonica
{9913}{}{plays the harmonica}

# Key duplicate
{9914}{}{|0xFFFF00 You have successfully duplicated a key.}

# X2 X3 containers
{9915}{}{|0xFFFF00 Container is full. You have to free up some space to take take the top container.}

# Sandbags
{9916}{}{|0xFFFF00 You can't make a sandbag stack any higher.}
{9917}{}{|0xFFFF00 A critter is preventing you from placing the sandbag.}

# Locks
{9918}{}{|0xFFFF00 You can't put a lock on the terminal.}
{9919}{}{|0xFFFF00 You require a single metal part to make a key for the lock.}
{9920}{}{|0xFFFF00 The door already has the lock, you need to dismantle current lock first, the |0xABABAB Tools |0xFFFF00 will be useful.}
{9921}{}{|0xFFFF00 You must close the door for this.}
{9922}{}{|0xFFFF00 This object can't be locked.}

# Dismantling/securing items
{9923}{}{|0xFFFF00 The item is dismantled, you can now move it to a new place.}
{9924}{}{|0xFFFF00 The item is firmly secured.}

# Carry Items
{9925}{}{|0xFFFF00 You can't pick this up!}
{9926}{}{|0xFFFF00 It's too heavy!}
{9927}{}{|0xFFFF00 You can't pick this up because you are already carrying the maximum allowed weight!}
{9928}{}{|0xFFFF00 You can't pick this up because your items take up too much volume.}

#Furniture
{9929}{}{|0xFFFF00 You don't have the right key.}
{9930}{}{|0xFFFF00 You must have the key or the keyring containing the right key in your hand.}
{9931}{}{stops}
{9932}{}{|0xFFFF00 This won't fit in here.}
{9933}{}{|0xFFFF00 Dismantling is required.}
{9934}{}{|0xFFFF00 That did nothing.}
{9935}{}{|0xFFFF00 The container is locked.}
{9936}{}{|0xFFFF00 The object is too heavy!}
{9937}{}{|0xFFFF00 You can't move this object without opening the lock first.}
{9938}{}{|0xFFFF00 The object is movable. Use [Repair] to change the object state.}
{9939}{}{|0xFFFF00 The object is immovable. Use [Repair] to change the object state.}
{9940}{}{tries to stop}
{9941}{}{|0xFFFF00 You can't move locked or closed furniture.}
{9942}{}{starts pushing}
{9943}{}{|0xFFFF00 You can't make a stack any higher.}
{9944}{}{|0xFFFF00 A critter is preventing you from placing the object.}
#TODO: {9945}{}{starts pulling}
#TODO: {9946}{}{The cart it fitting only for empty containers!}
#TODO: {9947}{}{flips over}
#TODO: {9948}{}{adjusts}
#TODO: {9949}{}{|0xFFFF00 The object is passable.}
#TODO: {9950}{}{|0xFFFF00 The object is unpassable.}

# No access to mob control
{9945}{}{|0xFFFF00 You require GM access.}

# h-attack
{9946}{}{|0xFFFF00 You can't fight with that.}

# use radio
{9947}{}{speaks through radio set}

# #zh - command
{9948}{}{|0xFFFF00 You have sent @lex critter@ to home position.}
{9949}{}{|0xFFFF00 Critter @lex critter@ is already at home position.}

# push target
{9950}{}{|0xFFFF00 You push the target.}
{9951}{}{|0xFFFF00 Target resisted.}

# ~naked - command
{9952}{}{undresses}

# #desc - command
{9954}{}{|0xFFFF00 Something catches your eye:
|0xABABAB @lex desc@}

# Throw
{9958}{}{|0xFFFF00 You can't throw that far.}
{9959}{}{|0xFFFF00 You can't throw that object.}
{9960}{}{catches item}
{9961}{}{failed to catch item}
{9962}{}{:shatters into pieces:}
{9963}{}{throws item}

# Knocking
{9964}{}{|0xFFFF00 Not enough action points.}
{9965}{}{|0xFFFF00 You can't do that.}
{9966}{}{|0xFFFF00 You've missed the target.}
{9967}{}{|0xFFFF00 You can't knock that often.}
{9968}{}{:knock:}
{9969}{}{|0xFFFF00 You have knocked.}
{9970}{}{|0xFFFF00 You are too far!}

# Code door password
{9971}{}{You set a new code: |0xFFFF00 @lex code@}
{9972}{}{|0xFFFF00 Wrong code format!}
{9973}{}{|0xFFFF00 Wrong code!}

# Change Lex self
{9974}{}{|0xFFFF00 You have changed your own description.}
# TODO:{9975}{}{|0xFFFF00 You have enabled AFK-mode.}
# TODO:{9976}{}{|0xFFFF00 You have disabled AFK-mode.}

# Digits input
{9975}{}{You set a new password: |0xFFFF00 @lex digits@}
{9976}{}{|0xFFFF00 You input the correct password!}
{9977}{}{|0xFFFF00 You input an incorrect password!}

# Suicide
{9978}{}{performs harakiri...}
{9979}{}{tries to choke them self...}
{9980}{}{spins the cylinder and puts the gun to their head...}
{9981}{}{puts the barrel in their mouth...}
{9982}{}{points the gun at their abdomen, with the finger on the trigger...}
{9983}{}{holds grenade to their chest and pulls the pin...}
{9984}{}{opens a bottle and pours liquid all over themselves, takes a lighter from their pocket...}
{9985}{}{presses sharp object to their belly...}
{9986}{}{is about to swallow the contents of a vial...}
{9987}{}{|0xFFFF00 You have nothing to kill yourself with.}
{9988}{}{blows own brains out}
{9989}{}{skull explodes with a fountain of blood, covering everything nearby with it}
{9991}{}{multiplies by two}
{9992}{}{head evaporates in an instant}
{9993}{}{body is shaking under electrical charge}
{9994}{}{tried to kill oneself wasting ammo, while weapon awkwardly falls to the ground}
{9995}{}{trigger guard flies to the side}
{9996}{}{|0xFFFF00 The grenade went off without any effect.}
{9997}{}{drinks the vial}
{9998}{}{sets themselves ablaze, the fire consumes everything nearby}

# Toilet
{9999}{}{flushes something down the toilet}

# StartMap
{10000}{}{|0xFFFF00 Error, please contact GM.}
{10001}{}{|0xFFFF00 The Start of the game is possible for new characters only.}
{10002}{}{|0xFFFF00 The Start of the game is possible only on a starting location.}
{10003}{}{|0xFFFF00 Please try again.}
{10004}{}{|0xFFFF00 Survival mode selected.}
{10005}{}{|0xFFFF00 Area not found.}
{10006}{}{|0xFFFF00 Map not found.}
{10007}{}{|0xFFFF00 This region is filled with sadness, but it seems like the next few steps forward will change your destiny...}
{10008}{}{|0xFFFF00 The item was consumed by the void.}
{10009}{}{|0xFFFF00 You can't do that}

# GM Mode
{10010}{}{|0xFFFFFF GM mode enabled.}
{10011}{}{|0x606060 GM mode disabled.}
{10012}{}{|0xFFFFFF GM-stealth mode enabled.}
{10013}{}{|0x606060 GM-stealth mode disabled.}
{10014}{}{|0xFFFFFF Hotkeys are on.}
{10015}{}{|0x606060 Hotkeys are off.}

{10016}{}{|0xFFFF00 You have enabled AFK-mode.} # TODO: reorder whole file to return that back into original position #9975
{10017}{}{|0xFFFF00 The item on your back is preventing you from changing clothes.}	# TODO: reorder whole file to return that back into original position #9890
{10018}{}{|0xFFFF00 Your item is too broken to equip.} # TODO: reorder whole file to return that back into original position #9891
{10019}{}{|0xFFFF00 Your tool shattered} # TODO: reorder whole file to return that back into original position #9900
{10020}{}{|0xFFFF00 You can't get rid of suffering in this place so easily!} # TODO: reorder whole file to return that back into original position #9978

{10021}{}{|0xFFFF00 No access to the database.}
{10022}{}{starts pulling} # TODO: reorder whole file to return that back into original position #9945
{10023}{}{|0xFFFF00 You have disabled AFK-mode.} # TODO: reorder whole file to return that back into original position #9976
{10024}{}{|0xFFFF00 The cart it fitting only for empty containers!} # TODO: reorder whole file to return that back into original position #9946
{10025}{}{flips over} # TODO: reorder whole file to return that back into original position #9947
{10026}{}{adjusts} # TODO: reorder whole file to return that back into original position #9948
{10027}{}{|0xFFFF00 The object is passable.} # TODO: reorder whole file to return that back into original position #9949
{10028}{}{|0xFFFF00 The object is unpassable.} # TODO: reorder whole file to return that back into original position #9950
	
#Grid_to_global_warning
{15000}{}{|0xFFFF00 You are getting scared.}
{15000}{}{|0xFFFF00 You have nowhere else to go.}
{15000}{}{|0xFFFF00 You see only dead wasteland in front of you and understand that going there will condemn you to certain death. You have no choice but to continue your miserable existence here, fighting for a piece of meat with other people and animals.}
{15000}{}{|0xFFFF00 There is no life there.}
{15000}{}{|0xFFFF00 Nothing is waiting for you there.}

# lifts:
# {2GG00} is the key card item proto name from data/ItemNames.lst where GG is lifts group
# {2GGFF} is the floor name where GG is the lifts group, FF is the floor

{20100}{}{PID_V15_KEYCARD}
{20101}{}{4 - Bridge}
{20102}{}{3 - Planning Center}
{20103}{}{2 - Barracks}
{20104}{}{1 - Mess Hall}
{20105}{}{0 - Sun Deck}

{20201}{}{1 - Trading Deck}
{20202}{}{2 - Recreation Deck}
{20203}{}{3 - Industrial Deck}
{20204}{}{4 - The Hole}

{20301}{}{4 - Suites}
{20302}{}{3 - Business rooms}
{20303}{}{2 - Economy rooms}
{20304}{}{1 - Club}
{20305}{}{0 - Lobby}

{20400}{}{PID_SECURITY_CARD}
{20401}{}{1 - Surface}
{20402}{}{2 - Bunker}
{20403}{}{3 - Technical level}

{20500}{}{PID_TERMINAL_METAL_KEY}
{20501}{}{0 - Surface}
{20502}{}{1 - Chemical Plant}

{20601}{}{1 - First Floor}
{20602}{}{0 - Lobby}

{20700}{}{PID_TERMINAL_METAL_KEY}
{20701}{}{1 - Topside}
{20702}{}{0 - Perfection}

{20801}{}{1 - Entrance level}
{20802}{}{2 - Living Blocks}
{20803}{}{3 - Control level}
{20804}{}{4 - Industrial level}

{20901}{}{0 - Command Deck}
{20902}{}{1 - Entrance level}

{21000}{}{PID_RED_PASS_KEY}
{21001}{}{0 - Lobby}
{21002}{}{1 - Level 1}
{21003}{}{2 - Level 2}

{21100}{}{PID_BLUE_PASS_KEY}
{21101}{}{0 - Shelter}
{21102}{}{1 - Station}

{21200}{}{PID_BLUE_PASS_KEY}
{21201}{}{0 - Surface}
{21202}{}{1 - level 1}

{21300}{}{PID_YELLOW_PASS_KEY}
{21301}{}{0 - Surface}
{21302}{}{1 - level 1}

{21400}{}{PID_RED_PASS_KEY}
{21401}{}{0 - level 1}
{21402}{}{1 - level 2}

{21500}{}{PID_YELLOW_PASS_KEY}
{21501}{}{1 - Central Shelter}
{21502}{}{2 - Station}

{21601}{}{0 - Shelter}
{21602}{}{1 - Station}

{21701}{}{0 - Surface}
{21702}{}{1 - Level 1}
{21703}{}{2 - Level 2}

{21801}{}{0 - Level 3}
{21802}{}{1 - Level 2}
{21803}{}{2 - Level 1}

{21901}{}{1 - Level 3}
{21902}{}{2 - Level 2}

{22001}{}{1 - Level 2}
{22002}{}{0 - Level 1}

{22101}{}{1 - Level 3}
{22102}{}{0 - Level 2}

{22201}{}{2 - Level 3}
{22202}{}{1 - Level 2}
{22203}{}{0 - Level 1}

{22301}{}{1 - Level 3}
{22302}{}{0 - Level 2}

{22401}{}{1 - Level 1}
{22402}{}{2 - Level 2}
{22403}{}{3 - Level 3}
{22404}{}{4 - Level 4}

{22501}{}{0 - Surface}
{22502}{}{1 - Level 1}
{22503}{}{2 - Level 2}

{22600}{}{PID_BLUE_PASS_KEY}
{22601}{}{0 - Central Shelter}
{22602}{}{1 - Station}

{22701}{}{1 - Level 1}
{22702}{}{2 - Level 2}

{22801}{}{0 - Surface}
{22802}{}{1 - Level 1}

{22901}{}{1 - Level 1}
{22902}{}{2 - Level 2}

#Scav demo vault

{23001}{}{1 - Level 1}
{23002}{}{2 - Level 2}

{23100}{}{PID_TERMINAL_ADVANCED_KEY}
{23101}{}{1 - Level 2}
{23102}{}{2 - Level 3}

{23201}{}{1 - Уровень 1}
{23202}{}{2 - Уровень 2}

#Rado Springs

{23301}{}{0 - Ground Floor}
{23302}{}{1 - First Floor}
{23303}{}{2 - Second Floor}
{23304}{}{3 - Third Floor}

{23401}{}{0 - Ground Floor}
{23402}{}{1 - First Floor}
{23403}{}{2 - Second Floor}
{23404}{}{3 - Third Floor}
{23405}{}{4 - Fourth Floor}
{23406}{}{5 - Fifth Floor}
{23407}{}{6 - Sixth Floor}

{23500}{}{PID_RED_PASS_KEY}
{23501}{}{0 - GrouИd}
{23502}{}{1 - TraDe}
{23503}{}{2 - MacHeeneZ}
{23504}{}{3 - RooMs I}
{23505}{}{4 - 4iLГ}

{23600}{}{PID_YELLOW_PASS_KEY}
{23601}{}{1 - tЯade}
{23602}{}{5 - Гabs}
{23603}{}{6 - Morkout}
{23604}{}{7 - Яooms II}
{23605}{}{8 - Rooms III}

{23701}{}{0 - Main Area}
{23702}{}{1 - GenOps}
{23703}{}{2 - Ref}

{23801}{}{2 - Second Floor}
{23802}{}{4 - Fourth Floor}

{23901}{}{0 - Ground Floor}
{23902}{}{1 - First Floor}
{23903}{}{2 - Second Floor}
{23904}{}{3 - Third Floor}
{23905}{}{4 - Fourth Floor}
{23906}{}{5 - Fifth Floor}
{23907}{}{6 - Sixth Floor}
{23908}{}{7 - Seventh Floor}
{23909}{}{8 - Eighth Floor}
{23910}{}{9 - Nineth Floor}
{23911}{}{10 - Tenth Floor}

{24001}{}{0 - Ground Fxxor}
{24002}{}{1 - Fixxt Floor}
{24003}{}{2 - Second Floor}
{24004}{}{3 - Txxrd Floor}
{24005}{}{4 - Fourth Floor}
{24006}{}{5 - Fxxth Floor}

{24101}{}{Floor 0}
{24102}{}{Floor 1}
{24103}{}{Floor 2}
{24104}{}{Floor 3}
{24105}{}{Fxxxx X}

{24201}{}{G}
{24202}{}{I}
{24203}{}{II}
{24204}{}{III}

{24300}{}{PID_SECURITY_CARD}
{24301}{}{0 - Ground Floor}
{24302}{}{1 - First Floor}
{24303}{}{2 - Second Floor}
{24304}{}{3 - Third Floor}
{24305}{}{4 - Fourth Floor}
{24306}{}{5 - Fifth Floor}
{24307}{}{6 - Sixth Floor}
{24308}{}{7 - Seventh Floor}
{24309}{}{8 - Eighth Floor}
{24310}{}{9 - Nineth Floor}
{24311}{}{10 - Tenth Floor}
{24312}{}{11 - Eleventh Floor}
{24313}{}{12 - Twelfth Floor}
{24314}{}{13 - Thirteenth Floor}
{24315}{}{14 - Fourteenth Floor}

{24400}{}{PID_BLUE_PASS_KEY}
{24401}{}{0 - Reception}
{24402}{}{4 - Engineering Dept}
{24403}{}{5 - Assembly Dept}
{24404}{}{6 - Showroom}
{24405}{}{7 - Sales Dept}
{24406}{}{12 - Warehouse}
{24407}{}{13 - Top Floor}

{24501}{}{0 - Ground Floor}
{24502}{}{1 - First Floor}
{24503}{}{2 - Second Floor}
{24504}{}{3 - Third Floor}
{24505}{}{4 - Fourth Floor}

{24601}{}{0 - Ground Floor}
{24602}{}{1 - First Floor}
{24603}{}{2 - Second Floor}
{24604}{}{3 - Third Floor}
{24605}{}{4 - Fourth Floor}

{24701}{}{1 - First Floor}
{24702}{}{0 - Lobby}

# =========================
# Translation feature:
# =========================

#devices 99500 - 99600
{99501}{}{Online}
{99502}{}{Offline}
{99503}{}{Activate}
{99504}{}{Deactivate}
{99505}{}{Increase radius}
{99506}{}{Decrease radius}
{99507}{}{Insert @lex balance_change@ $}
{99508}{}{Change}
{99509}{}{Input price}
{99510}{}{Enabled}
{99511}{}{Disabled}
{99512}{}{Assigned}
{99513}{}{Controlled}
{99514}{}{Active}
{99515}{}{Connect}
{99516}{}{Reset}

#firestarter commands 99600 - 99700
{99601}{}{@lex firestate@ The object is filled with fuel to |0xFFFF00 @lex occupancy_level@|0x3CF800 % of it's capacity.

   Choose your action:}
{99602}{}{Ignite}
{99603}{}{Extinguish}
{99604}{}{Add fuel}
{99605}{}{Cook}
{99606}{}{Fry}
{99607}{}{There is no fire burning, you may require fire fuel, a flint, or a lighter.}
{99608}{}{The fire is |0xFFFF00 burning|0x3CF800 .}
{99609}{}{The generator is |0xFFFF00 online|0x3CF800 .}

#furniture commands 99700 - 99800
{99701}{}{|0xF8F993 Weight: |0x00FF00 @lex weight@
@lex testInfo@
|0xF8F993 Volume: |0x00FF00 @lex volume@}
{99702}{}{Examine}
{99703}{}{Open Safe}
{99704}{}{Detach}
{99705}{}{Anchor}
{99706}{}{Pick up}
{99707}{}{Turn}
{99708}{}{Push}
{99709}{}{Stop}
{99710}{}{Lock}
{99711}{}{Unlock}
{99712}{}{Close}
{99713}{}{Open}
{99714}{}{Look inside}
{99715}{}{Craft}
{99716}{}{Smelt}
{99717}{}{Crusher Interface}
{99718}{}{Lockpick}
{99719}{}{Planting}
{99720}{}{Opened}
{99721}{}{Closed}
{99722}{}{Pull}
{99723}{}{Flip over}
{99724}{}{:items scatter on the ground:}
{99725}{}{Remove blocker}
{99726}{}{Place blocker}

{99750}{}{Mill interface}
{99760}{}{Sawhorse interface}
{99761}{}{@lex contains@

An axe is required to work with the sawhorse.}
{99762}{}{Saw}
{99763}{}{|0x3CF800 There is no suitable log on the sawhorse.}
{99764}{}{On the sawhorse there is |0xFFFF00 @lex item@ |0x3CF800 - |0xFFFF00 @lex amount@ |0x3CF800 pcs.}
{99765}{}{|0xFFFF00 The sawhorse is empty.}
{99766}{}{finishes the work}

{99770}{}{Anvil interface}

#generic text 99800 - 99900
{99801}{}{It's empty!}
{99802}{}{Amount:}
{99803}{}{Text:}
{99804}{}{On}
{99805}{}{Off}
{99806}{}{Previous}
{99807}{}{Next}
{99808}{}{Confirm}
{99809}{}{Decline}
{99810}{}{Cancel}
{99811}{}{ not}
{99812}{}{@lex description@}
{99813}{}{has @lex description@}
{99814}{}{no @lex description@}
{99815}{}{None}
{99816}{}{@lex name@}
{99817}{}{Yes}
{99818}{}{No}
{99819}{}{Male}
{99820}{}{Female}
{99821}{}{+}
{99822}{}{-}
{99823}{}{ERROR: @lex name@ not found!}
{99824}{}{Choose your action:}
{99825}{}{Do nothing}


#system buttons 99900 - 100000
{99901}{}{       Furniture Menu}
{99902}{}{          Close menu}
{99903}{}{           Hide menu}
{99904}{}{             Return}

{100000}{}{}

#player_menu.fos 100000 - 100050
{100001}{}{Hide face: [ |0xFFFF00 @lex face@ |0x3CF800 ]    Avatar: [ |0xFFFF00 @lex AvatarMode@ |0x3CF800 ]
Hide description: [ |0xFFFF00 @lex desc@ |0x3CF800 ] WSAD: [ |0xFFFF00 @lex WSAD@ |0x3CF800 ]
Hide typing: [ |0xFFFF00 @lex typing@ |0x3CF800 ]           RTS: [ |0xFFFF00 @lex RTS@ |0x3CF800 ]
Radio safety: [ |0xFFFF00 @lex radio@ |0x3CF800 ]         @lex STA@
Item visor: [ |0xFFFF00 @lex visor@ |0x3CF800 ]   NPC Icons: [ |0xFFFF00 @lex icon@ |0x3CF800 ]
Speech volume: [ |0xFFFF00 @lex volume@ |0x3CF800 ]}
{100002}{}{Face Hiding}
{100003}{}{Smart Target Assist}
{100004}{}{Hide Desc.}
{100005}{}{Hide Typing}
{100006}{}{Radio Safety}
{100007}{}{WSAD Movement}
{100008}{}{RTS Movement}
{100009}{}{Item Visor}
{100010}{}{Wall alpha: @lex alpha@}
{100011}{}{Increase Speech}
{100012}{}{Decrease Speech}
{100013}{}{Rolls}
{100014}{}{Animations}
{100015}{}{Actions}
{100016}{}{Enter Alpha: @lex vals@}
{100017}{}{STA: [ |0xFFFF00 @lex STA_status@ |0x3CF800 ]}
{100018}{}{Toggle Speech Radius}
{100019}{}{Toggle NPC Icons}

{100020}{}{Choose a Stat or type of dice to roll.
If stat is chosen the result will be your current stat value + 2d6.}
{100021}{}{Roll @lex stat@}
{100022}{}{Roll @lex dice@}
{100023}{}{|0xFFFF00 Dice amount must be a number!}
{100024}{}{SUCCESS}
{100025}{}{FAIL}
{100026}{}{Lie on belly}
{100027}{}{Lie on back}
{100028}{}{Devour}
{100029}{}{Attempt Suicide}
{100030}{}{Suggest sex}
{100031}{}{Get up}
{100032}{}{AFK Mode}
{100033}{}{Disable AFK Mode}
{100034}{}{Describe self}
{100035}{}{Describe item}
{100036}{}{Load Avatar}
{100037}{}{Check Id}
{100038}{}{Remember Name}
{100039}{}{Attempt Puke}

{100040}{}{Choose your animation:}
{100041}{}{Get up}
{100042}{}{Prone}
{100043}{}{Prone2}
{100044}{}{Lean}
{100045}{}{Lean2}
{100046}{}{Crouch}
{100047}{}{Kneel}
{100048}{}{Kneel2}
{100049}{}{Pushups}
{100050}{}{Squat}
{100051}{}{Flex}
{100052}{}{Crunches}

{100053}{}{Active Drugs} #TODO: REORDER PROPERTLY
{100054}{}{Current addictions:} #TODO: REORDER PROPERTLY
{100055}{}{   Stage               Drug Name                              Time} #TODO: REORDER PROPERTLY
{100056}{}{Consumed} #TODO: REORDER PROPERTLY
{100057}{}{Withdrawal} #TODO: REORDER PROPERTLY
{100058}{}{Addiction} #TODO: REORDER PROPERTLY
{100059}{}{Current effects:} #TODO: REORDER PROPERTLY

{100060}{}{Colorize critter}

#furnace.fos 100100 - 100110
{100100}{}{|0xFFFF00 Power|0x3CF800 : [ |0xFFFF00 @lex powerStatus@ |0x3CF800 ] |0xFFFF00 temp|0x3CF800 : @lex temp@C.
Smelted: 
@lex empty@
@lex iron@
@lex gold@
@lex led@
@lex nf_metal@
@lex glass@}
{100101}{}{|0xFFFF00 Fuel|0x3CF800 : @lex fuel@% |0xFFFF00 Temp|0x3CF800 : @lex temp@C. Smelted: 
@lex empty@@lex iron@@lex gold@@lex nf_metal@@lex glass@}
{100102}{}{|0xFFFF00 Iron|0x3CF800 : @lex ironW@ kg.}
{100103}{}{|0xFFFF00 Gold|0x3CF800 : @lex goldW@ kg.}
{100104}{}{|0xFFFF00 NF_metals|0x3CF800 : @lex nf_metalW@ kg.}
{100105}{}{|0xFFFF00 Glass|0x3CF800 : @lex glassW@ kg.}

#smithing:anvil 100110 - 100120
{100111}{}{@lex contains@ To work with that anvil you must hold some kind of sledgehammer.}
{100112}{}{Smith}
{100113}{}{|0x3CF800 There is no appropriate metal ingot on the anvil.}
{100114}{}{There is a |0xFFFF00 @lex item@ |0x3CF800 on the anvil - |0xFFFF00 @lex amount@ |0x3CF800  pcs.}

#smithing:crusher 100120 - 100130
{100121}{}{|0xFFFF00 Power|0x3CF800 : [ |0xFFFF00 @lex powerStatus@ |0x3CF800 ] |0xFFFF00 
@lex contains@}
{100122}{}{Put drugged inside}
{100123}{}{|0x3CF800 The crusher 2000 storage is empty.}
{100124}{}{The production line is loaded with: |0xFFFF00 @lex item@ |0x3CF800 - |0xFFFF00 @lex amount@ |0x3CF800  pcs.}
{100125}{}{|0x3CF800 The crusher 2000 contains junk.}

#Milling
{100131}{}{@lex contains@}
{100132}{}{Mill}
{100133}{}{|0x3CF800 There is no appropriate resource in the mill.}
{100134}{}{There is a |0xFFFF00 @lex item@ |0x3CF800 in the mill - |0xFFFF00 @lex amount@ |0x3CF800  pcs.}

#bootlegging.fos	100150 - 100200
{100151}{}{Still is @lex state@
Raw product: |0xFFFF00 @lex raw@ |0x3CF800 l.
Fuel: |0xFFFF00 @lex fuel@ |0x3CF800 %
Distilled |0xFFFF00 @lex product@ |0x3CF800 liters of moonshine.}
{100152}{}{Add homebrew}
{100153}{}{Clean the still}
{100154}{}{Pour moonshine}
{100155}{}{Still repair}
{100156}{}{Close the gate}
{100157}{}{Gate to 25%}
{100158}{}{Gate to 50%}
{100159}{}{Gate to 75%}
{100160}{}{Open the gate}
{100161}{}{not burning}
{100162}{}{burning,
Temperature: |0xFFFF00 @lex temp@ |0x3CF800 C.
Pressure: |0xFFFF00 @lex press@ |0x3CF800 bar.}
{100163}{}{|0xFFFF00 Is closed.}
{100164}{}{|0xFFFF00 25% open.}
{100165}{}{|0xFFFF00 Half-open}
{100166}{}{|0xFFFF00 75% open.}
{100167}{}{|0xFFFF00 Fully open.}
{100168}{}{EMERGENCY VENT}
{100169}{}{Vents extra heat}
{100170}{}{is broken}

#casino 100200 - 100220
{100201}{}{Slot machine № @lex casinoId@
Only coins!

@lex status@

@lex balance@}
{100202}{}{Bet 5 $}
{100203}{}{Bet 10 $}
{100204}{}{Bet 25 $}
{100205}{}{Bet 50 $}
{100206}{}{Bet 100 $}
{100207}{}{Gather cards}
{100208}{}{Gather deck}
{100209}{}{JACKPOT: |0xFFFF00 x@lex mul@ |0x3CF800 your bet!}
{100210}{}{There is no money in the machine.}
{100211}{}{Your balance: |0xFFFF00 @lex cash@|0x3CF800 $}
{100212}{}{You require coins to play.}
{100213}{}{Choose your action with deck:}
{100214}{}{Caps}
{100215}{}{Coins}
{100216}{}{Change wallet type.}


#fish 100220 - 100250
{100221}{}{@lex pullOutFish@}
{100222}{}{Drag}
{100223}{}{Strike}
{100224}{}{Pull out}
{100225}{}{Cut the fishing line}
{100226}{}{The fish is gone!}
{100227}{}{There is a fish on the hook!
Depth: |0xFFFF00 @lex fishDepth@|0x3CF800
Fish size: |0xFFFF00  @lex fishSize@ |0x3CF800
Fish action: |0xFFFF00 @lex fishAction@ |0x3CF800}
{100228}{}{You can't determine.}
{100229}{}{Is pulling}
{100230}{}{Moves rapidly}


#jukebox 100250 - 100280
{100251}{}{@lex descriptionJukeBox@}
{100252}{}{Mode: @lex modeJukebox@}
{100253}{}{Play Tune}
{100254}{}{Jukebox № |0xFFFF00 @lex jukeboxId@ |0x3CF800 @lex selectTune@ Sound radius: |0xFFFF00 @lex soundRadius@
|0x3CF800 Mode: |0xFFFF00 @lex modeJukeboxDisc@ |0x3CF800 
Price for tune: |0xFFFF00 @lex priceTune@|0x3CF800 $ Balance: |0xFFFF00 @lex balanceJukebox@|0x3CF800 $
@lex statusJukebox@ }
{100255}{}{Single tune}
{100256}{}{Continuous}
{100257}{}{Selected tune: 
[ |0xFFFF00 @lex selectedTuneJukebox@ |0x3CF800 ]
Playtime: |0xFFFF00 @lex durationTune@|0x3CF800 .}
{100258}{}{Select the tune!}
{100259}{}{     Press [ |0xFFFF00 Play Tune |0x3CF800 ] !}
{100260}{}{     The tune is playing.}


#sex 100280 - 100310
{100281}{}{@lex descriptionSex@}
{100282}{}{Protection: @lex protectionSex@}
{100283}{}{Mode: @lex modeSex@}
{100284}{}{Position: @lex positionSex@}
{100285}{}{Make offer}
{100286}{}{@lex offeredSexDesc@
Sex mode: |0xFFFF00 @lex modeSexDesc@|0x3CF800 
Protection: |0xFFFF00 @lex protectionSexDesc@|0x3CF800 
Position: |0xFFFF00 @lex positionSexDesc@|0x3CF800 }
{100287}{}{You are about to make an offer to have sex to your partner:}
{100288}{}{You have made an offer to have sex to your partner. 
And are now waiting for the response.}
{100289}{}{You are being offered to have sex!
It's up to you now to decide on the way to do it:}
{100290}{}{Condom}
{100291}{}{Black Screen}
{100292}{}{Animate}
{100293}{}{Classic}
{100294}{}{Doggie}
{100295}{}{Oral}
{100296}{}{Missionary}


#repair 100310 - 100330
{100311}{}{Item Action Menu
Item: |0xFFFF00 @lex itemRepair@|0x3CF800 
@lex deteriorationRepair@@lex service@@lex serviceExt@
Broken: |0xFFFF00 @lex brokenRepair@ |0x3CF800 times.}
{100312}{}{Repair}
{100313}{}{Set frequency}
{100314}{}{Dismantle}
{100315}{}{Install Radio}
{100316}{}{Paint Armour}
{100317}{}{Stow Weapons}
{100318}{}{Choose paint colour}
{100319}{}{Deterioration: |0xFFFF00 @lex commonDeterioration@|0x3CF800 %}
{100320}{}{
@lex serviceState@}
{100321}{}{
@lex serviceExtState@}


#heal 100330 - 100420
{100331}{}{@lex pulse@@lex poisoning@@lex radiation@@lex bleeding@.@lex typeTraumas@}
{100332}{}{Pulse normal}
{100333}{}{Weak pulse}
{100334}{}{, signs of poisoning}
{100335}{}{, signs of radiation sickness}
{100336}{}{, bleeding}
{100337}{}{
There is a bullet or a shard in the wound, that requires to be removed before anything else is done.}
{100338}{}{
A heavy wound that requires to be closed.
}
{100339}{}{
Nothing is requiring a doctor.}
{100340}{}{Extraction}
{100341}{}{Surgery}
{100342}{}{Traumas}
{100343}{}{Begin}	
{100344}{}{Medical check}
{100345}{}{pluck out}
{100346}{}{blade}
{100347}{}{painkillers}
{100348}{}{stich}
{100349}{}{burn}
{100350}{}{bandage}
{100351}{}{brace}
{100352}{}{fix limb}
{100353}{}{disinfecting}
{100354}{}{Remove @lex subDressing@}
{100355}{}{Improvised @lex subImprovised@}
{100356}{}{Nothing to @lex subNothing@ with}
{100357}{}{No @lex subNo@}
{100358}{}{Without @lex subWithout@}
{100359}{}{@lex descMenu@}	
{100360}{}{Choose your tool:}
{100361}{}{Apply disinfection:}
{100362}{}{Apply anesthetic:}
{100363}{}{You are ready to perform @lex operationHeal@. 
Expected success rate is: |0xFFFF00 @lex chances@|0x3CF800 %}
{100364}{}{extraction of an alien object from the patient}
{100365}{}{surgery on an open wound}
{100366}{}{[UNKNOWN STATE #@lex stageHeal@]}
{100367}{}{This part is already being healed.
}
{100368}{}{This part does not require healing.
}
{100370}{}{Choose healing method:
The approximate time of healing the limb is from @lex minMinutes@ to @lex maxMinutes@ minutes.}
{100371}{}{First aid menu:}
{100372}{}{eye wound}
{100373}{}{right arm}
{100374}{}{left arm}
{100375}{}{right leg}
{100376}{}{left leg}


#waterworks 100420 - 100470
{100421}{}{}
{100422}{}{@lex typeWaterworks@}
{100423}{}{Break @lex breakWaterworks@}
{100424}{}{Fix @lex fixWaterworks@}
{100425}{}{Drop @lex dropWaterworks@}
{100426}{}{Raise @lex raiseWaterworks@}
{100427}{}{Check @lex checkWaterworks@}
{100428}{}{Switch: @lex switchWaterworks@}
{100429}{}{Collect water}
{100430}{}{Drink}
{100435}{}{the bucket}
{100436}{}{well mechanism}
{100437}{}{pump}
{100438}{}{filter}
{100445}{}{Water @lex chargeWell@@lex bucketWell@@lex chainWell@@lex posBucketWell@}
{100446}{}{is clearely visible.}
{100447}{}{is not visible.}
{100448}{}{shimmers in the deep.}
{100449}{}{

The chain is unfolded.}
{100450}{}{

All is in order.}
{100451}{}{

The chain is in order.}
{100452}{}{

The bucket is missing.}
{100453}{}{

There is no chain to tie the bucket.}
{100454}{}{is fully unfold.}
{100455}{}{is amlost fully unfold.}
{100456}{}{partially unfold.}
{100457}{}{

Chain}
{100458}{}{The well is broken.}
{100460}{}{Waterpump № |0xFFFF00 @lex idWaterPump@ |0x3CF800 
Status: [ |0xFFFF00 @lex statusWaterPump@ |0x3CF800 ]
|0x3CF800 The water is|0xFF0000 @lex notFilterWaterPump@ |0x3CF800 being filtered. |0x3CF800 @lex isBrokenWaterPump@ @lex filterDirtyWaterPump@ 
|0x3CF800 Water stored: |0xFFFF00 @lex amountWaterPump@|0x3CF800 / |0xFFFF00 @lex maxAmountWaterPump@|0x3CF800  l. @lex generatorWaterPump@ 
}
{100464}{}{
The pump is broken.}
{100465}{}{
The filter is dirty.}
{100466}{}{
Connected to power generator.
Generator status: [ |0xFFFF00 @lex statusGeneratorWaterPump@|0x3CF800 ] }


#plants 100500 - 100550
{100501}{}{Water}
{100502}{}{Fertilize}
{100503}{}{Gather}
{100504}{}{Plant status:
The plant is|0xFFFF00 @lex notWaterinedPlant@ watered|0x3CF800 .
The plant is|0xFFFF00 @lex notFertilisedPlant@ fertilised|0x3CF800 .
The plant is @lex stagePlant@
Crop: @lex capacityPlant@
}
{100505}{}{Plant bed status: 
The Plant bed soil is|0xFFFF00 @lex soil_status@|0x3CF800 .
The Plant bed is|0xFFFF00 @lex notWatered@ watered|0x3CF800 .
The Plant bed is|0xFFFF00 @lex notFertilised@ fertilised|0x3CF800 .
}
{100506}{}{ripe enough to gather seeds.}
{100507}{}{ripe and can be gathered.}
{100508}{}{dead!}
{100509}{}{growing...}
{100510}{}{|0xFFFF00 You can't plant this!}
{100511}{}{|0xFFFF00 You are too far from a plant bed.}
{100512}{}{|0xFFFF00 You need to have empty soil.}
{100513}{}{|0xFFFF00 You need to plant it in some good soil.}
{100514}{}{planting hydro}
{100515}{}{|0xFFFF00 You need to plant it on a hydroponics farm.}
{100516}{}{planting Plant}
{100517}{}{|0xFFFF00 The soil must be watered and fertilized.}
{100518}{}{|0xFFFF00 You need to plant this in a Plant bed.}
{100519}{}{planting Seed}
{100520}{}{|0xFFFF00 There is nothing to gather yet!}
{100521}{}{|0xFFFF00 There is already enough fertilizer in there.}
{100522}{}{fertilizes the plant}
{100523}{}{|0xFFFF00 You have fertilized the plant.}
{100524}{}{|0xFFFF00 There is already enough water in there.}
{100525}{}{|0xFFFF00 You require to hold a water container.}
{100526}{}{|0xFFFF00 You have watered the plant.}
{100527}{}{waters the plant}
{100528}{}{|0xFFFF00 You require fertilizers.}
{100529}{}{|0xFFFF00  fertile}
{100530}{}{|0xFFFF00  barren}
{100531}{}{Fertilize Soil}
{100532}{}{|0xFFFF00 The soil lacks mineral fertilizer}
{100533}{}{|0xFFFF00 You require a mineral fertilizer for the soil.}

#vending 100600 - 100650
{100601}{}{@lex descriptionID@
Merchandise: @lex merchandise@
Put your |0xFFFFFF @lex wares@ |0x3CF800 into.
Balance: |0xFFFF00 @lex balance@|0x3CF800 $ @lex change@}
{100602}{}{[ Buy 1 pc. ]}
{100603}{}{[ Sell 1 pc. ]}
{100604}{}{Select item}
{100605}{}{[ NO ITEMS INSIDE ]}
{100606}{}{Set selling price}
{100607}{}{Set buying price}
{100608}{}{Mode: @lex mode@}
{100609}{}{Sell}
{100610}{}{Buy}
{100611}{}{Exchange}
{100612}{}{|0xFFFF00 @lex goods@|0x3CF800 , @lex lexCount@
@lex selling@ @lex buying@}
{100613}{}{|0xFF0000 EMPTY |0x3CF800 }
{100614}{}{|0xFFFF00 @lex count@ |0x3CF800 pc.}
{100615}{}{|0xFF0000 SOLD OUT |0x3CF800 }
{100616}{}{Price: |0xFFFF00 @lex sellingPrice@|0x3CF800 $}
{100617}{}{Purchace: |0xFFFF00 @lex byingPrice@|0x3CF800 $}
{100618}{}{|0xFF0000 NO CHANGE |0x3CF800 }
{100619}{}{money}
{100620}{}{goods}
{100621}{}{money or goods}
{100622}{}{Vending machine № |0xFFFF00 @lex ID@|0x3CF800 }
{100623}{}{@lex descriptionID@
Selected merchandise:
[ |0xFFFF00 @lex merch@ |0x3CF800 ]
Available: |0xFFFF00 @lex amount@ |0x3CF800 pc.
Choose desired merchandise and press |0xFFFF00 Confirm|0x3CF800  to complete the setup.}
{100624}{}{Change currency}


#terminal 100700 - 100800
{100700}{}{|0x3CF800 
State: [ |0xFFFF00 @lex statusTerminal@ |0x3CF800 ]}
{100701}{}{@lex descID@
@lex accessCard@@lex turrets@@lex fence@@lex noPassword@}
{100702}{}{GM MENU}
{100703}{}{Laser fence: @lex state@}
{100704}{}{Assign fence}
{100705}{}{Doors Control}
{100706}{}{Turret Auth}
{100707}{}{Turret Control}
{100708}{}{Open Reciever}
{100709}{}{Select Card}
{100710}{}{Fields Control}
{100711}{}{Assign Fields}
{100712}{}{Autodoc Control}
{100713}{}{Autodoc Install}
{100714}{}{Password Reset}
{100715}{}{Block Terminal}
{100716}{}{Unblock Terminal}
{100717}{}{End Session}
{100718}{}{|0xFFFF00 Terminal is blocked, please input the password!}
{100719}{}{Terminal № |0xFFFF00 @lex ID@|0x3CF800 }
{100720}{}{|0xFFFF00 No power!}
{100721}{}{|0xFFFF00 Attention, password not set! }
{100722}{}{|0x3CF800 Access card set: 
[ |0xFFFF00 @lex card@ |0x3CF800 ]
}
{100723}{}{|0x3CF800 Turrets enabled: [ |0xFFFF00 @lex amount@ |0x3CF800 ]
}
{100724}{}{|0x3CF800 Controlled laser fence:
[ |0xFFFF00 @lex fenceID@ |0x3CF800 ]

Fence status: |0xFFFF00 @lex fenceStatus@|0x3CF800 .
}
{100725}{}{Disable access cards}
{100726}{}{@lex descID@
|0x3CF800 Access card type: 
[ |0xFFFF00 @lex card@ |0x3CF800 ]
Choose an access card and press |0xFFFF00 Confirm |0x3CF800 to finish the setup.}
{100727}{}{@lex name@: @lex state@}
{100728}{}{@lex descID@
@lex emitters@
Assigned emitters: [ |0xFFFF00 @lex num@ |0x3CF800 ]}
{100729}{}{Compatible emitters found.}
{100730}{}{No emitters present on the grid.}
{100731}{}{Field Type: @lex fieldType@}
{100732}{}{Hard Field}
{100733}{}{Soft Field}
{100734}{}{|0xFFFF00 undefined}
{100735}{}{@lex descID@
@lex emitters@
Assigned emitters: [ |0xFFFF00 @lex assigned@ |0x3CF800 ]
Enabled emitters: [ |0xFFFF00 @lex enabled@ |0x3CF800 ]
Field type: [ |0xFFFF00 @lex type@ |0x3CF800 ]}
{100736}{}{@lex name@ is @lex state@}
{100737}{}{@lex descID@
@lex doors@
Enabled doors: [ |0xFFFF00 @lex enabled@ |0x3CF800 ]}
{100738}{}{No automatic doors present on the grid.}
{100739}{}{Autodoors found: [ |0xFFFF00 @lex amount@ |0x3CF800 ]}
{100740}{}{@lex descID@
Assigned doors: [ |0xFFFF00 @lex assigned@ |0x3CF800 ]
|0xFFFF00 Warning!|0x3CF800  Global setting overrides individual doors!

Select your command:}
{100741}{}{Blocked}
{100742}{}{Unblocked}
{100743}{}{@lex descID@
Door: [ |0xFFFF00 @lex name@ |0x3CF800 ]
Control initiated!
Door status: [ |0xFFFF00 @lex status@ |0x3CF800 ]
Door state: [ |0xFFFF00 @lex state@ |0x3CF800 ]
Select your command:}
{100744}{}{@lex name@ : @lex state@}
{100745}{}{Compatable turrets found: 
@lex turretsList@}
{100746}{}{№ @lex id@ - @lex state@
}
{100747}{}{authorised}
{100748}{}{unauthorised}
{100749}{}{busy}
{100750}{}{Assigned turrets: 
@lex turretsList@}
{100751}{}{status:}
{100752}{}{Access by:}
{100753}{}{GM menu for terminal options:}
{100754}{}{Powered}
{100755}{}{Fence Control}
{100756}{}{Force Field Control}
{100757}{}{Doors}
{100758}{}{Assign Doors}
{100759}{}{Turret Control}
{100760}{}{Access Cards}
{100761}{}{Autodoc Control}
{100762}{}{Password}
{100763}{}{@lex info@}
{100764}{}{Disable fence}
{100765}{}{Emitters found:
@lex emitters@
@lex group@
}
{100766}{}{|0xFFFF00 No emitters found!}
{100767}{}{|0x3CF800 Chosen group: [ |0xFFFF00 @lex IDgroup@ |0x3CF800 ]}
{100768}{}{Music Terminal}
{100769}{}{Set Music Frequency}
{100770}{}{You have set a new transmission frequency: |0xFFFF00 @lex digits@}
{100771}{}{Music frequency is set to: }
{100772}{}{Music Control}
{100773}{}{@lex descID@
@lex frequency@}
{100774}{}{Master Terminal}
{100775}{}{Assign terminals}
{100776}{}{@lex descID@
@lex terminals@}
{100777}{}{No terminals present on the grid.}
{100778}{}{Terminals found: [ |0xFFFF00 @lex amount@ |0x3CF800 ]}
{100779}{}{Mainframe control}
{100780}{}{Failed to connect with mainframe.}
{100781}{}{Hackability}
{100782}{}{Hack password}
{100783}{}{You can't hack this.}
{100784}{}{Select digit}
{100785}{}{Refresh datamess}
{100786}{}{Highlight @lex n@}
{100787}{}{Hack @lex n@ digit}
{100788}{}{@lex gminfo@
@lex state@}
{100789}{}{|0xFFFFFF Backup password: |0xFFFF00 @lex password@ |0xFFFFFF @lex percentage@|0x00FF00 % hints.}
{100790}{}{|0x888888      Selecting new digit..}
{100791}{}{|0x00FF00 Now hacking |0xFFFF00 @lex digit@ |0x00FF00 digit@lex hints@:
@lex datamess@}
{100792}{}{, hints on |0xFFFF00 @lex hintedN@|0x00FF00 @lex HintingCountText@}
{100793}{}{[|0xFFFFFF @lex hintedCount@|0x00FF00 ]}
{100794}{}{|0xFFFF00 You are required to hold a pip-boy for this.}
{100795}{}{|0xFFFF00 Console:
 |0xFFFFFF System Check... Done.
 Scanning Database... Done.
 Choose Data Section.}
{100796}{}{Copy Data}
{100797}{}{Read Data}
{100798}{}{|0xFFFF00 Copying data... Complete!}
{100799}{}{|0xFFFF00 You need to have holodisk in hands to copy data!}
{100800}{}{Database}

#autodoc 100800 - 100900
{100801}{}{Autodoc № |0xFFFF00 @lex Id@ |0x3CF800 @lex state@.}
{100802}{}{assigned}
{100803}{}{is chosen}
{100804}{}{Patient @lex state@}
{100805}{}{is free}
{100806}{}{locked}
{100807}{}{Heal}
{100808}{}{Cure Wound}
{100809}{}{Extraction}
{100810}{}{Blood transfusion}
{100811}{}{Reabilitation}
{100812}{}{Trauma}
{100813}{}{Reanimation}
{100814}{}{Body Modifications}
{100815}{}{Euthanasia}
{100816}{}{|0x3CF800 Autodoc № |0xFFFF00 @lex ID@ |0x3CF800 Biogel: |0xFFFF00 @lex biogel@ |0x3CF800 %
@lex warning@@lex autodocScan@}
{100817}{}{|0xFFFF00 Attention! Biogel absent! |0x3CF800 
}
{100818}{}{|0xFF0000 Terminal error! |0x3CF800 }
{100819}{}{|0xFF0000 Autodoc error! |0x3CF800 }
{100820}{}{|0xFF0000 You are in warp! |0x3CF800 }
{100821}{}{|0xFFFF00 Attention, procedure is undergoing! |0x3CF800 }
{100822}{}{|0xFFFF00 Bioscanner error! |0x3CF800 }
{100823}{}{|0x38F800 Procedure will end in: |0xFFFF00 @lex minute@|0x3CF800 :|0xFFFF00 @lex second@ |0x3CF800 }
{100824}{}{|0xFFFF00 Error! Alien object in auto doc! |0x3CF800 }
{100825}{}{|0xFFFF00 Error! Multiple bio signatures! |0x3CF800 }
{100826}{}{|0xFFFF00 Error! Non-human life forms inside! |0x3CF800 }
{100827}{}{|0xFFFF00 Error! The patient is not naked! |0x3CF800 }
{100828}{}{|0x3CF800 Patient: |0xFFFF00 @lex gender@|0x3CF800 .}
{100829}{}{|0xFF0000 Patient is dead! |0x3CF800 }
{100830}{}{|0xFFFF00 Patient in critical condition! |0x3CF800 }
{100831}{}{|0x3CF800 HP: |0xFFFF00 @lex HP@ |0x3CF800 / |0xFFFF00 @lex maxHP@ |0x3CF800 }
{100832}{}{|0x3CF800 Deviation: @lex color@@lex BaseHP@ |0x3CF800 HP.}
{100833}{}{|0xFFFF00 Drug addiction found! |0x3CF800 }
{100834}{}{|0xFFFF00 Jet effect found! |0x3CF800 }
{100835}{}{|0x3CF800 Alcohol level in blood: |0xFFFF00 @lex drunk@ |0x3CF800 %}
{100836}{}{|0x3CF800 Poisoning: |0xFFFF00 @lex poison@ |0x3CF800 %.}
{100837}{}{|0x3CF800 Radiation: |0xFFFF00 @lex radiation@ |0x3CF800 rad.}
{100838}{}{|0xFFFF00 Injures: |0x3CF800 @lex injures@}
{100839}{}{|0xFFFF00 Alien object found in the wound. |0x3CF800 }
{100840}{}{|0xFFFF00 Open wound found. |0x3CF800 }
{100841}{}{|0xFFFF00 Warning, patient is absent! |0x3CF800 }
{100842}{}{@lex strGender@ @lex stateHP@@lex baseHPState@@lex addictedState@@lex jettedState@@lex stateDrunk@@lex statePoison@@lex stateRadiation@@lex stateInjures@@lex stateBullet@@lex stateHeavy@}
{100843}{}{Strength @lex adjustment@}
{100844}{}{Perception @lex adjustment@}
{100845}{}{Endurance @lex adjustment@}
{100846}{}{Charisma @lex adjustment@}
{100847}{}{Agility @lex adjustment@}
{100848}{}{Labioplasty}
{100849}{}{Gender change}


#gm 101000 - 101500
{101001}{}{Main GM menu}
{101002}{}{Teleports}
{101003}{}{Storage}
{101004}{}{Map Spawners}
{101005}{}{GM Vision}
{101006}{}{GM Vision Modes}
{101007}{}{Rain Simulation}
{101008}{}{Input time in minutes}
{101009}{}{World rain}
{101010}{}{Input strength from 0 to 255}
{101011}{}{Map Rain}
{101012}{}{Music}
{101013}{}{Time}
{101014}{}{Factions}
{101015}{}{Refresh Mobs}
{101016}{}{Set all to:}
{101017}{}{Set mob count:}
{101018}{}{Animal Spawners}
{101019}{}{Monster Spawners}	
{101020}{}{Local map creature spawn menu}
{101021}{}{[@lex spawners@x@lex mobSpawns@] @lex nameMob@}
{101022}{}{Set number of mobs per spawner:}
{101023}{}{Set number of mobs:}
{101024}{}{Local map mob spawner: 
[ Spawn of X mobs ] Mob Type}
{101025}{}{Player logins}
{101026}{}{Player HP}
{101027}{}{ID over head}
{101028}{}{ID in chat}
{101029}{}{ID items in chat}	
{101030}{}{Hex coordinates}
{101031}{}{Radiation markers}
{101032}{}{Cursor sprites}
{101033}{}{Hear radios}
{101034}{}{Hear whisper}
{101035}{}{Info ~desc}
{101036}{}{Gas markers}
{101037}{}{Light markers}
{101038}{}{@lex gmInfo@: @lex status@}
{101039}{}{GM infro vision settings}
{101040}{}{Disable Sounds}	
{101041}{}{Action}
{101042}{}{Suspence}
{101043}{}{Cringe}
{101044}{}{SFX}
{101045}{}{Tunes}
{101046}{}{FOnline}
{101047}{}{NNM}
{101048}{}{Other}
{101049}{}{Local map music selection.}	
{101050}{}{ATTENTION, MUSIC TUNES OVERLAP!!!}
{101051}{}{Local Year}
{101052}{}{Reset Local Year}
{101053}{}{Global year}
{101054}{}{Input format: YYYY}
{101055}{}{Reset Global Year}
{101056}{}{Global Real Day: @lex state@}
{101057}{}{Time: @lex time@
Server time: |0xFFFF00 @lex timeMul@x @lex yearNow@|0x3CF800 -|0xFFFF00 @lex month@|0x3CF800 -|0xFFFF00 @lex day@|0x3CF800 
Current global year: |0xFFFF00 @lex yearGlobal@|0x3CF800 
Global year mod: |0xFFFF00 @lex yearShift@|0x3CF800 
Current local year: |0xFFFF00 @lex yearLocal@|0x3CF800 
Local mod: |0xFFFF00 @lex yearMod@|0x3CF800 }
{101058}{}{Actions with hex: Õ @lex X@ Y @lex Y@}
{101059}{}{NPC Spawn}
{101060}{}{Item Spawn}
{101061}{}{Item PID}
{101062}{}{Collect Items}
{101063}{}{Delete Items}
{101064}{}{Add Radiation}
{101065}{}{Add Gas}
{101066}{}{Teleport there}
{101067}{}{Control}
{101068}{}{Animal}
{101069}{}{Sentient}
{101070}{}{AI: @lex type@}
{101071}{}{Faction: @lex name@}
{101072}{}{ST_FACTION:}
{101073}{}{Agression: @lex state@}
{101074}{}{Passive}
{101075}{}{Active}
{101076}{}{Team ID: @lex id@}
{101077}{}{TEAM ID:}
{101078}{}{PID: @lex value@}
{101079}{}{PID NPC:}
{101080}{}{Bonus HP: @lex value@}
{101081}{}{Bonus HP:}
{101082}{}{Bonus Melee Damage: @lex value@}
{101083}{}{Bonus Melee Damage:}
{101084}{}{Skill bonus: @lex value@}
{101085}{}{Combat Skill bonus:}
{101086}{}{Select NPC}
{101087}{}{@lex name@}
{101088}{}{Mob spawn menu. Bonuses are cumulative to critter prototype parameters. Mob selection will assign the Pid.}
{101089}{}{Rat}
{101090}{}{Manti}
{101091}{}{Ant}
{101092}{}{Ant-lion}
{101093}{}{Pigrat}
{101094}{}{Molerat} 
{101095}{}{Molerat-Mutant} 
{101096}{}{Silver Gecko} 
{101097}{}{Golden Gecko} 
{101098}{}{Cave Gecko}
{101099}{}{Dog} 
{101100}{}{Wolf} 
{101101}{}{Rad-Scorpion} 
{101102}{}{B. Rad-Scorpion} 
{101103}{}{Yao} 
{101104}{}{Cave Rad-Scorpion} 
{101105}{}{Brahmin}
{101106}{}{You have spawned: @lex name@}
{101107}{}{Select a mob, it will be spawned immediately.}
{101108}{}{You have set: |0xFFFF00 @lex mob@ |0x3CF800 spawning at |0xFFFF00 @lex val@|0x3CF800 .}
{101109}{}{Evil-plant}
{101110}{}{Alien}
{101111}{}{Deathclaw}
{101112}{}{Crock}
{101113}{}{Shadow Crock}
{101114}{}{Firegecko}
{101115}{}{Beast}
{101116}{}{Centaur}
{101117}{}{Floater}
{101118}{}{Swamplurker}
{101119}{}{Wasp}
{101120}{}{Roach}
{101121}{}{Wild Ghoul}
{101122}{}{Millepede}
{101123}{}{Lavash}
{101124}{}{Spider}
{101125}{}{Coyote}
{101126}{}{Mode START}
{101127}{}{Mode Adventure}
{101128}{}{Mode SURVIVAL}
{101129}{}{Mode TEST}
{101130}{}{mode error}
{101131}{}{Parameters}
{101132}{}{Moderation}
{101133}{}{Inventory}
{101134}{}{Bonuses}
{101135}{}{Effects}
{101136}{}{Raise/KO}
{101137}{}{Skill Roll}
{101138}{}{Give Item PID}
{101139}{}{PSY Modes}
{101140}{}{Deaggro NPC!}
{101141}{}{0 Mode START}
{101142}{}{1 Mode Adventure}
{101143}{}{2 Mode SURVIVAL}
{101144}{}{3 Mode TEST}
{101145}{}{SPECIAL}
{101146}{}{SKILLS}
{101147}{}{Traumas}
{101148}{}{Modes}
{101149}{}{Traits}
{101150}{}{Skin/Bodytype}
{101151}{}{Faction: @lex name@}
{101152}{}{Extra Params}
{101153}{}{Lexems}
{101154}{}{Black Screen 30s}
{101155}{}{White Screen 30s}
{101156}{}{Red Screen 30s}
{101157}{}{Black Screen 25s}
{101158}{}{White Screen 25s}
{101159}{}{Red Screen 25s}
{101160}{}{Refresh timouts}
{101161}{}{Target @lex state@}
{101162}{}{Can't get up}
{101163}{}{Will get up soon}
{101164}{}{Input PID:}
{101165}{}{Current: - @lex value@}
{101166}{}{0 - No}
{101167}{}{1 - Animal Master}
{101168}{}{2 - Faceless}
{101169}{}{3 - Voice}
{101170}{}{4 - Mimic}
{101171}{}{Player aggro removed}
{101172}{}{Mob HP %}
{101173}{}{Mob list}
{101174}{}{Homegex set, 'return home' on.}
{101175}{}{@lex name@ is not registered yet, let the player get activated by NPC first!}
{101176}{}{|0xFFFF00 @lex name@ |0x00FF00 cleared.}
{101177}{}{Group #ID}
{101178}{}{Spawn NPC}
{101179}{}{Select Humanoid NPC}
{101180}{}{Set Map Time}
{101181}{}{Static time mode: @lex mode@}
{101182}{}{Reset time mod}
{101183}{}{|0xFFFF00 @lex global@ |0xAAAAAA @lex map@ |0x00FF00 @lex delta@}
{101184}{}{static}
{101185}{}{Amount: @lex amount@}
{101186}{}{RiverdalePA}
{101187}{}{Players}
{101188}{}{SK_TLJ}
{101189}{}{AoE Blind}
{101190}{}{Acid Rain}
{101191}{}{Ore Zone}
{101192}{}{Ore Markers}
{101193}{}{Junk Zone}
{101194}{}{Junk Markers}
{101195}{}{Deaggro Map}
{101196}{}{Mob Spawner}
{101197}{}{FORMATION}

# GM menu NPC groups
# Mobs
{101200}{}{Rats}
{101201}{}{Mantis}
{101202}{}{Ants}
{101203}{}{Pigrats & Molerats}
{101204}{}{Geckos}
{101205}{}{Dogs & Wolves}
{101206}{}{Scorpions}
{101207}{}{Brahmins & Lavash}
{101208}{}{Predatory Plants}
{101209}{}{Yao-guai}
{101210}{}{Aliens}
{101211}{}{Deathclaws}
{101212}{}{Crocks}
{101213}{}{Centaurs}
{101214}{}{Floaters}
{101215}{}{Swamplurkers}
{101216}{}{Other Insects}

# Humanoids
{101217}{}{Wild Ghouls}
{101218}{}{Super Mutants}
{101219}{}{NCR Soldiers}
{101220}{}{Rangers}
{101221}{}{BoS Soldiers}
{101222}{}{Enclave Soldiers}
{101223}{}{Vault City Soldiers}
{101224}{}{Renegade Soldiers}
{101225}{}{Vault Dwellers}
{101226}{}{Town Dwellers}
{101227}{}{Bounty Hunters}
{101228}{}{Tribals}
{101229}{}{Canibals}
{101230}{}{Bandits}
{101231}{}{Mercs}
{101232}{}{Slavers}
{101233}{}{Slaves}
{101234}{}{Homeless}

#handcuffs 101500 - 101550
{101501}{}{Remote is active.

Awaiting command...}
{101502}{}{Collar Control}
{101503}{}{Collar Array}
{101504}{}{Set Frequency}
{101505}{}{Collar @lex idCollar@}
{101506}{}{Punish}
{101507}{}{Wound}
{101508}{}{Maim}
{101509}{}{Kill}
{101510}{}{Release}
{101511}{}{: Disabled}
{101512}{}{: Active}
{101513}{}{Remote |0xFFFF00 @lex idRemote@ |0x3CF800    
 
@lex stateCollar@ collars: [|0xFFFF00 @lex num@|0x3CF800 ]}
{101514}{}{Active}
{101515}{}{Available}
{101516}{}{Collar |0xFFFF00 @lex idCollar@ |0x3CF800 }
{101517}{}{Input radio frequency}
{101518}{}{You have set radio frequency to: |0xFFFF00 @lex digits@|0x3CF800 .}
{101519}{}{|0xFFFF00 Your skill is too low to change the password!}

{101550}{}{Frequency is displayed: @lex frequency@|0x3CF800 .}

#map_start 101600 - 101650
{101601}{}{		  Welcome to the game!}
{101602}{}{Information (Website)}
{101603}{}{Begin Game}
{101604}{}{Change Skin}
{101605}{}{Change Gender}
{101606}{}{Arena1 @lex playersCount@}
{101607}{}{Arena2 @lex playersCount@}
{101608}{}{Players: [ @lex count@ ]}
{101609}{}{Arena Alpha Gameplay.

Select arena for teleportation. This action is irreversible.

 You will be given max level!}
 
{101610}{}{Start game terminal.

Here you can adjust the skin and gender of your character.

Choose Begin Game to start!}

{101611}{}{Teleport terminal.

Select the starting location!}
{101612}{}{Change Height}
{101613}{}{Height tuning:
Current Height: |0xFFFF00 @lex crHeight@|0x3CF800  cm.}

#recorder 101650 - 101669
{101651}{}{Tape recorder.
@lex batteryCharge@ |0x3CF800  
Sound radius: @lex volume@}
{101652}{}{Insert a battery}
{101653}{}{Open the cover}
{101654}{}{Battery charge: |0xFFFF00 @lex charge@ }
{101655}{}{|0xFFFF00 Battery is charged!}
{101656}{}{|0xFFFF00 You can only put a tape inside!}

#geiger 101670 - 101700
#99510 & 99511 - on/off
{101670}{}{Geiger counter.
Status: [ |0xFFFF00 @lex geigerState@ |0x3CF800 ]
Charge level: [ |0xFFFF00 @lex geigerCurCharge@ |0x3CF800 |0xFFFF00 @lex geigerMaxCharge@ |0x3CF800 ]
Radiation: [ |0xFFFF00 @lex crRadLvl@ |0x3CF800 ]
Local radiation: [ |0xFFFF00 @lex locRadLvl@ |0x3CF800 ]
}
{101671}{}{Many strange letters and numbers on the smooth glass of this device.}
{101672}{}{Strange button} # stupid on/off
{101673}{}{Measure rad. level}
{101674}{}{Wave the device}
{101675}{}{Scan yourself}
{101676}{}{Rub the device}
{101677}{}{Charge the device}
{101678}{}{Insert something}
{101679}{}{Super mode}
{101680}{}{Pretty button}
{101681}{}{Normal mode}
{101682}{}{Big button}
#geiger charge menu 101684 - 101691
{101684}{}{Geiger counter.
Status: [ |0xFFFF00 @lex geigerState@ |0x3CF800 ]
Charge level: |0xFFFF00 @lex geigerCurCharge@ |0x3CF800 |0xFFFF00 @lex geigerMaxCharge@ |0x3CF800
Select a charging method.
}
{101685}{}{Many strange letters and numbers on the smooth glass of this device. More letters have appeared below.}
{101686}{}{Bush energy cell}
{101687}{}{Yellow device}
{101688}{}{Energy cell}
{101689}{}{Red device}
{101690}{}{Nuclear microreactor}
{101691}{}{Large yellow device}
{101695}{}{You lack intelligence}
{101696}{}{You lack the knowledge to do this}
{101697}{}{It seems you've damaged this strange thing with your clumsy actions}
{101698}{}{Thanks to your knowledge, you've increased the device's runtime}
{101699}{}{You've increased the power and speed of the device. The battery charge will deplete faster}

{101700}{}{Database № |0xFFFF00 @lex Id@ |0x3CF800 @lex state@.}
{101701}{}{Database Install}

# Skill rolls
{102003}{}{SMALL GUNS}
{102013}{}{MEDIUM GUNS}
{102023}{}{BIG GUNS}
{102033}{}{UNARMED COMBAT}
{102043}{}{MELEE WEAPONS}
{102053}{}{THROWING}
{102063}{}{FIRST AID}
{102073}{}{DOCTOR}
{102083}{}{SNEAK}
{102093}{}{LOCKPICK}
{102103}{}{STEALING}
{102113}{}{TRAPS}
{102123}{}{SCIENCE}
{102133}{}{REPAIR}
{102143}{}{CRAFT}
{102153}{}{BARTER}
{102163}{}{-}
{102173}{}{-}
{102183}{}{MINING}
{102193}{}{CHOPPING}
{102203}{}{SCAVENGING}
{102213}{}{HUNTING}
{102223}{}{FISHING}
{102233}{}{FARMING}
{102243}{}{COOKING}
{102253}{}{HERBALISM}

# Headbag
{102254}{}{puts bag on your head}
{102255}{}{puts bag on the head}
{102256}{}{|0xFFFF00 You put bag on your head}
{102257}{}{|0xFFFF00 Somebody puts bag on your head}
{102258}{}{|0xFFFF00 Somebody removed bag from your head}
{102259}{}{removes bag from your head}
{102260}{}{removes bag}


