#
# Skill raise
#
{15}{}{Skill @lex skill@ is increased on @lex value@ points}

#
# Generic messages
#

{510}{}{Yes} # Magic ball
{511}{}{No} # Magic ball
{520}{}{Powders nose} # Cosmetic
{530}{}{. Smokes .oO} # Cigarettes

#
# Casino
#

{2000}{}{*Ring-a-ling*}
{2000}{}{*Zzzzzzz*}
{2000}{}{*Bing*}
{2000}{}{*Dingity-ding*}
{2000}{}{*Ding*}
{2000}{}{*Kaa-ching*}
{2001}{}{The machine is empty.}

{6500}{}{Stop it, my son, it's useless.}
{6501}{}{There is a lot of filth in you.}
{6502}{}{I understand your pain. Calm down, child.}
{6503}{}{Anger destroys you, don't go on about it.}
{6504}{}{It's not an easy path for you, you're embittered.}
{6505}{}{Your anger is unfair. Stop it now.}

{6506}{}{It's not time yet, you can't pass.}
{6507}{}{Patience, my son, patience.}
{6508}{}{Your time hasn't come yet. I can't let you pass.}
{6509}{}{Don't rush there, you have a whole eternity ahead of you.}
{6510}{}{You've lived your whole life in a hurry, take a break at least for now.}

{7001}{}{zero}
{7002}{}{double zero}
{7003}{}{red}
{7004}{}{black}
{7005}{}{number }
{7006}{}{Your winnings: }
{7007}{}{Invalid number}
{7008}{}{Incorrect bid}
{7009}{}{Number accepted}
{7010}{}{Bid accepted}
{7011}{}{Current bid: @lex betsize@}
{7012}{}{You bet on the numbers:}
{7013}{}{@lex result@}
{7014}{}{Make your bet}

#russian roullet
{9000}{}{he lost at "Russian Roulette"@@his brains got blown out@@today is not his lucky day@@he shouldn't have agreed to this@@he splattered everything around with his blood@@he screamed and pulled the trigger, the scream was cut off...@@he shot himself@@he did not hesitate to splatter the area with his brains}
{9001}{}{the gun clicked, but nothing happens@@he almost shit himself, but nothing happened...@@he screamed as he pulled the trigger, but everything turned out ok!@@Fortune smiled to him!@@he won at "Russian Roulette"@@LUCKY!@@he held his breath and pulled the trigger, but everything went fine}
{9002}{}{she lost at "Russian Roulette"@@she took her brains out@@today is not her day@@she shouldn't have agreed to this@@she poured her blood all over the place@@she screamed as she pulled the trigger, but the scream was cut off...@@she shot herself@@without hesitation, she splattered the area with her brains}
{9003}{}{the gun clicked, but nothing happened@@she almost shit herself, but nothing happened...@@she screamed and pulled the trigger, but everything turned out ok!@@fortune smiled on her@@she won at the "Russian Roulette"@@LUCKY@@she held her breath and pulled the trigger, but everything went fine}

#Resource Gathering
{9004}{}{picks a plant}
{9005}{}{|0xFFFF00 You haven't found anything usefull.}
{9006}{}{You've collected:}
{9007}{}{|0x3CF800 .}
{9008}{}{|0xFFFF00 You've picked the plant during a wrong growth stage and decided to dump it away.}

#Grid_to_global_warning
{15000}{}{You are getting scared.}
{15000}{}{You have nowhere else to go.}
{15000}{}{You see only dead wasteland in front of you and understand that going there, will condemn you to certain death. You have no choice but to continue your miserable existence here, fighting for a piece of meat with other people and animals.}
{15000}{}{There is no life there.}
{15000}{}{There is nothing waiting for you there.}

# lifts:
# {2GG00} is key card item proto name from data/ItemNames.lst where GG is lifts group
# {2GGFF} is floor name where GG is lifts group, FF is floor

{20100}{}{PID_V15_KEYCARD}
{20101}{}{4 - Control room}
{20102}{}{3 - Meeting room}
{20103}{}{2 - Barracks}
{20104}{}{1 - Dining Room}
{20105}{}{0 - Galley}

{20201}{}{1 - Trading}
{20202}{}{2 - Bar}
{20203}{}{3 - Industrial area}
{20204}{}{4 - Hole}

{20301}{}{4 - Suites}
{20302}{}{3 - Business rooms}
{20303}{}{2 - Economy rooms}
{20304}{}{1 - Club}
{20305}{}{0 - Lobby}

{20400}{}{PID_SECURITY_CARD}
{20401}{}{1 - Surface}
{20402}{}{2 - Bunker}
{20403}{}{3 - Technical level}

{20501}{}{0 - Surface}
{20502}{}{1 - Chemical Plant}

{20601}{}{1 - First Floor}
{20602}{}{0 - Lobby}

{20701}{}{0 - Lobby}